export default {
  en: {
    type: "commonLabels",

    module: "Sports Portal",
    // dashboard: 'PCMC Dashboard',
    dashboard: "Pimpri-Chinchwad Municipal Corporation Dashboard",
    master: "Masters",
    transaction: "Transactions",
    report: "Reports",
    masterPath: "Sports Portal / Master",
    transactionPath: "Sports Portal / Transaction ",
    reportPath: "Sports Portal / Reports ",

    type: "master",
    // master: "Masters",
    masterPath: "Sports Portal/ Master",
    master: "Masters",

    //breadcrum

    facilityNamePath: "Sports Portal/ Master/ Facility Name Master",
    venuePath: "Sports Portal/ Master / Venue Master",
    bookingTimePath: "Sports Portal/ Master / Booking Time Master",
    facilityTypePath: "Sports Portal/ Master / Facility Type Master",

    //label title
    facilityNameMaster: "Facility Sub-Type Master",
    venueMaster: "Facility Venue Master",
    bookingTimeMaster: "Booking Time Slot Master",
    facilityTypeMaster: "Facility Type Master",

    //Facility Name Master
    facilityNameId: "Facility Name ID",
    facilityTypeId: "Facility Type ID",
    zone: "Zone",
    ward: "Ward",
    venueId: "Venue ID",
    department: "Department",
    subDepartment: "Sub Department",
    facilityType: "Facility Type",
    facilityName: "Facility Sub-Type Name",
    gisCode: "GIS Code",
    remark: "Remark",
    venue: "Facility Venue",
    date: "Date",
    fromBookingTime: "From Booking Time",
    toBookingTime: "To Booking Time",
    capacity: "Capacity/TotalMember",

    //other labels

    //Remarks

    //buttons
    add: "Add",
    save: "Save",
    update: "Update",
    clear: "Clear",
    exit: "Exit",
    back: "Back",
    saveAndNext: "Save & Next",
    finish: "Finish",

    type: "transaction",

    transaction: "Transaction",

    transactionPath: "Sports Portal / Transactions ",

    //titles
    sportBooking: "Sport Booking",
    check: "Check Availability Status ",
    swimmingPool: "Swimming Pool",

    //breadcrum

    //titles
    bookingDetails: "Booking Details",
    personalGroupDetails: "Personal Group Details",
    personalDetails: "Personal Details",
    aadharAuthenticationDetails: "Aadhar Authentication Details",
    eCSDetails: "ECS Details",
    documentsUpload: "Documents Upload",

    //other labels
    documentUpload: "Document Upload",
    bookingDetails: "Booking Details",
    eCSDetails: "ECS Details",
    aadharAuthentication: "Aadhar Authentication",

    fromDate: "Date(From)",
    formDateTime: "Form Date Time",
    toDateTime: "To Date Time",
    toDate: "Date(To)",
    ward: "Ward",
    subDepartment: "Sub Department",
    bookingRegistrationId: "Booking Registration Id",
    applicationDate: "Application Date",
    bookingType: "Booking Type",
    zone: "Zone",
    department: "Department",
    facilityType: "Facility Type",
    facilityName: "Facility Sub-Type Name",
    venue: "Venue",
    totalGroupMember: "Total Group Member",
    groupDetails: "Group Details",
    title: "Title",
    firstName: "First Name",
    middleName: "Middle Name",
    lastName: "Last Name",
    gender: "Gender",
    dateOfBirth: "Date Of Birth",
    age: "Age",
    mobileNo: "Mobile No",
    aadharNo: "Aadhar No",
    emailAddress: "Email Address",
    currentAddress: "Current Address",
    permanentAddress: "Permanent Address",
    cityName: "City Name",
    state: "State",
    pinCode: "Pin Code",
    bankName: "Bank Name",
    branchName: "Branch Name",
    bankAccountHolderName: "Bank Account Holder Name",
    bankAccountNo: "Bank Account No",
    ifscCode: "IFSC Code",
    bankAddress: "Bank Address",
    aadharCard: "Aadhar Card",
    panCard: "Pan Card",
    otherDocumentPhoto: "Other Document Photo",
    checkBox: "Permanent Address as the Correspondence Address",
    purposeOfBooking: "Purpose Of Booking",
    bookingPersonDetails: "Booking Person Details",
    slots: "Slots",
    timePeriod: "Time Period",
    sendOtp: "SEND OTP",
    attachFile: "Attach File",
    viewImage: "VIEW IMAGE",
    srNo: "Sr. No",
    actions: "Actions",

    //buttons
    add: "Add",
    save: "Save",
    update: "Update",
    clear: "Clear",
    exit: "Exit",
    back: "Back",
    saveAndNext: "Save & Next",
    finish: "Finish",

    type: "report",

    reports: "Reports",

    reportsPath: "Sports Portal / Reports ",
  },
  mr: {
    type: "commonLabels",

    module: "क्रीडा विभाग",
    // dashboard: 'डॅशबोर्ड',
    dashboard: "पिंपरी-चिंचवड महानगरपालिका डॅशबोर्ड",
    master: "मास्टर्स",
    transaction: "व्यवहार",
    report: "अहवाल",
    masterPath: "क्रीडा विभाग/ मास्टर्स ",
    transactionPath: "कायदेशीर प्रकरण/ व्यवहार ",
    reportPath: "कायदेशीर प्रकरण/ अहवाल ",

    type: "master",

    master: "मास्टर्स",
    // transaction: "व्यवहार",
    report: "अहवाल",
    masterPath: "क्रीडा विभाग/ मास्टर ",
    // transactionPath: "क्रीडा विभाग/ व्यवहार ",

    //breadcrum

    facilityNamePath: "क्रीडा विभाग/ मास्टर्स / सुविधा उप-प्रकार मास्टर",
    venuePath: "क्रीडा विभाग/ मास्टर्स / ठिकाण मास्टर ",
    bookingTimePath: "क्रीडा विभाग/ मास्टर्स / बुकिंग वेळ मास्टर्स",
    facilityTypePath: "क्रीडा विभाग/ मास्टर्स / सुविधा प्रकार मास्टर",

    //titles
    facilityNameMaster: "सुविधा उप-प्रकार मास्टर",
    facilityTypeMaster: "सुविधा प्रकार मास्टर",
    venueMaster: "सुविधा ठिकाण मास्टर",
    bookingTimeMaster: "बुकिंग वेळ स्लॉट मास्टर",

    //labels
    facilityNameId: "सुविधा उपप्रकार आयडी",
    facilityTypeId: "सुविधा प्रकार आयडी",
    venueId: "ठिकाण आयडी",
    zone: "झोन",
    ward: "प्रभाग",
    subDepartment: "उप विभाग",
    department: "विभाग",
    facilityType: "सुविधा प्रकार",
    facilityName: "सुविधा उपप्रकार नाव",
    gisCode: "GIS कोड",
    remark: "शेरा",
    venue: "सुविधा ठिकाण",
    date: "तारीख",
    fromBookingTime: "(पासून) बुकिंगची वेळ",
    toBookingTime: "(ते) बुकिंगची वेळ",
    capacity: "क्षमता/एकूण सदस्य",

    cityOrVillage: "शहर / गाव",
    pincode: "पिनकोड",
    area: "क्षेत्राचे नाव",
    name: "नाव",
    mobile: "मोबाईल नं.",
    phone: "दूरध्वनी नं.",
    email: "इलेक्ट्रॉनिक संदेश",
    aadharNo: "आधार नं.",
    panNo: "पॅन नं.",
    advocateCreation: "वकिल यशस्वीपणे तयार केला",
    advocateDetails: "वकील तपशील",
    bankDetails: "बँक तपशील",
    documentUpload: "दस्तऐवज अपलोड",
    title: "शीर्षक *",
    fname: "पहिले नाव *",
    mname: "मधले  नाव *",
    lname: "शेवटचे नाव *",
    advocateCategory: "वकील श्रेणी *",
    nameOfBarCouncil: "वकिलांचे मंडळचे प्रमाणपत्र परिषदचे नाव *",
    remarks: "टिप्पणी *",
    bankName: "बँकेचे नाव *",
    branchName: "शाखेचे नाव *",
    accountNo: "खाता क्रमांक *",
    bankIFSC: "बँक IFSC कोड *",
    bankMICR: "बँक MICR कोड *",
    application: "अर्ज:",
    aadharCard: "आधार कार्ड:",
    panCard: "पॅन कार्ड:",
    barCouncilCertificate: "वकिलांचे मंडळचे प्रमाणपत्र:",
    bankPassbook: "बँक पासबुक:",
    subType: "उप-प्रकार",
    slots: "स्लॉट",
    timePeriod: "कालावधी",

    attachFile: "फाईल जोडा",
    srNo: "अनुक्रमांक",
    actions: "क्रिया ",

    //Remarks
    selectDate: "कृपया तारीख निवडा",
    selectTitle: "कृपया शीर्षक निवडा",
    enterFName: "कृपया पहिले नाव भरा ",
    enterMName: "कृपया मधले  नाव भरा ",
    enterLName: "कृपया शेवटचे नाव भरा ",
    selectAdvocateCategory: "कृपया वकील श्रेणी निवडा",
    enterCouncilName: "कृपया वकिलांचे मंडळचे प्रमाणपत्र परिषदचे नाव भरा",
    enterArea: "कृपया क्षेत्राचे नाव भरा ",
    enterRoadName: "कृपया रस्त्याचे नाव भरा ",
    enterLandmark: "कृपया  महत्त्वाची खूण भरा",
    enterCity: "कृपया  शहराचे / गावाचे नाव भरा ",
    enterPinCode: "कृपया पिनकोड भरा",
    enterPhoneNo: "कृपया दूरध्वनी नं. भरा",
    enterMobileNo: "कृपया मोबाईल नं. भरा",
    enterEmailAddress: "कृपया इलेक्ट्रॉनिक संदेश भरा",
    enteraadhaarNo: "कृपया आधार नं. भरा",
    enterpanNo: "कृपया पॅन नं. भरा",
    // enterRemarks: 'कृपया टिप्पणी. भरा',
    enterRemarks: "कृपया टिप्पणी. द्या",

    //buttons
    add: "जोडा",
    save: "जतन करा",
    update: "अद्यायावत करा",
    clear: "रिक्त",
    exit: "बाहेर पडा",
    back: "मागे",
    saveAndNext: "जतन करा आणि पुढे",
    finish: "समाप्त",

    type: "transaction",

    transaction: "व्यवहार",
    transactionPath: "कायदेशीर प्रकरण/ व्यवहार ",

    //breadcrum

    //titles
    sportBooking: "क्रीडा बुकिंग",
    check: "उपलब्धता स्थिती तपासा",
    swimmingPool: "जलतरण तलाव",

    //titles
    bookingDetails: "नोंदणी तपशील",
    personalGroupDetails: "वैयक्तिक गट तपशील",
    personalDetails: "वैयक्तिक माहिती",
    aadharAuthentication: "आधार प्रमाणीकरण",
    aadharAuthenticationDetails: "आधार प्रमाणीकरण तपशील",
    eCSDetails: "ECS तपशील",
    documentsUpload: "दस्तऐवज अपलोड करा",

    //other labels
    fromDate: "तारीख (पासून)",
    toDate: "तारीख (ते)",
    formDateTime: "(पासून) तारीख आणि वेळ",
    toDateTime: "(ते) तारीख आणि वेळ",
    bookingRegistrationId: "बुकिंग नोंदणी आयडी",
    documentUpload: "दस्तऐवज अपलोड",
    applicationDate: "अर्जाची तारीख",
    bookingType: "बुकिंग प्रकार",
    zone: "झोन",
    ward: "प्रभाग",
    subDepartment: "उप विभाग",
    department: "विभाग ",
    facilityType: "सुविधा प्रकार",
    facilityName: "सुविधेचे उपप्रकार",
    venue: "सुविधा ठिकाण",
    totalGroupMember: "एकूण गट सदस्य",
    groupDetails: "गट तपशील",
    title: "शीर्षक",
    firstName: "पहिले नाव",
    middleName: "मधले नाव",
    lastName: "आडनाव",
    gender: "लिंग",
    dateOfBirth: "जन्मतारीख",
    age: "वय",
    mobileNo: "मोबाईल क्र",
    aadharNo: "आधार क्र",
    emailAddress: "ईमेल आयडी",
    currentAddress: "सध्याचा पत्ता",
    permanentAddress: "कायमचा पत्ता",
    cityName: "शहराचे नाव",
    state: "राज्य",
    pinCode: "पिन कोड",
    bankName: "बँकेचे नाव",
    branchName: "शाखेचे नाव",
    bankAccountHolderName: "बँक खातेधारकाचे नाव",
    bankAccountNo: "बँक खाते क्र",
    ifscCode: "IFSC कोड",
    bankAddress: "बँकेचा पत्ता",
    aadharCard: "आधार कार्ड",
    panCard: "पॅन कार्ड",
    otherDocumentPhoto: "इतर दस्तऐवज फोटो",
    checkBox: "पत्रव्यवहाराचा पत्ता म्हणून कायमचा पत्ता",
    purposeOfBooking: "बुकिंगचा उद्देश",
    bookingPersonDetails: "बुकिंग व्यक्ती तपशील",

    //buttons
    add: "जोडा",
    save: "जतन करा",
    update: "अद्यायावत करा",
    clear: "रिक्त",
    exit: "बाहेर पडा",
    back: "मागे",
    saveAndNext: "जतन करा आणि पुढे",
    finish: "समाप्त",
  },
};
