export default {
  en: [
    {
      type: "commonLabels",

      // fireBridageSystem: "Fire Brigade System",
      module: "Fire Brigade System",
      // dashboard: 'PCMC Dashboard',
      dashboard: "Pimpri-Chinchwad Municipal Corporation Dashboard",
      masters: "Masters",
      transactions: "Transactions",
      reports: "Reports",
      masterPath: "FIRE BRIGADE SYSTEM / masters",
      transactionPath: "Legal Case / Transaction ",
      reportPath: "Legal Case / Report ",
    },
    {
      type: "masters",
      masters: "Masters",
      masterPath: "FIRE BRIGADE SYSTEM / masters",

      //breadcrum
      typeOfBuildingPath: "FIRE BRIGADE SYSTEM / masters / Type Of Building ",
      purposeOfBuildingPath:
        "FIRE BRIGADE SYSTEM / masters / Purpose Of Building ",
      typeOfNocPath: "/FireBrigadeSystem/masters/typeOfNoc",
      usageTypeMasterPath: "FIRE BRIGADE SYSTEM / masters / Usage Type Master",
      typeOfBusinessPath: "FIRE BRIGADE SYSTEM / masters / Type Of Business",
      vardiTypeMasterPath: "FIRE BRIGADE SYSTEM / masters / Vardi Type Master",
      fireStationDetailsPath:
        "FIRE BRIGADE SYSTEM / masters / Fire Station Details",
      employeeShiftMasterPath:
        "FIRE BRIGADE SYSTEM / masters / Employee Shift Master",
      vehicleDetailsPath: "FIRE BRIGADE SYSTEM / masters / Vehicle Details",

      //label title
      typeOfBuilding: "Type Of Building",
      purposeOfBuilding: "Purpose Of Building",
      typeOfNoc: "Type Of NOC",
      usageTypeMaster: "Usage Type Master",
      typeOfBusiness: "Type Of Business",
      vardiTypeMaster: "Vardi Type Master",
      fireStationDetails: "Fire Station Details",
      employeeShiftMaster: "Employee Shift Master",
      vehicleDetails: "Vehicle Details",

      //other labels
      typeOfBuildingEn: "Type Of Building (In English)",
      typeOfBuildingMr: "Type Of Building (In Marathi)",
      gISIDEn: "GIS ID (In English)",
      gISIDMr: "GIS ID (In Marathi)",
      fireStationNameEn: "Fire Station Name (In English)",
      fireStationNameMr: "Fire Station Name (In Marathi)",
      addressEn: "Address (In English)",
      addressMr: "Address (In Marathi)",
      vTSSystemIDEn: "VTS System ID (In English)",
      vTSSystemIDMr: "VTS System ID (In Marathi)",
      gPSDeviceIdEn: "GPS Device ID (In English)",
      gPSDeviceIdMr: "GPS Device ID (In Marathi)",
      vehicleTypeEn: "Vehicle Type (In English)",
      vehicleTypeMr: "Vehicle Type (In Marathi)",
      vehicleNumberEn: "Vehicle Number ID (In English)",
      vehicleNumberMr: "Vehicle Number (In Marathi)",
      vardiNameEn: "Vardi Name (In English)",
      vardiNameMr: "Vardi Name (In Marathi)",
      buildingPurposeEn: "Building Purpose (In English)",
      buildingPurposeMr: "Building Purpose  (In Marathi)",
      nOCNameEn: "NOC Name (In English)",
      nOCNameMr: "NOC Name (In Marathi)",
      nameOfUsageEn: "Vardi Name (In English)",
      nameOfUsageMr: "Vardi Name (In Marathi)",
      typeOfBusinessEn: "Vardi Name (In English)",
      typeOfBusinessMr: "Vardi Name (In Marathi)",

      //Remarks
      selectDate: "Please select a date",
      selectTitle: "Please select a title",
      enterFName: "Please enter first name ",
      enterMName: "Please enter middle name ",
      enterLName: "Please enter last name ",
      selectAdvocateCategory: "Please select a category",
      enterCouncilName: "Please enter council name",
      enterArea: "Please enter area ",
      enterRoadName: "Please enter road name ",
      enterLandmark: "Please enter a landmark ",
      enterCity: "Please enter a city ",
      enterPinCode: "Please enter a pincode ",
      enterPhoneNo: "Please enter a phone no. ",
      enterMobileNo: "Please enter a mobile no. ",
      enterEmailAddress: "Please enter an e-mail. ",
      enteraadhaarNo: "Please enter an aadhaar no. ",
      enterpanNo: "Please enter an pan no. ",
      enterRemarks: "Please enter a remark. ",

      attachFile: "Attach File",
      srNo: "Sr. No",
      actions: "Actions",

      //buttons
      add: "Add",
      save: "Save",
      update: "Update",
      clear: "Clear",
      exit: "Exit",
      back: "Back",
      saveAndNext: "Save & Next",
      finish: "Finish",
    },
    {
      type: "transaction",

      transaction: "Transactions",
      transactionPath: "Legal Case / Transaction ",

      //breadcrum
      opinionPath: "Legal Case/ Transactions/ Opinion",
      caseEntryPath: "Legal Case/ Transactions/ Case Entry",

      //title
      opinion: "Opinion",
      caseEntry: "Case Entry",

      //other labels
      // nOCName: "NOC Name",
      courtName: "Court Name",
      caseType: "Case Type",
      courtCaseNo: "Court Case Number",
      filingDate: "Filing Date",
      filedBy: "Filed By",
      caseDetails: "Case Details",
      advocateName: "Advocate Name",
      caseSubType: "Case Sub-Type",
      year: "Year",
      stampNo: "Stamp No.",
      filedAgainst: "Filed Against",
      advocateDetails: "Advocate Details",
      opponentAdvocate: "Opponent Advocate",
      concernPerson: "Concern Person",
      appearanceDate: "Appearance Date",
      deptName: "Department Name",
      prevCourtName: "Previous Court Name",
      document: "Document",

      attachFile: "Attach File",
      srNo: "Sr. No",
      actions: "Actions",

      //buttons
      add: "Add",
      save: "Save",
      update: "Update",
      clear: "Clear",
      exit: "Exit",
      back: "Back",
      saveAndNext: "Save & Next",
      finish: "Finish",
    },
    { type: "report" },
  ],
  mr: [
    {
      type: "commonLabels",

      module: "अग्निशामक यंत्रणा",
      // dashboard: 'डॅशबोर्ड',
      dashboard: "पिंपरी-चिंचवड महानगरपालिका डॅशबोर्ड",
      masters: "मास्टर्स",
      transactions: "व्यवहार",
      reports: "अहवाल",
      masterPath: "अग्निशमन यंत्रणा / मास्टर ",
      transactionPath: "कायदेशीर प्रकरण/ व्यवहार ",
      reportPath: "कायदेशीर प्रकरण/ अहवाल ",
    },
    {
      type: "masters",
      masters: "मास्टर्स",
      masterPath: "तक्रार निरीक्षण / मास्टर्स",

      transaction: "व्यवहार",
      report: "अहवाल",
      masterPath: "अग्निशमन यंत्रणा / मास्टर ",
      transactionPath: "कायदेशीर प्रकरण/ व्यवहार ",
      reportPath: "कायदेशीर प्रकरण/ अहवाल ",

      //breadcrum
      // masterPath: "फायर ब्रिगेड सिस्टम / मास्टर्स",
      typeOfBuildingPath: "फायर ब्रिगेड सिस्टम / मास्टर्स / इमारतीचा प्रकार",
      purposeOfBuildingPath:
        "फायर ब्रिगेड सिस्टीम / मास्टर्स / इमारतीचा उद्देश",
      typeOfNocPath: "फायर ब्रिगेड सिस्टम/ मास्टर्स/ एनओसीचा प्रकार",
      usageTypeMasterPath:
        "फायर ब्रिगेड सिस्टम / मास्टर्स / वापर प्रकार मास्टर",
      typeOfBusinessPath: "फायर ब्रिगेड सिस्टम / मास्टर्स / व्यवसायाचा प्रकार",
      vardiTypeMasterPath: "फायर ब्रिगेड सिस्टम / मास्टर्स / वर्दी टाइप मास्टर",
      fireStationDetailsPath:
        "फायर ब्रिगेड सिस्टीम / मास्टर्स / फायर स्टेशन तपशील",
      employeeShiftMasterPath:
        "फायर ब्रिगेड सिस्टम / मास्टर्स / कर्मचारी शिफ्ट मास्टर",
      vehicleDetailsPath: "फायर ब्रिगेड सिस्टीम / मास्टर्स / वाहन तपशील",

      //titles
      typeOfBuilding: "इमारतीचा प्रकार",
      purposeOfBuilding: "इमारतीचा उद्देश",
      typeOfNoc: "NOC चा प्रकार",
      usageTypeMaster: "वापराचे नाव",
      typeOfBusiness: "व्यवसायाचा प्रकार",
      vardiTypeMaster: "वर्दी प्रकार मास्टर",
      fireStationDetails: "फायर स्टेशन तपशील",
      employeeShiftMaster: "कर्मचारी शिफ्ट मास्टर",
      vehicleDetails: "वाहन तपशील",

      //other labels
      typeOfBuildingEn: "इमारतीचा प्रकार (इंग्रजी मध्ये)",
      typeOfBuildingMr: "इमारतीचा प्रकार (मराठी मध्ये)",
      gISIDEn: "GIS आयडी (इंग्रजी मध्ये)",
      gISIDMr: "GIS आयडी (मराठी मध्ये)",
      fireStationNameEn: "फायर स्टेशनचे नाव (इंग्रजी मध्ये)",
      fireStationNameMr: "फायर स्टेशनचे नाव (मराठी मध्ये)",
      addressEn: "पत्ता (इंग्रजी मध्ये)",
      addressMr: "पत्ता (मराठी मध्ये)",
      vTSSystemIDEn: "VTS सिस्टम आयडी (इंग्रजी मध्ये)",
      vTSSystemIDMr: "VTS सिस्टम आयडी (मराठी मध्ये)",
      gPSDeviceIdEn: "GPS साधन आयडी (इंग्रजी मध्ये)",
      gPSDeviceIdMr: "GPS साधन आयडी (मराठी मध्ये)",
      vehicleTypeEn: "वाहन प्रकार (इंग्रजी मध्ये)",
      vehicleTypeMr: "वाहन प्रकार (मराठी मध्ये)",
      vehicleNumberEn: "वाहन क्रमांक (इंग्रजी मध्ये)",
      vehicleNumberMr: "वाहन क्रमांक (मराठी मध्ये)",
      vardiNameEn: "वर्दी नाव (इंग्रजी मध्ये)",
      vardiNameMr: "वर्दी नाव (मराठी मध्ये)",
      buildingPurposeEn: "इमारत उद्देश (इंग्रजी मध्ये)",
      buildingPurposeMr: "इमारत उद्देश (मराठी मध्ये)",
      nOCNameEn: "NOC नाव (इंग्रजी मध्ये)",
      nOCNameMr: "NOC नाव (मराठी मध्ये)",
      nameOfUsageEn: "वापराचे नाव (इंग्रजी मध्ये)",
      nameOfUsageMr: "वापराचे नाव (मराठी मध्ये)",
      typeOfBusinessEn: "व्यवसायाचा प्रकार (इंग्रजी मध्ये)",
      typeOfBusinessMr: "व्यवसायाचा प्रकार (मराठी मध्ये)",

      courtName: "न्यायालयाचे नाव",
      address: "पत्ता",
      roadName: "रस्त्याचे नाव",
      landmark: "महत्त्वाची खूण",
      cityOrVillage: "शहर / गाव",
      pincode: "पिनकोड",
      area: "क्षेत्राचे नाव",
      name: "नाव",
      mobile: "मोबाईल नं.",
      phone: "दूरध्वनी नं.",
      email: "इलेक्ट्रॉनिक संदेश",
      aadharNo: "आधार नं.",
      panNo: "पॅन नं.",
      advocateCreation: "वकिल यशस्वीपणे तयार केला",
      advocateDetails: "वकील तपशील",
      bankDetails: "बँक तपशील",
      documentUpload: "दस्तऐवज अपलोड",
      title: "शीर्षक *",
      fname: "पहिले नाव *",
      mname: "मधले  नाव *",
      lname: "शेवटचे नाव *",
      advocateCategory: "वकील श्रेणी *",
      nameOfBarCouncil: "वकिलांचे मंडळचे प्रमाणपत्र परिषदचे नाव *",
      remarks: "टिप्पणी *",
      bankName: "बँकेचे नाव *",
      branchName: "शाखेचे नाव *",
      accountNo: "खाता क्रमांक *",
      bankIFSC: "बँक IFSC कोड *",
      bankMICR: "बँक MICR कोड *",
      application: "अर्ज:",
      aadharCard: "आधार कार्ड:",
      panCard: "पॅन कार्ड:",
      barCouncilCertificate: "वकिलांचे मंडळचे प्रमाणपत्र:",
      bankPassbook: "बँक पासबुक:",
      subType: "उप-प्रकार",

      attachFile: "फाईल जोडा",
      srNo: "अनुक्रमांक",
      actions: "क्रिया ",

      //Remarks
      selectDate: "कृपया तारीख निवडा",
      selectTitle: "कृपया शीर्षक निवडा",
      enterFName: "कृपया पहिले नाव भरा ",
      enterMName: "कृपया मधले  नाव भरा ",
      enterLName: "कृपया शेवटचे नाव भरा ",
      selectAdvocateCategory: "कृपया वकील श्रेणी निवडा",
      enterCouncilName: "कृपया वकिलांचे मंडळचे प्रमाणपत्र परिषदचे नाव भरा",
      enterArea: "कृपया क्षेत्राचे नाव भरा ",
      enterRoadName: "कृपया रस्त्याचे नाव भरा ",
      enterLandmark: "कृपया  महत्त्वाची खूण भरा",
      enterCity: "कृपया  शहराचे / गावाचे नाव भरा ",
      enterPinCode: "कृपया पिनकोड भरा",
      enterPhoneNo: "कृपया दूरध्वनी नं. भरा",
      enterMobileNo: "कृपया मोबाईल नं. भरा",
      enterEmailAddress: "कृपया इलेक्ट्रॉनिक संदेश भरा",
      enteraadhaarNo: "कृपया आधार नं. भरा",
      enterpanNo: "कृपया पॅन नं. भरा",
      // enterRemarks: 'कृपया टिप्पणी. भरा',
      enterRemarks: "कृपया टिप्पणी. द्या",

      //buttons
      add: "जोडा",
      save: "जतन करा",
      update: "अद्यायावत करा",
      clear: "रिक्त",
      exit: "बाहेर पडा",
      back: "मागे",
      saveAndNext: "जतन करा आणि पुढे",
      finish: "समाप्त",
    },
    {
      type: "transaction",

      transactions: "व्यवहार",
      transactionPath: "कायदेशीर प्रकरण/ व्यवहार ",

      //breadcrum
      opinionPath: "कायदेशीर प्रकरण / व्यवहार /मत",
      caseEntryPath: "कायदेशीर प्रकरण / व्यवहार /प्रकरणाची नोंदणी",

      //titles
      opinion: "मत",
      caseEntry: "प्रकरणाची नोंदणी",

      //other labels
      nameOfUsagemr: "वापराचे नाव",
      courtName: "न्यायालयाचे नाव",
      caseType: "प्रकरणाचा प्रकार",
      courtCaseNo: "न्यायालयाचा प्रकरणाचा नं.",
      filingDate: "दाखल करण्याची तारीख",
      filedBy: "द्वारे दाखल",
      caseDetails: "प्रकरणाचा तपशील",
      advocateName: "वकीलाचे नाव",
      caseSubType: "प्रकरणाचा उप-प्रकार",
      year: "वर्ष",
      stampNo: "मुद्रांक क्रमांक",
      filedAgainst: "विरुद्ध दाखल",
      advocateDetails: "वकील तपशील",
      opponentAdvocate: "विरोधक वकील",
      concernPerson: "संबंधित व्यक्ती",
      appearanceDate: "देखावा तारीख",
      deptName: "विभागाचे नाव",
      prevCourtName: "पूर्वीचे न्यायालयाचे नाव",
      document: "दस्तऐवज",

      attachFile: "फाईल जोडा",
      srNo: "अनुक्रमांक",
      actions: "क्रिया ",

      //buttons
      add: "जोडा",
      save: "जतन करा",
      update: "अद्यायावत करा",
      clear: "रिक्त",
      exit: "बाहेर पडा",
      back: "मागे",
      saveAndNext: "जतन करा आणि पुढे",
      finish: "समाप्त",
    },
    { type: "report" },
  ],
};

