export default {
//   en: {
    null: "Pending",
    0: "Save As Draft",
    1: "Send Back To Citizen For Approval",
    2: "Send to Samuha Sanghatak For Approval",
    3: "Send To Dept. Clerk For Approval",
    4: "Send Back To Dept. Clerk(Reverted)",
    5: "Send To Asst. Commissioner For Approval",
    6: "Send Back To Asst. Commissioner(Reverted)",
    7: "Send To Dy. Commissioner For Approval",
    8: "Send Back To Dy. Commissioner(Reverted)",
    16: "Send Back To Dept Clerk After Approval Dy Commissioner",
    10: "Complete",
    11: "Close",
    12: "Duplicate",
    22: "Rejected",
    23: "Send Back to Samuh Sanghtak",
    17: "Modification In Progress",
    18: "Modified",
    19: "Renewal In Progress",
    21: "Cancellation In Progress",
    9: "Send To Accountant",
    20: "Renewed",
    15: "Cancelled",
    13: "Cancellation Initiated",
    14: "Notice sent",
    invalid: "Invalid",
//   },
//   mr: {
//     pending: "प्रलंबित",
//     0: "मदतनिर्देश जतन करा",
//     1: "वापरकर्त्यास आपल्या मार्गदर्शकास पाठवा",
//     2: "अनुमोदनासाठी संघटकास निवेदन करा",
//     3: "अनुमोदनासाठी विभागीय लिपिकाकडे पाठवा",
//     4: "विभागीय लिपिकाकडून परत पाठवा (रिव्हर्टेड)",
//     5: "अनुमतीसाठी सहाय्यक आयुक्ताकडे पाठवा",
//     6: "सहाय्यक आयुक्ताकडून परत पाठवा (रिव्हर्टेड)",
//     7: "अनुमतीसाठी उपनिरीक्षकाकडे पाठवा",
//     8: "उपनिरीक्षकाकडून परत पाठवा (रिव्हर्टेड)",
//     16: "डेप्यूटी कमिश्नरकडून अनुमतीनंतर विभागीय लिपिकाकडे परत पाठवा",
//     10: "पूर्ण",
//     11: "बंद",
//     12: "कॉपी",
//     22: "अस्वीकृत",
//     23: "समूह संघटकाकडे परत पाठवा",
//     17: "संशोधन प्रगतीत",
//     18: "संशोधित",
//     19: "नवीनीकरण प्रगतीत",
//     21: "रद्दीकरण प्रगतीत",
//     9: "लेखापालकाकडे पाठवा",
//     20: "नवीनीत",
//     15: "रद्द",
//     13: "रद्दीकरण प्रारंभ",
//     14: "नोटिस पाठविला",
//     invalid: "अवैध",
//   },
};
