/* eslint-disable import/no-anonymous-default-export */
export default {
  en: {
    type: "commonLabels",

    module: "Legal Case Management System",
    // dashboard: 'PCMC Dashboard',
    dashboard: "Pimpri-Chinchwad Municipal Corporation Dashboard",
    master: "Masters",
    transaction: "Transactions",
    report: "Reports",
    masterPath: "Legal Case / Master ",
    transactionPath: "Legal Case / Transaction ",
    reportPath: "Legal Case / Report ",
    downloadPDF: "Download PDF",
    downloadEXCELL: "Download Excel",
    close: "Close",
    type: "master",
    master: "Masters",
    masterPath: "Legal Case/ Master",

    //breadcrum
    courtPath: "Legal Case / Master /Court",
    advocatePath: "Legal Case / Master /Advocate",
    serviceHierachyPath: "Legal Case / Master / Service Hierachy",
    caseTypePath: "Legal Case/ Master / Case Type",
    caseSubTypePath: "Legal Case / Master / Case Sub Type",
    caseStagesPath: "Legal Case/ Master / Case Stages",
    employeeAndUserCreationPath:
      "Legal Case / Master / Empnameloyee and User Creation",
    counterSchedulingPath: "Legal Case / Master / Counter Scheduling",
    smsEmailWhatsAppTemplatesPath:
      "Legal Case / Master / SMS / Email/WhatsApp Templates",
    userAuthenticationAndRoleRightsPath:
      "Legal Case / Master / User Authentication and Role-Rights",
    changeResetForgetPasswordPath:
      "Legal Case / Master / Change or Reset or ForgetPassword",
    calendarSchedulingPath: "Legal Case / Master / Calendar Scheduling",

    //label title
    court: "Court",
    advocate: "Advocate",
    serviceHierachy: "Service Hierarchy",
    caseType: "Case Type",
    caseSubType: "Case Sub-Type",
    caseStages: "Case-Stage",
    employeeAndUserCreation: "Employee and User Creation",
    counterScheduling: " Counter Scheduling",
    smsEmailWhatsAppTemplates: " SMS / E-mail / Whatsapp Template",
    userAuthenticationAndRoleRights: " User Authentication and Role Rights",
    changeResetForgetPassword: "Change / Reset / Forget Password",
    calendarScheduling: " Calender Scheduling",
    departmentCategory: "Department Category",
    meterStatus: "Meter Status",
    msedclCategory: "MSEDCL Category",
    billingUnitAndDivision: "Billing Division And Unit",
    subDivision: "Sub Division",
    billingCycle: "Billing Cycle",
    consumptionType: "Consumption Type",
    loadType: "Load Type",
    ebUsageType: "Usage Type",
    phaseType: "Phase Type",
    slabType: "Slab Type",
    division: "Division",
    tarriffCategory: "Tarriff Category",
    bachatGatCategory: "Bachat Gat Category",
    mainSchemes: "Main Schemes",
    schemesConfig: "Schemes Config",

    //other labels
    courtNameEn: "Court Name (In English)",
    courtNameMr: "Court Name (In Marathi)",

    departmentCategoryEn: "Department Category (In English)",
    departmentCategoryMr: "Department Category (In Marathi)",

    meterStatusEn: "Meter Status (In English)",
    meterStatusMr: "Meter Status (In Marathi)",

    msedclCategoryEn: "MSEDCL Category (In English)",
    msedclCategoryMr: "MSEDCL Category (In Marathi)",

    billingUnitEn: "Billing Unit (In English)",
    billingUnitMr: "Billing Unit (In Marathi)",

    tarriffCategoryEn: "Tarriff Category (In English)",
    tarriffCategoryMr: "Tarriff Category (In Marathi)",

    divisionNameEn: "Division Name (In English)",
    divisionNameMr: "Division Name (In Marathi)",

    subDivisionEn: "Sub Division (In English)",
    subDivisionMr: "Sub Division (In Marathi)",

    billingCycleEn: "Billing Cycle (In English)",
    billingCycleMr: "Billing Cycle (In Marathi)",

    categoryPrefixEn: "Category Prefix (In English)",
    categoryPrefixMr: "Category Prefix (In Marathi)",

    categoryNoEn: "Billing Unit (In English)",
    categoryNoMr: "Billing Unit (In Marathi)",

    categoryNameEn: "Billing Unit (In English)",
    categoryNameMr: "Billing Unit (In Marathi)",

    fromDateEn: "From Date(In English)",
    fromDateMr: "From Date (In Marathi)",

    toDateEn: "To Date (In English)",
    toDateMr: "To Date (In Marathi)",

    schemeIdEn: "Scheme Id (In English)",
    schemeIdMr: "Scheme Id (In Marathi)",

    schemeNameEn: "Scheme Name (In English)",
    schemeNameMr: "Scheme Name (In Marathi)",

    schemeNoEn: "Scheme No (In English)",
    schemeNoMr: "Scheme No (In Marathi)",

    schemePrefixEn: "Scheme Prefix (In English)",
    schemePrefixMr: "Scheme Prefix (In Marathi)",

    subSchemePrefixEn: "Sub Scheme Prefix (In English)",
    subSchemePrefixMr: "Sub Scheme Prefix (In Marathi)",

    subSchemeNoEn: "Scheme Prefix (In English)",
    subSchemeNoMr: "Scheme Prefix (In Marathi)",

    subSchemeNameEn: "Scheme Prefix (In English)",
    subSchemeNameMr: "Scheme Prefix (In Marathi)",

    mainSchemeKeyEn: "Scheme Id (In English)",
    mainSchemeKeyMr: "Scheme Id (In Marathi)",

    zoneKeyEn: "Zone Key (In English)",
    zoneKeyMr: "Zone Key (In Marathi)",

    wardKeyEn: "Ward Key (In English)",
    wardKeyMr: "Ward Key (In Marathi)",

    areaKeyEn: "Area Key (In English)",
    araeKeyMr: "Area Key (In Marathi)",

    geocodeEn: "GeoCode (In English)",
    geocodeMr: "GeoCode (In Marathi)",

    flatBuldingNoEn: "Flat BuldingNo (In English)",
    flatBuldingNoMr: "Flat BuldingNo (In Marathi)",

    buildingNameEn: "Building Name (In English)",
    buildingNameMr: "Building Name (In Marathi)",

    roadNameEn: "Road Name (In English)",
    roadNameMr: "Road Name (In Marathi)",

    landlineNoEn: "Landline No (In English)",
    landlineNoMr: "Landline No (In Marathi)",

    mobileNoEn: "Mobile No",
    mobileNoMr: "Mobile No (In Marathi)",

    emailIdEn: "Email Id",
    emailIdMr: "Email Id (In Marathi)",

    totalMembersCount: "Total Members Count",
    totalMembersCountMr: "total Members Count (In Marathi)",

    presidentFirstNameEn: "President First Name (In English)",
    presidentFirstNameMr: "President First Name (In Marathi)",

    presidentMiddleNameEn: "President Middle Name (In English)",
    presidentMiddleNameMr: "President Middle Name (In Marathi)",

    presidentLastNameEn: "president Last Name (In English)",
    presidentLastNameMr: "President Last Name (In Marathi)",

    applicantFirstNameEn: "Applicant First Name (In English)",
    applicantFirstNameMr: "Applicant First Name (In Marathi)",

    applicantMiddleNameEn: "Applicant Middle Name (In English)",
    applicantMiddleNameMr: "Applicant Middle Name (In Marathi)",

    applicantLastNameEn: "Applicant Last Name (In English)",
    applicantLastNameMr: "Applicant Last Name (In Marathi)",

    renewalDateEn: "Renewal Date (In English)",
    renewalDateMr: "Renewal Date(In Marathi)",

    closingDateEn: "Closing Date(In English)",
    closingDateMr: "Closing Date(In Marathi)",

    modificationDateEn: "Modification Date(In English)",
    modificationDateMr: "Modification Date(In Marathi)",

    closingDateEn: "Closing Date(In English)",
    closingDateMr: "Closing Date(In Marathi)",

    micrCodeEn: "Micr Code(In English)",
    micrCodeMr: "Micr Code(In Marathi)",
    panNumber: "PAN Number",

    iAgree: "I Agree",
    selfDeclaration: "Self Declaration",

    //other labels
    consumptionTypeEn: "Consumption Type (In English)",
    consumptionTypeMr: "Consumption Type (In Marathi)",
    loadTypeEn: "Load Type (In English)",
    loadTypeMr: "Load Type (In Marathi)",
    ebUsageTypeEn: "Usage Type (In English)",
    ebUsageTypeMr: "Usage Type (In Marathi)",
    phaseTypeEn: "Phase Type (In English)",
    phaseTypeMr: "Phase Type (In Marathi)",
    slabTypeEn: "Slab Type (In English)",
    slabTypeMr: "Slab Type (In Marathi)",

    addressEn: "Address (In English)",
    addressMr: "Address (In Marathi)",

    address: "Address",

    roadNameEn: "Road Name (In English)",
    roadNameMr: "Road Name (In Marathi)",

    roadName: "Road Name ",

    landmarkEn: "Landmark (In English)",
    landmarkMr: "Landmark (In Marathi)",

    landmark: "Landmark",

    cityOrVillageEn: "City / Village (In English)",
    cityOrVillageMr: "City / Village (In Marathi)",

    cityOrVillage: "City / Village",

    pincode: "Pincode",
    // pincodeMr: "Pincode (In Marathi)",

    areaEn: "Area (In English)",
    areaMr: "Area (In Marathi)",

    area: "Area",

    name: "Name",
    // nameMr: "Name (In Marathi)",

    mobile: "Mobile No.",
    // mobileMr: "Mobile No. (In Marathi)",

    phone: "Phone No.",
    // phoneMr: "Phone No. (In Marathi)",

    email: "E-mail",
    // emailMr: "E-mail (In Marathi)",

    aadharNoEn: "Aadhar No.(In English)",
    aadharNoMr: "Aadhar No.(In Marathi)",

    panNo: "Pan No.",
    // panNoMr: "Pan No.(In Marathi)",

    bankDetails: "Bank Details",
    // bankDetailsMr: "Bank Details (In Marathi)",

    billDetails: "Bill Details",

    paymentDetails: "Payment Details",

    paymentrate: "Payment Rate",

    payment: "Payment",
    caseFees: "Case Fees",

    fixedAmount: "Fixed Amount",

    paidAmount: "Paid Amount",
    remaingAmount: "Remaing Amount",
    paidFees: "Paid Fees",

    feesAmount: "Fees Amount",

    paidAmountDate: "Paid Amount Date",

    pendingAmount: "Pending Amount",
    pendingFees: "Pending Fees",

    approvalFeesAmount: "Approval Fees Amount",
    billAmount: "Disbursement Amount",

    documentUpload: "Document Upload",
    // documentUploadMr: "Document Upload (In Marathi)",

    nameOfBarCouncil: "Name Of Bar Council",

    remarksEn: "Remarks (In English)",
    remarksMr: "Remarks (In Marathi)",

    bankName: "Bank Name",
    // bankNameMr: "Bank Name (In Marathi)",

    branchNameEn: "Branch Name (In English)",
    branchNameMr: "Branch Name (In Marathi)",

    branchName: "Branch Name",

    accountNo: "Account No.",
    // accountNoMr: "Account No. (In Marathi)",

    bankIFSC: "Bank IFSC code",
    // bankIFSCMr: "Bank IFSC code (In Marathi)",

    bankMICR: "Bank MICR code",
    // bankMICRMr: "Bank MICR code (In Marathi)",

    applicationEn: "Application:(In English)",
    applicationMr: "Application:(In Marathi)",

    aadharNo: "Aadhar No:",

    panCard: "Pan Card:",

    barCouncilCertificateEn: "Bar Council Certificate:(In English)",
    barCouncilCertificateMr: "Bar Council Certificate:(In Marathi)",

    bankPassbookEn: "Bank Passbook:(In English)",
    bankPassbookMr: "Bank Passbook:(In Marathi)",

    subTypeEn: "Sub-Type (In English)",
    subTypeMr: "Sub-Type (In Marathi)",

    caseTypeEn: "Case Type(In English)",
    caseTypeMr: "Case Type(In Marathi)",

    caseStagesEn: "Case-Stage (In English)",
    caseStagesMr: "Case-Stage (In Marathi)",

    caseStatus: "Case Status",

    //Remarks
    selectDate: "Please select a date",
    // selectDateMr: "Please select a date (In Marathi)",

    selectTitle: "Please select a title",
    // selectTitleMr: "Please select a title (In Marathi)",

    enterFName: "Please enter first name",
    // enterFNameMr: "Please enter first name (In Marathi)",

    enterMName: "Please enter middle name",
    // enterMNameMr: "Please enter middle name (In Marathi)",

    enterLName: "Please enter last name",
    // enterLNameMr: "Please enter last name (In English)",

    selectAdvocateCategory: "Please select a category",
    // selectAdvocateCategoryMr: "Please select a category (In Marathi)",

    enterCouncilName: "Please enter council name",
    // enterCouncilNameMr: "Please enter council name (In Marathi)",

    enterArea: "Please enter area",
    // enterAreaMr: "Please enter area (In Marathi)",

    enterRoadName: "Please enter road name",
    // enterRoadNameMr: "Please enter road name (In Marathi)",

    enterLandmark: "Please enter a landmark",
    // enterLandmarkMr: "Please enter a landmark (In Marathi)",

    enterCity: "Please enter a city",
    // enterCityMr: "Please enter a city (In Marathi)",

    enterPinCode: "Please enter a pincode",
    // enterPinCodeMr: "Please enter a pincode (In Marathi)",

    enterPhoneNo: "Please enter a phone no.",
    // enterPhoneNoMr: "Please enter a phone no. (In Marathi)",

    enterMobileNo: "Please enter a mobile no.",
    // enterMobileNoMr: "Please enter a mobile no. (In Marathi)",

    enterEmailAddress: "Please enter an e-mail.",
    // enterEmailAddressMr: "Please enter an e-mail. (In Marathi)",

    enteraadhaarNo: "Please enter an aadhaar no.",
    // enteraadhaarNoMr: "Please enter an aadhaar no.(In Marathi)",

    enterpanNo: "Please enter an pan no.",
    // enterpanNoMr: "Please enter an pan no. (In Marathi)",

    enterRemarks: "Please enter a remark.",
    // enterRemarksMr: "Please enter a remark. (In Marathi)",

    attachFile: "Attach File",
    // attachFileMr: "Attach File (In Marathi)",

    srNo: "Sr.No",
    // srNoMr: "Sr. No (In Marathi)",

    actions: "Actions",
    // actionsMr: "Actions (In Marathi)",

    entersNumbers: "Please Enters Numbers Only",
    // entersNumbersMr: "Please Enters Numbers Only (In Marathi)",

    //buttons
    add: "Add",
    save: "Save",
    update: "Update",
    clear: "Clear",
    exit: "Exit",
    back: "Back",
    saveAndNext: "Save & Next",
    finish: "Finish",
    addPoint: "Add",
    // Transaction
    type: "transaction",

    transaction: "Transactions",
    transactionPath: "Legal Case / Transaction ",

    //breadcrum
    opinionPath: "Legal Case/ Transactions/ Opinion",
    caseEntryPath: "Legal Case/ Transactions/ Case Entry",

    //title
    opinion: "Opinion",

    opinionEn: "Opinion (In English)",
    opinionMr: "Opinion (In Marathi)",

    caseEntry: "Case Entry",

    //other labels
    courtName: "Court Name",
    caseType: "Case Type",
    courtCaseNo: "Court Case Number",
    filingDate: "Filing Date ",

    filedByEn: "Filed By (In English)",
    filedByMr: "Filed By (In Marathi)",

    filedBy: "Filed By",

    filedAgainstEn: "Filed Against (In English)",
    filedAgainstMr: "Filed Against (In Marathi)",

    caseDetails: "Case Details",
    advocateName: "Advocate Name",
    caseSubType: "Case Sub-Type",
    year: "Year",
    stampNo: "Stamp No.",
    advocateDetails: "Advocate Details",
    opponentAdvocate: "Opponent Advocate",
    opponentAdvocateEn: "Opponent Advocate (In English)",
    opponentAdvocateMr: "Opponent Advocate (In Marathi)",

    concernPerson: "Concern Person",

    concernPersonEn: "Concern Person (In English)",
    concernPersonMr: "Concern Person (In Marathi)",

    // concernDeptName:"Concen Dept. Name",

    locationName: "Location Name",

    appearanceDate: "Appearance Date",
    deptName: "Department Name",
    prevCourtName: "Previous Court Name",
    document: "Document",

    attachFile: "Attach File",
    srNo: "Sr. No",
    actions: "Actions",

    addHearing: "Add Hearing",

    add: "Add",
    save: "Save",
    update: "Update",
    exit: "Exit",
    back: "Back",
    saveAndNext: "Save & Next",
    finish: "Finish",

    courtCaseNumber: "Court Case Number",
    hearingDate: "Hearing Date",

    rate: "Rate",

    fromDate: "From Date",
    toDate: "To Date",
    panelAdvocate: " Panel Advocate",
    panelOther: "Other",

    caseNo: "Case No",
    noticeRecivedDate: "Notice Recived Date",
    noticeDate: "Notice Date",
    noticeRecivedFromAdvocatePerson: "Notice Recevied From Advocate",
    requisitionDate: "Requisition Date",
    noticeDetails: "Notice Details",
    advocateAddress: "Advocate Address",
    addMore: "Add More",
    officeLocation: "Office Location",
    deptName: "Department Name",
    delete: "Delete",
    saveAndNext: "Save And Next",
    next: "Next",
    exit: "Exit",
    back: "Back",

    transferDetails: "Transfer Details",

    transferAdvocate: "Transfer Advoacte",

    opinionRequestDate: "  Opinion Request Date",

    opinionSubject: "Opinion Subject",

    advPanel: "Do you want Opinion from Panel Advocate",

    reportAdvPanel: "Do you want Search Title Report from Panel Advocate",

    advoacteName: "Advoacate Name",

    submit: "Submit",

    cancel: "Cancel",

    searchTitleReport: "Search Title Report Date",

    hearingDetails: "Hearing Details",

    advocateOpinion: "Advocate Opinion",
    advocateOpinionEn: "Advocate Opinion (In English) ",
    advocateOpinionMr: "Advocate Opinion (In Marathi) ",

    saveAsDraft: "Save As Draft",

    approveOpinion: "Approve Opinion",

    caseRefNo: "Case refrence Number",

    noticeDatae: "Notice Date",
    noticeReceviedDate: "Notice Recevied Date",

    noticeReceviedFromAdvocate: "Notice received from Advocate/Person",
    requisitionDate: "Requisition Date",
    officeLocation: "Office Location",
    employeeName: "Employee Name",
    delete: "Delete",
    // notice:"Notice"
    parawiseReport: "Parawise Report",
    pointNo: "Point No",
    pointExp: "Points Explanation",
    issueNo: "Issue No",

    clerkRemark: "Clerk Remark",

    clerkRemarkEn: "Clerk Remark (In English) ",
    clerkRemarkMr: "Clerk Remark (In Marathi) ",
    caseFees: "Case Fees",

    approvalScreen: "Approval Screen",
    titleNewApplicationSchemes: "New application for schemes ",
    applicantAdharNo: "Applicant Aadhar No",
    applicationNo: "Application No",
    areaNm: "Area Name",
    wardname: "Ward Name",
    zoneNames: "Zone Name",

    flatBuildNo: "Flat/Building No",
    buildingNm: "Building Name",
    landmark: "Landmark",
    gisgioCode: "GIS/GIO code",
    applicantAdharNo: "Applicant Adhar No",
    dateOfBirth: "Date Of Birth",
    age: "Age",
    applicantMiddleName: "Applicant Middle Name",
    applicantFirstName: "Applicant First Name",
    applicantLastName: "Applicant Last Name",
    applicantDetails: "Applicant Details",
    gender: "Gender",
    subScheme: "Sub Scheme",

    mainScheme: "Main Scheme",
    beneficiaryCode: "Beneficiary Code",
    religion: "Religion",

    castCategory: "Caste Category",
    disabilityCertExpDate: "Disability Certificate Expiry Date",
    divyangSchemeType: "Divyang Scheme Type",
    savinAcFirstNm: "Saving Acc. First Name",
    savingAcMiddleNm: "Saving Acc. Middle Name",
    savingAcLastNm: "Saving Acc. Last Name",
    eligibilityDoc: "Eligibility Document",
    savingAcNo: "Saving Account No",
    eligibilityCriteria: "Eligibility Criteria",
    ans: "Answer",
    uploadDocs: "Upload Documents",
    currentStatus: "Current Status",

    saSanghatakRemark: "Samuha Sanghatak Remark",
    deptClerkRemark: "Zonal Clerk Remark",
    asstCommissionerRemark: "Zonal Officer Remark",
    deptyCommissionerRemark: "Head Officer Clerk Remark",
    approvebtn: "Approved",
    revertbtn: "Revert",
    welcomeToTheDashboard: "Welcome To The Dashboard",
    totalTodaysCount: "Today's Total Count",
    totalPendingCount: "Today's Pending Count",
    totalCompletedCount: "Today's Completed Count",
    totalCount: "Total Count",
    pendingCount: "Pending Count",
    completedCount: "Completed Count",
    mainSchemeSummary: "Main Scheme Summary",
    subSchemeSummary: "Sub Scheme Summary",
    mainSubSchemeSummary: "Main Scheme and Sub Scheme Summary",
    mainScheme: "Main Scheme",
    zoneOffice: "Zone office name",
    totalApplications: "Total Applications",
    approvedApplications: "Approved Applications",
    rejectedApplications: "Rejected Applications",
    benefiteApplications: "Benefited Applications",
    benefiteRejectedApplications: "Benefit Rejected Applications",
    subScheme: "Sub Scheme",

    financialYear: "Financial Year :",

    bachatGatRegTotalCount: "Total Registred Bachat Gat",
    bachatGatRegPendingCount: "Registration Pending Bachat Gat",
    bachatGatRegCompletedCount: "Registred Completed Bachat Gat",

    bachatGatCancelTotalCount: "Total Cancelled Bachat Gat",
    bachatGatCancelPendingCount: "Pending Cancellation Bachat Gat",
    bachatGatCancelCompleteCount: "Completed Cancelled Bachat Gat",

    bachatGatModiTotalCount: "Total Modified Bachat Gat",
    bachatGatModiPendingCount: "Pending Modification Bachat Gat",
    bachatGatModiCompleteCount: "Completed Modified Bachat Gat",

    bachatGatRenewTotalCount: "Total Renewed Bachat Gat",
    bachatGatRenewPendingCount: "Pending Renewal Bachat Gat",
    bachatGatRenewCompleteCount: "Completed Renewal Bachat Gat",
    bachatGatReg: "Bachat Gat Registration",

    titlaBRegTotal: "Bachat Gat Registration (Total)",
    titleBRegPending: "Bachat Gat Registration (Pending)",
    titleBRegComplete: "Bachat Gat Registration (Completed)",
    titleBCancelTotal: "Bachat Gat Cancellation (Total)",
    titleBCancelPending: "Bachat Gat Cancellation (Pending)",
    titleBCancelComplete: "Bachat Gat Cancellation (Completed)",

    titleBModiTotal: "Bachat Gat Modification (Total)",
    titleBModiPending: "Bachat Gat Modification (Pending)",
    titleBModiComplete: "Bachat Gat Modification (Completed)",

    titleRenewalTotal: "Bachat Gat Renewal (Total)",
    titleRenewalPending: "Bachat Gat Renewal (Pending)",
    titleRenewalComplete: "Bachat Gat Renewal (Completed)",
    applicantName: "Applicant Name",
    startDate: "Start Date",
    infoTitle: "Information Title",
    fileNm: "File Name",
    answer: "Answer",
    approvalSection: "Approval Section",
    rejectedReason: "Rejected Reason",
    revertedReason: "Reverted Reason",
    rejectBtn: "Reject",
    paymentDate: "Payment Date",
    chequeNo: "Cheque No/UTR No",
    accountantSection: "Accountant Section",
    bachatgatName: "Bachat Gat Name",
    presidentName: "President Name",
    bachatgatRegistration: "Bachat Gat Registration",
    bachatGatDetails: "Bachat Gat Details",
    gisgioCode: "GISID/Geo code",
    bachatgatFullName: "Bachat Gat Full Name",
    bachatgatCat: "Bachat Gat category",
    bachatgatAddress: "Bachat Gat Address",
    presidentFirstName: "Bachat Gat President First Name",
    presidentFatherName: "Bachat Gat President Father Name",
    presidentLastName: "Bachat Gat President Surname",
    totalCount: "Bachat Gat Total Members",
    landlineNo: "Landline No.",
    mobileNo: "Mobile No",
    emailId: "Email Id",
    accountHolderName: "Account Holder name",
    memberInfo: "Member Information",
    requiredDoc: "Required Documents",
    memFullName: "Member Full Name",
    memFullAdd: "Member Full Address",
    memDesign: "Member Designation",
    memAdharNo: "Member Adhaar No.",
    fileType: "File Type",
    attachedDate: "Attached Date",
    uploadFile: "Upload Files",
    addDoc: "Add Documents",
    upload: "Uploads",
    getDetails: "Get Details",
    results: "Results",
    searchArea: "Search Area",
    bachatgatCancellation: "Bachat Gat Cancellation ",
    search: "Search",
    cancellationSection: "Cancellation Section",
    cancelReason: "Cancel Reason",
    cancelDate: "Cancel Date",
    bachatgatForceFulCancellation: "Bachat Gat Forceful Cancellation",

    bachatgatModification: "Bachat Gat Modification ",

    print: "Print",
    pimpariChinchwadMaha: "Pimpri Chinchwad Municipal Corporation",
    appAcknowldgement: "Application Acknowledgement",
    ackDear: "Dear",
    ackpcmcthanku:
      "Thank you for using PCMC Pimpri Chinchwad Citizen Service Portal !!",
    ackshortDesc1: "Your application for ",
    ackshortDesc2: "Bachat Gat Registration ",
    ackshortDesc3: "under PCMC has been successfully submitted.",
    ackRTIAppealshortDesc:
      "Your application for Right To Information Appeal under PCMC has been successfully submitted.",

    ackApplicationSummery: "Application Summary",
    applicationNo: "Application No",
    dateofApplication: "Date of the Application",
    applicationDate: "Application Date",
    bachatgatRegistrationDate: "Registration Date",
    ackplzContactNearestOperator:
      "For any query please contact your nearest operator or the following contact details:",
    ackpcmcAddress: "Mumbai Pune Highway Pimpri Pune 411-018",
    ackPcmcphNo: "Phone Number:91-020-2742-5511/12/13/14",
    ackstateCountry: "Maharashtra, India",
    applicantAddress: "Applicant Address",

    renew: "Renew",
    renewalSection: "Renewal Section",

    renewalRemark: "Renewal Remark",

    uploadedDoc: "Uploaded Documents",
    categoryPrefix: "Category Prefix",
    categoryNo: "Category No",
    categoryNameEn: "Category Name (In English)",
    categoryNameMr: "Category Name (In Marathi)",
    categoryName: "Category Name",
    titleSchemeApplicationRenewal: "Scheme Application Renewal ",

    schemeNoReq: "Scheme No. is Required !!!",
    schemeNamePrefix: "Scheme Prefix is Required !!!",
    schemeNameMrReq: "Scheme Name (Marathi) is Required !!!",
    schemeNameReq: "Scheme Name is Required !!!",
    bachatgatToDate: "To Date is Required !!!",
    bachatgatFromDate: "From Date is Required !!!",
    mainSchemeReq: "Main Scheme is Required !!!",

    subSchemeNoReq: "Sub Scheme No. is Required !!!",
    subSchemeNameMrReq: "Sub Scheme Name (Marathi) is Required !!!",
    subSchemeNameReq: "Sub Scheme Name is Required !!!",
    subSchemePrefReq: "Sub Scheme Prefix is Required !!!",
    /////////////////////////////////////////////////////////////////////////////
    // Labels added by satej
    /////////////////////////////////////////////////////////////////////////////
    informationTitleT: "Information Title ",

    informationTitle: "Information Title (English)",
    informationTitleMr: "Information Title (Marathi)",
    informationType: "Information Type",
    informationSelectionData: "Information Selection Data",
    infoDataSize: "file size (in Mb)",
    installments: "No. Of Installments",
    benefitAmount: "Benefit Amount (in Rs.)",
    //application summary report labels - by satej
    onlineApplicationNo: "Online Application No.",
    cfcApplicationNo: "CFC Application No.",
    applicationDate: "Application Date",
    zoneName: "Zone Name",
    zoneNameMr: "Zone Name (Mr)",
    wardName: "Ward Name",
    wardNameMr: "Ward Name (Mr)",
    beneficiaryName: "Beneficiary Name",
    beneficiaryAddress: "Beneficiary Address",
    aadharNo: "Aadhar No",
    mobileNo: "Mobile No",
    schemeName: "Scheme Name",
    schemeNameMr: "Scheme Name (Mr)",
    subSchemeName: "Sub Scheme Name",
    subSchemeNameMr: "Sub Scheme Name (Mr)",
    download: "Download",
    totalApplicationSummaryHeading: "Total Application Summary",
    disabilityPercent: "Disability Percentage",
    benefitRejectedApplications: "Benefit Rejected Applications",
    benefitedApplications: "Benefited Applications",
    schemeWiseSummaryHeading: "Scheme Wise Summary",
    namunaAReportHeading: "Namuna A ",
    namunaBReportHeading: "Namuna B ",
    namunaCReportHeading: "Namuna C ",
    areaName: "Area Name",

    bankName: "Bank Name",
    branchName: "Branch Name",
    iFSCNo: "IFSC No.",
    mICRNo: "MICR No.",
    amount: "Amount",
    reasonForNonEligible: "Reason For Non Eligibility",
    castWiseListOfBeneficiariesHeading: "Caste Wise List Of Beneficiaries",
    castCategory: "Caste Category",

    bachatgatrenewal: "Bachat Gat Renewal ",
    RegistrationDate: "Registration Date",
    modificationDate: "Modification Date",

    cancellationDate: "Cancellation Date",
    schemeApplicationDate: "Scheme Application Date",
    bachatgatRenewalDate: "Bachat Gat  Renewal Date",
    schemeApplicationRenewalDate: "Scheme Application Renewal Date",
    docName: "Document Name",
    view: "View",
    userName: "Username",
    remark: "Remark",
    remarkDate: "Remark Date",
    design: "Designation",

    bachatgatStartDate: "Bachat Gat Start Date",
    fileUpload: "Upload File",

    /////////////// Validation error translation by shubham ////////////////////

    bgCategoryPrefixValidation: "Category Prefix is Required !!!",
    bgCategoryMrValidation: "Category Name in Marathi is Required !!!",
    bgCategoryNameValidation: "Category Name in English is Required !!!",
    bgCategoryPrefixLengthValidation:
      "Bachat Gat prefix should not exceed 15 characters",
    bgCategoryMrCharacterValidation:
      "Only characters are allowed in Bachat Gat Category Name (Marathi).",
    bgCategoryMrCharacterLengthValidation:
      "Bachat Gat Category Marathi Name should not exceed 100 characters",
    bgCategoryNameCharacterValidation:
      "Only characters are allowed in Bachat Gat Category Name.",
    bgCategoryNameLengthValidation:
      "Bachat Gat Category Name should not exceed 50 characters",
    bachatgatNameValidation: "Bachat Gat Name is Required !!!",
    bachatgatNameValidationLength:
      "Bachat Gat Full Name should not exceed 50 characters",
    presidentFirstNameValidation: "President First Name is Required !!!",
    presidentFirstNameValidationLength:
      "President First Name should not exceed 50 characters",
    presidentMiddleNameValidation: "President Middle Name is Required !!!",
    presidentMiddleNameValidationLength:
      "President Middle Name should not exceed 50 characters",
    presidentLastNameValidation: "President Last Name is Required !!!",
    presidentLastNameValidationLength:
      "President Last Name should not exceed 50 characters",
    totalMembersCountValidtion: "Total Members is Required !!!",

    middleNameValidation: "Middle Name is Required !!!",
    middleNameValidationLength: "Middle Name should not exceed 50 characters",

    totalMembersCountValidtionLength:
      "Total Members Count should not exceed 2 digit numbers",
    applicantFirstNameValidtion: "Applicant First Name is Required !!!",
    applicantFirstNameValidtionLength:
      "Applicant First Name should not exceed 50 characters",
    applicantMiddleNameValidtionL: "Applicant Middle Name is Required !!!",
    applicantMiddleNameValidtionLength:
      "Applicant Middle Name should not exceed 50 characters",
    applicantLastNameValidtionL: "Applicant Last Name is Required !!!",
    applicantLastNameValidtionLength:
      "Applicant Last Name should not exceed 50 characters",
    pinCodeValidtion: "Pincode is Required !!!",
    pinCodeValidtionLength: "Pincode should not exceed 6 characters",
    pinCodeValidtionMinLength: "Pincode must be 6 characters",
    flatBuldingNoValidation: "Flat/Building no is Required !!!",
    buildingNameValidation: "Building Name is Required !!!",
    roadNameValidation: "Road Name is Required !!!",
    landmarkValidation: "Landmark is Required !!!",
    geoCodeValidation: "Geocode is Required !!!",
    mobileNoValidation: "Mobile No is Required !!!",
    emailIdValidation: "Email Id is Required !!!",
    accountNoValidation: "Account No is Required !!!",
    ifscCodeValidation: "IFSC Code is Required !!!",
    micrCodeValidation: "MICR Code is Required !!!",
    bankAccountFullNameValidation: "Account Full Name is Required !!!",
    branchNameValidation: "Branch Name is Required !!!",
    startDateValidation: "Start Date is Required !!!",
    emailIdValidtionLength: "Email Id should not exceed 80 characters",
    accountNoValidtionLength: "Account No should not exceed 18 numbers",
    ifscCodeValidtionLength: "IFSC Code should not exceed 11 numbers",
    ifscCodeValidationMinLength: "IFSC Code must be 11 numbers",
    micrCodeValidtionLength: "MICR Code should not exceed 9 numbers",
    micrCodeValidtionMinLength: "MICR Code must be 9 numbers",
    landlineNoValidtionLength: "Land line number should not exceed 10 numbers",
    landlineNoValidtionMinLength: "Land line number must be 10 numbers",
    bankAccountFullNameValidtionLength:
      "Account Full Name should not exceed 500 characters",
    branchNameValidtionLength: "Branch Name should not exceed 50 characters",
    areaKeyValidation: "Area Name is Required !!!",
    zoneKeyValidation: "Zone Name is Required !!!",
    wardKeyValidation: "Ward Name Required !!!",
    surNameValidation: "Last Name Required !!!",
    benecodeValidation: "Beneficiary Code is Required !!!",
    mainSchemeKeyValidation: "Main Scheme is Required !!!",
    subSchemeKeyValidation: "Sub Scheme is Required !!!",
    genderValidation: "Gender is Required !!!",
    applicantAadharNoValidation: "Applicant Adhar No is Required !!!",
    applicantAadharNoValidationMinLength:
      "Aadhar No must be at least 12 numbers",
    applicantAccountNoValidationMinLength:
      "Account No must be at least 6 numbers",
    applicantAadharNoValidationLength: "Aadhar No should not exceed 12 numbers",
    dateOfBirthValidation: "Date of Birth is Required !!!",
    ageValidation: "Age is required",
    agePtvValidation: "Age must be a positive number",
    ageIntValidation: "Age must be an integer",
    ageValidationLength: "Age must be 18 years or older",
    religionKeyValidation: "Religion is Required !!!",
    casteCategoryValidation: "Caste Category is Required !!!",
    bachatGatCategoryValidation: "BachatGat Category is Required !!!",
    disabilityCertificateValidityValidation:
      "Disablity Certificate validity is Required !!!",
    bankBranchKeyValidation: "Bank Branch is Required !!!",
    savingAccountNoValidation: "Saving Account No is Required !!!",
    savingAccountNoValidationLength: "Account No should not exceed 18 numbers",
    saOwnerFirstNameValidation: "Saving Account First Name is Required !!!",
    saOwnerFirstNameValidationLength:
      "Saving Account First Name should not exceed 50 characters",
    saOwnerMiddleNameValidation: "Saving Account Middle Name is Required !!!",
    saOwnerMiddleNameValidationLength:
      "Saving Account Middle Name should not exceed 50 characters",
    saOwnerLastNameValidation: "Saving Account Last Name is Required !!!",
    saOwnerLastNameValidationLength:
      "Saving Account Last Name should not exceed 50 characters",
    schemeNameReqLength: "Scheme Name should not exceed 50 characters",
    schemeNameReqMrLength:
      "Scheme Name (Marathi) should not exceed 100 characters",
    schemeNamePrefixLength: "Scheme prefix should not exceed 15 characters",
    infoTitleRequiredLength:
      "Information title should not exceed 50 characters",
    subSchemeNameReqLength: "Sub Scheme Name should not exceed 50 characters",
    subSchemeNameMrReqLength:
      "Sub Scheme Name (Marathi) should not exceed 100 characters",
    subSchemePrefReqLength: "Sub Scheme prefix should not exceed 15 characters",
    benefitAmountReq: "Benifit Amount is Required",
    installmentsReq: "No of installments is Required",

    schemePrefixT: "Scheme Prefix",
    schemeNameT: "Scheme Name",
    totalMembersCountValidation:
      "Total members count must be equal to or less than 20",
    totalMembersCountRequiredValidation: "Total members count is Required",

    /////////////////sub scheme label changes by shubham //////////////
    subSchemePrefix: "Sub Scheme Prefix",
    mainSchemeNameT: "Main Scheme Name",
    subSchemeNameT: "Sub Scheme Name",
    subSchemeNo: "Sub Scheme No",
    subschemeTitle: "Sub Schemes",
    subSchemeNameFEn: "Sub Scheme Name (In English)",

    ////////////////////////main scheme error msg by shubham ////////////////
    allowSchemeNameReq: "Only characters are allowed in Scheme Prefix.",
    allowschemeNamePrefix:
      "Only characters and numbers are allowed in Scheme Prefix.",
    allowschemeNoReq: "Only numbers are allowed in Scheme Prefix.",
    infoTitleRequired: "Informatrion Title is Required !!!",
    infoTypeRequired: "Informatrion Type is Required !!!",
    aadharErrorMsg: "Member is already exist",
    schemeConfigData: "Eligibility Criteria and Document Master",
    bachatgatCatNmOnlychar:
      "Only characters are allowed in Bachat Gat Category Name.",
    benefitAmountReq: "Benifit Amount is Required",
    noOfInstallmentReq: "No of installments is Required",
    CompleteBtn: "Complete",
    requiredMessage: "Please fill out this field",
    applicationName: "Application Name",
    helpDeskBSUP: "Help Desk Of Samaj vikas Department",
    newSchemeApplicationCount: " Scheme Application Total Count",
    bachatgatNo: "Bachat Gat No",
    yes: "Yes",
    no: "No",
    // guideline1:"1) The applicant indicates the applicant Chinchwad Municipal Corporation by clicking on the social development section on the site through the online form.",
    // guideline2:"2) Applicant must belong to Pimpri Chinchwad Municipal Corporation.",
    // guideline3: `3) Marked fields are mandatory while others are optional.`,
    // guideline4:"4) Eligible / Ineligible application will be checked through the field office ",
    // guideline5:"5) Eligible list or application will be sent to Social Development Department at Pimpri Chinchwad Municipal Corporation Head Office.",
    // guideline6:"6) Proceedings for disbursement of benefits to eligible beneficiaries will be done through Social Development Department.",
    // guideline7:"7) Applicant must attach Aadhaar card within Pimpri Chinchwad Municipal Corporation limits along with the application.",
    // guideline8:'8) The original documents required by the applicant should be duly scanned and uploaded as per the given scheme. ',
    // guideline9:"9) Applicant should check his Aadhaar number and Mobile (Bhramandhwani) number properly and apply.",
    // guideline10: "10) Applicants are requested to note that if the applicant mentions wrong Aadhaar number in the application, his/her application will be disqualified.",
    // guideline11:'11) As per section 63 and 66 of the Maharashtra Municipal Corporation Act, as per section 72(a),(b),(c) of the Maharashtra Municipal Corporation Act, it is necessary to work.',

    guideline1:
      "१) अर्जदाराने अर्ज पिंपरी चिंचवड महानगरपालिका यांच्या संकेत स्थळावर जाऊन समाज विकास या विभागावर क्लिक करुन आँनलाईन पध्दतीने अर्ज करता येणार.",
    guideline2:
      "२) अर्जदार हा पिंपरी चिंचवड महानगरपालिका यांच्या हद्दीमधील असणे आवश्यक आहे.",
    guideline3: "३) चिन्हांकित फील्ड अनिवार्य आहेत तर इतर पर्यायी आहेत.",
    guideline4:
      "४) क्षेत्रीय कार्यालयामार्फत अर्जाची पात्र / अपात्र तपासणी केल्या जाईल.",
    guideline5:
      "५) पात्र असलेली यादी किंवा अर्ज पिंपरी चिंचवड महानगरपालिका मुख्य कार्यालय मध्ये समाज विकास विभागाकडे पाठविला जाईल.",
    guideline6:
      "६) पात्र असलेल्या लाभार्थीना लाभ देण्याची कार्यवाही समाज विकास विभागामार्फत केली जाईल.",
    guideline7:
      "७) अर्जदाराने अर्जासोबत पिंपरी चिंचवड महानगरपालिका हद्दीमधील आधारकार्ड जोडणे आवश्यक.",
    guideline8:
      "८) अर्जदाराने आवश्यक असलेले मुळ कागदपत्र योग्य रित्या स्कँन करुन दिलेल्या योजने नुसार अपलोड करण्यात यावे. ",
    guideline9:
      "९) अर्जदाराने आपला आधार क्रमांक आणि मोबाईल (भ्रमणध्वनी) क्रमांक योग्य रित्या तपासुन अर्ज करावा.",
    guideline10:
      "१०) अर्जदाराने चुकीचा आधार क्रमांक अर्जामध्ये नमुद केल्यास त्याचा अर्ज हा अपात्र करण्यात येईल याची नोंद अर्जदाराने घेण्यात यावी ही विनंती.",
    guideline11:
      "११) महाराष्ट्र महानगरपालिका अधिनियम कलम ६३ व ६६ नुसार महाराष्ट्र महानगरपालिका अधिनियम कलम ७२(अ),(ब),(क) नुसार काम करणे आवश्यक आहे",

    guideline11: "",
    guideline12: "12) guideline 12",
    guideline13: "13) guideline 13.",
    guideline14: "14) guideline 14.",
    guideline15: "15) guideline 15.",
    guideline16: "16) guideline 16.",
    guideline17: "17) guideline 17.",
    guideline18: "18) guideline 18.",
    guideline19: "19) guideline 19.",
    guideline20: "20) guideline 20.",
    guideline21: "21) guideline 21.",
    guideline22: "22) guideline 22.",
    guideline23: "23) guideline 23.",
    guideline24: "24) guideline 24.",
    guideline25: "25) guideline 25",
    // Tnc: "ACCEPT TERMS AND CONDITION",
    // bsupTermsndTitle: "Pimpri Chinchwad Municipal Corporation, Pimpri-411018",
    // rtiAct2005: "Samaj Vikas Department",
    // guidelineOfBsup: "GUIDELINES FOR USE OF SAMAJ VIKAS DEPARTMENT'S ONLINE PORTAL",
    Tnc: "नियम व अटी",
    bsupTermsndTitle: "पिंपरी चिंचवड महानगरपलिका,पिंपरी-४११०१८",
    rtiAct2005: "समाज विकास विभाग ",
    guidelineOfBsup:
      "समाज विकास विभागाच्या ऑनलाइन पोर्टलच्या वापरासाठी मार्गदर्शक तत्त्वे",

    fullNameRequired: "Full name is required",
    addressRequired: "Address is required",
    fullNameRequiredLength: "Full Name should not exceed 30 characters",
    addressRequiredLength: "Address should not exceed 100 characters",
    designRequired: "Designation is required",
    adharNoRequired: "Adhar no. is required",
    rejectCat: "Select Category",
    rejectCatMr: "Select Category (Mr.)",
    rejectCatReq: "Select Category is required",
    rejectCatMrReq: "Select Category (मराठी) is required",
    existingBachatGat: "Existing Bachat Gat",
    newBachatGat: "New Bachat Gat",
    oldBachatGatNo: "Existing Bachat Gat No.",
    oldBachatGatRegiDate: "Existing Bachatgat Registration Date",
    isSchemeForBachatGat: "Is this sub scheme applicable for bachat gat?",
    isForBachatOrScheme: "For bachat gat or scheme application",
    isForBachatOrSchemeReq: "For bachat gat or scheme application is required",

    forBachatGatOrScheme: "For bachat gat or scheme",
    benefitTitle: "Benefit Amount",
    installment: "Installments",
    exitTNC: "बाहेर पडा",
    castOption: "Caste Option",
    paidInstallments: "Paid Installments",
    installmentAmount: "Installment Amount",
    downloadCertificate: "Download Certificate",
    patraApatra: "Approved/Reverted",
    cfcackNo: "CFC Acknowldgement No.",
    showAll: "Show All",
    totalApplication: "Total Application",
    approvedApplication: "Approved Application",
    revertedApplication: "Reverted Application",
    rejectedApplication: "Rejected Application",
    hasBenefit: "Has benefit been given?",
    bachatApplicationDate: "Bachatgat Application Date",
    bachatApplicationNo: "Bachatgat Application No",
    applicantFullName: "Applicant Full Name",
    applicantFullNameMr: "Applicant Full Name (मराठी)",

    currInstallmentNumber: "Current Installment Number",
    installmentAmt: "Installment Amount",
    installmentDate: "Installment Date",
    chequeNo: "Cheque No",
    note: "Note",
    categoryType: "Category Type",
    categoryTypeReq: "Category Type is required",

    isMandatory: "Is Mandatory?",
    remarkSectionHeader: "Remarks Section",
    approveCategory: "Approve Category",
    revertCategory: "Select Remark",
    pendingApplication: "Pending Applications",
    
  
    question2: "Any own business of the Bachat Gat ? If yes which one?" ,
    question1:
      " Whether Training is taken by Bachat Gat members? ",
    question3:
      "बचतगटातील महिला वैयक्तिक व्यवसाय करतात का ? होय असल्यास कोणता ?",
    mahilaPrashikshan: "Training Name",
    vyavsayacheNav:'Business Name ',
    vVyasaycheNav:'Own Business Name'
  },

  mr: {
    type: "commonLabels",
    panelAdvocate: "पॅनेलचे वकील",
    panelOther: "इतर",
    branchName: "शाखेचे नाव",
    module: "कायदेशीर प्रकरण व्यवस्थापन प्रणाली",
    // dashboard: 'डॅशबोर्ड',
    dashboard: "पिंपरी-चिंचवड महानगरपालिका डॅशबोर्ड",
    master: "मास्टर्स",
    transaction: "व्यवहार",
    report: "अहवाल",
    masterPath: "कायदेशीर प्रकरण/ मास्टर ",
    transactionPath: "कायदेशीर प्रकरण/ व्यवहार ",
    reportPath: "कायदेशीर प्रकरण/ अहवाल ",
    type: "master",
    master: "मास्टर्स",
    transaction: "व्यवहार",
    report: "अहवाल",
    masterPath: "कायदेशीर प्रकरण/ मास्टर ",
    transactionPath: "कायदेशीर प्रकरण/ व्यवहार ",
    reportPath: "कायदेशीर प्रकरण/ अहवाल ",
    downloadPDF: "पीडीएफ डाउनलोड करा",
    downloadEXCELL: "एक्सेल डाउनलोड करा",
    //breadcrum
    courtPath: "कायदेशीर प्रकरण/ मास्टर /न्यायालय",
    advocatePath: "कायदेशीर प्रकरण/ मास्टर /वकील",
    serviceHierachyPath: "कायदेशीर प्रकरण/ मास्टर / सेवा पदानुक्रम",
    caseTypePath: "कायदेशीर प्रकरण/ मास्टर / प्रकरणाचा प्रकार",
    caseSubTypePath: "कायदेशीर प्रकरण/ मास्टर / प्रकरणाचा उप-प्रकार",
    caseStagesPath: "कायदेशीर प्रकरण/ मास्टर / प्रकरण-टप्पे",
    employeeAndUserCreationPath:
      "कायदेशीर प्रकरण/ मास्टर / कर्मचारी आणि वापरकर्ता निर्मिती",
    counterSchedulingPath: "कायदेशीर प्रकरण/ मास्टर / काउंटर शेड्युलिंग",
    smsEmailWhatsAppTemplatesPath:
      "कायदेशीर प्रकरण/ मास्टर / संदेश सेवा /  ई-मेल/ व्हॉट्सॲप साचा",
    userAuthenticationAndRoleRightsPath:
      "कायदेशीर प्रकरण/ मास्टर / वापरकर्ता प्रमाणीकरण आणि भूमिका-अधिकार",
    changeResetForgetPasswordPath:
      "कायदेशीर प्रकरण/ मास्टर / बदल किंवा पुनर्प्रस्थापित किंवा पासवर्ड विसरलात",
    calendarSchedulingPath: "कायदेशीर प्रकरण/ मास्टर / दिनदर्शिका शेड्युलिंग",
    //titles
    court: "न्यायालय",
    advocate: "वकील",
    serviceHierachy: "सेवा पदानुक्रम",
    caseType: "प्रकरणाचा प्रकार",
    caseSubType: "प्रकरणाचा उप-प्रकार",
    caseStages: "प्रकरण-टप्पे",
    employeeAndUserCreation: "कर्मचारी आणि वापरकर्ता निर्मिती",
    counterScheduling: " काउंटर शेड्युलिंग",
    smsEmailWhatsAppTemplates: " संदेश सेवा /  ई-मेल/ व्हॉट्सॲप साचा",
    userAuthenticationAndRoleRights: " वापरकर्ता प्रमाणीकरण आणि भूमिका-अधिकार",
    changeResetForgetPassword:
      "बदल किंवा पुनर्प्रस्थापित किंवा पासवर्ड विसरलात",
    calendarScheduling: " दिनदर्शिका शेड्युलिंग",
    departmentCategory: "विभाग श्रेणी",
    meterStatus: "मीटर स्थिती",
    msedclCategory: "MSEDCL श्रेणी",
    billingUnitAndDivision: "बिलिंग विभाग आणि युनिट",
    subDivision: "उपविभाग",
    billingCycle: "बिलिंग सायकल",
    consumptionType: "उपभोग प्रकार",
    loadType: "लोड प्रकार",
    ebUsageType: "वापराचा प्रकार",
    phaseType: "फेज प्रकार",
    slabType: "स्लॅब प्रकार",
    division: "विभाग",
    tarriffCategory: "शुल्क श्रेणी",
    bachatGatCategory: "बचतगट श्रेणी",
    mainSchemes: "मुख्य योजना",
    bachatGatCategoryRegistration: "बचतगट श्रेणी नोंदणी",
    //other labels
    courtNameEn: "न्यायालयाचे नाव (इंग्रजी मध्ये)",
    courtNameMr: "न्यायालयाचे नाव (मराठी मध्ये)",
    addressEn: "पत्ता (इंग्रजी मध्ये)",
    addressMr: "पत्ता (मराठी मध्ये)",
    departmentCategoryEn: "विभाग श्रेणी (इंग्रजी मध्ये)",
    departmentCategoryMr: "विभाग श्रेणी (मराठी मध्ये)",
    meterStatusEn: "मीटर स्थिती (इंग्रजी मध्ये)",
    meterStatusMr: "मीटर स्थिती (मराठी मध्ये)",
    tarriffCategoryEn: "शुल्क श्रेणी (इंग्रजी मध्ये)",
    tarriffCategoryMr: "शुल्क श्रेणी (मराठी मध्ये)",
    msedclCategoryEn: "MSEDCL श्रेणी (इंग्रजी मध्ये)",
    msedclCategoryMr: "MSEDCL श्रेणी (मराठी मध्ये)",
    billingUnitEn: "बिलिंग युनिट (इंग्रजी मध्ये)",
    billingUnitMr: "बिलिंग युनिट (मराठी मध्ये)",
    divisionNameEn: "विभाग नाव (इंग्रजी मध्ये)",
    divisionNameMr: "विभाग नाव (मराठी मध्ये)",
    subDivisionEn: "उपविभाग (इंग्रजी मध्ये)",
    subDivisionMr: "उपविभाग (मराठी मध्ये)",
    billingCycleEn: "बिलिंग सायकल (इंग्रजी मध्ये)",
    billingCycleMr: "बिलिंग सायकल (मराठी मध्ये)",
    categoryPrefixEn: "श्रेणी उपसर्ग (इंग्रजी मध्ये)",
    categoryPrefixMr: "श्रेणी उपसर्ग (मराठी मध्ये)",
    categoryNoEn: "श्रेणी क्र. (इंग्रजी मध्ये)",
    categoryNoMr: "श्रेणी क्र.बिलिंग सायकल (मराठी मध्ये)",
    categoryNameEn: "श्रेणीचे नाव (इंग्रजी मध्ये)",
    categoryNameMr: "श्रेणीचे नाव (मराठी मध्ये)",
    fromDateEn: "या तारखेपासून (इंग्रजी मध्ये)",
    fromDateMr: " या तारखेपासून  (मराठी मध्ये)",
    toDateEn: "आजपर्यंत (इंग्रजी मध्ये)",
    toDateMr: "आजपर्यंत (मराठी मध्ये)",
    schemeIdEn: "स्कीमआयडी (इंग्रजी मध्ये)",
    schemeIdMr: "स्कीमआयडी (मराठी मध्ये)",
    schemeIdEn: "स्कीमआयडी (इंग्रजी मध्ये)",
    schemeIdMr: "स्कीमआयडी (मराठी मध्ये)",
    schemeNameEn: "योजनेचे नाव (इंग्रजी मध्ये)",
    schemeNameMr: "योजनेचे नाव (मराठी मध्ये)",
    schemeNoEn: "योजना क्रमांक (इंग्रजी मध्ये)",
    schemeNoMr: "योजना क्रमांक (मराठी मध्ये)",
    schemePrefixEn: "योजना उपसर्ग (इंग्रजी मध्ये)",
    schemePrefixMr: "योजना उपसर्ग (इंग्रजी मध्ये)",
    subSchemePrefixEn: "उप योजना उपसर्ग (इंग्रजी मध्ये)",
    subSchemePrefixMr: "उप योजना उपसर्ग (इंग्रजी मध्ये)",
    subSchemeNoEn: "उप योजना क्र. (इंग्रजी मध्ये)",
    subSchemeNoMr: "उप योजना क्र. (इंग्रजी मध्ये)",
    subSchemeNameEn: "उप योजनेचे नाव (इंग्रजी मध्ये)",
    subSchemeNameMr: "उप योजनेचे नाव (इंग्रजी मध्ये)",
    mainSchemeKeyEn: "मुख्य योजना की (इंग्रजी मध्ये)",
    mainSchemeKeyMr: "मुख्य योजना की (इंग्रजी मध्ये)",
    consumptionTypeEn: "उपभोग प्रकार (इंग्रजी मध्ये)",
    consumptionTypeMr: "उपभोग प्रकार (मराठी मध्ये)",
    loadTypeEn: "लोड प्रकार (इंग्रजी मध्ये)",
    loadTypeMr: "लोड प्रकार (मराठी मध्ये)",
    ebUsageTypeEn: "वापराचा प्रकार (इंग्रजी मध्ये)",
    ebUsageTypeMr: "वापराचा प्रकार (मराठी मध्ये)",
    phaseTypeEn: "फेज प्रकार (इंग्रजी मध्ये)",
    phaseTypeMr: "फेज प्रकार (मराठी मध्ये)",
    slabTypeEn: "स्लॅब प्रकार (इंग्रजी मध्ये)",
    slabTypeMr: "स्लॅब प्रकार (मराठी मध्ये)",
    address: "पत्ता",
    roadNameEn: "रस्त्याचे नाव (इंग्रजी मध्ये)",
    roadNameMr: "रस्त्याचे नाव (मराठी मध्ये)",
    roadName: "रस्त्याचे नाव ",
    landmarkEn: "महत्त्वाची खूण (इंग्रजी मध्ये)",
    landmarkMr: "महत्त्वाची खूण (मराठी मध्ये)",
    flatBuldingNoEn: "फ्लॅट बिल्डिंग क्र(इंग्रजी मध्ये)",
    flatBuldingNoMr: "फ्लॅट बिल्डिंग क्र(मराठी मध्ये)",
    buildingNameEn: "इमारतीचे नाव (इंग्रजी मध्ये)",
    buildingNameMr: "इमारतीचे नाव (मराठी मध्ये)",
    landmarkEn: "महत्त्वाची खूण (इंग्रजी मध्ये)",
    landmarkMr: "महत्त्वाची खूण (मराठी मध्ये)",
    landlineNoEn: "लँडलाइन नंबर (इंग्रजी मध्ये)",
    landlineNoMr: "लँडलाइन नंबर (मराठी मध्ये)",
    mobileNoEn: "मोबाईल नंबर (इंग्रजी मध्ये)",
    mobileNoMr: "मोबाईल नंबर (मराठी मध्ये)",
    presidentFirstNameEn: "अध्यक्ष प्रथम नाव(इंग्रजी मध्ये)",
    presidentFirstNameMr: "अध्यक्ष प्रथम नाव (मराठी मध्ये)",
    presidentMiddleNameEn: "अध्यक्ष मध्यनाव (इंग्रजी मध्ये)",
    presidentMiddleNameMr: "अध्यक्ष मध्यनाव (मराठी मध्ये)",
    presidentLastNameEn: "अध्यक्ष आडनाव(इंग्रजी मध्ये)",
    presidentLastNameMr: "अध्यक्ष आडनाव (मराठी मध्ये)",
    applicantFirstNameEn: "अर्जदाराचे प्रथम नाव(इंग्रजी मध्ये)",
    applicantFirstNameMr: "अर्जदाराचे प्रथम नाव (मराठी मध्ये)",
    applicantMiddleNameEn: "अर्जदाराचे मध्यनाव (इंग्रजी मध्ये)",
    applicantMiddleNameMr: "अर्जदाराचे मध्यनाव (मराठी मध्ये)",
    applicantLastNameEn: "अर्जदाराचे आडनाव(इंग्रजी मध्ये)",
    applicantLastNameMr: "अर्जदाराचे आडनाव (मराठी मध्ये)",
    renewalDateEn: "नूतनीकरण तारीख (इंग्रजी मध्ये)",
    renewalDateMr: "नूतनीकरण तारीख (मराठी मध्ये)",
    closingDateEn: " बंद होण्याची तारीख (इंग्रजी मध्ये)",
    closingDateMr: "बंद होण्याची तारीख (मराठी मध्ये)",
    modificationDateEn: " (इंग्रजी मध्ये)",
    modificationDateMr: "महत्त्वाची खूण (मराठी मध्ये)",
    landmarkEn: "सुधारणा तारीख (इंग्रजी मध्ये)",
    landmarkMr: "महत्त्वाची खूण (मराठी मध्ये)",
    cityOrVillageEn: "शहर / गाव (इंग्रजी मध्ये)",
    cityOrVillageMr: "शहर / गाव (मराठी मध्ये)",
    cityOrVillage: "शहर / गाव",
    pincode: "पिनकोड",
    // pincodeMr: "पिनकोड (मराठी मध्ये)",
    areaEn: "क्षेत्राचे नाव (इंग्रजी मध्ये)",
    areaMr: "क्षेत्राचे नाव (मराठी मध्ये)",
    area: "क्षेत्राचे नाव",
    name: "नाव",
    // nameMr: "नाव (मराठी मध्ये)",
    mobile: "मोबाईल नं.",
    // mobileMr: "मोबाईल नं.(मराठी मध्ये)",
    phone: "दूरध्वनी नं.",
    // phoneMr: "दूरध्वनी नं.(मराठी मध्ये)",
    email: "ई-मेल",
    // emailMr: " ई-मेल (मराठी मध्ये)",
    aadharNo: "आधार नं.",
    panNo: "पॅन नं.",
    advocateCreationEn: "वकिल यशस्वीपणे तयार केला (इंग्रजी मध्ये)",
    advocateCreationMr: "वकिल यशस्वीपणे तयार केला (मराठी मध्ये)",
    advocateDetails: "वकील तपशील",
    // advocateDetailsMr: "वकील तपशील (मराठी मध्ये)",
    // paymentrate:"पेमेंट दर",
    caseFees: "केस फी",
    paymentDetails: "देयक तपशील",
    payment: "पेमेंट",
    paidAmount: "देय रक्कम",
    paidFees: "भरलेली फी",
    feesAmount: "फी रक्कम",
    paidAmountDate: "देय रक्कम तारीख",
    remaingAmount: "उर्वरित रक्कम",
    fixedAmount: "निश्चित रक्कम",
    pendingFees: "प्रलंबित शुल्क",
    approvalFeesAmount: "मंजूरी शुल्काची रक्कम",
    billAmount: "वितरणाची रक्कम",
    bankDetails: "बँक तपशील",
    billDetails: "बिल तपशील",
    documentUpload: "दस्तऐवज अपलोड",
    titleEn: "शीर्षक (इंग्रजी मध्ये)",
    titleMr: "शीर्षक (मराठी मध्ये)",
    fnameEn: "पहिले नाव (इंग्रजी मध्ये)",
    fnameMr: "पहिले नाव (मराठी मध्ये)",
    mnameEn: "मधले  नाव (इंग्रजी मध्ये)",
    mnameMr: "मधले  नाव (मराठी मध्ये)",
    lnameEn: "आडनाव (इंग्रजी मध्ये)",
    lnameMr: "आडनाव (मराठी मध्ये)",
    advocateCategory: "वकील श्रेणी",
    nameOfBarCouncilEn:
      "वकिलांचे मंडळचे प्रमाणपत्र परिषदचे नाव (इंग्रजी मध्ये)",
    nameOfBarCouncilMr: "वकिलांचे मंडळचे प्रमाणपत्र परिषदचे नाव (मराठी मध्ये)",
    nameOfBarCouncil: "वकिलांचे मंडळचे प्रमाणपत्र परिषदचे नाव",
    remarksEn: "टिप्पणी (इंग्रजी मध्ये)",
    remarksMr: "टिप्पणी (मराठी मध्ये)",
    bankName: "बँकेचे नाव",
    branchNameEn: "शाखेचे नाव (इंग्रजी मध्ये) ",
    branchNameMr: "शाखेचे नाव (मराठी मध्ये) ",
    accountNo: "खाता क्रमांक",
    bankIFSC: "बँक IFSC कोड ",
    bankMICR: "बँक एमआयसीआर कोड",
    applicationEn: "अर्ज:(इंग्रजी मध्ये)",
    applicationMr: "अर्ज:(मराठी मध्ये)",
    aadharCardEn: "आधार कार्ड:(इंग्रजी मध्ये)",
    aadharCardMr: "आधार कार्ड:(मराठी मध्ये)",
    panCardEn: "पॅन कार्ड:(इंग्रजी मध्ये)",
    panCardMr: "पॅन कार्ड:(मराठी मध्ये)",
    barCouncilCertificateEn: "वकिलांचे मंडळचे प्रमाणपत्र:(इंग्रजी मध्ये)",
    barCouncilCertificateMr: "वकिलांचे मंडळचे प्रमाणपत्र:(मराठी मध्ये)",
    bankPassbookEn: "बँक पासबुक:(इंग्रजी मध्ये)",
    bankPassbookMr: "बँक पासबुक:(मराठी मध्ये)",
    subTypeEn: "उप-प्रकार (इंग्रजी मध्ये)",
    subTypeMr: "उप-प्रकार (मराठी मध्ये)",
    caseStagesEn: "प्रकरण-टप्पे (इंग्रजी मध्ये)",
    caseStagesMr: "प्रकरण-टप्पे (मराठी मध्ये)",
    caseStatus: "केस स्थिती",
    attachFileEn: "फाईल जोडा (इंग्रजी मध्ये)",
    attachFileMr: "फाईल जोडा (मराठी मध्ये)",
    srNo: "अनुक्रमांक",
    // srNoMr: "अनुक्रमांक (मराठी मध्ये)",
    actions: "क्रिया",
    // actionsMr: "क्रिया (मराठी मध्ये)",
    entersNumbersEn: "कृपया फक्त क्रमांक प्रविष्ट करा (इंग्रजी मध्ये)",
    entersNumbersMr: "कृपया फक्त क्रमांक प्रविष्ट करा (मराठी मध्ये)",
    caseTypeEn: "प्रकरणाचा प्रकार (इंग्रजी मध्ये)",
    caseTypeMr: "प्रकरणाचा प्रकार (मराठी मध्ये)",

    //Remarks
    selectDate: "कृपया तारीख निवडा",
    selectTitle: "कृपया शीर्षक निवडा",
    enterFName: "कृपया पहिले नाव भरा ",
    enterMName: "कृपया मधले  नाव भरा ",
    enterLName: "कृपया शेवटचे नाव भरा ",
    selectAdvocateCategory: "कृपया वकील श्रेणी निवडा",
    enterCouncilName: "कृपया वकिलांचे मंडळचे प्रमाणपत्र परिषदचे नाव भरा",
    enterArea: "कृपया क्षेत्राचे नाव भरा ",
    enterRoadName: "कृपया रस्त्याचे नाव भरा ",
    enterLandmark: "कृपया  महत्त्वाची खूण भरा",
    enterCity: "कृपया  शहराचे / गावाचे नाव भरा ",
    enterPinCode: "कृपया पिनकोड भरा",
    enterPhoneNo: "कृपया दूरध्वनी नं. भरा",
    enterMobileNo: "कृपया मोबाईल नं. भरा",
    enterEmailAddress: "कृपया ई-मेल भरा",
    enteraadhaarNo: "कृपया आधार नं. भरा",
    enterpanNo: "कृपया पॅन नं. भरा",
    // enterRemarks: 'कृपया टिप्पणी. भरा',
    enterRemarks: "कृपया टिप्पणी. द्या",
    //buttons
    // add: "जोडा",
    add: "नवीन नोंदणी",
    save: "जतन करा",
    update: "अद्यायावत करा",
    clear: "रिक्त",
    exit: "बाहेर पडा",
    back: "मागे",
    saveAndNext: "जतन करा आणि पुढे",
    next: "पुढे",
    finish: "समाप्त",
    type: "transaction",
    transaction: "व्यवहार",
    transactionPath: "कायदेशीर प्रकरण/ व्यवहार ",
    //breadcrum
    opinionPath: "कायदेशीर प्रकरण / व्यवहार /मत",
    caseEntryPath: "कायदेशीर प्रकरण / व्यवहार /प्रकरणाची नोंदणी",
    //titles
    opinion: "अभिप्राय",
    opinionEn: "अभिप्राय (इंग्रजी मध्ये)",
    opinionMr: "अभिप्राय (मराठी मध्ये)",
    caseEntry: "प्रकरणाची नोंदणी",
    //other labels
    courtName: "न्यायालयाचे नाव",
    caseType: "प्रकरणाचा प्रकार",
    courtCaseNo: "न्यायालयाचा प्रकरणाचा नं.",
    filingDate: "दाखल करण्याची तारीख",
    filedByEn: "द्वारे दाखल (इंग्रजी मध्ये)",
    filedByMr: "द्वारे दाखल (मराठी मध्ये)",
    filedBy: "द्वारे दाखल",
    filedAgainstEn: "विरुद्ध दाखल (इंग्रजी मध्ये)",
    filedAgainstMr: "विरुद्ध दाखल (मराठी मध्ये)",
    caseDetails: "प्रकरणाचा तपशील",
    advocateName: "वकीलाचे नाव",
    caseSubType: "प्रकरणाचा उप-प्रकार",
    year: "वर्ष",
    stampNo: "मुद्रांक क्रमांक",
    advocateDetails: "वकील तपशील",
    opponentAdvocate: "विरोधक वकील",
    opponentAdvocateEn: "विरोधक वकील (इंग्रजी मध्ये)",
    opponentAdvocateMr: "विरोधक वकील (मराठी मध्ये) ",
    concernPerson: "संबंधित व्यक्ती",
    concernPersonEn: "संबंधित व्यक्ती (इंग्रजी मध्ये)",
    concernPersonMr: "संबंधित व्यक्ती (मराठी मध्ये)",
    appearanceDate: "देखावा तारीख",
    deptName: "विभागाचे नाव",
    prevCourtName: "पूर्वीचे न्यायालयाचे नाव",
    document: "दस्तऐवज",
    attachFile: "फाईल जोडा",
    srNo: "अनुक्रमांक",
    actions: "क्रिया ",
    addHearing: "सुनावणी जोडा",
    //buttons
    add: "नवीन नोंदणी",
    save: "जतन करा",
    update: "अद्यायावत करा",
    exit: "बाहेर पडा",
    back: "मागे",
    saveAndNext: "जतन करा आणि पुढे",
    finish: "समाप्त",
    courtCaseNumber: "कोर्ट केस नंबर",
    hearingDate: "सुनावणीची तारीख",
    rate: "दर",
    fromDate: "या तारखेपासून",
    toDate: "आजपर्यंत",
    caseNo: "केस क्र",
    noticeDate: "सूचना तारीख",
    noticeRecivedDate: "नोटीस मिळाल्याची तारीख",
    noticeRecivedFromAdvocatePerson: "अधिवक्ता व्यक्तीकडून नोटीस प्राप्त झाली",
    requisitionDate: "मागणीची तारीख",
    noticeDetails: "सूचना तपशील",
    advocateAddress: "वकिलाचा पत्ता",
    addMore: "अधिक जोडा",
    officeLocation: "कार्यालयाचे स्थान",
    deptName: "विभागाचे नाव",
    delete: "हटवा",
    saveAndNext: "जतन करा आणि पुढे",
    exit: "बाहेर पडा",
    back: "परत",
    transferDetails: "हस्तांतरण तपशील",
    locationName: "कार्यालयाचे स्थान",
    opinionRequestDate: "अभिप्राय विनंती तारीख",
    opinionSubject: "अभिप्राय विषय",
    advPanel: "तुम्हाला पॅनेलच्या वकिलांचे मत हवे आहे का",
    reportAdvPanel: "तुम्हाला पॅनेल अॅडव्होकेटकडून शोध शीर्षक अहवाल हवा आहे का",
    advoacteName: "वकिलाचे नाव",
    submit: "प्रस्तुत करा",
    cancel: "रद्द करा",
    searchTitleReport: "शोधा शीर्षक अहवाल तारीख",
    transferAdvocate: "बदली वकील",
    hearingDetails: "सुनावणीचे तपशील",
    advocateOpinion: "वकिलांचे मत",
    advocateOpinionEn: "वकिलांचे मत (इंग्रजी मध्ये)",
    advocateOpinionMr: "वकिलांचे मत (मराठी मध्ये)",
    saveAsDraft: "मसुदा म्हणून जतन करा",
    approveOpinion: "मत मंजूर करा",
    caseRefNo: "केस संदर्भ क्रमांक",
    noticeDatae: "सूचना तारीख",
    noticeReceviedDate: "नोटीस मिळाल्याची तारीख",
    noticeReceviedFromAdvocate: "अधिवक्ता/व्यक्तीकडून नोटीस प्राप्त झाली",
    requisitionDate: "मागणीची तारीख",
    officeLocation: "कार्यालयाचे स्थान",
    employeeName: "कर्मचारी नाव",
    addMore: "आणखी जोडा",
    delete: "हटवा",
    parawiseReport: "मुद्देसुत आहवल",
    pointNo: "मुद्दा क्र",
    pointExp: "मुद्द्यांचा परिच्छेद वर उत्तर मसुदा",
    addPoint: "नवीन मुद्दे",
    issueNo: "मसुदा क्र",
    clerkRemark: "लिपिक टिप्पणी ",
    clerkRemarkEn: "लिपिक टिप्पणी (इंग्रजी मध्ये) ",
    clerkRemarkMr: "लिपिक टिप्पणी (मराठी मध्ये) ",
    concernAdvocate: "च्याशी संबंधित वकील",
    caseFees: "केस फी",
    approvalScreen: "मंजुरी स्क्रीन",
    titleNewApplicationSchemes: "योजनांसाठी नवीन अर्ज ",
    applicantAdharNo: "अर्जदार आधार क्रमांक",
    zoneNames: "झोन चे नाव",
    wardname: "प्रभागाचे नाव",
    areaNm: "क्षेत्राचे नाव",
    applicationNo: "अर्ज क्र.",
    beneficiaryCode: "लाभार्थी कोड",
    mainScheme: "मुख्य योजना",
    subScheme: "उपयोजना",
    applicantDetails: "अर्जदाराचा तपशील",
    applicantFirstName: "अर्जदाराचे प्रथम नाव",
    applicantMiddleName: "अर्जदाराचे मधले नाव",
    applicantLastName: "अर्जदाराचे आडनाव",
    gender: "लिंग",
    dateOfBirth: "जन्म तारीख",
    age: "वय",
    landmark: "सीमाचिन्ह",
    applicantAdharNo: "अर्जदार आधार क्र.",
    gisgioCode: "जीआयएस / जीआयओ कोड",
    flatBuildNo: "फ्लॅट/ इमारतीचे क्र.",
    buildingNm: "इमारतीचे नाव",
    religion: "धर्म",
    castCategory: "जाती प्रवर्ग",
    divyangSchemeType: "दिव्यांग योजनेचा प्रकार",
    disabilityCertExpDate: "अपंगत्व प्रमाणपत्राची मुदत संपण्याची तारीख",
    savingAcNo: "बचत खाते क्र",
    eligibilityDoc: "पात्रता दस्तऐवज",
    savingAcLastNm: "खाते बचत आडनाव",
    savingAcMiddleNm: "बचत खाते मधले नाव",
    savinAcFirstNm: "बचत खाते प्रथम नाव",
    eligibilityCriteria: "पात्रता निकष",
    ans: "उत्तर द्या",
    disabilityPercent: "अपंगत्व टक्केवारी",
    uploadDocs: "दस्तऐवज अपलोड करा",
    currentStatus: "वर्तमान स्थिती",
    saSanghatakRemark: "समुह संघटक टिप्पणी",
    deptClerkRemark: "झोनल लिपिक टिप्पणी",
    asstCommissionerRemark: "झोनल अधिकारी टिपणी",
    deptyCommissionerRemark: "मुख्य अधिकारी लिपिक टिप्पणी",
    approvebtn: "मंजूर",
    revertbtn: "पूर्वस्थितीवर येणे",
    welcomeToTheDashboard: "डॅशबोर्डवर आपले स्वागत आहे",
    totalTodaysCount: "आजची एकूण संख्या",
    totalPendingCount: "आजची प्रलंबित संख्या",
    totalCompletedCount: "आजची पूर्ण संख्या",
    totalCount: "एकूण संख्या",
    pendingCount: "प्रलंबित संख्या",
    completedCount: "पूर्ण संख्या",
    mainSchemeSummary: "मुख्य योजनेचा सारांश",
    subSchemeSummary: "उप योजना सारांश",
    mainSubSchemeSummary: "मुख्य योजना आणि उप योजना",
    zoneOffice: "झोन कार्यालयाचे नाव",
    mainScheme: "मुख्य योजना",
    totalApplications: "एकूण अर्ज",
    approvedApplications: "मंजूर केलेले अर्ज",
    rejectedApplications: "नाकारलेले अर्ज",
    benefiteApplications: "लाभ दिला",
    benefiteRejectedApplications: "लाभ नाही दिला",
    subScheme: "उप योजना",
    financialYear: "आर्थिक वर्ष :",
    bachatGatRegTotalCount: "एकूण बचतगट नोंदणी ",
    bachatGatRegPendingCount: "प्रलंबित बचतगट नोंदणी ",
    bachatGatRegCompletedCount: "पूर्ण बचतगट नोंदणी ",
    bachatGatCancelTotalCount: "एकूण बचतगट रद्द ",
    bachatGatCancelPendingCount: "प्रलंबित बचतगट रद्द ",
    bachatGatCancelCompleteCount: "पूर्ण बचतगट रद्द ",
    bachatGatModiTotalCount: "एकूण बचतगट सुधारणा ",
    bachatGatModiPendingCount: "प्रलंबित बचतगट सुधारणा",
    bachatGatModiCompleteCount: "पूर्ण बचतगट सुधारणा ",
    bachatGatRenewTotalCount: "एकूण बचतगट नूतनीकरण ",
    bachatGatRenewPendingCount: "प्रलंबित बचतगट नूतनीकरण ",
    bachatGatRenewCompleteCount: "पूर्ण बचतगट नूतनीकरण ",
    bachatGatReg: "बचतगट नोंदणी",
    titlaBRegTotal: "बचतगट नोंदणी (एकूण)",
    titleBRegPending: "बचतगट नोंदणी (प्रलंबित)",
    titleBRegComplete: "बचतगट नोंदणी (पूर्ण)",
    titleBCancelTotal: "बचतगट रद्द (एकूण)",
    titleBCancelPending: "बचतगट रद्द (प्रलंबित)",
    titleBCancelComplete: "बचतगट रद्द (पूर्ण)",
    titleBModiTotal: "बचतगट सुधारणा (एकूण)",
    titleBModiPending: "बचतगट सुधारणा (प्रलंबित)",
    titleBModiComplete: "बचतगट सुधारणा (पूर्ण)",
    titleRenewalTotal: "बचतगट नूतनीकरण(एकूण)",
    titleRenewalPending: "बचतगट नूतनीकरण (प्रलंबित)",
    titleRenewalComplete: "बचतगट नूतनीकरण (पूर्ण)",
    applicantName: "अर्जदाराचे नाव",
    startDate: "प्रारंभ तारीख",
    print: "छापणे",
    infoTitle: "माहिती शीर्षक",
    fileNm: "फाईलचे नाव",
    answer: "उत्तर",
    approvalSection: "मंजूरी विभाग",
    rejectedReason: "नाकारलेचे कारण",
    revertedReason: "पूर्वस्थितीचे कारण",
    paymentDate: "पेमेंट तारीख",
    chequeNo: "चेक नंबर/यूटीआर नंबर",
    rejectBtn: "नाकारले",
    accountantSection: "लेखापाल विभाग",
    totalMembersCount: "एकूण सदस्य संख्या",
    bachatgatName: "बचतगट नाव",
    presidentName: "अध्यक्षाचे नाव",
    bachatgatRegistration: "बचतगट नोंदणी",
    bachatGatDetails: "बचतगट तपशील",
    gisgioCode: "जीआयएस/जिओ कोड",
    bachatgatFullName: "बचत गट पूर्ण नाव",
    bachatgatCat: "बचत गट श्रेणी",
    bachatgatAddress: "बचत गटाचा पत्ता",
    presidentFirstName: "बचत गट अध्यक्ष प्रथम नाव",
    presidentFatherName: "बचत गट अध्यक्ष वडिलांचे नाव",
    presidentLastName: "बचतगट अध्यक्ष आडनाव",
    totalCount: "बचतगट एकूण सदस्य संख्या",
    landlineNo: "लँडलाइन क्र.",
    mobileNo: "मोबाईल नं.",
    emailId: "ई-मेल आयडी",
    accountHolderName: "खातेधारकाचे नाव",
    memberInfo: "सदस्य माहिती",
    addMore: "आणखी जोडा",
    memFullAdd: "सदस्याचा पूर्ण पत्ता",
    memFullName: "सदस्याचे पूर्ण नाव",
    memDesign: "सदस्य पद",
    memAdharNo: "सदस्य आधार क्र.",
    requiredDoc: "आवश्यक कागदपत्रे",
    fileNm: "फाईलचे नाव",
    fileType: "दस्तावेजाचा प्रकार",
    attachedDate: "जोडलेली तारीख",
    uploadFile: "फाइल्स अपलोड करा",
    addDoc: "दस्तऐवज जोडा",
    upload: "अपलोड",
    getDetails: "तपशील मिळवा",
    results: "परिणाम",
    searchArea: "क्षेत्र शोधा",
    bachatgatCancellation: "बचतगट रद्द ",
    search: "शोधा",
    cancellationSection: "रद्दीकरण विभाग",
    cancelReason: "रद्द करण्याचे कारण",
    cancelDate: "रद्द करण्याची तारीख",
    bachatgatForceFulCancellation: "बचतगट सक्तीने रद्द करणे",
    bachatgatrenewal: "बचतगट नूतनीकरण ",
    renew: "नूतनीकरण करा",
    categoryPrefix: "श्रेणी उपसर्ग",
    categoryNo: "श्रेणी क्र.",
    categoryName: "श्रेणीचे नाव",
    remark: "शेरा",
    remarkDate: "टिप्पणी तारीख",
    design: "पदनाम",
    titleSchemeApplicationRenewal: "योजना अर्ज नूतनीकरण ",

    /////////////////////////////////////////////////////////////////////////////
    // Labels added by satej
    /////////////////////////////////////////////////////////////////////////////
    informationTitleT: "माहिती शीर्षक",
    informationTitle: "माहिती शीर्षक (इंग्रजी)",
    informationTitleMr: "माहिती शीर्षक (मराठी)",
    informationType: "माहिती प्रकार",
    informationSelectionData: "माहिती निवड डेटा",
    infoDataSize: "फाईलचा आकार (Mb मध्ये)",
    installments: "हप्त्यांची संख्या",
    benefitAmount: "लाभाची रक्कम (रु. मध्ये)",
    //application summary report labels - by satej
    onlineApplicationNo: "ऑनलाइन अर्ज क्र.",
    cfcApplicationNo: "सी.एफ.सी. अर्ज क्र.",
    applicationDate: "अर्जाची तारीख",
    zoneName: "झोनचे नाव",
    zoneNameMr: "झोनचे नाव (मराठी मध्ये)",
    wardName: "प्रभागाचे नाव (इंग्रजी)",
    wardNameMr: "प्रभागाचे नाव (मराठी मध्ये)",
    beneficiaryName: "लाभार्थीचे नाव",
    beneficiaryAddress: "लाभार्थीचा पत्ता",
    aadharNo: "आधार क्र",
    mobileNo: "मोबाईल क्र",
    schemeName: "योजनेचे नाव",
    schemeNameMr: "योजनेचे नाव (मराठी मध्ये)",
    subSchemeName: "उप योजनेचे नाव (इंग्रजी)",
    subSchemeNameMr: "उप योजनेचे नाव (मराठी मध्ये)",
    download: "डाउनलोड करा",
    totalApplicationSummaryHeading: "एकूण अर्जाचा सारांश",
    benefitRejectedApplications: "लाभ नाकारलेले अर्ज",
    benefitedApplications: "लाभलेले अर्ज",
    schemeWiseSummaryHeading: "योजना निहाय सारांश",
    namunaAReportHeading: "नमुना अ ",
    namunaBReportHeading: "नमुना ब ",
    namunaCReportHeading: "नमुना क ",
    areaName: "क्षेत्राचे नाव",
    bankName: "बँकेचे नाव",
    branchName: "शाखेचे नाव",
    iFSCNo: "आय.एफ.एस.सी क्र.",
    mICRNo: "एम.आय.सी.आर क्र.",
    amount: "रक्कम",
    reasonForNonEligible: "अपात्रतेचे कारण",
    castWiseListOfBeneficiariesHeading: "लाभार्थ्यांची जातनिहाय यादी",
    castCategory: "जात प्रवर्ग",
    pimpariChinchwadMaha: "पिंपरी चिंचवड महानगरपालिका",
    appAcknowldgement: "पोच पावती",
    ackDear: "प्रिय",
    ackpcmcthanku: "पिंपरी चिंचवड नागरिक सेवा वापरल्याबद्दल धन्यवाद !!",
    ackshortDesc1:
      "पिंपरी चिंचवड महापालिकेअंतर्गत येणाऱ्या नागरिक सेवा अंतर्गत तुमचा ",
    ackshortDesc2: "बचतगट नोंदणी ",
    ackshortDesc3: "यशस्वीरीत्या सादर झाला आहे.",
    ackRTIAppealshortDesc:
      "पिंपरी चिंचवड महापालिकेअंतर्गत येणाऱ्या नागरिक सेवा अंतर्गत तुमचा माहिती अधिकार अपील अर्ज यशस्वीरीत्या सादर झाला आहे.",
    ackApplicationSummery: "अर्जाचा तपशील",
    applicationNo: "अर्जाचा क्रमांक",
    dateofApplication: "अर्ज दिनांक",
    applicationDate: "अर्ज दिनांक",
    bachatgatRegistrationDate: "नोंदणी दिनांक",
    ackplzContactNearestOperator:
      "कोणत्याही प्रश्नासाठी कृपया तुमच्या जवळच्या ऑपरेटरशी संपर्क साधा खालील संपर्क तपशील:",
    ackpcmcAddress: "मुंबई पुणे महामार्ग पिंपरी पुणे ४११-०१८",
    ackPcmcphNo: "फोन क्रमांक:९१-०२०-२७४२-५५११/१२/१३/१४",
    ackstateCountry: "महाराष्ट्र, भारत",
    applicantAddress: "अर्जदाराचा पत्ता :",
    bachatgatModification: "बचतगट बदल ",
    renewalSection: "नूतनीकरण विभाग",
    renewalRemark: "नूतनीकरण टिप्पणी",
    uploadedDoc: "अपलोड केलेले दस्तऐवज",
    RegistrationDate: "नोंदणी दिनांक",
    modificationDate: "सुधारणा तारीख",
    cancellationDate: "रद्द करण्याची तारीख",
    schemeApplicationDate: "योजनेच्या अर्जाची तारीख",
    bachatgatRenewalDate: "बचतगट नूतनीकरण दिनांक",
    schemeApplicationRenewalDate: "योजना अर्ज नूतनीकरण तारीख",
    docName: "दस्तऐवजाचे नाव",
    fileNm: "फाईलचे नाव",
    view: "पहा",
    userName: "वापरकर्ता नाव",
    bachatgatStartDate: "बचतगट प्रारंभ तारीख",
    bachatgatFromDate: "पासून तारीख आवश्यक आहे !!!",
    bachatgatToDate: "आजपर्यंत आवश्यक आहे !!!",
    schemeNameReq: "योजनेचे नाव आवश्यक आहे !!!",
    schemeNameMrReq: "योजनेचे नाव (मराठी) आवश्यक आहे !!!",
    schemeNamePrefix: "योजना उपसर्ग आवश्यक आहे !!!",
    schemeNoReq: "योजना क्रमांक आवश्यक आहे !!!",
    subSchemeNameReq: "उप योजनेचे नाव आवश्यक!!!",
    subSchemeNameMrReq: "उप योजनेचे नाव (मराठी मध्ये) आवश्यक आहे !!!",
    subSchemePrefReq: "उप योजना उपसर्ग आवश्यक आहे !!!",
    subSchemeNoReq: "उपयोजना क्रमांक आवश्यक आहे !!!",
    mainSchemeReq: "मुख्य योजना आवश्यक आहे !!!",
    fileUpload: "फाइल अपलोड करा",

    ///////////////////////////Validation Translatoin by shubham ///////////////////

    bgCategoryPrefixValidation: "श्रेणी उपसर्ग आवश्यक आहे !!!",
    bgCategoryMrValidation: "श्रेणीचे नाव (मराठी मध्ये) आवश्यक आहे !!!",
    bgCategoryNameValidation: "श्रेणीचे नाव (इंग्रजी मध्ये) आवश्यक आहे !!!",
    bgCategoryPrefixLengthValidation:
      "बचत गट उपसर्ग 15 वर्णांपेक्षा जास्त नसावा",
    bgCategoryMrCharacterValidation:
      "बचत गट श्रेणी नावात (मराठी) फक्त वर्णांना परवानगी आहे.",
    bgCategoryMrCharacterLengthValidation:
      "बचत गट श्रेणी मराठी नाव 100 वर्णांपेक्षा जास्त नसावे",
    bgCategoryNameCharacterValidation:
      "बचत गट श्रेणीच्या नावात फक्त वर्णांना परवानगी आहे.",
    bgCategoryNameLengthValidation:
      "बचत गट श्रेणीचे नाव 50 वर्णांपेक्षा जास्त नसावे",
    presidentFirstNameValidationLength:
      "अध्यक्ष नाव 50 वर्णांपेक्षा जास्त नसावे",
    presidentMiddleNameValidation: "अध्यक्ष वडीलांचे नावं आवश्यक आहे !!!",
    presidentMiddleNameValidationLength:
      "अध्यक्ष वडीलांचे नावं ५० वर्णांपेक्षा जास्त नसावे",
    presidentLastNameValidation: "अध्यक्ष आडनाव नाव आवश्यक आहे !!!",
    presidentLastNameValidationLength:
      "अध्यक्ष आडनाव नाव ५० वर्णांपेक्षा जास्त नसावे",
    totalMembersCountValidtion: "सदस्य संख्या आवश्यक आहे !!!",
    totalMembersCountValidtionLength:
      "सदस्य संख्या 2 अंकी संख्येपेक्षा जास्त नसावी",
    bachatgatNameValidation: "बचत गट नाव आवश्यक!!!",
    bachatgatNameValidationLength:
      "बचत गट पूर्ण नाव 50 वर्णांपेक्षा जास्त नसावे",
    presidentFirstNameValidation: "अध्यक्ष प्रथम नाव आवश्यक आहे !!!",
    applicantFirstNameValidtion: "अर्जदाराचे नाव आवश्यक आहे !!!",
    applicantFirstNameValidtionLength:
      "अर्जदाराचे नाव ५० वर्णांपेक्षा जास्त नसावे",
    applicantMiddleNameValidtion: "अर्जदाराचे वडीलांचे नावं आवश्यक आहे !!!",
    applicantMiddleNameValidtionLength:
      "अर्जदाराचे वडीलांचे नावं ५० वर्णांपेक्षा जास्त नसावे",
    applicantLastNameValidtion: "अर्जदाराचे आडनाव नाव आवश्यक आहे !!!",
    applicantLastNameValidtionLength:
      "अर्जदाराचे आडनाव नाव ५० वर्णांपेक्षा जास्त नसावे",
    pinCodeValidtion: "पिनकोड आवश्यक आहे !!!",
    pinCodeValidtionLength: "पिनकोड 6 वर्णांपेक्षा जास्त नसावा",
    pinCodeValidtionMinLength: "पिनकोड 6 क्रमांकाचा असावा",
    flatBuldingNoValidation: "फ्लॅट/बिल्डिंग नंबर आवश्यक आहे !!!",
    buildingNameValidation: "इमारतीचे नाव आवश्यक आहे !!!",
    roadNameValidation: "रस्त्याचे नाव आवश्यक आहे !!!",
    landmarkValidation: "लँडमार्क आवश्यक आहे !!!",
    geoCodeValidation: "जिओकोड आवश्यक आहे !!!",
    mobileNoValidation: "मोबाइल नंबर आवश्यक आहे !!!",
    emailIdValidation: "ईमेल आयडी आवश्यक आहे !!!",
    accountNoValidation: "खाते क्रमांक आवश्यक आहे !!!",
    ifscCodeValidation: "IFSC कोड आवश्यक आहे !!!",
    micrCodeValidation: "MICR कोड आवश्यक आहे !!!",
    bankAccountFullNameValidation: "खात्याचे पूर्ण नाव आवश्यक आहे !!!",
    branchNameValidation: "शाखेचे नाव आवश्यक आहे !!!",
    startDateValidation: "प्रारंभ तारीख आवश्यक आहे !!!",
    emailIdValidtionLength: "ईमेल आयडी 80 वर्णांपेक्षा जास्त नसावा",
    accountNoValidtionLength: "खाते क्रमांक 18 पेक्षा जास्त नसावे",
    ifscCodeValidtionLength: "IFSC कोड 11 पेक्षा जास्त नसावा",
    ifscCodeValidationMinLength: "IFSC कोड 11 क्रमांकाचा असावा",
    micrCodeValidtionLength: "MICR कोड 9 पेक्षा जास्त नसावा",
    micrCodeValidtionMinLength: "MICR कोड 9 क्रमांकाचा असावा",
    landlineNoValidtionMinLength: "दूरध्वनी क्रमांक 10 क्रमांकाचा असावा",
    landlineNoValidtionLength: "दूरध्वनी क्रमांक 10 पेक्षा जास्त नसावा",
    bankAccountFullNameValidtionLength:
      "खात्याचे पूर्ण नाव 500 वर्णांपेक्षा जास्त नसावे",
    branchNameValidtionLength: "शाखेचे नाव ५० वर्णांपेक्षा जास्त नसावे",
    areaKeyValidation: "क्षेत्राचे नाव आवश्यक आहे !!!",
    zoneKeyValidation: "झोनचे नाव आवश्यक आहे !!!",
    wardKeyValidation: "वॉर्ड नाव आवश्यक आहे!!!",
    surNameValidation: "आडनाव आवश्यक आहे!!!",
    benecodeValidation: "लाभार्थी कोड आवश्यक आहे !!!",
    mainSchemeKeyValidation: "मुख्य योजना आवश्यक आहे !!!",
    subSchemeKeyValidation: "उप योजना आवश्यक आहे!!!",
    genderValidation: "लिंग आवश्यक आहे !!!",
    applicantAadharNoValidation: "अर्जदार आधार क्रमांक आवश्यक आहे !!!",
    applicantAadharNoValidationMinLength:
      "आधार क्रमांक किमान 12 क्रमांकाचा असावा",
    applicantAccountNoValidationMinLength:
      "बचत खाते क्रमांक किमान 6 क्रमांकाचा असावा",
    applicantAadharNoValidationLength:
      "आधार क्रमांक 12 क्रमांकापेक्षा जास्त नसावा",
    dateOfBirthValidation: "जन्मतारीख आवश्यक आहे !!!",
    ageValidation: "वय आवश्यक आहे",
    agePtvValidation: "वय ही सकारात्मक संख्या असणे आवश्यक आहे",
    ageIntValidation: "वय पूर्णांक असणे आवश्यक आहे",
    ageValidationLength: "वय १८ वर्षे किंवा त्यापेक्षा जास्त असणे आवश्यक आहे",
    religionKeyValidation: "धर्म आवश्यक आहे !!!",
    casteCategoryValidation: "जात प्रवर्ग आवश्यक आहे !!!",
    bachatGatCategoryValidation: "बचत खाते प्रवर्ग आवश्यक आहे !!!",
    disabilityCertificateValidityValidation:
      "अपंगत्व प्रमाणपत्राची वैधता आवश्यक आहे !!!",
    bankBranchKeyValidation: "बँकेची शाखा आवश्यक आहे !!!",
    savingAccountNoValidation: "बचत खाते क्रमांक आवश्यक आहे !!!",
    savingAccountNoValidationLength: "खाते क्रमांक 18 पेक्षा जास्त नसावे",
    saOwnerFirstNameValidation: "बचत खाते प्रथम नाव आवश्यक आहे !!!",
    saOwnerFirstNameValidationLength:
      "सेव्हिंग खाते प्रथम नाव 50 वर्णांपेक्षा जास्त नसावे",
    saOwnerMiddleNameValidation: "बचत खाते मधले नाव आवश्यक आहे !!!",
    saOwnerMiddleNameValidationLength:
      "सेव्हिंग अकाउंट मधले नाव 50 वर्णांपेक्षा जास्त नसावे",
    saOwnerLastNameValidation: "सेव्हिंग अकाउंट आडनाव आवश्यक आहे !!!",
    saOwnerLastNameValidationLength:
      "सेव्हिंग खाते आडनाव 50 वर्णांपेक्षा जास्त नसावे",
    surNameValidationLength: "आडनाव 50 वर्णांपेक्षा जास्त नसावे",
    schemeNameReqLength: "योजनेचे नाव 50 वर्णांपेक्षा जास्त नसावे",
    schemeNameReqMrLength: "योजनेचे नाव (मराठी) १०० वर्णांपेक्षा जास्त नसावे",
    schemeNamePrefixLength: "योजना उपसर्ग 15 वर्णांपेक्षा जास्त नसावे",
    infoTitleRequiredLength: "माहिती शीर्षक 50 वर्णांपेक्षा जास्त नसावे",
    subSchemeNameReqLength: "उप योजनेचे नाव ५० वर्णांपेक्षा जास्त नसावे",
    subSchemeNameMrReqLength:
      "उप योजनेचे नाव (मराठी) 100 वर्णांपेक्षा जास्त नसावे",
    subSchemePrefReqLength: "उप योजनेचे उपसर्ग 15 वर्णांपेक्षा जास्त नसावा",
    benefitAmountReq: "लाभाची रक्कम आवश्यक आहे",
    installmentsReq: "हप्त्यांची संख्या आवश्यक आहे",
    schemePrefixT: "योजना उपसर्ग",
    schemeNameT: "योजनेचे नाव",
    totalMembersCountValidation:
      "एकूण सदस्य संख्या 20 च्या समान किंवा कमी असणे आवश्यक आहे",
    totalMembersCountRequiredValidation: "एकूण सदस्य संख्या आवश्यक आहे",

    /////////////////sub scheme label changes by shubham //////////////
    subSchemePrefix: "उप योजना उपसर्ग",
    mainSchemeNameT: "मुख्य योजनेचे नाव",
    subSchemeNameT: "उप योजनेचे नाव",
    subSchemeNo: "उप योजना क्र.",
    subschemeTitle: "उप योजना",
    subSchemeNameFEn: "उप योजनेचे नाव (इंग्रजी मध्ये)",

    /////////////////////////main scheme error msg by shubham ///////////////
    allowSchemeNameReq: "योजना उपसर्गमध्ये फक्त वर्ण परवानगी आहे.",
    allowschemeNamePrefix:
      "योजना उपसर्गमध्ये फक्त वर्ण आणि संख्यांना परवानगी आहे.",
    allowschemeNoReq: "योजना उपसर्गमध्ये फक्त संख्यांना परवानगी आहे..",
    infoTitleRequired: "माहितीचे शीर्षक आवश्यक आहे !!!",
    infoTypeRequired: "माहितीचे प्रकार आवश्यक आहे !!!",
    aadharErrorMsg: "सदस्य आधीच अस्तित्वात आहे !!!",
    schemeConfigData: "पात्रता निकष आणि दस्तऐवज मास्टर",
    benefitAmountReq: "लाभाची रक्कम आवश्यक आहे",
    noOfInstallmentReq: "हप्त्यांची संख्या आवश्यक नाही",
    CompleteBtn: "पूर्ण",
    requiredMessage: " कृपया हे फील्ड भरा ",
    applicationName: "अर्जाचे नाव",
    helpDeskBSUP: "समाज विकास विभाग हेल्प डेस्क",
    newSchemeApplicationCount: "योजना अर्ज एकूण संख्या",
    bachatgatNo: "बचत गट क्र.",
    guideline1:
      "१) अर्जदाराने अर्ज पिंपरी चिंचवड महानगरपालिका यांच्या संकेत स्थळावर जाऊन समाज विकास या विभागावर क्लिक करुन आँनलाईन पध्दतीने अर्ज करता येणार.",
    guideline2:
      "२) अर्जदार हा पिंपरी चिंचवड महानगरपालिका यांच्या हद्दीमधील असणे आवश्यक आहे.",
    guideline3: "३) चिन्हांकित फील्ड अनिवार्य आहेत तर इतर पर्यायी आहेत.",
    guideline4:
      "४) क्षेत्रीय कार्यालयामार्फत अर्जाची पात्र / अपात्र तपासणी केल्या जाईल.",
    guideline5:
      "५) पात्र असलेली यादी किंवा अर्ज पिंपरी चिंचवड महानगरपालिका मुख्य कार्यालय मध्ये समाज विकास विभागाकडे पाठविला जाईल.",
    guideline6:
      "६) पात्र असलेल्या लाभार्थीना लाभ देण्याची कार्यवाही समाज विकास विभागामार्फत केली जाईल.",
    guideline7:
      "७) अर्जदाराने अर्जासोबत पिंपरी चिंचवड महानगरपालिका हद्दीमधील आधारकार्ड जोडणे आवश्यक.",
    guideline8:
      "८) अर्जदाराने आवश्यक असलेले मुळ कागदपत्र योग्य रित्या स्कँन करुन दिलेल्या योजने नुसार अपलोड करण्यात यावे. ",
    guideline9:
      "९) अर्जदाराने आपला आधार क्रमांक आणि मोबाईल (भ्रमणध्वनी) क्रमांक योग्य रित्या तपासुन अर्ज करावा.",
    guideline10:
      "१०) अर्जदाराने चुकीचा आधार क्रमांक अर्जामध्ये नमुद केल्यास त्याचा अर्ज हा अपात्र करण्यात येईल याची नोंद अर्जदाराने घेण्यात यावी ही विनंती.",

    guideline11: "",
    guideline12: "१२) मार्गदर्शक सूचना 12.",
    guideline13: "१३) मार्गदर्शक सूचना 13.",
    guideline14: "१४) मार्गदर्शक सूचना 14.",
    guideline15: "१५)  मार्गदर्शक सूचना 15.",
    guideline16: "१६)  मार्गदर्शक सूचना 16.",
    guideline17: "१७)  मार्गदर्शक सूचना 17.",
    guideline18: "१८)  मार्गदर्शक सूचना 18.",
    guideline19: "१९)  मार्गदर्शक सूचना 19.",
    guideline20: "२०)  मार्गदर्शक सूचना 20.",
    guideline21: "२१) मार्गदर्शक सूचना 21.",
    guideline22: "२२) मार्गदर्शक सूचना 22.",
    guideline23: "२३) मार्गदर्शक सूचना 23.",
    guideline24: "२४) मार्गदर्शक सूचना 24.",
    guideline25: "२५) मार्गदर्शक सूचना 25.",
    Tnc: "नियम व अटी",
    bsupTermsndTitle: "पिंपरी चिंचवड महानगरपलिका,पिंपरी-४११०१८",
    rtiAct2005: "समाज विकास विभाग ",
    guidelineOfBsup:
      "समाज विकास विभागाच्या ऑनलाइन पोर्टलच्या वापरासाठी मार्गदर्शक तत्त्वे",
    fullNameRequiredLength: "पूर्ण नाव 30 वर्णांपेक्षा जास्त नसावे",
    addressRequired: "पत्ता आवश्यक आहे",
    addressRequiredLength: "पत्ता 100 वर्णांपेक्षा जास्त नसावा",
    fullNameRequired: "पूर्ण नाव आवश्यक आहे",
    designRequired: "पदनाम आवश्यक आहे",
    adharNoRequired: "आधार क्र. आवश्यक आहे",
    rejectCat: "श्रेणी निवडा",
    rejectCatMr: "श्रेणी निवडा (मराठी)",
    rejectCatReq: "श्रेणी निवडा आवश्यक आहे",
    rejectCatMrReq: "श्रेणी निवडा (मराठी) आवश्यक आहे",
    existingBachatGat: "विद्यमान बचत गट",
    newBachatGat: "नवीन बचत गट",
    oldBachatGatNo: "विद्यमान बचत गट क्र",
    oldBachatGatRegiDate: "विद्यमान बचत गट नोंदणी तारीख",
    isSchemeForBachatGat: "बचत गटासाठी ही उप योजना लागू आहे का?",
    isForBachatOrScheme: "बचत गट किंवा योजना अर्जासाठी",
    isForBachatOrSchemeReq: "बचत गट किंवा योजना अर्जासाठी आवश्यक आहे",
    forBachatGatOrScheme: "बचत गट किंवा योजनेसाठी",
    benefitTitle: "लाभाची रक्कम",
    installment: "हप्ते",
    exitTNC: "बाहेर पडा",
    castOption: "जात पर्याय",
    paidInstallments: "लाभ दिलेले हप्ते",
    installmentAmount: "हप्त्याची रक्कम",
    downloadCertificate: "सर्टिफिकेट डाउनलोड करा",
    patraApatra: "मंजूर केलेले/परत केलेले",
    showAll: "सर्व दाखवा",

    cfcackNo: "सी. फ. सी. पावती क्र",
    totalApplication: "एकूण अर्ज",
    approvedApplication: "मंजूर अर्ज",
    revertedApplication: "परत केलेले अर्ज",
    rejectedApplication: "नाकारलेले अर्ज",
    hasBenefit: "लाभ दिला आहे का?",
    bachatApplicationDate: "बचतगट अर्जाची तारीख",
    close: "बंद",
    bachatApplicationNo: "Bachatgat Application No",
    applicantFullName: "अर्जदाराचे पूर्ण नाव",
    applicantFullNameMr: "अर्जदाराचे पूर्ण नाव (मराठी)",

    currInstallmentNumber: "वर्तमान हप्ता क्रमांक",
    installmentAmt: "हप्त्याची रक्कम",
    installmentDate: "हप्त्याची तारीख",
    chequeNo: "चेक क्र",
    note: "टीप",
    categoryType: "श्रेणी प्रकार",
    categoryTypeReq: "श्रेणी प्रकार आवश्यक आहे",

    isMandatory: "अनिवार्य आहे का?",
    remarkSectionHeader: "टिप्पणी विभाग",
    approveCategory: "श्रेणी मंजूर करा",
    revertCategory: "टिप्पणी निवडा",

    pendingApplication: "प्रलंबित अर्ज",


    question1:
      "बचतगटातील महिलांनी प्रशिक्षण घेतले आहे का ? होय असल्यास कोणते ? ",
    question2: "बचतगट कोणता व्यवसाय करतो का ? होय असल्यास कोणता ? ",
    question3:
      "बचतगटातील महिला वैयक्तिक व्यवसाय करतात का ? होय असल्यास कोणता ?",
    yes: "होय",
    no: "नाही",
     mahilaPrashikshan: "महिला प्रशिक्षणाचे नाव",
     vyavsayacheNav:'व्यवसायाचे नाव ',
    vVyasaycheNav:'वैयक्तिक व्यवसायाचे नाव ',
    panNumber: "पॅन क्रमांक",
    iAgree: "मी सहमत आहे",
    selfDeclaration: "स्वयंघोषणापत्र",

  },
};
