export default {
  en: {
    petLicense: "Pet License",
    petAnimal: "Pet Animal",
    area: "Area",
    zone: "Zone",
    ward: "Ward",
    flatOrHouseNo: "Flat/House No.",
    buildingName: "Building Name",
    detailAddress: "Detail Address",
    ownerName: "Owner Name",

    fNameEn: "First Name (In English)",
    mNameEn: "Middle Name (In English)",
    lNameEn: "Last Name (In English)",
    fNameMr: "First Name (In Marathi)",
    mNameMr: "Middle Name (In Marathi)",
    lNameMr: "Last Name (In Marathi)",

    mobileNo: "Mobile no.",
    emailId: "Email ID",
    //buttons
    add: "Add",
    save: "Save",
    update: "Update",
    clear: "Clear",
    exit: "Exit",
    back: "Back",
    saveAndNext: "Save & Next",
    finish: "Finish",
    print: "Print",
    oldP: "Old Password",
    newP: "New Password",
    confirmP: "confirm Password",
    changeP: "Change Password",
    resetP: "Reset Password",

    pdfOnly: "(Upload PDF only)",
    imageOnly: "(Upload image only)",
    imageAndPDF: "(Upload image or PDF only)",
  },
  mr: {
    petLicense: "पाळीव प्राणी परवाना",
    petAnimal: "पाळीव प्राणी",
    area: "क्षेत्र",
    zone: "झोन",
    ward: "प्रभाग",
    flatOrHouseNo: "फ्लॅट/घर क्र.",
    buildingName: "इमारतीचे नाव",
    detailAddress: "पूर्ण पत्ता",
    ownerName: "मालकाचे नाव",

    fNameEn: "पाहिलं नाव (इंग्रजीत)",
    mNameEn: "मधलं नाव (इंग्रजीत)",
    lNameEn: "शेवटचं नाव (इंग्रजीत)",
    fNameMr: "पाहिलं नाव (मराठीत)",
    mNameMr: "मधलं नाव (मराठीत)",
    lNameMr: "शेवटचं नाव (मराठीत)",

    mobileNo: "मोबाईल नं",
    emailId: "इमेल पत्ता",

    //buttons
    add: "जोडा",
    save: "जतन करा",
    update: "अद्यायावत करा",
    clear: "रिक्त",
    exit: "बाहेर पडा",
    back: "मागे",
    saveAndNext: "जतन करा आणि पुढे",
    finish: "समाप्त",
    print: "छापणे",
    oldP: "जुना पासवर्ड",
    newP: "नवीन पासवर्ड",
    confirmP: "पासवर्डची पुष्टी करा",
    changeP: "पासवर्ड बदला",
    resetP: "पासवर्ड बदला",

    pdfOnly: "(फक्त PDF अपलोड करा)",
    imageOnly: "(फक्त चित्र अपलोड करा)",
    imageAndPDF: "(फक्त चित्र किंवा PDF अपलोड करा)",
  },
};
