export default {
  en: {
    distanceFromBuildingToOpenSpace: "Distance From Building TO Open Space",
    isPodiumRampExists: "Is Podium Ramp Exists",
    noOfPodiumRamp: "No Of Podium Ramp",
    podiumRampWidth: "Podium Ramp Width",
    isBasementExists: "Is Basement Exists",
    noOfBasement: "No Of Basement",
    isFireLiftGiven: "Is Fire Lift Given",
    noOfFireLift: "No Of Fire Lift",
    capacityOfFireLift: "Capacity Of Fire Lift",
    isFireStairCaseGiven: "Is Fire StairCase Given",
    noOfFireStairCase: "No Of Fire StairCase",
    widthOfFireStairCase: "Fire StairCase Width",

    tankLocation: "Tank Location",
    tankType: "Tank Type",
    approachRoad: "Approach Road",
    direction: "Direction",
    roadSize: "Road Size",
    totalOverheadCapacity: "Total Overhead Water Tank Capacity",
    totalUndergroundCapacity: "Total Under Ground Water Tank Capacity",
    isPlanhaveUnderGroundWaterTank: "Is Plan have Common Water Tank",
    documentVerification: "DOCUMENT VERIFICATION",
    applicationDtlHeading: "Basic Application Details",
    applicationStatus: "Application Status",
    documentPreview: "Document Preview",
    type: "commonLabels",

    // fireBridageSystem: "Fire Brigade System",
    module: "Fire Brigade System",
    // dashboard: 'PCMC Dashboard',
    dashboard: "Pimpri-Chinchwad Municipal Corporation Dashboard",
    masters: "Masters",
    transactions: "Transactions",
    reports: "Reports",
    masterPath: "FIRE BRIGADE SYSTEM / masters",
    transactionPath: "Legal Case / Transaction ",
    reportPath: "Legal Case / Report ",

    type: "masters",
    masters: "Masters",
    masterPath: "FIRE BRIGADE SYSTEM / masters",

    //breadcrum
    typeOfBuildingPath: "FIRE BRIGADE SYSTEM / masters / Type Of Building ",
    purposeOfBuildingPath:
      "FIRE BRIGADE SYSTEM / masters / Purpose Of Building ",
    typeOfNocPath: "/FireBrigadeSystem/masters/typeOfNoc",
    usageTypeMasterPath: "FIRE BRIGADE SYSTEM / masters / Usage Type Master",
    typeOfBusinessPath: "FIRE BRIGADE SYSTEM / masters / Type Of Business",
    vardiTypeMasterPath: "FIRE BRIGADE SYSTEM / masters / Vardi Type Master",
    fireStationDetailsPath:
      "FIRE BRIGADE SYSTEM / masters / Fire Station Details",
    employeeShiftMasterPath:
      "FIRE BRIGADE SYSTEM / masters / Employee Shift Master",
    vehicleDetailsPath: "FIRE BRIGADE SYSTEM / masters / Vehicle Details",
    vehicleTypesPath: "FIRE BRIGADE SYSTEM / masters / Vehicle Types",
    firstAhawalPath: "FIRE BRIGADE SYSTEM / firstAhawal",
    finalAhawalPath: "FIRE BRIGADE SYSTEM / finalAhawal",
    provisionalBuildingNocPath: "FIRE BRIGADE SYSTEM / provisionalBuildingNoc",
    revisedBuildingNocPath: "FIRE BRIGADE SYSTEM / revisedBuildingNoc",
    finalBuildingNocPath: "FIRE BRIGADE SYSTEM / finalBuildingNoc",
    occuranceBookEntry: "FIRE BRIGADE SYSTEM / Occurance Register",
    businessNocPath: "FIRE BRIGADE SYSTEM / businessNoc",

    //label title

    typeOfBuildingTitle: "Type Of Building",
    purposeOfBuildingTitle: "Purpose Of Building",
    typeOfNocTitle: "Type Of NOC",
    usageTypeMasterTitle: "Usage Type Master",
    typeOfBusinessTitle: "Type Of Business",
    vardiTypeMasterTitle: "Vardi Type Master",
    fireStationDetailsTitle: "Fire Station Details",
    employeeShiftMasterTitle: "Employee Shift Master",
    vehicleDetailsTitle: "Vehicle Details",
    vehicleTypesTitle: "Vehicle Types",
    reasonOfFireTitle: "Probable Cause Of Fire",

    //other labels
    typeOfBuilding: "Type Of Building (In English)",
    typeOfBuildingMr: "Type Of Building (In Marathi)",
    gISID: "GIS ID",
    gISIDMr: "GIS ID (In Marathi)",
    fireStationName: "Fire Station Name (In English)",
    fireStationNameMr: "Fire Station Name (In Marathi)",
    address: "Address (In English)",
    addressMr: "Address (In Marathi)",
    vTSSystemID: "VTS System ID",
    // vTSSystemIDMr: "VTS System ID (In Marathi)",
    gPSDeviceId: "GPS Device ID",
    // gPSDeviceIdMr: "GPS Device ID (In Marathi)",
    vehicleType: "Vehicle Type (In English)",
    vehicleTypeF: "Vehicle Type",
    vehicleTypeMr: "Vehicle Type (In Marathi)",
    vehicleNumber: "Vehicle Number ID",
    stationOutTime: "Station Out time",
    vehicleReachedAtLocationTime: "Vehicle Reached At Location Time",
    pumpingTime: "Pumping Time",
    vehicleLeaveAtLocationTime: "Vehicle Leave At Location Time",
    vehicleInTimeAtFireStation: "Vehicle In Time At Fire Station",
    vehicleKm: "Vehicle Km",
    vehicleName: "Vehicle Name (In English)",
    vehicleNameMr: "Vehicle Name (In Marathi)",
    reasonOfFire: "Probable Cause Of Fire (In English)",
    reasonOfFireMr: "Reason Of Fire (In Marathi)",

    // vehicleNumberMr: "Vehicle Number (In Marathi)",
    vardiName: "Vardi Name (In English)",
    vardiNameMr: "Vardi Name (In Marathi)",
    buildingPurpose: "Building Purpose (In English)",
    buildingPurposeMr: "Building Purpose  (In Marathi)",
    nOCName: "NOC Name (In English)",
    nOCNameMr: "NOC Name (In Marathi)",
    nameOfUsage: "Name Of Usage (In English)",
    nameOfUsageMr: "Name Of Usage (In Marathi)",
    typeOfBusiness: "Type Of Business (In English)",
    typeOfBusinessMr: "Type Of Business (In Marathi)",
    fireStationName: "Fire Station Name (In English)",
    fireStationNameMr: "Fire Station Name (In Marathi)",
    ward: "Ward",
    zone: "Zone",
    latitude: "Latitude",
    Longitude: "Longitude",
    longitude: "Longitude",
    shiftName: "Shift Name (In English)",
    shiftNameMr: "Shift Name (In Marathi)",
    shiftStartTime: "Shift Start Time",
    shiftEndTime: "Shift End Time",
    nameOfCFO: "Name Of CFO",
    nameOfSFO: "Name Of SFO",
    nameOfOtherEmployee: "Name Of Other Employee",
    addMore: "Add More",

    // Master Form Header
    businessType: "Business Types",
    addBuilding: "Add - Type Of Building",
    updateBuilding: "Update - Type Of Building",
    addPBuilding: "Add - Purpose Of Building",
    updatePBuilding: "Update - Purpose Of Building",
    addNocName: "Add - Noc Name",
    updateNocName: "Update - Noc Name",
    addUsage: "Add - Usage Type",
    updateUsage: "Update - Usage Type",
    addBusinessT: "Add - Type Of Business",
    addRegistrationFees: "Add - Registration Fees",
    updateBusinessT: "Update - Type Of Business",
    addVardiT: "Add - Vardi Type",
    updateVardiT: "Update - Vardi Type",
    addEmp: "Add - Employee Shift",
    updateEmp: "Update -Employee Shift",
    addFireStation: "Add - Fire Station Details",
    updateFireStation: "Update -Fire Station Details",
    addVehicleDetails: "Add - Vehicle Details",
    updateVehicleDetails: "Update - Vehicle Details",

    // Table header
    // typeOfBuildingT: "Type Of Building (In English)",
    // typeOfBuildingMrT: "Type Of Building (In Marathi)",
    // buildingPurposeT: "Building Purpose (In English)",
    // buildingPurposeMrT: "Building Purpose (In Marathi)",
    // nOCNameT: "NOC Name (In English)",
    // nOCNameMrT: "NOC Name (In Marathi)",
    // nameOfUsageT: "Name Of Usage (In English)",

    // typeOfBusinessT: "Type Of Business (In English)",
    // typeOfBusinessMrT: "Type Of Business (In Marathi)",
    // vardiNameT: "Vardi Name (In English)",
    // vardiNameMrT: "Vardi Name (In Marathi)",

    //Remarks
    selectDate: "Please select a date",
    selectTitle: "Please select a title",
    enterFName: "Please enter first name ",
    enterMName: "Please enter middle name ",
    enterLName: "Please enter last name ",
    selectAdvocateCategory: "Please select a category",
    enterCouncilName: "Please enter council name",
    enterArea: "Please enter area ",
    enterRoadName: "Please enter road name ",
    enterLandmark: "Please enter a landmark ",
    enterCity: "Please enter a city ",
    enterPinCode: "Please enter a pincode ",
    enterPhoneNo: "Please enter a phone no. ",
    enterMobileNo: "Please enter a mobile no. ",
    enterEmailAddress: "Please enter an e-mail. ",
    enteraadhaarNo: "Please enter an aadhaar no. ",
    enterpanNo: "Please enter an pan no. ",
    enterRemarks: "Please enter a remark. ",

    attachFile: "Attach File",
    srNo: "Sr.No",
    actions: "Actions",

    //buttons
    add: "Add",
    save: "Save",
    update: "Update",
    clear: "Clear",
    exit: "Exit",
    back: "Back",
    saveAndNext: "Save & Next",
    finish: "Finish",

    type: "transactions",
    transactions: "Transactions",
    transactionPath: "Legal Case / Transaction ",
    actions: "Actions",

    // report
    date: "Date",
    time: "Time",
    approverName: "Approver Name",
    receipt: "Receipt",
    receiptNo: "Receipt No",
    receiptDate: "Receipt Date",
    allServices: "All Services",
    myApplication: "My Application",
    modeOfPayment: "Mode of payment",
    issueDate: "Issue Date",
    selectService: "Select Service",
    selectNocNumber: "Select No cNumber",
    search: "Search",
    nameOfApplicant: "Name of applicant",
    addressOfApplicant: "Address of Applicant",
    print: "Print",
    view: "View",
    reset: "Reset",
    submit: "Submit",
    receiptCapital: "RECEIPT",
    fireDepartment: "Fire Department",
    nocNo: "NOC No",
    partyName: "Party Name",
    loiNo: "LOI No",
    partyAddress: "Party Address",
    loiDate: "LOI Date",
    financialYear: "Financial Year",
    fireCertificate: "Fire Certificate",
    transactionId: "Transaction Id",
    total: "Total",
    paymentType: "Payment Type",
    pay: "Pay",
    amountInWord: "Amount in Word",
    amountInWordMr: "Amount in Word (In Marathi)",
    description: "Description",
    onlinePayment: "Online Payment/ Dept",
    printedBy: "Printed by",
    dateAndTime: "Date & Time",
    addressDeatils: "Address Details",
    termAndCondition: "Term and condition",
    applicationName: "Application Name",
    applicationType: "Application Type",
    serviceId: "Service Name",
    siteVistType: "Site Visit Type",
    visitDate: "Visit Date",
    siteVisitDetails: "Site Visit Details",
    vardiTime: "Vardi Time",
    isExternalEmployeeAddedInDuty:
      "is External Person(Employee) added in duty?",

    //label
    occupancyFireCertificate: "Occupancy Fire Certificate",
    finalFireNOCNumber: "Final Fire NOC Number",
    applicationDate: "Application Date",
    officeContactNo: "Office Contact No",
    personMobileNo: "working site Onsite person Mobile No",
    emailId: "Email Id",
    appliedFor: "Applied For",
    architectName: "Architect Name ",
    architectFirmName: "Architect Firm Name",
    architectRegistrationNo: "Architect Registration No",
    applicantPermanentAddress: "Applicant Permanent Address",
    siteAddress: "Site Address",
    applicantContactNo: "Applicant contact No",
    FinalPlotNoFP: "Final Plot No - (F.P)",
    RevenueSurveyNoRS: "Revenue Survey No ( R.S.)",
    BuildingLocation: "Building Location",
    townPlanningNo: "Town Planning No",
    blockNo: "Block No",
    OPNo: "O.P. No",
    citySurveyNo: "City Survey No",
    typeofBuilding: "Type Of Building",
    residentialUse: "Residential Use",
    commercialUse: "commercial use",
    NOCFor: "NOC For",
    buildingHeight: "Building Height from Ground Floor in Meter",
    // noOfBasement: "No of Basement",

    totalBuilding: "Total Building Floor (G+)",
    basementArea: "Basement Area in square Meter",
    noOfVentilation: "No Of Ventilation",
    noOfTowers: "No Of Towers",
    plotArea: "Plot area square Meter",
    construction: "construction are sq meter",
    noOfApprochedRoad: "No of Approched road",
    drawingProvided: "Drawing Provided",
    siteAddressWithName: "Site Address (with Building Name)",
    highTensionLineMac:
      "High Tension Line, Mac Grid Channel Railway Crossing information",
    areaZone: "Area Zone",
    fireNocTaken: "Previously Any Fire Noc Taken",
    underTheGroundWaterTank: "Under the Ground water Tank capacity Lighter",
    l: "L",
    b: "B",
    h: "H",
    volumeLBH: "Volume LBH in ( M³)",
    approvedMap: "Approved map of Underground water Tank",
    overHeadWaterTank: "Over head water Tank Capacity in Liter",
    OverHearWaterTank: "Over Hear water Tank co approved Maps",
    corporationName: "Corporation Name",
    applicationNo: "Application No",
    corporationLogo: "Corporation Logo",
    departmentLogo: "Department Logo ",
    sanctionDate: "Sanction Date",
    proposedSiteAddress: "Proposed Site Address",
    plotDetails: "Plot Details",
    buildingDetails: "Building Details",
    conditions: "Conditions",
    occurrenceBookEntry: "Occurrence Book Entry",
    occuranceNo: "Occurance No",
    dateOfIncident: "Date Of Incident",
    timeOfIncident: "Time Of Incident",
    occuranceDetails: "Occurance Details",
    occuranceDetailsMr: "Occurance Details (In Marathi)",
    informerDetails: "Caller Informer Details",
    addressOfInformer: "Address of Informer",
    incidanceTookPlace: "Incidance took Place",
    damageDetails: "Damage Details",
    occurancePcmcArea: "Occurance Within PCMC Area",
    chargesIfOutsidePCMC: "Charges if Outside PCMC",
    detailsOfIncidentSite: "Details Description of incident Site",
    remark: "Remark",
    uploadImages: "Upload Images",
    geoLocation: "GEO Location of Site",
    vardiAhalNumber: "Vardi Ahawal Number",
    causeOfFire: "Cause Of Fire",
    ownerName: "Owner Name",
    ownerFirstName: "Owner First Name",
    ownerFirstNameMr: "Owner First Name (In Marathi)",
    detailsDescriptionOfIncidentSite: "Details Description Of Incident Site",
    detailsDescriptionOfIncidentSiteMr:
      "Details Description Of Incident Site (In Marathi)",
    gEOLocationOfSite: "GEO Location Of Site",
    vehicleDetails: "Vehicle Details",
    nocTypes: "Business Types",
    nocNumber: "Noc Number",
    noOfRooms: "Number Of Rooms",
    businessNocId: "Business Noc Id",
    nocAreaForPetrolPumpInSqMtrs: "Noc Area For Petrol Pump In Sq. Mtrs.",
    noOfDespesingUnit: "No Of Despesing Unit",
    lengthOfCascadeForCNG: "Length Of Cascade For CNG",
    widthOfCascadeForCNG: "Width Of Cascade For CNG",
    foodAndDrugSafetyLicenseCopy: "Food And Drug Safety License Copy",
    noOfBeds: "Number Of Beds",
    noOfScreen: "Number Of Screen",
    eachScreenSeatingCapacity: "Each Screen Seating Capacity",
    typesOfCompany: "Types Of Company",
    businessDetails: "Business Details",
    rawMaterialDetails: "Raw Material Details",
    finalMaterialDetails: "Final Material Details",
    listOfHazardousMaterial: "List Of Hazardous Material",
    emergencyContactPersonDetails: "Emergency Contact Person Details",
    requireNocForHospitalInSqMtrs: "Require Noc For Hospital In Sq. Mtrs.",

    // Buisness Types
    applicationNumber: "Application Number",
    hotelArea: "Hotal Area in Square Meter",
    starHotel: "Star Hotel",
    ownerDetails: "Owner Details",
    applicantAddresss: "Applicant Address",
    applicantAddresssMr: "Applicant Address",
    chauMeter: "Square Meter",

    //breadcrum
    opinionPath: "Legal Case/ Transactions/ Opinion",
    caseEntryPath: "Legal Case/ Transactions/ Case Entry",
    vardiSlipPath: "FIRE BRIGADE SYSTEM/ Emergency Services",
    renewalOfBusinessNocPath:
      "FIRE BRIGADE SYSTEM / Transactions / Renewal Of Business Noc",
    iodFireNocPath: "FIRE BRIGADE SYSTEM / Transactions / IOD Fire NOC",
    loiChallanGenerationPath:
      "FIRE BRIGADE SYSTEM / Transactions / LOI (Challan Generation)",
    receiptPath: "FIRE BRIGADE SYSTEM / Transactions / Receipt",
    sanctionLetterPath:
      "FIRE BRIGADE SYSTEM / Transactions / Building Fire NOC (Sanction Letter)",
    occupancyFireCertificatePath:
      "FIRE BRIGADE SYSTEM / Transactions / Occupancy Fire Certificate",
    fireAttendanceCertificatePath:
      "FIRE BRIGADE SYSTEM / Transactions / Fire Attendance Certificate",

    //title
    isTenantHaveAnyLoss: "Is tenant have any loss?",
    yes: "Yes",
    no: "No",
    otherExternalEmp:
      "Other External Employee Who is Not on duty but present at the time of Vardi",
    fireStation: "Fire Station",

    opinion: "Opinion",
    caseEntry: "Case Entry",
    vardiSlip: "Emergency Service - Vardi Slip",
    firstVardi: "Emergency Service - First Vardi",
    finalVardi: "Emergency Service - Final Vardi",
    provisionalBuildingNoc: "Provisional Building NOC",
    isRoad: "Is Road",
    roadSizeIfDirectionNot: "Enter Road Size",
    occuranceRegister: "Occurance Register",

    revisedBuildingNoc: "Revised Building NOC",
    finalBuildingNoc: "Final Building NOC",
    occuranceBookEntry: "Occurance Register",
    businessNoc: "Business NOC",
    businessNocOf: "Business noc of",
    renewalOfBusinessNoc: "Renewal Of Business Noc",
    iodFireNoc: "IOD Fire NOC",
    iodFireNocUpdate: "IOD Fire NOC - Update",
    loiChallanGeneration: "LOI (Challan Generation)",
    receipt: "Receipt",
    sanctionLetter: "Building Fire NOC (Sanction Letter)",
    sanctionLetterUpdate: "Building Fire NOC (Sanction Letter) - Update",
    occupancyFireCertificate: "Occupancy Fire Certificate",
    fireAttendanceCertificate: "Fire Attendance Certificate",
    fireAttendanceCertificateUpdate: "Fire Attendance Certificate - Update",

    // Table Feild Name
    shift: "Shift",
    srNoF: "Sr No",
    informerNameF: "Informer Name",
    informerLastNameF: "Sir Name",
    contactNumberF: "Contact Number",
    occurancePlaceF: "Vardi Place",
    typeOfVardiIdF: "Type Of Vardi",
    dateAndTimeOfVardiF: "Date & Time Of Vardi",
    // business noc feild
    applicantAddressF: "Applicant Address",
    bussinessAddressF: "Bussiness Address",

    //other labels
    // nOCName: "NOC Name",
    isFireEquipmentAvailable: "Is Fire Equipment Available ?",
    listOfFireEquipments: "List Of Fire Equipments",
    height: "Height",
    capacity: "Capacity",
    unit: "Unit",
    carpetArea: "Carpet Area",
    chargebalArea: "Chargeable Area",
    applicantAddressI: "Applicant Address",
    businessAddressE: "Business Address (In English)",
    businessAddressMr: "Business Address (In Marathi)",
    dateOfApplication: "Date of Application",
    mobileNo: "Mobile Number",
    documentName: "Document Name",
    typeOfBusiness: "Type Of Business",
    mobileNo: "Mobile No",
    applicantNameI: "Applicant Name",
    courtName: "Court Name",
    caseType: "Case Type",
    courtCaseNo: "Court Case Number",
    filingDate: "Filing Date",
    filedBy: "Filed By",
    caseDetails: "Case Details",
    advocateName: "Advocate Name",
    caseSubType: "Case Sub-Type",
    year: "Year",
    stampNo: "Stamp No.",
    filedAgainst: "Filed Against",
    advocateDetails: "Advocate Details",
    aadharNo: "Adhar Number",
    opponentAdvocate: "Opponent Advocate",
    concernPerson: "Concern Person",
    appearanceDate: "Appearance Date",
    deptName: "Department Name",
    prevCourtName: "Previous Court Name",
    document: "Document",
    informerDetails: "Caller Informer Details",
    vardiDetails: "Vardi Details",
    paymentDetails: "Bill Payer Details",
    collectedAmount: "Collected Amount (In Rs)",
    referenceNumber: "Reference Number",
    attachFile: "Attach File",
    actions: "Actions",
    enterBusinessNocNumber: "Enter Business Noc Number",
    applicantFirstName: "Applicant First Name",
    applicantFirstNameE: "Applicant First Name (In English)",
    applicantFirstNameMr: "Applicant First Name (In Marathi)",
    serviceName: "Service Name",

    // Emergency Services Feilds
    reasonOfFireEn: "Reason Of Fire",
    serviceCharge: "Service Charge",
    timeOfVardi: "Vardi Time",
    dateOfVardi: "Vardi Date",
    ownerOfPropertyInjurredCount: "Owner Of Property Injurred Count",
    ownerOfPropertyDeadCount: "Owner Of Property Dead Count",
    ownerOfPropertyOtherDetails: "Owner Of Property Other Details",
    ownerOfProperty: "Owner Of Property",
    fireDamages: "Fire Damages",
    totalBuildingLoss: "Total Building Loss",
    propertyLoss: "Property loss declared by property owner",
    totalVehicleLoss: "Total Equipment Loss",
    totalCount: "Total Count",
    totalInjurred: "Total Injurred",
    otherDeadCount: "Other Dead Count",
    otherInjurredCount: "Other Injurred Count",
    other: "Other =",
    employeeDetails: "Employee Details",
    totalEmployeeInjurred: "Total Employee Injurred",
    totalEmployeeDead: "Total Employee Dead",
    employeeKarmarchari: "Employee = ",
    lifeLoss: "Life Loss/ Injurred",
    externalServiceName: "External Service Name",
    externalServiceNameFeilds: "External Service Name (In English)",
    externalServiceNameMr: "External Service Name (In Marathi)",
    externalServiceNameValidationEn:
      "External Service Name (In English) is required!!",
    externalServiceNameValidationMr:
      "External Service Name (In Marathi) is required!!",
    externalAdditionalSupportService: "External additional support services",
    personAddress: "Address",
    personContactno: "Contact Number",
    personName: "Full Name",
    personNameMr: "Full Name (In marathi)",
    isExternalSupportProvided: "Is External Support Provided ?",
    isFireEquipmentIsAvailable: "Is Fire Equipment Is Available ?",
    vardiAndEmployeeDetails: "Present employee on Duty and Other Person",
    fireEquipment: "Fire Equipment",
    informerName: "Informer Name (In English)",
    informerNameMr: "Informer Name (In Marathi)",
    haveInsurrancePolicy: "Have Insurrance Policy?",
    informerMiddleName: "Informer Middle Name (In English)",
    informerMiddleNameMr: "Informer Middle Name (In Marathi)",
    informerLastName: "Informer Last Name (In English)",
    informerLastNameMr: "Informer Last Name (In Marathi)",
    fireStationName: "Fire Station Name",
    houseNo: "House No",
    buildingName: "Building Name",
    roadName: "Road Name",
    area: "Area",
    areaMr: "Address (In Marathi)",
    city: "Village (In English)",
    cityMr: "Village (In Marathi)",
    contactNumber: "Contact Number",
    email: "email",
    occurancePlace: "Vardi Place (In English)",
    occurancePlaceMr: "Vardi Place (In Marathi)",
    typeOfVardi: "Type Of Vardi",
    slipHandedOverTo: "Slip Handed Over To",
    slipHandedOverToEmp: "Slip Handed Over To (Fire Station)",
    landmark: "Landmark (In English)",
    landmarkMr: "Landmark (In Marathi)",
    subTypesOfVardi: "Sub Type Of Vardi",
    otherVardiType: "Type Of Vardi (Other)",
    otherReasonOfFire: "Other Reason Of Fire",
    nameOfOwner: "Name Of Owner (In English)",
    nameOfOwnerMr: "Name Of Owner (In Marathi)",
    nameOfTenant: "Name Of Tenant (In English)",
    nameOfTenantMr: "Name Of Tenant (In Marathi)",
    vardiReceivedName: "Vardi Received Name",
    dateAndTimeOfVardi: "Date And Time Of Vardi",
    documentsUpload: "Documents Upload",
    documentsUploadEmr: "Documents Upload (Optional)",
    vardiDispatchTime: "Vardi Dispatch Time",
    reasonOfFire: "Probable Cause Of Fire",
    lossInAmount: "Loss In Amount (Rs)",
    insurancePolicyDetails: "Insurance Policy Details (In English)",
    insurancePolicyDetailsMr: "Insurance Policy Details (In Marathi)",
    fireEquipments: "Fire Equipments (In Case of Industrial Building)",
    fireEquipmentsTitle: "Fire Equipments",

    fireEquipmentsFeilds:
      "Fire Equipments (In Case of Industrial Building) (In English)",
    fireEquipmentsMr: "Fire Equipments (In Case of Industrial Building)",
    fireEquipmentsMrFeilds:
      "Fire Equipments (In Case of Industrial Building) (In Marathi)",
    manPowerLoss: "Man Power Loss (If Any)",
    employeeDetailsDuringFireWorks: "Employee Details During FireWorks",
    employeeName: "Employee Name",
    fireCrew: "Fire Crew",
    personDetailsNotOnDuty: "Person details who is not on duty",
    chargesCollected:
      "Charges Collected (If Incidance Outside the PCMC Area) Details",
    billPayerDetails: "Bill Payer Details (In English)",
    billPayerDetailsMr: "Bill Payer Details (In Marathi)",
    billPayerName: "Name (In English)",
    billPayerNameMr: "Name (In Marathi)",
    billPayeraddress: "Address (In English)",
    billPayeraddressMr: "Address (In Marathi)",
    billPayerContact: "Contact Number",
    nameOfSubFireOfficer: "Name Of Sub Fire Officer",
    nameOfMainFireOfficer: "Name Of Station Officer",
    firedThingsDuringAccuse: "Fired Things During Accuse (In English)",
    firedThingsDuringAccuseMr: "Fired Things During Accuse (In Marathi)",
    remark: "remark",
    vehicleDispatchTime: "Vehicle Dispatch Time",
    other: "Other",
    distanceFromMainFireStation: "Distance From Main Fire Station",
    distanceFromSubFireStation: "Distance From Sub Fire Station",
    fireReason: "Fire Reason (In English)",
    fireReasonMr: "Fire Reason (In Marathi)",
    fireType: "Fire Type (In English)",
    fireTypeMr: "Fire Type (In Marathi)",
    fireLossInformationDetails: "Fire Loss Information Details (In English)",
    fireLossInformationDetailsMr: "Fire Loss Information Details (In Marathi)",
    constructionLoss: "Construction Loss",
    insuranced: "Insuranced",
    finacialLoss: "Finacial Loss (In English)",
    finacialLossMr: "Finacial Loss (In Marathi)",
    actual: "Approx Loss",
    saveOfLoss: "Save Of Loss",
    lossOfBuildingMaterial: "Loss Of Building Material (In English)",
    lossOfBuildingMaterialMr: "Loss Of Building Material (In Marathi)",
    otherOutsideLoss: "Other Outside Loss (In English)",
    otherOutsideLossMr: "Other Outside Loss (In Marathi)",
    officerNameToReleaseVehicle: "Officer Name To Release Vehicle (In English)",
    officerNameToReleaseVehicleMr:
      "Officer Name To Release Vehicle (In Marathi)",
    // dateAndTimeOfVardi: "Officer Name To Release Vehicle",
    totalTimeConsumedAtLocationInHrsAndMinutes:
      "Total Time Consumed At Location In Hrs And Minutes",

    //.. provisional feild
    ownerName: "Owner Name (In English)",
    ownerMiddleName: "Owner Middle Name (In English)",
    ownerLastName: "Owner Last Name (In English)",
    ownerNameMr: "Owner Name (In Marathi)",
    ownerMiddleNameMr: "Owner Middle Name (In Marathi)",
    ownerLastNameMr: "Owner Last Name (In Marathi)",

    applicantNameEng: "Applicant Name (In English)",
    applicantMiddleName: "Applicant Middle Name (In English)",
    applicantLastName: "Applicant Last Name (In English)",
    applicantNameMr: "Applicant Name (In Marathi)",
    applicantMiddleNameMr: "Applicant Middle Name (In Marathi)",
    applicantLastNameMr: "Applicant Last Name (In Marathi)",

    ownerAddresss: "Owner Address",
    ownerAddresssMr: "Owner Address (In Marathi)",
    ownerMobileNo: "Owner Mobile Number",
    ownerEmailId: "Owner Email",
    IfApplicantIsRental: "If applicant is rental",

    applicationDate: "Application Date",
    officeContactNo: "Office Contact No",
    workingSiteOnsitePersonMobileNo: "On Site Person Mobile No",
    emailId: "Email Id",
    appliedFor: "Applied For",
    architectName: "PAO Name (In English)",
    architectNameMr: "PAO Name (In Marathi)",
    architectFirmName: "PAO Firm Name (In English)",
    architectFirmNameMr: "PAO Firm Name (In Marathi)",
    architectRegistrationNo: "PAO Registration No",
    applicantPermanentAddress: "PAO Permanent Address (IopNon English)",
    applicantPermanentAddressMr: "PAO Permanent Address (In Marathi)",
    siteAddress: "Site Address (In English)",
    siteAddressMr: "Site Address (In Marathi)",
    applicantContactNo: "PAO Contact No",
    finalPlotNo: "Final Plot No",
    revenueSurveyNo: "Revenue Survey No",
    buildingLocation: "Building Location (In English)",
    buildingLocationMr: "Building Location (In Marathi)",
    townPlanningNo: "Town Planning No",
    blockNo: "Block No",
    opNo: "DP Opinion Number",
    citySurveyNo: "City Survey No",
    typeOfBuilding: "Type Of Building",
    buildingHeightFromGroundFloorInMeter:
      "Building Height From Ground Floor In Meter",
    // noOfBasement: "No Of Basement",
    totalBuildingFloor: "Total Building Floor (G+)",
    basementAreaInsquareMeter: "Basement Area In Square Meter",
    basementAreaInsquareMeter: "Basement Area In Square Meter",

    plinthHeightInMeter: "Plinth height in meter",
    paymentStatus: "Payment Status",

    noOfVentilation: "No Of Ventilation",
    noOfTowers: "No Of Towers",
    plotAreaSquareMeter: "Plot Area Square Meter",
    constructionAreSqMeter: "Construction Area Sq Meter",
    noOfApprochedRoad: "No Of Approched Road",
    drawingProvided: "Drawing Provided",
    // siteAddress: "Site Address (with Building Name)",
    highTensionLine:
      "High Tension Line, Mac Grid Channel Railway Crossing information",
    areaZone: "Area Zone",
    previouslyAnyFireNocTaken: "Previously Any Fire Noc Taken",
    underTheGroundWaterTankCapacityLighter:
      "Under The Ground Water Tank Capacity Lighter",
    l: "L",
    b: "B",
    h: "H",
    volumeLBHIn: "Volume LBH in (M³)",
    residentialUse: "Residential Use",
    iceFactory: "Ice Factory",
    commercialUse: "Commercial Use",
    nocFor: "NOC For",
    propertyNumber: "Property No.",
    approvedMapOfUndergroundWaterTank: "Approved Map Of Underground Water Tank",
    firmName: "Firm Name (In English)",
    firmNameMr: "Firm Name (In Marathi)",
    propertyNo: "Property Number",
    shopNo: "Shop Number",
    plotNo: "Plot Number",
    gatNo: "Gat Number",
    citySurveNo: "City Survey Number",
    landMark: "LandMark",
    areaEn: "Area",
    village: "Village",
    pinCode: "PinCode",
    officeMailId: "Office Mail Id",
    workingOnSitePersonMobileNo: "Working On Site Person Mobile Number",

    overHeadWaterTankCapacityInLiter: "Over Head Water Tank Capacity in Liter",
    overHearWaterTankCoApprovedMaps: "Over Head Water Tank Coapproved Maps",
    approvedKeyPlan: "Approved Key plan, Site Plan, Elivation Section PCMC",
    approvedLayoutPlanPCMC: "Approved Layout plan PCMC",
    approvedApproachRoadPCMC: "Approved Approach Road PCMC",
    measurementOfTank: "Measurement of Tank (underground, overhead) with map",
    explosiveLicense:
      "Explosive License (for LPG, CNG,Petrol pump, Gas station, Gas storage",
    permissionLetterOfPCMC: "Permission Letter Of PCMC",
    completionCertificate: "Completion Certificate",
    structuralStabilityCertificate: "Structural Stability Certificate",
    escalatorApprovedByGovtCertificate:
      "Escalator / Lift Approved by Govt. Certificate",
    fireDrawingFloorWiseAlsoApprovedByComplianceAuthority:
      "Fire Drawing Floor Wise i.e also approved by Compliance Authority",
    applicantContactNo: "Applicant Number",
    nameOfNoc: "Name Of NOC",
    // end task

    // Occurance Fire Certificate

    // Table Title - Provisional Building Noc
    applicantName: "Applicant Name",
    applicantNameT: "Applicant Name",
    applicationDateT: "Application Date",
    applicantContactNoT: "Applicant Contact No",
    architectNameT: "Architect Name",
    architectFirmNameT: "Architect Firm Name",
    appliedForT: "Applied For",
    nOCForT: "Noc For",
    buildingUse: "Building Use",

    // building rate chart
    occupancyTypeTxt: "Occupancy Type",
    occupancyTypeTxtMr: "Occupancy Type in marathi",
    parishishtha: "Parishishtha",
    typeOfUsageId: "Type Of Usage",
    buildingHeightFrom: "Building Height From",
    buildingHeightTo: "Building Height To",
    preminumPerSqm: "Preminum Per Sqm",
    preminumMinimumRate: "Preminum Minimum Rate",

    capacityFrom: "Capacity From",
    capacityTo: "Capacity To",
    renewRatePercentage: "Renew Rate (In Percentage)",
    companyType: "Company Type",
    typeOfBusinessId: "Type Of Business",
    rate: "Rate",
    businessRateChart: "Business Rate Chart",
    buildingRateChart: "Building Rate Chart",
    citizenNeedToPayment: "Citizen need to Payment",
    isCitizenOutsideFromPcmcArea: "Is Citizen Outside From Pcmc Area",
    waterSprayingPumpingCharge: "Water spraying / pumping charge",
    numberOfTrip: "Number Of Trip",
    outsidePCMCAreaRescueVardi: "Outside PCMC Area / Rescue Vardi",
    charge: "Charge",
    otherChargesNameIfApplicable: "Other Charges Name (If Applicable)",
    otherChargesAmount: "Other Charges Amount",
    classificationOfFireTypeOfFire: " Classification Of Fire (Type Of Fire)",
    levelOfFire: "Level Of Fire",
    firstName: "First Name",
    middleName: "Middle Name",
    lastName: "Last Name",

    firstNameMr: "First Name (In Marathi)",
    middleNameMr: "Middle Name(In Marathi)",
    lastNameMr: "Last Name(In Marathi)",

    // business loi
    loiDetails: "LOI Details",
    slotSchedule: "Slot Schedule",
    totalCharges: "Total Charge",
    totalInWords: "Total in words",
    allTotal: "Total Amount",

    // Form Title
    addVardiSlip: "Add Vardi Slip",
    updateVardiSlip: "Update Vardi Slip",
    applicantDetails: "Applicant Details",
    fireDetails: "Fire Details",
    financialLossDetails: "Financial Loss Details",
    formDetails: "Form Details",
    otherDetails: "Other Details",
    applicationDetails: "Application Details",
    businessDetails: "Business Details",
    purposeOfBuildingUse: "Purpose Of Building Use",
    addProvisionalBuildingNoc: "Provisional Building Fire Noc",
    addBusinessNoc: "Business NOC",
    updateBusinessNoc: "Update : Business NOC",
    // firstVardiAhawal: "First Vardi Ahawal",
    // finalVardiAhawal: "Final Vardi Ahawal",
    documentAndBusinessTypeMapping: "Document And Business Type Mapping",

    // Business Noc
    firmOwnerName: "Firm Owner Name",
    waterConnectionNo: "Water Connection No",
    meterConnectionNo: "Meter Connection No",
    shopActNo: "Shop Act No",
    sactionPlanNo: "Saction Plan No",
    sactionPlanDate: "Saction Plan Date",
    occupancyCertificateNo: "Occupancy Certificate No",
    occupancyCertificateDate: "Occupancy Certificate  Date",
    finalFireNocNo: "Final Fire Noc No",
    finalFireNocDate: "Final Fire Noc Date",
    noOfCasCade: "No of Cascade",
    capForCng: " Capacity For CNG",
    batteryChargingStationUnit: "Battery Charging Station Unit",
    applicantAddress: "Applicant Address (In English)",
    applicantAddressMr: "Applicant Address (In Marathi)",
    bussinessAddress: "Bussiness Address (In English)",
    bussinessAddressMr: "Bussiness Address (In Marathi)",
    mobileNo: "Mobile Number",
    dateOfApplication: "Date Of Application",
    typeOfBussiness: "Type Of Bussiness",
    documentName: "Document Name",
    remark: "Remark",
    approveDate: "Approve Date",
    dateOfAppLocation: "Date Of App Location",
    fromDate: "From Date",
    toDate: "To Date",
    attachment: "Attachment",
    renewalDate: "Renewal Date",
    newFromDate: "New From Date",
    newToDate: "New To Date",

    // Business Noc -Hotel
    requireNOCAreainSqMtrs: "Require NOC Area in Sq. Mtrs.",
    noOfEmployees: "No. Of Employee's",
    detailsOfFireFightingEquipments: "Details Of Fire Fighting Equipment's",
    fireFightingWaterTankCapacity:
      "Fire Fighting Water Tank Capacity (If Applicable)",
    widthOfApproachRoad: "Width Of Approach Road",
    numberOfExit: "Number Of Exit",
    seatingCapacity: "Seating Capacity",
    usageOfDryGrass: "Usage of dry grass / Cotton or the inflarable",
    securityArrangement: "CCTV is available ?",
    cctvIsAvailable: "CCTV is available ?",
    parkingArrangement: "Parking Arrangement",
    listOfEmergencyContactNumber:
      "List of Emergency Contact Number /No Smoking Sign Board's",
    typesOfWiring: "Types Of Wiring (Open / Close)",
    arrangementOfLightingArrester: "Arrangement Of Lighting Arrester",

    // Business noc - petrol
    isStarHotel: "Is Star Hotel ?",

    requireNocAreaForPetrolDieselCngPumpInSqMtrs:
      "Require Noc Area For Petrol Diesel Cng Pump In Sq. Mtrs.",
    noOfDispensingUnits: "No Of Dispensing Units",
    fuelTankCapacity: "Fuel Tank Capacity",
    lengthAndWidthOfCascadeForCng: "Length And Width Of Cascade For Cng",
    noOfFireFightingTrainedPerson: "No Of Fire Fighting Trained Person",

    usageOfDryGrassCottonOrInflatable:
      "Usage Of Dry Grass Cotton Or Inflatable",
    listOfEmergencyContactNumberNoSmokingSignBoards:
      "List Of Emergency Contact Number No Smoking Sign Boards",
    typesOfWiringOpenClose: "Types Of Wiring Open Close",

    // Table Title
    emergencyPersonContactNo: "Emergency Person Contact Number",
    emergencyServices: "Emergency Services - Vardi Slip",
    emergencyServicesUpdate: "Emergency Services - Update Vardi Slip",
    emergencyServicesFirstVardiAhawal: "Emergency Services - First Vardi Slip",
    emergencyServicesFinalVardiAhawal: "Emergency Services - Final Vardi Slip",
    addFirstVardiSlip: "Emergency Services - Add First Vardi Slip",
    updateFirstVardiSlip: "Emergency Services - Update First Vardi Slip",
    provisionalBuilding: "Provisional Building Fire NOC",
    revisedBuildingFireNOC: "Revised Building Fire NOC",
    finalBuildingFireNOC: "Final Building Fire NOC",

    // feild heading
    documentUpload: "Document Upload",

    //buttons
    add: "Add",
    save: "Save",
    update: "Update",
    clear: "Clear",
    exit: "Exit",
    back: "Back",
    saveAndNext: "Save & Next",
    finish: "Finish",

    type: "reports",

    //title
    listOfIssuedNOC: "List of Issued NOC",
    defaulterNocList: "Defaulter NOC List",
    buildingNoc: "Building NOC (Typewise)",
    renewalPendingList: "Renewal Pending List",
    nocWiseApplicationsCount: "NOC Wise Applications Count",
    nocRegister: "NOC Inward/Outward Register",
    citizenDetailsReport: "Citizen Details Report",
    dailyRecordRegister: "Daily Record Register",

    //labels
    shift: "Shift",
    nameOfNoc: "Name Of NOC",
    fromDate: "From Date",
    toDate: "To Date",
    corporationName: "Corporation Name",
    corporationLogo: "Corporation Logo",
    departmentLogo: "Department Logo ",
    applicationDate: "Application Date",
    sanctionDate: "Sanction Date",
    applicantName: "Applicant Name",
    businessName: "Business Name",
    nameOfBusiness: "Name of Business",
    businessAddress: "Business Address",
    contactNo: "Contact No",
    nocNo: "NOC No",
    nocSanctionDate: "Noc Sanction Date",
    nocEndDate: "NOC End Date",
    nameOfApplicant: "Name of Applicant",
    inwardDate: "Inward Date",
    nocType: "NOC Type",
    outWardDate: "Out ward Date",
    all: "All",
    cfc: "CFC",
    online: "Online",
    cfcCenterName: "CFC Center Name/Online/Both",
    countOfReceivedApplicationsAtCfc:
      "Count of received applications at CFC/Online",
    countOfPendingApplicationsAtCfc:
      "Count of pending applications at CFC/Online",
    countOfReceivedApplicationsAtHocfc:
      "Count of received applications at HOCFC",
    CountOfPendingApplicationsAtDepartment:
      "Count of pending applications at the department",
    countOfPendingCertificatesAtCfc:
      "Count of pending certificates at CFC/Online",
    countOfIssueCertificatesByCfc: "Count of issue certificates by CFC/Online",
    countOfApplicationsExceed:
      "Count of applications exceed the standard service period (CFC/Online)",
    countOfRejectedApplications: "Count of Rejected Applications (CFC/Online)",
    typeOfSerivce: "Type Of Serivce",
    citizenName: "Citizen Name",
    firmOrBusinessName: "Firm/Business Name",
    officeAddress: "Office Address",
    typeOfBusiness: "Type of Business",
    emailId: "Email Id",
    search: "Search",
    registrationAmount: "Registration Amount",
    registrationFees: "Registration Fees",
    buildingHeight: "Building Height",
    lowerGroundHeight: "Lower Ground Height",
    length: "Length",
    breadth: "breadth",
    parafeetWallHeight: "Parafeet wall height ",
    totalBuildingHeight: "Total Building Height",
    buildingHeightUptoParafeet: "Building Height upto parafeet ",
    buildingHeightUptoTeres: "Building Height upto Teres",
    noOfRefusedArea: "No Of Refuge Area",
    refusedArea: "Refuge Area In sq.mtr",
    vehicalTypeName: "Vehicle Type",
    // Validations
    typeOfBuildingValidation: "Type Of Building is required !!",
    englishValidation: "Must be only english characters",
    parishishthaValidation: "Parishishtha is required !!",
    typeOfBusinessValidation: "Type Of Business (In English) is required!!",
    fireEquipmentsValidationEn: "Fire Equipments (In English) is required!! ",
    fireEquipmentsValidationMr: "Fire Equipments (In Marathi) is required!! ",

    preminumPerSqmValidation: "Preminum Per Sqm. required !!",
    buildingHeightFromValidation: "Building Height From is required !!",
    buildingHeightToValidation: "Building Height To is required !!",
    preminumMinimumRateValidation: "Preminum Minimum Rate is required !!",
    capacityFromValidation: "Capacity From is required !!",
    capacityToValidation: "Capacity To is required !!",
    rateValidation: "Rate is required !!",
    renewRatePercentageValidation: "Renew Rate Percentage is required !!",
    capacityFromNumberValidation: "Capacity From must be a Number",
    nOCNameValidation: "NOC Name (In English) is required !!",
    nOCNameMrValidation: "NOC Name (In Marathi) is required !!",
    nameOfUsageValidation: "Usage Name (In English) is required !!",
    nameOfUsageMrValidation: "Usage Name (In Marathi) is required !!",
    vardiNameValidation: "Vardi Name (In English) is required !!",
    vardiNameMrValidation: "Vardi Name (In Marathi) is required !!",
    vehicleTypeValidation: "Vehicle Type (In English) is required !!",
    vehicleTypeMrValidation: "Vehicle Type (In Marathi) is required !!",
    vTSSystemIDValidation: "VTS System ID is required !!",
    vehicleNameValidation: "Vehicle Name (In English) is required !!",
    buildingPurposeValidation: "Building Purpose (In English) is required !!",
    buildingPurposeValidationMr: "Building Purpose (In Marathi) is requierd !!",
    reasonOfFireValidation: "Reason Of Fire (In English) is required !!",
    reasonOfFireValidationMr: "Reason Of Fire (In Marathi) is required !!",

    gISIDValidation: "GIS ID is required !!",
    fireStationNameValidation: "Fire Station Name (In English) is required !!",
    fireStationNameMrValidation:
      "Fire Station Name (In Marathi) is required !!",
    addressValidation: "Address (In English) is required !!",
    addressMrValidation: "Address (In Marathi) is required !!",
    zoneValidation: "Zone is required !!",
    wardValidation: "Ward is required !!",
    gISLocationValidation: "GIS Location is required !!",

    serviceChargeMaster: "Service Charge Master",
    reasonOfFireEn: "Reason Of Fire",
    reasonOfFireEnF: "Reason Of Fire (In English)",

    // typeOfBusiness
    typeOfBusinessValidationEn: "Type of Business (In English) is required !!",
    typeOfBusinessValidationMr: "Type of Business (In Marathi) is required !!",

    vehicleNameMrValidation: "Vehicle Name (In Marathi) is required !!",
    vehicleNumberValidation: "Vehicle Number ID is required !!",
    fireStationNameValidation: "Fire Station Name is required !!",
    gPSDeviceIdValidation: "GPS Device ID is required !!",

    // Employee Shift Master
    shiftNameValidation: "Shift Name (In English) is required !!",
    shiftNameMrValidation: "Shift Name (In Marathi) is required !!",
    shiftStartTimeValidation: "Shift Start Time is required !!",
    shiftEndTimeValidation: "Shift End Time is required !!",
    nameOfCFOValidation: "Name Of CFO is required !!",
    nameOfSFOValidation: "Name Of SFO is required !!",
    typeOfBuildingMrValidation: "Type Of Building (In Marathi) is required !!",
    nocTypeValidation: "Noc Type is required !!",
    serviceNameValidation: "Service Name is required !!",
    registrationAmountValidation: "Registration Amount is required !!",

    // Select NOC Type
    selectNOCType: " Select NOC Type",
    gislocation: "GIS Location",

    fileName: "File Name",
    upload: "Upload",

    // Payment
    yourPaymentDoneSuccess: "Your Payment Done Success",
    paymentFailed: "Payment Failed",
    applicationNo: "Application Number",
    orderId: "Order Id",
    trackingId: "Tracking Id",
    bankRefNo: "Bank Ref No.",
    billingName: "Billing Name",
    billingAdd: "Billing Add",
    billingCity: "Billing City",
    billingState: "Billing State",
    billingZip: "Billing Zip",
    billingCountry: "Billing Country",
    billingEmail: "Billing Email",
    mobileNo: "Mobile No",
    totalAmount: "Total Amount",
    transactionDate: "Transaction Date",
    loiNo: "Loi No",
    viewCertificate: "Certificate",
  },

  mr: {
    distanceFromBuildingToOpenSpace: "इमारतीपासून खुल्या जागेपर्यंतचे अंतर",
    podiumRampWidth: "पोडियम रॅम्प रुंदी",
    noOfPodiumRamp: "पोडियम रॅम्पची संख्या",
    isPodiumRampExists: "पोडियम रॅम्प अस्तित्वात आहे का?",
    noOfBasement: "तळघर  संख्या",
    isBasementExists: "तळघर अस्तित्वात आहे का?",
    capacityOfFireLift: "फायर लिफ्टची क्षमता",
    noOfFireLift: "फायर लिफ्टची संख्या",
    isFireLiftGiven: "फायर लिफ्ट दिली आहे",
    widthOfFireStairCase: "फायर स्टेअरकेस रुंदी",
    noOfFireStairCase: "फायर स्टेअरकेसची संख्या",
    isFireStairCaseGiven: "फायर स्टेअरकेस दिलेला आहे",

    registrationAmount: "नोंदणीची रक्कम",
    registrationFees: "नोंदणी शुल्क",

    tankLocation: "टाकीचे स्थान",
    tankType: "टाकीचा प्रकार",
    approachRoad: "ऍप्रोच रोड",
    direction: "दिशा",
    roadSize: "रस्त्याचा आकार",

    totalOverheadCapacity: "ओव्हरहेड पाण्याच्या टाकीची एकूण क्षमता",
    totalUndergroundCapacity: "भूमिगत पाण्याच्या टाकीची एकूण क्षमता",
    isPlanhaveUnderGroundWaterTank: "योजनेत सामाईक पाण्याची टाकी आहे",
    documentVerification: "दस्तऐवज पडताळणी",
    applicationDtlHeading: "मूलभूत अर्ज तपशील",
    applicationStatus: "अर्जाची स्थिती",
    documentPreview: "दस्तऐवज पहा",
    type: "commonLabels",
    module: "अग्निशामक यंत्रणा",
    length: "लांबी",
    breadth: "रुंदी",
    parafeetWallHeight: "पॅराफीट भिंतीची उंची",
    totalBuildingHeight: "एकूण इमारतीची उंची",
    buildingHeightUptoParafeet: "पॅराफीट पर्यंत इमारतीची उंची",
    buildingHeightUptoTeres: "तेरेस पर्यंत इमारतीची उंची",
    noOfRefusedArea: "नाकारलेल्या क्षेत्राची संख्या",
    refusedArea: "चौ.मीटर मध्ये नाकारलेले क्षेत्र,",
    vehicalTypeName: "वाहनाचा प्रकार",
    // Validations
    typeOfBuildingValidation: "इमारतीचा प्रकार आवश्यक आहे !!",
    englishValidation: "फक्त इंग्लिश शब्द",
    typeOfBusinessValidation: "व्यवसायाचा प्रकार आवश्यक आहे !!",
    fireEquipmentsValidationEn: "अग्निशमन उपकरणे (इंग्रजीमध्ये) आवश्यक आहेत!! ",
    fireEquipmentsValidationMr: "अग्निशमन उपकरणे (मराठीत) आवश्यक आहेत!! ",

    parishishthaValidation: "परिशिष्ठ आवश्यक आहे !!",
    preminumPerSqmValidation: "प्रीमियम प्रति चौ.मी. आवश्यक आहे !!",
    buildingHeightToValidation: "इमारतीची उंची च्यापर्यत आवश्यक आहे !!",
    preminumMinimumRateValidation: "प्रीमियम किमान दर आवश्यक आहे !!",
    buildingHeightFromValidation: "पासून इमारतीची उंची आवश्यक आहे !!",
    capacityFromValidation: "पासून क्षमताआवश्यक आहे !!",
    capacityToValidation: "क्षमता ते आवश्यक आहे !!",
    rateValidation: "दर आवश्यक आहे !!",
    renewRatePercentageValidation: "नूतनीकरण दर टक्केवारी आवश्यक आहे !!",
    capacityFromNumberValidation: "पासून क्षमता एक संख्या असणे आवश्यक आहे",
    nOCNameValidation: "एनओसी नाव (इंग्रजीत) आवश्यक आहे !!",
    nOCNameMrValidation: "एनओसी नाव (मराठीत) आवश्यक आहे !!",
    nameOfUsageValidation: "वापराचे नाव (इंग्रजीत) आवश्यक आहे !!",
    nameOfUsageMrValidation: "वापराचे नाव (मराठीत) आवश्यक आहे !!",
    vardiNameValidation: "वर्दीचे नाव (इंग्रजीत) आवश्यक आहे !!",
    vardiNameMrValidation: "वर्दीचे नाव (मराठीत) आवश्यक आहे !!",
    vehicleTypeValidation: "वाहन प्रकार (इंग्रजीत) आवश्यक आहे !!",
    vehicleTypeMrValidation: "वाहन प्रकार (मराठीत) आवश्यक आहे !!",
    vTSSystemIDValidation: "VTS सिस्टम आयडी आवश्यक आहे !!",
    vehicleNameValidation: "वाहनाचे नाव (इंग्रजीत) आवश्यक आहे !!",
    typeOfBusinessEn: "व्यवसायाचा प्रकार (इंग्रजीमध्ये) आवश्यक आहे!!",
    typeOfBusinessValidationMr: "व्यवसायाचा प्रकार (मराठीत) आवश्यक आहे !!",

    // Fire station details
    gISIDValidation: "GIS ID आवश्यक आहे !!",
    fireStationNameValidation: "फायर स्टेशनचे नाव (इंग्रजीत) आवश्यक आहे !!",
    fireStationNameMrValidation: "फायर स्टेशनचे नाव (मराठीत) आवश्यक आहे !!",
    addressValidation: "पत्ता (इंग्रजीमध्ये) आवश्यक आहे !!",
    addressMrValidation: "पत्ता (मराठीत) आवश्यक आहे!!",
    zoneValidation: "झोन आवश्यक आहे !!",
    wardValidation: "प्रभाग आवश्यक आहे !!",
    gISLocationValidation: "GIS स्थान आवश्यक आहे !!",

    serviceChargeMaster: "सर्व्हिस चार्ज मास्टर",
    reasonOfFireEn: "आगीचे कारण",
    reasonOfFireEnF: "आगीचे कारण (इंग्रजी मध्ये)",

    buildingPurposeValidation: "इमारत उद्देश (इंग्रजीमध्ये) आवश्यक आहे !!",
    buildingPurposeValidationMr: "इमारत उद्देश (मराठीत) आवश्यक आहे !!",
    reasonOfFireValidation: "फायरचे कारण (इंग्रजीमध्ये) आवश्यक आहे !!",
    reasonOfFireValidationMr: "आगीचे कारण (मराठीत) आवश्यक आहे !!",

    vehicleNameMrValidation: "वाहनाचे नाव (मराठीत) आवश्यक आहे !!",
    vehicleNumberValidation: "वाहन क्रमांक आयडी आवश्यक !!",
    fireStationNameValidation: "फायर स्टेशनचे नाव आवश्यक !!",
    gPSDeviceIdValidation: "GPS डिव्हाइस आयडी आवश्यक आहे !!",
    // Employee Shift Master
    shiftNameValidation: "शिफ्ट नाव (इंग्रजीमध्ये) आवश्यक आहे !!",
    shiftNameMrValidation: "शिफ्ट नाव (मराठीत) आवश्यक आहे !!",
    shiftStartTimeValidation: "शिफ्ट स्टार्ट वेळ आवश्यक आहे !!",
    shiftEndTimeValidation: "शिफ्ट संपण्याची वेळ आवश्यक आहे !!",
    nameOfCFOValidation: "मुख्य अग्निशमन अधिकारी चे नाव आवश्यक !!",
    nameOfSFOValidation: "उप अग्निशमन अधिकारी चे नाव आवश्यक आहे !!",
    typeOfBuildingMrValidation: "इमारतीचा प्रकार (मराठीत) आवश्यक आहे !!",
    nocTypeValidation: "एनओसी प्रकार आवश्यक आहे !!",
    serviceNameValidation: "सेवेचे नाव आवश्यक आहे !!",
    registrationAmountValidation: "नोंदणीची रक्कम आवश्यक आहे !!",

    // dashboard: 'डॅशबोर्ड',
    dashboard: "पिंपरी-चिंचवड महानगरपालिका डॅशबोर्ड",
    masters: "मास्टर्स",
    transactions: "व्यवहार",
    reports: "अहवाल",
    masterPath: "अग्निशमन यंत्रणा / मास्टर ",
    transactionPath: "कायदेशीर प्रकरण/ व्यवहार ",
    reportPath: "कायदेशीर प्रकरण/ अहवाल ",

    type: "masters",
    masters: "मास्टर्स",
    masterPath: "तक्रार निरीक्षण / मास्टर्स",

    transaction: "व्यवहार",
    report: "अहवाल",
    masterPath: "अग्निशमन यंत्रणा / मास्टर ",
    transactionPath: "कायदेशीर प्रकरण/ व्यवहार ",
    reportPath: "कायदेशीर प्रकरण/ अहवाल ",

    //breadcrum
    // masterPath: "अग्निशमन दल प्रणाली / मास्टर्स",
    typeOfBuildingPath: "अग्निशमन दल प्रणाली / मास्टर्स / इमारतीचा प्रकार",
    purposeOfBuildingPath: "अग्निशमन दल प्रणाली / मास्टर्स / इमारतीचा उद्देश",
    typeOfNocPath: "अग्निशमन दल प्रणाली/ मास्टर्स/ एनओसीचा प्रकार",
    usageTypeMasterPath: "अग्निशमन दल प्रणाली / मास्टर्स / वापर प्रकार मास्टर",
    typeOfBusinessPath: "अग्निशमन दल प्रणाली / मास्टर्स / व्यवसायाचा प्रकार",
    vardiTypeMasterPath: "अग्निशमन दल प्रणाली / मास्टर्स / वर्दी टाइप मास्टर",
    fireStationDetailsPath:
      "अग्निशमन दल प्रणाली / मास्टर्स / फायर स्टेशन तपशील",
    employeeShiftMasterPath:
      "अग्निशमन दल प्रणाली / मास्टर्स / कर्मचारी शिफ्ट मास्टर",
    vehicleDetailsPath: "अग्निशमन दल प्रणाली / मास्टर्स / वाहन तपशील",
    vehicleTypesPath: "अग्निशमन दल प्रणाली / मास्टर्स / वाहनांचे प्रकार",
    firstAhawalPath: "अग्निशमन दल प्रणाली / प्रथम अहवाल",
    finalAhawalPath: "अग्निशमन दल प्रणाली / अंतिम अहवाल",
    provisionalBuildingNocPath: "अग्निशमन दल प्रणाली / तात्पुरती इमारत क्रमांक",
    revisedBuildingNocPath: "अग्निशमन दल प्रणाली / सुधारित इमारत एनओसी",
    finalBuildingNocPath: "अग्निशमन दल प्रणाली / अंतिम इमारत एनओसी",
    occuranceBookEntry: "अग्निशमन दल प्रणाली / घटना नोंदवही",
    businessNocPath: "अग्निशमन दल प्रणाली / व्यवसाय एनओसी",

    //titles
    typeOfBuildingTitle: "इमारतीचा प्रकार",
    purposeOfBuildingTitle: "इमारतीचा उद्देश",
    typeOfNocTitle: "एनओसी चा प्रकार",
    usageTypeMasterTitle: "वापराचे नाव",
    typeOfBusinessTitle: "व्यवसायाचा प्रकार",
    vardiTypeMasterTitle: "वर्दी प्रकार मास्टर",
    fireStationDetailsTitle: "फायर स्टेशन तपशील",
    employeeShiftMasterTitle: "कर्मचारी शिफ्ट मास्टर",
    vehicleDetailsTitle: "वाहन तपशील",
    vehicleTypesTitle: "वाहनांचे प्रकार",
    reasonOfFireTitle: "आगीचे संभाव्य कारण",

    //other labels
    typeOfBuilding: "इमारतीचा प्रकार (इंग्रजी मध्ये)",
    typeOfBuildingMr: "इमारतीचा प्रकार (मराठी मध्ये)",
    gISID: "GIS आयडी",
    gISIDMr: "GIS आयडी (मराठी मध्ये)",
    fireStationName: "फायर स्टेशनचे नाव (इंग्रजी मध्ये)",
    fireStationNameMr: "फायर स्टेशनचे नाव (मराठी मध्ये)",
    address: "पत्ता (इंग्रजी मध्ये)",
    addressMr: "पत्ता (मराठी मध्ये)",
    vTSSystemID: "VTS सिस्टम आयडी",
    // vTSSystemIDMr: "VTS सिस्टम आयडी (मराठी मध्ये)",
    gPSDeviceId: "GPS साधन आयडी",
    // gPSDeviceIdMr: "GPS साधन आयडी (मराठी मध्ये)",
    vehicleType: "वाहन प्रकार (इंग्रजी मध्ये)",
    vehicleTypeF: "वाहन प्रकार",
    vehicleTypeMr: "वाहन प्रकार (मराठी मध्ये)",
    vehicleNumber: "वाहन क्रमांक",
    stationOutTime: "स्टेशन बाहेर वेळ",
    vehicleReachedAtLocationTime: "वाहन वेळेवर पोहोचले",
    pumpingTime: "पंपिंग वेळ",
    vehicleLeaveAtLocationTime: "ठिकाणाच्या वेळी वाहन सुटते",
    vehicleInTimeAtFireStation: "फायर स्टेशनवर वेळेत वाहन",
    vehicleKm: "वाहन किमी",
    vehicleName: "वाहनाचे नाव",
    vehicleNameMr: "वाहनाचे नाव (मराठी मध्ये)",
    reasonOfFire: "आगीचे कारण (इंग्रजी मध्ये)",
    reasonOfFireMr: "आगीचे कारण (मराठी मध्ये)",

    // vehicleNumberMr: "वाहन क्रमांक (मराठी मध्ये)",
    vardiName: "वर्दी नाव (इंग्रजी मध्ये)",
    vardiNameMr: "वर्दी नाव (मराठी मध्ये)",
    buildingPurpose: "इमारत उद्देश (इंग्रजी मध्ये)",
    buildingPurposeMr: "इमारत उद्देश (मराठी मध्ये)",
    nOCName: "एनओसी नाव (इंग्रजी मध्ये)",
    nOCNameMr: "एनओसी नाव (मराठी मध्ये)",
    nameOfUsage: "वापराचे नाव (इंग्रजी मध्ये)",
    nameOfUsageMr: "वापराचे नाव (मराठी मध्ये)",
    typeOfBusiness: "व्यवसायाचा प्रकार (इंग्रजी मध्ये)",
    typeOfBusinessMr: "व्यवसायाचा प्रकार (मराठी मध्ये)",
    fireStationName: "फायर स्टेशनचे नाव (इंग्रजी मध्ये)",
    fireStationNameMr: "फायर स्टेशनचे नाव (मराठी मध्ये)",
    ward: "प्रभाग",
    zone: "झोन",
    latitude: "अक्षांश",
    Longitude: "रेखांश",
    longitude: "रेखांश",
    shiftName: "शिफ्ट नाव (इंग्रजी मध्ये)",
    shiftNameMr: "शिफ्ट नाव (मराठी मध्ये)",
    shiftStartTime: "शिफ्ट प्रारंभ वेळ",
    shiftEndTime: "शिफ्ट समाप्ती वेळ",
    nameOfCFO: "मुख्य अग्निशमन अधिकारीचे नाव",
    nameOfSFO: "वरिष्ठ अग्निशमन अधिकारीचे नाव",
    nameOfOtherEmployee: "इतर कर्मचाऱ्याचे नाव",
    addMore: "अधिक जोडा",

    // Master Form Header
    businessType: "व्यवसायाचे प्रकार",
    addRegistrationFees: "नवीन नोंदणी करा - नोंदणी शुल्क",
    addBuilding: "नवीन नोंदणी करा - इमारतीचा प्रकार",
    updateBuilding: "बदल करा - इमारतीचा प्रकार",
    addPBuilding: "नवीन नोंदणी करा - इमारत बांधण्याचा उद्देश",
    updatePBuilding: "बदल करा - इमारत बांधण्याचा उद्देश",
    addNocName: "नवीन नोंदणी करा - एनओसीचे नाव",
    updateNocName: "बदल करा - एनओसीचे नाव",
    addUsage: "नवीन नोंदणी करा - वापर प्रकार",
    updateUsage: "बदल करा - वापर प्रकार",
    addBusinessT: "नवीन नोंदणी करा - व्यवसायाचा प्रकार",
    updateBusinessT: "बदल करा - व्यवसायाचा प्रकार",
    addVardiT: "नवीन नोंदणी करा - वर्दी प्रकार",
    updateVardiT: "बदल करा  - वर्दी प्रकार",
    addEmp: "नवीन नोंदणी करा - कर्मचारी शिफ्ट",
    updateEmp: "बदल करा - कर्मचारी शिफ्ट",
    addFireStation: "नवीन नोंदणी करा - अग्निशमन केंद्र तपशील",
    updateFireStation: "बदल करा -अग्निशमन केंद्र तपशील",
    addVehicleDetails: "नवीन नोंदणी करा - वाहन तपशील",
    updateVehicleDetails: "बदल करा - वाहन तपशील",
    citizenNeedToPayment: "नागरिकांनी पैसे भरणे आवश्यक आहे",
    isCitizenOutsideFromPcmcArea: "पी सी एम सी क्षेत्राबाहेरील नागरिक आहे",
    waterSprayingPumpingCharge: "पाणी फवारणी / पंपिंग चार्ज",
    numberOfTrip: "सहलीची संख्या",
    outsidePCMCAreaRescueVardi: "पी सी एम सी क्षेत्राच्या बाहेर / बचाव वर्दी",
    charge: "चार्ज",
    otherChargesNameIfApplicable: "इतर शुल्काचे नाव (लागू असल्यास)",
    otherChargesAmount: "इतर शुल्काची रक्कम",
    classificationOfFireTypeOfFire: " आगीचे वर्गीकरण (अग्नीचा प्रकार)",
    levelOfFire: "आग पातळी",
    firstName: "पहिले नाव",
    middleName: "मधले नाव",
    lastName: "आडनाव",

    firstNameMr: "पहिले नाव(मराठी)",
    middleNameMr: "मधले नाव(मराठी)",
    lastNameMr: "आडनाव(मराठी)",

    // Table Header name
    // typeOfBuildingT: "इमारतीचा प्रकार (इंग्रजी मध्ये)",
    // typeOfBuildingMrT: "इमारतीचा प्रकार (मराठी मध्ये)",
    // buildingPurposeT: "इमारत उद्देश (इंग्रजी मध्ये)",
    // buildingPurposeMrT: "इमारत उद्देश (मराठी मध्ये)",
    // nOCNameT: "एनओसी चे नाव (इंग्रजी मध्ये)",
    // nOCNameMrT: "एनओसी चे नाव (मराठी मध्ये)",
    // nameOfUsageT: "वापराचे नाव (इंग्रजी मध्ये)",

    // typeOfBusinessT: "व्यवसायाचा प्रकार (इंग्रजी मध्ये)",
    // typeOfBusinessMrT: "व्यवसायाचा प्रकार (मराठी मध्ये)",
    // vardiNameT: "वर्दीचे नाव (इंग्रजी मध्ये)",
    // vardiNameMrT: "वर्दीचे नाव (मराठी मध्ये)",

    courtName: "न्यायालयाचे नाव",
    // address: "पत्ता",
    roadName: "रस्त्याचे नाव",
    landmark: "जवळची खूण (इंग्रजी मध्ये)",
    landmarkMr: "जवळची खूण (मराठी मध्ये)",
    cityOrVillage: "शहर / गाव",
    pincode: "पिनकोड",
    area: "क्षेत्राचे नाव",
    name: "नाव",
    mobile: "मोबाईल नं.",
    phone: "दूरध्वनी नं.",
    email: "इलेक्ट्रॉनिक संदेश",
    aadharNo: "आधार नं.",
    panNo: "पॅन नं.",
    advocateCreation: "वकिल यशस्वीपणे तयार केला",
    advocateDetails: "वकील तपशील",
    bankDetails: "बँक तपशील",
    documentUpload: "दस्तऐवज अपलोड",
    title: "शीर्षक *",
    fname: "पहिले नाव *",
    mname: "मधले  नाव *",
    lname: "शेवटचे नाव *",
    advocateCategory: "वकील श्रेणी *",
    nameOfBarCouncil: "वकिलांचे मंडळचे प्रमाणपत्र परिषदचे नाव *",
    remarks: "टिप्पणी *",
    bankName: "बँकेचे नाव *",
    branchName: "शाखेचे नाव *",
    accountNo: "खाता क्रमांक *",
    bankIFSC: "बँक IFSC कोड *",
    bankMICR: "बँक MICR कोड *",
    application: "अर्ज:",
    aadharCard: "आधार कार्ड:",
    panCard: "पॅन कार्ड:",
    barCouncilCertificate: "वकिलांचे मंडळचे प्रमाणपत्र:",
    bankPassbook: "बँक पासबुक:",
    subType: "उप-प्रकार",

    attachFile: "फाईल जोडा",
    srNo: "अनुक्रमांक",
    actions: "क्रिया ",

    //Remarks
    selectDate: "कृपया तारीख निवडा",
    selectTitle: "कृपया शीर्षक निवडा",
    enterFName: "कृपया पहिले नाव भरा ",
    enterMName: "कृपया मधले  नाव भरा ",
    enterLName: "कृपया शेवटचे नाव भरा ",
    selectAdvocateCategory: "कृपया वकील श्रेणी निवडा",
    enterCouncilName: "कृपया वकिलांचे मंडळचे प्रमाणपत्र परिषदचे नाव भरा",
    enterArea: "कृपया क्षेत्राचे नाव भरा ",
    enterRoadName: "कृपया रस्त्याचे नाव भरा ",
    enterLandmark: "कृपया  महत्त्वाची खूण भरा",
    enterCity: "कृपया  शहराचे / गावाचे नाव भरा ",
    enterPinCode: "कृपया पिनकोड भरा",
    enterPhoneNo: "कृपया दूरध्वनी नं. भरा",
    enterMobileNo: "कृपया मोबाईल नं. भरा",
    enterEmailAddress: "कृपया इलेक्ट्रॉनिक संदेश भरा",
    enteraadhaarNo: "कृपया आधार नं. भरा",
    enterpanNo: "कृपया पॅन नं. भरा",
    // enterRemarks: 'कृपया टिप्पणी. भरा',
    enterRemarks: "कृपया टिप्पणी. द्या",

    //buttons
    add: "नवीन नोंदणी करा",
    save: "जतन करा",
    update: "अद्यायावत करा",
    clear: "रिक्त",
    exit: "बाहेर पडा",
    back: "मागे",
    saveAndNext: "जतन करा आणि पुढे",
    finish: "समाप्त",

    type: "transactions",

    transactions: "व्यवहार",
    transactionPath: "कायदेशीर प्रकरण/ व्यवहार ",

    // report
    date: "तारीख",
    time: "वेळ",
    approverName: "अनुमोदकाचे नाव",
    receipt: "पावती",
    receiptNo: "पावती क्र",
    receiptDate: "पावतीची तारीख",
    allServices: "सर्व सेवा",
    myApplication: "माझा अर्ज",
    modeOfPayment: "पेमेंट मोड",
    issueDate: "जारी करण्याची तारीख",
    selectService: "सेवा निवडा",
    selectNocNumber: "नंबर निवडा",
    search: "शोधा",
    nameOfApplicant: "अर्जदाराचे नाव",
    addressOfApplicant: "अर्जदाराचा पत्ता",
    print: "छापा",
    view: "पहा",
    reset: "रीसेट करा",
    submit: "प्रस्तुत करणे",
    receiptCapital: "पावती",
    fireDepartment: "अग्निशमन विभाग",
    nocNo: "एनओसी क्र",
    partyName: "पक्षाचे नाव",
    loiNo: "अर्ज क्र",
    partyAddress: "पार्टी पत्ता",
    loiDate: "कायदा तारीख",
    financialYear: "आर्थिक वर्ष",
    fireCertificate: "फायर प्रमाणपत्र",
    transactionId: "व्यवहार आयडी",
    total: "एकूण",
    paymentType: "पैसे भरण्याची पध्दत",
    pay: "पैसे द्या",
    amountInWord: "शब्दात रक्कम",
    amountInWordMr: "शब्दात रक्कम (इंग्रजी मध्ये)",
    description: "वर्णन",
    onlinePayment: "ऑनलाइन पेमेंट/ विभाग",
    printedBy: "द्वारे मुद्रित",
    dateAndTime: "तारीख आणि वेळ",
    addressDeatils: "पत्ता तपशील",
    termAndCondition: "नियम आणि अटी",
    applicationName: "अर्जाचे नाव",
    applicationType: "अर्जाचे प्रकार",
    serviceId: "सेवेचे नाव",
    siteVistType: "साइट भेट प्रकार",
    visitDate: "भेट तारीख",
    siteVisitDetails: "साइट भेट तपशील",
    vardiTime: "वर्दीची वेळ",
    isExternalEmployeeAddedInDuty:
      "बाह्य व्यक्ती (कर्मचारी) कर्तव्यात जोडली गेली आहे का?",

    // Label
    height: "उंची",
    capacity: "क्षमता",
    unit: "युनिट",
    carpetArea: "कार्पेट क्षेत्र",
    chargebalArea: "चार्जेबल क्षेत्र",
    applicantAddressI: "अर्जदाराचा पत्ता",
    businessAddress: "व्यवसायाचा पत्ता",
    businessAddressE: "व्यवसायाचा पत्ता (इंग्रजी मध्ये)",
    businessAddressMr: "व्यवसायाचा पत्ता (मराठी मध्ये)",
    dateOfApplication: "अर्जाची तारीख",
    documentName: "कागदपत्र नाव",
    typeOfBusiness: "व्यवसायाचा प्रकार",
    mobileNo: "मोबाईल क्र",
    finalFireNOCNumber: "अंतिम फायर एनओसी क्रमांक प्रविष्ट करा",
    applicantNameI: "अर्जदाराचे नाव",
    applicationDate: "अर्जाची तारीख",
    officeContactNo: "कार्यालय संपर्क नं.",
    personMobileNo: "कार्यरत साइट ऑनसाइट व्यक्तीचा मोबाईल नं",
    emailId: "ई-मेल आयडी",
    appliedFor: "साठी अर्ज केला",
    architectName: "आर्किटेक्टचे नाव",
    architectFirmName: "आर्किटेक्ट फर्म नाव",
    architectRegistrationNo: "वास्तुविशारद नाॊंदणी क्रमांक",
    applicantPermanentAddress: "अर्जदार कायमचा पत्ता",
    siteAddress: "साइट पत्ता",
    applicantContactNo: "अर्जदार संपर्क नाही",
    FinalPlotNoFP: "अंतिम भूखंड क्रमांक - (F.P)",
    RevenueSurveyNoRS: "महसूल सर्वेक्षण क्रमांक (आर.एस.)",
    BuildingLocation: "इमारत स्थान",
    townPlanningNo: "नगररचना क्रमांक",
    blockNo: "ब्लॉक क्रमांक",
    OPNo: "ब्लॉक क्र",
    citySurveyNo: "सटी सर्वेक्षण क्रमांक",
    typeofBuilding: "सटी सर्वेक्षण क्रमांक",
    residentialUse: "निवासी वापर",
    commercialUse: "व्यावसायिक वापर",
    NOCFor: "साठी NOC",
    buildingHeight: "तळमजल्यापासून इमारतीची उंची मीटरमध्ये",
    // noOfBasement: "तळघर क्रमांक",
    totalBuilding: "एकूण इमारत मजला (G+)",
    basementArea: "चौरस मीटर मध्ये तळघर क्षेत्र",
    noOfVentilation: "वायुवीजन संख्या",
    noOfTowers: "टॉवर्सची संख्या",
    plotArea: "प्लॉट क्षेत्र चौरस मीटर",
    construction: "बांधकाम चौरस मीटर आहे",
    noOfApprochedRoad: "जवळचा रस्ता क्र",
    drawingProvided: "रेखाचित्र प्रदान केले",
    siteAddressWithName: "साइटचा पत्ता (इमारतीच्या नावासह)",
    highTensionLineMac:
      "हाय टेंशन लाइन, मॅक ग्रिड चॅनल रेल्वे क्रॉसिंगची माहिती",
    areaZone: "क्षेत्र झोन",
    fireNocTaken: "पूर्वी कोणतीही फायर एनओसी घेतली",
    underTheGroundWaterTank: "जमिनीखालील पाण्याची टाकी क्षमता लाइटर",
    l: "एल",
    b: "बि",
    h: "एच",
    volumeLBH: "( M³) मध्ये आवाज LBH",
    approvedMap: "भूमिगत पाण्याच्या टाकीचा मंजूर नकाशा",
    overHeadWaterTank: "ओव्हर हेड वॉटर टँकची क्षमता लिटरमध्ये",
    OverHearWaterTank: "ओव्हर हीअर वॉटर टँक सह मंजूर नकाशे",
    applicationNo: "अर्ज क्रमांक",
    corporationName: "कॉर्पोरेशनचे नाव",
    corporationLogo: "कॉर्पोरेशन लोगो",
    departmentLogo: "कॉर्पोरेशन लोगो",
    sanctionDate: "मंजुरीची तारीख",
    proposedSiteAddress: "प्रस्तावित साइट पत्ता",
    plotDetails: "प्लॉट तपशील",
    buildingDetails: "इमारत तपशील",
    conditions: "परिस्थिती",
    occurrenceBookEntry: "घटना पुस्तक नोंद",
    occuranceNo: "घटना क्रमांक",
    dateOfIncident: "घटनेची तारीख",
    dateOfIncidentMr: "घटनेची तारीख",
    timeOfIncident: "घटनेची वेळ",
    occuranceDetails: "घटना तपशील",
    occuranceDetailsMr: "घटना तपशील",
    informerDetails: "माहिती देणारा तपशील",
    informerDetailsMr: "माहिती देणारा तपशील",
    addressOfInformer: "माहिती देणाऱ्याचा पत्ता",
    addressOfInformerMr: "माहिती देणाऱ्याचा पत्ता",
    incidanceTookPlace: "घटना घडली",
    incidanceTookPlaceMr: "घटना घडली",
    damageDetails: "नुकसानीचा तपशील",
    damageDetailsMr: "नुकसानीचा तपशील",
    occurancePcmcArea: "PCMC क्षेत्रामधील घटना",
    chargesIfOutsidePCMC: "PCMC बाहेर असल्यास शुल्क",
    chargesIfOutsidePCMCMr: "PCMC बाहेर असल्यास शुल्क",
    detailsOfIncidentSite: "घटनास्थळाचे तपशील वर्णन",
    remark: "शेरा",
    uploadImages: "प्रतिमा अपलोड करा",
    geoLocation: "साइटचे GEO स्थान",
    vardiAhalNumber: "वर्दी अहवाल क्रमांक",
    causeOfFire: "आगीचे कारण",
    ownerName: "मालकाचे नाव",
    detailsDescriptionOfIncidentSite: "तपशील घटना साइट वर्णन",
    detailsDescriptionOfIncidentSiteMr: "तपशील घटना साइट वर्णन (मराठी मध्ये)",
    gEOLocationOfSite: "साइटचे जीईओ स्थान",
    vehicleDetails: "वाहन तपशील",
    nocTypes: "व्यवसाय प्रकार",
    nocNumber: "एनओसी संख्या",
    noOfRooms: "खोलीची संख्या",
    businessNocId: "व्यवसाय क्रमांक आयडी",
    nocAreaForPetrolPumpInSqMtrs: "चौ.मी.मध्ये पेट्रोल पंपासाठी एनओसी क्षेत्र",
    noOfDespesingUnit: "डिस्पेसिंग युनिटची संख्या",
    fuelTankCapacity: "इंधन टाकीची क्षमता",
    lengthOfCascadeForCNG: "सीएनजी साठी कॅसकेडची लांबी",
    widthOfCascadeForCNG: "सीएनजी साठी कॅसकेडची रुंदी",
    foodAndDrugSafetyLicenseCopy: "अन्न आणि औषध सुरक्षा परवाना प्रत",
    noOfBeds: "बेडची संख्या",
    noOfScreen: "स्क्रीनची संख्या",
    eachScreenSeatingCapacity: "प्रत्येक स्क्रीन बसण्याची क्षमता",
    typesOfCompany: "कंपनीची चाचणी",
    businessDetails: "व्यवसाय तपशील",
    rawMaterialDetails: "रॉ मटेरीअल तपशील",
    finalMaterialDetails: "अंतिम साहित्य तपशील",
    listOfHazardousMaterial: "धोकादायक सामग्रीची यादी",
    emergencyContactPersonDetails: "आपत्कालीन संपर्क व्यक्ती तपशील",
    requireNocForHospitalInSqMtrs: "रूग्णालयासाठी मीटर मध्ये एनओसी आवश्यक आहे",
    applicationNumber: "अर्ज क्रमांक",
    hotelArea: "हॉटेल क्षेत्र चौ. मीटर मध्ये",
    starHotel: "तारांकित हॉटेल",
    ownerDetails: "मालक तपशील",
    applicantAddresss: "अर्जदाराचे पत्ता (इंग्रजी मध्ये)",
    applicantAddresssMr: "अर्जदाराचे पत्ता (मराठी मध्ये)",
    chauMeter: "चौ. मीटर",

    //breadcrum
    opinionPath: "कायदेशीर प्रकरण / व्यवहार /मत",
    caseEntryPath: "कायदेशीर प्रकरण / व्यवहार /प्रकरणाची नोंदणी",
    // emergency breadcrum
    vardiSlipPath: "अग्निशामक यंत्रणा / आपत्कालीन सेवा",
    renewalOfBusinessNocPath:
      "अग्निशामक यंत्रणा / व्यवहार / व्यवसाय क्रमांकाचे नूतनीकरण",

    //titles
    opinion: "मत",
    caseEntry: "प्रकरणाची नोंदणी",

    isTenantHaveAnyLoss: "भाडेकरूचे काही नुकसान आहे का?",
    yes: "होय",
    no: "नाही",
    otherExternalEmp:
      "इतर बाह्य कर्मचारी - जो डयुटी वर नाही परंतु वर्दीच्या वेळी उपस्थित आहे",
    fireStation: "फायर स्टेशन",

    vardiSlip: "आपत्कालीन सेवा - वर्दी स्लिप",
    firstVardi: "पहिली वर्दी स्लिप",
    finalVardi: "अंतिम वर्दी स्लिप",
    occuranceRegister: "घटना नोंदवही",
    provisionalBuildingNoc: "तात्पुरती इमारत एनओसी",
    isRoad: "रोड आहे",
    roadSizeIfDirectionNot: "रस्त्याचा आकार प्रविष्ट करा",
    revisedBuildingNoc: "सुधारित इमारत एनओसी",
    finalBuildingNoc: "अंतिम इमारत एनओसी",
    occuranceBookEntry: "घटना नोंदवही",
    businessNoc: "व्यवसाय एनओसी",
    businessNocOf: "ची व्यवसाय एनओसी",
    renewalOfBusinessNoc: "व्यवसाय क्रमांकाचे नूतनीकरण",
    iodFireNoc: "आयओडी फायर एनओसी",
    loiChallanGeneration: "उद्देशीय पत्र (चलन निर्मिती)",
    receipt: "पावती",
    sanctionLetter: "बिल्डिंग फायर एनओसी (मंजुरी पत्र)",
    sanctionLetterUpdate: "बिल्डिंग फायर एनओसी (मंजुरी पत्र) मध्ये बदल करा",
    occupancyFireCertificate: "ताब्यात असलेले अग्निशामक प्रमाणपत्र",
    fireAttendanceCertificate: "अग्निशमन उपस्थिती प्रमाणपत्र",
    fireAttendanceCertificateUpdate:
      "अग्निशमन उपस्थिती प्रमाणपत्र मध्ये बदल करा",

    // Feild Name
    shift: "शिफ्ट",
    srNoF: "अनुक्रमांक",
    informerNameF: "माहिती देणाऱ्याचे नाव",
    informerLastNameF: "आडनाव",
    contactNumberF: "संपर्क क्रमांक",
    occurancePlaceF: "घटना ठिकाण",
    typeOfVardiIdF: "वर्दीचा प्रकार",
    dateAndTimeOfVardiF: "वर्दीचा तारीख आणि वेळ",

    //       //  business noc

    isFireEquipmentAvailable: "अग्निशमन उपकरणे उपलब्ध आहेत का?",
    listOfFireEquipments: "अग्निशामक उपकरणांची यादी",

    applicantAddressF: "अर्जदाराचा पत्ता",
    bussinessAddressF: "व्यवसाय पत्ता",

    //other labels
    applicantName: "अर्जदाराचे नाव",

    courtName: "न्यायालयाचे नाव",
    caseType: "प्रकरणाचा प्रकार",
    courtCaseNo: "न्यायालयाचा प्रकरणाचा नं.",
    filingDate: "दाखल करण्याची तारीख",
    filedBy: "द्वारे दाखल",
    caseDetails: "प्रकरणाचा तपशील",
    advocateName: "वकीलाचे नाव",
    caseSubType: "प्रकरणाचा उप-प्रकार",
    year: "वर्ष",
    stampNo: "मुद्रांक क्रमांक",
    filedAgainst: "विरुद्ध दाखल",
    advocateDetails: "वकील तपशील",
    opponentAdvocate: "विरोधक वकील",
    concernPerson: "संबंधित व्यक्ती",
    appearanceDate: "देखावा तारीख",
    deptName: "विभागाचे नाव",
    prevCourtName: "पूर्वीचे न्यायालयाचे नाव",
    document: "दस्तऐवज",
    informerDetails: "वर्दी बाबत माहिती देणाराचे तपशील",
    vardiDetails: "वर्दी तपशील",
    paymentDetails: "बिल भरणाऱ्याचा तपशील",
    collectedAmount: "गोळा केलेली रक्कम (रु. मध्ये)",
    referenceNumber: "संदर्भ क्रमांक",

    attachFile: "फाईल जोडा",
    actions: "क्रिया ",
    enterBusinessNocNumber: "व्यवसाय क्रमांक प्रविष्ट करा",
    applicantFirstName: "व्यवसाय क्रमांक प्रविष्ट करा",
    applicantFirstNameE: "व्यवसाय क्रमांक प्रविष्ट करा (इंग्रजी मध्ये)",
    applicantFirstNameMr: "व्यवसाय क्रमांक प्रविष्ट करा (मराठी मध्ये)",
    serviceName: "सेवेचे नाव",
    serviceNameMr: "सेवेचे नाव",

    // emergency services form feild
    reasonOfFireEn: "आगीचे कारण",
    serviceCharge: "सेवा शुल्क",
    timeOfVardi: "वर्दीची वेळ",
    dateOfVardi: "वर्दीची तारीख",
    ownerOfPropertyInjurredCount: "जखमी झालेल्या मालमत्तेचा मालक",
    ownerOfPropertyDeadCount: "संपत्तीचा मालक मृत संख्या",
    ownerOfPropertyOtherDetails: "मालमत्तेचा मालक इतर तपशील",
    ownerOfProperty: "मालमत्तेचा मालक",
    fireDamages: "आगीमुळे झालेले नुकसान",
    totalBuildingLoss: "एकूण बिल्डिंग लॉस",
    propertyLoss: "मालमत्ता मालकाने घोषित केलेल्या मालमत्तेचे नुकसान",
    totalVehicleLoss: "एकूण उपकरणे नुकसान",
    totalCount: "एकूण संख्या",
    totalInjurred: "एकूण जखमी",
    otherDeadCount: "इतर मृतांची संख्या",
    otherInjurredCount: "इतर जखमींची संख्या",
    other: "इतर =",
    employeeDetails: "कर्मचारी तपशील",
    totalEmployeeInjurred: "एकूण कर्मचारी जखमी",
    totalEmployeeDead: "एकूण कर्मचारी मृत",
    employeeKarmarchari: "कर्मचारी = ",
    lifeLoss: "जीवितहानी / जखमी",
    externalServiceName: "बाह्य सेवेचे नाव",
    externalServiceNameFeilds: "बाह्य सेवेचे नाव (इंग्रजी मध्ये)",
    externalServiceNameMr: "बाह्य सेवेचे नाव (मराठी मध्ये)",
    externalServiceNameValidationEn:
      "बाह्य सेवा नाव (इंग्रजीमध्ये) आवश्यक आहे!!",
    externalServiceNameValidationMr: "बाह्य सेवा नाव (मराठीत) आवश्यक आहे!!",
    externalAdditionalSupportService: "बाह्य अतिरिक्त आधार सेवा",
    personAddress: "पत्ता",
    personContactno: "संपर्क क्रमांक",
    personName: "नाव",
    personNameMr: "नाव (मराठी मध्ये)",
    isExternalSupportProvided: "बाह्य समर्थन प्रदान केले आहे का ?",
    isFireEquipmentIsAvailable: "अग्निशमन उपकरणे उपलब्ध आहेत का?",
    vardiAndEmployeeDetails: "कर्तव्यावर उपस्थित कर्मचारी आणि इतर व्यक्ती",
    fireEquipment: "फायर उपकरणे",
    informerName: "माहिती देणाऱ्याचे नाव (इंग्रजी मध्ये)",
    haveInsurrancePolicy: "विमा पॉलिसी आहे का?",
    informerNameMr: "माहिती देणाऱ्याचे नाव  (मराठी मध्ये)",
    informerMiddleName: "माहिती देणाऱ्याचे मधले नाव (इंग्रजी मध्ये)",
    informerMiddleNameMr: "माहिती देणाऱ्याचे मधले नाव (मराठी मध्ये)",
    informerLastName: "माहिती देणाऱ्याचे आडनाव (इंग्रजी मध्ये)",
    informerLastNameMr: "माहिती देणाऱ्याचे आडनाव (मराठी मध्ये)",
    fireStationName: "अग्निशमन केंद्र",
    landmark: "जवळची खूण (इंग्रजी मध्ये)",
    landmarkMr: "जवळची खूण (मराठी मध्ये)",
    subTypesOfVardi: "वर्दीचा उप-प्रकार",
    otherVardiType: "वर्दीचा प्रकार (इतर काही असल्यास)",
    otherReasonOfFire: "आगीचे कारण (इतर काही असल्यास)",
    nameOfOwner: "मालकाचे नाव (इंग्रजी मध्ये)",
    nameOfOwnerMr: "मालकाचे नाव (मराठी मध्ये)",
    nameOfTenant: "भाडेकरूचे नाव (इंग्रजी मध्ये)",
    nameOfTenantMr: "भाडेकरूचे नाव (मराठी मध्ये)",
    houseNo: "घर क्रमांक",
    buildingName: "इमारतीचे नाव",
    roadName: "रस्त्याचे नाव",
    areaMr: "पत्ता (मराठी मध्ये)",
    city: "गाव (इंग्रजी मध्ये)",
    cityMr: "गाव (मराठी मध्ये)",
    contactNumber: "संपर्क क्रमांक",
    email: "ई-मेल",
    occurancePlace: "घटना ठिकाण (इंग्रजी मध्ये)",
    occurancePlaceMr: "घटना ठिकाण (मराठी मध्ये)",
    typeOfVardi: "वर्दीचा प्रकार",
    slipHandedOverTo: "स्लिप सोपवली",
    slipHandedOverToEmp: "स्लिप सोपवली (फायर स्टेशनचे नाव)",
    vardiReceivedName: "वर्दी प्राप्त नाम",
    dateAndTimeOfVardi: "वर्दीची तारीख आणि वेळ",
    documentsUpload: "कागदपत्रे जोडा",
    documentsUploadEmr: "कागदपत्रे जोडा (पर्यायी)",
    vardiDispatchTime: "वर्दी पाठवण्याची वेळ",
    reasonOfFire: "आगीचे संभाव्य कारण",
    lossInAmount: "रकमेतील नुकसान (रु मध्ये)",
    insurancePolicyDetails: "विमा धोरण तपशील (इंग्रजी मध्ये)",
    insurancePolicyDetailsMr: "विमा धोरण तपशील (मराठी मध्ये)",
    fireEquipments: "अग्निशामक उपकरणे (औद्योगिक इमारतीच्या बाबतीत)",
    fireEquipmentsFeilds:
      "अग्निशामक उपकरणे (औद्योगिक इमारतीच्या बाबतीत) (इंग्रजी मध्ये)",
    fireEquipmentsTitle: "अग्निशामक उपकरणे",

    fireEquipmentsMr: "अग्निशामक उपकरणे (औद्योगिक इमारतीच्या बाबतीत)",
    fireEquipmentsMrFeilds:
      "अग्निशामक उपकरणे (औद्योगिक इमारतीच्या बाबतीत) (मराठी मध्ये)",
    manPowerLoss: "मनुष्यहानी (जर काही)",
    employeeDetailsDuringFireWorks: "आग कार्य करते दरम्यान कर्मचारी तपशील",
    employeeName: "कर्मचारी नाव",
    fireCrew: "पथक",
    personDetailsNotOnDuty: "डयुटी नसलेले कर्मचारी आणि इतर व्यक्ती",
    chargesCollected:
      "शुल्क गोळा केले (PCMC क्षेत्राबाहेरील घटना असल्यास) तपशील",
    billPayerDetails: "बिल भरणाऱ्याचा तपशील (इंग्रजी मध्ये)",
    billPayerDetailsMr: "बिल भरणाऱ्याचा तपशील (मराठी मध्ये)",
    billPayerName: "नाव (इंग्रजी मध्ये)",
    billPayerNameMr: "नाव (मराठी मध्ये)",
    billPayeraddress: "पत्ता (इंग्रजी मध्ये)",
    billPayeraddressMr: "पत्ता (मराठी मध्ये)",
    billPayerContact: "संपर्क क्रमांक",
    nameOfSubFireOfficer: "उप-अधिकारी नाव",
    nameOfMainFireOfficer: "स्टेशन ऑफिसरचे नाव",
    firedThingsDuringAccuse: "आरोप दरम्यान आग वस्तू (इंग्रजी मध्ये)",
    firedThingsDuringAccuseMr: "आरोप दरम्यान आग वस्तू (मराठी मध्ये)",
    remark: "टिप्पणी",
    vehicleDispatchTime: "वाहन पाठवण्याची वेळ",
    other: "इतर",
    distanceFromMainFireStation: "मुख्य अग्निशमन केंद्रापासून अंतर",
    distanceFromSubFireStation: "सब फायर स्टेशन पासून अंतर",
    fireReason: "आगीचे कारण (इंग्रजी मध्ये)",
    fireReasonMr: "आगीचे कारण (मराठी मध्ये)",
    fireType: "आगीचा प्रकार (इंग्रजी मध्ये)",
    fireTypeMr: "आगीचा प्रकार (मराठी मध्ये)",
    fireLossInformationDetails: "आग नुकसान माहिती तपशील (इंग्रजी मध्ये)",
    fireLossInformationDetailsMr: "आग नुकसान माहिती तपशील (मराठी मध्ये)",
    constructionLoss: "बांधकाम नुकसान",
    insuranced: "विमा",
    finacialLoss: "आर्थिक नुकसान (इंग्रजी मध्ये)",
    finacialLossMr: "आर्थिक नुकसान (मराठी मध्ये)",
    actual: "अंदाजे नुकसान",
    saveOfLoss: "नुकसान वाचवा",
    lossOfBuildingMaterial: "बांधकाम साहित्याचे नुकसान (इंग्रजी मध्ये)",
    lossOfBuildingMaterialMr: "बांधकाम साहित्याचे नुकसान (मराठी मध्ये)",
    otherOutsideLoss: "इतर बाहेरील नुकसान (इंग्रजी मध्ये)",
    otherOutsideLossMr: "इतर बाहेरील नुकसान (मराठी मध्ये)",
    officerNameToReleaseVehicle: "वाहन सोडण्यासाठी अधिकाऱ्याचे नाव",
    // dateAndTimeOfVardi: "Date And Time Of Vardi",
    totalTimeConsumedAtLocationInHrsAndMinutes:
      "एकूण वेळ तास आणि मिनिटांमध्ये स्थानावर",

    // provisional feild name

    ownerName: "मालकाचे  पहिले नाव (इंग्रजी मध्ये)",
    ownerFirstName: "मालकाचे पहिले नाव (इंग्रजी मध्ये)",
    ownerMiddleName: "मालकाचे मधले नाव (इंग्रजी मध्ये)",
    ownerLastName: "मालकाचे आडनाव (इंग्रजी मध्ये)",
    ownerFirstNameMr: "मालकाचे पहिले नाव (मराठी मध्ये)",
    ownerNameMr: "मालकाचे पहिले नाव (मराठी मध्ये)",
    ownerMiddleNameMr: "मालकाचे मधले नाव (मराठी मध्ये)",
    ownerLastNameMr: "मालकाचे आडनाव (मराठी मध्ये)",

    applicantNameEng: "अर्जदाराचे पहिले नाव (इंग्रजी मध्ये)",
    applicantMiddleName: "अर्जदाराचे मधले नाव (इंग्रजी मध्ये)",
    applicantLastName: "अर्जदार आडनाव (इंग्रजी मध्ये)",
    applicantNameMr: "अर्जदाराचे पहिले नाव (मराठी मध्ये)",
    applicantMiddleNameMr: "अर्जदाराचे मधले नाव (मराठी मध्ये)",
    applicantLastNameMr: "अर्जदार आडनाव (मराठी मध्ये)",

    ownerAddresss: "मालकाचा पत्ता",
    ownerAddresssMr: "मालकाचा पत्ता (मराठी मध्ये)",
    ownerMobileNo: "मालकाचा मोबाईल नंबर",
    ownerEmailId: "मालक ईमेल",
    IfApplicantIsRental: "जर अर्जदार भाडेतत्वावर असेल",

    applicationDate: "अर्जाची तारीख",
    officeContactNo: "कार्यालय संपर्क",
    workingSiteOnsitePersonMobileNo: "साइटवर कार्यरत व्यक्तीचा मोबाइल नंबर",
    emailId: "ई-मेल आयडी",
    appliedFor: "साठी अर्ज केला",
    architectName: "इमारतीचे नकाशे काढणाराचे नाव (इंग्रजी मध्ये)",
    architectNameMr: "इमारतीचे नकाशे काढणाराचे नाव (मराठी मध्ये)",
    architectFirmName: "इमारतीचे नकाशे काढणाराचे फर्मचे नाव (इंग्रजी मध्ये)",
    architectFirmNameMr: "इमारतीचे नकाशे काढणाराचे फर्मचे नाव (मराठी मध्ये)",
    architectRegistrationNo: "इमारतीचे नकाशे काढणाराचे नोंदणी क्रमांक",
    applicantPermanentAddress: "अर्जदाराचा कायमचा पत्ता (इंग्रजी मध्ये)",
    applicantPermanentAddressMr: "अर्जदाराचा कायमचा पत्ता (मराठी मध्ये)",
    siteAddress: "जागा पत्ता (इंग्रजी मध्ये)",
    siteAddressMr: "जागा पत्ता (मराठी मध्ये)",
    applicantContactNo: "अर्जदाराचा संपर्क क्रमांक",
    finalPlotNo: "अंतिम प्लॉट क्रमांक",
    revenueSurveyNo: "महसूल सर्वेक्षण क्रमांक",
    buildingLocation: "इमारत स्थान",
    townPlanningNo: "नगररचना क्रमांक",
    blockNo: "ब्लॉक क्रमांक",
    opNo: "ओ.पी.क्रमांक",
    citySurveyNo: "सटी सर्वेक्षण क्रमांक",
    typeOfBuilding: "इमारतीचा प्रकार",
    buildingHeightFromGroundFloorInMeter:
      "तळमजल्यापासून इमारतीची उंची मीटरमध्ये",
    // noOfBasement: "तळघर क्रमांक",
    totalBuildingFloor: "एकूण इमारत मजला (G+)",
    basementAreaInsquareMeter: "चौरस मीटरमध्ये तळघर क्षेत्र",
    plinthHeightInMeter: "प्लिंथची उंची मीटरमध्ये",
    paymentStatus: "पैसे भरल्याची स्थिती",

    noOfVentilation: "वायुवीजन संख्या",
    noOfTowers: "टॉवर्सची संख्या",
    plotAreaSquareMeter: "प्लॉट क्षेत्र चौरस मीटर",
    constructionAreSqMeter: "बांधकाम क्षेत्र चौरस मीटर",
    noOfApprochedRoad: "जवळचा रस्ता संख्या",
    drawingProvided: "रेखाचित्र प्रदान केले",
    highTensionLine: "उच्च ताण रेषा",
    areaZone: "क्षेत्र झोन",
    previouslyAnyFireNocTaken: "यापूर्वी कोणतीही फायर एनओसी घेतलेली",
    underTheGroundWaterTankCapacityLighter:
      "जमिनीखालील पाण्याची टाकी क्षमता लाइटर",
    l: "एल",
    b: "बि",
    h: "एच",
    propertyNumber: "मालमत्ता क्र.",
    volumeLBHIn: "एल बि एच मध्ये आवाज (M³)",
    nOCFor: "Noc For",
    residentialUse: "निवासी वापर",
    iceFactory: "बर्फ कारखाना",
    commercialUse: "व्यावसायिक वापर",
    nocFor: "एनओसी कशासाठी",
    approvedMapOfUndergroundWaterTank: "भूमिगत पाण्याच्या टाकीचा मंजूर नकाशा",
    firmName: "फर्म नाव (इंग्रजी मध्ये)",
    firmNameMr: "फर्म नाव (मराठी मध्ये)",
    propertyNo: "मालमत्तेचे संख्या",
    shopNo: "दुकान क्रमांक",
    plotNo: "प्लॉट क्रमांक",
    gatNo: "गट क्रमांक",
    citySurveNo: "शहर सर्वेक्षण क्रमांक",
    landMark: "महत्त्वाची खूण",
    areaEn: "क्षेत्र",
    village: "गाव",
    pinCode: "पिन कोड",
    officeMailId: "ऑफिस मेल आयडी",
    workingOnSitePersonMobileNo: "साइटवर कार्यरत व्यक्तीचा मोबाईल नंबर",

    overHeadWaterTankCapacityInLiter:
      "ओव्हरहेड पाण्याच्या टाकीची क्षमता लिटरमध्ये",
    // task marathi
    overHeadWaterTankCapacityInLiter:
      "ओव्हरहेड पाण्याच्या टाकीची क्षमता लिटरमध्ये",
    overHearWaterTankCoApprovedMaps: "ओव्हरहेड पाण्याच्या टाकी सह मंजूर नकाशे",
    approvedKeyPlan: "मंजूर की योजना, साइट प्लॅन, एवलव्हेशन सेक्शन प्लॅन PCMC",
    approvedLayoutPlanPCMC: "पीसीएमसीचे मंजूर लेआउट योजना ",
    approvedApproachRoadPCMC: "पीसीएमसीचे मंजूर ऍप्रोच रस्ते",
    measurementOfTank: "नकाशासह टाकीचे मोजमाप (भूमिगत, ओव्हरहेड).",
    explosiveLicense:
      "स्फोटक परवाना (च्या साठी एलपीजी, सीएनजी, पेट्रोल पंप, गॅस स्टेशन, गॅस स्टोरेज)",
    permissionLetterOfPCMC: "पीसीएमसीचे परवानगीपत्र",
    completionCertificate: "पूर्णत्व प्रमाणपत्र",
    structuralStabilityCertificate: "संरचनात्मक स्थिरता प्रमाणपत्र",
    escalatorApprovedByGovtCertificate:
      "एस्केलेटर मंजूर केलेले सरकारचे प्रमाणपत्र",
    fireDrawingFloorWiseAlsoApprovedByComplianceAuthority:
      "फायर ड्रॉइंग मजला वार देखील अनुपालन प्राधिकरणाद्वारे मंजूर",
    applicantContactNo: "अर्जदार क्रमांक",
    nameOfNoc: "NOC चे नाव",

    // end task

    // Table Title - Provisional Building Noc
    applicantName: "अर्जदाराचे नाव",
    applicantNameT: "अर्जदाराचे पहिले नाव",
    applicationDateT: "अर्जाची तारीख",
    applicantContactNoT: "अर्जदाराचा संपर्क क्रमांक",
    architectNameT: "इमारतीचे नकाशे काढणाराचे नाव",
    architectFirmNameT: "इमारतीचे नकाशे काढणाराचे फर्मचे नाव",
    appliedForT: "साठी अर्ज केला",
    nOCForT: "एनओसी कशासाठी",
    buildingUse: "इमारत वापर",

    // building rate chart
    occupancyType: "भोगवटा प्रकार",
    occupancyTypeTxt: "भोगवटा प्रकार",
    occupancyTypeTxtMr: "भोगवटा प्रकार (मराठी मध्ये)",
    parishishtha: "परिशिष्ठ",
    typeOfUsageId: "वापर प्रकार आयडी",
    buildingHeightFrom: "पासून इमारतीची उंची",
    buildingHeightTo: "इमारतीची उंची",
    preminumPerSqm: "प्रीमियम प्रति चौ.मी",
    preminumMinimumRate: "प्रीमियम किमान दर",

    capacityFrom: "पासून क्षमता",
    capacityTo: "क्षमता ते",
    renewRatePercentage: "नूतनीकरण दर (टक्केवारी)",
    companyType: "कंपनी प्रकार",
    typeOfBusinessId: "व्यवसायाचा प्रकार",
    rate: "दर",
    businessRateChart: "व्यवसाय दर चार्ट",
    buildingRateChart: "बिल्डिंग रेट चार्ट",

    // business loi
    loiDetails: "LOI तपशील",
    slotSchedule: "स्लॉट वेळापत्रक",
    totalCharges: "एकूण शुल्क",
    totalInWords: "शब्दात एकूण",
    allTotal: "एकूण रक्कम",

    // Form Title
    addVardiSlip: "वर्दी स्लिप जोडा",
    updateVardiSlip: "वर्दी स्लिप मध्ये बदल करा",
    addFirstVardi: "प्रथम वर्दी जोडा",
    addFinalVardi: "अंतिम वर्दी जोडा",
    applicantDetails: "अर्जदार तपशील",
    fireDetails: "आग तपशील",
    financialLossDetails: "आर्थिक नुकसान तपशील",
    addProvisionalBuildingNoc: "इमारत तात्पुरता ना हरकत दाखला",
    updateProvisionalBuildingNoc: "बदल करा - तात्पुरती इमारत एनओसी",
    formDetails: "फॉर्म तपशील",
    otherDetails: "इतर तपशील",
    applicationDetails: "अर्जाचा तपशील",
    businessDetails: "व्यवसाय तपशील",
    purposeOfBuildingUse: "इमारतीच्या वापराचा उद्देश",
    addBusinessNoc: "व्यवसाय एनओसी",
    updateBusinessNoc: "बदल करा : व्यवसाय एनओसी",
    // firstVardiAhawal: "प्रथम वर्दी अहवाल",
    // finalVardiAhawal: "अंतिम वर्दी अहवाल",\
    documentAndBusinessTypeMapping: "कागदपत्र आणि व्यवसाय प्रकार मॅपिंग",

    // Business Noc
    firmOwnerName: "फर्म मालकाचे नाव",
    waterConnectionNo: "पाणी कनेक्शन क्र",
    meterConnectionNo: "मीटर कनेक्शन क्र",
    shopActNo: "दुकान कायदा क्र",
    sactionPlanNo: "मंजुरी योजना क्र",
    sactionPlanDate: "मंजुरी प्लॅनची ​​तारीख",
    occupancyCertificateNo: "भोगवटा प्रमाणपत्र क्र",
    occupancyCertificateDate: "भोगवटा प्रमाणपत्राची तारीख",
    finalFireNocNo: "अंतिम फायर ना हरकत प्रमाणपत्र क्रमांक",
    finalFireNocDate: "अंतिम फायर ना हरकत प्रमाणपत्र तारीख",
    noOfCasCade: "कॅस्केडची संख्या",
    capForCng: "सी एन जी साठी क्षमता",
    batteryChargingStationUnit: "बॅटरी चार्जिंग स्टेशन युनिट",

    applicantAddress: "अर्जदाराचा पत्ता (इंग्रजी मध्ये)",
    applicantAddressMr: "अर्जदाराचा पत्ता (मराठी मध्ये)",
    bussinessAddress: "व्यवसायाचा पत्ता (इंग्रजी मध्ये)",
    bussinessAddressMr: "व्यवसायाचा पत्ता (मराठी मध्ये)",
    mobileNo: "मोबाईल नंबर",
    dateOfApplication: "अर्जाची तारीख",
    typeOfBussiness: "व्यवसायाचा प्रकार",
    documentName: "कागदपत्र नाव",
    remark: "टिप्पणी",
    approveDate: "तारीख मंजूर करा",
    dateOfAppLocation: "अॅप स्थानाची तारीख",
    fromDate: "या तारखेपासून",
    toDate: "आजपर्यंत",
    attachment: "जोडायची गोष्ट",
    renewalDate: "नूतनीकरण तारीख",
    newFromDate: "तारखेपासून नवीन",
    newToDate: "आजपर्यंत नवीन",

    // Business Noc -Hotel
    isStarHotel: "स्टार हॉटेल आहे का?",
    requireNOCAreainSqMtrs: "चौरस मीटरमध्ये एनओसी क्षेत्र आवश्यक आहे",
    noOfEmployees: "कर्मचाऱ्यांची संख्या",
    detailsOfFireFightingEquipments: "अग्निशमन उपकरणांचे तपशील",
    widthOfApproachRoad: "ऍप्रोच रोडची रुंदी",
    numberOfExit: "निर्गमन संख्या",
    seatingCapacity: "आसन क्षमता",
    usageOfDryGrass: "कोरडे गवत / कापूस किंवा इन्फ्लॅरेबलचा वापर",
    securityArrangement: "सी.सी.टीव्ही उपलब्ध आहे का?",
    cctvIsAvailable: "सी.सी.टीव्ही उपलब्ध आहे का?",
    parkingArrangement: "पार्किंग व्यवस्था",
    listOfEmergencyContactNumber:
      "आपत्कालीन संपर्क क्रमांक/नो स्मोकिंग साइन बोर्डची यादी",
    typesOfWiring: "वायरिंगचे प्रकार (आतील वायरिंग / बाह्य वायरिंग)",
    arrangementOfLightingArrester: "लाइटिंग अरेस्टरची व्यवस्था",

    // Business noc - petrol
    requireNocAreaForPetrolDieselCngPumpInSqMtrs:
      "चौरस मीटरमधील पेट्रोल डिझेल सीएनजी पंपासाठी एनओसी क्षेत्र आवश्यक आहे",
    noOfDispensingUnits: "वितरण युनिट्सची संख्या",
    lengthAndWidthOfCascadeForCng: "CNG साठी कॅसकेडची लांबी आणि रुंदी",
    noOfFireFightingTrainedPerson: "अग्निशमन प्रशिक्षित व्यक्तीची संख्या",
    fireFightingWaterTankCapacity:
      "अग्निशमन पाण्याच्या टाकीची क्षमता (लागू पडत असल्यास)",
    usageOfDryGrassCottonOrInflatable:
      "सुक्या गवताचा कापूस किंवा फुगवण्यायोग्य वापर",
    listOfEmergencyContactNumberNoSmokingSignBoards:
      "आपत्कालीन संपर्क क्रमांक नो स्मोकिंग साइन बोर्डची यादी",
    typesOfWiringOpenClose: "वायरिंगचे प्रकार ओपन क्लोज",

    // Table Title
    emergencyPersonContactNo: "आपत्कालीन व्यक्ती संपर्क क्रमांक",
    emergencyServices: "आपत्कालीन सेवा - वर्दी स्लिप ",
    iodFireNoc: "आयओडी फायर एनओसी",
    iodFireNocUpdate: "आयओडी फायर एनओसी मध्ये बदल करा",
    emergencyServicesUpdate: "आपत्कालीन सेवा - वर्दी स्लिप मध्ये बदल करा",
    emergencyServicesFirstVardiAhawal: "आपत्कालीन सेवा - प्रथम वर्दी स्लिप",
    emergencyServicesFinalVardiAhawal: "आपत्कालीन सेवा - अंतिम वर्दी स्लिप",
    // addFirstVardiSlip: "आपत्कालीन सेवा - प्रथम वर्दी स्लिप जोडा",
    // updateFirstVardiSlip: "आपत्कालीन सेवा - प्रथम वर्दी स्लिप मध्ये बदल करा",
    provisionalBuilding: "तात्पुरती इमारत आग एनओसी",
    revisedBuildingFireNOC: "सुधारित बिल्डिंग फायर एनओसी",
    finalBuildingFireNOC: "अंतिम इमारत फायर एनओसी",

    // Form Feild Title
    documentUpload: "कागदपत्र अपलोड",

    //buttons
    add: "नवीन नोंदणी करा",
    save: "जतन करा",
    update: "अद्यायावत करा",
    clear: "रिक्त",
    exit: "बाहेर पडा",
    back: "मागे",
    saveAndNext: "जतन करा आणि पुढे",
    finish: "समाप्त",

    type: "reports",

    // title
    listOfIssuedNOC: "जारी केलेल्या एनओसीची यादी",
    defaulterNocList: "डिफॉल्टर एनओसी यादी",
    buildingNoc: "इमारत एनओसी (प्रकारानुसार)",
    renewalPendingList: "नूतनीकरण प्रलंबित यादी",
    nocWiseApplicationsCount: "एनओसीनुसार अर्जांची संख्या",
    nocRegister: "एनओसीनुसार अर्जांची संख्या",
    citizenDetailsReport: "नागरिक तपशील अहवाल",
    dailyRecordRegister: "दैनिक रेकॉर्ड रजिस्टर",

    // labels
    nameOfNoc: "NOC चे नाव",
    fromDate: "या तारखेपासून",
    toDate: "आजपर्यंत",
    corporationName: "कॉर्पोरेशनचे नाव",
    applicationNo: "अर्ज क्रमांक",
    corporationLogo: "कॉर्पोरेशन लोगो",
    departmentLogo: "कॉर्पोरेशन लोगो",
    applicationDate: "अर्जाची तारीख",
    sanctionDate: "मंजुरीची तारीख",
    applicantName: "अर्जदाराचे नाव",
    businessName: "व्यवसायाचे नाव",
    nameOfBusiness: "व्यवसायाचे नाव",
    businessAddress: "व्यवसायाचा पत्ता",
    contactNo: "संपर्क क्रमांक",
    nocNo: "noc क्रमांक",
    nocSanctionDate: "NOC मंजुरीची तारीख",
    nocEndDate: "NOC समाप्ती तारीख",
    nameOfApplicant: "अर्जदाराचे नाव",
    inwardDate: "आवक तारीख",
    nocType: "एनओसी प्रकार",
    nocNumber: "एनओसी संख्या",
    outWardDate: "जावक तारीख",
    all: "सर्व",
    cfc: "CFC",
    online: "ऑनलाइन",
    cfcCenterName: "CFC केंद्राचे नाव/ऑनलाइन/दोन्ही",
    countOfReceivedApplicationsAtCfc:
      "CFC/ऑनलाइनवर प्राप्त झालेल्या अर्जांची संख्या",
    countOfPendingApplicationsAtCfc: "CFC/ऑनलाइन प्रलंबित अर्जांची संख्या",
    countOfReceivedApplicationsAtHocfc:
      "HOCFC वर प्राप्त झालेल्या अर्जांची संख्या",
    CountOfPendingApplicationsAtDepartment:
      "विभागातील प्रलंबित अर्जांची संख्या",
    countOfPendingCertificatesAtCfc:
      "CFC/ऑनलाइन प्रलंबित प्रमाणपत्रांची संख्या",
    countOfIssueCertificatesByCfc:
      "CFC/ऑनलाइनद्वारे जारी केलेल्या प्रमाणपत्रांची संख्या",
    countOfApplicationsExceed:
      "अर्जांची संख्या मानक सेवा कालावधीपेक्षा जास्त आहे (CFC/ऑनलाइन)",
    countOfRejectedApplications: "नाकारलेल्या अर्जांची संख्या (CFC/ऑनलाइन)",
    typeOfSerivce: "सेवेचा प्रकार",
    citizenName: "नागरिकाचे नाव",
    firmOrBusinessName: "फर्म/व्यवसायाचे नाव",
    officeAddress: "कार्यालयाचा पत्ता",
    typeOfBusiness: "व्यवसायाचा प्रकार",
    emailId: "ई-मेल आयडी",
    search: "शोधा",
    buildingHeight: "इमारतीची उंची",
    lowerGroundHeight: "जमिनीची कमी उंची",
    selectNOCType: "एनओसी प्रकार निवडा",
    gislocation: "जी. आय. एस. स्थान",

    fileName: "फाईलचे नाव",
    upload: "अपलोड करा",

    // Payment In Marathi
    yourPaymentDoneSuccess: "तुमचे पेमेंट पूर्ण झाले",
    paymentFailed: "पेमेंट अयशस्वी",
    applicationNo: "अर्ज क्रमांक",
    orderId: "ऑर्डर आयडी",
    trackingId: "ट्रॅकिंग आयडी",
    bankRefNo: "बँक संदर्भ क्र.",
    billingName: "बिलिंग नाव",
    billingAdd: "बिलिंग जोडा",
    billingCity: "बिलिंग शहर",
    billingState: "बिलिंग स्थिती",
    billingZip: "बिलिंग झिप",
    billingCountry: "बिलिंग देश",
    billingEmail: "बिलिंग ई-मेल",
    mobileNo: "मोबाईल क्रमांक",
    totalAmount: "एकूण रक्कम",
    transactionDate: "व्यवहाराची तारीख",
    loiNo: "लोई क्रमांक",
    viewCertificate: "प्रमाणपत्र",
  },
};
