/* eslint-disable import/no-anonymous-default-export */
export default {
  en: {
    hmsDashboard: "Street Vendor Management System",
    serviceChargeTypeName: "Service Charge Type Name",
    or: "OR",
    totalCharges: "Total Charges",
    loiPreview: "Loi Preview",
    chargeName: "Charge Name",
    amount: "Amount",
    iCard: "Identity Card",
    view: "View",
    ddNo: "Demand Draft Number",
    viewCertificate: "View Certificate",
    ddDate: "Demand Draft Date",
    AptBook: "Appointment Slot Booking",
    streetVendorQuestion: "Street Vendor Question",
    applicantName: "Applicant Name",
    receiptDate: "Receipt Date",
    receiptNumber: "Receipt Number",
    receiptAmount: "Receipt Amount",
    loiRecord: "Loi Record",
    loiGeneration: "LOI Generation",
    loiPrint: "  LOI Print",
    loiCollection: "LOI Collection",
    paymentMode: "Payment Mode",
    paymentType: "Payment Type",
    receiptModeDetails: "Receipt Mode Details",
    type: "commonLabels",
    search: "Search",
    statusValidation: "status selection required  !!!",
    loiNO: "LOI NO.",
    loiDetails: "LOI Details",
    and: "and",
    loiDate: "LOI Date",
    applicationNo: "Application NO.",
    rate: "Rate",
    total: "Total",
    totalInWords: "Total Charges in Words",
    licenseType: "License Type",
    years: "Years",
    months: "Months",
    durationOfLicenseValidity: " Duration of License Validity (In year)",
    checkFormLicenseValidityForm: " Check for License Validity Form",
    hawkerType: "Street Vendor",
    hawkerType1: "Street Vendor Type",
    hawkerTypeEn: "Street Vendor (In English) ",
    hawkerTypeMr: "Street Vendor (In Marathi) ",
    serviceCharge: "Service Charges",
    licenseValidity: "License Validity (In Years)",
    licenseValidityHeader: "License Validity",
    applicantDetails: "Applicant Details",
    chargesDetails: "Charges Details",
    dateOfIssuance: "Date of Issuance",
    calendarYear: "Calendar Year",
    financialYear: "Financial Year",
    generateLoi: "Generate LOI",
    previewLoi: "Preview LOI",
    verifyLoi: "Verify LOI",
    HMS: "Street Vendor Management System",
    streetVendorManagmentSystem: "Street Vendor Management System",
    siteVisitPhotoUpload: "Upload Photos of a Site Visit",
    siteVisitPhoto: "Photos of a Site Visit",
    streetVendorInformation: "Street Vendor Information",
    businessHawkinglocation:
      "who is operating the business at the Street Vendor location ?",
    remark: "Remark",
    dashboard: "Pimpri-Chinchwad Municipal Corporation Dashboard",
    master: "Masters",
    roadWithBusinessLocation: "Road Width at Business Location? (In feet)",
    streetVendorPhoto: "Photo",
    inFeet: "in feet",
    streetVendorThumb1: "Biometric Impression of Thumb 1",
    streetVendorThumb2: "Biometric Impression of Thumb 2",
    transactions: "Transactions",
    report: "Reports",
    masterPath: "Street Vendor Management System / Master",
    transactionPath: "Legal Case / Transaction ",
    reportPath: "Legal Case / Report ",
    inspectionSellingGoods:
      "Did the inspection discover that the applicant is selling goods at the specified location?",
    businessTrafficCongestion:
      "Does the business currently cause traffic congestion ?",
    religionPath: "Street Vendor Management System / masters / Religion",
    hawkerTypePath:
      "Street Vendor Management System / masters / Street Vendor Type",
    businessTypeMasterPath:
      "Street Vendor Management System / masters / Business Type Master",
    businessSubTypePath:
      "Street Vendor Management System / masters / Business Sub Type",
    titlePath: "Street Vendor Management System / masters / Title",
    itemMasterPath: "Street Vendor Management System / masters / Item Master",
    itemCategoryMasterPath:
      "Street Vendor Management System / masters / Item Category Master",
    castCategoryPath:
      "Street Vendor Management System / masters / Caste Category",
    castMasterPath: "Street Vendor Management System / masters / Cast Master",
    hawkingZonePath: "Street Vendor Management System / masters / Hawking Zone",
    subCastMasterPath:
      "Street Vendor Management System / masters / Sub Caste Master",
    licenseValidityPath:
      "Street Vendor Management System / masters / License Validity",
    penaltyPath: "Street Vendor Management System / masters / Penalty",
    bankMasterPath: "Street Vendor Management System / masters /Bank Master",
    hawkingZoneWiseFacilitiesPath:
      "Street Vendor Management System / masters / Street Vendor Zone Wise Facilities",
    taxTypeMasterPath:
      "Street Vendor Management System / masters / Tax Type Master",
    taxNameMasterPath:
      "Street Vendor Management System / masters / Tax Name Master",
    serviceTaxCollectionCyclePath:
      "Street Vendor Management System / masters / Service Tax Collection Cycle",
    taxRateChartMasterPath:
      "Street Vendor Management System / masters / Tax Rate Chart Master",
    noHawkingZonePath:
      "Street Vendor Management System / masters / No Street Vendor Zone",
    hawkerMasterPath:
      "Street Vendor Management System / masters / Street Vendor Master",
    ward: "Ward",
    zone: "Zone",
    religion: "Religion",
    businessTypeMaster: "Business Type Master",
    // businessSubType: "Business Sub Type",
    title: "Title",
    titleEn: "Title (In English)",
    titleMr: "Title (In Marathi)",
    itemMaster: "Item Master",
    itemCategoryMaster: "Item Category Master",
    castMaster: "Caste Master",
    hawkingZone: "Street Vendor Zone",
    subCastMaster: "Sub Caste Master",
    penalty: "Penalty",
    bankMaster: "Bank Master",
    hawkingZoneWiseFacilities: "Street Vendor Zone Wise Facilities",
    taxTypeMaster: "Tax Type Master",
    taxNameMaster: "Tax Name Master",
    serviceTaxCollectionCycle: "Service Tax Collection Cycle",
    taxRateChartMaster: "Tax Rate Chart Master",
    noHawkingZone: "No Street Vendor Zone",
    hawkerMaster: "Street Vendor Master",
    streetvendorApplicantCategory: "Street Vendor Applicant Category",
    srNo: "Sr.No",
    actions: "Actions",
    hawkerTypePrefix: "Street Vendor Type Prefix (In English)",
    hawkerTypePrefixMr: "Street Vendor Type Prefix (In Marathi)",
    fromDate: "From Date",
    toDate: "To Date",
    action: "Action",
    hawkingZoneInfo: "Street Vendor Zone Info",
    itemName: "Item Name",
    noOfHawkersPresent: "No of Street Vendors Present",
    capacityOfHawkingZone: "Capacity of Street Vendor Zone",
    declarationOrder: "Declaration Order",
    declarationOrderNo: "Declaration Order No",
    declarationDate: "Declaration Date",
    declarationPhotoValidation: "declaration photo is required !!!",
    areaName: "Area Name ",
    hawkingZoneName: "Street Vendor Zone Name",
    streetvendorModeName: "Street Vendor Mode Name",
    gisId: "GIS Id",
    hawkingZonePrefix: "Street Vendor Zone Prefix",
    constraint: "Constraint",
    serviceTaxCollectionCyclePrefix: "Service-Tax Collection Cycle Prefix",
    hawkerTypeName: "Street Vendor Type Name",
    licenseValidityPrefix: "License Validity Prefix",
    noHawkingZoneName: "No Street Vendor Zone Name",
    noHawkingZoneprefix: "No Street Vendor Zone Prefix",
    itemCategoryPrefixMr: "Item Category Prefix (In Marathi)",
    itemCategoryPrefix: "Item Category Prefix (In English)",
    itemCategoryMr: "Item Category (In Marathi)",
    itemCategory: "Item Category (In English)",
    itemCategoryT: "Item Category",
    hawkingZoneWiseFacilitiesPrefix:
      "Street Vendor Zone Wise Facilities Prefix",
    facilities: "Facilities",
    hawkerPrefix: "Street Vendor Prefix",
    citySurveyNo: "City Survey No",
    issuanceOfHawkerLicensePath:
      "Street Vendor Management System / issuanceOfStreetVendorLicense",
    siteVisitPath: "Street Vendor Management System / Site Visit",
    taskTransfer: "Street Vendor Management System / Task Transfer",
    viewLocationOnMap: "View Location On Map",
    department: "Department Name",
    issuanceOfHawkerLicense: "Issuance of Street Vendor License",
    applicantType: "Applicant Type",
    applicantTypeOther: "Applicant Type Other",
    basicApplicationDetails: "Basic Application Details",
    serviceName: "Service Name ",
    applicationNumber: "Application Number",
    applicationDate: "Application Date",
    hawkerDetails: "Street Vendor Details",
    addressOfHawker: "Address",
    aadharAuthentication: "Aadhaar Authentication",
    aadhaarNo: "Aadhaar No",
    additionalDetails: "Business Details",
    documentsUpload: "Documents Upload",
    documentUploadview: "Documents",
    renewalDocumentsUpload: "Renewal Documents Upload",
    firstName: "First Name (In English)",
    firstNameMr: "First Name (In Marathi)",
    middleName: "Middle Name (In English)",
    middleNameMr: "Middle Name (In Marathi)",
    lastName: "Last Name (In English)",
    lastNameMr: "Last Name (In Marathi)",
    gender: "Gender",
    caste: "Caste",
    castOther: "Caste Other",
    castCategory: "Caste Category",
    castCategoryOther: "Other Caste Category",
    subCast: "Sub Caste",
    dateOfBirth: "Date of Birth ",
    age: "Age ",
    mobile: "Mobile No. ",
    emailAddress: "Email Address",
    disability: "Disability",
    rationCardNo: "Ration Card No",
    yes: "Yes",
    no: "No",
    typeOfDisability: "Type of Disability",
    oldSVSLicenseDate: "Old License Date",
    oldLicenseNo: "Old License Number",
    currentAddressofHawker: "Current Address",
    citySurveyNumber: "City Survey Number ",
    landmarkName: "Landmark ",
    villageName: "Village Name ",
    cityName: "City Name ",
    state: "State ",
    pinCode: "Pin Code ",
    lattitude: "Lattitude ",
    logitude: "Longitude ",
    permanentPostalAddressOfHawker: "Permanent/Postal Address",
    permanentAddressAsTheCorrespondenceAddress:
      "Permanent Address As The Correspondence Address",
    verfiyOtp: "Verify OTP",
    sendOTP: "Send OTP",
    aadhaarOtpVerified: "aadhaar otp verified successfully",
    otpVerification: "OTP VERIFICATION",
    verifiyOTP: "Verifiy OTP",
    resendOTP: "Resend OTP",
    sendOTPMessage:
      "a 6 digit one-time password is sent to your registered number",
    wardNo: "Ward No",
    wardName: "Ward Name",
    natureOfBusiness: "Nature of Business",
    hawkingDurationDaily: "Street Vendor Duration Daily",
    item: "Item",
    periodOfResidenceInMaharashtra:
      "Period of Residence In Maharashtra (In month)",
    periodOfResidenceInPcmc: "Period of Residence In PCMC (In month)",
    bankName: "Bank Name",
    branchName: "Branch Name",
    bankAccountNo: "Bank Account No",
    ifscCode: "IFSC Code",
    bankDetails: "Bank Details",
    documentUpload: "Documents Upload ",
    adharCard: "Aadhaar Card ",
    panCard: "Pan Card ",
    rationCard: "Ration Card ",
    disablityCretificatePhoto: "Disability Certificate ",
    otherDocumentPhoto: "Other Documents ",
    affidaviteOnRS100StampAttachement: "Affidavite On RS.100 Stamp Attachment ",
    affidavite: "Affidavit",
    fileNotUploaded: "File Not Uploaded",
    selectDate: "Please select a date",
    selectTitle: "Please select a title",
    enterFName: "Please enter first name ",
    enterMName: "Please enter middle name ",
    enterLName: "Please enter last name ",
    enterArea: "Please enter area ",
    enterRoadName: "Please enter road name ",
    enterLandmark: "Please enter a landmark ",
    enterCity: "Please enter a city ",
    enterPinCode: "Please enter a pincode ",
    enterPhoneNo: "Please enter a phone no. ",
    enterMobileNo: "Please enter a mobile no. ",
    enterEmailAddress: "Please enter an e-mail. ",
    enteraadhaarNo: "Please enter an aadhaar no. ",
    enterpanNo: "Please enter an pan no. ",
    enterRemarks: "Please enter a remark. ",
    attachFile: "Attach File",
    tax: "Tax",
    streetVendorType: "Street Vendor Type",
    waterAmount: "Water Amount",
    propertyTaxNumber: "Property Tax No",
    waterConsumerNo: "Water Consumer No",
    proprtyAmount: "Property Amount",
    viewBill: "View Bill",
    payBill: "Pay Bill",
    PropertyAndWaterTaxes: "Taxes",
    propertyTaxes: "Property Taxes",
    pay: "Pay",
    waterTaxes: "Water Taxes",
    areaOfStreetvendor: "Area of Street Vendor",
    education: "Education",
    voterNameYN: "the name of applicant is present in Voters list?",
    voterId: "Voter Identity No.",
    additionalLabour: "are additional workers present at the site?",
    maharashtra: "Maharashtra",
    oldLicenseDate: "Old License Date",
    pimpriChinchwad: "Pimpri Chinchwad",
    applicantItsSelf: "Applicant its self",
    withHelpofFamilyMembers: "with help of family members",
    byKeepingservant: "by keeping servant",
    roadWithAtBusinessLocation: "road width at the business location",
    addButtonMaster: "Add",
    add: "Add",
    save: "Save",
    update: "Update",
    clear: "Clear",
    exit: "Exit",
    back: "Back",
    saveAndNext: "Save & Next",
    next: "Next",
    finish: "Finish",
    submit: "Submit",
    oldStreetVendorDetails: "Old Street Vendor Details",
    fileSizeInstrction: "file size should not be greater than 10 mb ",
    citySurveyNoValdation: "city survey number is required  !!!",
    citySurveyNoValdationA: "city survey number must be number !!!",
    areaNameValidation: "area name selection is required  !!!",
    hawkingZoneNameValidation:
      "Street Vendor zone name selection is required  !!!",
    zoneNameValidation: "zone name selection is required  !!!",
    titleValidation: "title selection is required  !!!",
    firstNameValidation: "first name (In English) is required  !!!",
    firstNameValidationMr: "first name (In Marathi) is required  !!!",
    middleNameValidation: "middle name (In English) is required  !!!",
    middleNameValidationMr: "middle name (In Marathi) is required  !!!",
    lastNameValidation: "last name (In English) is required  !!!",
    lastNameValidationMr: "last name (In Marathi) is required  !!!",
    genderValidation: "gender selection is required  !!!",
    religionValidation: "religion selection is required  !!!",
    casteValidation: "caste selection is required !!!",
    casteOtherValidation: "other caste is required !!!",
    castCategoryValidation: "caste category selection is required !!!",
    casteCategoryOtherValidation: "other caste category is required !!!",
    subCasteValidation: "sub caste selection is required  !!!",
    dateOfBirthValidation: "date of birth is required   !!!",
    ageValidation: "age is required  !!!",
    mobileNovalidation: "mobile number is required   !!!",
    rationCardNoValidation: "ration card number is required  !!!",
    applicantTypeValidation: "applicant type selection is required  !!!",
    applicantTypeOtherValidation: "applicant type other is required  !!!",
    disablityNameYNValidation: "disability yes no selection is required !!!",
    typeOfDisabilityValidation: "type of disability selection is required !!!",
    disablityPrecntageValidation: "disability percentage is required!!!",
    emailIdValidation: "email id is required  !!!",
    emailIdValidationA: "please enter valid email address !!!",
    landmarkNameValidation: "landmark name selection is required  !!!",
    villageNameValidation: "village name selection is required  !!!",
    roadNameValidation: "road name selection is required  !!!",
    cityNameValidation: "city name is required  !!!",
    stateNameValidation: "state name is required  !!!",
    pinCodeValidation: "pin code selection is required  !!!",
    lattitudeValidation: "latitude is required  !!!",
    logitudeValidation: "longitude s required  !!!",
    aadharNumberValidation: "aadhaar number is required  !!!",
    propertyTaxNumberValidation: "property Tax Number is required  !!!",
    waterConsumerNoValidation: "water Consumer Number is required  !!!",
    proprtyTaxAmountNumberValidation: "property amount is required  !!!",
    waterTaxAmountValidation: "water tax amount is required  !!!",
    streetvendorModeNameValidation:
      "street vendor Mode Name selection is required  !!!",
    wardNameValidation: "ward name selection is required  !!!",
    natureOfBusinessValidation: "nature of business name is required  !!!",
    hawkingDurationDailyValidation:
      "street vendor duration daily selection is required  !!!",
    hawkerTypeValidation: "street vendor type selection is required  !!!",
    itemValidation: "Constraint selection is required  !!!",
    educationValidation: "education selection is required  !!!",
    areaOfStreetvendorValidation: "area of street vendor is required  !!!",
    periodOfResidenceInPCMCValidation:
      "period of residence in PCMC is required  !!!",
    periodOfResidenceInMaharashtraValidation:
      "period of residence in maharashtra is required  !!!",
    voterIdValidation: "Voter Identity Number is required  !!!",
    voterNameYNValidation: "selection is required  !!!",
    oldLicenseYNValidation: "selection is required  !!!",
    bankMasterValidation: "bank name selection is required  !!!",
    bankAccountNoValidation: "bank account number is required  !!!",
    ifscCodeValidation: "IFSC code is required  !!!",
    branchNameValidation: "branch name is required  !!!",
    aadhaarCardPhotoValidation: "aadhaar card is required  !!!",
    panCardPhotoValidation: "pan card is required  !!!",
    rationCardPhotoValidation: "ration card is required  !!!",
    disablityCertificatePhotoValidation:
      "disablity certificate is required  !!!",
    affidaviteOnRS100StampAttacheValidation:
      "affidavite on rs100 statmp attachement is required  !!!",
    otherDocumentPhotoValidation: "other document is required  !!!",
    oldLicenseNoValidation: "old license number is required  !!!",
    oldLicenseDateValidation: "old license date is required  !!!",
    documentUpload1: "Doucument Upload",
    documentUploadSuccessfully: "document uploaded successfully !!!",
    areYouWantDelete: "are you sure you want to delete the file ?",
    fileDeletedSuccessfully: "file deleted successfully !!!",
    fileIsSafe: "file is safe",
    somethingWentWrong: "something went wrong ..!!!",
    siteVisitPhoto1: "Site Visit Photo 1",
    siteVisitPhoto2: "Site Visit Photo 2",
    siteVisitPhoto3: "Site Visit Photo 3",
    siteVisitPhoto4: "Site Visit Photo 4",
    siteVisitPhoto5: "Site Visit Photo 5",
    oldLicenseYN: "Old license is available ?",
    disablityNameYN: "is disabled ?",
    applicationStatus: "Application Status",
    viewForm: "View Form",
    print: "Print",
    paymentCollection: "Payment Collection",
    paymentReceipt: "Payment Receipt",
    generateCertitifcate: "Generate Certificate",
    generateIDCard: "Generate ID Card",
    viewIDCard: "View ID Card",
    loiGenerationRecipt: "Service Acceptance Letter",
    viewDocument: "View Document",
    siteVisitFormPreview: "Site Visit Form Preview",
    DocumentName: "Document Name",
    mandatory: "Mandatory",
    nonMandatory: "Non Mandatory",
    enterRemarkForApplication: "Enter Remark for Application",
    approve: "Approve",
    reassign: "Reassign",
    siteVisitAppointmentSchedule: "Site Visit Appointment Schedule",
    addSlotsOfSiteVisit: "Slots of Site Visits",
    addMore: "Add More",
    delete: "Delete",
    bookNow: "Book Now",
    siteVisitSchedule: "Site Visit Schedule",
    fromDateValidation: "from date selection is required  !!!",
    hawkerTypePrefixValidation:
      "Street Vendor Type Prefix (In English) is required ",
    hawkerTypePrefixMrValidation:
      "Street Vendor Type Prefix (In Marathi) is required ",
    hawkerTypeValidationTT: "Street Vendor Type selection is required ",
    hawkerTypeValidationT: "Street Vendor Type (In English) is required ",
    hawkerTypeMrValidation: "Street Vendor Type In Marathi is required ",
    hawkerTypeEnValidation: "Street Vendor Type In English is required",
    itemPrefixValidation: "Item Master Prefix is required  (In English) !!! ",
    itemPrefixMrValidation: "Item Master Prefix is required  (In Marathi) !!! ",
    itemCategoryValidation: "item category selection is required  !!!",
    itemCategoryValidationEn: "item category is required (In English)  !!!",
    itemCategoryValidationMr: "item category is required (In Marathi) !!!",
    itemValidationEn: "item is required  (In English) !!! ",
    itemValidationMr: "item is required  (In Marathi) !!! ",
    itemPrefixEn: "Item Prefix (In English)",
    itemPrefixMr: "Item Prefix (In Marathi)",
    itemEn: "Item (In English)",
    itemMr: "Item (In Marathi)",
    licenseValidityPrefixValidation:
      "License Validity Prefix is required  (In English) !!! ",
    licenseValidityPrefixMrValidation:
      "License Validity Prefix is required  (In Marathi) !!! ",
    licenseValidityValidation: "License Validity is required  ",
    zoneMaster: "Zone Master",
    wardMaster: "Ward Master",
    areaMaster: "Area Master",
    zoneName: "Zone Name",
    roadName: "Road Name",
    landmark: "Landmark",
    zoneNameEn: "Zone Name (In English)",
    wardNameEn: "Ward Name (In English)",
    zoneNameMr: "Zone Name (In Marathi)",
    wardNameMr: "Ward Name (In Marathi)",
    areaNameEn: "Area Name (In English)",
    areaNameMr: "Area Name (In Marathi)",
    areaZoneWardRoadLandMarkMappingMaster:
      "Area Zone Ward Road Landmark Mapping Master",
    zoneWardArea: "Zone Ward Area",
    licenseValidityMrValidation:
      "License Validity is required  (In Marathi) !!! ",
    licenseValidityEn: "License Validity in (Year) (In English)",
    licenseValidityMr: "License Validity in (Year) (In Marathi)",
    licenseValidityPrefixEn: "License Validity Prefix (In English)",
    licenseValidityPrefixMr: "License Validity Prefix (In Marathi) ",
    hawkingZonePrefixValidation:
      "Street Vendor Zone Prefix is required  (In English) !!!",
    hawkingZonePrefixMrValidation:
      "Street Vendor Zone Prefix is required  (In Marathi) !!!",
    gisIdValidation: "GIS id is required  !!!",
    hawkingNameValidation:
      "Street Vendor zone name is required  (In English) !!! ",
    hawkingNameMrValidation:
      "Street Vendor zone name is required  (In Marathi) !!! ",
    declarationDateValidation: "declaration date is required  !!!",
    declarationOrderNoValidation: "declaration order number is required  !!!",
    capacityOfHawkingZoneValidation:
      "capacity of Street Vendor zone is required  !!!",
    noOfHawkersPresentValidation:
      "number of street vendor present is required  !!!",
    hawkingZoneInfoValidation:
      "Street Vendor zone info is required  (In English) !!! ",
    hawkingZoneInfoMrValidation:
      "Street Vendor zone info is required  (In Marathi) !!! ",
    hawkingZoneInfoMr: "Street Vendor Zone Info (In Marathi)",
    numberOfHawkersPresent: "Number of Street Vendor Present",
    declarationOrderNumber: "Declaration Order Number",
    hawkingZoneNameMr: "Street Vendor Zone Name (In Marathi) ",
    hawkingZoneNameEn: "Street Vendor Zone Name (In English) ",
    noHawkingZoneNameMr: "No Street Vendor Zone Name (In Marathi) ",
    noHawkingZoneNameEn: "No Street Vendor Zone Name (In English) ",
    hawkerMode: "Street Vendor Mode",
    hawkerModePrefixEn: "Street Vendor Mode Prefix (In English)",
    noHawkingZonePrefixEn: "No Hawking Zone Prefix (In English)",
    noHawkingZonePrefixMr: "No Hawking Zone Prefix (In Marathi)",
    hawkerModePrefixMr: "Street Vendor Mode Prefix (In Marathi)",
    hawkerModeEn: "Street Vendor Mode (In English)",
    hawkerModeMr: "Street Vendor Mode (In Marathi)",
    hawkerModePrefixValidation:
      "Street Vendor mode prefix is required   (In English) !!! ",
    hawkerModePrefixMrValidation:
      "Street Vendor mode prefix is required   (In Marathi) !!! ",
    hawkerModeValidation: "Street Vendor mode is required   (In English) !!! ",
    hawkerModeMrValidation:
      "Street Vendor type mode is required   (In Marathi) !!! ",
    noHawkingZoneMr: "No Hawking Zone Name (In Marathi)",
    noHawkingZoneEn: "No Hawking Zone Name (In English)",
    noHawkingZoneInfo: "No Street Vendor Zone Info",
    declarationOrderValidation: "declaration order is required   !!! ",
    noHawkingZoneEnValidation:
      "No Hawking Zone Name (In English) is required  !!!",
    noHawkingZoneMrValidation:
      "No Hawking Zone Name (In Marathi) is required  !!!",
    noHawkingZoneInfoValidation: "No Street Vendor Zone Info is required  !!!",
    applicantPrefixMr: "Applicant Prefix (In Marathi)",
    applicantPrefixEn: "Applicant Prefix (In English)",
    applicantTypeMr: "Applicant Type (In Marathi)",
    applicantTypeEn: "Applicant Type (In English)",
    applicantSubTypeMr: "Applicant SubType (In Marathi)",
    applicantSubTypeEn: "Applicant SubType (In English)",
    applicantPrefixValidation: "applicant prefix is required  !!!",
    typeValidation: "applicant type is required  !!!",
    subtypeValidation: "applicant subtype is required  !!!",
    hawkingZoneWiseFacilitiesPrefixEn:
      "Hawking Zone Wise Facilities Prefix (In English)",
    hawkingZoneWiseFacilitiesPrefixMr:
      "Hawking Zone Wise Facilities Prefix (In Marathi)",
    facilitynameEn: "Facility Name (In English)",
    facilitynameMr: "Facility Name (In English)",
    hawkingZoneWiseFacilitiesPrefixValidation:
      "Street Vendor zonewise facility prefix is required  !!!",
    hawkingZoneWiseFacilitiesPrefixMrValidation:
      "Street Vendor zonewise facility prefix is required  !!!",
    hawkigZoneValidation: "Street Vendor zone selection is required  !!!",
    facilitiesValidation: "facility name is required  !!!",
    facilitiesMrValidation: "facility name is required  !!!",
    hawkingDurationDailyPrefixEn: "Street Vendor duration prefix (In English)",
    hawkingDurationDailyPrefixMr: "Street Vendor duration prefix (In Marathi)",
    hawkingDurationDailyFrom: "Street Vendor Duration Daily From",
    hawkingDurationDailyTo: "Street Vendor Duration Daily To",
    businessSubType: "Business Sub Type",
    businessType: "Business Type",
    hawkingDurationDailyPrefixValidation:
      "Street Vendor Duration Daily Prefix is required  !!!",
    hawkingDurationDailyFromValidation:
      "Street Vendor duration daily from is required  !!!",
    hawkingDurationDailyToValidation:
      "Street Vendor duration daily to is required  !!!",
    hawkerName: "Street Vendor Name",
    businessTypeValidation: "business type selection is required  !!!",
    businessSubTypeValidation: "business subtype selection is required  !!!",
    businessSubTypePrefixMr: "Business Sub Type Prefix (In Marathi)",
    businessSubTypePrefixEn: "Business Sub Type Prefix (In English)  ",
    businessSubTypeEn: "Business SubType (In English)",
    businessSubTypeMr: "Business SubType (In Marathi)",
    businessSubTypePrefixEnValidation:
      "business subtype prefix is required  !!!",
    businessSubTypePrefixMrValidation:
      "business subtype prefix is required  !!!",
    businessSubTypeMrValidation: "business subtype name is required  !!!",
    businessSubTypeEnValidation: "business subtype name is required  !!!",
    businessTypePrefixEn: "Business Prefix (In English) ",
    businessTypePrefixMr: "Business Prefix (In Marathi) ",
    businessTypeEn: "Business (In English)",
    businessTypeMr: "Business (In Marathi)",
    businessTypePrefixEnValidation: "business prefix is required  !!!",
    businessTypePrefixMrValidation: "business prefix is required  !!!",
    businessTypeMrValidation: "business name is required  !!!",
    businessTypeEnValidation: "business name is required  !!!",
    renewalOfIssuanceOfHawkerLicense: "Renewal of Street Vendor License",
    cancellationOfIssuanceOfHawkerLicense:
      "Cancellation of Street Vendor License",
    transferOfIssuanceOfHawkerLicense: "Transfer of Street Vendor License",
    issuanceOfHawkerLicenseNumber: "Street Vendor License Number",
    issuanceOfHawkerLicenseNumber1: "1) Street Vendor License Number",
    siteVisitDate: "Site Visit Date",
    siteVisitTime: "Site Visit Time",
    streetVendorFullName: "Street Vendor Full Name",
    streetVendorFullNameAndDateOfBirth:
      "2) Street Vendor Full Name and Date of Birth",
    serviceNameValidation: "service name selection is required  !!!",
    hawkingSummaryReport: "Street Vendor Summary Report",
    toDateValidation: "toDate selection is required  !!!",
    hawkerPhoto: "Street Vendor Photo ",
    hawkerPhotoValidation: "Street Vendor photo is required  !!!",
    chequeorPassbookPhoto:
      "Photocopy of cross cheque or. First page of the passbook",
    chequeorPassbookPhotoValidation:
      "Photocopy of cross cheque or. First page of the passbook is required  !!!",
    shopBusinessOldLicensePhoto:
      "Shop act licence / Business licence from PCMC in case of available",
    shopBusinessOldLicensePhotoValidation:
      "Shop act licence / Business licence from PCMC in case of available is required  !!!",
    //pg labels
    yourPaymentDoneSuccess: " Your payment done successful!!!",
    paymentFailed: "Payment failed!!!",
    orderId: "Order Id ",
    trackingId: "Tracking Id",
    bankRefNo: "Bank Reference No",
    billingName: "Billing Name",
    billingAdd: "Billing Address",
    billingCity: "Billing City",
    billingZip: "Billing Zipcode ",
    billingCountry: "Billing Country",
    billingEmail: "Billing Email",
    mobileNo: "Mobile No",
    billingState: "Billing State",
    transactionDate: "Transaction Date",
    goToList: "Go To List",
    totalAmount: "Total Amount",
    loiNo: "LOI No",
    licenseDuration: "License Duration",
    applicationName: "Module Name",
    applicationNameValidation: "module name selection is required  !!!",
    count: "Count",
    totalApplication: "Total Application",
    editApplication: "Edit Application",
    verificationDept: "verification DEPT",
    verificationAo: "verification AO",
    verificationWo: "verification WO",
    siteVisitReschedule: "Site Visit Reschdule",
    cancelCertificate: "cancel certificate",
    viewCancellationLetter: "view cancellation letter",
    languageValidation: "Must be only english characters",
    zoneWardAreaMapping: "Zone Ward Area is required !!!",
    landMarkValidation: "Landmark is required !!!",
    raodNameValidation: "Road Name is required !!!",
    disablityPrecntage: "Disability Percentage",
    avalibleSlots: "available slots",
    toTime: "To Time",
    fromTime: "From Time",
    siteVisit: "Site Visit",
  },
  mr: {
    transferOfIssuanceOfHawkerLicense: "पथविक्रेता परवाना हस्तांतरण",
    loiGenerationRecipt: "सेवा स्वीकृती पत्र",
    receiptModeDetails: "पावती प्रकार तपशील",
    chargeName: "शुल्काचे नाव",
    loiPreview: "सेवा स्वीकृती पत्र पूर्वावलोकन",
    iCard: "ओळखपत्र",
    view: "पहा",
    viewCertificate: "प्रमाणपत्र पहा",
    amount: "रक्कम",
    streetVendorQuestion: "रस्त्यावरील विक्रेता प्रश्न",
    or: "किंवा",
    loiRecord: "LOI रेकॉर्ड",
    loiNO: "LOI क्र.",
    loiGeneration: "LOI जनरेशन",
    loiPrint: "LOI प्रिंट",
    siteVisitSchedule: "साइट भेटीचे वेळापत्रक",
    loiCollection: "पेमेंट संकलन",
    paymentCollection: "पेमेंट संकलन",
    search: "शोधा",
    statusValidation: "स्थिती निवड आवश्यक",
    licenseNoValidation: "license number is required  !!!",
    and: "आणि",
    paymentMode: "पेमेंट मोड",
    paymentType: "पैसे भरण्याची पध्दत",
    loiDetails: "LOI तपशील",
    loiDate: "LOI तारीख",
    applicationNo: "अर्ज क्र.",
    rate: "दर",
    total: "एकूण",
    totalInWords: "शब्दांमध्ये एकूण शुल्क",
    licenseType: "परवाना प्रकार",
    durationOfLicenseValidity: "परवान्याच्या वैधतेचा कालावधी (वर्षात)",
    hawkerType: "पथविक्रेता प्रकार",
    licenseValidity: "परवाना वैधता (वर्षे)",
    licenseValidityHeader: "परवाना वैधता",
    applicantDetails: "अर्जदाराचे तपशील",
    paymetMode: "पेमेंट मोड",
    dateOfIssuance: "जारी करण्याची तारीख",
    calendarYear: "जानेवारी ते डिसेंबर असे वर्ष",
    chargesDetails: "शुल्काचा तपशील",
    serviceCharge: "सेवा शुल्क",
    financialYear: "आर्थिक वर्ष",
    checkFormLicenseValidityForm: "परवाना वैधता फॉर्म तपासा",
    generateLoi: "LOI व्युत्पन्न करा",
    previewLoi: "LOI चे पूर्वावलोकन करा",
    verifyLoi: "LOI सत्यापित करा",
    serviceChargeTypeName: "सेवा शुल्काचे प्रकार नाव",
    hmsDashboard: "पथविक्रेता व्यवस्थापन प्रणाली",
    totalCharges: "एकूण शुल्क",
    applicantName: "अर्जदाराचे नाव",
    receiptAmount: "पावती रक्कम",
    receiptNumber: "पावती क्रमांक",
    receiptDate: "पावती तारीख",
    ddDate: "डिमांड ड्राफ्ट तारीख",
    ddNo: "डिमांड ड्राफ्ट क्रमांक",
    AptBook: "अपॉइंटमेंट स्लॉट बुकिंग",
    streetVendorManagmentSystem: "पथविक्रेता व्यवस्थापन प्रणाली",
    HMS: "पथविक्रेता व्यवस्थापन प्रणाली",
    inFeet: "रुंदीमध्ये",
    streetVendorType: "पथविक्रेत्याचा प्रकार",
    oldLicenseDate: "जुनी परवाना तारीख",
    siteVisitPhotoUpload: "साइट भेटीचे फोटो अपलोड करा",
    siteVisitPhoto: "साइट भेटीचे फोटो",
    streetVendorThumb1: "बायोमेट्रिक अंगठ्याचा ठसा 1",
    streetVendorThumb2: "बायोमेट्रिक अंगठ्याचा ठसा 2",
    businessTrafficCongestion:
      "व्यवसायामुळे सद्द्यस्थितीत रहदारीस अडथळा होतो का?",

    dashboard: "पिंपरी-चिंचवड महानगरपालिका डॅशबोर्ड",
    roadWithBusinessLocation: "व्यवसाय ठिकाणची रस्ता रुंदी(फूट)",
    streetVendorInformation: "पथविक्रेता माहिती",
    businessHawkinglocation: "व्यवसाय कार्य",
    applicantItsSelf: "अर्जदार स्वतः",
    withHelpofFamilyMembers: "कुटुंबातील सदस्यांच्या मदतीने",
    streetVendorPhoto: "फोटो",
    byKeepingservant: "नोकर ठेवून",
    inspectionSellingGoods:
      "अर्जदार नमूद केलेल्या जागेवर व्यवसाय करीत असल्याचे तपासणीत आढळले?",
    master: "मास्टर्स",
    transactions: "व्यवहार",
    fileNotUploaded: "फाइल अपलोड केली नाही",
    report: "अहवाल",
    masterPath: "अग्निशमन यंत्रणा / मास्टर ",
    transactionPath: "कायदेशीर प्रकरण/ व्यवहार ",
    reportPath: "कायदेशीर प्रकरण/ अहवाल ",
    department: "Department Name",
    ward: "प्रभाग",
    zone: "झोन",
    religionPath: "पथविक्रेता व्यवस्थापन प्रणाली / मास्टर / धर्म",
    hawkerTypePath:
      "पथविक्रेता व्यवस्थापन प्रणाली / मास्टर / पथविक्रेता प्रकार",
    businessTypeMasterPath:
      "पथविक्रेता व्यवस्थापन प्रणाली / मास्टर / व्यवसाय प्रकार मास्टर",
    businessSubTypePath:
      "पथविक्रेता व्यवस्थापन प्रणाली / मास्टर / व्यवसाय उपप्रकार",
    titlePath: "पथविक्रेता व्यवस्थापन प्रणाली / मास्टर / शीर्षक",
    itemMasterPath: "पथविक्रेता व्यवस्थापन प्रणाली / मास्टर / वस्तु मास्टर",
    itemCategoryMasterPath:
      "पथविक्रेता व्यवस्थापन प्रणाली / मास्टर / वस्तु श्रेणी मास्टर",
    castCategoryPath: "पथविक्रेता व्यवस्थापन प्रणाली / मास्टर / जात श्रेणी",
    castMasterPath: "पथविक्रेता व्यवस्थापन प्रणाली / मास्टर / जात मास्टर",
    hawkingZonePath:
      "पथविक्रेता व्यवस्थापन प्रणाली / मास्टर /  पथविक्रेता क्षेत्र",
    subCastMasterPath: "पथविक्रेता व्यवस्थापन प्रणाली / मास्टर / सब जात मास्टर",
    licenseValidityPath:
      "पथविक्रेता व्यवस्थापन प्रणाली / मास्टर / परवाना वैधता",
    penaltyPath: "पथविक्रेता व्यवस्थापन प्रणाली / मास्टर / दंड",
    bankMasterPath: "पथविक्रेता व्यवस्थापन प्रणाली / मास्टर / बँक मास्टर",
    hawkingZoneWiseFacilitiesPath:
      "पथविक्रेता व्यवस्थापन प्रणाली / मास्टर / पथविक्रेता झोननिहाय सुविधा",
    taxTypeMasterPath:
      "पथविक्रेता व्यवस्थापन प्रणाली / मास्टर / कर प्रकार मास्टर",
    taxNameMasterPath: "पथविक्रेता व्यवस्थापन प्रणाली / मास्टर / कर नाव मास्टर",
    serviceTaxCollectionCyclePath:
      "पथविक्रेता व्यवस्थापन प्रणाली / मास्टर / सेवा कर संकलन सायकल",
    taxRateChartMasterPath:
      "पथविक्रेता व्यवस्थापन प्रणाली / मास्टर / कर दर चार्ट मास्टर",
    noHawkingZonePath:
      "पथविक्रेता व्यवस्थापन प्रणाली / मास्टर / पथविक्रेता क्षेत्र नाही",
    hawkerMasterPath:
      "पथविक्रेता व्यवस्थापन प्रणाली / मास्टर / पथविक्रेता मास्टर",
    streetvendorApplicantCategory: "Street Vendor Applicant Categor",
    religion: "धर्म",
    businessTypeMaster: "व्यवसायचा प्रकार मास्टर",
    businessSubType: "व्यवसाय उपप्रकार",
    title: "शीर्षक",
    itemMaster: "वस्तु मास्टर",
    itemCategoryMaster: "वस्तु श्रेणी मास्टर",
    castCategory: "जात श्रेणी",
    castMaster: "जात मास्टर",
    hawkingZone: "पथविक्रेता क्षेत्र",
    subCastMaster: "सब जात मास्टर",
    penalty: " दंड",
    bankMaster: "बँक मास्टर",
    hawkingZoneWiseFacilities: "पथविक्रेत्याच्या झोननिहाय सुविधा",
    taxTypeMaster: " कर प्रकार मास्टर",
    taxNameMaster: "कर नाव मास्टर",
    serviceTaxCollectionCycle: "सेवा कर संकलन सायकल",
    taxRateChartMaster: "कर दर चार्ट मास्टर",
    noHawkingZone: "न पथविक्रेता क्षेत्र",
    hawkerMaster: "पथविक्रेत्याचा मास्टर",
    courtName: "न्यायालयाचे नाव",
    roadName: "रस्त्याचे नाव",
    address: "पत्ता",
    landmark: "जवळची खूण",
    cityOrVillage: "शहर / गाव",
    pincode: "Pin Code",
    srNo: "अनुक्रमांक",
    actions: "क्रिया ",
    hawkerTypePrefix: "पथविक्रेत्याचा उपसर्ग प्रकार (इंग्रजी मध्ये)",
    hawkerTypePrefixMr: "पथविक्रेत्याचा उपसर्ग प्रकार (मराठी मध्ये)",
    fromDate: "या तारखेपासून",
    toDate: "आजपर्यंत",
    hawkerType1: "पथविक्रीचा प्रकार",
    remark: "शेरा",
    roadWithAtBusinessLocation: "व्यवसायाच्या ठिकाणी रस्त्याची रुंदी",
    action: "क्रिया",
    itemName: "वस्तु",
    noOfHawkersPresent: "उपस्थित पथविक्रेता्सची संख्या",
    declarationOrder: "घोषणा आदेश",
    declarationOrderNo: "घोषणा आदेश क्र",
    declarationDate: "घोषणा तारीख",
    declarationPhotoValidation: "घोषणा फोटो आवश्यक आहे !!!",
    areaName: "क्षेत्राचे नाव",
    hawkingZoneName: "पथविक्रेता झोनचे नाव",
    streetvendorModeName: "पथविक्रेता व्यवसायाचे स्वरूप",
    gisId: "GIS आयडी",
    serviceTaxCollectionCyclePrefix: "सेवा कर संकलन चक्र उपसर्ग",
    hawkingZonePrefix: "पथविक्रेत्याच्या झोनचा उपसर्ग",
    hawkerTypeName: "पथविक्रीच्या प्रकाराचे नाव",
    licenseValidityPrefix: "परवाना वैधता उपसर्ग",
    noHawkingZoneName: "न पथविक्रेता झोनचे नाव",
    noHawkingZoneprefix: "न पथविक्रेता झोनचा उपसर्ग नाही",
    itemCategoryPrefixMr: "वस्तुच्या श्रेणीचा उपसर्ग (मराठी मध्ये)",
    itemCategoryPrefix: "वस्तुच्या श्रेणीचा उपसर्ग (इंग्रजी मध्ये)",
    itemCategory: "वस्तुची श्रेणी (इंग्रजी मध्ये)",
    itemCategoryT: "वस्तुची श्रेणी",
    itemCategoryMr: "वस्तुची श्रेणी (मराठी मध्ये)",
    hawkingZoneWiseFacilitiesPrefix: "पथविक्रेता झोननिहाय सुविधा उपसर्ग",
    facilities: "सुविधा",
    hawkerPrefix: "पथविक्रेत्याचा उपसर्ग",
    addButtonMaster: "Add",
    add: "नवीन नोंदणी करा",
    save: "जतन करा",
    update: "अद्यायावत करा",
    clear: "रिक्त",
    exit: "बाहेर पडा",
    back: "मागे",
    saveAndNext: "जतन करा आणि पुढे",
    finish: "समाप्त",
    next: " पुढे",
    fileSizeInstrction: "फाइल आकार १० mb पेक्षा जास्त नसावा",
    issuanceOfHawkerLicense: "पथविक्रेता परवाना जारी करणे",
    siteVisit: "स्थळ भेट",
    issuanceOfHawkerLicensePath:
      "पथविक्रेता व्यवस्थापन प्रणाली / पथविक्रेता परवाना जारी करणे",
    siteVisitPath: "पथविक्रेता व्यवस्थापन प्रणाली /साइटला भेट द्या",
    taskTransfer: "पथविक्रेता व्यवस्थापन प्रणाली / कार्य हस्तांतरण",
    viewLocationOnMap: "नकाशावर स्थान पहा",
    oldSVSLicenseDate: "जुन्या परवाण्याची तारीख",
    oldLicenseNo: "जुना परवाना क्रमांक",
    issuanceOfHawkerLicenseT: "पथविक्रेता परवाना जारी करणे",
    applicantType: "अर्जदाराचा प्रकार",
    applicantTypeOther: "अर्जदाराचा प्रकार इतर",
    basicApplicationDetails: "मूलभूत अर्ज तपशील",
    serviceName: "सेवेचे नाव ",
    applicationNumber: "अर्ज क्रमांक",
    applicationDate: "अर्जाची तारीख",
    citySurveyNo: "शहर सर्वेक्षण क्रमांक",
    hawkerDetails: "पथविक्रेत्याच्या तपशील",
    addressOfHawker: "पत्ता",
    aadharAuthentication: "आधार प्रमाणीकरण",
    aadhaarNo: "आधार क्रमांक",
    additionalDetails: "व्यवसाय तपशील",
    documentsUpload: "दस्तऐवज अपलोड",
    renewalDocumentsUpload: "नूतनीकरण दस्तऐवज अपलोड",
    documentUploadview: "दस्तऐवज",
    titleMr: "शीर्षक (मराठी मध्ये)",
    titleEn: "शीर्षक (इंग्रजी मध्ये)",
    firstName: "पहिले नाव (इंग्रजी मध्ये)",
    firstNameMr: "पहिले नाव (मराठी मध्ये)",
    middleName: "वडीलांचे/पतीचे नाव (इंग्रजी मध्ये)",
    middleNameMr: "वडीलांचे/पतीचे नाव (मराठी मध्ये)",
    lastName: "आडनाव (इंग्रजी मध्ये)",
    lastNameMr: "आडनाव (मराठी मध्ये)",
    gender: "लिंग",
    caste: "जात",
    castOther: "इतर जात",
    castCategoryOther: "इतर जात श्रेणी",
    subCast: "पोटजात",
    dateOfBirth: "जन्मतारीख ",
    age: "वय",
    mobile: "दूरध्वनी क्रमांक",
    emailAddress: "ई-मेल आयडी ",
    disability: "दिव्यांग",
    rationCardNo: "शिधापत्रिका क्रमांक",
    yes: "होय",
    no: "नाही",
    typeOfDisability: "दिव्यांगाचा प्रकार",
    currentAddressofHawker: "सध्याचा पत्ता",
    citySurveyNumber: "शहर सर्वेक्षण क्रमांक ",
    landmarkName: "जवळची खुण",
    villageName: "गावाचे नाव ",
    cityName: "शहराचे नाव ",
    state: "राज्य ",
    pinCode: "पिन कोड ",
    lattitude: "अक्षांश ",
    logitude: "रेखांश ",
    permanentPostalAddressOfHawker: "कायमस्वरूपीचा/पत्रव्यवहाराचा पत्ता",
    permanentAddressAsTheCorrespondenceAddress:
      "पत्रव्यवहाराचा पत्ता म्हणून कायमचा पत्ता",
    wardNo: "प्रभाग क्रमांक ",
    wardName: "प्रभागाचे नाव ",
    natureOfBusiness: "व्यवसायाचे स्वरूप ",
    hawkingDurationDaily: "पथविक्रीचा दैनिक कालावधी",
    item: "वस्तु",
    periodOfResidenceInMaharashtra:
      "महाराष्ट्रात राहण्याचा कालावधी (महिन्यामध्ये)",
    periodOfResidenceInPcmc: "पीसीएमसीमध्ये राहण्याचा कालावधी (महिन्यामध्ये)",
    bankName: "बँकेचे नाव",
    branchName: "शाखेचे नाव",
    bankAccountNo: "बँक खाते क्रमांक",
    ifscCode: "आयफएससी कोड",
    hawkerTypeEn: "पथविक्रीचा प्रकार  (इंग्रजी मध्ये)",
    hawkerTypeMr: "पथविक्रीचा प्रकार (मराठी मध्ये)",
    bankDetails: "बँक तपशील",
    documentUpload: "दस्तऐवज अपलोड करा",
    adharCard: "आधार कार्ड ",
    rationCard: "शिधापत्रिका ",
    disablityCretificatePhoto: "दिव्यांग प्रमाणपत्र ",
    otherDocumentPhoto: "इतर दस्तऐवज ",
    affidaviteOnRS100StampAttachement:
      "रु. १००/- चे स्टॅम्प पेपरवर प्रतिज्ञा पत्र ",
    affidavite: " प्रतिज्ञा पत्र ",
    panCard: "पॅन कार्ड ",
    waterConsumerNo: "पाणी ग्राहक क्र.",
    waterAmount: "रक्कम",
    proprtyAmount: "रक्कम",
    propertyTaxNumber: "मिळकत कर क्र.",
    tax: "कर",
    viewBill: "बिल पहा",
    pay: "बिल भरा",
    PropertyAndWaterTaxes: "कर",
    propertyTaxes: "मालमत्ता कर",
    waterTaxes: "पाणी कर ",
    pimpriChinchwad: "पिंपरी चिंचवड",
    maharashtra: "महाराष्ट्र",
    areaOfStreetvendor: "पथविक्री क्षेत्र",
    voterNameYN: "अर्जदाराचे नाव मतदार यादीत आहे का?",
    voterId: "मतदार ओळखपत्र क्रमांक.",
    additionalLabour: "हॉकिन्सच्या ठिकाणी अतिरिक्त कामगार उपस्थित आहेत?",
    education: "शिक्षण",
    verfiyOtp: "ओटीपी तपसा",
    sendOTP: "ओटीपी पाठवा",
    aadhaarOtpVerified: "आधार ओटीपी यशस्वीरित्या सत्यापित",
    otpVerification: "ओटीपी पडताळणी",
    verifiyOTP: "ओटीपी सत्यापित करा",
    resendOTP: "ओटीपी पुन्हा पाठवा",
    sendOTPMessage:
      "तुमच्या नोंदणीकृत क्रमांकावर ६ अंकी वन-टाइम पासवर्ड पाठवला",
    selectDate: "कृपया तारीख निवडा",
    selectTitle: "कृपया शीर्षक निवडा",
    enterFName: "कृपया पहिले नाव भरा ",
    enterMName: "कृपया मधले  नाव भरा ",
    enterLName: "कृपया शेवटचे नाव भरा ",
    enterArea: "कृपया क्षेत्राचे नाव भरा ",
    enterRoadName: "कृपया रस्त्याचे नाव भरा ",
    enterLandmark: "कृपया  महत्त्वाची खूण भरा",
    enterCity: "कृपया  शहराचे / गावाचे नाव भरा ",
    enterPinCode: "कृपया पिनकोड भरा",
    enterPhoneNo: "कृपया दूरध्वनी नं. भरा",
    enterMobileNo: "कृपया मोबाईल नं. भरा",
    enterEmailAddress: "कृपया इलेक्ट्रॉनिक संदेश भरा",
    enteraadhaarNo: "कृपया आधार नं. भरा",
    enterpanNo: "कृपया पॅन नं. भरा",
    enterRemarks: "कृपया टिप्पणी. द्या",
    // ValidationszoneNameValidation
    citySurveyNoValdation: "शहर सर्वेक्षण क्रमांक आवश्यक आहे !!!",
    citySurveyNoValdationA: "शहर सर्वेक्षण क्रमांक आवश्यक आहे !!!",
    areaNameValidation: "क्षेत्राचे नाव निवडणे आवश्यक आहे !!!",
    hawkingZoneNameValidation: "पथविक्रेता झोनचे नाव निवडणे आवश्यक आहे !!!",
    zoneNameValidation: "झोनचे नाव निवडणे आवश्यक आहे !!!",
    titleValidation: "शीर्षक निवड आवश्यक आहे !!!",
    firstNameValidation: "पहिले नाव (इंग्रजी मध्ये) आवश्यक आहे !!!",
    firstNameValidationMr: "पहिले नाव (मराठी मध्ये) आवश्यक आहे !!!",
    middleNameValidation: "वडीलांचे/पतीचे नाव (इंग्रजी मध्ये) आवश्यक आहे !!!",
    middleNameValidationMr: "वडीलांचे/पतीचे नाव (मराठी मध्ये) आवश्यक आहे !!!",
    lastNameValidation: "आडनाव (इंग्रजी मध्ये) आवश्यक आहे !!!",
    lastNameValidationMr: "आडनाव (मराठी मध्ये) आवश्यक आहे !!!",
    genderValidation: "लिंग निवड आवश्यक आहे !!!",
    religionValidation: "धर्म निवड आवश्यक आहे !!!",
    casteValidation: "जात निवड आवश्यक आहे !!!",
    casteOtherValidation: "इतर जात आवश्यक आहे !!!",
    castCategoryValidation: "जात श्रेणी निवड आवश्यक आहे !!!",
    casteCategoryOtherValidation: "इतर जात श्रेणी आवश्यक आहे !!!",
    subCasteValidation: "पोटजात निवड आवश्यक आहे !!!",
    dateOfBirthValidation: "जन्मतारीख आवश्यक आहे !!!",
    ageValidation: "वय आवश्यक आहे !!!",
    mobileNovalidation: "मोबाईल नंबर आवश्यक आहे !!!",
    rationCardNoValidation: "शिधापत्रिका क्रमांक आवश्यक आहे !!!",
    applicantTypeValidation: "अर्जदाराचे प्रकार निवड आवश्यक आहे !!!",
    applicantTypeOtherValidation: "अर्जदाराचे प्रकार आवश्यक आहे !!!",
    emailIdValidation: "ई-मेल आयडी आवश्यक आहे !!!",
    emailIdValidationA: "कृपया वैध ई-मेल पत्ता प्रविष्ट करा !!!",
    landmarkNameValidation: "जवळची खूण नाव निवडणे  आवश्यक आहे ",
    villageNameValidation: "गावाचे नाव निवडणे आवश्यक आहे !!! ",
    roadNameValidation: "रस्त्याचे नाव निवडणे आवश्यक आहे !!!",
    cityNameValidation: "शहराचे नाव आवश्यक आहे !!!",
    stateNameValidation: "राज्याचे नाव आवश्यक आहे !!!",
    pinCodeValidation: "पिन कोड निवडणे आवश्यक आहे !!!",
    lattitudeValidation: "अक्षांश आवश्यक आहे !!!",
    logitudeValidation: "रेखांश आवश्यक आहे !!!",
    aadharNumberValidation: "आधार क्रमांक आवश्यक आहे !!!",
    propertyTaxNumberValidation: "मालमत्ता कर क्रमांक आवश्यक आहे !!!",
    waterConsumerNoValidation: "पाणी ग्राहक क्रमांक आवश्यक आहे !!!",
    proprtyTaxAmountNumberValidation: "मालमत्तेची रक्कम आवश्यक आहे !!!",
    waterTaxAmountValidation: "पाणी कराची रक्कम आवश्यक आहे !!!",
    streetvendorModeNameValidation:
      " पथविक्रीच्या व्यवसायाचे स्वरूप निवड आवश्यक आहे !!!",
    wardNameValidation: " प्रभाग नावाची निवड आवश्यक आहे  !!!",
    natureOfBusinessValidation: "व्यवसायाचे स्वरूप आवश्यक आहे !!!",
    hawkingDurationDailyValidation:
      "पथविक्रीचा दैनिक कालावधी निवड आवश्यक आहे !!!",
    hawkerTypeValidationT: "पथविक्रीचा प्रकार निवड आवश्यक आहे !!!",
    hawkerTypeValidationTT: "पथविक्रीचा प्रकार निवड आवश्यक आहे !!!",
    itemValidation: "वस्तु निवड आवश्यक आहे !!!",
    educationValidation: "शिक्षण निवड आवश्यक आहे !!!",
    areaOfStreetvendorValidation: "पथविक्री क्षेत्रनाव आवश्यक आहे !!!",
    periodOfResidenceInPCMCValidation:
      "पीसीएमसीमध्ये राहण्याचा कालावधी आवश्यक आहे !!!",
    periodOfResidenceInMaharashtraValidation:
      "महाराष्ट्रात राहण्याचा कालावधी आवश्यक आहे !!!",
    voterNameYNValidation: "निवड आवश्यक आहे",
    oldLicenseYNValidation: "निवड आवश्यक आहे",
    voterIdValidation: "मतदार ओळखपत्र क्रमांक आवश्यक आहे !!!",
    bankMasterValidation: "बँकेचे नाव निवडणे आवश्यक आहे !!!",
    branchNameValidation: "शाखेचे नाव आवश्यक आहे !!!",
    bankAccountNoValidation: "बँक खाते क्रमांक आवश्यक आहे !!!",
    ifscCodeValidation: "IFSC कोड आवश्यक आहे !!!",
    aadhaarCardPhotoValidation: "आधार कार्ड आवश्यक आहे !!!",
    panCardPhotoValidation: "पॅन कार्ड आवश्यक आहे !!!",
    rationCardPhotoValidation: "शिधापत्रिका आवश्यक आहे !!!",
    disablityCertificatePhotoValidation: "दिव्यांग प्रमाणपत्र आवश्यक आहे !!!",
    affidaviteOnRS100StampAttacheValidation:
      "रु. १००/- चे स्टॅम्प पेपरवर प्रतिज्ञा पत्र आवश्यक आहे !!!",
    otherDocumentPhotoValidation: "इतर दस्तऐवज आवश्यक आहे !!!",
    oldLicenseNoValidation: "जुना परवाना क्रमांक आवश्यक आहे !!!",
    oldLicenseDateValidation: "जुनी परवाना तारीख आवश्यक आहे !!!",
    documentUpload1: "दस्तऐवज अपलोड",
    documentUploadSuccessfully: "दस्तऐवज यशस्वीरित्या अपलोड केले !!!",
    areYouWantDelete: "तुम्हाला खात्री आहे की तुम्हाला फाइल हटवायची आहे ?",
    fileDeletedSuccessfully: "फाइल यशस्वीरित्या हटवली !!!",
    fileIsSafe: "फाइल सुरक्षित आहे",
    somethingWentWrong: "काहीतरी चूक झाली ..!!!",
    siteVisitPhoto1: "साइट भेट फोटो 1",
    siteVisitPhoto2: "साइट भेट फोटो 2",
    siteVisitPhoto3: "साइट भेट फोटो 3",
    siteVisitPhoto4: "साइट भेट फोटो 4",
    siteVisitPhoto5: "साइट भेट फोटो 5",
    oldLicenseYN: "जुना परवाना उपलब्ध आहे का ?",
    disablityNameYN: "दिव्यांग आहात का ?",
    applicationStatus: "अर्जाची स्थिती",
    viewForm: "फॉर्म पहा",
    print: "छापणे",
    licenseDuration: "परवाना कालावधी",
    applicationName: "मॉड्यूलचे नाव",
    paymentReceipt: "पैसे भरल्याची पावती",
    generateCertitifcate: "प्रमाणपत्र व्युत्पन्न करा",
    generateIDCard: "ओळखपत्र तयार करा",
    viewIDCard: "ओळखपत्र पहा",
    viewDocument: "कागदपत्र पहा",
    siteVisitFormPreview: "साइट भेट फॉर्म पूर्वावलोकन",
    DocumentName: "दस्तऐवजाचे नाव",
    mandatory: "अनिवार्य",
    nonMandatory: "अनिवार्य नाही",
    enterRemarkForApplication: "अर्जासाठी टिप्पणी प्रविष्ट करा",
    approve: "मंजूर",
    reassign: "पुन्हा नियुक्त करा",
    siteVisitAppointmentSchedule: "साइट भेट भेटीचे वेळापत्रक",
    addSlotsOfSiteVisit: "साइट भेटींचे स्लॉट",
    addMore: "आणखी जोडा",
    delete: "हटवा",
    bookNow: "बुक करा",
    fromDateValidation: "तारीख पासून निवड आवश्यक आहे",
    toDateValidation: "आजपर्यंतची निवड आवश्यक आहे",
    hawkerTypePrefixValidation:
      "पथविक्रेता प्रकार उपसर्ग (इंग्रजीमध्ये) आवश्यक आहे",
    hawkerTypePrefixMrValidation:
      "पथविक्रेता प्रकार उपसर्ग (मराठीमध्ये) आवश्यक आहे",
    hawkerTypeValidation: "पथविक्रेता प्रकार आवश्यक आहे !!!",
    hawkerTypeMrValidation: "पथविक्रेता प्रकार मराठीमध्ये आवश्यक आहे",
    hawkerTypeEnValidation: "पथविक्रेता प्रकार इंग्रजीमध्ये आवश्यक आहे",
    itemPrefixValidation: "वस्तू मास्टर उपसर्ग आवश्यक आहे (इंग्रजीमध्ये) !!! ",
    itemPrefixMrValidation: "वस्तू मास्टर उपसर्ग आवश्यक आहे (मराठीमध्ये) !!! ",
    itemCategoryValidation: "वस्तू श्रेणी निवड आवश्यक आहे !!!",
    itemCategoryValidationEn: "वस्तू श्रेणी (इंग्रजीमध्ये) !!! !!!",
    itemCategoryValidationMr: "वस्तू श्रेणी  (मराठीमध्ये) !!!",
    itemValidationEn: "वस्तू आवश्यक आहे  (इंग्रजीमध्ये) !!! ",
    itemValidationMr: "वस्तू आवश्यक आहे  (मराठीमध्ये) !!! ",
    itemPrefixEn: "वस्तू उपसर्ग (इंग्रजीमध्ये)",
    itemPrefixMr: "वस्तू उपसर्ग (मराठीमध्ये)",
    itemEn: "वस्तू (इंग्रजीमध्ये)",
    itemMr: "वस्तू (मराठीमध्ये)",
    licenseValidityPrefixValidation:
      "परवाना वैधता उपसर्ग आवश्यक आहे (इंग्रजीमध्ये) !!! ",
    licenseValidityPrefixMrValidation:
      "परवाना वैधता उपसर्ग आवश्यक आहे (मराठीमध्ये) !!! ",
    licenseValidityValidation: "परवाना वैधता आवश्यक आहे !!! ",
    zoneMaster: "झोन मास्टर",
    wardMaster: "वॉर्ड मास्टर",
    areaMaster: "क्षेत्र मास्टर",
    zoneName: "झोनचे नाव",
    zoneNameEn: "झोनचे नाव (इंग्रजीमध्ये)",
    wardNameEn: "वॉर्डचे नाव (इंग्रजीमध्ये)",
    zoneNameMr: "झोनचे नाव (मराठीत)",
    wardNameMr: "वॉर्डचे नाव (मराठीत)",
    areaNameEn: "क्षेत्राचे नाव (इंग्रजीत)",
    areaNameMr: "क्षेत्राचे नाव (मराठीत) ",
    areaZoneWardRoadLandMarkMappingMaster:
      "क्षेत्र झोन वॉर्ड रोड जवळची खून मॅपिंग मास्टर",
    zoneWardArea: "झोन प्रभाग क्षेत्र",
    licenseValidityMrValidation: "परवाना वैधता आवश्यक आहे (मराठीमध्ये) !!! ",
    licenseValidityEn: "परवाना वैधता (वर्षे) (इंग्रजीमध्ये)",
    licenseValidityMr: "परवाना वैधता (वर्षे) (मराठीमध्ये)",
    licenseValidityPrefixEn: "परवाना वैधता उपसर्ग (इंग्रजीमध्ये)",
    licenseValidityPrefixMr: "परवाना वैधता उपसर्ग (मराठीमध्ये)",
    hawkingZonePrefixValidation:
      "पथविक्रेता क्षेत्र उपसर्ग आवश्यक आहे (इंग्रजीमध्ये) !!!",
    hawkingZonePrefixMrValidation:
      "पथविक्रेता क्षेत्र उपसर्ग आवश्यक आहे (मराठीमध्ये) !!!",
    gisIdValidation: "जीआयएस आयडी आवश्यक आहे !!!",
    hawkingNameValidation: "पथविक्रेता झोनचे नाव आवश्यक आहे (इंग्रजीमध्ये) !!!",
    hawkingNameMrValidation: "पथविक्रेता झोनचे नाव आवश्यक आहे (मराठीमध्ये) !!!",
    declarationDateValidation: "घोषणा तारीख आवश्यक आहे !!!",
    declarationOrderNoValidation: "घोषणा ऑर्डर क्रमांक आवश्यक आहे !!",
    capacityOfHawkingZoneValidation: "पथविक्रेता झोनची क्षमता आवश्यक आहे !!!",
    noOfHawkersPresentValidation:
      "उपस्थित पथविक्रेत्याची संख्या आवश्यक आहे !!!",
    hawkingZoneInfoValidation:
      "पथविक्रेता क्षेत्र माहिती आवश्यक आहे (इंग्रजीमध्ये) !!!",
    hawkingZoneInfoMrValidation:
      "पथविक्रेता क्षेत्र माहिती आवश्यक आहे (मराठीमध्ये) !!!",
    hawkingZoneInfo: "पथविक्रेता क्षेत्र माहिती",
    hawkingZoneInfoMr: "पथविक्रेता क्षेत्र माहिती (मराठीमध्ये)",
    capacityOfHawkingZone: "पथविक्रेता झोनच्या संख्येची क्षमता",
    numberOfHawkersPresent: "सध्या पथविक्रेत्याची संख्या",
    declarationOrderNumber: "घोषणा ऑर्डर क्रमांक",
    constraint: "मर्यादा",
    hawkingZoneNameMr: "पथविक्रेता झोनचे नाव (मराठीमध्ये) ",
    hawkingZoneNameEn: "पथविक्रेता झोनचे नाव (इंग्रजीमध्ये) ",
    noHawkingZoneNameMr: "न पथविक्रेता झोनचे नाव (मराठीमध्ये) ",
    noHawkingZoneNameEn: "न पथविक्रेता झोनचे नाव (इंग्रजीमध्ये) ",
    hawkerMode: "पथविक्रेता मोड",
    hawkerModePrefixEn: "पथविक्रेता मोड उपसर्ग (इंग्रजीमध्ये)",
    hawkerModePrefixMr: "पथविक्रेता मोड उपसर्ग (मराठीमध्ये)",
    hawkerModeEn: "पथविक्रेता मोड (इंग्रजीमध्ये)",
    hawkerModeMr: "पथविक्रेता मोड (मराठीमध्ये)",
    hawkerModePrefixValidation:
      "पथविक्रेता मोड उपसर्ग आवश्यक आहे (इंग्रजीमध्ये) !!! ",
    hawkerModePrefixMrValidation:
      "पथविक्रेता मोड उपसर्ग आवश्यक आहे (मराठीमध्ये) !!! ",
    hawkerModeValidation: "पथविक्रेता मोड आवश्यक आहे (इंग्रजीमध्ये) !!! ",
    hawkerModeMrValidation: "पथविक्रेता मोड आवश्यक आहे (मराठीमध्ये) !!! ",
    noHawkingZoneMr: "न पथविक्रेता झोनचे नाव (मराठीमध्ये)",
    noHawkingZoneEn: "न पथविक्रेता झोनचे नाव (इंग्रजीमध्ये)",
    noHawkingZoneInfo: "न पथविक्रेता झोनचे माहिती",
    declarationOrderValidation: "घोषणा आदेश आवश्यक आहे  !!! ",
    noHawkingZoneEnValidation:
      "न पथविक्रेता झोनचे नाव (इंग्रजीमध्ये) आवश्यक आहे !!!",
    noHawkingZoneMrValidation:
      "न पथविक्रेता झोनचे नाव (मराठीमध्ये) आवश्यक आहे !!!",
    noHawkingZoneInfoValidation: "न पथविक्रेता क्षेत्र माहिती आवश्यक आहे !!!",
    applicantPrefixMr: "अर्जदार उपसर्ग (मराठीमध्ये)",
    applicantPrefixEn: "अर्जदार उपसर्ग (इंग्रजीमध्ये)",
    applicantTypeMr: "अर्जदाराचा प्रकार (मराठीमध्ये)",
    applicantTypeEn: "अर्जदाराचा प्रकार (इंग्रजीमध्ये)",
    applicantSubTypeMr: "अर्जदार उपप्रकार (मराठीमध्ये)",
    applicantSubTypeEn: "अर्जदार उपप्रकार (इंग्रजीमध्ये)",
    subtypeValidation: "अर्जदार उपप्रकार आवश्यक आहे !!!",
    typeValidation: "अर्जदाराचा प्रकार आवश्यक आहे !!!",
    applicantPrefixValidation: " अर्जदार उपसर्ग आवश्यक आहे !!!",
    hawkingZoneWiseFacilitiesPrefixEn:
      "पथविक्रेता झोननिहाय सुविधा उपसर्ग (इंग्रजीमध्ये)",
    hawkingZoneWiseFacilitiesPrefixMr:
      "पथविक्रेता झोननिहाय सुविधा उपसर्ग (मराठीमध्ये)",
    facilitynameEn: "सुविधेचे नाव (इंग्रजीमध्ये)",
    facilitynameMr: "सुविधेचे नाव (मराठीमध्ये)",
    hawkingZoneWiseFacilitiesPrefixValidation:
      "पथविक्रेता क्षेत्र उपसर्ग आवश्यक आहे !!!",
    hawkingZoneWiseFacilitiesPrefixMrValidation:
      "पथविक्रेता क्षेत्र उपसर्ग आवश्यक आहे !!!",
    hawkigZoneValidation: "पथविक्रेता क्षेत्र निवड आवश्यक !!!",
    facilitiesValidation: "सुविधेचे नाव आवश्यक आहे !!!",
    facilitiesMrValidation: "सुविधेचे नाव आवश्यक आहे !!!",
    hawkingDurationDailyFrom: "पथविक्रेता कालावधी दररोज पासून",
    hawkingDurationDailyTo: "पथविक्रेता कालावधी दैनिक ते",
    hawkingDurationDailyPrefixEn: "पथविक्रेता कालावधी उपसर्ग (इंग्रजीमध्ये)",
    hawkingDurationDailyPrefixMr: "पथविक्रेता कालावधी उपसर्ग (मराठीमध्ये)",
    businessType: "व्यवसाय प्रकार",
    hawkingDurationDailyPrefixValidation:
      "पथविक्रेता कालावधी दैनिक उपसर्ग आवश्यक आहे !!!",
    hawkingDurationDailyFromValidation:
      "पासून दररोज पथविक्रेता कालावधी आवश्यक आहे !!!",
    hawkingDurationDailyToValidation:
      "पथविक्रेता पथविक्रेता कालावधी आवश्यक आहे !!!",
    hawkerName: "रस्त्यावरील विक्रेत्याचे नाव",
    businessTypeValidation: "व्यवसाय प्रकार निवड आवश्यक आहे !!!",
    businessSubTypeValidation: "व्यवसाय उपप्रकार निवड आवश्यक आहे !!!",
    businessSubTypePrefixEn: "व्यवसाय उपप्रकार उपसर्ग (इंग्रजीमध्ये)",
    businessSubTypePrefixMr: "व्यवसाय उपप्रकार उपसर्ग (मराठीमध्ये)",
    businessSubTypeEn: "व्यवसाय उपप्रकार (इंग्रजीमध्ये) ",
    businessSubTypeMr: "व्यवसाय उपप्रकार (मराठीमध्ये)",
    businessSubTypePrefixEnValidation: "व्यवसाय उपप्रकार उपसर्ग आवश्यक आहे !!!",
    businessSubTypePrefixMrValidation: "व्यवसाय उपप्रकार उपसर्ग आवश्यक आहे !!!",
    businessSubTypeEnValidation: "व्यवसाय उपप्रकार नाव आवश्यक आहे !!!",
    businessSubTypeMrValidation: "व्यवसाय उपप्रकार नाव आवश्यक आहे !!!",
    years: "वर्षे",
    months: "महिने",
    businessTypePrefixEn: "व्यवसाय उपसर्ग (इंग्रजीमध्ये)",
    businessTypePrefixMr: "व्यवसाय उपसर्ग (मराठीमध्ये)",
    businessTypeEn: "व्यवसाय (इंग्रजीमध्ये) ",
    businessTypeMr: "व्यवसाय (मराठीमध्ये)",
    businessTypePrefixEnValidation: "व्यवसाय उपसर्ग आवश्यक आहे !!!",
    businessTypePrefixMrValidation: "व्यवसाय उपसर्ग आवश्यक आहे !!!",
    businessTypeEnValidation: "व्यवसाय नाव आवश्यक आहे !!!",
    businessTypeMrValidation: "व्यवसाय नाव आवश्यक आहे !!!",
    renewalOfIssuanceOfHawkerLicense: "पथविक्रेता परवाना नूतनीकरण",
    cancellationOfIssuanceOfHawkerLicense: "पथविक्रेता परवाना रद्द करणे",
    issuanceOfHawkerLicenseNumber: "पथविक्रेता परवाना क्रमांक",
    issuanceOfHawkerLicenseNumber1: "१) पथविक्रेता परवाना क्रमांक",
    siteVisitDate: "साइट भेट तारीख",
    siteVisitTime: "साइट भेट वेळ",
    streetVendorFullName: "पथविक्रेत्याचे पूर्ण नाव",
    streetVendorFullNameAndDateOfBirth:
      " २) पथविक्रेत्याचे पूर्ण नाव आणि जन्मतारीख",
    serviceNameValidation: "सेवा नाव निवड आवश्यक आहे !!!",
    hawkingSummaryReport: "पथविक्रेता सारांश अहवाल",
    hawkerPhoto: "पथविक्रेत्याचा फोटो ",
    hawkerPhotoValidation: "पथविक्रेत्याचा फोटो आवश्यक आहे !!!",
    chequeorPassbookPhoto:
      "क्रॉस चेकची छायाप्रत किंवा. पासबुकचे पहिले पान छायाप्रत",
    chequeorPassbookPhotoValidation:
      "क्रॉस चेकची छायाप्रत किंवा. पासबुकचे पहिले पान छायाप्रत आवश्यक आहे !!!",
    shopBusinessOldLicensePhoto:
      "उपलब्ध असल्यास PCMC कडून शॉप ऍक्ट लायसन्स / व्यवसाय परवाना",
    shopBusinessOldLicensePhotoValidation:
      "उपलब्ध असल्यास PCMC कडून शॉप ऍक्ट लायसन्स / व्यवसाय परवाना आवश्यक आहे !!!",
    //pg labels
    yourPaymentDoneSuccess: " तुमचे पेमेंट यशस्वी झाले!!!",
    paymentFailed: "पेमेंट अयशस्वी !!!",
    orderId: "ऑर्डर आयडी ",
    trackingId: "ट्रॅकिंग आयडी",
    bankRefNo: "बँक संदर्भ क्र",
    billingName: "बिलिंग नाव",
    billingAdd: "बिलाचा पत्ता",
    billingCity: "बिलिंग शहर",
    billingZip: "बिलिंग पिन कोड ",
    billingCountry: "बिलिंग देश",
    billingEmail: "बिलिंग ईमेल",
    mobileNo: "मोबाईल क्र",
    transactionDate: "व्यवहाराची तारीख",
    billingState: "बिलिंग राज्य",
    goToList: "सूचीवर जा",
    loiNo: "हेतू पत्र क्र",
    totalAmount: "एकूण रक्कम",
    applicationNameValidation: "मॉड्यूल नाव निवड आवश्यक आहे !!!",
    count: "गणना",
    totalApplication: "एकूण अर्ज",
    editApplication: "अर्ज संपादित करा",
    verificationDept: "dept verification",
    verificationAo: "verification AO",
    verificationWo: "verification WO",
    siteVisitReschedule: "Site Visit Reschdule",
    cancelCertificate: "प्रमाणपत्र रद्द करा",
    viewCancellationLetter: "रद्द करण्याचे पत्र पहा",
    languageValidation: "फक्त इंग्लिश शब्द",
    zoneWardAreaMapping: "झोन वॉर्ड क्षेत्र आवश्यक!!!",
    landMarkValidation: "जवळची खून  आवश्यक आहे !!!",
    raodNameValidation: "रस्त्याचे नाव आवश्यक आहे !!!",
    disablityPrecntage: "अपंगत्व टक्केवारी",
    avalibleSlots: "उपलब्ध स्लॉट",
    toTime: "पर्यंत",
    fromTime: "पासून",
    disablityNameYNValidation: "अपंगत्व होय/नाही निवड आवश्यक आहे !!!",
    disablityPrecntageValidation: "अपंगत्व टक्केवारी आवश्यक आहे !!!",
    typeOfDisabilityValidation: "अपंगत्वाची निवड आवश्यक आहे !!!",
    submit: "प्रस्तुत करणे",
    oldStreetVendorDetails: "जुन्या पथविक्रेत्याचा विक्रेता तपशील",
  },
};
