export default {
  en: {
    type: "commonLabels",

    module: "Library Management System",
    // dashboard: 'PCMC Dashboard',
    dashboard: "Pimpri-Chinchwad Municipal Corporation Dashboard",
    master: "Masters",
    transaction: "Transactions",
    report: "Reports",
    masterPath: "Legal Case / Master ",
    transactionPath: "Legal Case / Transaction ",
    reportPath: "Legal Case / Report ",

    type: "master",
    master: "Masters",
    masterPath: "Legal Case/ Master",

    //breadcrum
    courtPath: "Legal Case / Master /Court",
    advocatePath: "Legal Case / Master /Advocate",
    serviceHierachyPath: "Legal Case / Master / Service Hierachy",
    caseTypePath: "Legal Case/ Master / Case Type",
    caseSubTypePath: "Legal Case / Master / Case Sub Type",
    caseStagesPath: "Legal Case/ Master / Case Stages",
    employeeAndUserCreationPath:
      "Legal Case / Master / Empnameloyee and User Creation",
    counterSchedulingPath: "Legal Case / Master / Counter Scheduling",
    smsEmailWhatsAppTemplatesPath:
      "Legal Case / Master / SMS / Email/WhatsApp Templates",
    userAuthenticationAndRoleRightsPath:
      "Legal Case / Master / User Authentication and Role-Rights",
    changeResetForgetPasswordPath:
      "Legal Case / Master / Change or Reset or ForgetPassword",
    calendarSchedulingPath: "Legal Case / Master / Calendar Scheduling",

    //label title
    court: "Court",
    advocate: "Advocate",
    serviceHierachy: "Service Hierarchy",
    caseType: "Case Type",
    caseSubType: "Case Sub-Type",
    caseStages: "Case-Stage",
    employeeAndUserCreation: "Employee and User Creation",
    counterScheduling: " Counter Scheduling",
    smsEmailWhatsAppTemplates: " SMS / E-mail / Whatsapp Template",
    userAuthenticationAndRoleRights: " User Authentication and Role Rights",
    changeResetForgetPassword: "Change / Reset / Forget Password",
    calendarScheduling: " Calender Scheduling",
    departmentCategory: "Department Category",
    meterStatus: "Meter Status",
    msedclCategory: "MSEDCL Category",
    billingUnitAndDivision: "Billing Division And Unit",
    subDivision: "Sub Division",
    billingCycle: "Billing Cycle",
    consumptionType: "Consumption Type",
    loadType: "Load Type",
    ebUsageType: "Usage Type",
    phaseType: "Phase Type",
    slabType: "Slab Type",
    division: "Division",
    tarriffCategory: "Tarriff Category",
    ApplicatDetails: "Applicant Details",
    zone: "Zone",
    libraryTypes: "Library Types",
    educationD: "Education",
    ward: "Ward",

    //other labels

    addressEn: "Address (In English)",
    addressMr: "Address (In Marathi)",

    address: "Address",

    flatBuildingNo: "Flat/Building No (In English)",
    flatBuildingNoMr: "Flat/Building No (In Marathi)",
    buildingName: "Apartment Name (In English)",
    buildingNameMr: "Apartment Name (In Marathi)",

    roadNameEn: "Road Name (In English)",
    roadNameMr: "Road Name (In Marathi)",

    roadName: "Road Name ",

    landmarkEn: "Landmark (In English)",
    landmarkMr: "Landmark (In Marathi)",

    landmark: "Landmark",

    cityOrVillageEn: "City / Village (In English)",
    cityOrVillageMr: "City / Village (In Marathi)",

    cityOrVillage: "City / Village",

    state: "State (In English)",
    stateMr: "State (In Marathi)",

    pincode: "Pincode",
    // pincodeMr: "Pincode (In Marathi)",

    areaEn: "Area (In English)",
    areaMr: "Area (In Marathi)",

    area: "Area",

    name: "Name",
    // nameMr: "Name (In Marathi)",

    mobile: "Mobile No.",
    // mobileMr: "Mobile No. (In Marathi)",

    phone: "Phone No.",
    // phoneMr: "Phone No. (In Marathi)",

    email: "E-mail",
    // emailMr: "E-mail (In Marathi)",

    aadharNoEn: "Aadhar No.",
    aadharNoMr: "Aadhar No.(In Marathi)",

    panNo: "Pan No.",
    // panNoMr: "Pan No.(In Marathi)",

    advocateCreationEn: "Advocate Created Successfully (In English)",
    advocateCreationMr: "Advocate Created Successfully (In Marathi)",

    advocateDetails: "Advocate Details",

    concernAdvocate: "Concern Advocate",

    // advocateDetailsMr: "Advocate Details (In Marathi)",

    bankDetails: "Bank Details",
    // bankDetailsMr: "Bank Details (In Marathi)",

    billDetails: "Bill Details",

    paymentDetails: "Payment Details",

    paymentrate: "Payment Rate",

    payment: "Payment",
    caseFees: "Case Fees",

    fixedAmount: "Fixed Amount",

    paidAmount: "Paid Amount",
    paidFees: "Paid Fees",

    feesAmount: "Fees Amount",

    paidAmountDate: "Paid Amount Date",

    pendingAmount: "Pending Amount",
    pendingFees: "Pending Fees",

    approvalFeesAmount: "Approval Fees Amount",
    billAmount: "Bill Amount",

    documentUpload: "Document Upload",
    // documentUploadMr: "Document Upload (In Marathi)",

    titleEn: "Title (In English)",
    titleMr: "Title (In Marathi)",

    fnameEn: "First Name (In English)",
    fnameMr: "First Name (In Marathi)",

    mnameEn: "Middle Name (In English)",
    mnameMr: "Middle Name (In Marathi)",

    lnameEn: "Last Name (In English)",
    lnameMr: "Last Name (In Marathi)",

    advocateCategory: "Advocate Category",
    // advocateCategoryMr: "Advocate Category (In Marathi)",

    nameOfBarCouncil: "Name Of Bar Council",

    remarksEn: "Remarks (In English)",
    remarksMr: "Remarks (In Marathi)",

    bankName: "Bank Name*",
    // bankNameMr: "Bank Name (In Marathi)*",

    branchNameEn: "Branch Name (In English)*",
    branchNameMr: "Branch Name (In Marathi)*",

    branchName: "Branch Name",

    accountNo: "Account No.",
    // accountNoMr: "Account No. (In Marathi)*",

    bankIFSC: "Bank IFSC code",
    // bankIFSCMr: "Bank IFSC code (In Marathi)*",

    bankMICR: "Bank MICR code",
    // bankMICRMr: "Bank MICR code (In Marathi)*",

    applicationEn: "Application:(In English)",
    applicationMr: "Application:(In Marathi)",

    aadharNo: "Aadhar No:",

    panCard: "Pan Card:",

    caseStagesEn: "Case-Stage (In English)",
    caseStagesMr: "Case-Stage (In Marathi)",

    caseStatus: "Case Status",

    //Remarks
    selectDate: "Please select a date",
    // selectDateMr: "Please select a date (In Marathi)",

    selectTitle: "Please select a title",
    // selectTitleMr: "Please select a title (In Marathi)",

    attachFile: "Attach File",
    // attachFileMr: "Attach File (In Marathi)",

    srNo: "Sr.No",
    // srNoMr: "Sr. No (In Marathi)",

    actions: "Actions",
    // actionsMr: "Actions (In Marathi)",

    entersNumbers: "Please Enters Numbers Only",
    // entersNumbersMr: "Please Enters Numbers Only (In Marathi)",

    //buttons
    add: "Add",
    save: "Save",
    update: "Update",
    clear: "Clear",
    exit: "Exit",
    back: "Back",
    saveAndNext: "Save & Next",
    finish: "Finish",
    addPoint: "Add",
    // Transaction
    type: "transaction",

    transaction: "Transactions",

    srNo: "Sr. No",
    actions: "Actions",

    addHearing: "Add Hearing",

    add: "Add",
    save: "Save",
    update: "Update",
    clear: "Clear",
    exit: "Exit",
    back: "Back",
    finish: "Finish",
    approve: "APPROVE",
    reassign: "REASSIGN",

    fromDate: "From Date",
    toDate: "To Date",

    deptName: "Department Name",
    delete: "Delete",
    next: "Next",
    exit: "Exit",
    back: "Back",

    submit: "Submit",

    cancel: "Cancel",

    saveAsDraft: "Save AS Draft",

    libraryCSC: "Library/Competitive Study Centre",
    applicantName: "Applicant Name",
    membershipDetails: "Membership Details",
    startDate: "Membership Start Date",
    endDate: "Membership End Date",
    membershipMonths: "Membership for Months",
    identityProof: "Identity Proof",
    addressProof: "Address Proof",
    preview: "Preview",

    newBookRequest: "New Book Request",
    bookName: "Book Name",
    publication: "Publication",
    language: "Language",
    bookClassification: "Book Classification",
    bookType: "Book Type",
    bookSubType: "Book Sub Type",
    author: "Author",
    bookEdition: "Book Edition",
    closeMembership: "Close Membership",
    membershipNo: "Membership No",
    searchMember: "Search Member",
    memberName: "Member Name",
    dues: "Pending Dues",
    reason: "Reason",
    renewMembership: "Renew Membership",
    renewDetails: "Renew Details",
    startDateM: "Renewed Start Date",
    membershipMonthsM: "Renew Membership for Months",
    refundDeposit: "Refund Deposit",
    bankEcsDetails: "Bank(ECS Form) Details",
    bankHolderName: "Bank Account Holder Name",
    bankAccountNumber: "Bank Account Number",
    typeOfBankAccount: "Type Of Bank Account",
    bankAddress: "Bank Address",
    booksMaster: "Books Master",
    bookPrice: "Book Price",
    totalBooksCopy: "Total Books Copy",
    barcode: "QR Code",
    id: "id",
    bookTypeMaster: "Book Type Master",
    bookSubTypeMaster: "Book Sub Type Master",
    magazinesNewspaperName: "Magazines/Newspaper Name",
    magazinesNewspaperSubCategory: "Magazines/Newspaper Sub Category Name",
    supplierName: "Supplier Name",
    contactNumber: "Contact Number",
    remark: "Remark",
    magazineNewspaperMaster: "Magazine Newspaper Master",
    applicationDate: "Application Date",
    photoAttachment: "Passport Size Photo",
    taxReceipt: "Tax Receipt",
    libraryCSCMaster: "Library/Competitive Study Centre Master",
    libraryType: "Library Type",
    libraryNameMr: "Library Name/Competitive Study Centre(Mr)",
    libraryName: "Library Name/Competitive Study Centre(En)",
    rateChartMaster: "Rate Chart Master",
    chargeNameEng: "Charge Name (In English)",
    chargeNameMr: "Charge Name (In Marathi)",
    chargePrefixEng: "Charge Prefix(In English)",
    chargePrefixMr: "Charge Prefix(In Marathi)",
    chargeType: "Charge Type",
    amount: "Amount",
    service: "Service",
    print: "print",
    shelfCatlogMaster: "Shelf Catlog Master",
    lib: "Library Name",
    shelfNo: "Shelf No",
    shelfCatlogSection: "Shelf Catlog Section",
    applicationNo: "Application No",
    serviceName: "Service Name",
    applicationStatus: "Application Status",
    bookIssueReturnTitle: "Book Issue/Return",
    bookIssueReturnHistory: "Book Issue and Return History",
    issue: "Issue",
    Issue: "Issue",
    form: "Form",
    Return: "Return",
    bookLost: "Book Lost",
    Lost: "Lost",
    chooseBook: "Choose a Book",
    dateOf: "Date Of",
    bookDetails: "Book Details",
    totalAvailableBookCopy: "Available Books Copy",
    issuedAt: "Issued At",
    newMembershipRegistration: "New Membership Registration",
    issueLibCard: "Issue Library Card",
    chargesDetails: "Charges Details",
    serviceChargeTypeName: "Service Charge Type Name",
    totalCharges: "Total Charges(Rs)",
    totalInWords: "Total in Words(Rs)",
    generateLoi: "Generate LOI",
    paymentCollection: "Payment Collection",
    paymentType: "Payment Type",
    paymentMode: "Payment Mode",
    bankAccountNo: "Bank Account No",
    ddNo: "DD No",
    ddDate: "DD Date",
    upiId: "UPI ID",
    upiList: "UPI List",
    pay: "Pay",
    dailyEntryMagazineNewspaper: "Daily Entry Magazines Newspaper",
    quantity: "Quantity",
    publishedDate: "Published Date",
    receivedDate: "Received Date",
    refundDeposit: "Refund Deposit",
    librarianRemark: "Librarian Remark",
    sendToAccountDept: "Send To Account Dept",
    membershipCloseDate: "Membership Close Date",
    lastEndDate: "Last Membership End Date",
    chequeDate: "Cheque Date",
    chequeNo: "Cheque No",
    selectZone: "Please select a zone",
    selectLibrary: "Please select a library/Competetive study center",
    selectTitle: "Please select a title",

    enterFName: "Please enter first name (In English)",
    enterMName: "Please enter middle name (In English)",
    enterLName: "Please enter last name (In English)",

    enterFNameMr: "Please enter first name (In Marathi) ",
    enterMNameMr: "Please enter middle name (In Marathi)",
    enterLNameMr: "Please enter last name (In Marathi)",
    enterEmailAddress: "Please enter an e-mail. ",
    enterMobileNo: "Please enter a mobile no. ",
    enterFlat: "Please enter Flat/Building No (In English) ",
    enterApartment: "Please enter Apartment Name (In English)",
    enterRoadName: "Please enter Road Name (In English)",
    enterLandmark: "Please enter Landmark (In English)",
    enterCity: "Please enter a City Name / Village Name (In English) ",
    enterState: "Please enter State (In English)",
    enterFlatMr: "Please enter Flat/Building No (In Marathi)",
    enterApartmentMr: "Please enter Apartment Name (In Marathi)",
    enterRoadNameMr: "Please enter Road Name (In Marathi)",
    enterLandmarkMr: "Please enter Landmark (In Marathi)",
    enterCityMr: "Please enter a City Name / Village Name (In Marathi)",
    // stateMr: "Please enter State (In Marathi)",
    enterPinCode: "Please enter a pincode ",
    enteraadhaarNo: "Please enter an aadhaar no. ",
    selectMembershipMonths: "Please select membership Months",
    enterBankAccountHolderName: "Please Enter Bank Holder Name",
    enterBankAccountNo: "Please Enter Bank Account Number",
    selectBankAccount: "Please Select Type Of Bank Account",
    invalidBankAccountNo:
      "Bank account number must consist of 6 to 20 digits and only digits are allowed",
    selectBankName: "Please Select Bank Name",
    enterBankAddress: "Please Enter Bank Address",
    enterBankIFSC: "Please Enter Bank IFSC code",
    enterBankMICR: "Please Enter Bank MICR code",
    enterBookName: "Please Enter Book Name",
    enterPublication: " Please Enter Publication",
    selectLanguage: "Please select Language",
    selectBookClassification: "Please select Book Classification",
    selectBookType: "Please select Book Type",
    selectBookSubType: "Please select Book Sub Type",
    enterAuthor: "Please enter author",
    enterBookEdition: "Please enter Book Edition",
    bookSize: "Book Size(In Inch)",
    noOfPages: "No Of Pages",
    price: "Price",
    magazineNewspaperType: "Magazine/Newspaper Type",
    purchaseType: "Purchase Type",
    searchBook: "Search Book",
    search: "search",
    bookCaseNo: "Book Case No",
    accessionNo: "Accession no.",
    village: "Village",
    gisId: "GIS ID",
    libraryClassification: "Library Administrative Status",
    education: "Education(Graduation)",
    educationDoc: "Education(Graduation) Proof",
    educationEnter: "Please Enter the Education(Graduation)",
    witnessDetails: "Witness Details",
    referenceMobileNo: "Witness Mobile No",
    generateOtp: "Generate OTP",
    verifiedOtp: "OTP Verified",
    reopenMembership: "Re-open Membership",
    transferLibraryMembership: "Transfer Library Membership",
    transferMembershipDetails: "Transfer Membership Details",
    userKey: "User Key",
    bookConditionMaster: "Book Condition Master",
    bookConditionEn: "Book Condition(In English)",
    bookConditionMr: "Book Condition(In Marathi)",
    reOpen: "reOpen",
    renewMembershipDetails: "Renew/Reopen Membership",
    finePaid: "Fine Paid",
    fineNotPaid: "Fine Not Paid",
    fineAmount: "Fine Amount",
    note: "Note - Library Type must be 1) L(for library) 2) C(for Competitive center) 3) P(for Post Graduate Library)",
    classificationCode: "Classification Code",
    bookTypeCode: "Book Type Code",
    identityProofMessage: "Please Attach the Identity Proof..!!",
    addressProofMessage: "Please Attach the Address Proof..!!",
    passportProofMessage: "Please Attach the Passport Size Photo..!!",
    taxReceiptMessage: "Please Attach the Tax Receipt..!!",

    yourPaymentDoneSuccess: " Your payment done successful!!!",
    paymentFailed: "Payment failed!!!",
    orderId: "Order Id ",
    trackingId: "Tracking Id",
    bankRefNo: "Bank Reference No",
    billingName: "Billing Name",
    billingAdd: "Billing Address",
    billingCity: "Billing City",
    billingZip: "Billing Zipcode ",
    billingCountry: "Billing Country",
    billingEmail: "Billing Email",
    mobileNo: "Mobile No",
    billingState: "Billing State",
    transactionDate: "Transaction Date",
    goToList: "Go To List",
    totalAmount: "Total Amount",
    loiNo: "LOI No",

    uploadFile: "Upload File",
    backToHomeBtn: "Back To Home",
    printD: "Print",

    minMobileNo: "Mobile Number must be at least 10 number",
    maxMobileNo: "Mobile Number not valid on above 10 number",
    mustBeOnlyDigit: "Must be only digits",
    minAadharNo: "Adhar Number must be at least 12 number",
    maxAadharNo: "Adhar Number not valid on above 12 number",
    minPincode: "Pincode Number must be at least 6 number",
    maxPincode: "Pincode Number not valid on above 6 number",

    remarkModel: "Enter Remark on application",
  },

  mr: {
    type: "commonLabels",
    panelAdvocate: "पॅनेलचे वकील",
    panelOther: "इतर",
    branchName: "शाखेचे नाव",
    module: "ग्रंथालय व्यवस्थापन प्रणाली",
    // dashboard: 'डॅशबोर्ड',
    dashboard: "पिंपरी-चिंचवड महानगरपालिका डॅशबोर्ड",
    master: "मास्टर्स",
    transaction: "व्यवहार",
    report: "अहवाल",
    masterPath: "कायदेशीर प्रकरण/ मास्टर ",
    transactionPath: "कायदेशीर प्रकरण/ व्यवहार ",
    reportPath: "कायदेशीर प्रकरण/ अहवाल ",

    type: "master",

    master: "मास्टर्स",
    transaction: "व्यवहार",
    report: "अहवाल",
    masterPath: "कायदेशीर प्रकरण/ मास्टर ",
    transactionPath: "कायदेशीर प्रकरण/ व्यवहार ",
    reportPath: "कायदेशीर प्रकरण/ अहवाल ",

    ApplicatDetails: "अर्जदाराचे तपशील",
    zone: "झोन",
    libraryTypes: "लायब्ररीचे प्रकार",
    educationD: "शिक्षण",
    ward: "प्रभाग",

    addressEn: "पत्ता (इंग्रजी मध्ये)",
    addressMr: "पत्ता (मराठी मध्ये)",

    address: "पत्ता",
    flatBuildingNo: "फ्लॅट/इमारत क्रमांक (इंग्रजी मध्ये)",
    flatBuildingNoMr: "फ्लॅट/इमारत क्रमांक (मराठी मध्ये)",
    buildingName: "अपार्टमेंटचे नाव (इंग्रजी मध्ये)",
    buildingNameMr: "अपार्टमेंटचे नाव (मराठी मध्ये)",

    roadNameEn: "रस्त्याचे नाव (इंग्रजी मध्ये)",
    roadNameMr: "रस्त्याचे नाव (मराठी मध्ये)",

    roadName: "रस्त्याचे नाव ",

    landmarkEn: "महत्त्वाची खूण (इंग्रजी मध्ये)",
    landmarkMr: "महत्त्वाची खूण (मराठी मध्ये)",

    landmark: "महत्त्वाची खूण ",

    cityOrVillageEn: "शहर / गाव (इंग्रजी मध्ये)",
    cityOrVillageMr: "शहर / गाव (मराठी मध्ये)",

    cityOrVillage: "शहर / गाव",

    state: "राज्य (इंग्रजी मध्ये)",
    stateMr: "राज्य (मराठी मध्ये)",

    pincode: "पिनकोड",
    // pincodeMr: "पिनकोड (मराठी मध्ये)",

    areaEn: "क्षेत्राचे नाव (इंग्रजी मध्ये)",
    areaMr: "क्षेत्राचे नाव (मराठी मध्ये)",

    area: "क्षेत्राचे नाव",

    name: "नाव",
    // nameMr: "नाव (मराठी मध्ये)",

    mobile: "मोबाईल नं.",
    // mobileMr: "मोबाईल नं.(मराठी मध्ये)",

    phone: "दूरध्वनी नं.",
    // phoneMr: "दूरध्वनी नं.(मराठी मध्ये)",

    email: "ई-मेल",
    // emailMr: "इलेक्ट्रॉनिक संदेश (मराठी मध्ये)",

    aadharNo: "आधार नं.",

    panNo: "पॅन नं.",

    // pendingAmount:"प्रलंबित रक्कम",
    bankDetails: "बँक तपशील",
    // bankDetailsMr: "बँक तपशील (मराठी मध्ये)",

    billDetails: "बिल तपशील",

    documentUpload: "दस्तऐवज अपलोड",
    // documentUploadMr: "दस्तऐवज अपलोड(मराठी मध्ये)",

    titleEn: "शीर्षक (इंग्रजी मध्ये)",
    titleMr: "शीर्षक (मराठी मध्ये)",

    fnameEn: "पहिले नाव (इंग्रजी मध्ये)",
    fnameMr: "पहिले नाव (मराठी मध्ये)",

    mnameEn: "मधले  नाव (इंग्रजी मध्ये)",
    mnameMr: "मधले  नाव (मराठी मध्ये)",

    lnameEn: "आडनाव (इंग्रजी मध्ये)",
    lnameMr: "आडनाव (मराठी मध्ये)",

    remarksEn: "टिप्पणी (इंग्रजी मध्ये)*",

    bankName: "बँकेचे नाव",
    // bankNameMr: "बँकेचे नाव (मराठी मध्ये)*",

    branchNameEn: "शाखेचे नाव (इंग्रजी मध्ये) *",
    branchNameMr: "शाखेचे नाव (मराठी मध्ये) *",

    accountNo: "खाता क्रमांक",
    // accountNoMr: "खाता क्रमांक (मराठी मध्ये)*",

    bankIFSC: "बँक IFSC कोड ",
    // bankIFSCMr: "बँक IFSC कोड (मराठी मध्ये)*",

    bankMICR: "बँक एमआयसीआर कोड",
    // bankMICRMr: "बँक MICR कोड (मराठी मध्ये)*",

    applicationEn: "अर्ज:(इंग्रजी मध्ये)",
    applicationMr: "अर्ज:(मराठी मध्ये)",

    attachFileEn: "फाईल जोडा (इंग्रजी मध्ये)",
    attachFileMr: "फाईल जोडा (मराठी मध्ये)",

    srNo: "अनुक्रमांक",
    // srNoMr: "अनुक्रमांक (मराठी मध्ये)",

    actions: "क्रिया",
    // actionsMr: "क्रिया (मराठी मध्ये)",

    entersNumbersEn: "कृपया फक्त क्रमांक प्रविष्ट करा (इंग्रजी मध्ये)",
    entersNumbersMr: "कृपया फक्त क्रमांक प्रविष्ट करा (मराठी मध्ये)",

    //Remarks
    selectDate: "कृपया तारीख निवडा",
    selectTitle: "कृपया शीर्षक निवडा",
    enterFName: "कृपया पहिले नाव भरा ",
    enterMName: "कृपया मधले  नाव भरा ",
    enterLName: "कृपया शेवटचे नाव भरा ",
    selectAdvocateCategory: "कृपया वकील श्रेणी निवडा",
    enterCouncilName: "कृपया वकिलांचे मंडळचे प्रमाणपत्र परिषदचे नाव भरा",
    enterArea: "कृपया क्षेत्राचे नाव भरा ",
    enterRoadName: "कृपया रस्त्याचे नाव भरा ",
    enterLandmark: "कृपया  महत्त्वाची खूण भरा",
    enterCity: "कृपया  शहराचे / गावाचे नाव भरा ",
    enterPhoneNo: "कृपया दूरध्वनी नं. भरा",
    enterEmailAddress: "कृपया ई-मेल भरा",
    enteraadhaarNo: "कृपया आधार नं. भरा",
    enterpanNo: "कृपया पॅन नं. भरा",
    // enterRemarks: 'कृपया टिप्पणी. भरा',
    enterRemarks: "कृपया टिप्पणी. द्या",

    //buttons
    // add: "जोडा",
    add: "नवीन नोंदणी",
    save: "जतन करा",
    update: "अद्यायावत करा",
    clear: "रिक्त",
    exit: "बाहेर पडा",
    back: "मागे",
    saveAndNext: "जतन करा आणि पुढे",
    next: "पुढे",

    finish: "समाप्त",

    fromDate: "या तारखेपासून",
    toDate: "या तारखेपर्यंत",

    attachFile: "फाईल जोडा",
    srNo: "अनुक्रमांक",
    actions: "क्रिया ",

    //buttons
    add: "नवीन नोंदणी",
    save: "जतन करा",
    update: "अद्यायावत करा",
    clear: "रिक्त",
    exit: "बाहेर पडा",
    back: "मागे",
    saveAndNext: "जतन करा आणि पुढे",
    finish: "समाप्त",
    approve: "मंजूर",
    reassign: "पुन्हा नियुक्त करा",

    delete: "हटवा",
    saveAndNext: "जतन करा आणि पुढे",
    exit: "बाहेर पडा",
    back: "परत",

    submit: "सबमिट करा",

    cancel: "रद्द करा",

    saveAsDraft: "मसुदा म्हणून जतन करा",
    approveOpinion: "मत मंजूर करा",
    addMore: "आणखी जोडा",
    delete: "हटवा",

    bookClassification: "पुस्तक वर्गीकरण",
    bookMaster: "पुस्तक मास्टर",
    bookIssueReturn: "पुस्तक जारी/वापराची रिपोर्ट",
    dailyEntryMagazineNewspaper: "मासिके आणि वर्तमानपत्रांसाठी दैनिक रेकॉर्ड",

    libraryCSC: "ग्रंथालय/स्पर्धात्मक अभ्यास केंद्र",
    applicantName: "अर्जदाराचे नाव",
    membershipDetails: "सदस्यत्व तपशील",
    startDate: "सदस्यत्व सुरू होण्याची तारीख",
    endDate: "सदस्यत्व समाप्ती तारीख",
    membershipMonths: "महिन्यांसाठी सदस्यत्व",
    identityProof: "ओळख पुरावा",
    addressProof: "पत्ता पुरावा",
    preview: "पूर्वावलोकन",

    newBookRequest: "नवीन पुस्तकाची विनंती",
    bookName: "पुस्तकाचे नाव",
    publication: "प्रकाशन",
    language: "भाषा",
    bookClassification: "पुस्तक वर्गीकरण",
    bookType: "पुस्तकाचा प्रकार",
    bookSubType: "पुस्तक उपप्रकार",
    author: "लेखक",
    bookEdition: "पुस्तक आवृत्ती",
    closeMembership: "सदस्यत्व रद्द करा",
    membershipNo: "सदस्यत्व क्र",
    searchMember: "सदस्य शोधा",
    memberName: "सदस्याचे नाव",
    dues: "प्रलंबित थकबाकी",
    reason: "कारण",
    renewMembership: "सदस्यत्वाचे नूतनीकरण",
    renewDetails: "तपशीलांचे नूतनीकरण",
    startDateM: "नूतनीकृत प्रारंभ तारीख",
    membershipMonthsM: "महिन्यांसाठी सदस्यत्वाचे नूतनीकरण करा",

    refundDeposit: "परतावा ठेव",
    bankEcsDetails: "बँक (ECS फॉर्म) तपशील",
    bankHolderName: "बँक खातेधारकाचे नाव",
    bankAccountNumber: "बँक खाते क्रमांक",
    typeOfBankAccount: "बँक खात्याचा प्रकार",
    bankAddress: "बँकेचा पत्ता",

    booksMaster: "पुस्तके मास्टर",
    bookPrice: "पुस्तकाची किंमत",
    totalBooksCopy: "एकूण पुस्तकांच्या प्रती",
    barcode: "क्यूआर कोड",

    id: "आयडी",
    bookTypeMaster: "पुस्तक प्रकार मास्टर",
    bookSubTypeMaster: "पुस्तक उपप्रकार मास्टर",
    magazinesNewspaperName: "मासिके/वृत्तपत्रांचे नाव",
    magazinesNewspaperSubCategory: "मासिके/वृत्तपत्र उपवर्गाचे नाव",
    supplierName: "पुरवठादाराचे नाव",
    contactNumber: "संपर्क क्रमांक",
    remark: "टिप्पणी",
    magazineNewspaperMaster: "मासिक वृत्तपत्र मास्टर",
    applicationDate: "अर्जाची तारीख",
    photoAttachment: "पासपोर्ट आकाराचा फोटो",
    taxReceipt: "कर पावती",
    libraryCSCMaster: "ग्रंथालय/स्पर्धात्मक अभ्यास केंद्र मास्टर",
    libraryType: "ग्रंथालय प्रकार",
    libraryNameMr: "ग्रंथालयाचे/स्पर्धात्मक अभ्यास केंद्र नाव (मराठी मध्ये)",
    libraryName: "ग्रंथालयाचे/स्पर्धात्मक अभ्यास केंद्र नाव (इंग्रजी मध्ये)",
    rateChartMaster: "रेट चार्ट मास्टर",
    chargeNameEng: "शुल्काचे नाव (इंग्रजी मध्ये)",
    chargeNameMr: "शुल्काचे नाव (मराठी मध्ये)",
    chargePrefixEng: "शुल्क उपसर्ग (इंग्रजी मध्ये)",
    chargePrefixMr: "शुल्क उपसर्ग (मराठी मध्ये)",
    chargeType: "चार्ज प्रकार",
    amount: "रक्कम",
    service: "सेवा",
    print: "छापणे",
    shelfCatlogMaster: "शेल्फ कॅटलॉग मास्टर",
    lib: "ग्रंथालयाचे नाव",
    shelfNo: "शेल्फ क्र",
    shelfCatlogSection: "शेल्फ कॅटलॉग विभाग",
    applicationNo: "अर्ज क्र",
    serviceName: "सेवेचे नाव",
    applicationStatus: "अर्जाची स्थिती",
    bookIssueReturnTitle: "पुस्तक अंक/परतावा",
    bookIssueReturnHistory: "पुस्तक जारी आणि परतीचा इतिहास",
    issue: "जारी",
    Issue: "जारी",
    form: "फॉर्म",
    Return: "परत",
    bookLost: "पुस्तक हरवले",
    Lost: "हरवले",
    chooseBook: "पुस्तक निवडा",
    dateOf: "ची तारीख",
    bookDetails: "पुस्तकाचे तपशील",
    totalAvailableBookCopy: "उपलब्ध पुस्तकांची प्रत",
    issuedAt: "येथे जारी केले",
    newMembershipRegistration: "नवीन सदस्य नोंदणी",
    issueLibCard: "लायब्ररी कार्ड द्या",
    chargesDetails: "शुल्क तपशील",
    serviceChargeTypeName: "सेवा शुल्काचे प्रकार नाव",
    totalCharges: "एकूण शुल्क (रु.)",
    totalInWords: "शब्दांमध्ये एकूण (रु.)",
    generateLoi: "LOI व्युत्पन्न करा",
    paymentCollection: "पेमेंट संकलन",
    paymentType: "पैसे भरण्याची पध्दत",
    paymentMode: "पेमेंट मोड",
    bankAccountNo: "बँक खाते क्र",
    ddNo: "डीडी क्र",
    ddDate: "डीडी तारीख",
    upiId: "UPI आयडी",
    upiList: "UPI यादी",
    pay: "पैसे भरा",
    paymentDetails: "देयक तपशील",
    dailyEntryMagazineNewspaper: "दैनिक प्रवेश मासिके वर्तमानपत्र",
    quantity: "प्रमाण",
    publishedDate: "प्रकाशित तारीख",
    receivedDate: "प्राप्ती दिनांक",
    refundDeposit: "परतावा ठेव",
    librarianRemark: "ग्रंथपाल टिप्पणी",
    sendToAccountDept: "खाते विभागाकडे पाठवा",
    membershipCloseDate: "सदस्यत्व बंद करण्याची तारीख",
    lastEndDate: "अंतिम सदस्यत्व समाप्ती तारीख",
    chequeDate: "धनादेश तारीख",
    chequeNo: "धनादेश क्र",
    selectZone: "कृपया झोन निवडा",
    selectLibrary: "कृपया ग्रंथालय/स्पर्धात्मक अभ्यास केंद्र निवडा",
    selectTitle: "कृपया शीर्षक निवडा",
    enterFName: "कृपया पहिले नाव भरा (इंग्लिश मध्ये)",
    enterMName: "कृपया मधले  नाव भरा (इंग्लिश मध्ये)",
    enterLName: "कृपया शेवटचे नाव भरा (इंग्लिश मध्ये)",

    enterFNameMr: "कृपया पहिले नाव भरा (मराठी मध्ये) ",
    enterMNameMr: "कृपया मधले  नाव भरा (मराठी मध्ये)",
    enterLNameMr: "कृपया शेवटचे नाव भरा (मराठी मध्ये)",
    enterEmailAddress: "कृपया ई-मेल भरा",
    enterMobileNo: "कृपया मोबाईल नं. भरा",
    enterFlat: "कृपया  फ्लॅट नंबर नाव भरा  (इंग्लिश मध्ये) ",
    enterApartment: "कृपया  अपार्टमेंट  नाव भरा  (इंग्लिश मध्ये)",
    enterFlatMr: "कृपया  फ्लॅट नंबर नाव भरा  (मराठी मध्ये)",
    enterApartmentMr: "कृपया  अपार्टमेंट  नाव भरा(मराठी मध्ये)",
    enterRoadNameMr: "कृपया रस्त्याचे नाव भरा  (मराठी मध्ये)",
    enterLandmarkMr: "कृपया  महत्त्वाची खूण भरा  (मराठी मध्ये)",
    enterCityMr: "कृपया  शहराचे / गावाचे नाव भरा (मराठी मध्ये)",
    // stateMr: "कृपया  राज्य नाव भरा  (मराठी मध्ये)",
    enterPinCode: "कृपया पिनकोड भरा",
    selectMembershipMonths: "कृपया सदस्यता महिने निवडा",
    enterBankAccountHolderName: "कृपया बँक धारकाचे नाव प्रविष्ट करा",
    enterBankAccountNo: "कृपया बँक खाते क्रमांक प्रविष्ट करा",
    selectBankAccount: "कृपया बँक खात्याचा प्रकार निवडा",
    invalidBankAccountNo:
      "बँक खाते क्रमांक ६ ते २० अंकांचा असणे आवश्यक आहे आणि फक्त अंकांना परवानगी आहे",
    selectBankName: "कृपया बँकेचे नाव निवडा",
    enterBankAddress: "कृपया बँकेचा पत्ता प्रविष्ट करा",
    enterBankIFSC: "कृपया बँक IFSC कोड प्रविष्ट करा",
    enterBankMICR: "कृपया बँक MICR कोड प्रविष्ट करा",
    enterBookName: "कृपया पुस्तकाचे नाव प्रविष्ट करा",
    enterPublication: "कृपया प्रकाशन प्रविष्ट करा",
    selectLanguage: "कृपया भाषा निवडा",
    selectBookClassification: "कृपया पुस्तक वर्गीकरण निवडा",
    selectBookType: "कृपया पुस्तकाचा प्रकार निवडा",
    selectBookSubType: "कृपया पुस्तक उपप्रकार निवडा",
    enterAuthor: "कृपया लेखक प्रविष्ट करा",
    enterBookEdition: "कृपया पुस्तक संस्करण प्रविष्ट करा",
    bookSize: "पुस्तकाचा आकार (इंच मध्ये)",
    noOfPages: "पृष्ठांची संख्या",
    price: "किंमत",
    magazineNewspaperType: "वृत्तपत्र प्रकार",
    purchaseType: "खरेदी प्रकार",
    searchBook: "पुस्तक शोधा",
    search: "शोधा",
    bookCaseNo: "पुस्तक प्रकरण क्र",
    accessionNo: "प्रवेश क्रमांक",
    village: "गाव",
    gisId: "GIS आयडी",
    libraryClassification: "लायब्ररी प्रशासकीय स्थिती",
    education: "शिक्षण (पदवी)",
    educationDoc: "शिक्षण (पदवी) पुरावा",
    educationEnter: "कृपया शिक्षण (पदवी) प्रविष्ट करा",
    witnessDetails: "साक्षीदार तपशील",
    referenceMobileNo: "साक्षीदाराचा मोबाईल क्र",
    generateOtp: "OTP जनरेट करा",
    verifiedOtp: "OTP सत्यापित",
    reopenMembership: "सदस्यत्व पुन्हा उघडा",
    transferLibraryMembership: "ग्रंथालय सदस्यत्व हस्तांतरित करा",
    transferMembershipDetails: "ग्रंथालय सदस्यत्व तपशील हस्तांतरित करा",
    userKey: "वापरकर्ता आयडी",
    bookConditionMaster: "बुक कंडिशन मास्टर",
    bookConditionEn: "पुस्तकाची स्थिती (इंग्रजीमध्ये)",
    bookConditionMr: "पुस्तकाची स्थिती (मराठीत)",
    reOpen: "पुन्हा उघडा",
    renewMembershipDetails: "सदस्यत्व नूतनीकरण/पुन्हा उघडा",
    finePaid: "दंड भरला",
    fineNotPaid: "दंड भरला नाही",
    fineAmount: "दंड रक्कम",
    note: "नोंद - लायब्ररी प्रकार 1) एल (लायब्ररीसाठी) 2) सी (स्पर्धात्मक केंद्रासाठी) असणे आवश्यक आहे. ३) पी (पोस्ट ग्रॅज्युएट लायब्ररीसाठी)",
    classificationCode: "वर्गीकरण कोड",
    bookTypeCode: "पुस्तक प्रकार कोड",
    identityProofMessage: "कृपया ओळखीचा पुरावा जोडावा..!!",
    addressProofMessage: "कृपया पत्त्याचा पुरावा जोडावा..!!",
    passportProofMessage: "कृपया पासपोर्ट साईझ फोटो संलग्न करा..!!",
    taxReceiptMessage: "कृपया कर पावती संलग्न करा..!!",

    yourPaymentDoneSuccess: " तुमचे पेमेंट यशस्वी झाले!!!",
    paymentFailed: "पेमेंट अयशस्वी !!!",
    orderId: "ऑर्डर आयडी ",

    trackingId: "ट्रॅकिंग आयडी",
    bankRefNo: "बँक संदर्भ क्र",
    billingName: "बिलिंग नाव",
    billingAdd: "बिलाचा पत्ता",
    billingCity: "बिलिंग शहर",
    billingZip: "बिलिंग पिन कोड ",
    billingCountry: "बिलिंग देश",
    billingEmail: "बिलिंग ईमेल",
    mobileNo: "मोबाईल क्र",
    transactionDate: "व्यवहाराची तारीख",
    billingState: "बिलिंग राज्य",
    goToList: "सूचीवर जा",
    loiNo: "हेतू पत्र क्र",
    totalAmount: "एकूण रक्कम",
    remarkModel: "अर्जावर टिप्पणी प्रविष्ट करा",

    uploadFile: "अपलोड फाइल",
    backToHomeBtn: "होम बटणावर परत",
    printD: "प्रिंट",
  },
};
