export default {
  en: {
    boardType: "Board Type",
    otherDocuments: "Other Marriage Related Documents",
    fileName: "File Name",
    fileType: "File Type",
    uploadBy: "Upload By",
    action: "Action",
    attachmentSchema: "*the maximum upload size is 2MB.",
    addDocuments: "Add Documents",
    fileUpload: "File Upload",
    cancel: "Cancel",
    print: "Print",
    module: "Marriage Registration",
    // dashboard: 'PCMC Dashboard',
    dashboard: "Pimpri-Chinchwad Municipal Corporation Dashboard",
    masters: "Masters",
    transactions: "Transactions",
    reports: "Reports",
    receipt: "Receipts",
    usertask: "User task",
    serviceName: "Service Name ",
    masters: "Masters",
    masterPath: "FIRE BRIGADE SYSTEM / masters",
    demo: "",
    //mr
    MrMasters: "Marriage Registration / Masters",
    marriageRegistrationMaritalStatus:
      "Marriage Registration / Masters / Marital Status",

    pay: "PAY",
    marriageRegistrationrelation: "Marriage Registration / Masters / relation",
    receiptModeDetails: "Receipt Mode Details",
    maritialSatus: "Marital Status",
    relation: "Relation",

    AptBook: "Appointment Slot Booking",
    SlotMasterHead: "Slot Master",
    serviceChargeTypeName: "Service Charge Type Name",
    registrationFees: "Registration Fees (Rs.)",
    // field label
    srNo: "Sr. No",
    actions: "Actions",
    statusDetails: "Status Details (In English)",
    statusDetailsEng: "Status Details(In English)",
    gstatusAtTimeMarriageKey: "Groom Marital Status At Time Marriage",
    bstatusAtTimeMarriageKey: "Bride Marital Status At Time Marriage",
    //buttons
    add: "Add",
    save: "Save",
    update: "Update",
    clear: "Clear",
    exit: "exit",

    ward: "Ward",
    zone: "Zone",
    latitude: "Latitude",
    Longitude: "Longitude",

    documentUpload: "Documents Upload",
    applicationCreated: "Application Submitted Successfully",
    addFile: "Choose File",
    fileName: "File Name",
    mandatoryOrOptional: "Mandatory/Optional",
    mandatory: "Mandatory",
    optional: "Optional",
    upload: "Upload",
    next: "Next",
    preview: "Preview",
    verify: "Verify",
    reject: "Reject",
    noFileFound: "No file found",
    verified: "Verified",

    attachFile: "Attach File",
    srNo: "Sr. No",
    actions: "Actions",

    //breadcrum
    landReservationPath: "Town Planning / Master / Land Reservation ",

    attachFile: "Attach File",
    srNo: "Sr. No",
    actions: "Actions",

    //buttons
    add: "Add",
    save: "Save",
    update: "Update",
    clear: "Clear",
    exit: "Exit",
    back: "Back",
    saveAndNext: "Save & Next",
    finish: "Finish",

    //marathi details
    gFNameMr: "",
    gMNameMr: "",
    gLNameMr: "",
    ApplicatCheck1: "If the Applicant is Groom",
    ApplicatCheck2: "If the Applicant is Bride",
    ApplicatCheck1mod:
      "Do you want to Modify Groom Details ? Please attached document ! ",
    ApplicatCheck2mod:
      "Do you want to Modify Bride Details ? Please attached document ! ",

    OwnerChkeck: "Is the Applicant is Owner",
    transactions: "Transactions",
    transactionPath: "Legal Case / Transaction ",

    //mr
    Tnc: "Accept term & Condition",
    // instrustion
    onlyMHR:
      " Either the bride or the groom must be a resident of Pimpri Chinchwad Municipal Corporation limits and the Marriage should have taken place in Maharashtra.",
    // docNote: "Id proof, Residential proof, Age proof should be different ",
    // (Previous Status Proof contain value if Status at the time of marriage is Widow/ Widower or Divorce) If Aadhaar card proof is added and citizen A registered agreement is required if living on rent.

    //table
    newMRtable: "NEW MARRIAGE REGISTRATION ",
    boardtitle: "  Marriage Board Registration ",
    zone: "Zone",
    ward: "Ward",
    Addrees: "Applicant Address :",
    CrrtAdree: "Current Address :",
    parmtAdree: "Permanent Address :",
    personalDetails: "Personal Information :",
    partmapDetails: "Part Map Details :",
    Adress: "Address  :",
    AdressPrf: "Address proof",
    BriNBM: "  (  Name before marriage)",
    AppliToGroom: "If the Applicant is Groom ",
    AppliToBride: "If the Applicant is Bride",
    marrigeDetails: "MARRIAGE DETAILS ",
    marrigeDate: "Marriage Date",
    //aprove
    GPhoto: "Groom Photo  ",
    Bphoto: "Bride Photo  ",
    witnessphto1: "Witness 1 Photo  ",
    witnessphto2: "Witness 2 Photo  ",
    witnessphto3: "Witness 3 Photo  ",
    Gthumb: "Groom Thumb  ",
    Bthumb: "Bride Thumb  ",
    witnessthumb1: "Witness 1 Thumb  ",
    witnessthumb2: "Witness 2 Thumb  ",
    witnessthumb3: "Witness 3 Thumb  ",

    //title
    ApplicatDetails: "APPLICANT DETAILS",
    ApplicatName: "Applicant Name",
    groomDetail: "GROOM DETAILS",
    groomParaentDetail: "Groom Parents Details ",
    brideDetails: "BRIDE DETAILS",
    brideParaentDetail: "Bride Parents Details",
    priestDetails: "PRIEST DETAILS",
    witness: "Witness",
    witnessAdd: "Witness",
    witnessDetails: "WITNESS DETAILS",
    documentsUpload: "DOCUMENT UPLOAD",
    boardDetail: "Board Details :",
    otherDetail: "OTHER DETAILS",
    titleInmarathi: "Title (In Marathi)",
    titleInenglish: "Title (In english)",

    // viceversa
    titleV: "शीर्षक",
    firstNameV: "प्रथम नावं  ",
    middleNameV: "मधले नावं  ",
    lastNameV: "शेवटचे नाव  ",

    //Groom
    // title: 'Title  ',
    // firstName: 'First Name  ',
    // middleName: 'Middle Name  ',
    // lastName: 'Last Name  ',
    title: "Title ",
    title1: "Title ",
    firstName: "First Name (In English) ",
    middleName: "Middle Name (In English) ",
    lastName: "Last Name (In English) ",
    titlemr: "शीर्षक ",
    firstNamemr: "First Name (In Marathi) ",
    middleNamemr: "Middle Name (In Marathi) ",
    lastNamemr: "Last Name (In Marathi) ",
    otherNameMr: "Other Name(If any)(In Marathi)",
    otherName: "Other Name(If any)(In English)",

    BirthDate: "Birth Date   ",
    Gender: "Gender",
    AadharNo: "Aadhar No",
    Age: "Age (at the time of marriage)",
    gAge: "Groom Age (at the time of marriage)",
    bAge: "Bride Age (at the time of marriage)",
    mobileNo: "Mobile / Phone Number",
    phoneNo: "Phone Number",
    email: "Email",
    gmobileNo: "Groom Mobile No",
    bmobileNo: "Bride Mobile No",

    flatBuildingNo: "Flat/Building No (In English)  ",
    buildingName: "Apartment Name (In English) ",
    roadName: "Road Name (In English) ",
    Landmark: "Landmark (In English) ",
    villageName: "Village Name (In English) ",
    cityName: "City Name / Village Name (In English) ",

    flatBuildingNomr: "Flat/Building No (In Marathi) ",
    buildingNamemr: "Apartment Name (In Marathi) ",
    roadNamemr: "Road Name (In Marathi) ",
    Landmarkmr: "Landmark (In Marathi) ",
    villageNamemr: "Village Name (In Marathi) ",
    cityNamemr: "City Name / Village Name (In Marathi) ",

    gReligion: "Groom Religion",
    bReligion: "Bride Religion",
    State: "State (In English) ",
    statemr: "State (In Marathi) ",
    pincode: "Pin Code",
    Religion1: "Religion by Birth",
    Religion2: " Religion by Adoption",
    StatusOfMarrige: " Status at time of marriage",
    AgeDocument: "Birth Proof Document",
    IdDocument: "ID Document",
    residentialDocument: "Residential Document",
    StatusOfDocument: "Status Of Document",
    gOccupation: "Occupation(In English)",
    gOccupationAddress: "Business/ Office Address(In English)",
    gOccupationMr: "Occupation(In Marathi)",
    gOccupationAddressMr: "Business/ Office Address(In Marathi)",
    lawOfMarriageE: "Please select Law Of Marriage",
    // lawOfMarriageMr: " (In Marathi)",

    // //groomFather
    // firstNameF: 'Father First Name  ',
    // middleNameF: 'Father Middle Name  ',
    // lastNameF: 'Father Last Name  ',
    // AgeF: 'Father Age',
    // mobileNoF: 'Father Mobile Number',
    // AadharNoF: 'Father Aadhar No',

    // //groomMother
    // firstNameM: 'Mother First Name  ',
    // middleNameM: 'Mother Middle Name  ',
    // lastNameM: 'Mother Last Name  ',
    // AgeM: 'Mother Age',
    // mobileNoM: 'Mother Mobile Number',
    // AadharNoM: 'MotheM Aadhar No',

    //prist
    placeofMarriage: "Place of Marriage (In English)",
    pplaceofMarriage: "Place of Marriage ",
    placeofMarriage1: "Place of Marriage (In Marathi)",

    //witness
    address: "Address (In English)",
    addressMr: "Address (In Marathi)",
    wRelation: "Witness Relation",
    wDocument: "Witness Document",

    //Document

    DBProof: "Date of Birth Proof",
    ResProof: "Residence Proof",
    IdProof: "ID Proof",

    DBProof1: "Date of Birth Proof of first witness",
    DBProof2: "Date of Birth Proof of second witness",
    DBProof3: "Date of Birth Proof of third witness",

    ResProofW1: "Proof of first witness",
    ResProofW2: "Proof of second witness",
    ResProofW3: "Proof of third witness",

    marrigeRelatedDoc: "Marriage Related Document",

    invetaionCard:
      "Original Marriage Invitation Card / Affidavit - Rs.100 stamp paper",
    marrigePhotoC: "Marriage Photograph ",
    marDrf: "Draft an application on the 100 Rs Stamp",

    DivorcePaperg: "Decree / Judgement Copy of Divorce of Groom",
    DeathCg: "Death Certificate of previous Spouse",

    DivorcePaperb: "Decree / Judgement Copy of Divorce of Bride",
    DeathCb: "Death Certificate of previous Spouse",

    nikahnamag: "Nikahnama of Groom",
    nikahnamab: "Nikahnama of Bride",

    certiByReligiousPlc:
      " Certificate issued by religious place i.e Temple, Mosque etc",
    docFormat:
      "(Only jpg.jpeg.png.bmp.pdf files are allowed to upload. Photo Size max 10 MB)",
    enterDoc: "Document Name",
    TandC: "",
    //board
    applicantName: "Applicant Name :",
    boardNameT: "Marriage Board Name",
    boardName: "Marriage Board Name (In English)  ",
    boardNamemr: "Marriage Board Name (In Marathi)  ",
    remark: "Remarks",
    documentList: " Documents List",
    ValidtyofMBR: "  Validity Of MBR",
    documentsUploadF: "Documents Upload",

    //button
    back: "Back",
    next: "Next",
    add: "Add",
    save: "Save",
    update: "Update",
    clear: "Clear",
    exit: "Exit",
    submit: "Submit",
    apply: "Apply",
    addFile: "Upload File",

    //table filed
    srNo: "Sr. No",
    ApplicantName: "Applicant Name",
    hName: "Groom Name",
    wName: "Bride Name",
    actions: "Actions",

    //brudcrum
    newMarriageRegistration:
      "Marriage Registration / New Marriage Registration",
    BoardMarriageRegistration: "Marriage Registration / New Board Registration",

    //ReIssuance of Marriage Certificate

    onlyRIMC: "Re-Issuance of Marriage Certificate",
    mRegNo: "Marriage Reg No",
    marriageDate: "Marriage Date",
    marriageYear: "Marriage Year",
    brideName: "Bride Name",
    groomName: "Groom Name",
    regDate: "Registration Date",

    //Renewal of Marriage Board Registration
    onlyRMBR: "Renewal of Marriage Board Registration",
    mbrName: "Marriage Board Name",
    mbrDate: "Marriage Board Reg Date",
    mbrYear: "Marriage Board Reg Year",
    search: "Search",

    //Application Details

    onlyApplDetail: "Application Details",
    applFName: "Applicant First Name",
    applMName: "Applicant Middle Name",
    applLName: "Applicant Last Name",
    groomFName: "Groom First Name",
    groomMName: "Groom Middle Name",
    groomLName: "Groom Last Name",
    brideFName: "Bride First Name",
    brideMName: "Bride Middle Name",
    brideLName: "Bride Last Name",
    mDate: "Marriage Date",

    //ReIssuance of marriage Certificate
    newRMItable: "ReIssuance of Marriage Certificate",
    applFullName: "Applicant Full Name",
    applicationNo: "Application No",
    generateLoi: "Generate LOI",

    //Modification in Marriage Board Registration

    onlyMMBR: "MODIFICATION IN MARRIAGE BOARD REGISTRATION",
    applicationDate: "Application Date",
    registerationDate: "Registeration Date",
    registerationNo: "Marriage Board Reg Number",
    orgName: "Organisation Name",

    //Payment Collection
    bankName: "Bank Name",
    branchName: "Branch Name",
    ifsc: "IFSC Code",
    accountNumber: "Account Number ",
    pay: "Pay",
    exit: "Exit",

    //validation
    selectWard: "Please select a ward",
    selectDate: "Please select a date",
    selectTitle: "Please select a title",

    enterFName: "Please enter first name (In English)",
    enterMName: "Please enter middle name (In English)",
    enterLName: "Please enter last name (In English)",

    enterFNameMr: "Please enter first name (In Marathi) ",
    enterMNameMr: "Please enter middle name (In Marathi)",
    enterLNameMr: "Please enter last name (In Marathi)",

    enterFlat: "Please enter Flat/Building No (In English) ",
    enterApartment: "Please enter Apartment Name (In English)",
    enterRoadName: "Please enter Road Name (In English)",
    enterstatusName: "Please enter marital status (In English)",
    enterstatusNameMr: "Please enter marital status (In Marathi)",
    enterLandmark: "Please enter Landmark (In English)",
    enterCity: "Please enter a City Name / Village Name (In English) ",
    state1: "Please enter State (In English)",
    occupation: "Please Enter Occupation",
    occupation: "Please Enter Occupation",
    occupationAddress: "Please Enter Occupation Address",
    occupationAddress: "Please Enter Occupation Address",
    occupationAddress: "Please Enter Occupation Address",

    enterFlatMr: "Please enter Flat/Building No (In Marathi)",
    enterApartmentMr: "Please enter Apartment Name (In Marathi)",
    enterRoadNameMr: "Please enter Road Name (In Marathi)",
    enterLandmarkMr: "Please enter Landmark (In Marathi)",
    enterCityMr: "Please enter a City Name / Village Name (In Marathi)",
    stateMr: "Please enter State (In Marathi)",

    enterServiceId: "Please enter service Id ",
    enterChargeName: "Please enter charge name (In English)",
    enterChargeNameMr: "Please enter charge name (In Marathi)",
    enterChargeType: "Please enter charge type (In English)",
    enterChargeTypeMr: "Please enter charge type (In Marathi)",

    enterAmount: "Please enter Amount",
    enterdurationTo: "Please enter to duration",
    enterdurationForm: "Please enter from duration",

    enterPinCode: "Please enter a pincode ",
    enterPhoneNo: "Please enter a phone no. ",
    enterMobileNo: "Please enter a mobile no. ",
    enterEmailAddress: "Please enter an e-mail. ",
    enteraadhaarNo: "Please enter an aadhaar no. ",
    enterpanNo: "Please enter an pan no. ",
    enterRemarks: "Please enter a remark. ",
    enterAge: "Please enter a Age. ",
    selectGender: "Please select a Gender ",
    selectReligionby: "Please select a Religion by Birth",
    selectAdoptionby: "Please select a Religion by Adoption",
    selectStatusAt: "Please select a Status at time of marriage",

    //mr
    selectZone: "Please select a zone",
    selectWard: "Please select a ward",
    selectZone: "Please select a Zone",
    selectTitle: "Please select a Title",
    placeMarriage: "Please enter Place of Marriage (In English)",
    placeMarriageMr: "Please enter Place of Marriage (In Marathi)",

    birthProf: "Please select a Date of Birth Proof",
    ResideProof: "Please select a Residence Proof",
    IdentyProof: "Please select a ID Proof",

    witnessAddressC: "Please enter an Address (In English)",
    witnessAddressCMar: "Please enter an Address (In Marathi)",
    witnessRelation: "Please enter an Relation. ",
    boardOrganizationPhotoMod: "Please Attach Board Organization Photo. ",
    residentialProofMod: "Please Attach Residential Proof.",
    identityProofMod: "Please Attach Identity Proof.",

    EnterDocName: "Please enter an Document Name ",

    noOfCopies: "No of Copies",
    charges: "Total Charges",
    chargeName: "Charge Name",
    amount: "Amount",
    totalInWords: "Total Charges in Words",
    totalCharges: "Total Charges",
    applicantDetails: "Applicant Details",
    chargesDetails: "Charges Details",
    paymentMode: "Payment Mode",
    paymentType: "Payment Type",
    receiptDate: "Receipt Date",
    receiptNumber: "Receipt Number",
    receiptAmount: "Receipt Amount",
    ddNo: "Demand Draft Number",
    ddDate: "Demand Draft Date",
    bankName: "Bank Name",
    branchName: "Branch Name",
    bankAccountNo: "Bank Account No",

    cheuqeNo: "Cheuqe Number",
    cheuqeDate: "Cheuqe Date",
    gAddress: "Groom Address",
    bAddress: "Bride Address",
    //Modification in Marriage Certificate

    onlyMIMC: "Modification in Marriage Registration",
    oldLabel: "Old Information",
    newLabel: "New Information",
    gDoc: "Groom Documents",
    bDoc: "Bride Documents",
    OwnerDetails: " Owner Details :",
    Owneraddress: " Owner Address :",
    document: "Document Tab ",
    boardheadphoto: "Board Head Person Photo",
    boardorgphotocpy: "Board / Organization PhotoCopy",
    panCard: "Pan Card",
    adharcard: "Aadhaar card",
    rationcard: "Ration card",
    electrbill: "Electric Bill",
    OtherDocument: "Other Document",
    UploadFile: " Upload File",
    remarkModel: "Enter Remark On Application",
    APPROVE: "Approve",

    REASSIGN: "Revert Back",
    onlyeng: "Must be only characters",
    onlymarathi: "Must be only  marathi",

    //validation file upload
    birthProfV: "Please Upload a Date of Birth Proof",
    ResideProofV: "Please Upload a Residence Proof",
    IdentyProofV: "Please Upload a ID Proof",

    nikahnama: "Please Upload Document",
    deathcerti: "Please Upload Death Certificate",
    gudivorcePaper: "Please Upload Groom's Divorce Paper",
    budivorcePaper: "Please Upload Bride's Divorce Paper",
    personDisabled: "Please Upload Bride Disability certificate",
    personDisabled1: "Please Upload Groom Disability certificate",
    invetaionCardV: "Please Upload a Marriage Invitation card / affidavit ",
    marrigePhotoCV: "Please Upload a Marriage Photograph (Couple) ",
    marDrfV: "Please Upload a Draft an application on the 100 Rs Stamp",
    boardheadphotoV: "Please Upload a Board Head Person Photo",
    boardorgphotocpyV: "Please Upload a Board / Organization PhotoCopy",
    panCardV: "Please Upload a Pan Card",
    adharcardV: "Please Upload a Aadhaar card",
    rationcardV: "Please Upload a Ration card",
    electricBillV: "Please Upload a Electric Bill",
    otherDocumentV: "Please Upload a Other Document",
    registrationNumber: "Registration Number",
    registrationDate: "Registration Date",
    disablety: " Disability Type",
    AppliToGroomD: "Is Groom Disabled",
    AppliToBrideD: "Is Bride Disabled",
    sentbyuser: "Sent By User",
    date: "Date",
    time: "Time",
    applicationHis: "Application History",
    loiNo: "एल ओ आय क्र",

    yourPaymentDoneSuccess: " Your Payment Done Successfully!!!",
    paymentFailed: "Payment failed!!!",
    orderId: "Order Id ",
    trackingId: "Tracking Id",
    bankRefNo: "Bank Reference No",
    billingName: "Billing Name",
    billingAdd: "Billing Address",
    billingCity: "Billing City",
    billingZip: "Billing Zipcode ",
    billingCountry: "Billing Country",
    billingEmail: "Billing Email",
    mobileNo: "Mobile No",
    billingState: "Billing State",
    transactionDate: "Transaction Date",
    goToList: "Go To List",
    totalAmount: "Total Amount",
    // loiNo: "LOI No",
    serviceId: "Service Id",
    chargeNameMr: "Charge Name(In Marathi)",
    statusDetailsMr: "Status Details(In Marathi)",
    chargeType: "Charge Type",
    chargeTypeMr: "Charge Type(In Marathi)",
    relationMr: "Relation (In Marathi)",
    relationEng: "Relation (In English)",
    durationFrom: "Duration From",
    durationTo: "Duration To",
    gFullName: "Groom Full Name",
    bFullName: "Bride Full Name",
    isGroomDisabled: "Is Groom Disabled",
    isBrideDisabled: "Is Bride Disabled",
    gdisabledType: "Type Of Disabled (Groom)",
    bdisabledType: "Type Of Disabled(Bride)",

    delete: "Delete",

    //schedule
    fromTime: "From time",
    toTime: "To Time",
    noOfCopies: "No. of Copies",

    // filter
    modInMC1: " 1) Filter (Registration Number *)",
    modInMC2: " 2) Filter (Zone * ,marriage date *,groom Name ,bride Name )",

    oldMC: "Old Marriage Certificate",
    area: "Area ",
    officeLocation: "Office Location",
    villages: "Village",
    casts: "Caste",

    whoAreYou: "Applicant is",
    whoAreYouV: "Please select Applicant is",
    lawOfMarriage: "Law Of Marriage",

    personalLawEn:
      "Personal Law According to Which the Marriage between the parties was solemnized (In English)",
    personalLawMr:
      "Personal Law According to Which the Marriage between the parties was solemnized (In Marathi)",
    // personalLawEn:
    //   "Personal Law According to Which the Marriage between the parties was solemnized",
    // personalLawMr:
    //   "पक्षकारांमधील विवाह ज्या व्यक्तीगत कायद्यान्वये संपन्न झाला (संपुर्ण तपशिलासह)",
    areaKay: "Area Name",
    selectBoardType: "Please select a Board Type",
    oldBoardCertificate: "Please upload old marriage board certificate",
    aadharCardMod: "Please upload Adhar Card",
    panCardMod: "Please upload PAN Card",
    boardOrganizationPhotoMod: "Please upload Board Organization Photo",
    boardHeadPersonPhotoMod: "Please upload Board Head Person Photo",
    bLongitude: "Longitude",
    bLatitude: "Latitude",

    divorcedDate: "Divorced Date",
    widowDate: "Widow / Widower Date",
    bookNow: "BOOK NOW",
    adharV1: "Adhar Number not valid on above 12 number",
    adharV2: "Adhar Number must be at least 12 number",
    mobileV1: "Mobile Number must be at least 10 number",
    mobileV2: "Mobile Number not valid on above 10 number",
    mobileV: "Enter a Valid Mobile Number",
    emailV: "Incorrect E-mail Format",
    pincodeV1: "Pincode Number must be at least 6 number",
    pincodeV2: "Pincode Number not valid on above 6 number",
    agev211: "Age must be at least 21 year",
    agev212: "Age not valid on above 21 year",
    agev181: "Age must be at least 18 year",
    agev182: "Age not valid on above 18 year",
    dateV: "Please Enter a Date",
    slotdate: "Slot Date",
    noOfSlot: "No of Slot",
    oR: "OR",
    castCategory: "Caste Category",
    token: "Token",
    validationPinCode: "Must be only digits",
  },

  mr: {
    validationPinCode: "फक्त अंकात ",
    token: "टोकण",
    castCategory: "जात श्रेणी",

    oR: "किंवा",
    noOfSlot: "स्लॉटची संख्या",
    slotdate: "स्लॉट तारीख",
    dateV: "कृपया तारीख प्रविष्ट करा.",
    agev211: "वय किमान २१ वर्षे असणे आवश्यक आहे",
    agev212: "वय 21 वर्षांच्या वर वैध नाही",
    agev181: "वय किमान 18 वर्षे असणे आवश्यक आहे",
    agev182: "18 वर्षांवरील वय वैध नाही",
    pincodeV1: "पिनकोड क्रमांक किमान 6 क्रमांकाचा असावा",
    pincodeV2: "6 वरील क्रमांकावर पिनकोड क्रमांक वैध नाही",
    mobileV: "वैध मोबाईल नंबर टाका",
    emailV: "चुकीचे ई-मेल स्वरूप",
    mobileV1: "मोबाइल नंबर किमान 10 नंबर असणे आवश्यक आहे",
    mobileV2: "10 वरील नंबरवर मोबाईल नंबर वैध नाही",
    adharV1: "आधार क्रमांक १२ वरील क्रमांकावर वैध नाही",
    adharV2: "आधार क्रमांक किमान 12 क्रमांकाचा असावा",
    bookNow: "बुक करा",
    widowDate: "विधवा / विधुर तारीख",
    divorcedDate: "घटस्फोटाची तारीख",
    boardType: "बोर्ड प्रकार",
    bLongitude: "रेखांश",
    bLatitude: "अक्षांश",
    otherDocuments: "इतर विवाह संबंधित कागदपत्रे",
    fileName: "फाईलचे नाव",
    fileType: "दस्तावेजाचा प्रकार",
    uploadBy: "द्वारे अपलोड केले",
    action: "कृती",
    attachmentSchema: "*कमाल अपलोड आकार 2MB आहे.",
    addDocuments: "दस्तऐवज जोडा",
    fileUpload: "अपलोड",
    cancel: "रद्द करा",
    areaKay: "क्षेत्राचे नाव",
    whoAreYou: "अर्जदाराची ओळख",
    whoAreYouV: "कृपया अर्जदाराची ओळख निवडा",
    lawOfMarriage: "लग्नाचा कायदा",
    personalLawEn:
      "पक्षकारांमधील विवाह ज्या व्यक्तीगत कायद्यान्वये संपन्न झाला (संपुर्ण तपशिलासह इंग्लिश मध्ये)",
    personalLawMr:
      "पक्षकारांमधील विवाह ज्या व्यक्तीगत कायद्यान्वये संपन्न झाला (संपुर्ण तपशिलासह मराठी मध्ये)",

    casts: "जात",
    villages: "गाव",
    officeLocation: "कार्यालयाचे स्थान",
    area: "क्षेत्राचे नाव",
    nikahnamag: "वराचा निकाहनामा",
    nikahnamab: "वधूचा निकाहनाम",

    AdressPrf: "पत्त्याचा पुरावा",
    gDoc: "वराची कागदपत्रे",
    bDoc: "वधूची कागदपत्रे ",

    oldMC: "जुने विवाह प्रमाणपत्र",
    // filter
    modInMC1: " 1) फिल्टर (नोंदणी क्रमांक *)",
    modInMC2: " 2) फिल्टर (झोन * ,लग्नाची तारीख *, वराचे नाव *, वधूचे नाव *)",

    noOfCopies: "प्रतींची संख्या",
    fromTime: "काळापासून",
    toTime: " वेळेला",

    delete: "हटवा",
    bmobileNo: "वधू मोबाईल क्र",
    gmobileNo: "वराचा मोबाईल क्र",

    bstatusAtTimeMarriageKey: "लग्नाच्या वेळी वधूची वैवाहिक स्थिती",
    gstatusAtTimeMarriageKey: "लग्नाच्या वेळी वराची वैवाहिक स्थिती",
    registrationFees: "नोंदणी शुल्क रु",
    bReligion: "वधू धर्म",
    gReligion: "वराचा धर्म",
    bdisabledType: "अपंगांचा प्रकार (वधू)",
    gdisabledType: "अपंगांचा प्रकार (वर)",
    isGroomDisabled: "वर अपंग आहे",
    isBrideDisabled: "वधू अपंग आहे",
    yourPaymentDoneSuccess: " तुमचे पेमेंट यशस्वी झाले!!!",
    paymentFailed: "पेमेंट अयशस्वी !!!",
    orderId: "ऑर्डर आयडी ",
    gAddress: "वराचा पत्ता",
    bAddress: "वधूचा पत्ता",
    trackingId: "ट्रॅकिंग आयडी",
    bankRefNo: "बँक संदर्भ क्र",
    billingName: "बिलिंग नाव",
    billingAdd: "बिलाचा पत्ता",
    billingCity: "बिलिंग शहर",
    billingZip: "बिलिंग पिन कोड ",
    billingCountry: "बिलिंग देश",
    billingEmail: "बिलिंग ईमेल",
    mobileNo: "मोबाईल क्र",
    transactionDate: "व्यवहाराची तारीख",
    billingState: "बिलिंग राज्य",
    goToList: "सूचीवर जा",
    loiNo: "एल ओ आय क्र",
    totalAmount: "एकूण रक्कम",

    print: "प्रत काढा",
    partmapDetails: "भाग नकाशा तपशील :",
    // loiNo: "LOI क्र",
    applicationHis: "अर्जाचा इतिहास",
    date: "दिनांक",
    time: "वेळ",
    sentbyuser: "वापरकर्त्याने पाठवले",
    AppliToGroomD: "वर अपंग आहे ?",
    AppliToBrideD: "वधु अपंग आहे ?",
    disablety: " अपंगत्वाचा प्रकार",
    registrationNumber: "नोंदणी क्रमांक",
    registrationDate: "नोंदणी दिनांक",
    adharcardV: "कृपया आधार कार्ड अपलोड करा",
    panCardV: "कृपया पॅन कार्ड अपलोड करा",
    boardorgphotocpyV: "कृपया संस्था किंवा मंडळची दस्तऐवज अपलोड करा",
    boardheadphotoV: "कृपया मंडळाच्या प्रमुख व्यक्तीच छायाचित्र अपलोड करा",
    //validation file upload
    birthProfV: "कृपया जन्म पुरावा कागदपत्र अपलोड करा ",
    ResideProofV: "कृपया रहिवासाचा पुरावा अपलोड करा ",
    IdentyProofV: "कृपया ओळखपत्र पुरावा अपलोड करा ",

    nikahnama: "कृपया दस्तऐवज अपलोड करा",
    deathcerti: "कृपया मृत्यू प्रमाणपत्र अपलोड करा",
    gudivorcePaper: "कृपया वरांचा घटस्फोट पेपर अपलोड करा",
    budivorcePaper: "कृपया वधूचे घटस्फोट पेपर अपलोड करा",
    personDisabled: "कृपया वधूचे अपंगत्व प्रमाणपत्र अपलोड करा",
    personDisabled1: "कृपया वराचे अपंगत्व प्रमाणपत्र अपलोड करा",
    invetaionCardV: "कृपया विवाह निमंत्रण पत्रिका / प्रतिज्ञापत्र अपलोड करा",
    marrigePhotoCV: "कृपया विवाह छायाचित्र (जोडीचे) अपलोड करा",
    marDrfV:
      "कृपया १०० रुपयांच्या स्टॅम्प पेपरवर असलेला अर्जाचा मसुदा अपलोड करा",

    registerationNo: "मंडळाचा नोंदणी क्रमांक",
    onlyeng: "फक्त इंग्लिश मध्ये",
    onlymarathi: "फक्त मराठी मध्ये",
    APPROVE: "मंजूर करा",

    REASSIGN: "पुन्हा नियुक्त करा",
    remarkModel: "अर्जावर टिप्पणी प्रविष्ट करा",

    oldLabel: "पूर्वीची माहिती",
    newLabel: "नवीन माहिती",
    onlyMIMC: "विवाह प्रमाणपत्रात बदल",
    State: "राज्य (इंग्रजी मध्ये)",
    statemr: "राज्य (मराठी मध्ये) ",
    UploadFile: "फाइल अपलोड करा",
    electrbill: "वीज बिल",
    OtherDocument: "इतर दस्तऐवज",
    rationcard: "रेशान कार्ड",
    adharcard: "आधार कार्ड",
    panCard: "पॅन कार्ड",
    boardorgphotocpy: "संस्था किंवा मंडळची दस्तऐवज",
    boardheadphoto: "मंडळाच्या प्रमुख व्यक्तीच छायाचित्र",
    document: "दस्तऐवज",
    Owneraddress: " मंडळच्या प्रमुख व्यक्तीचा पत्ता  :",
    OwnerDetails: "मंडळच्या प्रमुख व्यक्तीची माहिती",
    titleInmarathi: "शीर्षक (मराठी मध्ये)",
    titleInenglish: "शीर्षक (इंग्लिश मध्ये)",
    OwnerChkeck: "अर्जादारच विवाह मंडळाचा प्रमुख आहे",
    apply: "जतन करा",
    ifsc: "आय एफ एस सी कोड",
    accountNumber: "खाते क्रमांक",
    bankName: "बँकेचे नाव",
    branchName: "शाखेचे नाव",
    bankAccountNo: "बँक खाते क्रमांक",
    ddDate: "डिमांड ड्राफ्ट तारीख",
    ddNo: "डिमांड ड्राफ्ट क्रमांक",

    cheuqeDate: "चेक तारीख",
    cheuqeNo: "चेक क्रमांक",

    receiptAmount: "पावती रक्कम",
    receiptNumber: "पावती क्रमांक",
    receiptDate: "पावती तारीख",
    paymentMode: "देयक मोड",
    // paymentMode: "पेमेंट मोड",
    paymentType: "देयक प्रकार",
    // paymentType: "पैसे भरण्याची पध्दत",
    receiptModeDetails: "पावती मोड तपशील",
    chargesDetails: "शुल्क तपशील",
    applicantDetails: "अर्जदाराची माहिती",
    generateLoi: "स्विकृती पत्र तयार करा",
    totalCharges: "एकुण रक्कम",
    totalInWords: "एकुण अक्षरी रक्कम ",
    amount: "रक्कम",
    EnterDocName: "कृपया दस्तऐवजाच नाव भरा ",
    witnessAddressC: "कृपया पत्ता भरा  (इंग्लिश मध्ये)",
    witnessAddressCMar: "कृपया पत्ता भरा  (मराठी मध्ये)",
    witnessRelation: "कृपया साक्षीदारशी नाते भरा  ",
    boardOrganizationPhotoMod: "कृपया मंडळ संस्थेचा फोटो जोडा",
    residentialProofMod: "कृपया निवासी पुरावा जोडा",
    identityProofMod: "कृपया ओळखीचा पुरावा जोडा",

    birthProf: "कृपया जन्म पुरावा कागदपत्र निवडा ",
    ResideProof: "कृपया रहिवासाचा पुरावा निवडा ",
    IdentyProof: "कृपया ओळखपत्र पुरावा निवडा ",
    // //Remarks
    selectReligionby: "कृपया जन्माने धर्म निवडा ",
    selectAdoptionby: "कृपया दत्तक घेऊन धर्म निवडा ",
    selectStatusAt: "कृपया लग्नाच्या वेळची स्थिती निवडा ",

    enterAge: "कृपया वय भरा ",
    selectGender: "कृपया लिंग निवडा ",
    selectZone: "कृपया झोन निवडा",
    selectWard: "कृपया वार्ड निवडा",
    selectDate: "कृपया तारीख निवडा",
    selectTitle: "कृपया शीर्षक निवडा",
    enterFName: "कृपया पहिले नाव भरा (इंग्लिश मध्ये)",
    enterMName: "कृपया मधले  नाव भरा (इंग्लिश मध्ये)",
    enterLName: "कृपया शेवटचे नाव भरा (इंग्लिश मध्ये)",
    selectBoardType: "कृपया बोर्ड प्रकार निवडा",
    enterFNameMr: "कृपया पहिले नाव भरा (मराठी मध्ये) ",
    enterMNameMr: "कृपया मधले  नाव भरा (मराठी मध्ये)",
    enterLNameMr: "कृपया शेवटचे नाव भरा (मराठी मध्ये)",

    enterFlat: "कृपया  फ्लॅट नंबर नाव भरा  (इंग्लिश मध्ये) ",
    enterApartment: "कृपया  अपार्टमेंट  नाव भरा  (इंग्लिश मध्ये)",
    enterRoadName: "कृपया रस्त्याचे नाव भरा (इंग्लिश मध्ये)",
    enterstatusName: "कृपया वैवाहिक स्थिती प्रविष्ट करा (इंग्रजी मध्ये)",
    enterstatusNameMr: "कृपया वैवाहिक स्थिती प्रविष्ट करा (मराठीत)",
    enterLandmark: "कृपया  लँडमार्क भरा (इंग्लिश मध्ये)",
    enterCity: "कृपया  शहराचे / गावाचे नाव भरा (इंग्लिश मध्ये)",
    state1: "कृपया  राज्य नाव भरा (इंग्लिश मध्ये)",
    occupation: "कृपया व्यवसाय प्रविष्ट करा",
    occupationAddress: "कृपया व्यवसायाचा पत्ता प्रविष्ट करा",

    enterFlatMr: "कृपया  फ्लॅट नंबर नाव भरा  (मराठी मध्ये)",
    enterApartmentMr: "कृपया  अपार्टमेंट  नाव भरा(मराठी मध्ये)",
    enterRoadNameMr: "कृपया रस्त्याचे नाव भरा  (मराठी मध्ये)",
    enterLandmarkMr: "कृपया  लँडमार्क भरा  (मराठी मध्ये)",
    enterCityMr: "कृपया  शहराचे / गावाचे नाव भरा (मराठी मध्ये)",
    stateMr: "कृपया  राज्य नाव भरा  (मराठी मध्ये)",

    enterArea: "कृपया क्षेत्राचे नाव भरा ",
    enterRoadName: "कृपया रस्त्याचे नाव भरा ",
    enterLandmark: "कृपया  लँडमार्क भरा",
    enterCity: "कृपया  शहराचे / गावाचे नाव भरा ",

    enterServiceId: "कृपया सेवा आयडी प्रविष्ट करा",
    enterChargeName: "कृपया शुल्काचे नाव प्रविष्ट करा (इंग्रजी मध्ये)",
    enterChargeNameMr: "कृपया शुल्काचे नाव प्रविष्ट करा (मराठीत)",
    enterChargeTypeMr: "कृपया शुल्काचा प्रकार प्रविष्ट करा (मराठीत)",
    enterChargeType: "कृपया शुल्क प्रकार प्रविष्ट करा (इंग्रजी मध्ये)",
    enterdurationForm: "कृपया कालावधी पासून प्रविष्ट करा",
    enterdurationTo: "कृपया कालावधी प्रविष्ट करा",
    enterAmount: "कृपया रक्कम प्रविष्ट करा",

    enterPinCode: "कृपया पिनकोड भरा",
    enterPhoneNo: "कृपया दूरध्वनी नं. भरा",
    enterMobileNo: "कृपया मोबाईल नं. भरा",
    enterEmailAddress: "कृपया इलेक्ट्रॉनिक संदेश भरा",
    enteraadhaarNo: "कृपया आधार नं. भरा",
    enterpanNo: "कृपया पॅन नं. भरा",
    enterRemarks: "कृपया टिप्पणी. द्या",
    //mr
    selectWard: "कृपया प्रभाग निवडा ",
    selectZone: "कृपया झोन निवडा ",
    selectTitle: "कृपया शीर्षक निवडा ",
    placeMarriage: "कृपया  विवाहाचे ठिकाण भरा (इंग्लिश मध्ये)",
    placeMarriageMr: "कृपया  विवाहाचे ठिकाण भरा  (मराठी मध्ये)",

    pay: "पैसे भरा",
    titlemr: "शीर्षक ",
    title1: "Title ",
    newMRtable: "नवीन विवाह नोंदणी",
    module: "विवाह नोंदणी",
    // dashboard: 'डॅशबोर्ड',
    dashboard: "पिंपरी-चिंचवड महानगरपालिका डॅशबोर्ड",
    masters: "मास्टर्स",
    transactions: "ट्रैन्ज़ैक्शन",
    reports: "अहवाल",
    receipt: "पावती",
    usertask: "User task",
    serviceChargeTypeName: "सेवा शुल्काचा प्रकार",

    chargeName: "शुल्काचा प्रकार",
    masters: "मास्टर्स",
    masterPath: "तक्रार निरीक्षण / मास्टर्स",

    transaction: "व्यवहार",
    report: "अहवाल",
    masterPath: "अग्निशमन यंत्रणा / मास्टर ",
    transactionPath: "कायदेशीर प्रकरण/ व्यवहार ",
    reportPath: "कायदेशीर प्रकरण/ अहवाल ",

    //mr
    MrMasters: "विवाह नोंदणी/ मास्टर ",
    marriageRegistrationMaritalStatus: "विवाह नोंदणी/ मास्टर / वैवाहिक स्थिती",

    marriageRegistrationrelation: "विवाह नोंदणी/ मास्टर / नाते",

    AptBook: "अपॉइंटमेंट स्लॉट बुकिंग",
    SlotMasterHead: "स्लॉट मास्टर",
    documentUpload: "दस्तऐवज अपलोड",
    addFile: "फाइल जोडा",
    fileName: "फाईलचे नाव",
    mandatoryOrOptional: "अनिवार्य/पर्यायी",
    mandatory: "अनिवार्य",
    optional: "पर्यायी",
    verify: "सत्यापित",
    reject: "नाकारा",
    noFileFound: "कोणतीही फाइल आढळली नाही",
    verified: "तपासून झाले",

    upload: "अपलोड करा",
    next: "पुढे",
    preview: "पूर्वावलोकन",

    attachFile: "फाईल जोडा",
    srNo: "अनु क्र",
    actions: "क्रिया ",
    serviceName: "सेवेचे नाव ",
    //titles

    calendarScheduling: " दिनदर्शिका शेड्युलिंग",
    maritialSatus: "वैवाहिक स्थिती",
    relation: "संबंध/नाते",
    //field label
    srNo: "अनु क्रमांक",
    actions: "क्रिया ",
    statusDetails: "स्थिती तपशील",
    statusDetailsEng: "स्थिती तपशील (इंग्लिश मध्ये)",

    //buttons
    add: "जोडा",
    save: "जतन करा",
    update: "अद्यायावत करा",
    clear: "रिक्त",
    exit: "बाहेर पडा",

    ward: "प्रभाग",
    zone: "झोन",
    latitude: "अक्षांश",
    Longitude: "रेखांश",

    ward: "प्रभाग",
    zone: "झोन",
    latitude: "अक्षांश",
    Longitude: "रेखांश",

    ApplicatCheck1: "जर अर्जदार वर असेल तर",
    ApplicatCheck2: "जर अर्जदार वधु असेल तर",

    ApplicatCheck1mod: "वराची माहिती बदलवायची आहे काय ?",
    ApplicatCheck2mod: "वधुची माहिती बदलवायची आहे काय ?",

    transactions: " ट्रैन्ज़ैक्शन",
    transactionPath: "कायदेशीर प्रकरण/  ट्रैन्ज़ैक्शन ",

    //mr
    // instrustion
    onlyMHR:
      "महाराष्ट्रातील विवाहाचे रजिस्ट्रेशन केले जाते आणि वधू किंवा वर यापैकी एक जण पिंपरी चिंचवड महानगरपालिकेच्या हद्दी मधील रहिवासी असावा.",
    docNote:
      "आयडी पुरावा, रहिवासी पुरावा, वयाचा पुरावा वेगळा असावा, (लग्नाच्या वेळी स्थिती असल्यास मागील स्टेटस प्रूफमध्ये मूल्य असते विधवा/विधुर किंवा घटस्फोटीत आहे) आधारकार्ड पुरावा जोडल्यास व नागरिक भाड्याने राहत असलेस नोंदणीकृत करारनामा आवश्यक आहे.",

    //aprove
    GPhoto: "वरचा फोटो  ",
    Bphoto: "वधुचा फोटो  ",
    witnessphto1: "साक्षीदारचा १ फोटो  ",
    witnessphto2: "साक्षीदारचा २ फोटो  ",
    witnessphto3: "साक्षीदारचा ३ फोटो  ",
    Gthumb: "वरचा अंगठाचा ठसा  ",
    Bthumb: "वधुचा अंगठाचा ठसा  ",
    witnessthumb1: "साक्षीदारचा १ अंगठाचा ठसा  ",
    witnessthumb2: "साक्षीदारचा २ अंगठाचा ठसा  ",
    witnessthumb3: "साक्षीदारचा ३ अंगठाचा ठसा  ",

    //table
    Tnc: "नियम व अटी",
    newMRtable: "नवीन विवाह नोंदणी",
    boardtitle: "विवाह मंडळाची माहिती",
    zone: "झोन",
    ward: "वार्ड",
    Addrees: "अर्जदाराचा रहिवासाचा पत्ता :",

    CrrtAdree: "सध्याचा रहिवासाचा पत्ता :",
    parmtAdree: "कायमचा रहिवासाचा पत्ता :",
    personalDetails: "वैयक्तिक माहिती :",
    Adress: "पत्ता :",
    BriNBM: "  (  लग्नाआधीचे नाव)",
    AppliToGroom: "",
    AppliToBride: "",
    marrigeDetails: "विवाहाची माहिती :",
    marrigeDate: "विवाहाची दिनांक",

    //title
    ApplicatDetails: "अर्जदाराची माहिती",
    ApplicatName: "अर्जदाराचे नाव",
    groomDetail: "वराची माहिती",
    groomParaentDetail: "वराच्या पालकांची माहिती",
    brideDetails: "वधुची माहिती",
    brideParaentDetail: "वधुच्या पालकांची माहिती",
    priestDetails: "पुजारी माहिती",
    witness: "साक्षीदार",
    witnessDetails: "साक्षीदार माहिती",
    documentsUpload: "दस्तऐवज अपलोड",
    boardDetail: "विवाह मंडळाची माहिती :",
    otherDetail: "इतर तपशील",

    // viceversa
    titleV: "Title  ",
    firstNameV: "First Name  ",
    middleNameV: "Middle Name  ",
    lastNameV: "Last Name  ",

    //groom
    title: "शीर्षक",
    firstName: "प्रथम नाव (इंग्लिश मध्ये) ",
    middleName: "मधले नाव (इंग्लिश मध्ये) ",
    lastName: "शेवटचे नाव (इंग्लिश मध्ये) ",
    firstNamemr: "प्रथम नाव (मराठी मध्ये) ",
    middleNamemr: "मधले नाव (मराठी मध्ये) ",
    lastNamemr: "शेवटचे नाव (मराठी मध्ये) ",
    BirthDate: "जन्म दिनांक  ",
    Gender: "लिंग",
    AadharNo: "आधार नंबर",
    Age: "वय (लग्नाच्या वेळीचे वय)",
    gAge: "वराचे वय (लग्नाच्या वेळीचे वय)",
    bAge: "वधूचे वय (लग्नाच्या वेळीचे वय)",
    mobileNo: "दूरध्वनी क्रमांक",
    phoneNo: "फोन नंबर",
    email: "ई-मेल",
    otherName: "इतर नाव (असल्यास) (इंग्रजीमध्ये)",
    otherNameMr: "इतर नाव (असल्यास) (मराठीत)",
    gOccupation: "व्यवसाय (इंग्रजीमध्ये)",
    gOccupationAddress: "व्यवसाय / कार्यालय पत्ता (इंग्रजीमध्ये)",
    gOccupationMr: "व्यवसाय (मराठीत)",
    gOccupationAddressMr: "व्यवसाय / कार्यालय पत्ता (मराठीत)",

    lawOfMarriageE: "कृपया विवाहचा कायदा निवडा",
    // lawOfMarriageMr: " (मराठीत)",

    flatBuildingNo: "फ्लॅट नंबर (इंग्लिश मध्ये) ",
    buildingName: "अपार्टमेंट नाव (इंग्लिश मध्ये) ",
    roadName: "रस्त्याचे नाव (इंग्लिश मध्ये) ",
    Landmark: "लँडमार्क (इंग्लिश मध्ये) ",
    villageName: "Village Name (In English) ",
    cityName: "शहराचे नाव (इंग्लिश मध्ये) ",

    flatBuildingNomr: "फ्लॅट नंबर (मराठी मध्ये) ",
    buildingNamemr: "अपार्टमेंट नाव (मराठी मध्ये) ",
    roadNamemr: "रस्त्याचे नाव (मराठी मध्ये) ",
    Landmarkmr: "लँडमार्क (मराठी मध्ये) ",
    villageNamemr: "Village Name (In Marathi) ",
    cityNamemr: "शहराचे नाव (मराठी मध्ये) ",

    // flatBuildingNo: 'फ्लॅट नंबर',
    // buildingName: 'अपार्टमेंट नाव',
    // roadName: 'रस्त्याचे नाव',
    // Landmark: 'लँडमार्क',
    // villageName: 'गावाचे नाव ',
    // cityName: 'शहराचे नाव',
    state: "राज्य (इंग्लिश मध्ये) ",
    statemr: "राज्य (मराठी मध्ये)  ",

    pincode: "पिन कोड",
    Religion1: "जन्माने धर्म",
    Religion2: "दत्तक घेऊन धर्म",
    StatusOfMarrige: "लग्नाच्या वेळची स्थिती",
    AgeDocument: "जन्म पुरावा कागदपत्र",
    IdDocument: "ओळख कागदपत्र ",
    residentialDocument: "रहिवाशी कागदपत्र",
    StatusOfDocument: "कागदपत्र स्थिती ",

    //groomFather
    firstNameF: "वडिलांचं प्रथम नाव  ",
    middleNameF: "वडिलांचं मधले नाव  ",
    lastNameF: "वडिलांचं शेवटचे नाव  ",
    AgeF: "वडिलांच वय",
    mobileNoF: "वडिलांचं दूरध्वनी क्रमांक",
    AadharNoF: "वडिलांचं आधार नंबर",

    //groomMother
    firstNameM: "आईचे प्रथम नाव  ",
    middleNameM: "आईचे मधले नाव  ",
    lastNameM: "आईचे शेवटचे नाव  ",
    AgeM: "आईचे वय",
    mobileNoM: "आईचे दूरध्वनी क्रमांक",
    AadharNoM: "आईचे आधार नंबर",

    //prist
    placeofMarriage: "लग्नाचे ठिकाण (इंग्लिश मध्ये)",
    pplaceofMarriage: "लग्नाचे ठिकाण ",
    placeofMarriage1: "लग्नाचे ठिकाण (मराठी मध्ये) ",

    //witness
    address: "पत्ता (इंग्लिश मध्ये)",
    addressMr: "पत्ता (मराठी मध्ये)",
    wRelation: "साक्षीदारशी नाते",
    wDocument: "साक्षीदाराचे कागदपत्र",
    witnessAdd: "साक्षीदार जोडा",

    //Document

    DBProof: "जन्म पुरावा कागदपत्र",
    ResProof: "रहिवासाचा पुरावा",
    IdProof: "ओळखपत्र पुरावा",

    DBProof1: "प्रथम साक्षीदार जन्म पुरावा कागदपत्र",
    DBProof2: "द्वितीय साक्षीदार जन्म पुरावा कागदपत्र",
    DBProof3: "तृतिय साक्षीदार जन्म पुरावा कागदपत्र",

    ResProofW1: "प्रथम साक्षीदार रहिवासाचा पुरावा",
    ResProofW2: "द्वितीय साक्षीदार रहिवासाचा पुरावा",
    ResProofW3: "तृतिय साक्षीदार रहिवासाचा पुरावा",
    marrigeRelatedDoc: "विवाह संबंधित दस्तऐवज",

    invetaionCard:
      "मूळ प्रत लग्नपत्रिका / प्रतिज्ञापत्र हे १०० च्या स्टॅम्प वर",
    marrigePhotoC: "विवाह छायाचित्र ",
    marDrf: "१०० रुपयांच्या स्टॅम्प पेपरवर अर्जाचा मसुदा तयार करा",

    DivorcePaperg: "वरचे वैध घटस्फोट कागद ",
    DeathCg: "मागील जोडीदाराचा मृत्यू प्रमाणपत्र",

    DivorcePaperb: "वधुचे वैध घटस्फोट कागद ",
    DeathCb: "मागील जोडीदाराचा मृत्यू प्रमाणपत्र",

    certiByReligiousPlc:
      " मंदिर, मशीद इ. धार्मिक स्थळाद्वारे जारी केलेले प्रमाणपत्र",
    docFormat:
      " (फक्त jpg.jpeg.png.bmp.pdf फाइल अपलोड करण्याची परवानगी आहे. फोटो आकार कमाल 10 MB)",
    enterDoc: "दस्तऐवजाच नाव ",

    //board

    applicantName: "अर्जदाराचे नाव :",
    boardNameT: "विवाह मंडळचे नाव",
    boardName: "विवाह मंडळचे नाव (इंग्लिश मध्ये) ",
    boardNamemr: "विवाह मंडळचे नाव (मराठी मध्ये) ",
    oldBoardCertificate: "कृपया जुने विवाह मंडळाचे प्रमाणपत्र अपलोड करा",
    aadharCardMod: "कृपया आधार कार्ड अपलोड करा",
    panCardMod: "कृपया पॅन कार्ड अपलोड करा",
    boardOrganizationPhotoMod: "कृपया मंडळ संस्थेचा फोटो अपलोड करा",
    boardHeadPersonPhotoMod: "कृपया मंडळाच्या प्रमुख व्यक्तीचा फोटो अपलोड करा",
    remark: "शेरा",
    documentList: "दस्तऐवज यादी",
    ValidtyofMBR: "विवाह मंडळाची अंतिम वैधता",
    documentsUploadF: "दस्तऐवज अपलोड",
    TandC: "",
    //button
    back: "मागे",
    next: "पुढे",
    add: "जोडा",
    save: "जतन करा",
    update: "अद्यायावत करा",
    clear: "रिक्त",
    exit: "बाहेर पडा",
    submit: "प्रस्तुत करणे",
    addFile: "फाइल जोडा",

    //table filed
    srNo: "अनुक्रमांक",
    actions: "क्रिया ",
    hName: "वरचे नाव",
    wName: "वधूचे नाव",
    ApplicantName: "अर्जदाराचे नाव",

    //brudcrum
    newMarriageRegistration: "विवाह नोंदणी / नवीन विवाह नोंदणी ",
    BoardMarriageRegistration: "विवाह मंडळ नोंदणी / नवीन विवाह मंडळ नोंदणी ",

    //module: 'शहर नियोजन',
    dashboard: "पिंपरी-चिंचवड महानगरपालिका डॅशबोर्ड",
    // master: 'मास्टर्स',
    // transactions: 'व्यवहार',
    // report: 'अहवाल',
    // masterPath: 'शहर नियोजन/ मास्टर ',
    // transactionPath: 'शहर नियोजन/ व्यवहार ',
    // reportPath: 'शहर नियोजन/ अहवाल ',

    // //breadcrum
    // landReservationPath: 'शहर नियोजन/ मास्टर / जमीन आरक्षण',
    // tdrZoneGatAndVillageMappingPath:
    //   'शहर नियोजन/ मास्टर / टीडीआर प्रभाग-गट आणि गाव मॅपिंग',
    // villageWiseLandReservationEntryPath:
    //   'शहर नियोजन/ मास्टर / गावनिहाय जमीन आरक्षण नोंद',
    // villageMappingWithDesignationPath:
    //   'शहर नियोजन/ मास्टर / पदनामासह गाव मॅपिंग',

    // //titles
    // landReservation: 'जमीन आरक्षण',
    // tdrZoneGatAndVillageMapping: 'टीडीआर प्रभाग-गट आणि गाव मॅपिंग',
    // villageWiseLandReservationEntry: 'गावनिहाय जमीन आरक्षण नोंद',
    // villageMappingWithDesignation: 'पदनामासह गाव मॅपिंग',

    // //other labels
    // landReservationID: 'जमीन आरक्षण क्र',
    // reservationName: 'आरक्षणाचे नाव',
    // reservationNameEng: 'आरक्षणाचे नाव इंग्रजीत',
    // reservationNameMr: 'आरक्षणाचे नाव मराठीत',
    // surveyNumber: 'सर्वेक्षण क्र',
    // landReservationLegend: 'जमीन आरक्षण आख्यायिका',
    // reservationAreaInHector: 'हेक्टर मध्ये आरक्षण क्षेत्र',
    // landInPossession: 'ताब्यात जमीन',
    // remark: 'टिप्पणी',
    // villageName: 'गावाचे नाव',
    // gatName: 'गटाचे नाव',
    // zoneName: 'झोनचे नाव',
    // landReservationName: 'जमीन आरक्षण नाव',
    // citySurveyNo: 'शहर सर्वेक्षण क्र',
    // reservationNo: 'आरक्षण क्र',
    // landNotInPossessionInHector: 'ताब्यात नसलेली जमीन (हेक्टरमध्ये)',
    // landInPossessionInHector: 'ताब्यात जमीन (हेक्टरमध्ये)',
    // ddtp: 'डी.डी.टी.पी',
    // deAndTp: 'उपअभियंता /नगर नियोजक',
    // atpAndJe: 'सहाय्यक नगर नियोजक /कनिष्ठ अभियंता',

    // attachFile: 'फाईल जोडा',
    // srNo: 'अनु क्र',
    // actions: 'क्रिया ',

    // //buttons
    // add: 'जोडा',
    // save: 'जतन करा',
    // update: 'अद्यायावत करा',
    // clear: 'रिक्त',
    // exit: 'बाहेर पडा',
    // back: 'मागे',
    // saveAndNext: 'जतन करा आणि पुढे',
    // finish: 'समाप्त',

    //ReIssuance of Marriage Certificate

    onlyRIMC: "विवाह प्रमाणपत्र पुन्हा जारी करणे",
    mRegNo: "विवाह रजि क्र",
    marriageDate: "लग्नाची तारीख",
    marriageYear: "लग्नाचे वर्ष",
    brideName: "वधूचे नाव",
    groomName: "वराचे नाव",
    regDate: "नोंदणी दिनांक",

    //Renewal of Marriage Board Registration
    onlyRMBR: "विवाह मंडळ नोंदणीचे नूतनीकरण",
    mbrName: "विवाह मंडळ नोंदणी नाव",
    mbrDate: "विवाह मंडळ नोंदणी तारीख",
    mbrYear: "विवाह मंडळ नोंदणी वर्ष",
    search: "शोधा",

    //Application Details

    onlyApplDetail: "अर्ज तपशील",
    applFName: "अर्जदाराचे पहिले नाव",
    applMName: "अर्जदाराचे मधले नाव",
    applLName: "अर्जदार शेवटचे नाव",
    groomFName: "वराचे पहिले नाव",
    groomMName: "वराचे मधले नाव",
    groomLName: "वराचे शेवटचे नाव",
    brideFName: "वधूचे पहिले नाव",
    brideMName: "वधू मधले नाव",
    brideLName: "वधू शेवटचे नाव",
    mDate: "लग्नाची तारीख",
    gFullName: "वराचे पूर्ण नाव",
    bFullName: "वधूचे पूर्ण नाव",

    //ReIssuance of marriage Certificate
    newRMItable: "विवाह प्रमाणपत्र पुन्हा जारी करणे",
    applFullName: "अर्जदाराचे पूर्ण नाव",
    applicationNo: "अर्ज क्र",
    applicationDate: "अर्ज तारीख",
    onlyMMBR: "विवाह मंडळ नोंदणीमध्ये बदल",
    statusDetailsMr: "स्थिती तपशील (मराठी मध्ये)",
    relationMr: "संबंध/नाते (मराठी मध्ये)",
    relationEng: "संबंध/नाते (इंग्रजी मध्ये)",
    durationFrom: "या पासून कालावधी",
    durationTo: " या कालावधीपर्यंत",
    chargeType: "चार्ज प्रकार",
    chargeTypeMr: "चार्ज प्रकार(मराठी मध्ये)",
    chargeName: "शुल्काचे नाव",
    chargeNameMr: "शुल्काचा प्रकार (मराठी मध्ये)",
    serviceId: "सेवा आयडी",
  },
};
