export default {
  en: {
    //labels
    officeNameOrElectoralWard: "Electoral ward",
    departmentName: "Department Name",
    committeeName: "Committee Name",
    financialYear: "Financial Year",
    docketType: "Docket Type",
    subjectSerialNumber: "Subject Serial Number",
    subjectDate: "Subject Date",
    approvedDate: "Approved Date",
    subject: "Subject",
    description: "Description",
    attachment: "Attachment",
    subjectStatus: "Subject Status",
    subjectSummary: "Subject Summary",
    subjectDetails: "Subject Details",
    amount: "Amount (₹)",
    remark: "Remark",
    outwardNumber: "Outward Number",
    outwardDate: "Outward Date",
    inwardNumber: "Inward Number",
    inwardDate: "Inward Date",
    fromDate: "From Date",
    toDate: "To Date",
    agendaNo: "Agenda No.",
    agendaDate: "Agenda Date",
    committeeMemberName: "Name of Committee Member",
    attendanceMethod: "Attendance captured from",
    proceedingDate: "Proceeding Date",
    onHoldSubjects: "On Hold Subjects",
    nameOfSuchak: "Name of Proposer",
    nameOfAnumodak: "Name of Seconder",
    month: "Month",
    year: "Year",
    ward: "Ward",
    corporatorName: "Name of Corporator",
    captureAttendance: "Get Attendance for this month",
    fixedAmountPerMonth: "Fixed Amount (Per Month) (₹)",
    amountForMeetingAttendedInTheMonth:
      "Amount for Meeting Attended in the Month (₹)",
    deductedOtherAmount: "Deducted Other Amount (₹)",
    healthInsuranceCharges: "Health Insurance Charges (₹)",
    grandTotal: "Grand Total (₹)",
    dateOfHonorariumProcess: "Date of Honorarium Process",
    firstNameEn: "First Name (in English)",
    middleNameEn: "Middle Name (in English)",
    lastNameEn: "Last Name (in English)",
    firstNameMr: "First Name (in Marathi)",
    middleNameMr: "Middle Name (in Marathi)",
    lastNameMr: "Last Name (in Marathi)",
    gender: "Gender",
    religion: "Religion",
    caste: "Caste",
    electedWard: "Elected Ward",
    dateOfBirth: "Date of Birth",
    casteCertificateNo: "Caste Certificate No.",

    idProofCategory: "ID Proof Category",
    panNo: "PAN No",
    idProofNo: "ID Proof No.",
    mobileNo: "Mobile No",
    emailAddress: "Email Address",
    address: "Address",
    addressEn: "Address In English",
    addressMr: "Address In Marathi",
    electedDate: "Elected Date",
    monthlyHonorariumAmount: "Monthly Honorarium Amount",
    resignDate: "Resign Date",
    reason: "Reason",
    reasonEn: "Reason In English",
    reasonMr: "Reason In Marathi",
    bankName: "Bank Name",
    branchName: "Branch Name",
    savingAccountNo: "Saving's Account No.",
    bankIFSCcode: "Bank IFSC Code",
    bankMICRcode: "Bank MICR Code",
    fullName: "FullName",
    nominatedCorporator: "Nominated Corporator",

    search: "Search",
    preview: "Preview ",
    preview_Edit: "Preview & Edit",
    addFile: "Upload File",
    srNo: "Sr. No",
    actions: "Actions",

    //buttons
    add: "Add",
    save: "Save",
    update: "Update",
    clear: "Clear",
    exit: "Exit",
    back: "Back",
    saveAndNext: "Save & Next",
    finish: "Finish",
    print: "Print",
    send: "Send",
    close: "Close",

    /////////////////////////////////////////////
    docketId: "Docket Id",
    /////////////////////////////////////////////
    departmentId: "Department Id",
    subjectId: "Subject Id",
    inwardDate: "Inward Date",
    prepareAgenda: "PREPARE AGENDA",
    selectCommitteeName: "Select Committee Name",
    agendaSubject: "Agenda Subject",
    agendaOutwardDate: "Agenda Outward Date",
    coveringLetterSubject: "Covering Letter Subject",
    coveringLetterNote: "Covering Letter Note",
    agendaDescription: "Agenda Description",
    tip: "Tip",
    sabhavruttant: "Sabhavruttant",
    btnSaveText: "SAVE",
    selectDockets: "Select Dockets",

    ////////////// Masters///////////////////////////
    defineCommitteeTitle: "",
    nominatedCorporator: "Nominated Corporator",
    selectCommittee: "Select Committee",
    nominatedChairperson: "Nominated as Chairperson",
    wardName: "Ward Name",
    electedWardName: "Elected Ward Name",
    castCertificateNo: "Caste Certificate No",
    amountDecidedPerMeeting: "Amount Decided /Meeting",
    monthlyMaximumLimitForCommittee: "Monthly Max Limit of Committee",
    memberChange: "Member Change",
    reasonForChange: "Reason For Change",
    srNo: "Sr.No",
    defineCorporator: "CORPORATOR MASTER",
    bankDetails: "Bank Details",
    defineCommittee: "COMMITTEE MASTER",
    nameOfCommitee: "Name Of Committee (In English)",
    nameOfCommiteeMr: "Name Of Committee (In Marathi)",
    countOfCommitee: "Count of Committee Members",
    addCommittee: "Add Committee",
    defineCommitteeEstablishment: "COMMITTEE ESTABLISHMENT MASTER",
    committeeEstablishedDate: "Committee Establishment Date",
    committeeDismissedDate: "Committee Dismissed Date",
    honorariumPerMeeting: "Honorarium Per Meeting (₹)",
    workingNotWorking: "Working/Not Working",

    /////////////////////////////// NEW LABELS ADDED BY ANWAR ANSARI////////////////////////////////
    newDocketEntry: "NEW DOCKET ENTRY",
    additionalDocketEntry: "ADDITIONAL DOCKET ENTRY",
    sendAgendaOnEMail: "SEND AGENDA ON E-MAIL",
    attendance: "ATTENDANCE",
    outwardNo: "Outward Number",
    inwardNo: "Inward No",
    tahkubNotice: "Tahkub Notice",
    meetingTime: "Meeting Time",
    newMeetingDate: "New Meeting Date",
    currentMeetingPlace: "Current Meeting Place",
    meetingPlace: "Meeting Place",
    previousMeetingDate: "Previous Meeting Date",
    meetingReschedule: "MEETING RESCHEDULE",
    calender: "Calendar",
    printPreview: "Print Preview",
    submitData: "Submit Data",
    closeModal: "Close Modal",
    meetingSchedule: "MEETING SCHEDULE",
    meetingDate: "Meeting Date",
    proceeding: "PROCEEDING",
    additionalDocket: "Add Additional Docket",
    reference: "Department File Reference Number",
    nameOfPresident: "Name Of President",
    selectCommittees: "Select Committees",
    budgetHead: "Budget Head",
    approverName: "Approver's Name",
    approverDepartment: "Approver's Department",
    approverDesignation: "Approver's Designation",
    agendaOutwardNo: "Agenda Outward Number",

    /////////////////////////////////////////////
    selectedCommittees: "Selected Committees",
    meetingScheduled: "Meeting Scheduled",

    honorariumChargeMaster: "HONORARIUM CHARGE MASTER",

    personalDetails: "PERSONAL DETAILS",

    identificationProofDocumentTable: "Identification Proof Document",
    identificationProofDocument: "Identification Proof Document (In English)",
    identificationProofDocumentMr: "Identification Proof Document (In Marathi)",
    defineIdentificationProof: "IDENTIFICATION PROOF MASTER",

    defineOffice: "DEFINE OFFICE MASTER",

    zoneName: "Zone Name",
    officeName: "Office Name",
    officeNameEn: "Office Name (In English)",
    officeNameMr: "Office Name (In Marathi)",

    officeAddress: "Office Address",
    officeAddressEn: "Office Address (In English)",
    officeAddressMr: "Office Address (In Marathi)",

    officeType: "Office Type",
    officeTypeEn: "Office Type (In English)",
    officeTypeMr: "Office Type (In Marathi)",

    gisId: "GIS ID / GEO CODE",
    latitude: "Latitude",
    longitude: "Longitude",

    defineStatesAndCity: "DEFINE STATE AND CITY MASTER",

    state: "State Name",
    stateEn: "State Name (In English)",
    stateMr: "State Name (In Marathi)",

    city: "City Name",
    cityEn: "City Name (In English)",
    cityMr: "City Name (In Marathi)",

    defineParty: "PARTY MASTER",

    partyName: "Party Name",
    partyNameEn: "Party Name (In English)",
    partyNameMr: "Party Name (In Marathi)",

    defineCommitteeMembers: "COMMITTEE MEMBER MASTER",
    nominatedAsChairperson: "Nominated As Chairperson",
    selectCorporator: "Select Corporator",

    fixedAmount: "Fixed Amount (₹)",
    amountDecidedPerMeeting: "Amount Decided Per Meeting (₹)",

    attendees: "ATTENDEES",
    MOM: "MINUTES OF MEETING",
    proceedingReport: "PROCEEDING REPORT",

    editableSection: "EDITABLE SECTION",

    status: "Status",
    committeEstablishment: "COMMITTEE ESTABLISHMENT",
    listOfCorporators: "LIST OF CORPORATORS",

    CorporatorsHonorariumAndAllowances: "CORPORATORS HONORARIUM AND ALLOWANCES",

    allowancePerMeeting: "Allowance Per Meeting",
    generalBodyMeetingCount: "General Body Meeting Count",
    maxLimitOfAllowanceInMonth: "Max-Limit Of Allowance In Month",
    standingCommiotteeCount: "Standing Committee Count",
    totalAttendanceCount: "Total Attendance Count",

    honorariumLetter: "HONORARIUM LETTER",

    AddAdditionalDocketSection: "ADD ADDITIONAL DOCKET SECTION",

    meetingAttentedAmount: "Meeting Attented Amount (₹)",
    mobileCharges: "Mobile Charges (₹)",

    honorariumProcess: "HONORARIUM PROCESS",

    totalCount: "Total Attendance Count for this month",
    dateAndDay: "Day And Date",
    honorariumProcessDate: "Honorarium Process Date",

    // //////////////
    committeName: "Committe Name",

    documentSection: "DOCUMENT SECTION",
    markAttendance: "MARK ATTENDANCE",

    thisFieldIsrequired: "This field is required!",

    // ///////////////////////////
    Initiated: "Initiated",
    InProcess: "InProcess",
    Reassigned: "Reassigned",
    Freezed: "Freezed",
    Approved: "Approved",
    OnHold: "OnHold",

    // //////////////////////////
    invalidEmailFormat: "Invalid Email Format",
    newDocketEntryOnHodLogin: "Approval New Docket Entry",
    newDocketEntryOnSecretaryLogin: "Final Approval New Docket Entry",

    ////////////////////////////
    historyTable: "History Table Section",
    senderName: "Sender Name",
    senderDepartment: "Sender Department",
    senderDesignation: "Sender Designation",
    sentDateTime: "Sent Date Time",
    senderRemark: "Sender Remark",
    //
    circulateTahkubNotice: "Circulate Tahkub Notice",
    priority: "Priority",
    aadharNo: "Aadhar Number",
    prapatra: "PRAPATRA",

    // VALIDATION MESSAGES
    countOfCommitteeMembersMessage:
      "countOfCommitteeMembers must be a valid number",
  },
  mr: {
    //labels
    officeNameOrElectoralWard: "निवडणूक प्रभाग",
    departmentName: "विभागाचे नाव",
    committeeName: "समितीचे नाव",
    financialYear: "आर्थिक वर्ष",
    docketType: "विषयपत्राचा प्रकार",
    subjectSerialNumber: "विषय अनुक्रमांक",
    subjectDate: "विषयाची तारीख",
    approvedDate: "मंजूर तारीख",
    subject: "विषय",
    description: "वर्णन",
    attachment: "संलग्नक",
    subjectStatus: "विषय स्थिती",
    subjectSummary: "विषयपत्राचा आशय",
    subjectDetails: "विषयपत्राचा तपशील",
    amount: "रक्कम (₹)",
    remark: "टिप्पणी",
    outwardNumber: "बाह्य क्र.",
    outwardDate: "बाह्य तारीख",
    inwardNumber: "आवक क्र.",
    inwardDate: "आवक तारीख",
    fromDate: "या तारखेपासून",
    toDate: "या तारखेपर्यंत",
    agendaNo: "कार्यपत्रिका क्रमांक",
    agendaDate: "कार्यपत्रिका तारीख",
    committeeMemberName: "समिती सदस्याचे नाव",
    attendanceMethod: "उपस्थितीची पद्धत",
    proceedingDate: "प्रक्रिया तारीख",
    onHoldSubjects: "होल्डवरचे विषय",
    nameOfSuchak: "प्रस्तावकाचे नाव",
    nameOfAnumodak: "अनुमोदकाचे नाव",
    month: "महिना",
    year: "वर्ष",
    ward: "वार्ड",
    corporatorName: "नगरसेवकाचे नाव",
    captureAttendance: "या महिन्यातील एकूण उपस्थिती मिळवा",
    fixedAmountPerMonth: "निश्चित रक्कम (प्रति महिना)",
    amountForMeetingAttendedInTheMonth:
      "महिन्यातील उपस्थित मीटिंगची कमाल रक्कम",
    deductedOtherAmount: "इतर कपात केलेली रक्कम (₹)",
    healthInsuranceCharges: "आरोग्य विमा शुल्क (₹)",
    grandTotal: "एकूण रक्कम (₹)",
    dateOfHonorariumProcess: "मानधन प्रक्रियेची तारीख",
    firstNameEn: "पहिले नाव (इंग्रजीत)",
    middleNameEn: "मधले नाव (इंग्रजीत)",
    lastNameEn: "शेवटचं नाव (इंग्रजीत)",
    firstNameMr: "पहिले नाव (मराठीत)",
    middleNameMr: "मधले नाव (मराठीत)",
    lastNameMr: "शेवटचं नाव (मराठीत)",
    gender: "लिंग",
    religion: "धर्म",
    caste: "जात",
    electedWard: "निवडून आलेला प्रभाग",
    dateOfBirth: "जन्मतारीख",
    casteCertificateNo: "जात प्रमाणपत्र क्र.",

    idProofCategory: "आयडी प्रूफ श्रेणी",
    panNo: "पॅन क्रं",
    idProofNo: "आयडी प्रूफ क्र.",
    mobileNo: "मोबाईल नं",
    emailAddress: "इमेल पत्ता",
    address: "पत्ता",
    addressEn: "पत्ता (इंग्रजीत)",
    addressMr: "पत्ता (मराठीत)",
    electedDate: "निवडलेली तारीख",
    monthlyHonorariumAmount: "मासिक मानधन रक्कम",
    resignDate: "राजीनाम्याची तारीख",
    reason: "कारण",
    reasonEn: "कारण (इंग्रजीत)",
    reasonMr: "कारण (मराठीत)",
    bankName: "बँकेचे नाव",
    branchName: "शाखेचे नाव",
    savingAccountNo: "बचत खाते क्र.",
    bankIFSCcode: "बँक आयएफएससी कोड",
    bankMICRcode: "बँक एमआयसीआर कोड",
    nominatedCorporator: "नामनिर्देशित नगरसेवक",

    search: "शोधा",
    preview: "पूर्वावलोकन",
    preview_Edit: "पूर्वावलोकन आणि संपादित करा",
    addFile: "फाइल जोडा",
    srNo: "अनु क्र",
    actions: "क्रिया ",
    fullName: "पूर्ण नाव",

    //buttons
    add: "जोडा",
    save: "जतन करा",
    update: "अद्यायावत करा",
    clear: "साफ करा",
    exit: "बाहेर पडा",
    back: "मागे",
    saveAndNext: "जतन करा आणि पुढे",
    finish: "समाप्त",
    print: "छापणे",
    send: "पाठवा",
    close: "बंद करा",

    ///////////////////////////////////////////
    docketId: "डॉकेट आयडी",
    /////////////////////////////////////////////
    departmentId: "विभाग आयडी",
    subjectId: "विषय आयडी",
    inwardDate: "आवक तारीख",
    prepareAgenda: "कार्यपत्रिका तयार करा",
    selectCommitteeName: "समितीचे नाव निवडा",
    agendaSubject: "कार्यपत्रिका विषय",
    agendaOutwardDate: "कार्यपत्रिका जावक तारीख",
    coveringLetterSubject: "आवरण पत्राचा विषय",
    coveringLetterNote: "कव्हरिंग लेटर नोट",
    agendaDescription: "कार्यपत्रिका वर्णन",
    tip: "टीप",
    sabhavruttant: "सर्वज्ञ",
    btnSaveTextMr: "जतन करा",
    selectDockets: "डॉकेट निवडा",

    ////////////// Masters///////////////////////////
    defineCommitteeTitle: "समिती सदस्यांची व्याख्या करा",
    nominatedCorporator: "नामनिर्देशित नगरसेवक",
    selectCommittee: "निवड समिती",
    nominatedChairperson: "अध्यक्ष म्हणून नामनिर्देशित केले",
    wardName: "प्रभागाचे नाव",
    electedWardName: "निवडून आलेल्या प्रभागाचे नाव",
    castCertificateNo: "जात प्रमाणपत्र क्र",
    amountDecidedPerMeeting: "ठरलेली रक्कम/बैठक",
    monthlyMaximumLimitForCommittee: "समितीची मासिक कमाल मर्यादा",
    memberChange: "सदस्य बदल",
    reasonForChange: "बदलाचे कारण",
    srNo: "अनु. क्र",
    defineCorporator: "नगरसेवक मास्टर",
    bankDetails: "बँक तपशील",
    defineCommittee: "समिती मास्टर",
    nameOfCommitee: "समितीचे नाव",
    nameOfCommiteeMr: "समितीचे नाव (मराठी)",
    countOfCommitee: "समिती सदस्यांची संख्या",
    addCommittee: "समिती जोडा",
    defineCommitteeEstablishment: "समिती स्थापना मास्टर",
    committeeEstablishedDate: "समिती स्थापनेची तारीख",
    committeeDismissedDate: "समिती बरखास्त तारीख",
    honorariumPerMeeting: "प्रति बैठक मानधन (₹)",
    workingNotWorking: "कार्यरत/काम करत नाही",

    /////////////////////////////// NEW LABELS ADDED BY ANWAR ANSARI////////////////////////////////
    newDocketEntry: "विषयपत्र तयार करा",
    additionalDocketEntry: "अतिरिक्त डॉकेट तयार करा",
    sendAgendaOnEMail: "अजेंडा इमेल वर पाठवा",
    attendance: "हजेरी",
    outwardNo: "जावक क्रमांक",
    inwardNo: "आवक क्रमांक",
    tahkubNotice: "तहकूब नोटीस",
    meetingTime: "सभेची वेळ",
    newMeetingDate: "नवीन सभेची दिनांक",
    currentMeetingPlace: "वर्तमान सभेचे ठिकाण",
    meetingPlace: "सभेचे ठिकाण",
    previousMeetingDate: "मागील सभेची दिनांक",
    meetingReschedule: "मीटिंग री-शेड्यूल",
    calender: "कॅलेंडर",
    printPreview: "प्रिंट पूर्वावलोकन",
    submitData: "डेटा सबमिट करा",
    closeModal: "मोडल बंद करा",
    meetingSchedule: "सभेचे वेळापत्रक",
    meetingDate: "सभेची दिनांक",
    proceeding: "प्रोसिडिंग",
    additionalDocket: "अतिरिक्त डॉकेट जोडा",
    reference: "विषयपत्र संदर्भ क्रमांक",
    nameOfPresident: "अध्यक्षाचे नाव",
    selectCommittees: "समिती निवडा",
    budgetHead: "लेखाशिर्ष निवडा",
    approverName: "अधिका-याचे नांव",
    approverDepartment: "विभाग",
    approverDesignation: "पदनाम",
    agendaOutwardNo: "अजेंडा जावक क्रमांक",

    /////////////////////////////////////////////
    selectedCommittees: "निवडलेल्या समित्या",
    meetingScheduled: "बैठक शेड्यूल केली",

    honorariumChargeMaster: "मानधन शुल्क मास्टर",

    personalDetails: "वैयक्तिक माहिती",

    identificationProofDocumentTable: "ओळख पुरावा दस्तऐवज",
    identificationProofDocument: "ओळख पुरावा दस्तऐवज (इंग्रजीत)",
    identificationProofDocumentMr: "ओळख पुरावा दस्तऐवज (मराठीत)",
    defineIdentificationProof: "ओळख पुरावा मास्टर",

    defineOffice: "ऑफिस मास्टरची व्याख्या करा",

    zoneName: "झोनचे नाव",
    officeName: "कार्यालयाचे नाव",
    officeNameEn: "कार्यालयाचे नाव (इंग्रजीत)",
    officeNameMr: "कार्यालयाचे नाव (मराठीत)",

    officeAddress: "कार्यालयाचा पत्ता",
    officeAddressEn: "कार्यालयाचा पत्ता (इंग्रजीत)",
    officeAddressMr: "कार्यालयाचा पत्ता (मराठीत)",

    officeType: "कार्यालय प्रकार",
    officeTypeEn: "कार्यालय प्रकार (इंग्रजीत)",
    officeTypeMr: "कार्यालय प्रकार (मराठीत)",

    gisId: "जीआयएस आयडी / जिओ कोड",
    latitude: "अक्षांश",
    longitude: "रेखांश",

    defineStatesAndCity: "राज्य आणि शहर मास्टर परिभाषित करा",

    state: "राज्याचे नाव",
    stateEn: "राज्याचे नाव (इंग्रजीत)",
    stateMr: "राज्याचे नाव (मराठीत)",

    city: "City Name",
    cityEn: "City Name (इंग्रजीत)",
    cityMr: "City Name (मराठीत)",

    defineParty: "पक्ष मास्टर",

    partyName: "पक्षाचे नाव",
    partyNameEn: "पक्षाचे नाव (इंग्रजीत)",
    partyNameMr: "पक्षाचे नाव (मराठीत)",

    defineCommitteeMembers: "समिती सदस्य मास्टर",
    nominatedAsChairperson: "चेअरपर्सन म्हणून नामनिर्देशित केले",
    selectCorporator: "नगरसेवक निवडा",

    fixedAmount: "निश्चित रक्कम (₹)",
    amountDecidedPerMeeting: "प्रति मीटिंग ठरवलेली रक्कम (₹)",

    attendees: "उपस्थित समिती सदस्य",
    MOM: "सभेचे इतिवृत्तांत",
    proceedingReport: "कार्यवाही अहवाल",

    editableSection: "संपादनीय विभाग",
    status: "स्थिती",

    committeEstablishment: "समितीची स्थापना",
    listOfCorporators: "नगरसेवकांची यादी",

    CorporatorsHonorariumAndAllowances: "नगरसेवकांचे मानधन आणि भत्ते",

    allowancePerMeeting: "प्रति बैठक भत्ता",
    generalBodyMeetingCount: "सर्वसाधारण सभेची संख्या",
    maxLimitOfAllowanceInMonth: "महिन्यातील भत्त्याची कमाल-मर्यादा",
    standingCommiotteeCount: "स्थायी समिती गण",
    totalAttendanceCount: "एकूण उपस्थिती संख्या",

    honorariumLetter: "मानधन पत्र",

    AddAdditionalDocketSection: "अतिरिक्त डॉकेट जोडा विभाग ",

    meetingAttentedAmount: "समिती बैठक उपस्थिती रक्कम (₹)",
    mobileCharges: "मोबाईल चार्जेस (₹)",

    honorariumProcess: "मानधन प्रक्रिया",
    totalCount: "महिन्यातील एकूण उपस्थीती संख्या",
    dateAndDay: "दिवस आणि तारीख",
    honorariumProcessDate: "मानधन प्रक्रियेची तारीख",

    // ///
    committeName: "समितीचे नाव",

    documentSection: "दस्तऐवज विभाग",
    markAttendance: "उपस्थिती चिन्हांकित करा",

    thisFieldIsrequired: "कृपया हे भरणे आवश्यक आहे!",

    // ///////////////////////////
    Initiated: "प्राथमिक स्वरूपाचे",
    InProcess: "प्रगतीपथावर आहे",
    Reassigned: "परत पाठविणे",
    Freezed: "फ्रीज करणे",
    Approved: "मंजूर",
    OnHold: "स्थगित करणे",

    // //////////////////////////
    invalidEmailFormat: "अवैध ईमेल स्वरूप",

    newDocketEntryOnHodLogin: "नवीन डॉकेट मंजूर करा",
    newDocketEntryOnSecretaryLogin: "नवीन डॉकेट अंतिम मंजुरी",

    ////////////////////////////
    historyTable: "इतिहास सारणी विभाग",
    senderName: "पाठवणाऱ्याचे नाव",
    senderDepartment: "पाठवणाऱ्याचे विभाग",
    senderDesignation: "पाठवणाऱ्याचे पदनाम",
    sentDateTime: "पाठवण्याची तारीख वेळ",
    senderRemark: "पाठवणाऱ्याची टिप्पणी",

    // //////////////////////////
    circulateTahkubNotice: "तहकूब नोटीस प्रसारित करा",
    priority: "प्राधान्य",
    aadharNo: "आधार क्रमांक",
    prapatra: "प्रपत्र",

    // VALIDATION MESSAGES
    countOfCommitteeMembersMessage:
      "समिती सदस्यांची संख्या वैध संख्या असणे आवश्यक आहे",
  },
}
