export default {
  en: {
    pressNoteDocx: "Press Note(in .docx/.xlsx/.xls/.jpeg/.png)",
    pressNotePdf: "Press Note(in .pdf)",
    requestDate: "Request Date And Time",
    edit: "EDIT",
    penaltyHeadsHeading: "Penalty Heads Master",
    pointNo: "Penalty Number",
    pointDescTable: "Penalty Description",
    pointDesc: "Penalty Description(in English)",
    pointDescMr: "Penalty Description(in Marathi)",
    rate: "Rate(In Rupees)",
    isFixed: "Is Fixed",
    previousRotationNumber: "Reference News Publish Request No.",
    budgetHeading: "Budget Master",
    financialYear: "Financial Year",
    budgetAmount: "Budget Amount",
    newsAgencyEn: "Newspaper Agency Name (In English)",
    newsAgencyMr: "Newspaper Agency Name (In Marathi)",
    newspaperNameEn: "News Paper Name (In English)",
    newspaperNameMr: "News Paper Name (In Marathi)",
    addressEn: "Address (In English)",
    addressMr: "Address (In Marathi)",
    accountDetails: "Account Details",
    newsRotation: "News Rotation",
    newsRotationRequestNumber: "News Rotation Request Number",
    newsAgency: "Newspaper Agency Name",
    newsp: "Newspaper",
    contact: "Contact Number",
    emailId: "Email Id",
    area: "Area",
    zone: "Zone Name",
    ward: "Ward",
    departmentName: "Department Name",
    advertisementType: "Advertisement Type",
    newsSubject: "Advertisement Subject",
    work: "Work Name",
    workCost: "Work Cost",
    tender: "Tender No",
    tenderCost: "Tender Amount",
    isSpecialNotice: "Special Notice",
    newsDescription: "Advertisement Description",
    groupName: "Rotation Group",
    rotationgroupNameE: "Rotation Group (In English)",
    rotationgroupNameM: "Rotation Group (In Marathi)",
    rotationgroupSubNameE: "Rotation Sub Group (In English)",
    rotationgroupSubNameM: "Rotation Sub Group (In Marathi)",
    subGroup: "Rotation Sub Group",
    paperLevel: "News Paper Level",
    newsTypes: "Type Of Advertisement",
    attachement: "Attachment",
    attachements: "Attachments",
    newsFromDate: "Advertisement Publish Date",
    newsFromDateTable: "Publish Date",
    publishDate: "Published Date",
    formateSize: "Standard Format Size",
    newsReleaseDate: "News Release Date",
    status: "Status",
    action: "Actions",
    attachNews: "Attach Advertisement",
    attachmentSchema: "*the maximum upload size is 2MB.",
    APPROVE: "APPROVE",
    newsAttachement: "Advertisement Attachment",
    papercutAttachement: "Paper Cut Attachements",
    newsPublish: "Advertisement Publish Request",

    vaccinationDate: "VaccinationDate",
    veterinaryDoctorsName: `Veterinary Doctor's Name`,
    documents: "Documents",
    vaccinationPDF: "Vaccination PDF",
    animalPhoto: "Animal Photo",
    remark: "Remark",
    status: "Status",
    petAnimalEn: "Pet Animal name in English",
    petAnimalMr: "Pet Animal name in Marathi",
    petBreed: "Pet Breed",
    breedNameEn: "Breed name in English",
    breedNameMr: "Breed name in Marathi",
    ownerPhotoID: "Owner ID Proof",
    makePayment: "Make Payment",
    generateLicense: "Generate License",
    licenseFor: "License For",
    pcmc: "Pimpri-Chinchwad Municipal Corporation",
    fiscalYear: "F.Y.",
    officeCopy: "OFFICE COPY",
    customerCopy: "CUSTOMER COPY",
    receiptNo: "Receipt No.",
    date: "Date",
    relatedTo: "Related To",
    cfcRefNo: "CFC Ref. No",
    cfcCounterNo: "CFC Counter No.",
    receivedFrom: "Received From",
    serviceName: "Service Name",
    narration: "Narration",
    address: "Address",
    paymentMode: "Payment Mode",
    rupees: "Rupees",
    chequeNo: "Cheque No.",
    chequeDate: "Cheque Date",
    bankName: "Bank Name",
    referenceNo: "Reference No.",
    applicationHis: "Application History",
    applicationDate: "Application Date",
    details: "Details",
    payableAmount: "Payable Amount",
    receivedAmount: "Received Amount",
    rebateAmount: "Rebate/Concession Amount",
    advanceAmount: "Advance Amount",
    actualPayableAmount: "Actual Payable Amount",
    totalAmount: "Total Amount",
    amountInWords: "Amount in Words",
    receiverSignature: `Receiver's Signature`,
    tip: "Tip",
    printBy: "Printed By",
    printDateAndTime: "Print Date and Time",
    casePaperNo: "Case Paper No.",
    licenseNo: "License No.",
    ownerAddress: "Owner Address",
    symptoms: "Symptoms",
    aknowledgementSlipNo: "Acknowledgement Slip No. (numeric)",
    diagnosisDetail: "Diagnosis Details",
    medicineDetails: "Medicine Details",
    treatment: "Treatment",
    payment: "Payment",
    payerName: "Payer Name",
    payerAddress: "Payer Address",
    receiptDate: "Receipt Date",
    transactionDate: "Transaction Date",
    treatmentCategory: "Treatment Category",
    casePaperDate: "Case Paper Date",
    accountGlCode: "GL Account Code",
    opd: "OPD",
    lattitude: "Lattitude",
    longitude: "Longitude",
    city: "City",
    state: "State",
    pincode: "Pincode",
    amount: "Amount",
    paymentType: "Payment Type",
    cfcCode: "CFC Code",
    ddNo: "Demand Draft's No.",
    ddDate: "Demand Draft's Date",
    branchName: "Branch Name",
    ifscCode: "IFSC Code",
    accountNo: "Account No.",
    newsOrAdvertisementRotationNo: "Advertisement Rotation No.",
    department: "Department",
    newsReleasingDate: "Advertisement Releasing Date",
    newsOrAdvertisementPublishedDate: "Advertisement Published Date",
    subject: "Subject",
    description: "Description",
    standardFormatSizeLabel: "Standard Format Size",
    publishStatus: "Publish Status",
    newsOrAdvertisementSqMeter: "Advertisement sq. meter",
    billAmount: "Bill Amount",
    billApprovalRemark: "Bill Approval Remark",
    attachment: "Attachment",
    fromDate: "From Date",
    toDate: "To Date",

    search: "Search",
    preview: "Preview",
    addFile: "Add File",
    srNo: "Sr. No",
    actions: "Actions",
    approve: "Approve",
    reassign: "Reassign",
    agreeAndNext: "Agree & Next",
    cancel: "Cancel",
    //buttons
    add: "Add",
    save: "Save",
    finalSubmit: "Final Submit",
    update: "Update",
    clear: "Clear",
    exit: "Exit",
    back: "Back",
    saveAndNext: "Save & Next",
    finish: "Finish",
    print: "Print",
    addDocuments: "Add Documents",
    fileUpload: "File Upload",
    ward: "Ward",
    REASSIGN: "Revert Back",
    newsRotationReqN: "Advertisement Rotation Request Number",
    newsRotationgrp: "Newspaper Rotation Group",

    /* press note  labels english */
    pressNoteNo: "Press Note No.",
    pressNoteReleasingDate: "Press Note Releasing Date",
    pressNoteSubject: "Press Note Subject",
    pressNoteDescription: "Press Note Description",
    pressNoteReleaseDate: "Press Note Release Date",
    pressNoteReleaseHeading: "Press Note Release Request",
    pressNoteRequestAddNew: "Add New",
    remarkModel: "Enter Remark on application",
    srNo: "Sr. No",
    /* news Type mst lables marathi */

    newsTypeHeading: "Advertisement Rotation Type",
    newsType: "Advertisement Rotation Type (In English)",
    newsTypeMr: "Advertisement Rotation Type (In Marathi)",

    /* advertisementType mst lables marathi */
    advertisementTypeHeading: "Advertisement Publish Type",
    advertisementType: "Advertisement Publish Type (In English)",
    advertisementTypeMr: "Advertisement Publish Type (In Marathi)",

    /* News Paper Level mst lables marathi */
    newsPaperLevelHeading: "News Paper Level",
    newsPaperLevel: "News Paper Level (In English)",
    newsPaperLevelMr: "News Paper Level (In Marathi)",

    addNew: "Add New",
    ChargeType: "Charge Type",
    chargeprefix: "Charge Type Prefix",
    chargeNameE: "Charge Name English",
    chargeNameM: "Charge Name Marathi",
    mapGi: "Map With Gl Account Code",

    /* Rate Chart mst lables marathi */
    rateChartHeading: "Rate Chart",
    newsPaperLevelDropDown: "News Paper Level",
    newsPaperDropDown: "News Paper",
    chargeType: "Charge Type",
    chargeAmount: "Amount (per Sq.CM)",
    RotationsubGroup: "Newspaper Rotation Sub Group",
    rotationMaping: "Rotation Group SubGroup NewsPaper NewsLevel Mapping",
    standardFormatSize: "Standard Format Size(in Sq.CM)",

    advirtiseMentInDocx:
      "Advertisement Attachment(in .docx/.xlsx/.xls/.jpg/.jpeg/.png)",
    advirtiseMentInPdf: "Advertisement Attachment(in .pdf)",

    //Event Management
    eventManagement: "Event Management",
    eventNumber: "Event Number",
    eventDate: "Event Date",
    eventTime: "Event Time",
    eventDescription: "Event Description",
    eventLocationLat: "Event Location Lat",
    eventLocationLong: "Event Location Long",

    //Budget Provision
    budgetProvision: "Budget Provision",
    billDescription: "Bill Description",
    newsPaperName: "News Paper Name",
    billAmount: "Bill Amount",
    budgetAmountAfterPreviousBillPaymentDeduction:
      "Budget Amount (After Previous Bill Payment Deduction)",
    budgetAmountAfterCurrentBillPaymentDeduction:
      "Budget Amount (After Current Bill Payment Deduction)",
    billApprovalDate: "Bill Approval Date",
    billApprovalOfficerName: "Bill Approval Officer Name",
    fileName: "File Name",
    fileType: "File Type",
    uploadBy: "Upload By",
    action: "Action",

    papercutting: "Paper Cutting Book",
    newsreqsearch: "Search Advertisement Request Number",
    newsreqNumber: "Advertisement Request Number",
    specialNotice: "Special Notice",

    enterPenaltyAmount: "Enter penalty amount",
    selectThisPenaltyFirst: "Select this penalty first",
    enterPenaltyDescription: "Enter penalty description",
    upload: "Upload",
    uploadedBy: "Uploaded By",
    id: "ID",
    newsPublishID: "News Publish ID",
    statusUpdateDate: "Status Update Date",
    noRemarkFound: "No remark found!",
  },
  mr: {
    applicationHis: "अर्जाचा इतिहास",
    pressNoteDocx: "प्रेस नोट (डॉक्स/एक्सेल फोर्मट मध्ये)",
    pressNotePdf: "प्रेस नोट (पीडीएफ फोर्मट मध्ये)",
    requestDate: "विनंती तारीख आणि वेळ",
    edit: "संपादित करा",
    penaltyHeadsHeading: "पेनल्टी हेड मास्टर",
    pointNo: "दंड क्रमांक",
    pointDescTable: "दंडाचे वर्णन",
    pointDesc: "दंडाचे वर्णन (इंग्रजीमध्ये)",
    pointDescMr: "दंडाचे वर्णन (मराठीत)",
    rate: "दर (रुपयामध्ये)",
    isFixed: "निश्चित आहे",
    previousRotationNumber: "संदर्भ जाहिरात विनंती क्रमांक",
    budgetHeading: "बजेट मास्टर",
    financialYear: "आर्थिक वर्ष",
    budgetAmount: "बजेट रक्कम रु",
    newsAgencyEn: "वृत्तपत्र एजन्सीचे नाव (इंग्लिश मध्ये)",
    newsAgencyMr: "वृत्तपत्र एजन्सीचे नाव (मराठी मध्ये)",
    newspaperNameEn: "वृत्तपत्राचे नाव (इंग्लिश मध्ये)",
    newspaperNameMr: "वृत्तपत्राचे नाव (मराठी मध्ये)",
    addressEn: "पत्ता (इंग्लिश मध्ये)",
    addressMr: "पत्ता (मराठी मध्ये)",
    accountDetails: "खाते तपशील",
    newsreqsearch: "जाहिरात विनंती क्रमांक शोधा",
    newsreqNumber: "जाहिरात विनंती क्रमांक",
    papercutting: "पेपर कटिंग बुक",
    standardFormatSizeLabel: "स्टैन्डर्ड फॉर्मेट आकार",
    rotationMaping: "रोटेशन ग्रुप सबग्रुप न्यूजपेपर मॅपिंग",
    ChargeType: "शुल्काचा प्रकार",
    chargeprefix: "शुल्काचा प्रकारचा उपसर्ग",
    chargeNameE: "शुल्काचा नाव इंग्लिशमध्ये ",
    chargeNameM: "शुल्काचा नाव मराठीमध्ये ",
    mapGi: "खाते कोडसह नकाशा",

    newsRotationgrp: "वृतपत्र रोटेशन ग्रुप",
    srNo: "अनु क्र",
    newsp: "वृत्तपत्र",
    contact: "संपर्क क्रमांक",
    newsAgency: "वृत्तपत्र एजन्सीचे नाव",
    remarkModel: "अर्जावर टिप्पणी प्रविष्ट करा",
    REASSIGN: "पुन्हा नियुक्त करा",
    APPROVE: "मंजूर करा",
    newsRotationReqN: "जाहिरात रोटेशन विनंती क्रमांक",
    ward: "प्रभाग",
    fileUpload: "अपलोड",
    cancel: "रद्द करा",
    addDocuments: "दस्तऐवज जोडा",
    newsRotation: "जाहिरात रोटेशन",
    newsRotationRequestNumber: "जाहिरात रोटेशन विनंती क्रमांक",
    departmentName: "विभागाचे नाव",
    advertisementType: "जाहिरातीचा प्रकार",
    newsSubject: "जाहिरातीचा विषय",
    work: "कामाचे नाव",
    workCost: "कामाची किमत",
    tender: "निविदा क्रमांक",
    tenderCost: "निविदा रक्कम",
    isSpecialNotice: "विशेष सूचना",
    newsDescription: "जाहिरातीचे वर्णन",
    groupName: "रोटेशन गटाचे नाव",
    rotationgroupNameE: "रोटेशन गट (इंग्लिशमध्ये)",
    rotationgroupNameM: "रोटेशन गट (मराठीमध्ये)",
    rotationgroupSubNameE: "रोटेशन उप गट (इंग्लिशमध्ये)",
    rotationgroupSubNameM: "रोटेशन उप गट (मराठीमध्ये)",
    subGroup: "रोटेशन उप गटाचे नाव",
    RotationsubGroup: "वृतपत्र रोटेशन उप गटाचे नाव",
    paperLevel: "वृत्तपत्र पातळी",
    newsTypes: "जाहिरातीचा प्रकार",
    attachement: "दस्तऐवज",
    attachements: "कागदपत्रे",
    newsFromDate: "जाहिरात प्रकाशित तारीख",
    newsFromDateTable: "प्रकाशन दिनांक",
    publishDate: "प्रकाशित तारीख",
    formateSize: "मानक स्वरूप आकार",
    newsReleaseDate: "जाहिरात प्रकाशन तारीख",
    status: "स्थिती",
    action: "क्रिया",
    attachNews: "जाहिरात संलग्न करा",
    attachmentSchema: "*कमाल अपलोड आकार 2MB आहे.",
    newsAttachement: "जाहिरात संबंधित दस्तऐवज",
    papercutAttachement: "पेपर कटिंग संलग्न",
    newsPublish: "जाहिरात प्रकाशित करण्याची विनंती",

    petLicense: "पाळीव प्राणी परवाना",
    petAnimal: "पाळीव प्राणी",
    area: "क्षेत्र",
    zone: "झोनचे नाव",
    ward: "प्रभाग",
    flatOrHouseNo: "फ्लॅट/घर क्र.",
    buildingName: "इमारतीचे नाव",
    detailAddress: "पूर्ण पत्ता",
    ownerName: "मालकाचे नाव",
    mobileNo: "मोबाईल नं",
    emailId: "इमेल पत्ता",
    petName: "पाळीव प्राण्याचे नाव",
    petBirthdate: "पाळीव प्राण्याची जन्मतारीख",
    animalBreed: "प्राण्याची जाती",
    animalColor: "प्राण्याचा रंग",
    animalAge: "प्राण्याचं वय (वर्ष मध्ये)",
    animalWeight: "प्राण्याचं वजन (किलोग्राम मध्ये)",
    animalGender: "प्राण्याचं लिंग",
    antiRabiesVaccinationStatus: "रेबीजविरोधी लसीकरण स्थिती",
    vaccinationDate: "लसीकरणची तारीख",
    veterinaryDoctorsName: "पशुवैद्यकीय डॉक्टरांचे नाव",
    documents: "कागदपत्रे",
    vaccinationPDF: "लसीकरणाची PDF",
    animalPhoto: "प्राण्याचा फोटो",
    remark: "टिप्पणी",
    status: "अर्ज स्थिती",
    petAnimalEn: "पाळीव प्राण्याचे इंग्रजीत नाव",
    petAnimalMr: "पाळीव प्राण्याचे मराठीत नाव",
    petBreed: "पाळीव प्राण्याची जाती",
    breedNameEn: "जातीचं नाव इंग्रजीत",
    breedNameMr: "जातीचं नाव मराठीत",
    ownerPhotoID: "मालकाचा ओळख पुरावा",
    makePayment: "पैसे भरा",
    generateLicense: "परवाना निर्मिती",
    licenseFor: "कुठल्या पाळीव प्राण्यासाठी",
    pcmc: "पिंपरी चिंचवड महानगरपालिका",
    fiscalYear: "सन",
    officeCopy: "कार्यालयाची प्रत",
    customerCopy: "ग्राहकाची प्रत",
    receiptNo: "पावती क्र.",
    date: "तारीख",
    relatedTo: "विभागाकडून",
    cfcRefNo: "सीएफसी संदर्भ क्रं",
    cfcCounterNo: "सीएफसी काउंटर क्रं",
    receivedFrom: "कोणाकडून",
    serviceName: "सेवेचे नाव",
    narration: "विवरण",
    address: "पत्ता",
    paymentMode: "देण प्रकार",
    rupees: "रुपये",
    chequeNo: "धनादेश क्रं.",
    chequeDate: "धनादेश क्रं",
    bankName: "बँकेचे नाव",
    referenceNo: "संदर्भ क्रं.",
    applicationDate: "अर्जाची तारीख",
    details: "तपशील",
    payableAmount: "देय रक्कम",
    receivedAmount: "स्वीकारलेली रक्कम",
    rebateAmount: "सूट/सवलत रक्कम",
    advanceAmount: "आगाऊ रक्कम",
    actualPayableAmount: "एकूण देय रक्कम",
    totalAmount: "एकूण रक्कम",
    amountInWords: "एकूण रक्कम शब्दांमध्ये",
    receiverSignature: "स्वीकारनाऱ्याची स्वाक्षरी",
    tip: "टीप",
    printBy: "छापनार्याचे नाव",
    printDateAndTime: "छापतांना तारीख आणि वेळ",
    casePaperNo: "केसपेपर क्र.",
    licenseNo: "परवाना क्र.",
    ownerAddress: "मालकाचा पत्ता",
    symptoms: "लक्षणं",
    aknowledgementSlipNo: "पोच पावती क्र. (क्रमांक)",
    diagnosisDetail: "निदान तपशील",
    medicineDetails: "औषध तपशील",
    treatment: "उपचार",
    payment: "पैसे भरणे",
    payerName: "देयकाचे नाव",
    payerAddress: "देयकाचा पत्ता",
    receiptDate: "पावतीची तारीख",
    transactionDate: "ट्रांसकशनची तारीख",
    treatmentCategory: "उपचार श्रेणी",
    casePaperDate: "केस पेपरची तारीख",
    accountGlCode: "जीएल खात्याचा कोड",
    opd: "ओपीडी",
    lattitude: "अक्षांश",
    longitude: "रेखांश",
    city: "शहर",
    state: "राज्य",
    pincode: "पिनकोड",
    amount: "रक्कम",
    paymentType: "पैसे भरण्याची पध्दत",
    cfcCode: "सीएफसी कोड",
    ddNo: "डिमांड ड्राफ्ट क्र",
    ddDate: "डिमांड ड्राफ्टची तारीख",
    branchName: "शाखेचे नाव",
    ifscCode: "आयएफएससी कोड",
    accountNo: "खाते क्रमांक",
    newsOrAdvertisementRotationNo: "जाहिरातीचे रोटेशन क्र.",
    department: "विभाग",
    newsReleasingDate: "जाहिरात प्रकाशन तारीख",
    newsOrAdvertisementPublishedDate: "जाहिरातीचे प्रकाशित तारीख",
    subject: "विषय",
    description: "वर्णन",
    standardFormatSize: "स्टैन्डर्ड फॉर्मेट आकार(चौरस सेंटीमीटर मध्ये)",
    publishStatus: "प्रकाशितची स्थिती",
    newsOrAdvertisementSqMeter: "जाहिरातीचे चौरस मीटर",
    billAmount: "बिलाची रक्कम",
    billApprovalRemark: "बिल मंजुरी टिप्पणी",
    attachment: "संलग्नक",
    fromDate: "ह्या तारखेपासून",
    toDate: "ते तारखेपर्यंत",

    search: "शोधा",
    preview: "पूर्वावलोकन",
    addFile: "फाइल जोडा",
    srNo: "अनु क्र",
    actions: "क्रिया ",
    approve: "मंजूर",
    reassign: "पुन्हा नियुक्त करा",
    agreeAndNext: "सहमत आणि पुढे",

    //buttons
    add: "जोडा",
    save: "जतन करा",
    finalSubmit: "अंतिम सबमिट करा",
    update: "अद्यायावत करा",
    clear: "रिक्त",
    exit: "बाहेर पडा",
    back: "मागे",
    saveAndNext: "जतन करा आणि पुढे",
    finish: "समाप्त",
    print: "छापणे",

    /* press note lables marathi */
    pressNoteNo: "प्रेस नोट नंबर",
    pressNoteReleasingDate: "प्रेस नोट जारी करण्याची तारीख",
    pressNoteSubject: "प्रेस नोट विषय",
    pressNoteDescription: "प्रेस नोट विवरण",
    pressNoteReleaseDate: "प्रेस नोट जारी करण्याची तारीख",
    pressNoteReleaseHeading: "प्रेस नोट प्रकाशन विनंती",
    pressNoteRequestAddNew: "नवीन विनंती",
    newsPaperName: "वृत्तपत्राचे नाव",

    /* news Type mst lables marathi */
    newsTypeHeading: "जाहिरातीचा प्रकार",
    newsType: "जाहिरातीचा प्रकार (इन इंग्रजी)",
    newsTypeMr: "जाहिरातीचा प्रकार (मराठी मध्ये) ",

    /* advertisementType mst lables marathi */
    advertisementTypeHeading: "जाहिरात प्रकाशन प्रकार",
    advertisementType: "जाहिरात प्रकाशन प्रकार (इन इंग्रजी)",
    advertisementTypeMr: "जाहिरात प्रकाशन प्रकार (मराठी मध्ये)",

    /* News Paper Level mst lables marathi */
    newsPaperLevelHeading: "वृत्तपत्र पातळी",
    newsPaperLevel: "वृत्तपत्र पातळी (इन इंग्रजी)",
    newsPaperLevelMr: "वृत्तपत्र पातळी (मराठी मध्ये)",

    addNew: "जोडा",

    /* Rate Chart mst lables marathi */
    rateChartHeading: "दर तक्ता",
    newsPaperLevelDropDown: "वृत्तपत्र पातळी",
    newsPaperDropDown: "वृत्तपत्राचे नाव",
    chargeType: "शुल्काचा प्रकार",
    chargeAmount: "दर (प्रति चौरस सेंटीमीटर)",

    advirtiseMentInDocx: "जाहिरातीचे दस्तऐवज (डॉक्स/एक्सेल फोर्मट मध्ये)",
    advirtiseMentInPdf: "जाहिरातीचे दस्तऐवज(पीडीएफ फोर्मट मध्ये)",

    //Event Management
    eventManagement: "कार्यक्रम व्यवस्थापन",
    eventNumber: "कार्यक्रम क्रमांक",
    eventDate: "कार्यक्रमाची तारीख",
    eventTime: "कार्यक्रमाची वेळ",
    eventDescription: "कार्यक्रमाचे वर्णन",
    eventLocationLat: "कार्यक्रमाचे ठिकाण (अक्षांश)",
    eventLocationLong: "कार्यक्रमाचे ठिकाण (रेखांश)",

    //budget provision
    budgetProvision: "अर्थसंकल्पात तरतूद",
    billDescription: "बिल वर्णन",
    newsPaperName: "वृत्तपत्राचे नाव",
    billAmount: "बिलाची रक्कम",
    budgetAmountAfterPreviousBillPaymentDeduction:
      "बजेटची रक्कम (मागील बिल पेमेंट कपातीनंतर)",
    budgetAmountAfterCurrentBillPaymentDeduction:
      "बजेटची रक्कम (वर्तमान बिल पेमेंट कपातीनंतर)",
    billApprovalDate: "बिल मंजुरीची तारीख",
    billApprovalOfficerName: "बिल मंजूरी अधिकाऱ्याचे नाव",
    fileName: "फाईलचे नाव",
    fileType: "दस्तावेजाचा प्रकार",
    uploadBy: "द्वारे अपलोड केले",
    action: "कृती",

    specialNotice: "विशेष सूचना",
    enterPenaltyAmount: "दंडाची रक्कम प्रविष्ट करा",
    selectThisPenaltyFirst: "प्रथम हा दंड निवडा",
    enterPenaltyDescription: "दंडाचे वर्णन प्रविष्ट करा",
    upload: "अपलोड करा",
    uploadedBy: "द्वारे अपलोड केले",
    id: "आयडी",
    newsPublishID: "बातम्या प्रकाशित आयडी",
    statusUpdateDate: "स्थिती अद्यतन तारीख",
    noRemarkFound: "कोणतीही टिप्पणी आढळली नाही!",
  },
};
