export default {
  en: {
    //constants
    publicAud: "PUBLIC AUDITORIUM BOOKING AND BROADCAST MANAGEMENT",
    addAuditorium: "New Auditorium Entry",
    newAuditoriumEntry: "New Auditorium Entry",
    add: "Add",
    save: "Save",
    update: "Update",
    clear: "Clear",
    exit: "Exit",
    back: "Back",
    saveAndNext: "Save & Next",
    next: "Next",
    btnSaveText: "Save",
    srNo: "Sr No.",
    zone: "Zone",
    ward: "Ward",
    status: "Status",
    actions: "Actions",
    reset: "Reset",

    //equipment master
    equipmentCategory: "Equipment Category",
    equipmentName: "Equipment Name",
    equipmentNameMr: "Equipment Name (Marathi)",
    vendorName: "Vendor Name",

    //auditorium master
    auditorium: "Auditorium Name",
    auditoriumMr: "Auditorium Name (Marathi)",
    address: "Address",
    addressMr: "Address (Marathi)",
    gisIdGeocode: "GISID Geocode",
    seatingCapacity: "Seating Capacity",
    startTime: "Start Time",
    endTime: "End Time",

    // equipment Category master
    equipmentCategoryNameEn: "Equipment Category Name",
    equipmentCategoryNameMr: "Equipment Category Name (Marathi)",

    //equipment Charges
    equipmentCharges: "Equipment Charges",
    auditorium: "Auditorium Name",
    equipment: "Equipment Name",
    equipmentCategory: "Equipment Category",
    equipmentCategoryMr: "Equipment Category (Marathi)",
    _price: "Company Rate",
    corporationRate: "Corporation Rate",
    multiplyingFactor: "Multiplying Factor",
    totalAmount: "Total Amount",
    equipmentRate: "Equipment Rate",

    //Check Auditorium availability
    checkAuditoriumAvailability: "Check Auditorium Availability",
    auditoriumBookingType: "Auditorium Booking Type",
    normalAuditoriumBooking: "Regular Auditorium Booking",
    advancedAuditoriumBooking: "Advanced Auditorium Booking",
    search: "Search",
    auditorium: "Auditorium Name",
    selectSlot: "Select Slot",
    eventDate: "Event Date",
    selectEvent: "Select Event",

    //auditorium Events
    eventTimee: "Event Date",
    programEventDescription: "Program Event Description",
    eventHours: "Event Hours",
    eventNameEn: "Event Name",
    eventNameMr: "Event Name (Marathi)",

    //auditorium Events Charges
    auditoriumEventCharges: "Auditorium Event Charges",
    auditoriumEvents: "Auditorium Events",
    programEventDescription: "Program Event Description",
    depositAmount: "Deposit Amount",
    grandTotal: "Grand Total",
    eventTime: "Event Time",
    gstAmount: "GST Amount",
    gst: "GST",
    rentAmount: "Rent Amount",
    securityAmount: "Security Guard Charges",
    totalAmount: "Total Amount",
    noOfDays: "No. Of Days",
    banner_boardCharges: "Banner/Board Charges",
    exportTo: "Export To",
    excel: "Excel",
    printPdf: "Print / PDF",

    //Auditorium Schedule Master
    auditoriumSchedule: "Auditorium Schedule",
    shift: "Shift",
    auditorium: "Auditorium Name",
    eventTimeFrom: "Event Time From",
    eventTimeTo: "Event Time To",
    slotDescription: "Remark",
    NoOfdays: "Number of days",
    showTimeDuration: "Show Time / Duration",
    publishFromDate: "Publish From Date",
    publishToDate: "Publish To Date",
    bookingConfirmationDate: "Booking Confirmation Date",

    //Rate Chart Master
    rateChartMaster: "Rate Chart Master",
    eventName: "Event Name",
    chargeName: "Charge Name",
    fromDate: "From Date",
    toDate: "To Date",
    range: "Discount",
    price: "Price",
    period: "Period (Hrs)",
    discount: "Discount",
    ticketRate: "Ticket Rate",
    isMondayToThursday: "Monday To Thursday",
    isFridayToSunday: "Friday To Sunday",
    ticket: "Ticket",
    sgst: "SGST",
    cgst: "CGST",
    actualPrice: "Actual Price",
    discountedPrice: "Discounted Price",
    zeroToHundred: "0 To 100",
    oneHundredOneAndAbove: "101 & above",
    days: "Days",
    withTicket: "With Ticket",
    withoutTicket: "Without Ticket",

    //transactions
    //Auditorium Booking online process

    auditoriumBooking: "Auditorium Booking",
    selectAuditorium: "Select Auditorium",
    auditoriumBookingNumber: "Auditorium Booking Number",
    auditoriumBookingApplicationNumber: "Auditorium Booking Application Number",
    bookingForPCMC: "Booking For Only PCMC (50% Discount)",
    bookingForOtherVendor: "Booking For Government (30% Discount)",
    bookingForOtherOrganization: "Booking For Others",
    organizationName: "Organization Name",
    title: "Title",
    flat_buildingNo: "Flat Building No.",
    organizationOwnerFirstName: "Organization Owner First Name",
    organizationOwnerMiddleName: "Organization Owner Middle Name",
    organizationOwnerLastName: "Organization Owner Last Name",
    buildingName: "Building Name",
    roadName: "Road Name",
    landmark: "Landmark",
    pinCode: "Pin Code",
    aadhaarNo: "Aadhaar Number",
    landline: "Landline",
    gstNo: "GST No",
    mobile: "Mobile",
    emailAddress: "Email Address",
    messageDisplay: "Message Display",
    eventDetails: "Event Details",
    eventDate: "Event Date",
    eventDay: "Event Day",
    eventTimeFrom: "Event Time From",
    eventTimeTo: "Event Time To",
    depositAmount: "Deposit Amount",
    payDepositAmount: "Pay Deposit Amount",
    rentAmount: "Rent Amount",
    payRentAmount: "Pay Rent Amount",
    depositReceipt: "Deposit Receipt",
    extendedRentAmount: "Extended Rent Amount",
    rentReceipt: "Rent Receipt",
    managersDigitalSignature: "Managers Digital Signature",
    termsAndConditions: "Terms And Conditions -",
    ecsFormDetails: "ECS Form Details",
    bankAccountHolderName: "Bank Account Holder Name",
    bankAccountNumber: "Bank Account Number",
    confirmBankAccountNo: "Confirm Bank Account Number",
    typeOfBankAccount: "Type Of Bank Account",
    bankName: "Bank Name",
    bankAddress: "Bank Address",
    ifscCode: "IFSC Code",
    micrCode: "MICR Code",
    remark: "Remark",
    equipments: "Equipments",
    addMore: "Add more",
    rate: "Rate",
    quantity: "Quantity",
    total: "Total",
    bookingAuditoriumDetails: "Booking Auditorium Detail's",
    employeeId: "Employee Id / Code",
    employeeName: "Employee Name",
    designation: "Designation",
    departmentName: "Department Name",
    eventTitle: "Event Title",
    eventDateFrom: "Event Date",
    eventDateTo: "Event Date To",
    eventDayFrom: "Event Day",
    eventDayTo: "Event Day To",
    applicantDetails: "Applicant Detail's",
    applicantName: "Applicant Name",
    applicantMobileNo: "Applicant Mobile No",
    applicantConfirmMobileNo: "Applicant Confirm Mobile No",
    applicantEmail: "Applicant Email",
    applicantConfirmEmail: "Applicant Confirm Email",
    relationWithOrganization: "Relation With Organization",
    applicantFlatHouseNo: "Applicant Flat/House No",
    applicantFlatBuildingName: "Applicant Flat/Building Name",
    applicantLandmark: "Applicant Landmark",
    applicantArea: "Applicant Area",
    country: "Applicant Country",
    applicantState: "Applicant State",
    applicantCity: "Applicant City",
    applicantPinCode: "Applicant PinCode",
    bookingCharges: "Booking Charges",
    applicationHistory: "Application History",
    approvalClerkRemark: "Approval Clerk Remark",
    approvalRemarkByHod: "Approval Remark By HOD",
    approve: "Approve",
    reject: "Reject",
    loiGenration: "LOI Generation",
    generateLoi: "Generate LOI",
    bookedPublicAuditorium: "Booked Public Auditorium",
    bankDetails: "Bank Details",
    receiptAmount: "Receipt Amount",
    receiptNumber: "Receipt Number",
    receiptDate: "Receipt Date",
    fromTime: "From Time",
    toTime: "To Time",
    date: "Date",
    payDepositeAndApply: "Pay & Apply",
    equipmentsTotal: "Equipments Total Amount",
    calendar: "Calendar",
    confirmBookingForAboveSelectedDateAndTime:
      "Confirm booking for above selected date and time",
    uploadDocuments: "Upload Documents",
    apply: "Apply.",
    eventModal: "Event Modal",
    bookingAvailable: "Booking Available",
    day: "Day",
    close: "Close",
    bookingConfirmedFor: "Booking Confirmed For - ",

    //auditorium booking cancellation
    bookingCancellationByDepartment: "Booking Cancellation By Department",
    clarkReasonForCancellation: "Clerk reason for cancellation",
    cancellationRemarkByClark: "Cancellation Remark By Clark",
    hodReasonForCancellation: "HOD reason for cancellation",
    cancellationRemarkByHod: "Cancellation Remark By HOD",
    bookingCancellation: "Booking Cancellation",
    selectAuditorium: "Auditorium",
    auditoriumId: "Auditorium Id",
    selectService: "Service",
    auditoriumBookingNumber: "Auditorium Booking Number",
    cancelByApplicant_Vendor: "Cancel by Applicant/Vendor",
    cancelByDepartment: "Cancel by Department",
    reasonForCancellation: "Reason for cancellation",
    searchByAuditoriumBookingNumber: "Search By Auditorium Booking Number",
    searchByAuditoriumBookingApplicationNumber:
      "Search By Auditorium Booking Application Number",
    searchByEventDate: "Search By Event Date",
    returnAmountDetails: "Return Amount Details",
    shownAnAmountToBeReturnedAfterBookingCancellation:
      "Shown an amount to be returned after booking cancellation",
    amountToBeReturned: "Amount to be returned",
    bookingCancellationDetails: "Booking Cancellation Details",
    budgetingUnit: "Budgeting Unit",
    notesheet_ReferenceNumber: "Notesheet / Reference number",
    billDate: "Bill Date",
    remark: "Remark",
    citizenReasonForCancellation: "Citizen Reason For Cancellation",
    cancellationRemark: "Cancellation Remark",
    bookingDate: "Booking Date",
    cancellationDate: "Cancellation Date",
    amountDetails: "Amount Details",
    refundBreakupDetails: "Refund Breakup Details",
    cancellationRateChart: "Cancellation Rate Chart",
    content: "Content",
    depositAmountPaid: "Deposit amount paid",
    cancellationCharges: "Cancellation Charges",
    totalRefundableAmount: "Total refundable amount",
    certainFees:
      "1) Certain fees (GST Amount) collected are not refundable as per cancellation policy.",
    deductionAre: "2) Deduction are done as per cancellation policy.",
    selectApplication: "Select Application",

    //depositeRefundProcessing
    searchByAuditoriumBookingNumber: "Search By Auditorium Booking Number",
    attachDocuments: "Attach Documents",
    depositRefundBillDetails: "Deposit Refund Bill Details",
    ecsPayment: "ECS Payment",
    depositeReceiptNo: "Deposit Receipt Number",
    depositeAmount: "Deposit Amount",
    depositeReceiptDate: "Deposit Receipt Date",
    bankAccountNo: "Bank Account Number",
    depositRefundProcess: "Deposit Refund Process",
    attachment: "Attachment",
    addExtraEquipments: "Add Extra Equipments",
    extraEquipments: "Extra Equipments",
    extraEquipmentAmount: "Other Equipment Amount",
    refundableAmount: "Refundable Amount",
    finalRefundableAmount: "Final Refundable Amount",
    details: "Details",

    //shift master
    shiftTitle: "Shift Master",
    timeSlot: "Shift Hours",
    shift: "Shift Name",

    durationOfApplicationDistributionAndAcceptance:
      "Duration Of Application Distribution And Acceptance",
    holidayWeekendSchedule: "Holiday Weekend Schedule",

    //Forcefully Cancellation By Department
    forcefullyCancellationByDepartment: "Forcefully Cancellation By Department",

    //Auditorium bill
    auditoriumBill: "Auditorium Bill",
    depositAdjustment: "Deposit Adjustment",
    bookingAuditoriumDetails: "Booking Auditorium Details",
    generateBill: "Generate Bill",
    payExtraAmountAndGenerateBill: "Generate Extra Equipment Bill",

    //Reports
    //auditoriumBooking
    applicationDate: "Application Date",
    applicationNumber: "Application Number",
    loiNo: "LOI No",
    loiDate: "LOI Date",
    applicantName: "Applicant Name",
    applicantMobile: "Applicant Mobile",
    auditorium: "Auditorium",
    organizationName: "Organization Name",
    deposite: "Deposit",
    rent: "Rent",
    totalAmount: "Total Amount",
    remarks: "Remarks",
    downloadExcel: "DOWNLOAD EXCEL",
    downloadPdf: "DOWNLOAD PDF",
    cancel: "Cancel",
    submit: "Submit",
    process: "Process",
    print: "Print",
    amount: "Amount",

    //payment
    paymentCollection: "Payment Collection",
    receiptModeDetails: "Receipt Mode Details",
    paymentType: "Payment Type",
    paymentMode: "Payment Mode",
    pay: "Pay",
    upiId: "UPI ID",
    upiList: "UPI List",
    branchName: "Branch Name",

    //pgSuccess
    applicationNo: "Application Number",
    orderId: "Order Id",
    trackingId: "Tracking Id",
    bankRefNo: "Bank Ref. No",
    billingName: "Billing Name",
    billingAdd: "Billing Address",
    billingCity: "Billing City",
    billingState: "Billing State",
    billingZip: "Billing Zip Code",
    billingCountry: "Billing Country",
    billingEmail: "Billing Email",
    mobileNo: "Mobile No",
    totalAmount: "Total Amount",
    transactionDate: "Transaction Date",
    loiNo: "LOI No",
    goToList: "Exit",
    moduleName: "Module Name",
    extraAmountPaid: "Extra Equipment Amount Paid",
    extraAmount: "Extra Equipment Amount",

    //OTHER
    yourPaymentDoneSuccess: "Deposit Paid",
    audBookingRentCharges: "Auditorium Booking Rent Charges",
    saveAsDraft: "Save As Draft",
    paymentFailed: "Payment Aborted",
    orderStatus: "Order Status",
    attachmentSchema: "Attachments",
    yourRehearsalRentPaymentDoneSuccess: "Rehearsal Rent Payment Paid",
    paymentRehearsalRentFailed: "Rehearsal Rent Payment Failed",
  },
  mr: {
    //constants
    publicAud: "पब्लिक ऑडिटोरियम बुकिंग आणि ब्रॉडकास्ट व्यवस्थापन",
    addAuditorium: "नवीन प्रेक्षागृह / नाट्यगृह नोंदणी",
    newAuditoriumEntry: "नवीन प्रेक्षागृह / नाट्यगृह नोंदणी",
    add: "नवीन नोंदणी",
    save: "जतन करा",
    update: "अद्यायावत करा",
    clear: "रिक्त",
    exit: "बाहेर पडा",
    back: "मागे",
    saveAndNext: "जतन करा आणि पुढे",
    next: "पुढे",
    btnSaveText: "जतन करा",
    srNo: "अनु क्र",
    zone: "झोन",
    ward: "प्रभाग",
    status: "स्थिती",
    actions: "क्रिया",
    reset: "रीसेट",

    //equipment master
    equipmentCategory: "उपकरणे श्रेणी",
    equipmentName: "उपकरणाचे नाव",
    equipmentNameMr: "उपकरणाचे नाव मराठी",
    vendorName: "विक्रेता नाव",

    //Auditorium master
    auditorium: "प्रेक्षागृह / नाट्यगृह नाव",
    auditoriumMr: "प्रेक्षागृह / नाट्यगृह नाव (मराठी)",
    address: "पत्ता",
    addressMr: "पत्ता (मराठी)",
    gisIdGeocode: "जीएसआय आयडी जिओकोड",
    seatingCapacity: "आसन क्षमता",
    startTime: "सुरवातीची वेळ",
    endTime: "समाप्तीचा कालावधी",

    // equipment Category master
    equipmentCategoryNameEn: "उपकरण श्रेणीचे नाव",
    equipmentCategoryNameMr: "उपकरण श्रेणीचे नाव (मराठी)",

    //equipment Charges
    equipmentCharges: "उपकरणे शुल्क",
    auditorium: "प्रेक्षागृह / नाट्यगृह नाव",
    equipment: "उपकरणाचे नाव",
    equipmentCategory: "उपकरणे श्रेणी",
    equipmentCategoryMr: "उपकरण श्रेणी (मराठी)",
    _price: "कंपनी दर",
    corporationRate: "महानगरपालिका दर",
    multiplyingFactor: "गुणाकार घटक",
    totalAmount: "एकूण रक्कम",
    equipmentRate: "उपकरण दर",

    //Check Auditorium availability
    checkAuditoriumAvailability: "प्रेक्षागृह / नाट्यगृह उपलब्धता तपासा",
    auditoriumBookingType: "प्रेक्षागृह बुकिंग प्रकार",
    normalAuditoriumBooking: "नियमित प्रेक्षागृह / नाट्यगृह बुकिंग",
    advancedAuditoriumBooking: "आगाऊ प्रेक्षागृह / नाट्यगृह बुकिंग",
    search: "शोधा",
    auditorium: "प्रेक्षागृह / नाट्यगृह नाव",
    selectSlot: "स्लॉट निवडा",
    eventDate: "कार्यक्रमाची तारीख",
    selectEvent: "कार्यक्रम निवडा",

    //auditorium Events
    eventTimee: "कार्यक्रमाची तारीख",
    programEventDescription: "कार्यक्रमाचे वर्णन",
    eventHours: "कार्यक्रमाचे तास",
    eventNameEn: "कार्यक्रमाचे नाव",
    eventNameMr: "कार्यक्रमाचे नाव (मराठी)",

    //auditorium Events Charges
    auditoriumEventCharges: "प्रेक्षागृह / नाट्यगृह कार्यक्रम शुल्क",
    auditoriumEvents: "प्रेक्षागृह / नाट्यगृह कार्यक्रम",
    programEventDescription: "कार्यक्रमाचे वर्णन",
    depositAmount: "अनामत रक्कम",
    grandTotal: "एकूण",
    eventTime: "कार्यक्रमाची वेळ",
    gstAmount: "जीएसटी रक्कम",
    gst: "जीएसटी",
    rentAmount: "भाडे रक्कम",
    securityAmount: "सुरक्षा रक्कम",
    totalAmount: "एकूण रक्कम",
    noOfDays: "दिवसांची संख्या",
    banner_boardCharges: "बॅनर/बोर्ड शुल्क",
    exportTo: "पाठवा",
    excel: "एक्सेल",
    printPdf: "प्रिंट/पीडीएफ",

    //Auditorium Schedule Master
    auditoriumSchedule: "प्रेक्षागृह / नाट्यगृह वेळापत्रक",
    shift: "शिफ्ट",
    auditorium: "प्रेक्षागृह / नाट्यगृह नाव",
    eventTimeFrom: "पासून कार्यक्रम वेळ",
    eventTimeTo: "कार्यक्रमाची वेळ पर्यंत",
    slotDescription: "टिप्पणी",
    NoOfdays: "दिवसांची संख्या",
    showTimeDuration: "शोची वेळ / कालावधी",
    publishFromDate: "प्रकाशन तारखेपासून",
    publishToDate: "तारखेपर्यंत प्रकाशित",
    bookingConfirmationDate: "बुकिंग पुष्टीकरण तारीख",

    //Rate Chart Master
    rateChartMaster: "दर तक्ता मास्टर",
    eventName: "कार्यक्रमाचे नाव",
    chargeName: "शुल्क नाव",
    fromDate: "या तारखेपासून",
    toDate: "या तारखेपर्यंत",
    range: "सवलत",
    price: "किंमत",
    period: "कालावधी (तास)",
    discount: "सवलत",
    ticketRate: "तिकीट दर",
    isMondayToThursday: "सोमवार ते गुरुवार",
    isFridayToSunday: "शुक्रवार ते रविवार",
    ticket: "तिकीट",
    sgst: "एसजीएसटी",
    cgst: "सीजीएसटी",
    actualPrice: "वास्तविक किंमत",
    discountedPrice: "सवलत किंमत",
    zeroToHundred: "० ते १००",
    oneHundredOneAndAbove: "१०१ आणि त्यावरील",
    days: "दिवस",
    withTicket: "तिकिटासह",
    withoutTicket: "विना तिकीट",

    //transactions
    //Auditorium Booking online process

    auditoriumBooking: "प्रेक्षागृह बुकिंग",
    selectAuditorium: "प्रेक्षागृह निवडा",
    auditoriumBookingNumber: "प्रेक्षागृह बुकिंग क्रमांक",
    auditoriumBookingApplicationNumber: "प्रेक्षागृह बुकिंग अर्ज क्रमांक",
    bookingForPCMC: "बुकिंग फक्त पीसीएमसी साठी (५०% सवलत)",
    bookingForOtherVendor: "सरकारी संस्थेसाठी बुकिंग (३०% सवलत)",
    bookingForOtherOrganization: "अन्य संस्थेसाठी बुकिंग",
    organizationName: "संस्थेचे नाव",
    title: "शीर्षक",
    flat_buildingNo: "फ्लॅट इमारत क्र.",
    organizationOwnerFirstName: "संस्थेच्या मालकाचे पहिले नाव",
    organizationOwnerMiddleName: "संस्थेच्या मालकाचे मधले नाव",
    organizationOwnerLastName: "संस्थेच्या मालकाचे आडनाव",
    buildingName: "इमारतीचे नाव",
    roadName: "रस्त्याचे नाव",
    landmark: "लँडमार्क",
    pinCode: "पिन कोड",
    aadhaarNo: "आधार क्रमांक",
    landline: "लँडलाइन",
    gstNo: "जीएसटी क्र",
    mobile: "मोबाईल",
    emailAddress: "ईमेल",
    messageDisplay: "संदेश प्रदर्शन",
    eventDetails: "कार्यक्रम तपशील",
    eventDate: "कार्यक्रमाची तारीख",
    eventDay: "कार्यक्रमाचा दिवस",
    eventTimeFrom: "पासून कार्यक्रम वेळ",
    eventTimeTo: "कार्यक्रमाची वेळ पर्यंत",
    depositAmount: "अनामत रक्कम",
    payDepositAmount: "अनामत रक्कम भरा",
    rentAmount: "भाडे रक्कम",
    payRentAmount: "भाड्याची रक्कम द्या",
    depositReceipt: "अनामत रक्कम पावती",
    extendedRentAmount: "विस्तारित भाडे रक्कम",
    rentReceipt: "भाड्याची पावती",
    managersDigitalSignature: "व्यवस्थापकांची डिजिटल स्वाक्षरी",
    termsAndConditions: "नियम आणि अटी",
    ecsFormDetails: "ईसीएस फॉर्म तपशील",
    bankAccountHolderName: "बँक खातेधारकाचे नाव",
    bankAccountNumber: "बँक खाते क्रमांक",
    confirmBankAccountNo: "बँक खाते क्रमांकाची पुष्टी करा",
    typeOfBankAccount: "बँक खात्याचा प्रकार",
    bankName: "बँकेचे नाव",
    bankAddress: "बँकेचा पत्ता",
    ifscCode: "आयएफएससी कोड",
    micrCode: "एमआयसीआर कोड",
    remark: "शेरा",
    equipments: "उपकरणे",
    addMore: "अधिक जोडा",
    rate: "दर",
    quantity: "प्रमाण",
    total: "एकूण",
    bookingAuditoriumDetails: "बुकिंग प्रेक्षागृह / नाट्यगृह तपशील",
    employeeId: "कर्मचारी आयडी / कोड",
    employeeName: "कर्मचारी नाव",
    designation: "हुद्दा",
    departmentName: "विभागाचे नाव",
    eventTitle: "कार्यक्रमाचे शीर्षक",
    eventDateFrom: "इव्हेंटची तारीख",
    eventDateTo: "इव्हेंटची तारीख पर्यंत",
    eventDayFrom: "इव्हेंट डे",
    eventDayTo: "इव्हेंट डे पर्यंत",
    applicantDetails: "अर्जदाराचे तपशील",
    applicantName: "अर्जदाराचे नाव",
    applicantMobileNo: "अर्जदार मोबाईल क्र",
    applicantConfirmMobileNo: "अर्जदाराच्या मोबाईल क्रमांकाची पुष्टी करा",
    applicantEmail: "अर्जदाराचा ईमेल",
    applicantConfirmEmail: "अर्जदाराच्या ईमेलची पुष्टी करा",
    relationWithOrganization: "संस्थेशी संबंध",
    applicantFlatHouseNo: "अर्जदार फ्लॅट/घर क्र",
    applicantFlatBuildingName: "अर्जदार फ्लॅट/बिल्डिंगचे नाव",
    applicantLandmark: "अर्जदार लँडमार्क",
    applicantArea: "अर्जदार राहण्याचे क्षेत्र",
    country: "अर्जदाराचा देश",
    applicantState: "अर्जदाराचे राज्य",
    applicantCity: "अर्जदाराचे शहर",
    applicantPinCode: "अर्जदाराचा पिनकोड",
    bookingCharges: "बुकिंग शुल्क",
    applicationHistory: "अर्ज इतिहास",
    approvalClerkRemark: "मंजूरी लिपिक टिप्पणी",
    approvalRemarkByHod: "एचओडी द्वारे मान्यता टिप्पणी",
    approve: "मंजूर",
    reject: "नाकारणे",
    loiGenration: "एलओआय जनरेशन",
    generateLoi: "उत्पन्न करा",
    bookedPublicAuditorium: "बुक केलेले सार्वजनिक प्रेक्षागृह / नाट्यगृह",
    bankDetails: "बँक तपशील",
    receiptAmount: "पावती रक्कम",
    receiptNumber: "पावती क्रमांक",
    receiptDate: "पावतीची तारीख",
    fromTime: "वेळ पासून",
    toTime: "वेळेपर्यंत",
    date: "तारीख",
    payDepositeAndApply: "अनामत रक्कम भरा & अर्ज करा",
    equipmentsTotal: "उपकरणे एकूण रक्कम",
    calendar: "कॅलेंडर",
    confirmBookingForAboveSelectedDateAndTime:
      "वरील निवडलेल्या तारीख आणि वेळेसाठी बुकिंगची पुष्टी करा",
    uploadDocuments: "दस्तऐवज अपलोड करा",
    apply: "अर्ज करा.",
    eventModal: "कार्यक्रमाचे वर्णन",
    bookingAvailable: "बुकिंग उपलब्ध",
    day: "दिवस",
    close: "बंद",
    bookingConfirmedFor: "बुकिंग कन्फर्म -",

    //auditorium booking cancellation
    bookingCancellationByDepartment: "विभागाकडून बुकिंग रद्द करणे",
    clarkReasonForCancellation: "लिपिक रद्द करण्याचे कारण",
    cancellationRemarkByClark: "क्लार्क द्वारे रद्द टिप्पणी",
    hodReasonForCancellation: "रद्द करण्याचे HOD कारण",
    cancellationRemarkByHod: "HOD द्वारे रद्दीकरण टिप्पणी",
    bookingCancellation: "बुकिंग रद्द करणे",
    selectAuditorium: "प्रेक्षागृह",
    auditoriumId: "प्रेक्षागृह / नाट्यगृह आयडी",
    selectService: "सेवा",
    auditoriumBookingNumber: "प्रेक्षागृह बुकिंग क्रमांक",
    cancelByApplicant_Vendor: "अर्जदार/विक्रेत्याद्वारे रद्द करा",
    cancelByDepartment: "विभागाकडून रद्द करा",
    reasonForCancellation: "रद्द करण्याचे कारण",
    searchByAuditoriumBookingNumber: "प्रेक्षागृह बुकिंग नंबर द्वारे शोधा",
    searchByAuditoriumBookingApplicationNumber:
      "ऑडिटोरियम बुकिंग अर्ज क्रमांक द्वारे शोधा",
    searchByEventDate: "इव्हेंटच्या तारखेनुसार शोधा",
    returnAmountDetails: "परतावा रक्कम तपशील",
    shownAnAmountToBeReturnedAfterBookingCancellation:
      "बुकिंग रद्द केल्यानंतर परत करावयाची रक्कम दर्शविली",
    amountToBeReturned: "परत करावयाची रक्कम",
    bookingCancellationDetails: "बुकिंग रद्दीकरण तपशील",
    budgetingUnit: "बजेटिंग युनिट",
    notesheet_ReferenceNumber: "नोटशीट / संदर्भ क्रमांक",
    billDate: "बिल तारीख",
    remark: "शेरा",
    citizenReasonForCancellation: "रद्द करण्यासाठी नागरिकांचे कारण",
    cancellationRemark: "रद्द करण्याची टिप्पणी",
    bookingDate: "बुकिंग तारीख",
    cancellationDate: "रद्द करण्याची तारीख",
    amountDetails: "रक्कम तपशील",
    refundBreakupDetails: "परतावा तपशील",
    cancellationRateChart: "रद्दीकरण दर चार्ट",
    content: "सामग्री",
    depositAmountPaid: "अनामत रक्कम भरली",
    cancellationCharges: "रद्दीकरण शुल्क",
    totalRefundableAmount: "एकूण परत करण्यायोग्य रक्कम",
    certainFees:
      "1) रद्द करण्याच्या धोरणानुसार गोळा केलेले काही शुल्क (जीएसटी रक्कम) परत करण्यायोग्य नाहीत.",
    deductionAre: "2) कपात रद्द करण्याच्या धोरणानुसार केली जाते.",
    selectApplication: "अर्ज निवडा",

    //depositeRefundProcessing
    searchByAuditoriumBookingNumber: "ऑडिटोरियम बुकिंग नंबर द्वारे शोधा",
    attachDocuments: "कागदपत्रे संलग्न करा",
    depositRefundBillDetails: "अनामत रक्कम परतावा बिल तपशील",
    ecsPayment: "ईसीएस पेमेंट",
    depositeReceiptNo: "जमा पावती क्रमांक",
    depositeAmount: "अनामत रक्कम",
    depositeReceiptDate: "जमा पावतीची तारीख",
    bankAccountNo: "बँक खाते क्रमांक",
    depositRefundProcess: "अनामत रक्कम परतावा प्रक्रिया",
    attachment: "संलग्नक",
    addExtraEquipments: "अतिरिक्त उपकरणे जोडा",
    extraEquipments: "अतिरिक्त उपकरणे",
    extraEquipmentAmount: "अतिरिक्त उपकरणे रक्कम",
    refundableAmount: "परत करण्यायोग्य रक्कम",
    finalRefundableAmount: "अंतिम परत करण्यायोग्य रक्कम",
    details: "तपशील",

    //shift master
    shiftTitle: "शिफ्ट मास्टर",
    timeSlot: "शिफ्ट तास",
    shift: "शिफ्ट नाव",

    durationOfApplicationDistributionAndAcceptance:
      "अर्ज वितरण आणि स्वीकृती कालावधी",
    holidayWeekendSchedule: "सुट्टीचे शनिवार व रविवार वेळापत्रक",

    //Forcefully Cancellation By Department
    forcefullyCancellationByDepartment: "विभागाकडून सक्तीने रद्द करणे",

    //Auditorium bill
    auditoriumBill: "प्रेक्षागृह / नाट्यगृह बिल",
    depositAdjustment: "अनामत रक्कम समायोजन",
    bookingAuditoriumDetails: "प्रेक्षागृह / नाट्यगृह बुकिंग तपशील",
    generateBill: "बिल तयार करा",
    payExtraAmountAndGenerateBill: "अतिरिक्त उपकरणे बिल तयार करा",

    //Reports
    //auditoriumBooking
    applicationDate: "अर्जाची तारीख",
    applicationNumber: "अर्ज क्रमांक",
    loiNo: "एलओआय क्र",
    loiDate: "एलओआय तारीख",
    applicantName: "अर्जदाराचे नाव",
    applicantMobile: "अर्जदार मोबाईल",
    auditorium: "प्रेक्षागृह / नाट्यगृह",
    organizationName: "संस्थेचे नाव",
    deposite: "अनामत रक्कम",
    rent: "भाडे",
    totalAmount: "एकूण रक्कम",
    remarks: "शेरा",
    downloadExcel: "एक्सेल डाउनलोड करा",
    downloadPdf: "पीडीएफ डाउनलोड करा",
    cancel: "रद्द करा",
    submit: "प्रस्तुत",
    process: "प्रक्रिया",
    print: "छापा",
    amount: "रक्कम",

    //payment
    paymentCollection: "पेमेंट संकलन",
    receiptModeDetails: "पावती मोड तपशील",
    paymentType: "पैसे भरण्याची पध्दत",
    paymentMode: "पेमेंट मोड",
    pay: "पैसे भरा",
    upiId: "यूपीआय आयडी",
    upiList: "यूपीआय यादी",
    branchName: "शाखेचे नाव",

    //pgSuccess
    applicationNo: "अर्ज क्रमांक",
    orderId: "ऑर्डर आयडी",
    trackingId: "ट्रॅकिंग आयडी",
    bankRefNo: "बँक संदर्भ क्र",
    billingName: "बिलिंग नाव",
    billingAdd: "बिलाचा पत्ता",
    billingCity: "बिलिंग शहर",
    billingState: "बिलिंग राज्य",
    billingZip: "बिलिंग पिन कोड",
    billingCountry: "बिलिंग देश",
    billingEmail: "बिलिंग ईमेल",
    mobileNo: "मोबाईल क्र",
    totalAmount: "एकूण रक्कम",
    transactionDate: "व्यवहाराची तारीख",
    loiNo: "एलओआय क्र",
    goToList: "बाहेर पडा",
    moduleName: "मॉड्यूलचे नाव",
    extraAmountPaid: "अतिरिक्त उपकरणाची रक्कम यशस्वीरित्या अदा केली",
    extraAmount: "अतिरिक्त उपकरणाची रक्कम",

    //OTHER
    yourPaymentDoneSuccess: "अनामत रक्कम भरली",
    audBookingRentCharges: "प्रेक्षागृह / नाट्यगृह बुकिंग भाडे शुल्क",
    saveAsDraft: "मसुदा म्हणून जतन करा",
    paymentFailed: "पेमेंट रद्द केले",
    orderStatus: "आदेश स्थिती",
    attachmentSchema: "संलग्नक",
    yourRehearsalRentPaymentDoneSuccess: "रंगीत तालीम भाडे रक्कम भरली",
    paymentRehearsalRentFailed: "रंगीत तालीम भाडे भरणे अयशस्वी",
  },
};
