export default {
  en: {
    RoadExcavation_NocPermission: "ROAD EXCAVATION / NOC PERMISSION",
    RoadExcavation_NocPermissionMaintenance:
      "ROAD EXCAVATION / NOC PERMISSION (Maintenance Form)",
    roadTypes: "Road Type",
    srNo: "Sr. No.",
    roadType: "Road Type(in English)",
    roadTypeMr: "Road Type (in Marathi)",
    roadTypePrefix: "Road Prefix (in English)",
    roadTypePrefixMr: "Road Prefix (in Marathi)",
    remarks: "Remark (in English)",
    remarksMr: "Remark (in Marathi)",
    actions: "Actions",
    add: "Add",
    roadTypeName: "Road Type Name",
    update: "Update",
    save: "Save",
    clear: "Clear",
    exit: "Exit",
    date: "Date",
    applicationNumber: "Application No.",
    applicationNumberLOIno: "Application / LOI Number",
    companyName: "Company Name (in English)",
    companyNameMr: "Company Name (in Marathi)",
    brtsRoad: "BRTS Road",
    internalRoad: "Internal Road",
    firstName: "First Name (in English)",
    firstNameMr: "First Name(in Marathi)",
    middleName: "Middle Name (in English)",
    middleNameMr: "Middle Name (in Marathi)",
    lastName: "Last Name (in English)",
    lastNameMr: "Last Name (in Marathi)",
    landLineNo: "LandLine No.",
    mobileNo: "mobile No.",
    emailAddress: " Email Address",
    mainScheme: "Main Scheme",
    subScheme: "Sub Scheme",
    eligibleForSchemeYn: "Eligible For Scheme",
    Y: "Yes",
    N: "No",
    expectedPeriod: "Expected Period (In Months and Days)",
    expectedPeriodInDays: "Expected Period (In Days)",
    scopeOfWork: "Scope Of Work",
    startLatAndStartLng:
      "START Latitude and Longitude Of Excavation(e.g Lat 18.23 and Long 72.34)",
    endLatAndEndLng:
      "END Latitude and Longitude Of Excavation(e.g Lat 18.23 and Long 72.34)",
    locationSameAsPcmcOrderYn:
      "Is Location excavation is same as per PCMC order?",
    lengthSameAsPcmcOrderYn:
      "Is Length excavation is same as per PCMC order? (meter)",
    depthSameAsPcmcOrderYn:
      "Is Depth excavation is same as per PCMC order? (meter)",
    widthSameAsPcmcOrderYn:
      "Is Width excavation is same as per PCMC order? (meter)",
    remark: "Remark",
    requiredDocuments: "Required Documents ",
    upload: "Upload",
    addDocuments: "Add Documents",
    fileUpload: "File Upload",
    cancel: "Cancel",
    // attachmentSchema:"Attachment Schema",
    applicationNo: "Application No",
    companyName: "Company Name",
    fullName: "Full Name",
    applicationDate: "Application Date",
    applicationStatus: "Application Status",
    action: "Action",
    add: "Add",
    roadExcavationApplications: "Road Excavation Applications",
    roadExcavationMaintenanceApplications:
      "Road Excavation Maintenance Applications",
    generateLOI: "Generate Demand Note",
    bookSlot: " Book Slot",
    view: "View",
    generateNOC: "Generate NOC",
    pay: "Pay",
    noc: "NOC",
    receipt: "Receipt",
    receiptNo: "Receipt No.",
    docName: "Document Name",
    docType: "Document Type",
    excavationDetails: "Excavation Details",
    addMore: "Add More",
    zone: "Zone",
    ward: "Ward",
    locationOfExcavation: "Location Of Excavation",
    lengthOfRoad: "Length Of Road (in meter)",
    widthOfRoad: "Width Of Road (in meter)",
    depthOfRoad: "Depth Of Road (in meter)",
    excavationPattern: "Excavation Pattern",
    siteVisit: "Site Visit",
    uploadedDocument: "Uploaded Document",
    REVERT: "REVERT",
    REJECT: "REJECT",
    APPROVE: "ACCEPT",
    juniorEngineerRemark: "Junior Engineer Remark",
    deputyEngineerRemark: "Deputy Engineer Remark",
    excutiveEngineerRemark: "Excutive Engineer Remark",
    additionalCityEngineerRemark: "Additional City Engineer Remark",
    additionalCommissionerRemark: "Additional Commissioner Engineer Remark ",
    commissionerRemark: "Commissioner Remark",
    collectionFeesPenalty: "Collection-(Fees/Penalty)",
    serviceName: "Service Name",
    applicantName: "Applicant Name",
    applicationDetails: "Application Details",
    duePendingAmount: "Dues Pending Amount",
    paymentType: "Payment Type",
    paymentMode: "Payment Mode",
    siteVisitSchedulerandIntimation: "Site Visit Scheduler and Intimation",
    siteVisitId: "Site Visit Id",
    employeeName: "Employee Name",
    time: "Time",
    message: "Message",
    siteVisitAppointmentSchedule: "Site Visit Appointment Schedule",
    addSlotsOfSiteVisit: "Add Slots Of Site Visit",
    fromTime: "From Time",
    toTime: "To Time",
    addNoOfSlot: "Add No.Of Slot's",
    delete: "Delete",
    bookNow: "Book Now",
    submit: "Submit",
    individual: "Individual",
    firm: "Firm",
    natureOfExacavation: "Nature Of Exacation",
    natureOfExcavationPrefix: "Nature Of Exacation Prefix",
    pcmc: "Pimpri-Chinchwad Municipal Corporation,Pune",
    name: "Name",
    DemandNoteGeneration: "Demand Note",
    subHead: "Bombay Municipal Corporation Act 1949, Sections 439/440, 442/479",
    number: "Number",
    natureOfExacavationEng: "Nature Of Exacavation (In English)",
    natureOfExacavationMr: "Nature Of Exacavation (In Marathi)",
    rate: "Rate",
    chargeTypeName: "Charge Type Name",
    amount: "Amount",
    totalAmount: "Total Amount",
    lengthOfExcavationFrom: "Starting Length of Excavation (meter)",
    lengthOfExcavationTo: "Ending Length of Excavation (meter)",
    rateCharge: "Rate Charge",
    rateType: "Rate Type",
    applicationReport: "Application Report",
    maintenanceApplicationReport: "Maintenance Application Report",
    REASIGNE: "REASIGNE",
    nameofBRTSRoad: "Name of BRTS Road",

    // validation labels
    select: "Select",
    companyNameReqEn: "Company Name Required (in english)",
    companyNameReqMr: "Company Name Required (in marathi)",
    firstNameReqEn: "First Name Required (in english)",
    firstNameReqMr: "First Name Required (in marathi)",
    lastNameReqEn: "Last Name Required (in english)",
    lastNameReqMr: "Last Name Required (in marathi)",
    middleNameReqEn: "Middle Name Required (in english)",
    middleNameReqMr: "Middle Name Required (in marathi)",
    landlineNoReq: "Valid Landline Number is Required ",
    mobileNoReq: "Valid Mobile Number is Required ",
    emailAddressReq: "Valid Email Address is Required ",
    categoryOfRoadReq: "Category Of Road is Required ",
    nameOfBRTSRoadReq: "Name Of BRTS Road is Required ",
    nonBRTSRoadZoneReq: "Zone is Required ",
    nonBRTSRoadWardReq: "Ward is Required ",
    nonBRTSRoadLocationOfExcavationReq: "Location Of Excavation is Required ",
    typeOfPavementReq: "Type Of Pavement is Required ",
    typesOfServicesReq: "Type Of Services is Required ",
    otherTypesOfServicesReq: "Other Type Of Services is Required ",
    natureofExcavationReq: "Nature Of Excavation is Required ",
    lengthOfRoadReq: "Length Of Excavation is Required ",
    widthOfRoadReq: "Width Of Excavation is Required ",
    depthOfRoadReq: "Depth Of Excavation is Required ",
    expectedPeriodReq: "Expected Period is Required ",
    scopeOfWorkReq: "Scope Of Work is Required ",
    startLatAndStartLngReq: "Start Lant and Lang is Required ",
    endLatAndEndLngReq: "End Lant and Lang is Required ",
    print: "Print",
    applicationHistory: "Application History",
    senderName: "Sender Name",
    sentDate: "Sent Date",
    sentTime: "Sent Time",
    applicationName: "Module Name",
    siteVisitDate: "Site Visit Date",
    siteVisitTime: "Site Visit Time",
    siteVisitReschedule: "Site Visit Reschedule",
    fromDate:"From Date",
    toDate:"To Date"
  },
  mr: {
    fromDate:"या तारखेपासून",
    toDate:"या तारखेपर्यंत",
    siteVisitReschedule: "साइट भेट रीशेड्यूल",
    siteVisitDate: "साइट भेट तारीख",
    siteVisitTime: "साइट भेट वेळ",
    applicationName: "मॉड्यूलचे नाव",
    print: "छापा",
    number: "क्रमांक",
    RoadExcavation_NocPermission: "रस्ता उत्खनन / एनओसी परवानगी",
    RoadExcavation_NocPermissionMaintenance:
      "रस्ता उत्खनन / एनओसी परवानगी (देखभाल फॉर्म)",
    name: "नाव",
    roadTypes: "रस्त्याचे प्रकार",
    srNo: "अ.क्र.",
    roadType: "रस्त्याचा प्रकार (इंग्रजी मध्ये)",
    roadTypeMr: "रस्त्याचा प्रकार (मराठी मध्ये)",
    roadTypePrefix: "रस्ता उपसर्ग (इंग्रजी मध्ये)",
    roadTypePrefixMr: "रस्ता उपसर्ग (मराठी मध्ये)",
    remarks: "टिप्पणी (इंग्रजी मध्ये)",
    remarksMr: "टिप्पणी (मराठी मध्ये)",
    actions: "क्रिया",
    add: "जोडा",
    individual: "वैयक्तिक",
    roadTypeName: "रस्त्याचे नाव",
    add: "जोडा",
    save: "जतन करा",
    update: "अद्यायावत करा",
    clear: "रिक्त करा",
    exit: "बाहेर पडा",
    date: "तारीख",
    applicationNumber: "अर्ज क्रमांक",
    applicationNumberLOIno: "अर्ज / LOI क्रमांक",
    companyName: "कंपनीचे नाव (इंग्रजी मध्ये)",
    companyNameMr: "कंपनीचे नाव (मराठी मध्ये)",
    brtsRoad: "BRTS रोड",
    internalRoad: "अंतर्गत रस्ता",
    firstName: "पहिले नाव (इंग्रजी मध्ये)",
    firstNameMr: "पहिले नाव (मराठी मध्ये)",
    middleName: "मधले नाव (इंग्रजी मध्ये)",
    middleNameMr: "मधले नाव (मराठी मध्ये)",
    lastName: "आडनाव (इंग्रजी मध्ये)",
    lastNameMr: "आडनाव (मराठी मध्ये)",
    landLineNo: "लँडलाइन क्र.",
    mobileNo: "मोबाईल नंबर",
    emailAddress: "ईमेल",
    mainScheme: "मुख्य योजना",
    subScheme: "उपयोजना",
    eligibleForSchemeYn: "योजनेसाठी पात्रता",
    Y: "होय",
    N: "नाही",
    expectedPeriod: "अपेक्षित कालावधी (दिवस आणि महिन्यात)",
    expectedPeriodInDays: "अपेक्षित कालावधी (दिवसांमध्ये)",
    scopeOfWork: "काम व्याप्ती",
    startLatAndStartLng:
      "उत्खननाचा प्रारंभ अक्षांश आणि रेखांश (उदा. अक्षांश 18.23 आणि रेखांश 72.34)",
    endLatAndEndLng:
      "उत्खनन समाप्ती अक्षांश आणि रेखांश (उदा. अक्षांश 18.23 आणि रेखांश 72.34)",
    firm: "उद्योग",
    locationSameAsPcmcOrderYn:
      "पीसीएमसीच्या आदेशानुसार स्थान उत्खनन समान आहे का?",
    lengthSameAsPcmcOrderYn:
      "पीसीएमसीच्या आदेशानुसार खोदकामाची लांबी समान आहे का?",
    depthSameAsPcmcOrderYn:
      "पीसीएमसीच्या आदेशानुसार उत्खननाची खोली समान आहे का?",
    widthSameAsPcmcOrderYn: "उत्खननाची रुंदी पीसीएमसीच्या आदेशानुसार आहे का?",
    remark: "शेरा",
    requiredDocuments: "आवश्यक कागदपत्रे ",
    upload: "अपलोड करा",
    addDocuments: "दस्तऐवज जोडा",
    fileUpload: "फाइल अपलोड",
    cancel: "रद्द करा",
    applicationNo: "अर्ज क्र",
    companyName: "कंपनीचे नाव",
    fullName: "पूर्ण नाव",
    applicationDate: "अर्जाची तारीख",
    applicationStatus: "अर्ज स्थिती",
    action: "क्रिया",
    add: "जोडा",
    roadExcavationApplications: "रस्ता उत्खनन अनुप्रयोग",
    roadExcavationMaintenanceApplications: "रस्ता उत्खनन देखभाल अनुप्रयोग",
    generateLOI: "डिमांड नोट तयार करा",
    bookSlot: "बुक स्लॉट",
    view: "पहा",
    generateNOC: "एनओसी तयार करा",
    pay: "पैसे द्या",
    noc: "एनओसी",
    receipt: "पावती",
    receiptNo: "पावती क्र",
    docName: "दस्तऐवज नाव",
    docType: "दस्तऐवज प्रकार",
    excavationDetails: "उत्खनन तपशील",
    addMore: "अधिक जोडा",
    zone: "झोन",
    ward: "प्रभाग",
    locationOfExcavation: "उत्खनन स्थान",
    lengthOfRoad: "रस्त्याची लांबी (मीटर)",
    widthOfRoad: "रस्त्याची रुंदी (मीटर)",
    depthOfRoad: "रस्त्याची खोली (मीटर)",
    excavationPattern: "उत्खनन प्रकार",
    siteVisit: "साइटला भेट ",
    uploadedDocument: "अपलोड केलेले दस्तऐवज",
    REVERT: "परत पाठवा",
    REJECT: "नकार द्या",
    APPROVE: "स्वीकारा",
    juniorEngineerRemark: "कनिष्ठ अभियंता  शेरा",
    deputyEngineerRemark: "उपअभियंता शेरा",
    excutiveEngineerRemark: "कार्यकारी अभियंता शेरा",
    additionalCityEngineerRemark: "अतिरिक्त शहर अभियंता शेरा",
    additionalCommissionerRemark: "अतिरिक्त आयुक्त अभियंता शेरा",
    commissionerRemark: "आयुक्त शेरा",
    collectionFeesPenalty: "संकलन(शुल्क/दंड)",
    serviceName: "सेवा नाव",
    applicantName: "अर्जदाराचे नाव",
    applicationDetails: "अर्ज तपशील",
    duePendingAmount: "देय प्रलंबित रक्कम",
    paymentType: "पैसे भरण्याची पध्दत",
    paymentMode: "पेमेंट मोड",
    siteVisitSchedulerandIntimation: "साइट भेट शेड्यूलर आणि माहिती",
    siteVisitId: "साइट भेट आयडी",
    employeeName: "कर्मचारी नाव",
    time: "वेळ",
    message: "संदेश",
    siteVisitAppointmentSchedule: "साइट भेट भेटीचे वेळापत्रक",
    addSlotsOfSiteVisit: "साइट भेटीचे स्लॉट जोडा",
    fromTime: "या वेळेपासून",
    toTime: "या वेळेपर्यंत",
    addNoOfSlot: "स्लॉटची संख्या जोडा",
    delete: "हटवा",
    bookNow: "त्वरा करा",
    submit: "प्रस्तुत करणे",
    natureOfExacavation: "उत्खननाचे स्वरूप",
    natureOfExacavationEng: "उत्खननाचे स्वरूप (इंग्रजी मध्ये)",
    natureOfExacavationMr: "उत्खननाचे स्वरूप (मराठी मध्ये)",
    natureOfExcavationPrefix: "उत्खननाचे स्वरूप उपसर्ग",
    natureOfExcavationCode: "उत्खननाचे स्वरूप कोड",
    pcmc: "पिंपरी चिंचवड महानगरपालिका,पुणे",
    DemandNoteGeneration: "डिमांड नोट ",
    subHead: "मुंबई प्रांतिक महानगरपालिका अधिनियम १९४९, कलमे ४३९/४४०, ४४२/४७९",
    chargeTypeName: "चार्ज प्रकार नाव",
    amount: "रक्कम",
    totalAmount: "एकूण रक्कम",
    lengthOfExcavationFrom: "उत्खननाची सुरुवातीची लांबी (मीटर)",
    lengthOfExcavationTo: "उत्खननाची शेवटची लांबी (मीटर)",
    rate: "दर",
    rateType: "दर प्रकार",
    rateCharge: "दर शुल्क",
    applicationReport: "अनुप्रयोग अहवाल",
    maintenanceApplicationReport: "देखभाल अनुप्रयोग अहवाल",
    REASIGNE: "पुन्हा नियुक्त करणे",

    // validation labels
    select: "निवडा",
    companyNameReqEn: "कंपनीचे नाव आवश्यक (इंग्रजीमध्ये)",
    companyNameReqMr: "कंपनीचे नाव आवश्यक (मराठीत)",
    firstNameReqEn: "प्रथम नाव आवश्यक (इंग्रजीमध्ये)",
    firstNameReqMr: "प्रथम नाव आवश्यक (मराठीत)",
    lastNameReqEn: "आडनाव आवश्यक (इंग्रजीमध्ये)",
    lastNameReqMr: "आडनाव आवश्यक (मराठीत)",
    middleNameReqEn: "मधले नाव आवश्यक (इंग्रजीमध्ये)",
    middleNameReqMr: "मधले नाव आवश्यक (मराठीत)",
    landlineNoReq: "वैध लँडलाइन क्रमांक आवश्यक आहे",
    mobileNoReq: "वैध मोबाईल नंबर आवश्यक आहे",
    emailAddressReq: "वैध ईमेल पत्ता आवश्यक आहे",
    categoryOfRoadReq: "रस्त्याची श्रेणी आवश्यक आहे ",
    nameOfBRTSRoadReq: "बीआरटीएस रस्त्याचे नाव आवश्यक आहे",
    nonBRTSRoadZoneReq: "झोन आवश्यक आहे",
    nonBRTSRoadWardReq: "प्रभाग आवश्यक आहे",
    nonBRTSRoadLocationOfExcavationReq: "उत्खननाचे ठिकाण आवश्यक आहे ",
    typeOfPavementReq: "फुटपाथ प्रकार आवश्यक आहे",
    typesOfServicesReq: "सेवेचा प्रकार आवश्यक आहे",
    otherTypesOfServicesReq: "इतर प्रकारच्या सेवा आवश्यक आहेत",
    natureofExcavationReq: "उत्खननाचे स्वरूप आवश्यक आहे",
    lengthOfRoadReq: "उत्खननाची लांबी आवश्यक आहे",
    widthOfRoadReq: "उत्खननाची रुंदी आवश्यक आहे",
    depthOfRoadReq: "उत्खननाची खोली आवश्यक आहे",
    expectedPeriodReq: "अपेक्षित कालावधी आवश्यक आहे",
    scopeOfWorkReq: "कार्यक्षेत्र आवश्यक आहे",
    startLatAndStartLngReq: "प्रारंभ अक्षांश आणि रेखांश आवश्यक आहे",
    endLatAndEndLngReq: "शेवट अक्षांश आणि रेखांश आवश्यक आहे",
    nameofBRTSRoad: "बीआरटीएस रोडचे नाव",
    applicationHistory: "अनुप्रयोग इतिहास",
    senderName: "पाठवणाराचे नाव",
    sentDate: "पाठवली तारीख",
    sentTime: "पाठवली वेळ",
  },
};
