export default {
  en: {
    mediumPrefix: "Medium Prefix",
    nameOfMedium: "Name of Medium",
    nameOfMediumMr: "Name of Medium in Marathi",
    infoTransferMediumMaster: "Medium Master",
    add: "Add",
    srNo: "Sr.No",
    actions: "Actions",
    address: "Address",
    addressMr: "Address (Marathi)",
    save: "Save",
    update: "Update",
    clear: "Clear",
    exit: "Exit",
    back: "Back",
    rtiApplication:
      "RTI Application -  Right to Information Act 2005, Section 3",
    applicantFirstName: "First Name of Applicant ",
    applicantMiddleName: " Middle Name of Applicant",
    applicantLastName: " Last Name of Applicant",
    applicantFirstNameMr: "First Name of Applicant (Marathi) ",
    applicantMiddleNameMr: "Middle Name of Applicant (Marathi)",
    applicantLastNameMr: "Last Name of Applicant (Marathi)  ",
    gender: "Gender",
    male: "Male",
    female: "Female",
    other: "Other",
    pinCode: "Pincode",
    contactDetails: "Contact No.",
    emailId: "Applicant Email Id",
    education: "Educational Status",
    literate: "Literate",
    illiterate: "Illiterate",
    wardKey: "Ward",
    areaKey: "Area",
    zoneKey: "Zone",
    departmentKey: "Department",
    subDepartmentKey: "Sub department",
    isApplicantBelowToPovertyLine: "Is applicant below to poverty line?",
    bplCardNo: "BPL Card/ List Number",
    yearOfIssues: "Year of Issues",
    issuingAuthority: "Issuing Authority",
    informationSubject: "Information Subject",
    fromDate: "From Date(Related Information)",
    toDate: "To Date(Related Information)",
    description: "Description of information required",
    descriptionMr: "Description of information required(Marathi)",
    yes: "Yes",
    no: "No",
    requiredInfoDeliveryDetails: "Required Information Delivery Details",
    byPost: "By Post",
    byHand: "By Hand",
    softCopy: "Soft Copy/ By Email",
    departmentKey: "Name of Department ",
    subDepartmentKey: "Name of Sub Department",

    rtiAppeal: "RTI Appeal – Right to Information Act 2005, Section 19 (1)",
    applicationNo: "Application No",
    search: "Search",
    descInfoOfOfficer: "Description of Information officer",
    dateOfOfficialorderAgainstAppeal:
      "Date of Official order against the appeal",
    descriptionOfInfo: "Description of Information",
    reqInfoSubjectAndDesc: "Required Information subject and description",
    concernOfficerDeptnmWhoseInfoRequired:
      "Concerned Officer or department name whose information required",
    rtiFileDate: "RTI File Date",
    uploadFile: "Upload Document",

    requiredInfoPurpose: "Subject of Information Purpose",
    reasonForAppeal: "Reason for Appeal",
    paymentModeKey: "Payment Mode",
    paymentAmount: "Application Charges",
    status: "Status",
    rtiApplicationList:
      "RTI Application -  Right to Information Act 2005, Section 3",
    ViewrtiApplication:
      "View RTI Application -  Right to Information Act 2005, Section 3",
    addFile: "Add File",
    appealApplicationNo: "Appeal Application No",
    rtiAppealList: "RTI Appeal – Right to Information Act 2005, Section 19 (1)",
    appealFileDate: "Appeal File Date",
    viewrtiAppeal:
      "View RTI Appeal– Right to Information Act 2005, Section 19 (1)",
    currentStatus: "Current Status",
    isLOIGenerated: "Is Information Charges/Intimation Letter Generated?",
    payment: "Pay Application Fees",
    saveAndPay: "Save and Pay",
    completeApplication: "Complete status of Application",
    loiGenerate: "Intimation Letter",
    closeModal: "Close",
    loiGenerateBtn: "Generate Intimation Letter ",
    serviceName: "Name of Service ",
    noOfPages: "No of Pages",
    chargeType: "Charge Type",
    amount: "Amount",
    totalAmount: "Total Amount",
    remark: "Remarks",
    viewLoi: "View Intimation Letter",
    print: "Print",
    makePayment: "Make a Payment",
    applicationReceivedBy: "Application Received By",
    cfcuser: "CFC User",
    citizenuser: "Citizen User",
    pcmcportal: "PCMC Portal",
    aaplesarkar: "Aaple Sarkar",
    ratePerPage: "Rate Per Page",
    fileSize: " File size must be less than 2MB",
    fileExtension: "Attach Only .JPG, .PNG, .JPEG  and .PDF files",
    cancel: "Cancel",
    fileUpload: "File Upload",
    addDoc: " ADD DOCUMENTS",
    uploadDoc: "UPLOAD DOCUMENT/IMAGE",
    informationRemark: "Information Ready Remark",
    infoReady: "Information Ready",
    infoPages: "Information Pages",
    selectedReturnMedia: "Selected Return Media",
    infoReadyDate: "Information Ready Date",
    completeDate: "Outward Date",
    completeRemark: "Complete Remark",
    informationReturnMedia: "Information Return Media",
    hearingSchedule: "Hearing Schedule",
    decisionEntry: "Decision Entry",
    Tnc: "ACCEPT TERMS AND CONDITION",
    applicantName: "Name of Applicant",
    appealNo: "Appeal No",
    scheduleDate: " Scheduled Date for Hearing",
    scheduleTime: "Schedule Time for Hearing",
    venueForHearing: "Venue for Hearing",
    subject: "Subject",
    rtiApplicationNO: "RTI Application No",

    decisiontakenInHearing: "Decision taken in hearing",

    decisionStatus: "Decision Status by department",
    decisionOrderAttach: "Decision order upload",
    updloadScanInfoDelivered:
      "According to Order Upload Scan Copy of Information Delivered ",
    hearingReschedule: "Hearing Reschedule",
    completeAppeal: "Complete Status of Appeal",
    decisionDetails: "Decision Details",
    documents: "Documents",
    completeDoc: "Complete Documents",
    RTIApplicationdoc: "RTI Application Documents",
    RTIAppealdoc: "RTI Appeal Documents",
    forwardApplication: "Forward/Transfer Application",
    currentdept: "Current department",
    currentSubDept: "Current sub department",
    forwardApplication: "Forward Application",
    forwardToDept: "Forward to department",
    forwardTosubDept: "Forward to sub department",
    downloadLoiReceipt: "Download Service Acceptance Letter Receipt",
    addInfo: "Additional Information",
    downloadAcknowldgement: "Download Acknowledgement",
    print: "Print",
    pimpariChinchwadMaha: "Pimpri Chinchwad Municipal Corporation",
    appAcknowldgement: "Application Acknowledgement",
    ackDear: "To",
    ackpcmcthanku:
      "Thank you for using PCMC Pimpri Chinchwad Citizen Service Portal !!",
    ackshortDesc:
      "Your application for Right To Information under PCMC has been successfully submitted.",
    ackRTIAppealshortDesc:
      "Your application for Right To Information Appeal under PCMC has been successfully submitted.",

    ackApplicationSummery: "Application Summary",
    applicationNo: "Application No",
    dateofApplication: "Date of the Application",
    ackplzContactNearestOperator:
      "For any query please contact your nearest operator or the following contact details:",
    ackpcmcAddress: "Mumbai Pune Highway Pimpri Pune 411 018",
    ackPcmcphNo:
      "Phone: 91-020-2742-5511/12/13/14 67333333 / for direct contact please dial 6733 and extension no.and Fax: 91-020-27425600 / 67330000 Email: egov@pcmcindia.gov.in / sarathi@pcmcindia.gov.in",
    ackstateCountry: "Maharashtra, India",
    applicantAddress: "Applicant Address",
    other: "Other",
    rti: "RTI",
    no1: "1)",
    no2: "2)",
    chargeNm: "Name of Charge",
    loiNo: "Intimation Letter No",
    rtiApplicationAmt: "Your application has been accepted.",
    determineandPayAmt: "Please pay the fees prescribed below.",
    contactNearestpcmcDivisionalOffice:
      "Or visit the nearest Pimpri Chinchwad Municipal Corporation Divisional Office.",
    serviceAcceptance: "Service Acceptance Letter",
    isApplicationMultiDept: "Is application under multi department?",
    addDepartment: "Add Department",
    parentRemark: "Parent Remark",
    forwardRemark: "Forward Remark",
    applicationType: "Application Type",

    welcomeToTheDashboard: "Welcome To The Dashboard",
    dashboardTotalCount: "Total Applications",
    dashboardInProgress: "In Progress",
    dashboardLoiGenerated: "Generated Intimation Letter ",
    dashboardInfoReady: "Information Ready",
    dashboardCompleted: "Completed Application",
    dashboardHearingScheduled: "Hearing Scheduled",

    dashboardTotalAppealCount: "Total Appeal",
    dashboardCompletedAppeal: "Completed Appeal",

    goToAppeal: "Go To Appeal",

    applicationinfoReady: "Application Information Ready",
    appealInfoReady: "Appeal Information Ready",

    ///////////////// FOR REPORTS ADDED BY ANWAR ANSARI /////////
    rtiApplicationRegister: "RTI APPLICATION REGISTER",
    applicationNumber: "Application Number",
    fullName: "Full Name",
    descriptioniOfInformationRequired: "Description Of Information Required",
    dateOfOrderAgainstAppeal: "Date of Official Order Against Appeal",
    descriptionOfInformation: "Description Of Information",
    concernDepartmentOrOffice: "Concerned Department Or Officer",
    reasonOfAppeal: "Reasons of the Appeal",
    informationPurpose: "Information Purpose",

    toDateR: "To Date",
    fromDateR: "From Date",

    submit: "Submit",
    downloadEXCELL: "Download Excel",
    downloadPDF: "Download Pdf",
    cancel: "Cancel",
    //////////////////////////////////////////////
    rtiApplicationDashboard: "RTI APPLICATION DASHBOARD",
    rtiAppealRegister: "RTI APPEAL REGISTER",
    subjectName: "Name of Subject ",
    systemEntryDate: "System Entry Date",
    wards: "Ward",
    bplCardNumber: "BPL Card/ List Number",
    isApplicantBPL: "Is Applicant BPL",
    deptName: "Name of Department",
    /////////////////////////////////////////////////
    vivaranPatra01: "Vivaranpatra 01",
    vivaranPatra02: "Vivaranpatra 02",
    vivaranPatra03: "Vivaranpatra 03",
    vivaranPatra04: "Vivaranpatra 04",
    vivaranPatra05: "Vivaranpatra05",

    monthName: "Month",
    count: "Count",

    periodOfRelatedInformation: "Period Of Related Information",

    year: "Year",
    descriptionOfInformationOfficer: "Description Of Information Officer",

    serialNumber: "Serial Number",
    deptWiseCollection: "DEPARTMENT WISE COLLECTION",
    strFromDate: "From Date",
    strToDate: "To Date",
    total: "Total",
    totalApplication: "Total Application",
    grandTotal: "Grand Total",
    requiredInformationByPostOrPersonallly:
      "Required Information By Post Or Personallly",
    applicationDate: "Date of Application ",
    departmentName: "Name of Department",
    fileNm: "File Name",
    fileType: "File Type",
    transferRemark: "Transfer Remark",
    viewAttach: "View Attachment",
    rtiDueDate: "RTI Due Date",
    totalNoOfDays: "Remaining Days",
    viewDoc: "View",

    //////////////////////rtiapplication wise collection label changes by shubham/////////////////
    appWiseCollection: "APPLICATION WISE COLLECTION",
    applicationName: "Application Name",
    serviceAcceptanceCharges: "Service Acceptance Charges",
    serviceCharges: "Service Charges",
    lastMonthPendingAppCount: "Last Month Pending application Count",
    reportingMonthRecivedAppConunt:
      "In Reporting Month's received application count",
    reportingMonthClearanceConunt:
      "In Reporting Month's application clearance count",
    infoDeleverdRTIAppCount:
      "Information Delivered as per RTI Application Count",
    infoRejectedRTIAppCount:
      "Information Rejected as per RTI Application Count",
    pendingAppCount: "Pending Application Count",
    reportingMonthRecivedAppealConunt:
      "In Reporting Month's received appeal count",
    reportingMonthAppealClearanceConunt:
      "In Reporting Month's appeal clearance count",
    appealAcceptedConunt: "Appeal Accepted Count",
    appealRejectedConunt: "Appeal Rejected Count",
    pendingAppealConunt: "Pending Appeal Count",
    lastMonthPendingAppealCount: "Last Month Pending Appeal Count",
    reportingMonthDeleveredAppealCount:
      "In Reporting Months Delivered Appeal Count",
    pendingAppealCount: "Pending Appeal Count",
    searchArea: "Search Area",
    getDetails: "Get Details",
    results: "Results",
    attachDoccument: "Attach document",
    thirdPartyAattachDoccument: "Attach thirdParty document if applicable",
    rtiTermsndTitle: "Pimpri Chinchwad Municipal Corporation, Pimpri-411018",
    childDeptTitle: "Child Application Departments",
    rtiAct2005: "RTI Act, 2005 ",
    guidelineOfRti: "GUIDELINES FOR USE OF RTI ONLINE PORTAL",
    guideline1:
      "1)	This Web Portal can be used by Indian citizens to file RTI application online and also to make payment for RTI application online. First appeal can also be filed online.",
    guideline2:
      "2) An applicant who desires to obtain any information under the RTI Act can make a applicatin through this Web Portal to the Pimpri Chinchwad Mahanagarpalika.",
    guideline3: `3) On clicking at "Submit Application", the applicant has to fill the required details on the page that will appear.`,
    guideline4:
      "4) The fields marked * are mandatory while the others are optional ",
    guideline5:
      "5) The text of the application may be written at the prescribed column.",
    guideline6:
      "6) At present, the text of an application that can be uploaded at the prescribed column is confined to 3000 characters only.",
    guideline7:
      "7) Only alphabets A-Z a-z number 0-9 and special characters, . - _ ( ) / @ : & ?  % is allowed in Text for RTI Request application.",
    guideline8:
      '8) In case an application contains more than 3000 characters, it can be uploaded as an attachment, by using column "Supporting document". ',

    guideline9:
      "9) Do not upload Aadhar Card or PAN Card or any other personal Identification (Except BPL Card).",
    guideline10: "10) PDF file name should not have any blank spaces.",
    guideline11:
      '11) After filling the application, the applicant has to click on "Make Payment" to make payment of the prescribed fee.',
    guideline12:
      "12) The applicant can pay the prescribed fee through the following modes: (a)Internet banking; (b) Using credit/debit card of Master/Visa; c) Using RuPay Card.",
    guideline13:
      "13) Fee for making an application is as prescribed in the RTI Rules.",
    guideline14: "14) After making payment, an application can be submitted.",
    guideline15:
      "15) After making payment, if applicant didn’t receive the registration number then applicant is advised to wait for the 24-48 working hours as registration number will be generated after reconciliation. Please do not make additional attempt to make payment again. If it is not generated within 24-48 hours kindly send an e-mail at help (sarthi@pcmcindia.gov.in), (egov@pcmcindia.com) with transaction details.",
    guideline16:
      "16) No RTI fee is required to be paid by any citizen who is below poverty line as per RTI Rules. However, the applicant must attach a copy of the certificate issued by the appropriate authority in this regard, along with the application.",
    guideline17:
      "17) On submission of an application, a unique registration number would be issued, which may be referred by the applicant for any references in future.",
    guideline18:
      '18) The application filed through this Web Portal would reach electronically to the "Nodal Officer" of concerned Department, who would transmit the RTI application electronically to the concerned PIO.',
    guideline19:
      "19) In case additional fee is required representing the cost for providing information, the PIO would intimate the applicant through this portal. This intimation can be seen by the applicant through Status Report or through his/her e-mail alert.",
    guideline20:
      '20) For making an appeal to the first Appellate Authority, the applicant has to click at "Submit First Appeal" and fill up the page that will appear.',

    guideline21:
      "21) The registration number of original application has to be used for reference.",
    guideline22:
      "22) The applicant/the appellant should submit his/her mobile number to receive SMS alert.",
    guideline23:
      '23) Status of the RTI application/first appeal filed online can be seen by the applicant/appellant by clicking at "View Status".',
    guideline24:
      "24)All the requirements for filing an RTI application and first appeal as well as other provisions regarding time limit, exemptions etc., as provided in the RTI Act, 2005 will continue to apply.",
    guideline25:
      "25) All provisions mentioned in RTI Act 2005 are applicable to the RTI Application and RTI Appeal Application.",
    guideline26:
      "26) A RTI application should cover only one subject and the word limit should be up to 150. Should apply separate application for the second subject.",

    mediumPrefReq: "Medium Prefix is Required !!!",
    nmOfMediumReq: "Name of Medium is Required !!!",
    nmOfMediumReqMr: "Name of Medium in Marathi is Required !!!",

    mediumMinLeng: "Name of medium must be at least 2 character",
    mediumMaxLen: "Name of medium is too long",

    mediumMinLengMr: "Name of medium in marathi must be at least 2 character",
    mediumMaxLenMr: "Name of medium in marathi is too long",

    mediumPrefMinLeng: "Medium Prefix must be at least 2 character",
    mediumPrefMaxLen: "Medium Prefix is too long",

    decisionMinLen: "Decision details must be at least 20 character",
    decisionMaxLen: "Decision details is too long",
    decisionReq: "Decision taken in hearing is Required !!!",
    decisionStatusReq: "Decision status is Required !!!",
    remarkReq: "Remarks is Required !!!",
    venueReq: "Venue is Required !!!",
    chargeTypeReq: "Charge Type Required !!!",

    educationReq: "Education Status is Required !!!",
    areaNmReq: "Name of Area is Required !!!",
    wardNmReq: "Name of Ward is Required !!!",
    zoneNmReq: "Name of Zone is Required !!!",
    deptReq: "Name of Department is Required !!!",
    isBplReq: "Is applicant below to poverty line is Required !!!",
    addReq: "Address is Required !!!",
    addMrReq: "Address(Marathi) is Required !!!",

    descriptionReq: "Descrition of required Information is Required !!!",
    reasonForAppealReq: "Reason for appeal is Required !!!",

    appliFirstNmReq: " First Name of Applicant is Required !!!",
    appliMiddNmReq: "Middle Name of Applicant is Required !!!",
    appliLastNmReq: "Last Name of Applicant is Required !!!",
    genderReq: "Gender is Required !!!",
    pincodeReq: "Pincode is Required !!!",
    inCorrectMsg: "Incorrect format",
    emailReq: "Applicant Email Id is Required !!!",
    contactReq: "Contact No is Required !!!",
    attachDate: "Attached Date",

    uploadTitle: "Upload",
    descriptionMaxLen: "Description is exceeding limit",
    addressMaxLen: "Address is exceeding limit",
    reasonMaxLen: "Reason of appeal is exceeding limit",
    remarkMaxLen: "Remarks is exceeding limit",
    venueMaxLen: "Venue is exceeding limit",
    decisionStatussMaxLen: "Decision status is exceeding limit",
    appealDecision: "Appeal Decision",
    applicationCurrentStatus: "RTI application Current status",

    mustBeOnlyNum: "Must be only digits",
    allowNum: "Allow only number",
    noOfPageMin: "No of Pages must be at least 1 number",
    noOfPagesMax: "No of Pages not valid on above 5 number",
    noOfPageReq: "No of pages is required",
    totalMax: "Total Amount exceeds is exceeding limit",
    ratePerPageReq: "Rate per page is required",
    ratePerPageMin: "Rate per page must be at least 1 number",
    ratePerPageMax: "Rate per page not valid on above 4 number",

    // /////////////////////changes in rtiapplication label by shubham ///////////////////
    requiredInformationPurposeMaxLen:
      "Subject of Information Purpose is exceeding limit",
    requiredInformationPurpose: "Subject of Information Purpose",
    requiredInformationPurposeMr: "Subject of Information Purpose (Marathi)",
    requiredInformationPurposeReq: "Subject of Information Purpose is required",
    paymentCollection: "Payment Collection",
    datePayment: "Date",
    receiptModeDetails: "Receipt Mode Details",
    paymentType: "Payment Type",
    paymentMode: "Payment Mode",
    pay: "Pay",
    newText: "New",
    applicationWithSLA: "In time period",
    applicationWithoutSLA: "Overdue",
    outwardNumber: "Outward Number",
    helpDeskRTI: "RTI Help Desk ",
    amountInWord: "Amount in words",
    receipthead: "Pimpri Chinchwad Municipal Corporation, Pimpari 411018",
    receiptTitle: "Civil Facilities Center",
    receiptHeader: "Receipt of payment(Computer System)",
    receiptNo: "Receipt No",
    challenNo: "Challen No",
    receiptTime: " Time",
    saveAsDraft: "Save As Draft",
    officeLocation: "Office Location",
    zoneOfficeWiseDepartment: "Zone, Office Location Wise Department Mapping",

    officeLocationReq: "Office Location is Required",
    rejectCat: "Rejected Category",
    rejectCatMr: "Rejected Category(Marathi)",
    rejectCatReq: "Rejected Category is required",
    rejectCatMrReq: "Rejected Category(Marathi) is required",

    rejectedCatMrCharacterValidation:
      "Only characters are allowed in Rejected Category (Marathi).",
    rejectedCatCharacterValidation:
      "Only characters are allowed in Rejected Category.",

    rejectedCatMrCharacterLengthValidation:
      "Rejected Category Marathi Name should not exceed 100 characters",

    rejectedCatCharacterLengthValidation:
      "Rejected Category Name should not exceed 100 characters",

    totalAmtReq: "Total amount is required",

    accept: "Accept",
    reject: "Reject",
    rejectedSection: "Rejected Section",
    rejectedRemark: "Rejected Remark",
    forwardToOfficeLocation: "Forward To Office Location",
    forwardTozoneKey: "Forward To Zone",
    formDateReq: "Related Information From Date is Required !!!",
    toDateReq: "Related Information To Date is Required !!!",
    applicantFirstnmMax:
      "First Name of Applicant should not exceed 50 characters",
    middleNameMax: "Middle Name of Applicant should not exceed 50 characters",
    lastNameMax: "Last Name of Applicant should not exceed 50 characters",
    pinCodeValidtion: "Pincode is Required !!!",
    pinCodeValidtionLength: "Pincode should not exceed 6 characters",
    reqInfoDeliveryDetailsReq:
      "Required Information Delivery Details is required",

    bplCardNoMaxLen: "BPL Card/ List Number not exceed 10 character",
    issuingAuthMax: "Issuing authority exceed 100 character",
    emailIdMax: "Applicant Email Id should not exceed 80 characters",
    totalAmountMin: "Total amount should not be zero",
    yourPaymentDoneSuccess: " Your payment done successful!!!",
    paymentFailed: "Payment failed!!!",
    orderId: "Order Id ",
    trackingId: "Tracking Id",
    bankRefNo: "Bank Reference No",
    billingName: "Name",
    billingAdd: "Address",
    billingCity: "City",
    billingZip: "Zipcode ",
    billingCountry: "Country",
    billingEmail: "Email",
    mobileNo: "Mobile No",
    billingState: "State",
    transactionDate: "Transaction Date",
    goToList: "Go To Dashboard",
    serviceChargeReceipt: "Service Charges Receipt",
    pcmc: "Pimpri-Chinchwad Municipal Corporation",
    fiscalYear: "F.Y.",
    date: "Date",
    relatedTo: "Related To",
    cfcRefNo: "CFC Ref. No",
    cfcCounterNo: "CFC Counter No.",
    receivedFrom: "Received From",
    rti: "RTI Online System",
    narration: "Narration",
    applicationServiceReceipt: "Application Service Charge Receipt",
    appealServiceReceipt: "Appeal Service Charge Receipt",

    officeCopy: "OFFICE COPY",
    customerCopy: "CUSTOMER COPY",
    rupees: "Rupees",
    chequeNo: "Cheque No.",
    chequeDate: "Cheque Date",
    bankName: "Name of Bank ",
    referenceNo: "Bank Reference No.",
    details: "Details",
    payableAmount: "Payable Amount",
    receivedAmount: "Received Amount",
    rebateAmount: "Rebate/Concession Amount",
    advanceAmount: "Advance Amount",
    actualPayableAmount: "Actual Payable Amount",
    receiverSignature: `Receiver's Signature`,
    printBy: "Name",
    printDateAndTime: "Date and Time",
    iagreeForOnlinePay: "I Agree For Online Payment",
    acknowldgementNo: "Acknowldgement No",
    loiPayment: "Charges of Intimation Letter ",
    loiPaymentReceipt: "Receipt of Intimation Letter ",
    paymentCancelled: "Payment Cancelled",
    selectMonthYr: "Select Month and Year",
    pinCodeValidtionMinLength: "Pincode must be 6 digits",
    mobMaxValLen: "Contact No. must be 10 digits",
    mobMinValLen: "Contact No. must be 10 digits",

    softCopyNote:
      "Note: (If the information is available in a soft copy format, it will be provided in the same or else it will be provided as a hard copy)",
    addMore: "Add More",
    rate: "Rate",
    quantity: "Quantity",
    completeNote:
      " Note - If you are not satisfied with the information provided, you can file an appeal with the Appellate Authority within 30 days from the date of receipt of this information.",
    trackOldRTIApplication: "Track Old RTI Application",
    OldRTIApplication: "Old RTI Applications",
    trackOldRTIApplicationHistory: "History Of Track Old RTI Application",
    searchFilter: "Search By Filter",
    finalRemark: "Final Remark",
    applicationDateOld: "Application Date",

    backToDashboard: "Back To Dashboard",
    villageName: "Name of Village",
    rtiAdhikariNm: "Name of RTI Adhikari ",
    bplCardDoc: "Attach BPL proof document :",
    fileNotUpload: "File Not Uploaded",
    dataNotAvail: "Data Not Available",
    infoSentByPost: "Information sent by post",
    infoProvidedByPerson: "Information provided in-person",
    postalService: "Post Type",
    place: "Place",
    placeReq: "Place is required",
    officerTitle: "RTI Application and RTI Appeal Officers details",
    officerName: "Name of Officer",
    designation: "Designation",
    officialAddress: "Official Address",
  },

  mr: {
    mediumPrefix: "माध्यम उपसर्ग",
    nameOfMedium: "माध्यमाचे नाव",
    nameOfMediumMr: "माध्यमाचे नाव मराठी",
    infoTransferMediumMaster: "माध्यम मास्टर",
    srNo: "अ.क्र.",
    actions: "क्रिया",
    add: "जोडा",
    save: "जतन करा",
    update: "अद्यायावत करा",
    clear: "रिक्त",
    exit: "बाहेर पडा",
    rtiApplication: "आरटीआय अर्ज - माहितीचा अधिकार कायदा 2005, कलम 3",
    applicantFirstName: "अर्जदाराचे प्रथम नाव",
    applicantMiddleName: "अर्जदाराचे मधले नाव",
    applicantLastName: "अर्जदाराचे आडनाव",
    applicantFirstNameMr: "अर्जदाराचे प्रथम नाव (मराठी)",
    applicantMiddleNameMr: "अर्जदाराचे मधले नाव (मराठी)",
    applicantLastNameMr: "अर्जदाराचे आडनाव (मराठी)",
    gender: "लिंग",
    male: "पुरुष",
    female: "स्त्री",
    other: "इतर",
    pinCode: "पिन कोड",
    contactDetails: "संपर्क क्र.",
    emailId: "अर्जदाराचा ईमेल आयडी",
    education: "शैक्षणिक स्थिती",
    literate: "साक्षर",
    illiterate: "निरक्षर",
    // wardKey: "प्रभाग",
    areaKey: "क्षेत्र",
    wardKey: "प्रभाग",
    zoneKey: "झोन",
    departmentKey: "विभाग",
    subDepartmentKey: "उपविभाग",
    isApplicantBelowToPovertyLine: "अर्जदार दारिद्र्य रेषेखालील आहे का?",
    bplCardNo: "बीपीएल कार्ड/ यादी क्रमांक",
    yearOfIssues: "कार्ड वितरीत वर्ष",
    issuingAuthority: "कार्ड मान्यता अधिकारी यांचे नाव",
    informationSubject: "माहितीचा विषय",
    fromDate: "तारखेपासून (संबंधित माहिती)",
    toDate: "तारखेपर्यंत (संबंधित माहिती)",
    description: "आवश्यक असलेल्या माहितीचे वर्णन",
    descriptionMr: "आवश्यक असलेल्या माहितीचे वर्णन (मराठी)",
    yes: "होय",
    no: "नाही",
    requiredInfoDeliveryDetails: "आवश्यक माहिती वितरण तपशील",
    byPost: "पोस्टाने",
    byHand: "हाताने",
    softCopy: "सॉफ्टकॉपी /ई- मेलद्वारे",
    address: "पत्ता",
    addressMr: "पत्ता (मराठी)",
    departmentKey: "विभागाचे नाव",
    subDepartmentKey: "उपविभागाचे नाव",

    rtiAppeal: "आरटीआय अपील - माहितीचा अधिकार कायदा 2005, कलम 19 (1)",
    applicationNo: "नोंदणी क्र",
    search: "शोधा",
    descInfoOfOfficer: "माहिती अधिकाऱ्याचा तपशील",
    dateOfOfficialorderAgainstAppeal:
      "ज्या आदेशाविरुद्ध अपिल केले तो आदेश मिळाल्याची दिनांक",

    descriptionOfInfo: "माहितीचा तपशील",
    reqInfoSubjectAndDesc: "आवश्यक असलेल्या माहितीचे स्वरूप आणि विषय",
    concernOfficerDeptnmWhoseInfoRequired:
      "माहिती ज्या कार्यालयाशी किंवा विभागाशी संबंधित विभागाशी आहे त्याचे नाव",
    requiredInfoPurpose: "ज्यासाठी माहिती आवश्यक आहे ते प्रयोजन",
    reasonForAppeal: "अपिलाचे कारण",
    paymentModeKey: "देय प्रकार",
    paymentAmount: "अर्ज शुल्क",
    rtiFileDate: "आरटीआय फाइलची तारीख",
    status: "स्थिती",
    rtiApplicationList: "आरटीआय अर्ज यादी- माहितीचा अधिकार कायदा 2005, कलम 3",
    ViewrtiApplication: "आरटीआय अर्ज पहा-माहितीचा अधिकार कायदा 2005, कलम 3",

    appealApplicationNo: "अपील अर्ज क्र",
    rtiAppealList: "आरटीआय अपील यादी",
    appealFileDate: "अपील फाइलची तारीख",
    viewrtiAppeal: "आरटीआय अपील पहा",
    currentStatus: "वर्तमान स्थिती",
    loiGenerate: "माहिती शुल्क",
    isLOIGenerated: "माहिती शुल्क/सूचना पत्र उत्पन्न करणे आवश्यक आहे?",
    payment: "अर्ज शुल्क भरा",
    saveAndPay: "जतन करा आणि पैसे द्या",
    completeApplication: "अर्जाची संपूर्ण स्थिती",
    closeModal: "बंद करा",
    loiGenerateBtn: "सूचना पत्र उत्पन्न करा",
    serviceName: "सेवेचे नाव",
    noOfPages: "पृष्ठांची संख्या",
    chargeType: "शुल्क प्रकार ",
    amount: "रक्कम",
    totalAmount: "एकूण रक्कम",
    remark: "शेरा",
    completeRemark: "पूर्ण टिप्पणी",

    viewLoi: "सूचना पत्र पहा",
    print: "छापणे",
    makePayment: "पैसे भरा",
    applicationReceivedBy: "द्वारे अर्ज प्राप्त झाला",
    cfcuser: "CFC वापरकर्ता",
    citizenuser: "नागरिक वापरकर्ता",
    pcmcportal: "PCMC पोर्टल",
    aaplesarkar: "आपल सरकार",
    ratePerPage: "प्रति पृष्ठ दर",
    fileSize: " फाइल आकार 2MB पेक्षा कमी असणे आवश्यक आहे",
    fileExtension: "फक्त .JPG, .PNG, .JPEG आणि .PDF फाइल्सना अनुमती द्या",
    cancel: "रद्द करा",
    fileUpload: "फाइल अपलोड",
    addDoc: " दस्तऐवज जोडा",
    uploadDoc: "दस्तऐवज/इमेज अपलोड करा",
    informationRemark: "माहिती तयार टिप्पणी",
    inforReady: "माहिती तयार",
    infoPages: "माहिती पृष्ठे",
    selectedReturnMedia: "माहिती रिटर्न मीडिया",

    infoReadyDate: "माहिती तयार तारीख",
    completeDate: "जावक तारीख",
    informationReturnMedia: "माहिती रिटर्न मीडिया",
    hearingSchedule: "सुनावणीचे वेळापत्रक",
    decisionEntry: "निर्णय प्रवेश",

    applicantName: "अर्जदाराचे नाव",
    appealNo: "अपील क्र",
    scheduleDate: "सुनावणीसाठी नियोजित तारीख",
    scheduleTime: "सुनावणीसाठी नियोजित वेळ",
    venueForHearing: "सुनावणीचे ठिकाण",

    subject: "विषय",
    rtiApplicationNO: "आरटीआय अर्ज क्र",
    decisiontakenInHearing: "सुनावणीत घेतलेला निर्णय",

    decisionStatus: "विभागानुसार निर्णयाची स्थिती",
    decisionOrderAttach: "निर्णय आदेश अपलोड",
    updloadScanInfoDelivered:
      "आदेशानुसार वितरित केलेल्या माहितीची स्कॅन प्रत अपलोड करा",
    hearingReschedule: "सुनावणीचे पुन्हा वेळापत्रक",
    completeAppeal: "अपीलची संपूर्ण स्थिती",
    decisionDetails: "निर्णय तपशील",
    documents: "दस्तऐवज",
    completeDoc: "पूर्ण कागदपत्रे",
    RTIApplicationdoc: "आरटीआय अर्जाची कागदपत्रे",
    RTIAppealdoc: "आरटीआय अपील कागदपत्रे",
    forwardApplication: "अग्रेषित/हस्तांतरण अर्ज",
    currentdept: "वर्तमान विभाग",
    currentSubDept: "वर्तमान उपविभाग",
    forwardApplication: "अर्ज फॉरवर्ड करा",
    forwardToDept: "विभागाकडे पाठवा",
    forwardTosubDept: "उपविभागाकडे पाठवा",
    downloadLoiReceipt: "सेवा स्वीकृती पत्र डाउनलोड करा",
    addInfo: "अतिरिक्त माहिती",
    downloadAcknowldgement: "पावती डाउनलोड करा",
    print: "छापणे",
    pimpariChinchwadMaha: "पिंपरी चिंचवड महानगरपालिका",
    appAcknowldgement: "पोच पावती",
    ackDear: "प्रति",
    ackpcmcthanku: "पिंपरी चिंचवड नागरिक सेवा वापरल्याबद्दल धन्यवाद !!",

    ackshortDesc:
      "पिंपरी चिंचवड महापालिकेअंतर्गत येणाऱ्या नागरिक सेवा अंतर्गत तुमचा माहिती अधिकार अर्ज यशस्वीरीत्या सादर झाला आहे.",
    ackRTIAppealshortDesc:
      "पिंपरी चिंचवड महापालिकेअंतर्गत येणाऱ्या नागरिक सेवा अंतर्गत तुमचा माहिती अधिकार अपील अर्ज यशस्वीरीत्या सादर झाला आहे.",
    ackApplicationSummery: "अर्जाचा तपशील",
    applicationNo: "नोंदणी क्रमांक",
    dateofApplication: "अर्ज दिनांक",
    ackplzContactNearestOperator:
      "कोणत्याही प्रश्नासाठी कृपया तुमच्या जवळच्या ऑपरेटरशी संपर्क साधा खालील संपर्क तपशील:",
    ackpcmcAddress: "मुंबई पुणे महामार्ग पिंपरी पुणे ४११ ०१८",
    ackPcmcphNo:
      "फोन:९१-०२०-२७४२-५५११/१२/१३/१४ ६७३३३३३३/ थेट संपर्कासाठी कृपया ६७३३ डायल करा आणि विस्तार क्र. आणि फॅक्स: ९१-०२०-२७४२५६०० /६७३३०००० ईमेल: egov@pcmdcm.gov.in/ sarathi@pcmcindia.gov.in",
    ackstateCountry: "महाराष्ट्र, भारत",
    applicantAddress: "अर्जदाराचा पत्ता",
    rti: "माहिती अधिकार",
    no1: "१)",
    no2: "२)",
    chargeNm: "शुल्काचे नाव",
    loiNo: "सूचना पत्र क्र",
    rtiApplicationAmt: "आपला अर्ज स्वीकृत केला असून",
    determineandPayAmt: "पुढील प्रमाणे शुल्क भरण्यात यावे .",
    contactNearestpcmcDivisionalOffice:
      "किंवा जवळील पिंपरी चिंचवड महानगरपलिका विभागीय कार्यालयाला भेट द्या.",

    serviceAcceptance: "सेवा स्वीकृती पत्र",
    isApplicationMultiDept: "बहु विभागांतर्गत अर्ज आहे का?",
    addDepartment: "विभाग जोडा",
    parentRemark: "पॅरेंट टिप्पणी",
    forwardRemark: "अग्रेषित टिप्पणी",

    applicationType: "अर्जाचा प्रकार",

    welcomeToTheDashboard: "डॅशबोर्डवर आपले स्वागत आहे",
    dashboardTotalCount: "एकूण अर्ज",
    dashboardInProgress: "प्रगतीपथावर आहे",
    dashboardLoiGenerated: "सेवा स्वीकृती पत्र उत्पन्न",
    infoReady: "माहिती तयार",

    dashboardInfoReady: "माहिती तयार",
    dashboardCompleted: "पूर्ण केलेले अर्ज",
    dashboardHearingScheduled: "सुनावणी नियोजित",

    dashboardCompletedAppeal: "पूर्ण केलेले अपील",
    dashboardTotalAppealCount: "एकूण अपील",
    goToAppeal: "अपील वर जा",

    applicationinfoReady: "अर्ज माहिती तयार आहे",
    appealInfoReady: "अपील माहिती तयार आहे",

    ///////////////// FOR REPORTS ADDED BY ANWAR ANSARI /////////
    rtiApplicationRegister: "आरटीआय अर्ज नोंदणी",
    applicationNumber: "अर्ज क्रमांक",
    fullName: "पूर्ण नाव",
    descriptioniOfInformationRequired: "आवश्यक माहितीचे वर्णन",
    dateOfOrderAgainstAppeal: "अपील विरुद्ध आदेशाची तारीख",
    descriptionOfInformation: "माहितीचे वर्णन",
    concernDepartmentOrOffice: "संबंधित विभाग किंवा कार्यालय",
    reasonOfAppeal: "अपीलचे कारण",
    informationPurpose: "माहितीचा उद्देश",

    toDateR: "या तारखे पर्यंत",
    fromDateR: "या तारखेपासून",

    submit: "प्रस्तुत करा",
    downloadEXCELL: "एक्सेल डाउनलोड करा",
    downloadPDF: "पीडीएफ डाउनलोड करा",
    cancel: "रद्द करा",

    //////////////////////////////////////////////
    rtiApplicationDashboard: "आरटीआय ऍप्लिकेशन डॅशबोर्ड",
    rtiAppealRegister: "आरटीआय अपील नोंदणी",
    subjectName: "विषयाचे नाव",
    systemEntryDate: "सिस्टम एंट्रीची तारीख",
    wards: "वार्ड",
    bplCardNumber: "बीपीएल कार्ड/ यादी क्रमांक",
    isApplicantBPL: "अर्जदार बीपीएल आहे",
    deptName: "विभागाचे नाव",
    /////////////////////////////////////////////////
    vivaranPatra01: "विवरण पत्र ०१",
    vivaranPatra02: "विवरण पत्र ०२",
    vivaranPatra03: "विवरण पत्र ०३",
    vivaranPatra04: "विवरण पत्र ०४",
    vivaranPatra05: "विवरण पत्र ०५",

    monthName: "महिना",
    count: "मोजणे",

    periodOfRelatedInformation: "कालावधी संबंधित माहिती",

    year: "वर्ष",

    descriptionOfInformationOfficer: "माहिती अधिकाऱ्याचे वर्णन",

    serialNumber: "अनुक्रमांक",
    deptWiseCollection: "विभागनिहाय संकलन",
    strFromDate: "या तारखेपासून",
    strToDate: "या तारखेपर्यंत",
    total: "एकूण",
    totalApplication: "एकूण अर्ज",
    grandTotal: "ग्रँड टोटल",
    requiredInformationByPostOrPersonallly:
      "पोस्टाने किंवा वैयक्तिकरित्या आवश्यक माहिती",
    applicationDate: "अर्जाची तारीख",
    departmentName: "विभागाचे नाव",

    fileNm: "फाईलचे नाव",
    fileType: "दस्तवेजाचा प्रकार",
    transferRemark: "हस्तांतरण टिप्पणी",
    viewAttach: "संलग्नक पहा",
    back: "मागे",

    //////////////////////RTI APPLICATION WISE COLLECTION LABEL CHANGES BY SHUBHAM /////////////////
    appWiseCollection: "अर्जानुसार संकलन",
    applicationName: "अर्जाचे नाव",
    serviceAcceptanceCharges: "सेवा स्वीकृती शुल्क",
    serviceCharges: "सेवा शुल्क",
    lastMonthPendingAppCount: "मागिल महिन्यातील थकीत अर्जांची संख्या",
    reportingMonthRecivedAppConunt:
      "अहवालाच्या महिन्यात प्राप्त झालेल्या अर्जांची संख्या",
    reportingMonthClearanceConunt:
      "अहवालाच्या महिन्यात निकाली काढलेल्या अर्जांची संख्या",
    infoDeleverdRTIAppCount:
      "निकाली काढलेल्या अर्जांपैकी माहिती उपलब्ध करुन देण्यात आलेल्या अर्जांची संख्या",
    infoRejectedRTIAppCount:
      "निकाली काढलेल्या अर्जांपैकी माहिती नाकरण्यात आलेल्या अर्जांची संख्या",
    pendingAppCount: "प्रलंबित अर्जांची संख्या",
    reportingMonthRecivedAppealConunt:
      "अहवालाच्या महिन्यात प्राप्त झालेल्या अपिलांची संख्या",
    reportingMonthAppealClearanceConunt: "निकाली अपिलांची संख्या",
    appealAcceptedConunt: "विनंती मान्य केलेल्या अपिलांची संख्या",
    appealRejectedConunt: "नाकारलेल्या अपिलांची संख्या",
    pendingAppealConunt: "प्रलंबित अपिलांची संख्या",
    lastMonthPendingAppealCount: "गेल्या महिन्यात प्रलंबित अपील गणना",
    reportingMonthDeleveredAppealCount: "वितरीत अपील संख्या अहवाल महिन्यात",
    rtiDueDate: "आरटीआय देय तारीख",
    totalNoOfDays: "उर्वरित दिवस",
    Tnc: "नियम व अटी",
    getDetails: "तपशील मिळवा",
    results: "परिणाम",
    searchArea: "क्षेत्र शोधा",
    rtiTermsndTitle: "पिंपरी चिंचवड महानगरपलिका,पिंपरी-४११०१८",
    rtiAct2005: "महिती अधिकार कायदा, २००५ ",
    guidelineOfRti: "आरटीआय ऑनलाइन पोर्टलच्या वापरासाठी सूचना",
    guideline1:
      "१) या वेब पोर्टलचा वापर भारतीय नागरिक आरटीआय अर्ज ऑनलाइन दाखल करण्यासाठी आणि आरटीआय अर्जासाठी ऑनलाइन पेमेंट करण्यासाठी करू शकतात. प्रथम अपील ऑनलाइन देखील दाखल करता येईल.",
    guideline2:
      "२) आरटीआय कायद्यांतर्गत कोणतीही माहिती मिळवू इच्छिणारा अर्जदार या वेब पोर्टलद्वारे पिंपरी चिंचवड महानगरपालिकेला अर्ज करू शकतो.",
    guideline3:
      '३) "सबमिट अँप्लिकेशन" वर क्लिक केल्यावर, अर्जदाराने दिसणार्‍या पेजवर आवश्यक तपशील भरावा लागेल.',
    guideline4: "४) चिन्हांकित बाबी अनिवार्य आहेत तर इतर बाबी पर्यायी आहेत.",
    guideline5: "५) अर्जाचा मजकूर विहित रकान्यात लिहिला जाऊ शकतो.",
    guideline6:
      "६) सध्या, विहित रकान्यात अपलोड करता येणारा अर्जाचा मजकूर केवळ ३००० अक्षरपुरताच मर्यादित आहे.",
    guideline7:
      "७) फक्त अक्षरे अ-ज्ञ क्रमांक ०-९ आणि विशेष चिन्ह , . - _ ( ) / @ : & % यास RTI विनंती अर्जासाठी मजकुरात अनुमती आहे.",
    guideline8:
      '८) जर अर्ज ३००० पेक्षा जास्त अक्षर असतील तर, "सपोर्टिंग डॉक्युमेंट" कॉलम वापरून ते पुरवणी म्हणून अपलोड केले जाऊ शकते.',
    guideline9:
      "९) आधार कार्ड किंवा पॅन कार्ड किंवा इतर कोणतीही वैयक्तिक ओळख (बीपीएल कार्ड वगळता) अपलोड करू नका.",
    guideline10: "१०) पीडीएफ फाइलच्या नावात रिक्त जागा असू नयेत सलग असावे.",
    guideline11:
      '११) अर्ज भरल्यानंतर, विहित शुल्क भरण्यासाठी अर्जदाराला "पेमेंट करा" वर क्लिक करावे लागेल.',
    guideline12:
      "१२) अर्जदार खालील पद्धतींद्वारे विहित शुल्क भरू शकतात: इंटरनेट बँकिंग/मास्टर/व्हिसाचे क्रेडिट/डेबिट कार्ड वापरणे/RuPay कार्ड वापरणे.",
    guideline13:
      "१३) अर्ज करण्यासाठी शुल्क आरटीआय नियम मध्ये विहित केलेले आहे.",
    guideline14: "१४) पेमेंट केल्यानंतर, अर्ज सबमिट केला जाईल.",
    guideline15:
      "१५) पेमेंट केल्यानंतर, जर कार्यालयीन अर्जदाराला नोंदणी क्रमांक प्राप्त झाला नाही तर अर्जदाराला कार्यालयीन २४-४८ कामकाजाच्या तासांची प्रतीक्षा करण्याचा सल्ला दिला जातो कारण नोंदणी क्रमांक ताळमेळ नंतर तयार होईल. पुन्हा पेमेंट करू नये. जर नोंदणी क्रमांक प्राप्त झाले नाही तर कृपया (sarthi@pcmcindia.gov.in), (egov@pcmcindia.com) येथे तपशीलांसह ई-मेल पाठवा.",
    guideline16:
      "१६) RTI नियम, नुसार दारिद्र्यरेषेखालील कोणत्याही नागरिकाला RTI फी भरण्याची आवश्यकता नाही. तथापि, अर्जदाराने या संदर्भात विहित BPL प्रमाणपत्राची प्रत अर्जासोबत जोडणे आवश्यक आहे.",
    guideline17:
      "१७) अर्ज सबमिट केल्यावर, एक नोंदणी क्रमांक दिला जाईल, ज्याचा वापर अर्जदार भविष्यात संदर्भासाठी वापर करू शकेल.",
    guideline18:
      '१८) या वेब पोर्टलद्वारे दाखल केलेला अर्ज इलेक्ट्रॉनिक पद्धतीने संबंधित विभागाच्या "नोडल ऑफिसर" पर्यंत पोहोचेल, जो संबंधित PIO कडे RTI अर्ज इलेक्ट्रॉनिक पद्धतीने पाठवेल.',
    guideline19:
      "१९) माहिती प्रदान करण्यासाठी अतिरिक्त शुल्क आवश्यक असल्यास, PIO अर्जदाराला या पोर्टलद्वारे सूचित करेल. ही सूचना अर्जदाराला स्टेटस रिपोर्टद्वारे किंवा त्याच्या/तिच्या ई-मेल अलर्टद्वारे पाहता येईल.",
    guideline20:
      '२०) प्रथम अपील प्राधिकरणाकडे अपील करण्यासाठी, अर्जदाराला "प्रथम अपील सबमिट करा" वर क्लिक करावे लागेल आणि प्रथम अपील अर्ज भरावे लागेल.',
    guideline21: "२१) मूळ अर्जाचा नोंदणी क्रमांक संदर्भासाठी वापरावा लागेल.",
    guideline22:
      "२२) अर्जदार/अपीलकर्त्याने एसएमएस अलर्ट प्राप्त करण्यासाठी त्याचा/तिचा मोबाईल क्रमांक सादर करावा.",
    guideline23:
      '२३) ऑनलाइन दाखल केलेल्या आरटीआय अर्जाची/प्रथम अपीलची स्थिती अर्जदार/अपीलकर्ता "स्थिती पहा" वर क्लिक करून पाहू शकतात.',
    guideline24:
      "२४) RTI कायदा, २००५ मध्ये प्रदान केल्याप्रमाणे RTI अर्ज आणि प्रथम अपील अर्ज तसेच कालमर्यादा, सूट इत्यादींसंबंधीच्या इतर तरतुदी दाखल करण्याच्या सर्व आवश्यकता लागू राहतील.",
    guideline25:
      "२५) आरटीआय कायदा २००५ मध्ये नमूद केलेल्या सर्व तरतुदी आरटीआय अर्ज आणि आरटीआय अपील अर्जाला लागू आहेत.",
    guideline26:
      "२६) एक माहिती अधिकार अर्जात एकच विषय अंतर्भूत असावा व शब्द मर्यादा १५० पर्यंत असावी. दुसऱ्या विषयासाठी स्वतंत्र अर्ज करावा.",

    mediumPrefReq: "माध्यम उपसर्ग आवश्यक आहे !!!",
    nmOfMediumReq: "माध्यमाचे नाव आवश्यक आहे !!!",
    nmOfMediumReqMr: "मराठीत माध्यमाचे नाव आवश्यक आहे !!!",

    mediumMinLeng: "माध्यमाचे नाव किमान 2 वर्ण असले पाहिजे",
    mediumMaxLen: "माध्यमाचे नाव खूप मोठे आहे",

    mediumMinLengMr: "मराठीतील माध्यमाचे नाव किमान २ अक्षरांचे असावे",
    mediumMaxLenMr: "मराठीत माध्यमाचे नाव खूप मोठे आहे",

    mediumPrefMinLeng: "माध्यम उपसर्ग किमान 2 वर्ण असणे आवश्यक आहे",
    mediumPrefMaxLen: "मध्यम उपसर्ग खूप मोठा आहे",

    decisionMinLen: "निर्णय तपशील किमान 20 वर्ण असणे आवश्यक आहे",
    decisionMaxLen: "निर्णयाचे तपशील खूप मोठे आहेत",
    decisionReq: "सुनावणीत घेतलेला निर्णय आवश्यक!!!",
    decisionStatusReq: "निर्णयाची स्थिती आवश्यक आहे !!!",
    remarkReq: "टिप्पणी आवश्यक आहे !!!",
    venueReq: "सुनावणीचे ठिकाण आवश्यक आहे !!!",
    chargeTypeReq: "आरटीआय माहिती शुल्क आवश्यक आहे !!!",

    educationReq: "शैक्षणिक स्थिती आवश्यक आहे !!!",
    areaNmReq: "क्षेत्राचे नाव आवश्यक आहे !!!",
    wardNmReq: "प्रभागाचे नाव आवश्यक आहे !!!",
    zoneNmReq: "झोनचे नाव आवश्यक आहे !!!",
    deptReq: "विभागाचे नाव आवश्यक आहे !!!",
    isBplReq: "दारिद्र्यरेषेखालील अर्जदार आवश्यक आहे !!!",
    addReq: "पत्ता आवश्यक आहे !!!",
    addMrReq: "पत्ता(मराठी) आवश्यक आहे !!!",
    descriptionReq: "आवश्यक माहितीचे वर्णन आवश्यक आहे !!!",
    reasonForAppealReq: "अपीलचे कारण आवश्यक आहे !!!",
    appliFirstNmReq: "अर्जदाराचे पहिले नाव आवश्यक आहे !!!",
    appliMiddNmReq: "अर्जदाराचे मधले नाव आवश्यक आहे !!!",
    appliLastNmReq: "अर्जदाराचे आडनाव आवश्यक आहे !!!",
    genderReq: "लिंग आवश्यक आहे !!!",
    pincodeReq: "पिनकोड आवश्यक आहे !!!",
    inCorrectMsg: "चुकीचे स्वरूप",
    emailReq: "अर्जदाराचा ईमेल आयडी आवश्यक आहे !!!",
    contactReq: "संपर्क क्र. आवश्यक आहे !!!",
    attachDate: "जोडलेली तारीख",

    uploadTitle: "अपलोड करा",
    childDeptTitle: "Child अर्ज विभाग",
    attachDoccument: "दस्तऐवज संलग्न करा",
    thirdPartyAattachDoccument: "लागू असल्यास तृतीय पक्ष दस्तऐवज संलग्न करा",
    descriptionMaxLen: "वर्णन मर्यादा ओलांडत आहे",
    addressMaxLen: "पत्ता मर्यादा ओलांडत आहे",
    reasonMaxLen: "अपीलचे कारण मर्यादा ओलांडत आहे",
    remarkMaxLen: "टिप्पणी मर्यादा ओलांडली आहे",
    venueMaxLen: "सुनावणीचे ठिकाण मर्यादा ओलांडत आहे",
    decisionStatussMaxLen: "निर्णयाची स्थिती मर्यादा ओलांडत आहे",
    appealDecision: "अपील निर्णय",
    applicationCurrentStatus: "आरटीआय अर्जाची सद्यस्थिती",

    mustBeOnlyNum: "फक्त अंक असणे आवश्यक आहे",
    allowNum: "फक्त नंबरला परवानगी द्या",
    noOfPageMin: "पृष्ठांची संख्या किमान 1 संख्या असणे आवश्यक आहे",
    noOfPagesMax: "5 वरील पानांची संख्या वैध नाही",
    noOfPageReq: "पृष्ठांची संख्या आवश्यक आहे",

    ratePerPageReq: "प्रति पृष्ठ दर आवश्यक आहे",
    ratePerPageMin: "प्रति पृष्ठ दर किमान 1 संख्या असणे आवश्यक आहे",
    ratePerPageMax: "वरील 4 क्रमांकावर प्रति पृष्ठ दर वैध नाही",

    // /////////////////////changes in rtiapplication label by shubham ///////////////////
    requiredInformationPurposeMaxLen:
      "माहितीच्या उद्देशाचा विषय मर्यादा ओलांडत आहे",
    requiredInformationPurpose: "माहितीच्या उद्देशाचा विषय",
    requiredInformationPurposeMr: "माहितीच्या उद्देशाचा विषय (मराठी)",
    paymentCollection: "पेमेंट संकलन",
    datePayment: "तारीख",
    receiptModeDetails: "पावती मोड तपशील",
    paymentType: "पैसे भरण्याची पध्दत",
    paymentMode: "देय प्रकार",
    pay: "पे",
    newText: "नवीन",
    applicationWithSLA: "मुदतीत असलेले अर्ज",
    applicationWithoutSLA: "मुदत संपून गेलेले अर्ज",

    outwardNumber: "जावक क्रमांक",
    helpDeskRTI: "महिती अधिकार मदत कक्ष",
    amountInWord: "अक्षरी रक्कम",
    receipthead: "पिंपरी चिंचवड महानगरपालिका, पिंपरी ४११०१८",
    receiptTitle: "नागरी सुविधा केंद्र (संगणक प्रणाली)",
    receiptHeader: "पैसे भरल्याची पावती",
    receiptNo: "पावती क्र",
    challenNo: "चलन क्र",

    receiptTime: " वेळ",
    saveAsDraft: "मसुदा म्हणून जतन करा",
    zoneOfficeWiseDepartment: "झोन, ऑफिस लोकेशन निहाय विभाग मॅपिंग",
    officeLocation: "कार्यालयाचे स्थान",
    officeLocationReq: "कार्यालयाचे स्थान आवश्यक आहे",

    rejectCat: "नाकारलेली श्रेणी",
    rejectCatMr: "नाकारलेली श्रेणी(मराठी)",
    rejectCatReq: "नाकारलेली श्रेणी आवश्यक आहे",
    rejectCatMrReq: "नाकारलेली श्रेणी(मराठी) आवश्यक आहे",
    rejectedCatCharacterValidation:
      "नाकारलेली श्रेणीत फक्त वर्णांना परवानगी आहे.",
    rejectedCatMrCharacterValidation:
      "नाकारलेली श्रेणीत (मराठी) फक्त वर्णांना परवानगी आहे.",
    rejectedCatMrCharacterLengthValidation:
      "नाकारलेली श्रेणी मराठी नाव 100 वर्णांपेक्षा जास्त नसावे",
    rejectedCatCharacterLengthValidation:
      "नाकारलेली श्रेणी नाव 100 वर्णांपेक्षा जास्त नसावे",
    formDateReq: "तारखेपासून संबंधित माहिती आवश्यक आहे !!!",
    toDateReq: "आजपर्यंत संबंधित माहिती आवश्यक आहे !!!",
    applicantFirstnmMax: "अर्जदाराचे पहिले नाव ५० वर्णांपेक्षा जास्त नसावे",

    middleNameMax: "अर्जदाराचे मधले नाव ५० वर्णांपेक्षा जास्त नसावे",
    lastNameMax: "अर्जदाराचे आडनाव ५० वर्णांपेक्षा जास्त नसावे",
    pinCodeValidtion: "पिनकोड आवश्यक आहे !!!",
    pinCodeValidtionLength: "पिनकोड 6 वर्णांपेक्षा जास्त नसावा",
    reqInfoDeliveryDetailsReq: "आवश्यक माहिती वितरण तपशील आवश्यक आहे",
    requiredInformationPurposeReq: "माहितीच्या उद्देशाचा विषय आवश्यक आहे",
    bplCardNoMaxLen: "बीपीएल कार्ड/ यादी क्रमांक 10 वर्णांपेक्षा जास्त नाही",
    issuingAuthMax: "जारी करणारे अधिकार 100 वर्णांपेक्षा जास्त",
    emailIdMax: "अर्जदाराचा ईमेल आयडी 80 वर्णांपेक्षा जास्त नसावा",
    totalAmtReq: "एकूण रक्कम आवश्यक आहे",

    accept: "स्वीकारा",
    reject: "नकार द्या",
    rejectedSection: "नकार विभाग",
    rejectedRemark: "नकार टिप्पणी",
    forwardToOfficeLocation: "ऑफिसच्या ठिकाणी फॉरवर्ड करा",
    forwardTozoneKey: "झोनकडे फॉरवर्ड करा",
    totalAmountMin: "एकूण रक्कम शून्य असू नये",
    yourPaymentDoneSuccess: " तुमचे पेमेंट यशस्वी झाले!!!",
    paymentFailed: "पेमेंट अयशस्वी !!!",
    orderId: "ऑर्डर आयडी ",

    trackingId: "ट्रॅकिंग आयडी",
    bankRefNo: "बँक संदर्भ क्र",
    billingName: "नाव",
    billingAdd: "पत्ता",
    billingCity: "शहर",
    billingZip: "पिन कोड ",
    billingCountry: "देश",
    billingEmail: "ईमेल",
    mobileNo: "मोबाईल क्र",
    transactionDate: "व्यवहाराची तारीख",
    billingState: "राज्य",
    goToList: "सूचीवर जा",
    serviceChargeReceipt: "सेवा शुल्काची पावती",
    pcmc: "पिंपरी चिंचवड महानगरपालिका",
    fiscalYear: "सन",
    date: "तारीख",
    relatedTo: "विभागाकडून",
    cfcRefNo: "सीएफसी संदर्भ क्रं",
    cfcCounterNo: "सीएफसी काउंटर क्रं",
    receivedFrom: "कोणाकडून",
    rti: "माहितीचा अधिकार ऑनलाइन प्रणाली",
    narration: "विवरण",
    applicationServiceReceipt: "अर्ज सेवा शुल्क पावती",
    officeCopy: "कार्यालयाची प्रत",
    customerCopy: "ग्राहकाची प्रत",
    rupees: "रुपये",
    chequeNo: "धनादेश क्रं.",
    chequeDate: "धनादेश क्रं",
    bankName: "बँकेचे नाव",
    referenceNo: "बँक संदर्भ क्र.",
    details: "तपशील",
    payableAmount: "देय रक्कम",
    receivedAmount: "स्वीकारलेली रक्कम",
    rebateAmount: "सूट/सवलत रक्कम",
    advanceAmount: "आगाऊ रक्कम",
    actualPayableAmount: "एकूण देय रक्कम",
    receiverSignature: "स्वीकारणाऱ्याची स्वाक्षरी",
    printBy: "अर्जदाराचे नाव",
    printDateAndTime: "तारीख आणि वेळ",
    iagreeForOnlinePay: "मी ऑनलाइन पेमेंटसाठी सहमत आहे",
    acknowldgementNo: "पावती क्र",
    loiPayment: "सूचना पत्र शुल्क",
    appealServiceReceipt: "अपील सेवा शुल्क पावती",
    loiPaymentReceipt: "अर्ज सूचना पत्र पावती",
    paymentCancelled: "पेमेंट रद्द केले",
    selectMonthYr: "महिना आणि वर्ष निवडा",
    pinCodeValidtionMinLength: "पिनकोड 6 क्रमांकाचा असावा",
    mobMaxValLen: "संपर्क क्र. 10 क्रमांकाचा असावा",
    mobMinValLen: "संपर्क क्र. 10 क्रमांकाचा असावा",
    totalMax: "एकूण रक्कम मर्यादा ओलांडली आहे",
    uploadFile: "दस्तऐवज अपलोड करा",
    addFile: "फाइल जोडा",
    softCopyNote:
      "टीप : (जर माहिती सॉफ्ट कॉपी स्वरूपात उपलब्ध असेल तर ती त्याच स्वरूपात दिली जाईल अन्यथा ती हार्ड कॉपी म्हणून प्रदान केली जाईल.)",
    addMore: "अधिक जोडा",
    rate: "दर",
    quantity: "प्रमाण",
    completeNote:
      " टीप - दिलेल्या माहितीने समाधान न झाल्यास माहिती प्राप्त झाल्यापासून 30 दिवसाच्या आत अर्जदार यांना अपीलीय अधिकारी यांच्याकडे अपील अर्ज करता येईल.",
    trackOldRTIApplication: "जुन्या आरटीआय अर्जाचा मागोवा घ्या",
    OldRTIApplication: "जुने आरटीआय अर्ज",

    trackOldRTIApplicationHistory: "जुन्या आरटीआय अर्जाचा इतिहास",
    searchFilter: "फिल्टरद्वारे शोधा",
    finalRemark: "अंतिम टिप्पणी",
    applicationDateOld: "अर्जाची तारीख",
    backToDashboard: "डॅशबोर्डवर परत",
    villageName: "गावाचे नाव ",
    rtiAdhikariNm: "आरटीआय अधिकारी नाव",

    bplCardDoc: "बीपीएल पुरावा कागदपत्र संलग्न करा :",
    fileNotUpload: "फाइल अपलोड केली नाही",
    dataNotAvail: "डेटा उपलब्ध नाही",
    viewDoc: "पहा",
    infoSentByPost: "पोस्टाने माहिती पाठवली",
    infoProvidedByPerson: "वैयक्तिकरित्या माहिती दिली",
    postalService: "पोस्ट प्रकार",
    place: "ठिकाण",
    placeReq: "ठिकाण आवश्यक आहे",
    officerTitle: "आरटीआय अर्ज आणि आरटीआय अपील अधिकारी तपशील",

    designation: "पदनाम",
    officialAddress: "अधिकृत पत्ता",

    officerName: "अधिकाऱ्याचे नाव",
  },
};
