const schoolLabels = {
  en: {
    type: "commonLabels",
    module: "School",

    studentDailyAttendance: "Student Daily Attendance",
    classTimetable: "Class Timetable",
    addDailyTimetable: "Add Daily Timetable",
    timeAndSub: "Select Time and Subjects",
    subjectTeacherMapping: "Assign Subject to Teacher",

    schoolUserMaster: "School User Master",
    itiUserMaster: "ITI User Master",
    userReq: "User name is required !!",
    userName: "User name",

    studentList: "Student List",
    selectSchool: "Select School",
    schoolRequired: "School is required",
    selectAcademicYear: "Select Academic Year",
    academicYear: "Academic Year",
    academicYearRequired: "Academic Year is required !!",
    selectClass: "Select Standard",
    classRequired: "Class is required",
    selectDivision: "Select Division",
    divisionRequired: "Division is required",
    date: "Date",
    dateRequired: "Date is required",
    studentName: "Student Name",
    presentAbsent: "Present/Absent",
    examName: "Exam Name",
    examType: "Exam Type",
    othExamTypeName: "Other Exam Type Name",
    othExamTypeNameRequired: "Other Exam Type Name is Required",
    examNameRequired: "Exam Name is required",
    examTypeRequired: "Exam Type is required",
    examDate: "Exam Date",
    examDateRequired: "Exam Date is required",
    subNameRequired: "Subject Name Required !! must be only words",
    minimumMarksRequired: "Minimum Marks is Required",
    examFromTime: "Exam From Time",
    examFromTimeRequired: "Exam From Time is required",
    examToTime: "Exam To Time",
    examToTimeRequired: "Exam To Time is required",
    srNo: "Sr.No",
    minimumMarks: "Minimum Marks",

    ayFromDate: "From Date",
    ayToDate: "To Date",

    schoolClass: "School Standard",
    schoolDiv: "School Standard Division",

    stateMaster: "State Master",

    schoolName: "School Name",
    schoolNameMr: "School Name (In Marathi)",
    medium: "Medium",
    studentGeneralRegisterNumber: "Student General Register Number",
    admissionDate: "Admission Date",
    rollNumber: "Roll Number",
    divisionName: "Division Name",
    divisionPrefix: "Division Code",
    intake: "Intake",
    firstName: " First Name",
    middleName: "Middle Name",
    surnameName: "Surname Name",
    address: "Address",
    mobileNumber: "Mobile Number",
    emailId: "Email ID",
    studentGRnumber: "Student GR Number",
    or: "OR",
    applicationStatus: "Application Status",
    className: "Standard Name",
    division: "Division",
    dateOfbirth: "Date of Birth",
    birthAddress: "Birth Address",
    bonafiedPurpose: "Purpose of bonafide certificate (In Eng)",
    bonafiedPurposeMr: "Purpose of bonafide certificate (in Mar)",
    approveBonafiedDate: "Bonafide Approve/Reject Date",
    approveLCDate: "Leaving Certificate Approve/Reject Date",
    selectStudent: "Select Student",
    studentRequired: "Student is required",
    reasonForLeavingSchoolMr: "School leaving Reason (In Marathi)",
    reasonForLeavingSchoolMrReq:
      "School leaving Reason (In Marathi words) required",
    reasonForLeavingSchoolEn: "School leaving Reason (In English)",
    reasonForLeavingSchoolEnReq:
      "School leaving Reason (In English words) required",

    addNewTimetable: "Add New Timetable",
    updateTimetable: "Update Timetable",
    periodList: "Period List",
    day: "Day",
    from: "From",
    to: "To",
    subject: "Subject",
    academicSubject: "Academic Subject",
    teacher: "Teacher",
    recess: "Recess",
    teachersForSubjects: "Assign Teachers for Subjects",
    selectSubject: "Select Subject",
    selectTeacher: "Select Teacher",
    go: "GO",

    2: "Monday",
    3: "Tuesday",
    4: "Wednesday",
    5: "Thursday",
    6: "Friday",
    7: "Saturday",
    fromTime: "From Time",
    toTime: "To Time",
    Monday: "Monday",
    Tuesday: "Tuesday",
    Wednesday: "Wednesday",
    Thursday: "Thursday",
    Friday: "Friday",
    Saturday: "Saturday",

    search: "Search",
    clear: "Clear",
    close: "Close",
    teacherParentCommunication: "Teacher Parent Communication",
    add: "Add",
    save: "Save",
    saveWeekelyTimetable: "Add Weekely Timetable",
    finalSubmit: "Final Submit Timetable",
    edit: "Edit",
    toggle: "Toggle",
    updateAttendance: "Update Attendance",
    update: "Update",
    exit: "Exit",

    success: "Success!",
    attendanceUpdated: "Attendance Updated Successfully",
    examSaved: "Exam Saved Successfully",
    examUpdated: "Exam Updated Successfully",
    error: "Error!",
    admissionRegitrationNo: "Admission Reg. No.",

    aadharNumber: "Aadhar Number",
    schoolTeacher: "School Teacher",
    gender: "Gender",
    male: "Male",
    female: "Female",
    motherTongue: "Mother Tongue",
    permanentAddress: "Permanent Address",
    pincode: "Pincode",
    contactPersonName: "Contact Person Name",
    contactPersonNumber: "Contact Person Number",
    schoolMaster: "School Master",
    schoolPrefix: "School Code",
    gisCode: "GIS Code",
    udiceCode: "UDISE No",
    schoolAddress: "School Address",
    lattitude: "Lattitude",
    longitude: "Longitude",
    message: "Message",
    teacherName: "Teacher Name",
    selectAll: "Select All",
    actions: "Actions",
    action: "Action",
    age: "Age",
    status: "Status",
    reject: "Reject",
    approve: "Approve",
    submit: "Submit",
    view: "View",
    principalRemarksEn: "Principal Remarks (In Eng)",
    principalRemarksMr: "Principal Remarks (In Mar)",

    studentAdmissionForm: "Student Admission Form",
    studentPersonalInfo: "Personal Details",
    studentParentInfo: "Parents or Guardian Details",
    studentOthInfo: "Other Details",
    lastSchoolInfo: "Last School Information (If Applicable)",
    accountDetails: "Bank Account Details",
    accountNo: "Bank Account Number",
    confirmBankAcNumber: "Confirm Bank Account Number",
    bankName: "Bank Name",
    ifscCode: "Bank IFSC Code",
    bankAdderess: "Bank Adderess",
    documents: "Documents",
    accountHolderName: "Account Holder Name",
    zoneName: "Zone Name",
    wardName: "Ward Name",
    studentFirstName: "Student First Name",
    studentFirstNameMr: "Student First Name (In Marathi)",
    studentMiddleName: "Student Middle Name",
    studentMiddleNameMr: "Student Middle Name (In Marathi)",
    studentLastName: "Student Last Name",
    studentLastNameMr: "Student Last Name (In Marathi)",
    fatherFirstName: "Father First Name",
    fatherMiddleName: "Father Middle Name",
    fatherLastName: "Father Last Name",
    motherName: "Mother First Name",
    motherNameMr: "Mother First Name (In Marathi)",
    motherMiddleName: "Mother Middle Name",
    motherLastName: "Mother Last Name",
    religion: "Religion",
    casteName: "Caste Name",
    subCastName: "Sub Caste Name",
    citizenship: "Citizenship",
    nationality: "Nationality",
    birthPlace: "Birth Place",
    birthPlaceMr: "Birth Place (In Marathi)",
    studentState: "Student Birth State",
    studentDist: "Student Birth District",
    parentAddress: "Parent Address",
    parentOccupation: "Parent Occupation",
    fatherMobileNumber: " Father Mobile Number",
    motherMobileNumber: " Mother Mobile Number",
    permanentAddress: "Permanent Address",
    parentFullName: "Parent Full Name",
    parentEmailId: "Parent Email",
    colony: "Colony",
    district: "District",
    // state: "State",
    lastSchoolName: "Last School Name -if applicable",
    lastSchoolNameMr: "Last School Name (In Marathi) -if applicable",
    lastSchoolAdmissionDate: "Last School Admission Date -if applicable",
    lastSchoolAndFromWhenStudying: "Last School and from when Studying",
    lastSchoolLeavingDate: "Last School Leaving Date",
    studentBehaviour: "Student Behaviour",
    studentBehaviourMr: "Student Behaviour (In Marathi)",
    reasonForLeavingSchool: "Reason for Leaving School",

    studentBirthCertificate: "Student Birth Certificate",
    studentSchoolLeavingCertificate:
      "Student School Leaving Certificate (if applicable)",
    studentPhotograph: "Student Photograph",
    studentAadhar: "Student Aadhar Card",
    parentAadhar: "Parent Aadhar Card",
    studentLastYearMarksheet: "Student Last Year Marksheet (if applicable)",

    selectExam: "Select Examination",
    exam: "Examination",
    examMarks: "Exam Marks",
    examRequired: "Examination is required",
    selectTerm: "Select Term",
    term: "Term",
    termRequired: "Term is required",
    marksObtained: "Marks Obtained",
    outOfMarks: "Out of Marks",
    outOfMarksRequired: "Out of Marks is required",
    passingMarks: "Passing Marks",
    passingMarksRequired: "Passing Marks is required",
    marksError: "Marks should be less than or equal to out of marks",
    updateMarks: "Update Marks",
    marksUpdated: "Marks Updated Successfully",

    deactivate: "Deactivate",
    activate: "Activate",
    areYouSureToDeactivate: "Are you sure to deactivate this record?",
    areYouSureToActivate: "Are you sure to activate this record?",
    deactivateSuccess: "Record Deactivated Successfully",
    activateSuccess: "Record Activated Successfully",
    previewReport: "Preview Report",
    classTimetableReport: "Class Timetable Report",
    teacherClassTimetableReport: "Teacher Class Timetable Report",
    generateReport: "Generate Report",
    fromDate: "From Date",
    toDate: "To Date",
    studentsAttendanceReport: "Students Attendance Report",
    schoolLeavingCert: "School Leaving Certificate",
    studentBonafideCert: "Student Bonafide Certificate",
    fatherQualification: "Father Qualification",
    fatherOccupation: "Father Occupation",
    fatherIncome: "Father Income",
    motherQualification: "Mother Qualification",
    motherOccupation: "Mother Occupation",
    motherIncome: "Mother Income",
    stateNameMr: "State Name (In marathi)",
    stateName: "State Name (In English)",
    state: "State Name",
    relation: "Relation with account holder",
    saralId: "Saral Id",
    view: "View",
    remark: "Remark",
    docsRemark: "Documents Verifications Remark",
    selectMedium: "Select Medium",
    disabilityTypes: "Disability Types",
    disabilityTypesEn: "Disability Types (in English)",
    disabilityTypesMr: "Disability Types (in Marathi)",
    disabilityInfo: "Disability Information (if Applicable)",
    percentageofDisability: "Percentage of Disability",
    certificateOfDisability: "Certificate Of Disability",
    updateStudentInfo: "Update Students Information",
    search: "Search",
    attachmentDocument: "Required Document",
    designationOfOrderIssuancePerson: "Designation Of Order Issuance Person",
    nameofPrderIssuancePerson: "name Of Order Issuance Person",
    examTimeTableReport: "Exam Timetable Report",
    serviceName: "Service Name",
    applicationDate: "Application Date",
    examTimetable: "Exam Timetable",
    addTimetable: "Add Timetable",
    timetable: "Timetable",
    // ----------------------school validations Labels en-----------------------------------------------------------------------------------
    schoolReq: "School name is required",
    ayReq: "Academic year is required",
    classReq: "Class name is required",
    divReq: "Division name is required",
    studentReq: "Student name is required",

    bonafiedPurposeReq:
      "Bonafide purpose in english required !! must be only english characters",
    bonafiedPurposeMrReq:
      "Bonafide purpose in marathi required !! must be only marathi character",
    studentRollNoReq: "Student roll number required !! / must be only digits",
    other: "Other",

    schoolMediumReq: "School medium is required!",
    studentFirstNameReq:
      "Student First Name Required !! / must be only english characters",
    studentMiddleNameReq:
      "Student Middle Name Required !! / must be only english characters",
    studentLastNameReq:
      "Student last Name Required !! / must be only english characters",
    firstNameMrReq:
      "Student First Name Required (In Marathi) !! Must be only marathi characters",
    middleNameMrReq:
      "Student Middle Name Required (In Marathi) !! Must be only marathi characters",
    lastNameMrReq:
      "Student Last Name Required (In Marathi) !! Must be only marathi characters",

    fatherFirstNameReq: "Father First Name Required !! must be only words",
    fatherMiddleNameReq: "Father Middle Name Required !! must be only words",
    fatherLastNameReq: "Father Last Name Required !! must be only words",
    motherNameReq: "Mother Name Required !!/ must be only english characters",
    motherMiddleNameReq: "Mother Middle Name Required !! / must be only words",
    motherLastNameReq: "Mother last Name Required !! / must be only words",
    motherNameMrReq:
      "Mother Name (In Marathi) Required!! / must be only marathi characters",
    studentGenderReq: "Select your gender",
    mobileReq: "Must be only digits / Mobile Number must be 10 number ",
    emailReq: "EmailID required and must be correct format",
    aadharNoReq: "Must be only digits / Aadhar Number must be 12 number",
    religionKeyReq: "Select Your Religion",

    casteKeyReq: "Select your Caste Name",
    subCastKeyReq: "Select your Sub Cast Name",
    citizenshipNameReq: "Select your CItizenship Name",
    motherTongueNameReq: "Select your Mother Tongue Name",
    studentBirthPlaceReq:
      "Enter your Birthplace (In English) / must be only english characters",
    birthPlacemrReq:
      "Enter your Birthplace (In Marathi) / must be only marathi characters ",
    studentDateOfBirthReq: "Select your Date of Birth",
    stateNameReq: "Select your State name",
    districtNameReq: "Enter your District name / must be only words",
    familyPermanentAddressReq: "Enter your family permanent address ",
    parentFullNameReq: "Parent Full Name Required !! / must be only words",
    parentEmailIdReq: "Parent EmailId required and must be correct format !! ",
    parentAddressReq: "Parent Address required !! ",

    fatherContactNumberReq:
      "Father Contact No. required ! and must be only digits / must be 10 number  ",
    motherContactNumberReq:
      "Mother Contact No. required ! and must be only digits / must be 10 number  ",
    fatherQualificationReq: "Father Qualification Required !!",
    fatherOccupationReq: "Father Occupation Required !! must be only words",
    fatherIncomeReq: "Father Income Required !! must be only digits",
    motherQualificationReq: "Mother Qualification Required !!",
    motherOccupationReq: "Mother Occupation Required !! must be only words",
    motherIncomeReq: "Mother Income Required !! must be only words",
    colonyNameReq: "Enter your Area/Colony Name",
    parentDistrictNameReq:
      "Parent District Name Required !! must be only words",
    parentStateNameReq: "Parent State Name Required !! must be only words",

    parentPincodeReq:
      "Parent Pincode Required !! /and must be only digits / must be 6 number ",
    accountNoReq: "Account Number Required !! / and must be only digits",
    confirmBankAcNumberReq:
      "Account number and confirm bank account number must be same and it is required !!",
    accountHolderNameReq: "Account holder name Required !! must be only words",
    bankNameReq: "Bank  name Required !! must be only words",
    ifscCodeReq: "Bank  IFSC code Required !! must be correct format",
    bankAdderessReq: "Bank  address Required !!",
    relationWithAccountantHolderReq: "Relation With Account Holder Required !!",
    studentBirthCertificateReq: "Student Birth Certificate Required",
    studentPhotographReq: "Student photograph Required",
    studentAadharCardReq: "Student Aadhar card Required",
    parentAadharCardReq: "Parent Aadhar card Required",

    selectStudReq: "Please select at least one student",
    teacherKeyReq: "Teacher name required !!",
    commSubjectReq: "Communication Subject Name required !!",
    commMessageReq: "Communication Message required !!",

    // masters
    subjectReq: "Subject Name required !!",
    fromDateReq: "From date is required !!",
    toDateReq: "To date is required !!",

    typeOfDisabilityReq:
      "Type Of Disability is required !! / only english words",
    typeOfDisabilityMrReq:
      "Type Of Disability in marathi is required !! / only marathi words",
    remarkReq: "Remarks required !!",

    zoneReq: "Zone Name is Required !!",
    schoolNameMrReq: "School Name in marathi Required !!",
    udiceCodeReq: "School UDICE code required !!",
    schoolAddressReq: "School address required !!",
    pincodeReq:
      "Pincode Required !! / and must be only digits / must be 6 number",
    gisCodeReq: "GIS Code is Required !!",
    contactPersonNameReq: "School Contact Person Name required  !!",
    contactPersonNumberReq:
      "School Contact Person Mobile Number required and must be only digits / must be 10 number",
    schoolEmailIdReq: "School EmailId required and must be correct format !!",

    divPrefixReq: "Division Prefix is Required !!",
    intakeReq: "Division intake (in number) is Required !!",

    empId: "Employee ID",
    teacherPhotograph: "Teacher Photo",
    firstNameReq: "First Name Required !! must be only words",
    middleNameReq: "Middle Name Required !! must be only words",
    lastNameReq: "Last Name Required !! must be only words",
    genderReq: "Gender Required !!",
    contactDetailsReq:
      "Mobile Number required and must be only digits / must be 10 number",
    emailDetailsReq: "EmailId required and must be correct format !!",
    aadharNumberReq:
      "Aadhar Number required and must be only digits / must be 12 number!!",
    motherTongueNameReq: "Mother Tongue name required !!",
    permanentAddressReq: "Permanent address required !!",

    stateNameEnReq: "State Name in english required !! / only english words",
    stateNameMrReq: "State Name in marathi required !! / only english words",

    // ----------------------ITI Labels en-----------------------------------------------------------------------------------
    itiTraineeBonafideCert: "ITI Trainee Bonafide Certificate",
    itiName: "ITI Name",
    tradeName: "Trade Name",
    traineeName: "Trainee Name",
    traineeMoNo: "Trainee Mobile No",
    traineeEmailId: "Trainee Email",
    selectIti: "Select ITI Name",
    selectTrade: "Select Trade Name",
    selectTrainee: "Select Trainee",
    selectTraineeComm: "At least one Trainee name required !!",
    registrationNo: "Registration No",
    grpInstructorRemarksEn: "Group Instructor Remarks (Eng)",
    grpInstructorRemarksMr: "Group Instructor Remarks (Mar)",

    itiTraineeDetails: "ITI Trainee Details",
    traineeFirstName: "Trainee First Name",
    traineeMiddleName: "Trainee Middle Name",
    traineeLastName: "Trainee Last Name",
    casteCategory: "Caste Category",
    locatedAt: "Located At",
    preview: "Preview",
    areaName: "Area Name",
    allotementDetails: "Allotement Details",
    allotementRound: "Allotement Round",
    preferenceNumber: "Preference Number",
    allotementCategory: "Allotement Category",
    mcode: "M-Code",
    allotedItiName: "Alloted ITI Name",
    allotedTradeName: "Alloted Trade Name",
    lastSchoolDetails: "Last School Details",
    lastSchoolNamee: "Last School Name",
    lastSchoolAdmissionDatee: "Last School Admission Date",
    lastClass: "Last Class",
    traineePhotograph: "Trainee Photograph",
    traineeAadhar: "Trainee Aadhar Card",
    traineeBirthCert: "Trainee Birth Certificate",
    traineeTc: "Trainee School Transfer Certificate",
    traineeLastYrMarksheet: "Trainee Last Year Marksheet",
    dvetItiAllotementLetter: "DVET ITI Allotement Letter",
    nonCreamyLayer: "Non-Creamy Layer Certificate",
    incomeProof: "Income Proof Certificate",
    instructorParentComm:
      "Instructor/Group Instructor and Parent/Trainee Communication",
    instructorName: "Instructor Name",
    selectInstructor: "Select Instructor Name",
    teacherOrInstructorName: "Teacher / Instructor Name",
    itiTeacherOrInstructorMaster: "ITI Teacher / Instructor Master",
    isInstructorOrTeacher: "is Teacher / is Instructor",

    totalAdmissionFees: "Total Admission Fees",
    feesAmountToPay: "Fees Amount To Pay",
    remainingFeesAmount: "Remaining Fees Amount",
    paymentType: "Payment Type",
    paymentMode: "Payment Mode",
    accountantRemarks: "Accountants Remark",
    groupInstructorRemarksEnRequiredEn: "Remark Required in English",
    groupInstructorRemarksEnRequiredMr: "Remark Required in Marathi",
    principalRemarksRequiredEn: "Remark Required in English",
    principalRemarksRequiredMr: "Remark Required in Marathi",
    itiKeyRequired: "select iti Required ",
    itiTraineeAttendance: "ITI Trainee Attendance",
    itiPrefix: "ITI Prefix",
    intakeCapacity: "Intake Capacity",
    itiCode: "ITI Code",
    required: "Required",
    itiMaster: "ITI Master",
    itiTradeDivMaster: "ITI Trade Division Master",
    itiType: "ITI Type",
    tradeFees: "Trade Fees",
    tradeDesc: "Trade Description",
    itiTradeMaster: "ITI Trade Master",
    cautionFees: "Caution Fees",
    fees: "Fees",
    locationName: "Location Name",
    itiFeesStructureMaster: "ITI Fees Structure Master",
    castCertificate: "Caste Certificate",
    mediumOfEdu: "Medium Of Education",
    parentMobileNo: "Parent Mobile Number",
    tradeDuration: "Trade Duration (In Year)",
    tradeUnit: "Trade Unit",
    tradeAffiliationNo: "Trade Affiliation Number",
    tradeType: "Trade Type",
    admissionFees: "Admission Fees",
    itiSubMaster: "ITI Trade Subject Master",
    tradeSubName: "Subject Name",
    tradeSubPref: "Subject Prefix",
    tradeSubMarks: "Marks",
    itiTraineeAttendanceReport: "ITI Trainee Attendance Report",
    lastSchoolAdmissionDateiti: "Last School Admission Date",

    // ITI transactions Validations marathi labels
    itiNameReq: "ITI Name required !! must be only words",
    itiTradeReq: "ITI Trade name required !! must be only words",
    traineeNameReq: "Trainee name required !!",
    instructorReq: "Instructor name required !!",

    allotmentRoundReq:
      "Allotment round number required !! / must be only digits",
    preferenceNumberReq: "Preference number required !!",
    allotmentCategoryReq: "Allotment Category required !!",
    traineeFirstNameReq: "Trainee first name required !! must be only words",
    traineeMiddleNameReq: "Trainee middle name required !! must be only words",
    traineeLastNameReq: "Trainee last name required !! must be only words",
    fatherFirstNameReqAdmission:
      "Father first name required !!/ must be only words",
    fatherMiddleNameReqAdmission:
      "Father middle name required !!/ must be only words",
    fatherLastNameReqAdmission:
      "Father last name required !! / must be only words",
    motherFirstNameReq: "Mother first name required !! must be only digits",

    traineeMobileNumberReq:
      "Trainee mobile number required !! / Must be only digits and it must be 10 number ",
    parentMobileNumberReq:
      "Parent mobile number required !! / Must be only digits and it must be 10 number ",
    traineeEmailIdReq:
      "Trainee EmailId required and must be correct format !! ",
    traineeAadharNumberReq:
      "Trainee aadhar number required !! / Must be only digits and it must be 12 number ",
    casteCategoryKeyReq: "Caste Category required !!",
    casteKeyReq: "Caste required !!",
    nationalityReq: "Nationality required !!",
    motherTongueNameReq: "Mother Tongue Name required !!",
    addressReq: "Address required !!",

    locatedAtReq: "located at required !! must be only words",
    areaReq: "Area name required !!",
    traineeDateOfBirthReq: "Trainee Date of Birth required !!",
    traineeDateOfBirthReqAdmission:
      "Trainee Date of Birth required !! it must be 15 years old",
    traineeBirthPlaceReq: "Trainee birth place required !! must be only words",
    lastSchoolNameReq: "Last school name required !! it must be only words",
    lastClassReq: "Last class name required !!",
    mediumOfEducationReq:
      "Last class education medium required !! must be only words",
    lastSchoolAdmissionDateitiReq: "Last school admission date required !!",
    lastSchoolLeavingDateitiReq: "Last school leaving date required !!",
    lastSchoolLeavingReasonReq:
      "Last school leaving reason required !! it must be only words",

    traineePhotographReq: "Trainee photograph required !!",
    traineeAadharCardDocumentReq: "Trainee aadhar card required !!",
    leavingCertificateDocumentReq: "Trainee leaving certificate required !!",
    lastYearMarksheetReq: "Trainee last year marksheet required !!",
    dvetAllotmentLetterReq: "DVET ITI allotment letter required !!",

    actionReq: "Status/Action is required !!",

    admissionFeesReq: "Admission fees required !! / Must be only digits !!",
    depositReq: "Caution fees required !! / Must be only digits !!",
    totalAdmissionFeeRsReq:
      "Total admission fees required !! / Must be only digits !!",
    admissionFeeAmountToPayReq:
      "Admission fee amount to pay required !! / Must be only digits !!",
    remainingFeesAmountReq:
      "Remaining fees amount required !! / Must be only digits !!",
    paymentTypeKeyReq: "Payment type required !!",
    paymentModeKeyReq: "Payment mode required !!",
    accountantRemarksReq: "Accountant remarks required !!",

    purposeOfBonafideEnReq: "Purpose of bonafide (In English) required !!",
    purposeOfBonafideMrReq: "Purpose of bonafide (In Marathi) required !!",

    groupInstructorRemarksEnReq: "Remarks (In English) required !!",
    groupInstructorRemarksMrReq: "Remarks (In Marathi) required !!",

    // masters validations
    feesReq: "Fees required !! / Must be only digits !!",

    itiPrefixReq: "ITI prefix is required !!",
    itiCodeReq: "ITI code is required !!",
    intakeCapacityReq:
      "Intake capacity required !! / it must be only digits !!",
    itiContactPersonNameReq:
      "Contact Person Name required  !! must be only words",
    itiContactPersonNumberReq:
      "Contact Person Mobile Number required and must be only digits / must be 10 number",
    itiAddressReq: "ITI address required !!",
    gisIdReq: "GIS Id required !!",

    teacherTypeReq: "Is Teacher or is instructor ? required !!",

    tradeDurationReq:
      "Trade duration (In Year) required !! / and must be only digits",
    tradeUnitReq: "Trade unit required !!",
    tradeAffiliationNoReq: "Trade affiliation number required !!",
    tradeTypeReq: "Trade type required !!",
    tradeDescriptionReq: "Trade description required !!",

    subjectPrefixReq: "Subject prefix required !!",
    marksReq: "Marks required !! / and must be only digits",
  },

  mr: {
    type: "commonLabels",
    module: "शाळा",
    subjectTeacherMapping: "शिक्षकांना विषय नियुक्त करा",

    schoolUserMaster: "शाळा वापरकर्ता मास्टर",
    itiUserMaster: "आयटीआय युजर मास्टर",
    userReq: "वापरकर्ता नाव आवश्यक आहे !!",
    userName: "वापरकर्त्याचे नाव",

    studentDailyAttendance: "विद्यार्थी दैनिक उपस्थिती",
    classTimetable: "वर्ग वेळापत्रक",
    addDailyTimetable: "दैनिक वेळापत्रक जोडा",
    timeAndSub: "वेळ आणि विषय निवडा",

    studentList: "विद्यार्थी सूची",
    selectSchool: "शाळा निवडा",
    schoolRequired: "शाळा आवश्यक आहे !!",
    selectAcademicYear: "शैक्षणिक वर्ष निवडा",
    academicYear: "शैक्षणिक वर्ष",
    academicYearRequired: "शैक्षणिक वर्ष आवश्यक आहे !!",
    selectClass: "इयत्ता निवडा",
    classRequired: "वर्ग आवश्यक आहे",
    selectDivision: "तुकडी निवडा",
    divisionRequired: "तुकडी आवश्यक आहे",
    date: "तारीख",
    dateRequired: "तारीख आवश्यक आहे",
    studentName: "विद्यार्थ्याचे नाव",
    presentAbsent: "उपस्थित/अनुपस्थित",
    examName: "परीक्षेचे नाव",
    examType: "परीक्षेचा प्रकार",
    othExamTypeName: "इतर परीक्षा प्रकाराचे नाव",
    othExamTypeNameRequired: "इतर परीक्षा प्रकाराचे नाव आवश्यक आहे",
    examNameRequired: "परीक्षेचे नाव आवश्यक आहे",
    examTypeRequired: "परीक्षेचा प्रकार आवश्यक आहे",
    examDate: "परीक्षेची तारीख",
    examDateRequired: "परीक्षेची तारीख आवश्यक आहे",
    subNameRequired: "विषयाचे नाव आवश्यक आहे !! फक्त शब्द असावेत",
    minimumMarksRequired: "किमान गुण आवश्यक आहेत",
    examFromTime: "सुरवातीची वेळ",
    examFromTimeRequired: "सुरवातीची वेळ आवश्यक आहे",
    examToTime: "समाप्तीची वेळ",
    examToTimeRequired: "समाप्तीची वेळ आवश्यक आहे",
    srNo: "अनु क्रमांक",
    ayFromDate: "पासून वर्ष",
    ayToDate: "आजपर्यंत",
    minimumMarks: "किमान गुण",
    schoolClass: "शाळेची इयत्ता",
    schoolDiv: "शाळेतील इयत्तेची तुकडी",

    stateMaster: "राज्य मास्टर",

    schoolName: "शाळेचे नाव",
    schoolNameMr: "शाळेचे नाव (मराठी मध्ये)",
    medium: "माध्यम",
    studentGeneralRegisterNumber: "अर्ज क्रमाांक",
    admissionDate: "प्रवेशाची तारीख",
    rollNumber: "हजेरी क्रमांक",
    divisionName: "तुकडीचे नाव",
    divisionPrefix: "तुकडी कोड",
    intake: "जागा",
    firstName: "पहिले नाव",
    middleName: "मधले नाव",
    surnameName: "आडनाव",
    address: "पत्ता",
    mobileNumber: "मोबाईल नंबर",
    emailId: "ई - मेल आयडी",
    studentGRnumber: "विद्यार्थी GR क्रमांक",
    or: "किंवा",
    applicationStatus: "अर्जाची स्थिती",
    className: "इयत्तेचे नाव",
    division: "विभागणी",
    dateOfbirth: "जन्मतारीख",
    birthAddress: "जन्माचा पत्ता",
    remark: "शेरा",
    docsRemark: "कागदपत्रांची पडताळणी टिप्पणी",
    bonafiedPurpose: "बोनाफाईड प्रमाणपत्राचा उद्देश (इंग्रजीमध्ये)",
    bonafiedPurposeMr: "बोनाफाईड प्रमाणपत्राचा उद्देश (मराठीत)",
    approveBonafiedDate: "बोनाफाईड मंजूर/नकार दिनांक",
    approveLCDate: "शाळा सोडल्याचा दाखला मंजूर/नकार दिनांक",
    selectStudent: "विद्यार्थी निवडा",
    studentRequired: "विद्यार्थी आवश्यक आहे",
    reasonForLeavingSchoolMr: "शाळा सोडण्याचे कारण (मराठीत)",
    reasonForLeavingSchoolMrReq:
      "शाळा सोडण्याचे कारण (मराठीत) आवश्यक आहे / फक्त मराठी शब्द",
    reasonForLeavingSchoolEn: "शाळा सोडण्याचे कारण (इंग्रजीमध्ये)",
    reasonForLeavingSchoolEnReq:
      "शाळा सोडण्याचे कारण आवश्यक आहे / फक्त इंग्रजी शब्द असावेत",

    addNewTimetable: "नवीन वेळापत्रक जोडा",
    updateTimetable: "वेळापत्रक अद्यायावत करा",
    periodList: "वेळापत्रक सूची",
    day: "वार  ",
    from: "सुरू",
    to: "समाप्त",
    subject: "विषय",
    academicSubject: "शैक्षणिक विषय",
    teacher: "शिक्षक",
    recess: "सुट्टी",
    teachersForSubjects: "विषयांसाठी शिक्षक नियुक्त करा",
    selectSubject: "विषय निवडा",
    selectTeacher: "शिक्षक निवडा",
    go: "जा",

    2: "सोमवार",
    3: "मंगळवार",
    4: "बुधवार",
    5: "गुरुवार",
    6: "शुक्रवार",
    7: "शनिवार",
    fromTime: "या वेळेपासून",
    toTime: "या वेळेपर्यंत",
    Monday: "सोमवार",
    Tuesday: "मंगळवार",
    Wednesday: "बुधवार",
    Thursday: "गुरुवार",
    Friday: "शुक्रवार",
    Saturday: "शनिवार",

    search: "शोधा",
    clear: "हटवा",
    close: "बंद करा",
    teacherParentCommunication: "शिक्षक पालक संपर्क",
    add: "जोडा",
    save: "जतन करा",
    saveWeekelyTimetable: "आठवडा वेळापत्रक जोडा",
    finalSubmit: "अंतिम वेळापत्रक जतन करा ",
    edit: "संपादित करा",
    toggle: "टॉगल करा",
    updateAttendance: "उपस्थिती अद्यायावत करा",
    update: "अद्यायावत करा",
    exit: "बाहेर पडा",

    success: "सफलता!",
    attendanceUpdated: "उपस्थिती यशस्वीरित्या अद्यायावत केली गेली आहे",
    examSaved: "परीक्षा यशस्वीरित्या जतन केली गेली आहे",
    examUpdated: "परीक्षा यशस्वीरित्या अद्यायावत केली गेली आहे",
    error: "त्रुटी!",
    admissionRegitrationNo: "प्रवेश नोंदणी क्रमांक",

    aadharNumber: "आधार क्रमांक",
    schoolTeacher: "शाळेतील शिक्षक",
    gender: "लिंग",
    male: "पुरुष",
    female: "स्त्री",
    motherTongue: "मातृभाषा",
    permanentAddress: "कायमचा पत्ता",
    pincode: "पिन कोड",
    contactPersonName: "संपर्क व्यक्तीचे नाव",
    contactPersonNumber: "संपर्क व्यक्ती क्रमांक",
    schoolMaster: "शाळा मास्टर",
    schoolPrefix: "शाळेचा कोड",
    gisCode: "जी आय एस कोड",
    udiceCode: "UDISE क्रमांक",
    schoolAddress: "शाळेचा पत्ता",
    lattitude: "अक्षांश",
    longitude: "रेखांश",
    message: "संदेश",
    teacherName: "शिक्षकाचे नाव",
    selectAll: "सर्व निवडा",
    actions: "क्रिया",
    action: "क्रिया",
    age: "वय",
    status: "स्थिती",
    reject: "नकार",
    approve: "मंजूर",
    submit: "सबमिट",
    view: "पहा",
    principalRemarksEn: "मुख्याध्यापक रिमार्क्स (इंग्रजीमध्ये)",
    principalRemarksMr: "मुख्याध्यापक रिमार्क्स (मराठीमध्ये)",

    studentAdmissionForm: "विद्यार्थी प्रवेश अर्ज",
    studentPersonalInfo: "वैयक्तिक माहिती",
    studentOthInfo: "इतर माहिती",
    studentParentInfo: "आईवडील / पालक माहिती",
    lastSchoolInfo: "शेवटच्या शाळेची माहिती (लागू असल्यास)",
    accountDetails: "बँक खाते तपशील",
    accountNo: "बँक खाते क्रमांक",
    confirmBankAcNumber: "बँक खाते क्रमांकाची पुष्टी करा",
    bankName: "बँकेचे नाव",
    ifscCode: "बँक IFSC कोड",
    bankAdderess: "बँकेचा पत्ता",
    documents: "कागदपत्रे",
    accountHolderName: "खातेधारकाचे नाव",
    zoneName: "झोनचे नाव",
    wardName: "प्रभागाचे नाव",
    studentFirstName: "विद्यार्थ्याचे पहिले नाव",
    studentFirstNameMr: "विद्यार्थ्याचे पहिले नाव (मराठी मध्ये)",
    studentMiddleName: "विद्यार्थ्याचे मधले नाव",
    studentMiddleNameMr: "विद्यार्थ्याचे मधले नाव (मराठी मध्ये)",
    studentLastName: "विद्यार्थ्याचे आडनाव",
    studentLastNameMr: "विद्यार्थ्याचे आडनाव (मराठी मध्ये)",
    fatherFirstName: "वडिलांचे पहिले नाव",
    fatherMiddleName: "वडिलांचे मधले नाव",
    fatherLastName: "वडिलांचे आडनाव",
    motherName: "आईचे पहिले नाव",
    motherNameMr: "आईचे पहिले नाव (मराठी मध्ये)",
    motherMiddleName: "आईचे मधले नाव",
    motherLastName: "आईचे आडनाव",
    religion: "धर्म",
    casteName: "जातीचे नाव",
    subCastName: "उपजातीचे नाव",
    citizenship: "नागरिकत्व",
    nationality: "राष्ट्रीयत्व",
    birthPlace: "जन्म ठिकाण",
    birthPlaceMr: "जन्म ठिकाण (मराठी मध्ये)",
    studentState: "विद्यार्थी जन्मठिकाण राज्य",
    studentDist: "विद्यार्थी जन्मठिकाण जिल्हा",
    parentAddress: "पालकांचा पत्ता",
    parentOccupation: "पालकांचा व्यवसाय ",
    fatherMobileNumber: "वडिलांचा मोबाईल नंबर ",
    motherMobileNumber: "आईचा मोबाईल नंबर ",
    permanentAddress: "कायमचा पत्ता",
    parentFullName: "पालकांचे पूर्ण नाव",
    parentEmailId: "पालक ईमेल आयडी",
    colony: "वसाहत",
    district: "जिल्हा",
    lastSchoolName: "शेवटच्या शाळेचे नाव -जर लागू असेल तर",
    lastSchoolNameMr: "शेवटच्या शाळेचे नाव (मराठी मध्ये) -जर लागू असेल तर",
    lastSchoolAdmissionDate: "शाळा प्रवेशाची शेवटची तारीख - लागू असल्यास",
    lastSchoolAndFromWhenStudying: "शेवटचा वर्ग आणि कधीपासून अभ्यास",
    lastSchoolLeavingDate: "शाळा सोडण्याची शेवटची तारीख",
    studentBehaviour: "विद्यार्थ्याचे वर्तन",
    studentBehaviourMr: "विद्यार्थ्याचे वर्तन (मराठी मध्ये)",
    reasonForLeavingSchool: "शाळा सोडण्याचे कारण",

    studentBirthCertificate: "विद्यार्थी जन्म प्रमाणपत्र",
    studentSchoolLeavingCertificate:
      "विद्यार्थी शाळा सोडल्याचा दाखला (लागू असल्यास)",
    studentPhotograph: "विद्यार्थ्याचा फोटो",
    studentAadhar: "विद्यार्थी आधार कार्ड",
    parentAadhar: "पालक आधार कार्ड",
    studentLastYearMarksheet:
      "विद्यार्थी शेवटच्या वर्षाची मार्कशीट (लागू असल्यास)",

    selectExam: "परीक्षा निवडा",
    exam: "परीक्षा",
    examMarks: "परीक्षा गुण",
    examRequired: "परीक्षा आवश्यक आहे",
    selectTerm: "सत्र निवडा",
    term: "अवधी",
    termRequired: "सत्र आवश्यक आहे",
    marksObtained: "प्राप्त गुण",
    outOfMarks: "एकूण गुण",
    outOfMarksRequired: "एकूण गुण आवश्यक आहे",
    passingMarks: "उत्तीर्ण गुण",
    passingMarksRequired: "उत्तीर्ण गुण आवश्यक आहे",
    marksError: "मिळवलेले गुण हे एकूण गुणांच्या आत असणे आवश्यक आहे",
    updateMarks: "गुण अद्यायावत करा",
    marksUpdated: "गुण यशस्वीरित्या अद्यायावत केले गेले आहेत",

    deactivate: "निष्क्रिय करा",
    activate: "सक्रिय करा",
    areYouSureToDeactivate: "तुम्हाला निष्क्रिय करण्याची खात्री आहे?",
    areYouSureToActivate: "तुम्हाला सक्रिय करण्याची खात्री आहे?",
    deactivateSuccess: "निष्क्रिय करण्यात यशस्वी झाले",
    activateSuccess: "सक्रिय करण्यात यशस्वी झाले",
    previewReport: "पूर्वावलोकन अहवाल",
    classTimetableReport: "वर्ग वेळापत्रकाचा अहवाल",
    teacherClassTimetableReport: "शिक्षक वर्ग वेळापत्रकाचा अहवाल",
    generateReport: "अहवाल तयार करा",
    fromDate: "या तारखेपासून",
    toDate: "या तारखेपर्यंत",
    studentsAttendanceReport: "विद्यार्थ्यांचा उपस्थिती अहवाल",
    schoolLeavingCert: "शाळा सोडल्याचा दाखला",
    studentBonafideCert: "विद्यार्थी बोनाफाईड प्रमाणपत्र",
    fatherQualification: "वडील शैक्षणिक पात्रता",
    fatherOccupation: "वडील व्यवसाय",
    fatherIncome: "वडील उत्पन्न",
    motherQualification: "आईची शैक्षणिक पात्रता",
    motherOccupation: "आईचा व्यवसाय",
    motherIncome: "आईचे उत्पन्न",
    stateNameMr: "राज्याचे नाव(मराठी मध्ये)",
    stateName: "राज्याचे नाव(इंग्रजी मध्ये)",
    state: "राज्याचे नाव",
    relation: "खातेदाराशी संबंध",
    saralId: "सरल आयडी",
    view: "पहा",
    selectMedium: "मध्यम निवडा",
    disabilityTypes: "अपंगत्वाचे प्रकार",
    disabilityTypesEn: "अपंगत्वाचे प्रकार (इंग्रजी मध्ये)",
    disabilityTypesMr: "अपंगत्वाचे प्रकार (मराठी मध्ये)",
    disabilityInfo: "अपंगत्व माहिती (लागू असल्यास)",

    percentageofDisability: "अपंगत्वाची टक्केवारी",
    certificateOfDisability: "अपंगत्व प्रमाणपत्र",
    updateStudentInfo: "विद्यार्थी माहिती अद्यतनित करा",
    search: "शोधा",
    attachmentDocument: "आवश्यक कागदपत्रे",
    designationOfOrderIssuancePerson: "ऑर्डर जारी करणाऱ्या व्यक्तीचे पद",
    nameofPrderIssuancePerson: "ऑर्डर जारी करणाऱ्या व्यक्तीचे नाव",
    examTimeTableReport: "परीक्षा वेळापत्रक अहवाल",
    serviceName: "सेवेचे नाव",
    applicationDate: "अर्जाची तारीख",
    examTimetable: "परीक्षेचे वेळापत्रक",
    addTimetable: "वेळापत्रक जोडा",
    timetable: "वेळापत्रक",
    // ----------------------school validations Labels mr-----------------------------------------------------------------------------------
    schoolReq: "शाळेचे नाव आवश्यक आहे !!",
    ayReq: "शैक्षणिक वर्ष आवश्यक आहे !!",
    classReq: "वर्गाचे नाव आवश्यक आहे !!",
    divReq: "तुकडीचे नाव आवश्यक आहे !!",
    studentReq: "विद्यार्थ्याचे नाव आवश्यक आहे !!",
    bonafiedPurposeReq:
      "इंग्रजीत बोनाफाईड उद्देश आवश्यक आहे !! फक्त इंग्लिश शब्द",
    bonafiedPurposeMrReq:
      "मराठीमध्ये बोनाफाईड उद्देश आवश्यक आहे !! फक्त मराठी शब्द",
    studentRollNoReq: "विद्यार्थी रोल नंबर आवश्यक आहे !! फक्त अंक असावेत",
    other: "इतर",

    schoolMediumReq: "शालेय माध्यम आवश्यक आहे!",
    studentFirstNameReq: "विद्यार्थ्याचे नाव आवश्यक !! / फक्त इंग्लिश शब्द",
    studentMiddleNameReq:
      "विद्यार्थ्याचे मधले नाव आवश्यक !! / फक्त इंग्लिश शब्द",
    studentLastNameReq: "विद्यार्थ्याचे आडनाव आवश्यक !! / फक्त इंग्लिश शब्द",
    firstNameMrReq: "विद्यार्थ्याचे नाव आवश्यक (मराठीत) !! फक्त मराठी शब्द",
    middleNameMrReq:
      "विद्यार्थ्याचे मधले नाव आवश्यक (मराठीत) !! फक्त मराठी शब्द",
    lastNameMrReq: "विद्यार्थ्याचे आडनाव आवश्यक (मराठीत) !! फक्त मराठी शब्द",
    fatherFirstNameReq: "वडिलांचे नाव आवश्यक !! फक्त शब्द असावेत",
    fatherMiddleNameReq: "वडिलांचे मधले नाव आवश्यक !! फक्त शब्द असावेत",
    fatherLastNameReq: "वडील आडनाव आवश्यक !! फक्त शब्द असावेत",
    motherNameReq: "आईचे नाव आवश्यक !!/ फक्त इंग्लिश शब्द",
    motherMiddleNameReq: "आईचे मधले नाव आवश्यक !! / फक्त शब्द असावेत",
    motherLastNameReq: "आईचे आडनाव आवश्यक !! / फक्त शब्द असावेत",
    motherNameMrReq: "आईचे नाव (मराठीत) आवश्यक!! / फक्त मराठी शब्द",
    studentGenderReq: "तुमचे लिंग निवडा",
    mobileReq:
      "फक्त अंक असणे आवश्यक आहे / मोबाईल क्रमांक 10 क्रमांकाचा असणे आवश्यक आहे",
    emailReq: "ईमेलआयडी आवश्यक आहे आणि योग्य स्वरूप असणे आवश्यक आहे",
    aadharNoReq:
      "फक्त अंक असणे आवश्यक आहे / आधार क्रमांक 12 क्रमांकाचा असणे आवश्यक आहे",
    religionKeyReq: "तुमचा धर्म निवडा",
    casteKeyReq: "तुमचे जातीचे नाव निवडा",
    subCastKeyReq: "तुमचे पोटजात नाव निवडा",
    citizenshipNameReq: "तुमचे नागरिकत्व नाव निवडा",
    motherTongueNameReq: "तुमच्या मातृभाषेचे नाव निवडा",
    studentBirthPlaceReq: "तुमचे जन्मस्थान प्रविष्ट करा (इंग्रजीमध्ये)",
    birthPlacemrReq: "तुमचे जन्मस्थान (मराठीत) प्रविष्ट करा / फक्त मराठी शब्द",
    studentDateOfBirthReq: "तुमची जन्मतारीख निवडा",
    stateNameReq: "तुमच्या राज्याचे नाव निवडा",
    districtNameReq: "तुमच्या जिल्ह्याचे नाव प्रविष्ट करा / फक्त शब्द असावेत",
    familyPermanentAddressReq: "तुमच्या कुटुंबाचा कायमचा पत्ता प्रविष्ट करा",
    parentFullNameReq: "पालकांचे पूर्ण नाव आवश्यक !! / फक्त शब्द असावेत",
    parentEmailIdReq:
      "पालक ईमेल आयडी आवश्यक आहे आणि ते योग्य स्वरूप असले पाहिजे !!",
    parentAddressReq: "पालक पत्ता आवश्यक !!",
    fatherContactNumberReq:
      "वडील संपर्क क्रमांक आवश्यक आहे! आणि फक्त अंक असणे आवश्यक आहे / 10 क्रमांक असणे आवश्यक आहे",
    motherContactNumberReq:
      "मदर संपर्क क्रमांक आवश्यक आहे! आणि फक्त अंकांचा असणे आवश्यक आहे / 10 क्रमांक असणे आवश्यक आहे",
    fatherQualificationReq: "वडील पात्रता आवश्यक !!",
    fatherOccupationReq: "वडिलांचा व्यवसाय आवश्यक !! फक्त शब्द असावेत",
    fatherIncomeReq: "वडिलांचे उत्पन्न आवश्यक !! फक्त अंक असावेत",
    motherQualificationReq: "आई पात्रता आवश्यक !!",
    motherOccupationReq: "आईचा व्यवसाय आवश्यक !! फक्त शब्द असावेत",
    motherIncomeReq: "आईचे उत्पन्न आवश्यक !! फक्त शब्द असावेत",
    colonyNameReq: "तुमच्या क्षेत्राचे/वस्तीचे नाव प्रविष्ट करा",
    parentDistrictNameReq: "पालक जिल्ह्याचे नाव आवश्यक !! फक्त शब्द असावेत",
    parentStateNameReq: "पालक राज्याचे नाव आवश्यक !! फक्त शब्द असावेत",
    parentPincodeReq:
      "पालक पिनकोड आवश्यक !! /आणि फक्त अंक असणे आवश्यक आहे / 6 संख्या असणे आवश्यक आहे",
    accountNoReq: "खाते क्रमांक आवश्यक आहे !! / आणि फक्त अंक असणे आवश्यक आहे",
    confirmBankAcNumberReq:
      "खाते क्रमांक आणि पुष्टी बँक खाते क्रमांक समान असणे आवश्यक आहे आणि ते आवश्यक आहे !!",
    accountHolderNameReq: "खातेधारकाचे नाव आवश्यक !! फक्त शब्द असावेत",
    bankNameReq: "बँकेचे नाव आवश्यक !! फक्त शब्द असावेत",
    ifscCodeReq: "बँकेचा IFSC कोड आवश्यक !! आणि तो योग्य स्वरूपाचा असावा",
    bankAdderessReq: "बँकेचा पत्ता आवश्यक !!",
    relationWithAccountantHolderReq: "खातेधारकाशी असलेले संबंध आवश्यक !!",
    studentBirthCertificateReq: "विद्यार्थी जन्म प्रमाणपत्र आवश्यक",
    studentPhotographReq: "विद्यार्थी छायाचित्र आवश्यक",
    studentAadharCardReq: "विद्यार्थ्यांचे आधार कार्ड आवश्यक",
    parentAadharCardReq: "पालकांचे आधार कार्ड आवश्यक",

    selectStudReq: "कृपया किमान एक विद्यार्थी निवडा",
    teacherKeyReq: "शिक्षकाचे नाव आवश्यक !!",
    commSubjectReq: "संवाद विषयाचे नाव आवश्यक !!",
    commMessageReq: "संवाद संदेश आवश्यक !!",

    // masters
    subjectReq: "विषयाचे नाव आवश्यक आहे !!",
    fromDateReq: "तारीख पासून आवश्यक आहे !!",
    toDateReq: "आजपर्यंत आवश्यक आहे !!",

    typeOfDisabilityReq: "अपंगत्वाचा प्रकार आवश्यक आहे !! फक्त इंग्लिश शब्द",
    typeOfDisabilityMrReq:
      "मराठीमध्ये अपंगत्वाचा प्रकार आवश्यक आहे !! / फक्त मराठी शब्द",
    remarkReq: "टिप्पणी आवश्यक आहे !!",

    zoneReq: "झोनचे नाव आवश्यक आहे !!",
    schoolNameMrReq: "शाळेचे नाव मराठीत आवश्यक!!",
    udiceCodeReq: "शाळेचा UDICE कोड आवश्यक!!",
    schoolAddressReq: "शाळेचा पत्ता आवश्यक!!",
    pincodeReq:
      "पिनकोड आवश्यक !! / आणि फक्त अंक असणे आवश्यक आहे / 6 संख्या असणे आवश्यक आहे",
    gisCodeReq: "GIS कोड आवश्यक आहे !!",
    contactPersonNameReq: "शाळा संपर्क व्यक्तीचे नाव आवश्यक आहे !!",
    contactPersonNumberReq:
      "शाळा संपर्क व्यक्तीचा मोबाईल नंबर आवश्यक आणि फक्त अंक असणे आवश्यक आहे / 10 क्रमांक असणे आवश्यक आहे",
    schoolEmailIdReq:
      "शाळेचा ईमेल आयडी आवश्यक आहे आणि तो योग्य स्वरूपाचा असावा !!",

    divPrefixReq: "विभाग उपसर्ग आवश्यक आहे !!",
    intakeReq: "आसन क्षमता (संख्या )आवश्यक आहे !! ",

    empId: "कर्मचारी आयडी",
    teacherPhotograph: "शिक्षक छायाचित्र",
    firstNameReq: "नाव आवश्यक !! फक्त शब्द असावेत",
    middleNameReq: "मधले नाव आवश्यक !! फक्त शब्द असावेत",
    lastNameReq: "आडनाव आवश्यक !! फक्त शब्द असावेत",
    genderReq: "लिंग आवश्यक !!",
    contactDetailsReq:
      "मोबाईल नंबर आवश्यक आहे आणि फक्त अंकांचा असावा / 10 नंबर असणे आवश्यक आहे",
    emailDetailsReq: "EmailId आवश्यक आहे आणि ते योग्य स्वरूपाचे असावे!!",
    aadharNumberReq:
      "आधार क्रमांक आवश्यक आहे आणि फक्त अंकांचा असणे आवश्यक आहे / 12 संख्या असणे आवश्यक आहे!!",
    motherTongueNameReq: "मातृभाषेचे नाव आवश्यक !!",
    permanentAddressReq: "कायमचा पत्ता आवश्यक!!",

    stateNameEnReq: "राज्याचे इंग्रजीत नाव आवश्यक !! / फक्त इंग्लिश शब्द",
    stateNameMrReq: "राज्याचे मराठीत नाव आवश्यक!! / फक्त मराठी शब्द",

    // ----------------------ITI Labels mr-----------------------------------------------------------------------------------

    itiTraineeBonafideCert: "आयटीआय प्रशिक्षणार्थी बोनाफाइड प्रमाणपत्र",
    itiName: "आयटीआयचे नाव",
    tradeName: "ट्रेडचे नाव",
    traineeName: "प्रशिक्षणार्थीचे नाव",
    traineeMoNo: "प्रशिक्षणार्थी मोबाईल नंबर",
    traineeEmailId: "प्रशिक्षणार्थी ईमेल आयडी",
    selectIti: "आयटीआयचे नाव निवडा",
    selectTrade: "ट्रेडचे नाव निवडा",
    selectTrainee: "प्रशिक्षणार्थी निवडा",
    selectTraineeComm: "किमान एक प्रशिक्षणार्थी नाव आवश्यक !!",
    registrationNo: "नोंदणी क्रमांक",
    grpInstructorRemarksEn: "ग्रुप इंस्ट्रक्टर रिमार्क्स (इंग्लिशमध्ये)",
    grpInstructorRemarksMr: "ग्रुप इंस्ट्रक्टर रिमार्क्स (मराठीमध्ये)",

    itiTraineeDetails: "आयटीआय प्रशिक्षणार्थी तपशील",
    traineeFirstName: "प्रशिक्षणार्थीचे पहिले नाव",
    traineeMiddleName: "प्रशिक्षणार्थीचे मधले नाव",
    traineeLastName: "प्रशिक्षणार्थीचे आडनाव",
    casteCategory: "जात प्रवर्ग",
    locatedAt: "येथे स्थित आहे",
    preview: "पूर्वावलोकन",
    areaName: "क्षेत्राचे नाव",
    allotementDetails: "अलौटमेंट तपशील",
    allotementRound: "अलौटमेंटची फेरी",
    preferenceNumber: "प्राधान्य क्रमांक",
    allotementCategory: "अलौटमेंट श्रेणी",
    mcode: "एम-कोड",
    allotedItiName: "वाटप केलेले आयटीआय नाव",
    allotedTradeName: "वाटप केलेले ट्रेडचे नाव",
    lastSchoolDetails: "शेवटच्या शाळेची माहिती",
    lastSchoolNamee: "शेवटच्या शाळेचे नाव",
    lastSchoolAdmissionDatee: "शाळा प्रवेशाची शेवटची तारीख ",
    lastClass: "शेवटचा वर्ग",
    traineePhotograph: "प्रशिक्षणार्थी फोटो",
    traineeAadhar: "प्रशिक्षणार्थी आधार कार्ड",
    traineeBirthCert: "प्रशिक्षणार्थी जन्म प्रमाणपत्र",
    traineeTc: "प्रशिक्षणार्थी शाळा बदली प्रमाणपत्र",
    traineeLastYrMarksheet: "प्रशिक्षणार्थी शेवटच्या वर्षाची मार्कशीट",
    dvetItiAllotementLetter: "डीव्हीईटी आयटीआय वाटप पत्र",
    nonCreamyLayer: "नॉन-क्रिमी लेयर सर्टिफिकेट",
    incomeProof: "उत्पन्नाचा पुरावा प्रमाणपत्र",
    instructorParentComm:
      "प्रशिक्षक/गट प्रशिक्षक आणि पालक/प्रशिक्षणार्थी संवाद",
    instructorName: "प्रशिक्षकाचे नाव",
    selectInstructor: "प्रशिक्षकाचे नाव निवडा",
    teacherOrInstructorName: "शिक्षक / प्रशिक्षकाचे नाव",
    itiTeacherOrInstructorMaster: "आयटीआय शिक्षक / प्रशिक्षक मास्टर",
    isInstructorOrTeacher: "शिक्षक आहे / प्रशिक्षक आहे",

    totalAdmissionFees: "एकूण प्रवेश फी",
    feesAmountToPay: "फी भरायची रक्कम",
    remainingFeesAmount: "उरलेली फी रक्कम",
    paymentType: "पैसे भरण्याची पध्दत",
    paymentMode: "भरणा मोड",
    accountantRemarks: "लेखापाल टिप्पणी",
    groupInstructorRemarksEnRequiredEn: "इंग्लिशमध्ये टिप्पणी आवश्यक आहे",
    groupInstructorRemarksEnRequiredMr: "मराठीत टिप्पणी आवश्यक आहे",
    principalRemarksRequiredEn: "इंग्लिशमध्ये टिप्पणी आवश्यक आहे",
    principalRemarksRequiredMr: "मराठीत टिप्पणी आवश्यक आहे",
    itiKeyRequired: "आवश्यक आहे",
    itiTraineeAttendance: "आयटीआय प्रशिक्षणार्थीची उपस्थिती",
    itiPrefix: "आयटीआय उपसर्ग",
    intakeCapacity: "आसन क्षमता",
    itiCode: "आयटीआय कोड",
    required: "आवश्यक आहे",
    itiMaster: "आयटीआय मास्टर",
    itiTradeDivMaster: "आयटीआय ट्रेड डिव्हिजन मास्टर",
    itiType: "आयटीआय प्रकार",
    tradeFees: "ट्रेड फी",
    tradeDesc: "ट्रेड वर्णन",
    itiTradeMaster: "आयटीआय ट्रेड मास्टर",
    cautionFees: "खबरदारी शुल्क",
    fees: "शुल्क",
    locationName: "स्थानाचे नाव",
    itiFeesStructureMaster: "आयटीआय फी स्ट्रक्चर मास्टर",
    castCertificate: "जात प्रमाणपत्र",
    mediumOfEdu: "शिक्षणाचे माध्यम",
    parentMobileNo: "पालकांचा मोबाईल क्रमांक",
    tradeDuration: "ट्रेड कालावधी (वर्षामध्ये)",
    tradeUnit: "ट्रेड युनिट",
    tradeAffiliationNo: "ट्रेड संलग्नता क्रमांक",
    tradeType: "ट्रेड प्रकार",
    admissionFees: "प्रवेश फी",
    itiSubMaster: "आयटीआय ट्रेड विषय मास्टर",
    tradeSubName: "विषयाचे नाव",
    tradeSubPref: "विषय उपसर्ग",
    tradeSubMarks: "गुण",
    itiTraineeAttendanceReport: "आयटीआय प्रशिक्षणार्थी उपस्थिती अहवाल",
    lastSchoolAdmissionDateiti: "अंतिम शाळा प्रवेश दिनांक",

    // iti transactions mr validations
    itiNameReq: "आयटीआय नाव आवश्यक !! फक्त शब्द असावेत",
    itiTradeReq: "आयटीआय ट्रेड नाव आवश्यक !! फक्त शब्द असावेत",
    traineeNameReq: "प्रशिक्षणार्थी नाव आवश्यक !!",
    instructorReq: "प्रशिक्षकाचे नाव आवश्यक !!",

    allotmentRoundReq: "वाटप फेरी क्रमांक आवश्यक !! / फक्त अंक असणे आवश्यक आहे",
    preferenceNumberReq: "प्राधान्य क्रमांक आवश्यक !!",
    allotmentCategoryReq: "वाटप श्रेणी आवश्यक !!",
    traineeFirstNameReq: "प्रशिक्षणार्थी नाव आवश्यक !! फक्त शब्द असावेत",
    traineeMiddleNameReq: "प्रशिक्षणार्थी मधले नाव आवश्यक !! फक्त शब्द असावेत",
    traineeLastNameReq: "प्रशिक्षणार्थी आडनाव आवश्यक !! फक्त शब्द असावेत",
    fatherFirstNameReqAdmission: "वडिलांचे नाव आवश्यक !! / फक्त शब्द असावेत",
    fatherMiddleNameReqAdmission:
      "वडिलांचे मधले नाव आवश्यक !! / फक्त शब्द असावेत",
    fatherLastNameReqAdmission: "वडिलांचे आडनाव आवश्यक !! / फक्त शब्द असावेत",
    motherFirstNameReq: "आईचे पहिले नाव आवश्यक !! फक्त शब्द असावेत",

    traineeMobileNumberReq:
      "प्रशिक्षणार्थी मोबाईल नंबर आवश्यक !! / फक्त अंकांचा असावा आणि तो 10 क्रमांकाचा असावा",
    parentMobileNumberReq:
      "पालकांचा मोबाईल नंबर आवश्यक!! / फक्त अंकांचा असावा आणि तो 10 क्रमांकाचा असावा",
    traineeEmailIdReq:
      "प्रशिक्षणार्थी EmailId आवश्यक आहे आणि ते योग्य स्वरूपाचे असावे!!",
    traineeAadharNumberReq:
      "प्रशिक्षणार्थी आधार क्रमांक आवश्यक !! / फक्त अंकांचा असावा आणि तो 12 क्रमांकाचा असावा",
    casteCategoryKeyReq: "जात श्रेणी आवश्यक !!",
    casteKeyReq: "जात आवश्यक !!",
    nationalityReq: "राष्ट्रीयत्व आवश्यक !!",
    motherTongueNameReq: "मातृभाषेचे नाव आवश्यक !!",
    addressReq: "पत्ता आवश्यक !!",

    locatedAtReq: "स्थान आवश्यक !! फक्त शब्द असावेत",
    areaReq: "क्षेत्राचे नाव आवश्यक !!",
    traineeDateOfBirthReq: "प्रशिक्षणार्थीची जन्मतारीख आवश्यक!!",
    traineeDateOfBirthReqAdmission:
      "प्रशिक्षणार्थीची जन्मतारीख आवश्यक !! आणि ते 15 वर्षांचे असावे",
    traineeBirthPlaceReq:
      "प्रशिक्षणार्थी जन्म ठिकाण आवश्यक !! फक्त शब्द असावेत",
    lastSchoolNameReq: "शेवटचे शाळेचे नाव आवश्यक !! फक्त शब्द असावेत",
    lastClassReq: "अंतिम वर्गाचे नाव आवश्यक !!",
    mediumOfEducationReq:
      "अंतिम वर्गाचे शिक्षण माध्यम आवश्यक !! फक्त शब्द असावेत",
    lastSchoolAdmissionDateitiReq: "शेवटची शाळा प्रवेश तारीख आवश्यक!!",
    lastSchoolLeavingDateitiReq: "शाळा सोडण्याची शेवटची तारीख आवश्यक!!",
    lastSchoolLeavingReasonReq:
      "शेवटची शाळा सोडण्याचे कारण आवश्यक !! फक्त शब्द असावेत",

    traineePhotographReq: "प्रशिक्षणार्थी छायाचित्र आवश्यक !!",
    traineeAadharCardDocumentReq: "प्रशिक्षणार्थी आधार कार्ड आवश्यक !!",
    leavingCertificateDocumentReq:
      "प्रशिक्षार्थी शाळा सोडण्याचे प्रमाणपत्र आवश्यक !!",
    lastYearMarksheetReq:
      "प्रशिक्षार्थीची मागील वर्षाची मार्कशीट आवश्यक आहे !!",
    dvetAllotmentLetterReq: "DVET ITI वाटप पत्र आवश्यक !!",

    actionReq: "स्थिती/क्रिया आवश्यक आहे!!",

    admissionFeesReq: "प्रवेश शुल्क आवश्यक !! / फक्त अंक असणे आवश्यक आहे !!",
    depositReq: "सावधगिरी शुल्क आवश्यक !! / फक्त अंक असणे आवश्यक आहे !!",
    totalAdmissionFeeRsReq:
      "एकूण प्रवेश शुल्क आवश्यक !! / फक्त अंक असणे आवश्यक आहे !!",
    admissionFeeAmountToPayReq:
      "प्रवेश शुल्काची रक्कम भरणे आवश्यक आहे !! / फक्त अंक असणे आवश्यक आहे !!",
    remainingFeesAmountReq:
      "उर्वरित शुल्क रक्कम आवश्यक !! / फक्त अंक असणे आवश्यक आहे !!",
    paymentTypeKeyReq: "पेमेंट प्रकार आवश्यक !!",
    paymentModeKeyReq: "पेमेंट मोड आवश्यक !!",
    accountantRemarksReq: "लेखापाल टिपणी आवश्यक !!",

    purposeOfBonafideEnReq: "बोनाफाईडचा उद्देश (इंग्रजीमध्ये) आवश्यक आहे !!",
    purposeOfBonafideMrReq: "बोनाफाइडचा उद्देश (मराठीमध्ये) आवश्यक आहे !!",

    groupInstructorRemarksEnReq: "टिप्पणी (इंग्रजीमध्ये) आवश्यक!!",
    groupInstructorRemarksMrReq: "टिप्पणी (मराठीमध्ये) आवश्यक !!",

    //  masters validations

    feesReq: "शुल्क आवश्यक !! / फक्त अंक असणे आवश्यक आहे !!",

    itiPrefixReq: "ITI उपसर्ग आवश्यक आहे !!",
    itiCodeReq: "ITI कोड आवश्यक आहे !!",
    intakeCapacityReq: "इनटेक क्षमता आवश्यक !! / ते फक्त अंक असले पाहिजेत !!",
    itiContactPersonNameReq:
      "संपर्क व्यक्तीचे नाव आवश्यक आहे !! फक्त शब्द असावेत",
    itiContactPersonNumberReq:
      "संपर्क व्यक्तीचा मोबाईल नंबर आवश्यक आहे आणि तो फक्त अंकांचा असावा / 10 नंबरचा असावा",
    itiAddressReq: "ITI पत्ता आवश्यक आहे !!",
    gisIdReq: "GIS आयडी आवश्यक आहे !!",

    teacherTypeReq: "शिक्षक आहे की प्रशिक्षक ? आवश्यक आहे !!",

    tradeDurationReq:
      "ट्रेड कालावधी (वर्षात) आवश्यक !! / आणि फक्त अंक असणे आवश्यक आहे",
    tradeUnitReq: "ट्रेड युनिट आवश्यक !!",
    tradeAffiliationNoReq: "ट्रेड संलग्नता क्रमांक आवश्यक !!",
    tradeTypeReq: "ट्रेड प्रकार आवश्यक !!",
    tradeDescriptionReq: "ट्रेड वर्णन आवश्यक !!",

    subjectPrefixReq: "विषय उपसर्ग आवश्यक !!",
    marksReq: "गुण आवश्यक !! / आणि फक्त अंक असावेत !!",
  },
};

export default schoolLabels;
