export default {
    en: {
      module: 'Town Planning',
      dashboard: 'Pimpri-Chinchwad Municipal Corporation Dashboard',
      master: 'Masters',
      transactions: 'Transactions',
      report: 'Reports',
      masterPath: 'Town Planning / Master ',
      transactionPath: 'Town Planning / Transaction ',
      reportPath: 'Town Planning / Report ',
  
      //breadcrum
      landReservationPath: 'Town Planning / Master / Land Reservation ',
      ZoneGatAndVillageMappingPath:
        'Town Planning / Master / Zone Gat and Village Mapping',
      villageWiseLandReservationEntryPath:
        'Town Planning / Master / Village Wise Land Reservation Entry',
      villageMappingWithDesignationPath:
        'Town Planning / Master / Village Mapping With Designation',
      partMapPath: 'Town Planning / Transaction / Part Map',
      zoneCertificatePath: 'Town Planning / Transaction / Zone Certificate',
      developementPlanOpinionPath:
        'Town Planning / Transaction / Development Plan Opinion',
  
      //label title
      landReservation: 'Land Reservation',
      ZoneGatAndVillageMapping: 'Zone Gat and Village Mapping',
      villageWiseLandReservationEntry: 'Village Wise Land Reservation Entry',
      villageMappingWithDesignation: 'Village Mapping With Designation',
      partMap: 'Part Map',
      zoneCertificate: 'Zone Certificate',
      developementPlanOpinion: 'Development Plan Opinion',
      setBackCertificate: 'Set Back Certificate',
  
      //other labels
      landReservationID: 'Land Reservation ID',
      reservationName: 'Reservation Name',
      reservationNameEn: 'Reservation Name in English',
      reservationNameMr: 'Reservation Name in Marathi',
      surveyNumber: 'Survey No.',
      landReservationLegend: 'Land Reservation Legend',
      reservationAreaInHector: 'Reservation Area (In Hector)',
      landInPossession: 'Land in Possession',
      remark: 'Remark',
      villageName: 'Village Name',
      gatName: 'Gat Name',
      zoneName: 'Zone Name',
      landReservationName: 'Land Reservation Name',
      citySurveyNo: 'City Survey No.',
      reservationNo: 'Reservation No.',
      landNotInPossessionInHector: 'Land Not In Possession (in Hector)',
      landInPossessionInHector: 'Land in Possession (in Hector)',
      ddtp: 'DDTP ',
      deAndTp: 'Dy Engineer /Town Planner',
      atpAndJe: 'Asst. Town Planner /Junior Engineer',
      applicationDate: 'Application Date',
      applicationNo: 'Application No.',
      fullName: 'Full Name',
      pincode: 'Pincode',
      status: 'Status',
      serviceName: 'Service Name',
      title: 'Title',
      firstNameEn: 'First Name (in English)',
      middleNameEn: 'Middle Name (in English)',
      surnameEn: 'Last Name (in English)',
      firstNameMr: 'First Name (in Marathi)',
      middleNameMr: 'Middle Name (in Marathi)',
      surnameMr: 'Last Name (in Marathi)',
      gender: 'Gender',
      mobile: 'Mobile',
      panNo: 'PAN No.',
      email: 'Email',
      aadharNo: 'Aadhaar No.',
      serviceCompletionDate: 'Service Completion Date',
      isCurrentUser: 'Same as logged in user',
      personalDetails: 'Personal Details',
      areaDetails: 'Area Details',
      documentUpload: 'Documents Upload',
      applicationCreated: 'Application Submitted Successfully',
      addFile: 'Choose File',
      fileName: 'File Name',
      mandatoryOrOptional: 'Mandatory/Optional',
      mandatory: 'Mandatory',
      optional: 'Optional',
      upload: 'Upload',
      next: 'Next',
      preview: 'Preview',
      verify: 'Verify',
      reject: 'Reject',
      noFileFound: 'No file found',
      verified: 'Verified',
      surveyNo: 'Survey No.',
      gisLocation: 'GIS Location',
      flatNo: 'Flat/Building No.',
      buildingName: 'Building Name',
      roadName: 'Road Name',
      landmark: 'Landmark',
      ctsNo: 'CTS No.',
      plotNo: 'Plot No.',
      documentVerification: 'Document Verification',
      legend: 'Legend',
      landReservationNo: 'Land Reservation No.',
      electoralWard: 'Electoral Ward',
      landUnderPossession: 'Land Under Possession',
      landNotUnderPossession: 'Land Not Under Possession',
      appropriateAuthority: 'Appropriate Authority',
      authorityNameEn: 'Authority Name in English',
      authorityNameMr: 'Authority Name in Marathi',
  
      attachFile: 'Attach File',
      srNo: 'Sr. No',
      actions: 'Actions',
  
      //Remarks
      selectDate: 'Please select a date',
      selectTitle: 'Please select a title',
      enterFName: 'Please enter first name ',
      enterMName: 'Please enter middle name ',
      enterLName: 'Please enter last name ',
      selectAdvocateCategory: 'Please select a category',
      enterCouncilName: 'Please enter council name',
      enterArea: 'Please enter area ',
      enterRoadName: 'Please enter road name ',
      enterLandmark: 'Please enter a landmark ',
      enterCity: 'Please enter a city ',
      enterPinCode: 'Please enter a pincode ',
      enterPhoneNo: 'Please enter a phone no. ',
      enterMobileNo: 'Please enter a mobile no. ',
      enterEmailAddress: 'Please enter an e-mail. ',
      enteraadhaarNo: 'Please enter an aadhaar no. ',
      enterpanNo: 'Please enter an pan no. ',
      enterRemarks: 'Please enter a remark. ',
  
      //buttons
      add: 'Add',
      save: 'Save',
      update: 'Update',
      clear: 'Clear',
      exit: 'Exit',
      back: 'Back',
      saveAndNext: 'Save & Next',
      finish: 'Finish',


      petAnimals: 'Pet Animals',
    },
  
    mr: {
      module: 'शहर नियोजन',
      dashboard: 'पिंपरी-चिंचवड महानगरपालिका डॅशबोर्ड',
      master: 'मास्टर्स',
      transactions: 'व्यवहार',
      report: 'अहवाल',
      masterPath: 'शहर नियोजन/ मास्टर ',
      transactionPath: 'शहर नियोजन/ व्यवहार ',
      reportPath: 'शहर नियोजन/ अहवाल ',
  
      //breadcrum
      landReservationPath: 'शहर नियोजन/ मास्टर / जमीन आरक्षण',
      ZoneGatAndVillageMappingPath:
        'शहर नियोजन/ मास्टर / प्रभाग-गट आणि गाव मॅपिंग',
      villageWiseLandReservationEntryPath:
        'शहर नियोजन/ मास्टर / गावनिहाय जमीन आरक्षण नोंद',
      villageMappingWithDesignationPath:
        'शहर नियोजन/ मास्टर / पदनामासह गाव मॅपिंग',
      partMapPath: 'शहर नियोजन / व्यवहार / भाग नकाशा',
      zoneCertificatePath: 'शहर नियोजन / व्यवहार / झोन प्रमाणपत्र',
      developementPlanOpinionPath: 'शहर नियोजन / व्यवहार / विकास योजना मत',
  
      //titles
      landReservation: 'जमीन आरक्षण',
      ZoneGatAndVillageMapping: 'प्रभाग-गट आणि गाव मॅपिंग',
      villageWiseLandReservationEntry: 'गावनिहाय जमीन आरक्षण नोंद',
      villageMappingWithDesignation: 'पदनामासह गाव मॅपिंग',
      partMap: 'भाग नकाशा',
      zoneCertificate: 'झोन प्रमाणपत्र',
      developementPlanOpinion: 'विकास योजना मत',
      setBackCertificate: 'सामासिक अंतर दाखला',
  
      //other labels
      landReservationID: 'जमीन आरक्षण क्र',
      reservationName: 'आरक्षणाचे नाव',
      reservationNameEn: 'आरक्षणाचे नाव इंग्रजीत',
      reservationNameMr: 'आरक्षणाचे नाव मराठीत',
      surveyNumber: 'सर्वेक्षण क्र',
      landReservationLegend: 'जमीन आरक्षण आख्यायिका',
      reservationAreaInHector: 'हेक्टर मध्ये आरक्षण क्षेत्र',
      landInPossession: 'ताब्यात जमीन',
      remark: 'टिप्पणी',
      villageName: 'गावाचे नाव',
      gatName: 'गटाचे नाव',
      zoneName: 'झोनचे नाव',
      landReservationName: 'जमीन आरक्षण नाव',
      citySurveyNo: 'शहर सर्वेक्षण क्र',
      reservationNo: 'आरक्षण क्र',
      landNotInPossessionInHector: 'ताब्यात नसलेली जमीन (हेक्टरमध्ये)',
      landInPossessionInHector: 'ताब्यात जमीन (हेक्टरमध्ये)',
      ddtp: 'डी.डी.टी.पी',
      deAndTp: 'उपअभियंता /नगर नियोजक',
      atpAndJe: 'सहाय्यक नगर नियोजक /कनिष्ठ अभियंता',
      applicationDate: 'अजाणची तारीख',
      applicationNo: 'अर्ज क्रमांक',
      fullName: 'पूर्ण नाव',
      Zone: 'झोन',
      pincode: 'पिन कोड',
      status: 'स्थिती',
      serviceName: 'सेवेचे नाव',
      title: 'शीर्षक',
      firstNameEn: 'अर्जदाराचे पहिले नाव (इंग्रजी मध्ये)',
      middleNameEn: 'अर्जदाराचे मधले नाव (इंग्रजी मध्ये)',
      surnameEn: 'अर्जदाराचे शेवटचे नाव (इंग्रजी मध्ये)',
      firstNameMr: 'अर्जदाराचे पहिले नाव (मराठी मध्ये)',
      middleNameMr: 'अर्जदाराचे मधले नाव (मराठी मध्ये)',
      surnameMr: 'अर्जदाराचे शेवटचे नाव (मराठी मध्ये)',
      gender: 'लिंग',
      mobile: 'मोबाईल',
      panNo: 'पॅन नं',
      email: 'ईमेल पत्ता',
      aadharNo: 'आधार क्र.',
      serviceCompletionDate: 'सेवा पूर्ण होण्याची तारीख',
      isCurrentUser: 'लॉग इन केलेल्या वापरकर्त्याप्रमाणेच',
      personalDetails: 'वैयक्तिक माहिती',
      areaDetails: 'क्षेत्र तपशील',
      documentUpload: 'दस्तऐवज अपलोड',
      addFile: 'फाइल जोडा',
      fileName: 'फाईलचे नाव',
      mandatoryOrOptional: 'अनिवार्य/पर्यायी',
      mandatory: 'अनिवार्य',
      optional: 'पर्यायी',
      verify: 'सत्यापित',
      reject: 'नाकारा',
      noFileFound: 'कोणतीही फाइल आढळली नाही',
      verified: 'तपासून झाले',
      surveyNo: 'सर्वेक्षण क्र',
      gisLocation: 'GIS स्थान',
      flatNo: 'फ्लॅट/इमारत क्र',
      buildingName: 'इमारतीचे नाव',
      roadName: 'रस्त्याचे नाव',
      landmark: 'महत्त्वाची खूण',
      ctsNo: 'सीटीएस क्र.',
      plotNo: 'भूखंड क्र.',
      documentVerification: 'दस्तऐवज सत्यापन',
      legend: 'आख्यायिका',
      electoralWard: 'निवडणूक प्रभाग',
      landUnderPossession: 'ताब्यात असलेली जमीन',
      landNotUnderPossession: 'ताब्यात नसलेली जमीन',
      appropriateAuthority: 'समुचित प्राधिकरण',
      landReservationNo: 'जमिनीचे आरक्षण क्र',
      authorityNameEn: 'समुचित प्राधिकरणाचे इंग्रजीमध्ये नाव',
      authorityNameMr: 'समुचित प्राधिकरणाचे मराठीमध्ये नाव',
  
      upload: 'अपलोड करा',
      next: 'पुढे',
      preview: 'पूर्वावलोकन',
  
      attachFile: 'फाईल जोडा',
      srNo: 'अनु क्र',
      actions: 'क्रिया ',
  
      //Remarks
      selectDate: 'कृपया तारीख निवडा',
      selectTitle: 'कृपया शीर्षक निवडा',
      enterFName: 'कृपया पहिले नाव भरा ',
      enterMName: 'कृपया मधले  नाव भरा ',
      enterLName: 'कृपया शेवटचे नाव भरा ',
      enterCouncilName: 'कृपया वकिलांचे मंडळचे प्रमाणपत्र परिषदचे नाव भरा',
      enterArea: 'कृपया क्षेत्राचे नाव भरा ',
      enterRoadName: 'कृपया रस्त्याचे नाव भरा ',
      enterLandmark: 'कृपया  महत्त्वाची खूण भरा',
      enterCity: 'कृपया  शहराचे / गावाचे नाव भरा ',
      enterPinCode: 'कृपया पिनकोड भरा',
      enterPhoneNo: 'कृपया दूरध्वनी नं. भरा',
      enterMobileNo: 'कृपया मोबाईल नं. भरा',
      enterEmailAddress: 'कृपया इलेक्ट्रॉनिक संदेश भरा',
      enteraadhaarNo: 'कृपया आधार नं. भरा',
      enterpanNo: 'कृपया पॅन नं. भरा',
      // enterRemarks: 'कृपया टिप्पणी. भरा',
      enterRemarks: 'कृपया टिप्पणी. द्या',
  
      //buttons
      add: 'जोडा',
      save: 'जतन करा',
      update: 'अद्यायावत करा',
      clear: 'रिक्त',
      exit: 'बाहेर पडा',
      back: 'मागे',
      saveAndNext: 'जतन करा आणि पुढे',
      finish: 'समाप्त',

      petAnimals: 'पेट जानवर',
    },
  }
  