export default {
  en: {
    //multiple file attachment
    attachmentSchema: "*the maximum upload size is 2MB.",
    addDocuments: "Add Documents",
    fileUpload: "File Upload",
    attachment: "Attachement",

    slumDetails: "Slum Details",

    slumAddress: "Slum Owner's details",
    applicantInfo: "Applicant Information",
    additionalFields: "Additional Fields",
    outstandingTaxesAmount: "Outstanding Taxes Amount",
    waterTaxesAmount: "Water Taxes Amount",
    slumTaxesAmount: "Slum Taxes Amount",
    generateDocuments: "Generate Documents",
    selfDeclarationForm: "Self Declaration Form",
    selfAttestation: "Self-Declaration for Self-Attestation",
    completeSiteVisit: "Complete Site Visit",
    cancel: "Cancel",

    hutDetails: "Hut Details",

    //// Self Declaration ////////

    formA: "Form-A",
    declarationForm: "Self Declaration Form",
    applicantPhoto: "Applicant Photo",
    me: "I am",
    mr: "Mr.",
    sonOfAge: "of Son/Daughter, Age",

    /////// Reports

    casteWiseReport: "Caste Wise Report",
    slumName: "Slum Name",
    downloadEXCELL: "Download EXCELL",
    downloadPDF: "Download PDF",
    religion: "Religion",
    caste: "Caste",
    handicap: "Handicap",
    widow: "Widow",
    eligibleIneligibleCriteria: "Eligible/Ineligible Criteria",
    ownershipTypeWiseReport: "Ownership Type Wise Report",
    ownership: "Ownership",
    hutCount: "Hut Count",
    defaulterReport: "Defaulter Report",
    fromAmount: "From Amount",
    toAmount: "To Amount",
    previousAmount: "Previous Amount",
    currentAmount: "Current Amount",
    hutRegister: "Hut Register",
    signMobileNo: "Signature-Mobile No.",
    dayWiseCollectionRegister: "Day Wise Collection Register",
    bookAndRecieptNo: "Book And Reciept No",
    recieptDate: "Reciept Date",
    recoveredFromWhom: "Recovered From Whom",
    overAmount: "Over Amount",
    date: "Date",
    demandReport: "Demand Report",
    pimpri: "Pimpri 18",
    hutOccupierName: "Hut Occupier Name",
    eligible: "Eligible",
    inEligible: "Ineligible",
    hutWiseDetailReport: "Hut Wise Detail Report",
    photopassStatusReport: "Photopass Status Report",
    clerk: "Clerk",
    headClerk: "Head Clerk",
    officeSuperintendant: "Office Superintendant",
    administrativeOfficer: "Administrative Officer",
    assistantCommissioner: "Assistant Commissioner",
    serviceTaxReciept: "Service Tax Reciept",

    ////// Issuance of NOC

    issuanceOfNoc: "Issuance Of NOC",
    nocSiteDetails: "Site Visit Details",
    issuanceOfNocDetails: "Issuance Of NOC Details",
    issueNoc: "Issue NOC",
    purposeForNoc: "Purpose For NOC",
    purpose: "Purpose",
    purposeValidation: "Purpose For NOC is required !!",

    ////// Hut Bill Generation
    hutBillGeneration: "Hut Bill Generation",
    generatedHutBill: "Generated Hut Bill",

    ///// HUT Transfer

    hutTransfer: "Hut Transfer",
    searchHutDetails: "Search Hut Details",
    proposedOwner: "Proposed Owner",
    currentOwner: "Current Owner",
    transferType: "Transfer Type",
    marketValue: "Market Value",
    saleValue: "Sale Value",
    zoneName: "Zone",
    wardName: "Ward",
    hutOwnerDetails: "Hut Owner's Details",
    hutOccupiersDetails: "Hut Occupiers Details",
    hutAddressDetails: "Hut Address Details",
    transferDetails: "Transfer Details",
    generateRejectionLetter: "Generate Rejection Letter",
    details: "Details",
    subTransferType: "Sub Transfer Type",
    transferDate: "Transfer Date",
    viewExistingOwnerName: "View Existing Owner's Name",
    ownerName: "Owner Name",
    addName: "Add Name",
    siteVisitRemark: "Site Visit Remark",
    oldHutNo: "Old Hut No",
    hutArea: "Hut Area Sq.Ft.(Approximate)",
    slumArea: "Slum Area Sq.Ft.(Approximate)",
    close: "Close",
    currentOwnerTitle: "Current Owner Title",
    currentOwnerFirstName: "Current Owner First Name",
    currentOwnerMiddleName: "Current Owner Middle Name",
    currentOwnerLastName: "Current Owner Last Name",
    currentOwnerMobileNo: "Current Owner Mobile No",
    currentOwnerAadharNo: "Current Owner Aadhar No",
    newOwnerDetails: "New Owner Details",
    proposedOwnerTitle: "Title",
    proposedOwnerFirstName: "First Name",
    proposedOwnerFirstNameMr: "First Name(In Marathi)",
    proposedOwnerMiddleName: "Middle Name",
    proposedOwnerMiddleNameMr: "Middle Name(In Marathi)",
    proposedOwnerLastName: "Last Name",
    proposedOwnerLastNameMr: "Last Name(In Marathi)",
    proposedOwnerMobileNo: "Mobile No",
    proposedOwnerAadharNo: "Aadhar No",
    proposedOwnerEmailId: "Email Id",
    transferRemarks: "Transfer Remarks",
    view: "View",
    scheduleSiteVisitDetails: "Site Visit Details",
    transferHutSiteDetails: "Site Visit Details",
    familyMemberDetails: "Family Member Details",

    // SLUM Master
    slumPrefixEn: "Slum Prefix",
    slumPrefixMr: "Slum Prefix(In Marathi)",
    citySurveyNo: "City Survey No",
    surveyNo: "Survey No / Gat No",
    declarationDate: "Declaration Date",
    declarationOrderNo: "Declaration Order No",
    slumNameEn: "Slum Name(In English)",
    slumNameMr: "Slum Name(In Marathi)",
    areaName: "Area Name",
    areaOfSlum: "Area Of Slum",
    declarationOrder: "Declaration Order",
    noOfHuts: "No Of Huts",
    hutOccupiedArea: "Hut Occupied Area",
    population: "Total Population",
    malePopulation: "Male Population",
    femalePopulation: "Female Population",
    scPopulation: "SC Population",
    stPopulation: "ST Population",
    slumBoundaryInfo: "Slum Boundary Info",
    slumStatus: "Slum Status",

    hutMaster: "Hut Master",
    hutMember: "Hut Member",
    age: "Age",
    genderKey: "Gender",
    religionKey: "Religion",
    religionKeyValidation: "Religion is required",
    castCategory: "Caste Category",
    castCategoryValidation: "Caste Category is required !!!",
    casteKey: "Caste",
    casteKeyValidation: "Caste is required !!!",
    subCasteKey: "Sub Caste",
    educationKey: "Education",
    educationKeyValidation: "Education is required",
    headOfFamily: "Head of Family",
    collection: "Collection",
    trnCollectionDate: "Transaction Date",
    serviceName: "Service Name",
    receiptNo: "Receipt No",
    collectionCenter: "Collection Center",
    counter: "Counter",
    moduleName: "Module Name",
    userName: "User Name(SAP/NonCore/GIS)",
    receiptType: "Receipt Type",
    refernece: "Reference",
    referenceDate: "Reference Date",
    payerName: "Payer Name",
    address: "Address",
    narration: "Narration",
    paymentMode: "Payment Mode",
    accoundCode: "Account Code",
    codeDescription: "Code Description",
    amount: "Amount",
    totalAmount: "Total Amount",
    receivedAmount: "Received Amount",
    paymentModeKey: "Payment Mode",
    paymentAmount: "Payment Amount",
    transactionStatus: "Transaction Status",
    year: "Year",
    financialYear: "Financial Year",
    viewBill: "View Bill",
    bill: "Bill",
    completeAndIssueOrder: "Complete And Issue Order",

    genderKeyValidation: "Gender is Required",

    ownershipTypePrefix: "Ownership Type Prefix",
    fromDate: "From Date",
    toDate: "To Date",
    ownershipType: "Ownership Type",
    ownershipTypeMr: "Ownership Type(मराठी)",
    btnSaveText: "Save",
    remarks: "Remark",

    constructionTypePrefix: "Construction Type Prefix",
    constructionType: "Construction Type",
    constructionTypeMr: "Construction Type(मराठी)",

    usageTypePrefix: "Usage Type Prefix",
    usageType: "Usage Type",
    usageTypeMr: "Usage Type (मराठी)",

    subUsageTypePrefix: "Sub Usage Type Prefix",
    subUsageType: "Sub Usage Type",
    subUsageTypeMr: "Sub Usage Type (मराठी)",

    factorPrefix: "Factor Prefix",
    factorName: "Factor name",
    factorNameMr: "Factor name (मराठी)",
    applicableOn: "Applicable On",

    setFor: "Set for",
    flagName: "Flag name",
    flagNameMr: "Flag name (मराठी)",

    billingCyclePrefix: "Billing Cycle Prefix",
    billingCycle: "Billing Cycle",
    billingCycleMr: "Billing Cycle (मराठी)",

    ageSlabPrefix: "Age Slab Prefix",
    ageSlabName: "Age Slab",
    ageSlabNameMr: "Age Slab (मराठी)",
    rangeOfAge: "Range of Age",

    educationCategoryPrefix: "Education Category Prefix",

    educationCategory: "Education Category",
    educationCategoryMr: "Education Category (मराठी)",
    stream: "Stream",
    std: "Std",
    constructionTypeKey: "Construction Type",
    usageTypeKey: "Usage Type ",
    usageSubTypeKey: "Usage Sub Type",
    length: "Length",
    breadth: "Breadth",
    height: "Height(Approximate)",

    partNoInList: "Part No. in List ",
    module: "Marriage Registration",
    // dashboard: 'PCMC Dashboard',
    dashboard: "Pimpri-Chinchwad Municipal Corporation Dashboard",
    masters: "Masters",
    transactions: "Transactions",
    reports: "Reports",
    receipt: "Receipts",
    usertask: "User task",
    serviceName: "Service Name ",
    masters: "Masters",
    masterPath: "FIRE BRIGADE SYSTEM / masters",
    demo: "",
    //mr
    MrMasters: "Marriage Registration / Masters",
    marriageRegistrationMaritalStatus:
      "Marriage Registration / Masters / Marital Status",

    pay: "PAY",
    marriageRegistrationrelation: "Marriage Registration / Masters / relation",
    receiptModeDetails: "Receipt Mode Details",
    maritialSatus: "Marital Status",

    AptBook: "Appointment Slot Booking",
    serviceChargeTypeName: "Service Charge Type Name",

    // field label
    srNo: "Sr. No",
    actions: "Actions",
    statusDetails: "Status Details",

    //buttons
    add: "Add",
    save: "Save",
    update: "Update",
    clear: "Clear",
    exit: "Exit",
    Revert: "Revert Back",
    scheduleSiteVisit: "Schedule Site Visit",
    reScheduleSiteVisit: "Reschedule Site Visit",
    print: "Print",

    ward: "Ward",
    zone: "Zone",
    latitude: "Latitude",
    Longitude: "Longitude",
    LongitudeReq: "Longitude is Required",
    latitudeReq: "Latitude is Required",

    documentUpload: "Documents Upload",
    applicationCreated: "Application Submitted Successfully",
    addFile: "Choose File",
    fileName: "File Name",
    mandatoryOrOptional: "Mandatory/Optional",
    mandatory: "Mandatory",
    optional: "Optional",
    upload: "Upload",
    next: "Next",
    preview: "Preview",
    _preview: "Preview",
    verify: "Verify",
    reject: "Reject",
    noFileFound: "No file found",
    verified: "Verified",
    agreeAndProceed: "I Agree And Proceed",

    attachFile: "Attach File",
    rquiredAttachFile: "Required Attach File",
    srNo: "Sr. No",

    //breadcrum
    landReservationPath: "Town Planning / Master / Land Reservation ",

    attachFile: "Attach File",
    srNo: "Sr. No",
    actions: "Actions",

    //buttons
    add: "Add",
    save: "Save",
    update: "Update",
    clear: "Clear",
    exit: "Exit",
    back: "Back",
    saveAndNext: "Save & Next",
    finish: "Finish",
    download: "Download",
    downloadPhotopass: "Download Photopass",

    //marathi details
    gFNameMr: "",
    gMNameMr: "",
    gLNameMr: "",
    ApplicatCheck1: "If the Applicant is Groom",
    ApplicatCheck2: "If the Applicant is Bride",
    OwnerChkeck: "If the Applicant is Owner",
    transactions: "Transactions",
    transactionPath: "Legal Case / Transaction ",

    //mr
    Tnc: "accept term & Condition",
    // instrustion
    onlyMHR:
      " Marriages are registered in Maharashtra and either the bride or the groom must be a resident of Pimpri Chinchwad Municipal Corporation limits.",
    docNote:
      "Id proof, Residential proof, Age proof should be different, (Previous Status Proof contain value if Status at the time of marriage is Widow/Widower or Divorce) If Aadhaar card proof is added and citizen A registered agreement is required if living on rent.",
    //table
    newMRtable: "NEW MARRIAGE REGISTRATION ",
    boardtitle: "  Marriage Board Registration ",
    zone: "Zone",
    ward: "Ward",
    Addrees: "Applicant Address :",
    CrrtAdree: "Current Address :",
    parmtAdree: "Permanent Address :",
    personalDetails: "Personal Information :",
    Adress: "Address  :",
    BriNBM: "  (  Name are before marriage)",
    AppliToGroom: "If the Applicant is Groom ",
    AppliToBride: "If the Applicant is Bride",
    marrigeDetails: "  Marriage Details :",
    marrigeDate: "Marriage Date",
    //aprove
    GPhoto: "Groom Photo  ",
    Bphoto: "Bride Photo  ",
    witnessphto1: "Witness 1 Photo  ",
    witnessphto2: "Witness 2 Photo  ",
    witnessphto3: "Witness 3 Photo  ",
    Gthumb: "Groom Thumb  ",
    Bthumb: "Bride Thumb  ",
    witnessthumb1: "Witness 1 Thumb  ",
    witnessthumb2: "Witness 2 Thumb  ",
    witnessthumb3: "Witness 3 Thumb  ",

    //title
    ApplicatDetails: "APPLICANT DETAILS",
    ApplicatName: "Applicant Name",
    groomDetail: "GROOM DETAILS",
    groomParaentDetail: "Groom Parents Details ",
    brideDetails: "BRIDE DETAILS",
    brideParaentDetail: "Bride Parents Details",
    priestDetails: "PRIEST DETAILS",
    witness: "Witness",
    witnessAdd: "Witness",
    witnessDetails: "WITNESS DETAILS",
    documentsUpload: "DOCUMENT UPLOAD",
    boardDetail: "Board Details :",
    otherDetail: "OTHER DETAILS",
    titleInmarathi: "Title In Marathi",
    titleInenglish: "Title In english",

    // viceversa
    titleV: "शीर्षक",
    firstNameV: "प्रथम नावं  ",
    middleNameV: "मधले नावं  ",
    lastNameV: "आडनाव  ",

    //Groom
    // title: 'Title  ',
    firstName: "First Name  ",
    middleName: "Middle Name  ",
    lastName: "Last Name  ",
    title: "Title ",
    title1: "Title ",
    firstNameEn: "First Name (In English) ",
    middleNameEn: "Middle Name (In English) ",
    lastNameEn: "Last Name (In English) ",
    titlemr: "शीर्षक ",
    firstNamemr: "First Name (In Marathi) ",
    middleNamemr: "Middle Name (In Marathi) ",
    lastNamemr: "Last Name (In Marathi) ",

    BirthDate: "Birth Date   ",
    Gender: "Gender",
    AadharNo: "Aadhar No",
    Age: "Age (at the time of marriage)",
    mobileNo: "Mobile / Phone Number",
    phoneNo: "Phone Number",
    email: "Email",

    flatBuildingNo: "Flat/Building No (In English)  ",
    buildingName: "Apartment Name (In English) ",
    roadName: "Road Name (In English) ",
    Landmark: "Landmark (In English) ",
    villageName: "Village Name ",
    villageNameValidation: "Select at least one village",
    zoneNameValidation: "Select at least one zone",
    wardNameValidation: "Select at least one ward",
    clusterNameValidation: "Select at least one cluster",
    cityName: "City Name / Village Name (In English) ",

    flatBuildingNomr: "Flat/Building No (In Marathi) ",
    buildingNamemr: "Apartment Name (In Marathi) ",
    roadNamemr: "Road Name (In Marathi) ",
    Landmarkmr: "Landmark (In Marathi) ",
    villageNamemr: "Village Name (In Marathi) ",
    cityNamemr: "City Name / Village Name (In Marathi) ",

    State: "State (In English) ",
    statemr: "State (In Marathi) ",
    pincode: "Pin Code",
    Religion1: "Religion by Birth",
    Religion2: " Religion by Adoption",
    StatusOfMarrige: " Status at time of marriage",
    AgeDocument: "Birth Proof Document",
    IdDocument: "Id Document",
    residentialDocument: "Residential Document",
    StatusOfDocument: "Status Of Document",

    //witness
    address: "Address",

    //Document

    DBProof: "Date of Birth Proof",
    ResProof: "Residence Proof",
    IdProof: "ID Proof",

    ResProofW1: "Residence Proof of first witness",
    ResProofW2: "Residence Proof of second witness",
    ResProofW3: "Residence Proof of third witness",
    marrigeRelatedDoc: "Marriage Related Document",
    invetaionCard: "Marriage Invitation card / affidavit ",
    marrigePhotoC: "Marriage Photograph (Couple) ",
    marDrf: "Draft an application on the 100 Rs Stamp paper",
    DivorcePaper: "Valid Divorce Paper (if applicable)",
    DeathC: "Death Certificate (if applicable)",
    certiByReligiousPlc:
      " Certificate issued by religious place i.e Temple, Mosque etc",
    docFormat:
      " (Only jpg.jpeg.png.bmp.pdf files are allowed to upload. Photo Size max 100 kb)",
    enterDoc: "Document Name",
    TandC: "",
    //board
    applicantName: "Applicant Name",
    boardNameT: "Marriage Board Name",
    boardName: "Marriage Board Name (In English)  ",
    boardNamemr: "Marriage Board Name (In Marathi)  ",
    remark: "Remarks",
    documentList: " Documents List",
    ValidtyofMBR: "  Validity Of MBR",
    documentsUploadF: "Documents Upload",

    //button
    back: "Back",
    next: "Next",
    add: "Add",
    save: "Save",
    update: "Update",
    clear: "Clear",
    exit: "Exit",
    submit: "Submit",
    apply: "Apply",
    addFile: "Upload File",

    //table filed
    srNo: "Sr. No",
    hName: "Groom Name",
    wName: "Bride Name",
    actions: "Actions",

    //brudcrum
    newMarriageRegistration:
      "Marriage Registration / New Marriage Registration",
    BoardMarriageRegistration: "Marriage Registration / New Board Registration",

    //ReIssuance of Marriage Certificate

    onlyRIMC: "Re-Issuance of Marriage Certificate",
    mRegNo: "Marriage Reg No",
    marriageDate: "Marriage Date",
    marriageYear: "Marriage Year",
    brideName: "Bride Name",
    groomName: "Groom Name",
    regDate: "Registration Date",

    //Renewal of Marriage Board Registration
    onlyRMBR: "Renewal of Marriage Board Registration",
    mbrName: "Marriage Board Name",
    mbrDate: "Marriage Board Reg Date",
    mbrYear: "Marriage Board Reg Year",
    search: "Search",

    //Application Details

    onlyApplDetail: "Application Details",
    applFName: "Applicant First Name",
    applMName: "Applicant Middle Name",
    applLName: "Applicant Last Name",
    groomFName: "Groom First Name",
    groomMName: "Groom Middle Name",
    groomLName: "Groom Last Name",
    brideFName: "Bride First Name",
    brideMName: "Bride Middle Name",
    brideLName: "Bride Last Name",
    mDate: "Marriage Date",

    //ReIssuance of marriage Certificate
    newRMItable: "ReIssuance of Marriage Certificate",
    applFullName: "Applicant Full Name",
    applicationNo: "Application Number",
    generateLoi: "Generate LOI",

    //Modification in Marriage Board Registration

    onlyMMBR: "Modification in Marriage Board Registration",
    applicationDate: "Application Date",
    registerationDate: "Registeration Date",
    registerationNo: "Registeration No",
    orgName: "Organisation Name",

    //Payment Collection
    bankName: "Bank Name",
    branchName: "Branch Name",
    ifsc: "IFSC Code",
    accountNumber: "Account Number ",
    pay: "Pay",
    exit: "Exit",

    //validation
    selectWard: "Please select a ward",
    selectDate: "Please select a date",
    selectTitle: "Please select a title",

    enterFName: "Please enter first name (In English)",
    enterMName: "Please enter middle name (In English)",
    enterLName: "Please enter last name (In English)",

    enterFNameMr: "Please enter first name (In Marathi) ",
    enterMNameMr: "Please enter middle name (In Marathi)",
    enterLNameMr: "Please enter last name (In Marathi)",

    enterFlat: "Please enter Flat/Building No (In English) ",
    enterApartment: "Please enter Apartment Name (In English)",
    enterRoadName: "Please enter Road Name (In English)",
    enterLandmark: "Please enter Landmark (In English)",
    enterCity: "Please enter a City Name / Village Name (In English) ",
    state: "Please enter State (In English)",

    enterFlatMr: "Please enter Flat/Building No (In Marathi)",
    enterApartmentMr: "Please enter Apartment Name (In Marathi)",
    enterRoadNameMr: "Please enter Road Name (In Marathi)",
    enterLandmarkMr: "Please enter Landmark (In Marathi)",
    enterCityMr: "Please enter a City Name / Village Name (In Marathi)",
    stateMr: "Please enter State (In Marathi)",

    enterPinCode: "Please enter a pincode ",
    enterPhoneNo: "Please enter a phone no. ",
    enterMobileNo: "Please enter a mobile no. ",
    enterEmailAddress: "Please enter an e-mail. ",
    enteraadhaarNo: "Please enter an aadhaar no. ",
    enterpanNo: "Please enter an pan no. ",
    enterRemarks: "Please enter a remark. ",
    enterAge: "Please enter a Age. ",
    selectGender: "Please select a Gender ",
    selectReligionby: "Please select a Religion by Birth",
    selectAdoptionby: "Please select a Religion by Adoption",
    selectStatusAt: "Please select a Status at time of marriage",

    //mr
    selectZone: "Please select a zone",
    selectWard: "Please select a ward",
    selectZone: "Please select a Zone",
    selectTitle: "Please select a Title",
    placeMarriage: "Please enter Place of Marriage (in English)",
    placeMarriageMr: "Please enter Place of Marriage (in Marathi)",
    birthProf: "Please select a Date of Birth Proof",
    ResideProof: "Please select a Residence Proof",
    IdentyProof: "Please select a ID Proof",
    witnessAddressC: "Please enter an Address ",
    witnessRelation: "Please enter an Relation. ",

    EnterDocName: "Please enter an Document Name ",

    noOfCopies: "No of Copies",
    charges: "Total Charges",
    chargeName: "Charge Name",
    amount: "Amount",
    totalInWords: "Total Charges in Words",
    totalCharges: "Total Charges",
    applicantDetails: "Applicant Details",
    chargesDetails: "Charges Details",
    payment: "Payment",
    paymentMode: "Payment Mode",
    paymentType: "Payment Type",
    receiptDate: "Receipt Date",
    receiptNumber: "Receipt Number",
    receiptAmount: "Receipt Amount",
    ddNo: "Demand Draft Number",
    ddDate: "Demand Draft Date",
    bankName: "Bank Name",
    branchName: "Branch Name",
    bankAccountNo: "Bank Account No",

    //Modification in Marriage Certificate

    onlyMIMC: "Modification of Marriage Certificate",
    oldLabel: "Old Information",
    newLabel: "New Information",
    gDoc: "Groom Documents",
    bDoc: "Bride Documents",
    OwnerDetails: " Owner Details :",
    Owneraddress: " Owner Address :",
    document: "Document Tab :",
    boardheadphoto: "Board Head Person Photo",
    boardorgphotocpy: "Board / Organization PhotoCopy",
    panCard: "Pan Card",
    adharcard: "Aadhaar card",
    rationcard: "Ration card",
    electrbill: "Electric Bill",
    OtherDocument: "Other Document",
    UploadFile: " Upload File",
    remarkModel: "Enter Remark on application",
    APPROVE: "Approve",
    photo: "Photo",
    husbandWifePhoto: "Upload Husband Wife Combined Photo",

    REASSIGN: "REASSIGN",
    onlyeng: "Must be only characters",
    onlymarathi: "Must be only  marathi",

    module: "Legal Case Management System",
    formType: "masters",
    master: "Masters",
    transaction: "Transactions",
    report: "Reports",

    masterPath: "Legal Case / Master ",
    transactionPath: "Legal Case / Transaction ",

    courtPath: "Legal Case / Master /Court",
    advocatePath: "Legal Case / Master /Advocate",
    serviceHierachyPath: "Legal Case / Master / Service Hierachy",
    caseTypePath: "Legal Case/ Master / Case Type",
    caseSubTypePath: "Legal Case / Master / Case Sub Type",
    caseStagesPath: "Legal Case/ Master / Case Type",
    employeeAndUserCreationPath:
      "Legal Case / Master / Employee and User Creation",
    counterSchedulingPath: "Legal Case / Master / Counter Scheduling",
    smsEmailWhatsAppTemplatesPath:
      "Legal Case / Master / SMS / Email/WhatsApp Templates",
    userAuthenticationAndRoleRightsPath:
      "Legal Case / Master / User Authentication and Role-Rights",
    changeResetForgetPasswordPath:
      "Legal Case / Master / Change or Reset or ForgetPassword",
    calendarSchedulingPath: "Legal Case / Master / Calendar Scheduling",

    //label title
    court: "Court",
    advocate: "Advocate",
    serviceHierachy: "Service Hierarchy",
    caseType: "Case type",
    caseSubType: "Case Sub-Type",
    caseStages: "Case-Stage",
    employeeAndUserCreation: "Employee and User Creation",
    counterScheduling: " Counter Scheduling",
    smsEmailWhatsAppTemplates: " SMS / E-mail / Whatsapp Template",
    userAuthenticationAndRoleRights: " User Authentication and Role Rights",
    changeResetForgetPassword: "Change / Reset / Forget Password",
    calendarScheduling: " Calender Scheduling",
    spouseDetails: "Spouse Details",

    //other labels
    other: "Other",
    complaintType: "Subject/Complaint Type *",
    complaintSubType: "Complaint Sub Type *",
    status: "Status ",
    mediaName: "Media Name *",
    mediaPrefix: "Prefix *",
    remark: "Remark",
    eventType: "Event Type",
    eventDate: "Event Date *",
    alertDateTime: "Alert Date & Time *",
    description: "Description",
    courtName: "Court Name *",
    address: "Address ",
    roadName: "Road Name *",
    landmark: "Landmark *",
    cityOrVillage: "City / Village *",
    pincode: "Pincode *",
    area: "Area *",
    name: "Name *",
    mobile: "Mobile No. *",
    phone: "Phone No. *",
    email: "E-mail",
    occupation: "Occupation",
    relation: "Relation With Head Of Family",
    aadharNo: "Aadhar No.",
    panNo: "Pan No.",
    advocateCreation: "Advocate Created Successfully",
    advocateDetails: "Advocate Details",
    bankDetails: "Bank Details",
    documentUpload: "Document Upload",
    title: "Title *",
    fname: "First Name *",
    mname: "Middle Name *",
    lname: "Last Name *",
    advocateCategory: "Advocate Category *",
    nameOfBarCouncil: "Name Of Bar Council *",
    remarks: "Remarks *",
    bankName: "Bank Name *",
    branchName: "Branch Name *",
    accountNo: "Account No. *",
    bankIFSC: "Bank IFSC code *",
    bankMICR: "Bank MICR code *",
    application: "Application:",
    aadharCard: "Aadhar Card:",
    panCard: "Pan Card:",
    barCouncilCertificate: "Bar Council Certificate:",
    bankPassbook: "Bank Passbook:",

    //Remarks
    selectDate: "Please select a date",
    selectTitle: "Please select a title",
    enterFName: "Please enter first name ",
    enterMName: "Please enter middle name ",
    enterLName: "Please enter last name ",
    selectAdvocateCategory: "Please select a category",
    enterCouncilName: "Please enter council name",
    enterArea: "Please enter area ",
    enterRoadName: "Please enter road name ",
    enterLandmark: "Please enter a landmark ",
    enterCity: "Please enter a city ",
    enterPinCode: "Please enter a pincode ",
    enterPhoneNo: "Please enter a phone no. ",
    enterMobileNo: "Please enter a mobile no. ",
    enterEmailAddress: "Please enter an e-mail. ",
    enteraadhaarNo: "Please enter an aadhaar no. ",
    enterpanNo: "Please enter an pan no. ",
    enterRemarks: "Please enter a remark. ",

    attachFile: "Attach File",
    srNo: "Sr. No",
    actions: "Actions",

    //buttons
    add: "Add",
    save: "Save",
    update: "Update",
    clear: "Clear",
    exit: "Exit",
    back: "Back",
    saveAndNext: "Save & Next",
    finish: "Finish",

    hutPrefix: "Hut Prefix",
    zoneKey: "Zone Name",
    hutNo: "Hut No",
    slumKey: "Slum",
    areaOfHut: "Area of Hut in Sq.Ft.(Approximate)",
    ownershipKey: "Ownership",

    rehabilitation: "Rehabilitation",
    eligibility: "Eligibility",
    waterConnection: "Water Connection",
    noOfFloors: "Total No. of Floors (G+)",
    maleCount: "Male Count ",
    femaleCount: "Female Count",
    totalFamilyMembers: "Total Family Members",
    areaKey: "Area Name",
    villageKey: "Village Name",
    cityKey: "City Name",
    pincode: "Pincode",
    lattitude: "Lattitude",
    longitude: "Longitude",
    assemblyConstituency: "Name of Assembly constituency",
    correction: "Correction",
    remarks: "Remark",
    applicationNo: "Application No",
    applicationDate: "Application Date",
    hutNo: "Hut No.",
    firstName: "First Name",
    middleName: "Middle Name",
    lastName: "Last Name",
    photo: "Upload Photo",
    mobileNo: "Mobile No.",
    aadharNo: "Aadhar No.",
    emailId: "Email ID",
    slumName: "Slum Name",
    area: "Area",
    village: "Village",
    city: "City",
    pincode: "Pincode",
    lattitude: "Lattitude",
    longitude: "Longitude",
    title: "Title",
    noOfCopies: "No. of Copies",
    asOnDate: "As on Date",
    feesApplicable: "Fees Applicable",
    details: "Details",
    outstandingTaxesAmount: "Outstanding Taxes Amount",
    addApplicant: "Add Applicant",
    fullName: "Full Name",

    save: "Save",
    clear: "Clear",
    exit: "Exit",
    search: "Search",

    srNo: "Sr No.",
    action: "Actions",

    // issuance of photopass

    searchSlumDetails: "Search Hut Details",
    hutNo: "Hut Number",
    insuranceOfPhotopass: "Issuance Of Photopass",
    noOfCopies: "No Of Copies",
    scheduleDateTime: "Schedule Date-Time",
    rescheduleDateTime: "Reschedule Date-Time",
    visitDateTime: "Visit Date-Time",
    back: "Back",
    photopassSiteDetails: "Site Visit Details",
    fileUploadValidationError: "You can add only 5 Images",
    geocode: "Geo Code",
    attachImages: "Attach Images",
    attachInspectionImages: "Attach Inspection Reports",
    uploadSiteVisitImages: "Upload site visit images",
    generateInspectionReport: "Generate Inspection Report",
    generatedInspectionReport: "Generated Inspection Report",
    viewPhoto: "View Photo",
    generate: "Generate",
    remarks: "Remark",
    Complete: "Complete",
    issuePhotopass: "Issue Photopass",
    loiDetails: "LOI Payment Details",
    transactionDateTime: "Transaction Date-Time",
    inssuranceOfPhotopassDetails: "Issuance Of Photopass Details",
    generateReports: "Generate Reports",
    clerkApprovalRemark: "Clerk Remark",
    headClerkApprovalRemark: "Head Clerk Remark",
    officeSuperintendantApprovalRemark: "Office Superintendant Remark",
    administrativeOfficerApprovalRemark: "Administrative Officer Remark",
    assistantCommissionerApprovalRemark: "Assistant Commissioner Remark",

    //acknowledgement
    pimpariChinchwadMaha: "Pimpri Chinchwad Municipal Corporation",
    appAcknowldgement: "Application Acknowledgement",
    ackDear: "Dear",
    ackpcmcthanku:
      "Thank you for using PCMC Pimpri Chinchwad Citizen Service Portal !!",
    ackshortDesc:
      "Your application for Issuance of Photopass under PCMC has been successfully submitted.",
    ackHutTransferShortDesc:
      "Your application for Hut Transfer under PCMC has been successfully submitted.",

    ackApplicationSummery: "Application Summary",
    applicationNo: "Application No",
    dateofApplication: "Date of the Application",
    ackplzContactNearestOperator:
      "For any query please contact your nearest operator or the following contact details:",
    ackpcmcAddress: "Mumbai Pune Highway Pimpri Pune 411 018",
    ackPcmcphNo: "Phone Number:91-020-2742-5511/12/13/14",
    ackstateCountry: "Maharashtra, India",
    applicantAddress: "Applicant Address",
    other: "Other",
    no1: "1)",
    no2: "2)",
    chargeNm: "Charge Name",
    loiNo: "LOI NO",
    photopassApplicationAmt:
      "For your Issuance of Photopass on Citizen Seva Portal please your amount Rs",
    hutTransferAmt:
      "For your Transfer of Hut on Citizen Seva Portal please your amount Rs",
    determineandPayAmt:
      "Determine and pay the amount/charge for the service rendered.",
    contactNearestpcmcDivisionalOffice:
      "Or visit the nearest Pimpri Chinchwad Municipal Corporation Divisional Office.",
    serviceAcceptance: "Service Acceptance Letter",
    isApplicationMultiDept: "Is it application under multi department?",
    addDepartment: "Add Department",
    parentRemark: "Parent Remark",
    forwardRemark: "Forward Remark",
    applicationType: "Application Type",
    departmentKey: "Department",
    nocApplicationAmt:
      "For your Issuance of NOC on Citizen Seva Portal please your amount Rs",
    saveAsDraft: "Save As Draft",
    hutTransferDetails: "Hut Transfer Details",
    currentStatus: "Current Status",
    helpDeskOfSlum: "Help Desk Of Slum",
    applicationName: "Application Name",
    fileNm: "File Name",
    fileType: "File Type",
    saveAsDraft: "Saved as a draft",
    revertByClerk: "Revert by Clerk",

    waitingForSiteVisit: "Waiting for Site Visit",
    revertByHeadClerk: "Revert by Head Clerk",
    photoPassWaitForClerk: "Photopass Waiting for Clerk",
    waitForClerk: "Waiting For Head Clerk",
    revertBySuperintendant: "Revert by Office-Superintendant",
    waitForSuperintendant: "Waiting for Office-Superintendant",
    revertByAdminOfficer: "Revert By Administrative-Officer",
    waitForAdminOfficer: "Waiting for Administrative-Officer",
    revertForAssComm: "Revert by Assistant-Commissioner",
    waitForAssComm: "Waiting for Assistant-Commissioner",
    sendForAssComm: "send back to assistant commissioner",
    loiGenerated: "LOI Generated",
    paymentDone: "Payment Done",
    siteVisitSch: "Site Visit Scheduled",
    siteVisitDone: "Site Visit Done",
    photopassIssued: "Photopass Issued",
    statusClose: "Close",
    statusDuplicate: "Duplicate",
    statusRejected: "Rejected",
    sendBackToCitizenAfterVisit: "Send back to citizen after Site Visit",
    sendToClerkAfterVisit: "Send to Clerk after Site Visit",
    sendToClerkAfterLoiPay: "Send to Clerk after LOI Payment",
    gisId: "Gis Id",
    gisIdReq: "Gis Id is required",
    // /////////////////////////////// Shubham add by error translation msg /////////////////////////////
    slumFromDate: "From Date is Required !!!",
    slumToDate: "To Date is Required !!!",
    declarationDateValidation: "DeclarationDate is Required !!!",

    ageSlabValidation: "Age Slab is Required",
    ageSlabPrefixValidation: "Age Slab Prefix is Required",
    ageSlabNameValidation: "Age Slab Name is Required",
    ageSlabNameMrValidation: "Age Slab Marathi Name is Required",
    rangeOfAgeValidation: "Range of Age is Required",

    ageSlabNameReqLength: "Age slab name should not exceed 50 characters",
    ageSlabNameMrLength:
      "Age slab name (Marathi) should not exceed 100 characters",

    ageSlabPrefixLength: "Age slab prefix should not exceed 15 characters",

    billingCyclePrefixValidation: "Billing cycle prefix is Required ",
    billingCyclePrefixLength:
      "Billing cycle prefix should not exceed 15 characters",
    billingCycleValidation: "Billing cycle is Required",
    billingCycleReqLength: "Billing cycle should not exceed 50 characters",
    billingCycleMrValidation: "Billing cycle (Marathi) is Required",
    billingCycleMrLength:
      "Billing cycle (Marathi) should not exceed 100 characters",

    constructionTypePrefixValidation: "Construction type prefix is Required ",
    constructionTypePrefixLength:
      "Construction type prefix should not exceed 15 characters",
    constructionTypeValidation: "Construction type is Required",
    constructionTypeReqLength:
      "Construction type should not exceed 50 characters",
    constructionTypeMrValidation: "Construction type (Marathi) is Required",
    constructionTypeMrLength:
      "Construction type (Marathi) should not exceed 100 characters",

    educationCategoryPrefixValidation: "education category prefix is Required ",
    educationCategoryPrefixLength:
      "education category prefix should not exceed 15 characters",
    educationCategoryValidation: "education category is Required",
    educationCategoryReqLength:
      "education category should not exceed 50 characters",
    educationCategoryMrValidation: "education category (Marathi) is Required",
    educationCategoryMrLength:
      "education category (Marathi) should not exceed 100 characters",

    streamValidation: "Stream is required",
    stdValidation: "std is required",

    factorPrefixValidation: "Factor prefix is Required ",
    factorPrefixLength: "Factor prefix should not exceed 15 characters",
    factorNameValidation: "Factor is Required",
    factorNameReqLength: "Factor should not exceed 50 characters",
    factorNameMrValidation: "Factor (Marathi) is Required",
    factorNameMrLength: "Factor (Marathi) should not exceed 100 characters",
    applicableOnValidation: "Applicable On is Required",

    setForValidation: "Set for is Required",
    setForReqLength: "Set for should not exceed 50 characters",
    flagNameValidation: "Flag Name is Required",
    flagNameReqLength: "Flag Name should not exceed 50 characters",
    flagNameMrLength: "Flag Name (Marathi) should not exceed 100 characters",
    flagNameMrValidation: "Flag Name (Marathi) is Required",

    zoneKeyValidation: "Zone Name is Required !!!",
    clusterKeyValidation: "Cluster Name is Required",
    hutPrefixValidation: "Hut prefix is Required ",
    hutPrefixLength: "Hut prefix should not exceed 15 characters",
    wardKeyValidation: "Ward Name is Required",
    hutNoValidation: " Hut no. is Required !!!",
    slumKeyValidation: "Slum is Required !!!",
    areaOfHutValidation: "Area of hut is Required !!!",
    ownershipKeyValidation: "Ownership is Required !!!",
    constructionTypeKeyValidation: "Construction type is Required !!!",
    usageTypeKeyValidation: "Usage type is Required !!!",
    usageSubTypeKeyValidation: "is Required !!!",
    lengthValidation: " Length is Required !!!",
    breadthValidation: "Breadth is Required !!!",
    heightValidation: "Height is Required !!!",
    partNoInListValidation: "Part no in list is Required !!!",
    noOfFloorsValidation: "No of floors is Required !!!",
    maleCountValidation: "Male count is Required !!!",
    femaleCountValidation: "Female count is Required !!!",
    totalFamilyMembersValidation: "Total Family Member is Required !!!",
    areaKeyValidation: "Area is Required !!!",
    villageKeyValidation: "Village is Required !!!",
    cityKeyValidation: "City is Required !!!",
    pinCodeValidtion: "  Pincode is Required !!!",
    pinCodeValidtionLength: "Pincode should not exceed 6 characters",
    pinCodeValidtionMinLength: "Pincode must be 6 characters",
    assemblyConstituencyValidation: "Assembly constituencyis Required !!!",
    correctionValidation: "Correction is Required !!!",

    ownershipTypePrefixValidation: "Ownership type prefix is Required ",
    ownershipTypePrefixLength:
      "Ownership type prefix should not exceed 15 characters",
    ownershipTypeValidation: "Ownership type is Required",
    ownershipTypeReqLength: "Ownership type should not exceed 50 characters",
    ownershipTypeMrValidation: "Ownership type (Marathi) is Required",
    ownershipTypeMrLength:
      "Ownership type (Marathi) should not exceed 100 characters",

    slumPrefixValidation: "Slum prefix is Required !!!",
    slumPrefixLength: "Slum prefix should not exceed 15 characters",
    slumNameValidation: "Slum Name is Required !!!",
    slumNameReqLength: "Slum Name should not exceed 50 characters",
    slumNameMrValidation: "Slum Name (Marathi) is Required !!! ",
    slumNameMrLength: "Slum Name (Marathi) should not exceed 100 characters",
    areaOfSlumValidation: "Area of slum is Required !!!",
    declarationOrderValidation: "Declaration order is Required !!!",
    noOfHutsValidation: "No of huts is Required !!!",
    hutOccupiedAreaValidation: "Hut occupied area is Required !!!",
    totalPopulationValidation: "Total population is Required !!!",
    malePopulationValidation: "Male population is Required !!!",
    femalePopulationValidation: "Female population is Required !!!",
    scPopulationValidation: "SC population is Required !!!",
    stPopulationValidation: "ST population is Required !!!",
    otherPopulationValidation: "Other population is Required !!!",

    slumBoundaryInfoValidation: "Slum boundary information is Required !!!",
    slumStatusValidation: "Slum status is Required !!!",
    citySurveyNoValidation: "City survey number is Required !!!",
    citySurveyNoValidation: "City survey number is Required !!!",
    surveyNoValidation: "Survey number is Required !!!",
    surveyNoValidation: "Survey number is Required !!!",
    declarationOrderNoValidation: "Declaration order number is Required !!!",

    subUsageTypePrefixValidation: "Sub usage type prefix is Required ",
    subUsageTypePrefixLength:
      "Sub usage type prefix should not exceed 15 characters",
    subUsageTypeValidation: "Sub usage type is Required",
    subUsageTypeReqLength: "Sub usage type should not exceed 50 characters",
    subUsageTypeMrValidation: "Sub usage type (Marathi) is Required",
    subUsageTypeMrLength:
      "Sub usage type (Marathi) should not exceed 100 characters",

    usageTypePrefixValidation: "Usage type prefix is Required ",
    usageTypePrefixLength: "Usage type prefix should not exceed 15 characters",
    usageTypeValidation: "Usage type is Required",
    usageTypeReqLength: "Usage type should not exceed 50 characters",
    usageTypeMrValidation: "Usage type (Marathi) is Required",
    usageTypeMrLength: "Usage type (Marathi) should not exceed 100 characters",

    asOnDateValidation: "As on date is Required  !!!",
    applicantTitleValidation: "Applicant Title is Required  !!!",
    noOfCopiesValidation: "Number of copies is Required  !!!",
    applicantFirstNameValidation: "Applicant First Name is Required  !!!",
    applicantFirstNameValidationLength:
      "Applicant First Name should not exceed 50 characters",
    titleValidation: "Title is Required  !!!",
    revertSection: "Revert Section",
    revertedRemark: "Revert Remark",
    accept: "Accept",
    revert: "Revert",
    siteVisitDone: "Do you want site visit complete?",
    isRescheduled: "Is Rescheduled",
    applicantFirstNameMrValidation:
      "Applicant First Name (Marathi) is Required  !!!",
    applicantFirstNameMrValidationLength:
      "Applicant First Name (Marathi) should not exceed 100 characters",
    applicantMiddleNameValidation: "Applicant Middle Name is Required  !!!",
    applicantMiddleNameValidationLength:
      "Applicant Middle Name should not exceed 50 characters",
    applicantMiddleNameMrValidation:
      "Applicant Middle Name (Marathi) is Required  !!!",
    applicantMiddleNameMrValidationLength:
      "Applicant Middle Name (Marathi) should not exceed 100 characters",
    applicantLastNameValidation: "Applicant Last Name is Required  !!!",
    applicantLastNameValidationLength:
      "Applicant Last Name should not exceed 50 characters",
    applicantLastNameMrValidation:
      "Applicant Last Name (Marathi) is Required  !!!",
    applicantLastNameMrValidationLength:
      "Applicant Last Name (Marathi) should not exceed 100 characters",
    applicantMobileNoValidation: "Mobile number is Required  !!!",
    applicantAadharNoValidation: "Applicant aadhar number is Required  !!!",
    applicantAadharNoValidationMinLength: "Aadhar No must be 12 numbers",
    applicantAadharNoValidationLength: "Aadhar No should not exceed 12 numbers",
    aadharNoValidation: "Aadhar number is Required  !!!",
    approvalSection: "Approval Section",
    clearkRemarks: "Clerk Remark",
    headClerkApprovalRemark: "Head Clerk Remark",
    officeSuperintendantApprovalRemark: "Office Superintendant Remark",
    administrativeOfficerApprovalRemark: "Administrative Officer Remark",
    assistantCommissionerApprovalRemark: "Assistant Commissioner Remark",
    finalApprovedRemark: "Final Remark",

    feesApplicableValidation: "Fees applicable is Required  !!!",
    newHutNoValidation: "Hut number is Required  !!!",
    saleValueValidation: "Sale value is Required  !!!",
    marketValueValidation: "Market Value is Required  !!!",
    transferRemarksValidation: "Transfer Remark is Required  !!!",
    proposedOwnerTitleValidation: "Proposed owner title is Required  !!!",
    proposedOwnerFirstNameValidation: "First name is Required  !!!",
    proposedOwnerFirstNameValidationLength:
      "First name should not exceed 50 characters",
    proposedOwnerFirstNameMrValidation: "First name is Required  !!!",
    proposedOwnerFirstNameMrValidationLength:
      "First name (Marathi) should not exceed 100 characters",
    proposedOwnerMiddleNameValidation: "Middle name is Required  !!!",
    proposedOwnerMiddleNameValidationLength:
      "Middle name should not exceed 50 characters",
    proposedOwnerMiddleNameMrValidation: "Middle name is Required  !!!",
    proposedOwnerMiddleNameMrValidationLength:
      "Middle name (Marathi) should not exceed 100 characters",
    proposedOwnerLastNameValidation: "Last name is Required  !!!",
    proposedOwnerLastNameValidationLength:
      "Last name should not exceed 50 characters",
    proposedOwnerLastNameMrValidation: "Last name is Required  !!!",
    proposedOwnerLastNameMrValidationLength:
      "Last name (Marathi) should not exceed 100 characters",
    proposedOwnerMobileNoValidation:
      "Proposed owner mobile number  is Required  !!!",
    proposedOwnerAadharNoValidation:
      "Proposed owner Aadhar No must be 12 numbers  !!!",
    proposedOwnerAadharNoValidationMinLength:
      "Proposed owner aadhar number must be 12 numbers",
    proposedOwnerAadharNoValidationLength:
      "Proposed owner aadhar number should not exceed 12 numbers",
    transferDateValidation: " Transfer date is Required  !!!",
    transferTypeKeyValidation: "Transfer type is Required  !!!",
    subTransferTypeKeyValidation: "Sub transfer type is Required  !!!",

    mobileNoValidation: "Mobile number  is Required  !!!",

    spouseOccupationValidation: "Occupation is Required  !!!",
    spouseRelationKeyValidation: "Relation is Required  !!!",
    emailIdValidation: "E-mail is Required  !!!",
    emailIdValidtionLength: "Email Id should not exceed 80 characters",
    spouseAgeValidation: "Age is required",
    spouseAgePtvValidation: "Age must be a positive number",
    spouseAgeIntValidation: "Age must be an integer",
    spouseAgeValidationLength: "Age must be 18 years or older",

    visitTimeValidation: "Visit time is Required  !!!",
    lattitudeValidation: "Lattitude is Required  !!!",
    longitudeValidation: "Longitude is Required  !!!",
    geocodeValidation: "Geocode is Required  !!!",
    scheduleDateTimeValidation: "Schedule date and time is Required  !!!",
    downloadNoc: "Download NOC",
    revertedSection:'Reverted Section',
    approvalSection: "Approval Section",
    clearkRemarks: "Clerk Remark",
    headClerkApprovalRemark: "Head Clerk Remark",
    officeSuperintendantApprovalRemark: "Office Superintendant Remark",
    administrativeOfficerApprovalRemark: "Administrative Officer Remark",
    assistantCommissionerApprovalRemark: "Assistant Commissioner Remark",
    finalApprovedRemark: "Final Remark",
    iagreeForOnlinePay: "I Agree For Online Payment",

    acknowledgementNo: "Acknowledgement No",

    amountInWord: "Amount in word",
    narration: "Narration",
    yourPaymentDoneSuccess: " Your payment done successful!!!",
    paymentFailed: "Payment failed!!!",
    orderId: "Order Id ",
    trackingId: "Tracking Id",
    bankRefNo: "Bank Reference No",
    billingName: "Billing Name",
    billingAdd: "Billing Address",
    billingCity: "Billing City",
    billingZip: "Billing Zipcode ",
    billingCountry: "Billing Country",
    billingEmail: "Billing Email",
    mobileNo: "Mobile No",
    billingState: "Billing State",
    transactionDate: "Transaction Date",
    goToList: "Go To List",
    pcmc: "Pimpri-Chinchwad Municipal Corporation",
    fiscalYear: "F.Y.",
    date: "Date",
    relatedTo: "Related To",
    cfcRefNo: "CFC Ref. No",
    cfcCounterNo: "CFC Counter No.",
    receivedFrom: "Received From",
    slum: "Slum Billing System",
    narration: "Narration",
    applicationServiceReceipt: "Application Service Charge Receipt",
    officeCopy: "OFFICE COPY",
    customerCopy: "CUSTOMER COPY",
    rupees: "Rupees",
    chequeNo: "Cheque No.",
    chequeDate: "Cheque Date",
    bankName: "Bank Name",
    referenceNo: "Reference No.",
    details: "Details",
    payableAmount: "Payable Amount",
    receivedAmount: "Received Amount",
    rebateAmount: "Rebate/Concession Amount",
    advanceAmount: "Advance Amount",
    actualPayableAmount: "Actual Payable Amount",
    receiverSignature: `Receiver's Signature`,
    printBy: "Printed By",
    printDateAndTime: "Print Date and Time",
    loiGenerate: "LOI Generate",
    serviceCharges: "Service Charges",

    hutTransferServiceReceipt: "Hut Transfer Service Charge Receipt",
    nocServiceReceipt: "Issuance of Noc Service Charge Receipt",
    photoPassServiceReceipt: "Issuance of Photopass Service Charge Receipt",
    aadharErrorMsg: "Adhar number is already exist",
    cluster: "Cluster",
    clusterName: "Cluster Name",
    clusterNameMr: "Cluster Name (मराठी)",
    OtherPopulation: "Other Population",
    noDocUpload: "No Document Uploaded",
    nameOfScheme: "Name of Scheme",
    location: "Location",
    flatNo: "Flat No",
    eligible: "Eligible",
    noteligible: "Not Eligible",
    makeLoiPayment: "Make LOI Payment",
    viewDoc: "View",
    remarkReq: "Remark is Required",
    iAgree: "I Agree",
  },

  mr: {
    attachment: "अपलोड फाइल",
    loiDetails: "LOI देयक तपशील",
    transactionDateTime: "व्यवहाराची तारीख-वेळ",
    inssuranceOfPhotopassDetails: "फोटोपास तपशील",
    generateReports: "अहवाल तयार करा",
    clerkApprovalRemark: "लिपिक टिप्पणी",
    headClerkApprovalRemark: "मुख्य लिपिक टिप्पणी",
    officeSuperintendantApprovalRemark: "कार्यालय अधीक्षक टिप्पणी",
    administrativeOfficerApprovalRemark: "प्रशासकीय अधिकारी टिप्पणी",
    assistantCommissionerApprovalRemark: "सहाय्यक आयुक्त टिप्पणी",
    viewPhoto: "फोटो पहा",
    serviceTaxReciept: "सेवा कर पावती",

    remarks: "टिप्पणी",
    generateInspectionReport: "तपासणी अहवाल तयार करा",
    generatedInspectionReport: "तपासणी अहवाल तयार केला",
    uploadSiteVisitImages: "साइट भेट प्रतिमा अपलोड करा",
    attachImages: "तपासणी अहवाल संलग्न करा",
    attachInspectionImages: "तपासणी प्रतिमा संलग्न करा",
    geocode: "भौगोलिक कोड",
    photopassSiteDetails: "साइट भेट तपशील",
    fileUploadValidationError: "आपण फक्त 5 प्रतिमा जोडू शकता",
    scheduleDateTime: "तारीख-वेळ शेड्यूल करा",
    rescheduleDateTime: "तारीख-वेळ पुन्हा शेड्यूल करा",
    visitDateTime: "भेटीची तारीख-वेळ",
    back: "मागे",
    generate: "उत्पन्न करा",
    generateDocuments: "कागदपत्रे तयार करा",
    selfDeclarationForm: "स्वयंघोषणा प्रपत्र",
    selfAttestation: "स्वयं - साक्षांकनासाठी स्वयंघोषणापत्र ",
    slumDetails: "झोपडपट्टी तपशील",

    noOfCopies: "प्रतींची संख्या",
    slumAddress: "झोपडपट्टी मालकाचा तपशील",
    applicantInfo: "अर्जदाराची माहिती",
    additionalFields: "अतिरिक्त फील्ड",
    outstandingTaxesAmount: "थकबाकी कर रक्कम",
    waterTaxesAmount: "पाणीकराची रक्कम",
    slumTaxesAmount: "झोपडपट्टी कर रक्कम",
    completeSiteVisit: "साइट भेट पूर्ण",
    cancel: "रद्द करा",

    //// Self Declaration ////////

    formA: "प्रपत्र - अ",
    declarationForm: "स्वयंघोषणा प्रपत्र",
    applicantPhoto: "अर्जदाराचा फोटो",
    me: "मी",
    mr: "श्री.",
    sonOf: "यांचा मुलगा/मुलगी, वय",

    ////// reports

    casteWiseReport: "जातनिहाय अहवाल",
    slumName: "झोपडपट्टीचे नाव",
    downloadEXCELL: "एक्सेल डाउनलोड करा",
    downloadPDF: "PDF डाउनलोड करा",
    religion: "धर्म",
    caste: "जात",
    handicap: "अपंग",
    widow: "विधवा",
    eligibleIneligibleCriteria: "पात्र/अपात्र निकष",
    ownershipTypeWiseReport: "मालकी प्रकारानुसार अहवाल",
    ownership: "मालकी",
    hutCount: "झोपडी गणना",
    defaulterReport: "डिफॉल्टर अहवाल",
    fromAmount: "रकमेपासून",
    toAmount: "रक्कम",
    previousAmount: "मागील रक्कम",
    currentAmount: "चालू रक्कम",
    hutRegister: "झोपडी नोंदणी",
    signMobileNo: "स्वाक्षरी-मोबाईल क्र.",
    dayWiseCollectionRegister: "दिवसनिहाय संकलन नोंदवही",
    bookAndRecieptNo: "पुस्तक व पावती क्रमांक",
    recieptDate: "पावती तारीख",
    recoveredFromWhom: "कोनाकडुन वसुल केले",
    overAmount: "जास्त रक्कम",
    date: "तारीख",
    demandReport: "मागणी अहवाल",
    pimpri: "पिंपरी १८",
    hutOccupierName: "झोपडीधारकाचे नाव",
    eligible: "पात्र",
    inEligible: "अपात्र",
    hutWiseDetailReport: "झोपडी वार तपशील अहवाल",
    photopassStatusReport: "फोटोपास स्थिती अहवाल",
    clerk: "लिपिक",
    headClerk: "मुख्य लिपिक",
    officeSuperintendant: "कार्यालयीन अधीक्षक",
    administrativeOfficer: "प्रशासकीय अधिकारी",
    assistantCommissioner: "सहाय्यक आयुक्त",

    ////// Issuance of NOC

    issuanceOfNoc: "एनओसी जारी करणे",
    nocSiteDetails: "साइट भेट तपशील",
    issuanceOfNocDetails: "एनओसी तपशील",
    issueNoc: "एनओसी जारी करा",
    purposeForNoc: "एनओसीसाठी उद्देश",
    purpose: "उद्देश",
    purposeValidation: "एनओसीसाठी उद्देश आवश्यक आहे !!",

    ////// Hut Bill Generation

    hutBillGeneration: "झोपडी बिल जनरेशन",
    generatedHutBill: "उत्पन्न केलेले झोपडी बिल",

    ///// HUT Transfer

    hutTransfer: "झोपडी हस्तांतरण",
    proposedOwner: "प्रस्तावित मालक",
    currentOwner: "वर्तमान मालक",
    transferType: "हस्तांतरण प्रकार",
    marketValue: "बाजार भाव",
    saleValue: "विक्री मूल्य",
    searchHutDetails: "झोपडी तपशील शोधा",
    hutDetails: "झोपडी तपशील",
    familyMemberDetails: "कुटुंबातील सदस्यांचे तपशील",

    zoneName: "झोन",
    hutOwnerDetails: "झोपडी मालक तपशील",
    hutOccupiersDetails: "झोपडीधारकाचे तपशील",
    hutAddressDetails: "झोपडीचा पत्ता तपशील",
    transferDetails: "तपशील हस्तांतरित करा",
    generateRejectionLetter: "नकार पत्र उत्पन्न करा",
    details: "तपशील",
    subTransferType: "उपहस्तांतरण प्रकार",
    transferDate: "हस्तांतरण तारीख",
    viewExistingOwnerName: "विद्यमान मालकाचे नाव पहा",
    ownerName: "मालकाचे नाव",
    addName: "नाव जोडा",
    siteVisitRemark: "साइट भेट टिप्पणी",
    hutNo: "झोपडी क्र",
    oldHutNo: "जुनी झोपडी क्र",
    hutArea: "झोपडी क्षेत्र चौ.फुट (अंदाजे)",
    slumArea: "झोपडपट्टी क्षेत्र चौ.फुट (अंदाजे)",
    close: "बंद",
    currentOwnerTitle: "वर्तमान मालक शीर्षक",
    currentOwnerFirstName: "वर्तमान मालकाचे नाव",
    currentOwnerMiddleName: "वर्तमान मालकाच्या वडिलांचे नाव",
    currentOwnerLastName: "वर्तमान मालकाचे आडनाव",
    currentOwnerMobileNo: "वर्तमान मालकाचा मोबाईल क्र",
    currentOwnerAadharNo: "वर्तमान मालक आधार क्र",
    newOwnerDetails: "नवीन मालक तपशील",
    proposedOwnerTitle: "शीर्षक",
    proposedOwnerFirstName: "पहिले नाव",
    proposedOwnerFirstNameMr: "पहिले नाव(मराठीत)",
    proposedOwnerMiddleName: "वडीलांचे नावं",
    proposedOwnerMiddleNameMr: "वडीलांचे नावं(मराठीत)",
    proposedOwnerLastName: "आडनाव",
    proposedOwnerLastNameMr: "आडनाव(मराठीत)",
    proposedOwnerMobileNo: "मोबाईल क्र",
    proposedOwnerAadharNo: "आधार क्र",
    proposedOwnerEmailId: "ई-मेल आयडी",
    transferRemarks: "हस्तांतरित टिप्पण्या",
    scheduleSiteVisitDetails: "साइट भेट तपशील",
    reScheduleSiteVisit: "साइटला भेट रीशेड्युल करा",
    siteVisitDone: "तुम्हाला साइट भेट पूर्ण करायची आहे का?",

    transferHutSiteDetails: "साइट भेट तपशील",

    //SLUM master
    slumPrefixEn: "झोपडपट्टी उपसर्ग",
    slumPrefixMr: "झोपडपट्टी उपसर्ग(मराठी)",
    citySurveyNo: "शहर सर्वेक्षण क्र",
    surveyNo: "सर्वेक्षण क्र / गट क्र",
    declarationDate: "घोषणा तारीख",
    declarationOrderNo: "घोषणा आदेश क्रमांक",
    slumNameEn: "झोपडपट्टीचे नाव (इंग्रजी)",
    slumNameMr: "झोपडपट्टीचे नाव (मराठी)",
    areaName: "क्षेत्राचे नाव",
    areaOfSlum: "झोपडपट्टीचा परिसर",
    declarationOrder: "घोषणा आदेश",
    noOfHuts: "झोपड्यांची संख्या",
    hutOccupiedArea: "झोपडी व्यापलेले क्षेत्र",
    population: "एकुण लोकसंख्या",
    malePopulation: "पुरुष लोकसंख्या",
    femalePopulation: "महिला लोकसंख्या",
    scPopulation: "SC लोकसंख्या",
    stPopulation: "ST लोकसंख्या",
    slumBoundaryInfo: "झोपडपट्टीची माहिती",
    slumStatus: "झोपडपट्टीची स्थिती",

    hutMaster: "झोपडी मास्टर",
    hutMember: "झोपडी सदस्य",
    age: "वय",
    genderKey: "लिंग",
    religionKey: "धर्म",
    religionKeyValidation: "धर्म आवश्यक आहे !!!",
    casteKey: "जात",
    casteKeyValidation: "जात आवश्यक आहे !!!",
    castCategory: "जात प्रवर्ग",
    castCategoryValidation: "जात प्रवर्ग आवश्यक आहे !!!",
    subCasteKey: "पोटजाती",
    educationKey: "शिक्षण",
    educationKeyValidation: "शिक्षण आवश्यक आहे !!!",
    headOfFamily: "कुटुंब प्रमुख",
    collection: "संकलन",
    trnCollectionDate: "व्यवहाराची तारीख",
    serviceName: "सेवेचे नाव",
    receiptNo: "पावती क्र",
    collectionCenter: "संकलन केंद्र",
    counter: "काउंटर",
    moduleName: "मॉड्यूलचे नाव",
    userName: "वापरकर्ता नाव(SAP/NonCore/GIS)",
    receiptType: "पावती प्रकार",
    refernece: "संदर्भ",
    referenceDate: "संदर्भ तारीख",
    payerName: "देयकाचे नाव",
    address: "पत्ता",
    narration: "कथन",
    payment: "पेमेंट",
    paymentMode: "पेमेंट मोड",
    accoundCode: "खाते कोड",
    codeDescription: "कोड वर्णन",
    amount: "रक्कम",
    totalAmount: "एकूण रक्कम",
    receivedAmount: "प्राप्त रक्कम",
    paymentModeKey: "देयक प्रकार",
    paymentAmount: "देयक रक्कम",
    transactionStatus: "व्यवहार स्थिती",
    year: "वर्ष",
    financialYear: "आर्थिक वर्ष",
    viewBill: "बील पहा",
    bill: "बील",
    completeAndIssueOrder: "पूर्ण करा आणि ऑर्डर जारी करा",

    genderKeyValidation: "लिंग आवश्यक आहे !!!",

    ownershipTypePrefix: "मालकी प्रकार उपसर्ग",
    fromDate: "या तारखेपासून",
    toDate: "आजपर्यंत",
    ownershipType: "मालकीचा प्रकार",
    ownershipTypeMr: "मालकीचा प्रकार (मराठी)",
    btnSaveText: "जतन करा",
    remark: "टिप्पणी",
    scheduleSiteVisit: "साइट भेटीचे वेळापत्रक",

    constructionTypePrefix: "बांधकाम प्रकार उपसर्ग",
    constructionType: "बांधकाम प्रकार",
    constructionTypeMr: "बांधकाम प्रकार (मराठी)",

    usageTypePrefix: "वापर प्रकार उपसर्ग",
    usageType: "वापर प्रकार",
    usageTypeMr: "वापर प्रकार (मराठी)",

    subUsageTypePrefix: "उप वापर प्रकार उपसर्ग",
    subUsageType: "उप वापर प्रकार",
    subUsageTypeMr: "उप वापर प्रकार (मराठी)",

    factorPrefix: "घटक उपसर्ग",
    factorName: "घटक नाव",
    factorNameMr: "घटक नाव (मराठी)",
    applicableOn: "वर लागू",

    setFor: "च्यासाठी ठेवा",
    flagName: "ध्वज नाव",
    flagNameMr: "ध्वज नाव (मराठी)",

    billingCyclePrefix: "बिलिंग सायकल उपसर्ग",
    billingCycle: "बिलिंग सायकल",
    billingCycleMr: "बिलिंग सायकल (मराठी)",

    ageSlabPrefix: "वय स्लॅब उपसर्ग",
    ageSlabName: "वय स्लॅब",
    ageSlabNameMr: "वय स्लॅब(मराठी)",
    rangeOfAge: "वयाची श्रेणी",

    educationCategoryPrefix: "शिक्षण श्रेणी उपसर्ग",

    educationCategory: "शिक्षण श्रेणी",
    educationCategoryMr: "शिक्षण श्रेणी उपसर्ग (मराठी)",
    stream: "प्रवाह",
    std: "इयत्ता",

    onlyeng: "फक्त इंग्लिश",
    onlymarathi: "फक्त मराठी",
    APPROVE: "मंजूर करा",
    photo: "छायाचित्र",
    husbandWifePhoto: "पती पत्नीचा एकत्रित फोटो अपलोड करा",

    REASSIGN: "पुन्हा नियुक्त करा",
    remarkModel: "अर्जावर टिप्पणी प्रविष्ट करा",

    oldLabel: "पूर्वीची माहिती",
    newLabel: "नवीन माहिती",
    onlyMIMC: "विवाह प्रमाणपत्रात बदल",
    State: "स्टेट (इंग्लिश) ",
    statemr: "स्टेट (मराठी) ",
    UploadFile: "फाइल अपलोड करा",
    electrbill: "वीज बिल",
    OtherDocument: "इतर दस्तऐवज",
    rationcard: "रेशान कार्ड",
    adharcard: "आधार कार्ड",
    panCard: "पॅन कार्ड",
    boardorgphotocpy: "संस्था किंवा मंडळची दस्तऐवज",
    boardheadphoto: "मंडळाच्या प्रमुख व्यक्तीच छायाचित्र",
    document: "दस्तऐवज",
    Owneraddress: " मंडळच्या प्रमुख व्यक्तीचा पत्ता  :",
    OwnerDetails: "मंडळच्या प्रमुख व्यक्तीची माहिती",
    titleInmarathi: "शीर्षक मराठी",
    titleInenglish: "शीर्षक इंग्लिश",
    OwnerChkeck: "जर अर्जादारच विवाह मंडळाचा प्रमुख असेल",
    apply: "जतन करा",
    ifsc: "आय एफ एस सी कोड",
    accountNumber: "खाते क्रमांक",
    bankName: "बँकेचे नाव",
    branchName: "शाखेचे नाव",
    bankAccountNo: "बँक खाते क्रमांक",
    ddDate: "डिमांड ड्राफ्ट तारीख",
    ddNo: "डिमांड ड्राफ्ट क्रमांक",
    receiptAmount: "पावती रक्कम",
    receiptNumber: "पावती क्रमांक",
    receiptDate: "पावती तारीख",
    paymentMode: "Payment Mode",
    paymentType: "Payment Type",
    receiptModeDetails: "Receipt Mode Details",
    chargesDetails: "शुल्क तपशील",
    applicantDetails: "अर्जदाराची माहिती",
    generateLoi: "स्विकृती पत्र तयार करा",
    totalCharges: "एकुण रक्कम",
    totalInWords: "एकुण अक्षरी रक्कम ",
    amount: "रक्कम",
    EnterDocName: "कृपया दस्तऐवजाच नाव भरा ",
    witnessAddressC: "कृपया पत्ता भरा  ",
    witnessRelation: "कृपया साक्षीदारशी नाते भरा  ",

    birthProf: "कृपया जन्म तारीख पुरावा निवडा ",
    ResideProof: "कृपया रहिवासाचा पुरावा निवडा ",
    IdentyProof: "कृपया ओळखपत्र पुरावा निवडा ",
    // //Remarks
    selectReligionby: "कृपया जन्माने धर्म निवडा ",
    selectAdoptionby: "कृपया दत्तक घेऊन धर्म निवडा ",
    selectStatusAt: "कृपया लग्नाच्या वेळची स्थिती निवडा ",

    enterAge: "कृपया वय भरा ",
    selectGender: "कृपया लिंग निवडा ",
    selectZone: "कृपया झोन निवडा",
    selectWard: "कृपया वार्ड निवडा",
    selectDate: "कृपया तारीख निवडा",
    selectTitle: "कृपया शीर्षक निवडा",
    enterFName: "कृपया पहिले नाव भरा (इंग्लिश)",
    enterMName: "कृपया मधले  नाव भरा (इंग्लिश)",
    enterLName: "कृपया शेवटचे नाव भरा (इंग्लिश)",

    enterFNameMr: "कृपया पहिले नाव भरा (मराठी) ",
    enterMNameMr: "कृपया मधले  नाव भरा (मराठी)",
    enterLNameMr: "कृपया शेवटचे नाव भरा (मराठी)",

    enterFlat: "कृपया  फ्लॅट नंबर नाव भरा  (इंग्लिश) ",
    enterApartment: "कृपया  अपार्टमेंट  नाव भरा  (इंग्लिश)",
    enterRoadName: "कृपया रस्त्याचे नाव भरा (इंग्लिश)",
    enterLandmark: "कृपया  महत्त्वाची खूण भरा (इंग्लिश)",
    enterCity: "कृपया  शहराचे / गावाचे नाव भरा (इंग्लिश)",
    state: "कृपया  राज्य नाव भरा (इंग्लिश)",

    enterFlatMr: "कृपया  फ्लॅट नंबर नाव भरा  (मराठी)",
    enterApartmentMr: "कृपया  अपार्टमेंट  नाव भरा(मराठी)",
    enterRoadNameMr: "कृपया रस्त्याचे नाव भरा  (मराठी)",
    enterLandmarkMr: "कृपया  महत्त्वाची खूण भरा  (मराठी)",
    enterCityMr: "कृपया  शहराचे / गावाचे नाव भरा (मराठी)",
    stateMr: "कृपया  राज्य नाव भरा  (मराठी)",

    enterArea: "कृपया क्षेत्राचे नाव भरा ",
    enterRoadName: "कृपया रस्त्याचे नाव भरा ",
    enterLandmark: "कृपया  महत्त्वाची खूण भरा",
    enterCity: "कृपया  शहराचे / गावाचे नाव भरा ",

    enterPinCode: "कृपया पिनकोड भरा",
    enterPhoneNo: "कृपया दूरध्वनी नं. भरा",
    enterMobileNo: "कृपया मोबाईल नं. भरा",
    enterEmailAddress: "कृपया इलेक्ट्रॉनिक संदेश भरा",
    enteraadhaarNo: "कृपया आधार नं. भरा",
    enterpanNo: "कृपया पॅन नं. भरा",
    enterRemarks: "कृपया टिप्पणी. द्या",
    //mr
    selectWard: "कृपया प्रभाग निवडा ",
    selectZone: "कृपया झोन निवडा ",
    selectTitle: "कृपया शीर्षक निवडा ",
    placeMarriage: "कृपया  विवाहाचा ठिकाण भरा (इंग्लिश)",
    placeMarriageMr: "कृपया  विवाहाचा ठिकाण भरा  (मराठी)",

    pay: "पैसे भरा",
    titlemr: "शीर्षक ",
    title1: "Title ",
    newMRtable: "नवीन विवाह नोंदणी",
    module: "विवाह नोंदणी",
    // dashboard: 'डॅशबोर्ड',
    dashboard: "पिंपरी-चिंचवड महानगरपालिका डॅशबोर्ड",
    masters: "मास्टर्स",
    transactions: "ट्रैन्ज़ैक्शन",
    reports: "अहवाल",
    receipt: "पावती",
    usertask: "User task",
    serviceChargeTypeName: "सेवा शुल्काचा प्रकार",

    chargeName: "शुल्काचा प्रकार",
    masters: "मास्टर्स",
    masterPath: "तक्रार निरीक्षण / मास्टर्स",

    transaction: "व्यवहार",
    report: "अहवाल",
    masterPath: "अग्निशमन यंत्रणा / मास्टर ",
    transactionPath: "कायदेशीर प्रकरण/ व्यवहार ",
    reportPath: "कायदेशीर प्रकरण/ अहवाल ",

    //mr
    MrMasters: "विवाह नोंदणी/ मास्टर ",
    marriageRegistrationMaritalStatus: "विवाह नोंदणी/ मास्टर / वैवाहिक स्थिती",

    marriageRegistrationrelation: "विवाह नोंदणी/ मास्टर / नाते",

    AptBook: "अपॉइंटमेंट स्लॉट बुकिंग",

    documentUpload: "दस्तऐवज अपलोड",
    addFile: "फाइल जोडा",
    fileName: "फाईलचे नाव",
    mandatoryOrOptional: "अनिवार्य/पर्यायी",
    mandatory: "अनिवार्य",
    optional: "पर्यायी",
    verify: "सत्यापित",
    reject: "नाकारा",
    noFileFound: "कोणतीही फाइल आढळली नाही",
    verified: "तपासून झाले",

    upload: "अपलोड करा",
    next: "पुढे",
    preview: "पूर्वावलोकन",
    _preview: "पूर्वावलोकन",
    agreeAndProceed: "सहमत आणि पुढे जा",

    attachFile: "फाईल जोडा",
    rquiredAttachFile: "आवश्यक संलग्न फाइल",
    srNo: "अनु क्र",
    actions: "क्रिया ",
    serviceName: "सेवेचे नाव ",
    //titles

    calendarScheduling: " दिनदर्शिका शेड्युलिंग",
    maritialSatus: "वैवाहिक स्थिती",
    relation: "नाते",
    statusDetails: "स्थिती तपशील",
    spouseDetails: "जोडीदार तपशील",

    //buttons
    add: "जोडा",
    save: "जतन करा",
    update: "अद्यायावत करा",
    clear: "रिक्त",
    exit: "बाहेर पडा",
    Revert: "परत पाठवा",
    Complete: "पूर्ण",
    issuePhotopass: "फोटोपास जारी करा",

    ward: "प्रभाग",
    wardName: "प्रभाग",
    zone: "झोन",
    latitude: "अक्षांश",
    Longitude: "रेखांश",
    LongitudeReq: "रेखांश आवश्यक आहे",
    latitudeReq: "अक्षांश आवश्यक आहे",

    ApplicatCheck1: "जर अर्जदार वर असेल तर",
    ApplicatCheck2: "जर अर्जदार वधु असेल तर",

    transactions: " ट्रैन्ज़ैक्शन",
    transactionPath: "कायदेशीर प्रकरण/  ट्रैन्ज़ैक्शन ",

    //mr
    // instrustion
    onlyMHR:
      "महाराष्ट्रातील विवाहाचे रजिस्ट्रेशन केले जाते आणि वधू किंवा वर यापैकी एक जण पिंपरी चिंचवड महानगर पालिकेच्या हद्दी मधील रहिवासी असावा.",
    docNote:
      "आयडी पुरावा, रहिवासी पुरावा, वयाचा पुरावा वेगळा असावा, (लग्नाच्या वेळी स्थिती असल्यास मागील स्टेटस प्रूफमध्ये मूल्य असते विधवा/विधुर किंवा घटस्फोटीत आहे) आधारकार्ड पुरावा जोडल्यास व नागरिक भाड्याने राहत असलेस नोंदणीकृत करारनामा आवश्यक आहे.",

    //aprove
    GPhoto: "वरचा फोटो  ",
    Bphoto: "वधुचा फोटो  ",
    witnessphto1: "साक्षीदारचा १ फोटो  ",
    witnessphto2: "साक्षीदारचा २ फोटो  ",
    witnessphto3: "साक्षीदारचा ३ फोटो  ",
    Gthumb: "वरचा अंगठाचा ठसा  ",
    Bthumb: "वधुचा अंगठाचा ठसा  ",
    witnessthumb1: "साक्षीदारचा १ अंगठाचा ठसा  ",
    witnessthumb2: "साक्षीदारचा २ अंगठाचा ठसा  ",
    witnessthumb3: "साक्षीदारचा ३ अंगठाचा ठसा  ",

    //table
    Tnc: "नियम व अटी",
    newMRtable: "नवीन विवाह नोंदणी",
    boardtitle: "विवाह मंडळाची माहिती",
    zone: "झोन",
    ward: "वार्ड",
    Addrees: "अर्जदाराचा रहिवासाचा पत्ता :",

    CrrtAdree: "सध्याचा रहिवासाचा पत्ता :",
    parmtAdree: "कायमचा रहिवासाचा पत्ता :",
    personalDetails: "वैयक्तिक माहिती :",
    Adress: "पत्ता :",
    BriNBM: "  (  लग्नाआधीचे नाव)",
    AppliToGroom: "",
    AppliToBride: "",
    marrigeDetails: "विवाहाची माहिती :",
    marrigeDate: "विवाहाची दिनांक",

    //title
    ApplicatDetails: "अर्जदाराची माहिती",
    ApplicatName: "अर्जदाराच नाव",
    groomDetail: "वराची माहिती",
    groomParaentDetail: "वराच्या पालकांची माहिती",
    brideDetails: "वधुची माहिती",
    brideParaentDetail: "वधुच्या पालकांची माहिती",
    priestDetails: "पुजारी माहिती",
    witness: "साक्षीदार",
    witnessDetails: "साक्षीदार माहिती",
    documentsUpload: "दस्तऐवज अपलोड",
    boardDetail: "विवाह मंडळाची माहिती :",
    otherDetail: "इतर तपशील",

    // viceversa
    titleV: "Title  ",
    firstNameV: "First Name  ",
    middleNameV: "Middle Name  ",
    lastNameV: "Last Name  ",

    //groom
    title: "शीर्षक",
    firstNameEn: "प्रथम नाव (इंग्लिश)",
    middleNameEn: "मधले नाव (इंग्लिश) ",
    lastNameEn: "आडनाव (इंग्लिश) ",
    firstName: "प्रथम नाव (इंग्लिश) ",
    middleName: "मधले नाव (इंग्लिश) ",
    lastName: "आडनाव (इंग्लिश) ",
    firstNamemr: "प्रथम नाव (मराठी) ",
    middleNamemr: "मधले नाव (मराठी) ",
    lastNamemr: "आडनाव (मराठी) ",
    BirthDate: "जन्म दिनांक  ",
    Gender: "लिंग",
    AadharNo: "आधार नंबर",
    Age: "वय (लग्नाच्या वेळीचे वय)",
    mobileNo: "दूरध्वनी क्रमांक",
    phoneNo: "फोन नंबर",
    email: "ई-मेल",

    flatBuildingNo: "फ्लॅट नंबर (इंग्लिश) ",
    buildingName: "अपार्टमेंट नाव (इंग्लिश) ",
    roadName: "गल्लीचे नाव (इंग्लिश) ",
    Landmark: "जमीन चिन्ह (इंग्लिश) ",
    villageName: "गावाचे नाव",
    villageNameValidation: "किमान एक गाव निवडा",
    zoneNameValidation: "किमान एक झोन निवडा",
    wardNameValidation: "किमान एक प्रभाग निवडा",
    clusterNameValidation: "किमान एक क्लस्टर निवडा",
    cityName: "शहराचे नाव (इंग्लिश) ",

    flatBuildingNomr: "फ्लॅट नंबर (मराठी) ",
    buildingNamemr: "अपार्टमेंट नाव (मराठी) ",
    roadNamemr: "गल्लीचे नाव (मराठी) ",
    Landmarkmr: "जमीन चिन्ह (मराठी) ",
    villageNamemr: "गावाचे नाव",
    cityNamemr: "शहराचे नाव (मराठी) ",

    // flatBuildingNo: 'फ्लॅट नंबर',
    // buildingName: 'अपार्टमेंट नाव',
    // roadName: 'गल्लीचे नाव',
    // Landmark: 'जमीन चिन्ह',
    // villageName: 'गावाचे नाव ',
    // cityName: 'शहराचे नाव',
    state: "राज्य (इंग्लिश) ",
    statemr: "राज्य (मराठी)  ",

    pincode: "पिन कोड",
    Religion1: "जन्माने धर्म",
    Religion2: "दत्तक घेऊन धर्म",
    StatusOfMarrige: "लग्नाच्या वेळची स्थिती",
    AgeDocument: "वयाचे कागदपत्र",
    IdDocument: "ओळख कागदपत्र ",
    residentialDocument: "रहिवाशी कागदपत्र",
    StatusOfDocument: "कागदपत्र स्थिती ",

    //groomFather
    firstNameF: "वडिलांचं प्रथम नाव  ",
    middleNameF: "वडिलांचं मधले नाव  ",
    lastNameF: "वडिलांचं आडनाव  ",
    AgeF: "वडिलांच वय",
    mobileNoF: "वडिलांचं दूरध्वनी क्रमांक",
    AadharNoF: "वडिलांचं आधार नंबर",

    //groomMother
    firstNameM: "आईचे प्रथम नाव  ",
    middleNameM: "आईचे मधले नाव  ",
    lastNameM: "आईचे आडनाव  ",
    AgeM: "आईचे वय",
    mobileNoM: "आईचे दूरध्वनी क्रमांक",
    AadharNoM: "आईचे आधार नंबर",

    //prist
    placeofMarriage: "लग्नाचे ठिकाण (इंग्लिश)",
    placeofMarriage1: "लग्नाचे ठिकाण (मराठी) ",

    //witness
    address: "पत्ता",
    wRelation: "साक्षीदारशी नाते",
    wDocument: "साक्षीदाराचे कागदपत्र",
    witnessAdd: "साक्षीदार जोडा",

    //Document

    DBProof: "जन्म तारीख पुरावा",
    ResProof: "रहिवासाचा पुरावा",
    IdProof: "ओळखपत्र पुरावा",
    ResProofW1: "प्रथम साक्षीदार रहिवासाचा पुरावा",
    ResProofW2: "द्वितीय साक्षीदार रहिवासाचा पुरावा",
    ResProofW3: "तृतिय साक्षीदार रहिवासाचा पुरावा",
    marrigeRelatedDoc: "विवाह संबंधित दस्तऐवज",
    invetaionCard: "विवाह निमंत्रण पत्रिका / प्रतिज्ञापत्र ",
    marrigePhotoC: "विवाह छायाचित्र (जोडीचे) ",
    marDrf: "१०० रुपयांच्या स्टॅम्प पेपरवर अर्जाचा मसुदा तयार करा",
    DivorcePaper: "वैध घटस्फोट कागद (लागू असल्यास)",
    DeathC: "मृत्यू प्रमाणपत्र (लागू असल्यास)",
    certiByReligiousPlc:
      " मंदिर, मशीद इ. धार्मिक स्थळाद्वारे जारी केलेले प्रमाणपत्र",
    docFormat:
      " (फक्त jpg.jpeg.png.bmp.pdf फाइल अपलोड करण्याची परवानगी आहे. फोटो आकार कमाल 100 kb)",
    enterDoc: "दस्तऐवजाच नाव ",

    //board
    applicantName: "अर्जदाराचे नाव ",
    boardNameT: "विवाह मंडळचे नाव",
    boardName: "विवाह मंडळचे नाव (इंग्लिश) ",
    boardNamemr: "विवाह मंडळचे नाव (मराठी) ",

    remark: "शेरा",
    documentList: "दस्तऐवज यादी",
    ValidtyofMBR: "विवाह मंडळाची अंतिम वैधता",
    documentsUploadF: "दस्तऐवज अपलोड",
    TandC: "",
    //button
    back: "मागे",
    next: "पुढे",
    add: "जोडा",
    save: "जतन करा",
    update: "अद्यायावत करा",
    clear: "रिक्त",
    exit: "बाहेर पडा",
    submit: "प्रस्तुत करणे",
    addFile: "फाइल जोडा",

    //table filed
    actions: "क्रिया ",
    hName: "वरचे नाव",
    wName: "वधूचे नाव",

    //brudcrum
    newMarriageRegistration: "विवाह नोंदणी / नवीन विवाह नोंदणी ",
    BoardMarriageRegistration: "विवाह मंडळ नोंदणी / नवीन विवाह मंडळ नोंदणी ",

    //module: 'शहर नियोजन',
    dashboard: "पिंपरी-चिंचवड महानगरपालिका डॅशबोर्ड",
    // master: 'मास्टर्स',
    // transactions: 'व्यवहार',
    // report: 'अहवाल',
    // masterPath: 'शहर नियोजन/ मास्टर ',
    // transactionPath: 'शहर नियोजन/ व्यवहार ',
    // reportPath: 'शहर नियोजन/ अहवाल ',

    // //breadcrum
    // landReservationPath: 'शहर नियोजन/ मास्टर / जमीन आरक्षण',
    // tdrZoneGatAndVillageMappingPath:
    //   'शहर नियोजन/ मास्टर / टीडीआर प्रभाग-गट आणि गाव मॅपिंग',
    // villageWiseLandReservationEntryPath:
    //   'शहर नियोजन/ मास्टर / गावनिहाय जमीन आरक्षण नोंद',
    // villageMappingWithDesignationPath:
    //   'शहर नियोजन/ मास्टर / पदनामासह गाव मॅपिंग',

    // //titles
    // landReservation: 'जमीन आरक्षण',
    // tdrZoneGatAndVillageMapping: 'टीडीआर प्रभाग-गट आणि गाव मॅपिंग',
    // villageWiseLandReservationEntry: 'गावनिहाय जमीन आरक्षण नोंद',
    // villageMappingWithDesignation: 'पदनामासह गाव मॅपिंग',

    // //other labels
    // landReservationID: 'जमीन आरक्षण क्र',
    // reservationName: 'आरक्षणाचे नाव',
    // reservationNameEng: 'आरक्षणाचे नाव इंग्रजीत',
    // reservationNameMr: 'आरक्षणाचे नाव मराठीत',
    // surveyNumber: 'सर्वेक्षण क्र',
    // landReservationLegend: 'जमीन आरक्षण आख्यायिका',
    // reservationAreaInHector: 'हेक्टर आरक्षण क्षेत्र',
    // landInPossession: 'ताब्यात जमीन',
    // remark: 'टिप्पणी',
    // villageName: 'गावाचे नाव',
    // gatName: 'गटाचे नाव',
    // zoneName: 'झोनचे नाव',
    // landReservationName: 'जमीन आरक्षण नाव',
    // citySurveyNo: 'शहर सर्वेक्षण क्र',
    // reservationNo: 'आरक्षण क्र',
    // landNotInPossessionInHector: 'ताब्यात नसलेली जमीन (हेक्टरमध्ये)',
    // landInPossessionInHector: 'ताब्यात जमीन (हेक्टरमध्ये)',
    // ddtp: 'डी.डी.टी.पी',
    // deAndTp: 'उपअभियंता /नगर नियोजक',
    // atpAndJe: 'सहाय्यक नगर नियोजक /कनिष्ठ अभियंता',

    // attachFile: 'फाईल जोडा',
    // srNo: 'अनु क्र',
    // actions: 'क्रिया ',

    // //buttons
    // add: 'जोडा',
    // save: 'जतन करा',
    // update: 'अद्यायावत करा',
    // clear: 'रिक्त',
    // exit: 'बाहेर पडा',
    // back: 'मागे',
    // saveAndNext: 'जतन करा आणि पुढे',
    // finish: 'समाप्त',

    //ReIssuance of Marriage Certificate

    onlyRIMC: "विवाह प्रमाणपत्र पुन्हा जारी करणे",
    mRegNo: "विवाह रजि क्र",
    marriageDate: "लग्नाची तारीख",
    marriageYear: "लग्नाचे वर्ष",
    brideName: "वधूचे नाव",
    groomName: "वराचे नाव",
    regDate: "नोंदणी दिनांक",

    //Renewal of Marriage Board Registration
    onlyRMBR: "विवाह मंडळ नोंदणीचे नूतनीकरण",
    mbrName: "विवाह मंडळ नोंदणी नाव",
    mbrDate: "विवाह मंडळ नोंदणी तारीख",
    mbrYear: "विवाह मंडळ नोंदणी वर्ष",
    search: "शोधा",

    //Application Details

    onlyApplDetail: "अर्ज तपशील",
    applFName: "अर्जदाराचे पहिले नाव",
    applMName: "अर्जदाराचे मधले नाव",
    applLName: "अर्जदार आडनाव",
    groomFName: "वराचे पहिले नाव",
    groomMName: "वराचे मधले नाव",
    groomLName: "वराचे आडनाव",
    brideFName: "वधूचे पहिले नाव",
    brideMName: "वधू मधले नाव",
    brideLName: "वधू आडनाव",
    mDate: "लग्नाची तारीख",

    //ReIssuance of marriage Certificate
    newRMItable: "विवाह प्रमाणपत्र पुन्हा जारी करणे",
    applFullName: "अर्जदाराचे पूर्ण नाव",
    applicationNo: "अर्ज क्र",
    applicationDate: "अर्ज तारीख",

    module: "कायदेशीर प्रकरण व्यवस्थापन प्रणाली",
    formType: "masters",
    master: "मास्टर्स",
    transaction: "व्यवहार",
    report: "अहवाल",

    masterPath: "कायदेशीर प्रकरण/ मास्टर ",
    transactionPath: "कायदेशीर प्रकरण/ व्यवहार ",

    courtPath: "कायदेशीर प्रकरण/ मास्टर /न्यायालय",
    advocatePath: "कायदेशीर प्रकरण/ मास्टर /वकील",
    serviceHierachyPath: "कायदेशीर प्रकरण/ मास्टर / सेवा पदानुक्रम",
    caseTypePath: "कायदेशीर प्रकरण/ मास्टर / प्रकरणाचा प्रकार",
    caseSubTypePath: "कायदेशीर प्रकरण/ मास्टर / प्रकरणाचा उप-प्रकार",
    caseStagesPath: "कायदेशीर प्रकरण/ मास्टर / प्रकरण-टप्पे",
    employeeAndUserCreationPath:
      "कायदेशीर प्रकरण/ मास्टर / कर्मचारी आणि वापरकर्ता निर्मिती",
    counterSchedulingPath: "कायदेशीर प्रकरण/ मास्टर / काउंटर शेड्युलिंग",
    smsEmailWhatsAppTemplatesPath:
      "कायदेशीर प्रकरण/ मास्टर / संदेश सेवा / इलेक्ट्रॉनिक संदेश/ व्हॉट्सॲप साचा",
    userAuthenticationAndRoleRightsPath:
      "कायदेशीर प्रकरण/ मास्टर / वापरकर्ता प्रमाणीकरण आणि भूमिका-अधिकार",
    changeResetForgetPasswordPath:
      "कायदेशीर प्रकरण/ मास्टर / बदल किंवा पुनर्प्रस्थापित किंवा पासवर्ड विसरलात",
    calendarSchedulingPath: "कायदेशीर प्रकरण/ मास्टर / दिनदर्शिका शेड्युलिंग",

    //titles
    court: "न्यायालय",
    advocate: "वकील",
    serviceHierachy: "सेवा पदानुक्रम",
    caseType: "प्रकरणाचा प्रकार",
    caseSubType: "प्रकरणाचा उप-प्रकार",
    caseStages: "प्रकरण-टप्पे",
    employeeAndUserCreation: "कर्मचारी आणि वापरकर्ता निर्मिती",
    counterScheduling: " काउंटर शेड्युलिंग",
    smsEmailWhatsAppTemplates:
      " संदेश सेवा / इलेक्ट्रॉनिक संदेश/ व्हॉट्सॲप साचा",
    userAuthenticationAndRoleRights: " वापरकर्ता प्रमाणीकरण आणि भूमिका-अधिकार",
    changeResetForgetPassword:
      "बदल किंवा पुनर्प्रस्थापित किंवा पासवर्ड विसरलात",
    calendarScheduling: " दिनदर्शिका शेड्युलिंग",

    //other labels
    other: "इतर",
    complaintType: "विषय/तक्रारीचा प्रकार *",
    complaintSubType: "तक्रारीचा उप प्रकार *",
    status: "स्थिती ",
    mediaName: "मीडियाचे नाव *",
    mediaPrefix: "मीडिया उपसर्ग *",
    remark: "टिप्पणी",
    eventType: "कार्यक्रमाचा प्रकार *",
    eventDate: "कार्यक्रमाची तारीख *",
    alertDateTime: "सूचना तारीख आणि वेळ *",
    description: "वर्णन",
    courtName: "न्यायालयाचे नाव",
    address: "पत्ता",
    roadName: "रस्त्याचे नाव",
    landmark: "महत्त्वाची खूण",
    cityOrVillage: "शहर / गाव",
    pincode: "पिनकोड",
    area: "क्षेत्राचे नाव",
    name: "नाव",
    mobile: "मोबाईल नं.",
    phone: "दूरध्वनी नं.",
    email: "इलेक्ट्रॉनिक संदेश",
    occupation: "व्यवसाय",
    relation: "कुटुंब प्रमुखाशी संबंध",
    aadharNo: "आधार नं.",
    panNo: "पॅन नं.",
    advocateCreation: "वकिल यशस्वीपणे तयार केला",
    advocateDetails: "वकील तपशील",
    bankDetails: "बँक तपशील",
    documentUpload: "दस्तऐवज अपलोड",
    title: "शीर्षक *",
    fname: "पहिले नाव *",
    mname: "मधले  नाव *",
    lname: "शेवटचे नाव *",
    advocateCategory: "वकील श्रेणी *",
    nameOfBarCouncil: "वकिलांचे मंडळचे प्रमाणपत्र परिषदचे नाव *",
    remarks: "टिप्पणी *",
    bankName: "बँकेचे नाव *",
    branchName: "शाखेचे नाव *",
    accountNo: "खाता क्रमांक *",
    bankIFSC: "बँक IFSC कोड *",
    bankMICR: "बँक MICR कोड *",
    application: "अर्ज:",
    aadharCard: "आधार कार्ड:",
    panCard: "पॅन कार्ड:",
    barCouncilCertificate: "वकिलांचे मंडळचे प्रमाणपत्र:",
    bankPassbook: "बँक पासबुक:",

    attachFile: "फाईल जोडा",
    actions: "क्रिया ",

    //Remarks
    selectDate: "कृपया तारीख निवडा",
    selectTitle: "कृपया शीर्षक निवडा",
    enterFName: "कृपया पहिले नाव भरा ",
    enterMName: "कृपया मधले  नाव भरा ",
    enterLName: "कृपया शेवटचे नाव भरा ",
    selectAdvocateCategory: "कृपया वकील श्रेणी निवडा",
    enterCouncilName: "कृपया वकिलांचे मंडळचे प्रमाणपत्र परिषदचे नाव भरा",
    enterArea: "कृपया क्षेत्राचे नाव भरा ",
    enterRoadName: "कृपया रस्त्याचे नाव भरा ",
    enterLandmark: "कृपया  महत्त्वाची खूण भरा",
    enterCity: "कृपया  शहराचे / गावाचे नाव भरा ",
    enterPinCode: "कृपया पिनकोड भरा",
    enterPhoneNo: "कृपया दूरध्वनी नं. भरा",
    enterMobileNo: "कृपया मोबाईल नं. भरा",
    enterEmailAddress: "कृपया इलेक्ट्रॉनिक संदेश भरा",
    enteraadhaarNo: "कृपया आधार नं. भरा",
    enterpanNo: "कृपया पॅन नं. भरा",
    // enterRemarks: 'कृपया टिप्पणी. भरा',
    enterRemarks: "कृपया टिप्पणी. द्या",

    //buttons
    add: "जोडा",
    save: "जतन करा",
    update: "अद्यायावत करा",
    clear: "रिक्त",
    exit: "बाहेर पडा",
    back: "मागे",
    saveAndNext: "जतन करा आणि पुढे",
    finish: "समाप्त",
    hutPrefix: "झोपडी उपसर्ग",
    zoneKey: "झोन",
    hutNo: "झोपडी क्र",
    download: "डाउनलोड करा",
    downloadPhotopass: "फोटोपास डाउनलोड करा",
    print: "प्रत",

    slumKey: "झोपडपट्टी",
    areaOfHut: "चौरस फूट झोपडीचे क्षेत्र(अंदाजे)",
    ownershipKey: "मालकी",

    constructionTypeKey: "बांधकाम प्रकार",
    usageTypeKey: "वापराचा प्रकार",
    usageSubTypeKey: "वापर उपप्रकार",
    length: "लांबी",
    breadth: "रुंदी",
    height: "उंची",
    partNoInList: "यादीतील भाग क्र",
    rehabilitation: "पुनर्वसन",
    eligibility: "पात्रता",
    waterConnection: "पाणी जोडणी",
    noOfFloors: "एकूण क्र. पैकी मजले (जी +)",
    maleCount: "पुरुष संख्या ",
    femaleCount: "महिलांची संख्या",
    totalFamilyMembers: "एकूण कुटुंब सदस्य",
    areaKey: "क्षेत्र",
    villageKey: "गावाचे नाव",
    cityKey: "शहराचे नाव",
    pincode: "पिन कोड",
    lattitude: "अक्षांश",
    longitude: "रेखांश",
    assemblyConstituency: "विधानसभा मतदारसंघाचे नाव",
    correction: "दुरुस्ती",
    remarks: "शेरा",

    applicationNo: "अर्ज क्रमांक",
    applicationDate: "अर्जाची तारीख",
    hutNo: "झोपडी क्रमांक",
    firstName: "पहिले नाव",
    middleName: "मधले नाव",
    lastName: "शेवटचे नाव",
    photo: "चित्र",
    mobileNo: "मोबाईल क्रमांक",
    aadharNo: "आधार क्रमांक",
    emailId: "इमेल पत्ता",
    slumName: "झोपडपट्टीचे नाव",
    area: "क्षेत्र",
    village: "गाव",
    city: "शहर",
    pincode: "पिनकोड",
    lattitude: "अक्षांश",
    longitude: "रेखांश",
    title: "शीर्षक",
    noOfCopies: "प्रतींची संख्या",
    asOnDate: "तारखेप्रमाणे",
    feesApplicable: "शुल्क लागू",
    details: "तपशील",
    outstandingTaxesAmount: "थकबाकी कराची रक्कम",
    addApplicant: "अर्जदार जोडा",
    fullName: "पूर्ण नाव",

    save: "जतन करा",
    clear: "रिक्त",
    exit: "बाहेर पडा",
    search: "शोधा",

    srNo: "अ.क्र.",
    action: "क्रिया",

    //issuance of Photopass

    insuranceOfPhotopass: "फोटोपास जारी करणे",
    searchSlumDetails: "झोपडी तपशील शोधा",

    //aknowledgement

    pimpariChinchwadMaha: "पिंपरी चिंचवड महानगरपालिका",
    appAcknowldgement: "पोच पावती",
    ackDear: "प्रिय",
    ackpcmcthanku: "पिंपरी चिंचवड नागरिक सेवा वापरल्याबद्दल धन्यवाद !!",

    ackshortDesc:
      "पिंपरी चिंचवड महापालिकेअंतर्गत येणाऱ्या नागरिक सेवा अंतर्गत फोटोपास जारी करण्यासाठी तुमचा अर्ज यशस्वीरीत्या सादर झाला आहे.",
    ackHutTransferShortDesc:
      "पिंपरी चिंचवड महापालिकेअंतर्गत येणाऱ्या नागरिक सेवा अंतर्गत झोपडी हस्तांतरणासाठी तुमचा अर्ज यशस्वीरीत्या सादर झाला आहे.",
    ackApplicationSummery: "अर्जाचा तपशील",
    applicationNo: "अर्जाचा क्रमांक",
    dateofApplication: "अर्ज दिनांक",
    ackplzContactNearestOperator:
      "कोणत्याही प्रश्नासाठी कृपया तुमच्या जवळच्या ऑपरेटरशी संपर्क साधा खालील संपर्क तपशील:",
    ackpcmcAddress: "मुंबई पुणे महामार्ग पिंपरी पुणे ४११ ०१८",
    ackPcmcphNo: "फोन क्रमांक:९१-०२०-२७४२-५५११/१२/१३/१४",
    ackstateCountry: "महाराष्ट्र, भारत",
    applicantAddress: "अर्जदाराचा पत्ता :",

    no1: "१)",
    no2: "२)",
    chargeNm: "शुल्काचे नाव",
    loiNo: "हेतू पत्र क्र",
    photopassApplicationAmt:
      "तुमच्याकडे  या सेवेसाठी नागरिक सेवा पोर्टलवर कृपया तुमची रक्कम रुपये",
    determineandPayAmt: "निश्चित करा आणि केलेल्या सेवेची रक्कम/शुल्क भरा.",
    contactNearestpcmcDivisionalOffice:
      "किंवा जवळील पिंपरी चिंचवड महानगरपलिका विभागीय कार्यालयाला भेट द्या.",
    departmentKey: "विभाग",
    hutTransferAmt:
      "सिटीझन सेवा पोर्टलवर झोपडीच्या हस्तांतरणासाठी कृपया तुमची रक्कम रु",
    nocApplicationAmt:
      "सिटीझन सेवा पोर्टलवर तुमची एनओसी जारी करण्यासाठी कृपया तुमची रक्कम रु",
    saveAsDraft: "मसुदा म्हणून जतन करा",
    currentStatus: "वर्तमान स्थिती",

    helpDeskOfSlum: "झोपडपट्टीचे हेल्प डेस्क",
    applicationName: "अर्जाचे नाव",
    hutTransferDetails: "झोपडी हस्तांतरण तपशील",
    fileNm: "फाईलचे नाव",
    fileType: "दस्तवेजाचा प्रकार",
    saveAsDraft: "मसुदा म्हणून सेव्ह केला",
    revertByClerk: "लिपिकाद्वारे परत करा",
    waitingForSiteVisit: "साइट भेटीची वाट पाहत आहे",
    revertByHeadClerk: "हेड क्लार्कने पूर्ववत केले",
    photoPassWaitForClerk: "लिपिकाची वाट पाहत फोटोपास",
    waitForClerk: "हेड क्लर्कची वाट पाहत आहे",
    revertBySuperintendant: "कार्यालय-अधीक्षकाद्वारे पूर्ववत केले",
    waitForSuperintendant: "कार्यालय-अधीक्षकाची वाट पाहत आहे",
    revertByAdminOfficer: "प्रशासकीय-अधिकाऱ्याने परत केले",
    waitForAdminOfficer: "प्रशासकीय-अधिकाऱ्याची प्रतीक्षा  ",
    revertForAssComm: "सहाय्यक-आयुक्तांद्वारे परत करा",
    waitForAssComm: "सहाय्यक-आयुक्तांची प्रतीक्षा आहे",
    sendForAssComm: "सहाय्यक आयुक्तांकडे परत पाठवा",
    loiGenerated: "हेतू पत्र उत्पन्न",
    paymentDone: "पेमेंट झाले",
    siteVisitSch: "साइट भेट शेड्यूल",
    siteVisitDone: "साइट भेट पूर्ण झाली",
    photopassIssued: "फोटोपास जारी केला",
    statusClose: "बंद",
    statusDuplicate: "नक्कल",
    statusRejected: "नाकारले",
    sendBackToCitizenAfterVisit: "साइटला भेट दिल्यानंतर नागरिकांना परत पाठवा",
    sendToClerkAfterVisit: "साइटला भेट दिल्यानंतर लिपिकाकडे पाठवा",
    sendToClerkAfterLoiPay: "लेटर ऑफ इंटेंड पेमेंट नंतर लिपिकाकडे पाठवा",

    // /////////////////////////////// Shubham add by error translation msg /////////////////////////////
    slumFromDate: "पासून तारीख आवश्यक आहे !!!",
    slumToDate: "आजपर्यंत तारीख आवश्यक आहे !!!",
    declarationDateValidation: "घोषणा तारीख आवश्यक आहे !!!",
    ageSlabValidation: "वय स्लॅब आवश्यक आहे !!!",
    ageSlabPrefixValidation: "वय स्लॅब उपसर्ग आवश्यक आहे !!!",
    ageSlabNameValidation: "वय स्लॅब नाव आवश्यक आहे !!!",
    ageSlabNameMrValidation: "वय स्लॅब (मराठी) नाव आवश्यक आहे !!!",
    rangeOfAgeValidation: "वयाची श्रेणी आवश्यक आहे !!!",

    ageSlabNameReqLength: "वय स्लॅब नाव 50 वर्णांपेक्षा जास्त नसावे",
    ageSlabNameMrLength: "वय स्लॅब नाव (मराठी) १०० वर्णांपेक्षा जास्त नसावे",

    ageSlabPrefixLength: "वय स्लॅब उपसर्ग 15 वर्णांपेक्षा जास्त नसावे",

    billingCyclePrefixValidation: " बिलिंग सायकल उपसर्ग आवश्यक आहे !!! ",
    billingCyclePrefixLength: "बिलिंग सायकल उपसर्ग 15 वर्णांपेक्षा जास्त नसावे",
    billingCycleValidation: "बिलिंग सायकल आवश्यक आहे !!!",
    billingCycleReqLength: "बिलिंग सायकल 50 वर्णांपेक्षा जास्त नसावे",
    billingCycleMrValidation: "बिलिंग सायकल (मराठी) आवश्यक आहे !!!",
    billingCycleMrLength: "बिलिंग सायकल (मराठी) १०० वर्णांपेक्षा जास्त नसावे",

    constructionTypePrefixValidation: " बांधकाम प्रकार उपसर्ग आवश्यक आहे !!! ",
    constructionTypePrefixLength:
      "बांधकाम प्रकार उपसर्ग 15 वर्णांपेक्षा जास्त नसावे",
    constructionTypeValidation: "बांधकाम प्रकार आवश्यक आहे !!!",
    constructionTypeReqLength: "बांधकाम प्रकार 50 वर्णांपेक्षा जास्त नसावे",
    constructionTypeMrValidation: "बांधकाम प्रकार (मराठी) आवश्यक आहे !!!",
    constructionTypeMrLength:
      "बांधकाम प्रकार (मराठी) १०० वर्णांपेक्षा जास्त नसावे",

    educationCategoryPrefixValidation: "शिक्षण श्रेणी उपसर्ग आवश्यक आहे !!! ",
    educationCategoryPrefixLength:
      "शिक्षण श्रेणी उपसर्ग 15 वर्णांपेक्षा जास्त नसावे",
    educationCategoryValidation: "शिक्षण श्रेणी आवश्यक आहे !!!",
    educationCategoryReqLength: "शिक्षण श्रेणी 50 वर्णांपेक्षा जास्त नसावे",
    educationCategoryMrValidation: "शिक्षण श्रेणी (मराठी) आवश्यक आहे !!!",
    educationCategoryMrLength:
      "शिक्षण श्रेणी (मराठी) १०० वर्णांपेक्षा जास्त नसावे",

    streamValidation: "प्रवाह आवश्यक आहे !!!",
    stdValidation: "इयत्ता आवश्यक आहे !!!",

    factorPrefixValidation: "घटक नाव उपसर्ग आवश्यक आहे !!! ",
    factorPrefixLength: "घटक नाव उपसर्ग 15 वर्णांपेक्षा जास्त नसावे",
    factorNameValidation: "घटक नाव आवश्यक आहे !!!",
    factorNameReqLength: "घटक नाव 50 वर्णांपेक्षा जास्त नसावे",
    factorNameMrValidation: "घटक नाव (मराठी) आवश्यक आहे !!!",
    factorNameMrLength: "घटक नाव (मराठी) १०० वर्णांपेक्षा जास्त नसावे",
    applicableOnValidation: "वर लागू आवश्यक आहे !!!",

    setForValidation: "च्यासाठी ठेवा आवश्यक आहे !!! ",
    setForReqLength: "च्यासाठी ठेवा 50 वर्णांपेक्षा जास्त नसावे",
    flagNameValidation: "ध्वज नाव आवश्यक आहे !!!",
    flagNameReqLength: "ध्वज नाव 50 वर्णांपेक्षा जास्त नसावे",
    flagNameMrValidation: "ध्वज नाव (मराठी) आवश्यक आहे !!!",
    flagNameMrLength: "ध्वज नाव (मराठी) १०० वर्णांपेक्षा जास्त नसावे",

    zoneKeyValidation: "झोनचे नाव आवश्यक आहे !!!",
    clusterKeyValidation: "समुहचे नाव आवश्यक आहे",
    wardKeyValidation: "प्रभागाचे नाव आवश्यक आहे",
    hutPrefixValidation: "झोपडी उपसर्ग आवश्यक आहे !!!d ",
    hutPrefixLength: "झोपडी उपसर्ग 15 वर्णांपेक्षा जास्त नसावे",

    hutNoValidation: "झोपडी क्र आवश्यक आहे !!!",
    slumKeyValidation: "झोपडपट्टी आवश्यक आहे !!!",
    areaOfHutValidation: "चौरस फूट झोपडीचे क्षेत्र(अंदाजे) आवश्यक आहे !!!",
    ownershipKeyValidation: "मालकी आवश्यक आहे !!!",
    constructionTypeKeyValidation: "बांधकाम प्रकार आवश्यक आहे !!!",
    usageTypeKeyValidation: "वापराचा प्रकार आवश्यक आहे !!!",
    usageSubTypeKeyValidation: "वापर उपप्रकार आवश्यक आहे !!!",
    lengthValidation: "लांबी आवश्यक आहे !!!",
    breadthValidation: " रुंदी आवश्यक आहे !!!",
    heightValidation: "उंची आवश्यक आहे !!!",
    partNoInListValidation: "यादीतील भाग क्र.आवश्यक आहे !!!",
    noOfFloorsValidation: "एकूण क्र. पैकी मजले (जी +) आवश्यक आहे !!!",
    maleCountValidation: "पुरुष संख्या आवश्यक आहे !!!",
    femaleCountValidation: "महिलांची संख्या आवश्यक आहे !!!",
    totalFamilyMembersValidation: "एकूण कुटुंब सदस्य आवश्यक आहे !!!",
    areaKeyValidation: "क्षेत्र आवश्यक आहे !!!",
    villageKeyValidation: "गावाचे नाव आवश्यक आहे !!!",
    cityKeyValidation: "शहराचे नाव आवश्यक आहे !!!",
    pinCodeValidtion: "पिन कोड आवश्यक आहे !!!",
    pinCodeValidtionLength: "पिनकोड 6 वर्णांपेक्षा जास्त नसावा",
    pinCodeValidtionMinLength: "पिनकोड 6 क्रमांकाचा असावा",
    assemblyConstituencyValidation: "विधानसभा मतदारसंघाचे नाव आवश्यक आहे !!!",
    correctionValidation: "दुरुस्ती आवश्यक आहे !!!",

    ownershipTypePrefixValidation: "मालकी प्रकार उपसर्ग आवश्यक आहे !!! ",
    ownershipTypePrefixLength:
      "मालकी प्रकार उपसर्ग 15 वर्णांपेक्षा जास्त नसावे",
    ownershipTypeValidation: "मालकी प्रकार आवश्यक आहे !!!",
    ownershipTypeReqLength: "मालकी प्रकार 50 वर्णांपेक्षा जास्त नसावे",
    ownershipTypeMrValidation: "मालकी प्रकार (मराठी) आवश्यक आहे !!!",
    ownershipTypeMrLength: "मालकी प्रकार (मराठी) १०० वर्णांपेक्षा जास्त नसावे",

    slumPrefixValidation: "झोपडपट्टी उपसर्ग आवश्यक आहे !!!",
    slumPrefixLength: "झोपडपट्टी उपसर्ग 15 वर्णांपेक्षा जास्त नसावे",
    slumNameValidation: "झोपडपट्टी नाव आवश्यक आहे !!!",
    slumNameReqLength: "झोपडपट्टी नाव 50 वर्णांपेक्षा जास्त नसावे",
    slumNameMrValidation: "झोपडपट्टी नाव (मराठी) आवश्यक आहे !!! ",
    slumNameMrLength: "झोपडपट्टी नाव (मराठी) १०० वर्णांपेक्षा जास्त नसावे",
    areaOfSlumValidation: "झोपडपट्टीचा परिसर आवश्यक आहे !!!",
    declarationOrderValidation: "घोषणा आदेश आवश्यक आहे !!!",
    noOfHutsValidation: "झोपड्यांची संख्या आवश्यक आहे !!!",
    hutOccupiedAreaValidation: "झोपडी व्यापलेले क्षेत्र आवश्यक आहे !!!",
    totalPopulationValidation: "लोकसंख्या आवश्यक आहे !!!",
    malePopulationValidation: "पुरुष लोकसंख्या आवश्यक आहे !!!",
    femalePopulationValidation: "महिला लोकसंख्या आवश्यक आहे !!!",
    scPopulationValidation: "SC लोकसंख्या आवश्यक आहे !!!",
    stPopulationValidation: "ST लोकसंख्या आवश्यक आहे !!!",
    otherPopulationValidation: "इतर लोकसंख्या आवश्यक आहे  !!!",

    slumBoundaryInfoValidation: "झोपडपट्टीची माहिती आवश्यक आहे !!!",
    slumStatusValidation: "झोपडपट्टीची स्थिती आवश्यक आहे !!!",
    citySurveyNoValidationL: "शहर सर्वेक्षण क्र आवश्यक आहे !!!",
    surveyNoValidationL: "सर्वेक्षण क्र आवश्यक आहे !!!",
    declarationOrderNoValidation: "घोषणा आदेश क्रमांक आवश्यक आहे !!!",

    subUsageTypePrefixValidation: "उप वापर प्रकार उपसर्ग आवश्यक आहे !!! ",
    subUsageTypePrefixLength:
      "उप वापर प्रकार उपसर्ग 15 वर्णांपेक्षा जास्त नसावे",
    subUsageTypeValidation: "उप वापर प्रकार आवश्यक आहे !!!",
    subUsageTypeReqLength: "उप वापर प्रकार 50 वर्णांपेक्षा जास्त नसावे",
    subUsageTypeMrValidation: "उप वापर प्रकार (मराठी) आवश्यक आहे !!!",
    subUsageTypeMrLength: "उप वापर प्रकार (मराठी) १०० वर्णांपेक्षा जास्त नसावे",

    usageTypePrefixValidation: "वापर प्रकार उपसर्ग आवश्यक आहे !!! ",
    usageTypePrefixLength: "वापर प्रकार उपसर्ग 15 वर्णांपेक्षा जास्त नसावे",
    usageTypeValidation: "वापर प्रकार आवश्यक आहे !!!",
    usageTypeReqLength: "वापर प्रकार 50 वर्णांपेक्षा जास्त नसावे",
    usageTypeMrValidation: "वापर प्रकार (मराठी) आवश्यक आहे !!!",
    usageTypeMrLength: "वापर प्रकार (मराठी) १०० वर्णांपेक्षा जास्त नसावे",

    asOnDateValidation: "तारखेप्रमाणे आवश्यक आहे !!!",
    applicantTitleValidation: "शीर्षक आवश्यक आहे !!!",
    noOfCopiesValidation: "प्रतींची संख्या आवश्यक आहे !!!",
    applicantFirstNameValidation: "अर्जदाराचे नाव आवश्यक आहे !!!",
    titleValidation: "शीर्षक आवश्यक आहे !!!",
    revertSection: "पूर्ववत विभाग",
    revertedRemark: "पूर्ववत टिप्पणी",
    accept: "स्वीकारा",
    revert: "पूर्वस्थितीवर येणे",
    isRescheduled: "पुन्हा शेड्यूल करू इच्छिता?",
    applicantFirstNameValidationLength:
      "अर्जदाराचे नाव ५० वर्णांपेक्षा जास्त नसावे",
    applicantFirstNameMrValidation: "अर्जदाराचे (मराठी) नाव आवश्यक आहे !!!",
    applicantFirstNameMrValidationLength:
      "अर्जदाराचे (मराठी) नाव 100 वर्णांपेक्षा जास्त नसावे",
    applicantMiddleNameValidation: "अर्जदाराचे वडीलांचे नावं आवश्यक आहे !!!",
    applicantMiddleNameValidationLength:
      "अर्जदाराचे वडीलांचे नावं ५० वर्णांपेक्षा जास्त नसावे",
    applicantMiddleNameMrValidation:
      "अर्जदाराचे वडीलांचे (मराठी) नावं आवश्यक आहे !!!",
    applicantMiddleNameMrValidationLength:
      "अर्जदाराचे वडीलांचे (मराठी) नावं 100 वर्णांपेक्षा जास्त नसावे",
    applicantLastNameValidation: "अर्जदाराचे आडनाव नाव आवश्यक आहे !!!",
    applicantLastNameValidationLength:
      "अर्जदाराचे आडनाव नाव ५० वर्णांपेक्षा जास्त नसावे",
    applicantLastNameMrValidation:
      "अर्जदाराचे आडनाव (मराठी) नाव आवश्यक आहे !!!",
    applicantLastNameMrValidationLength:
      "अर्जदाराचे आडनाव (मराठी) नाव 100 वर्णांपेक्षा जास्त नसावे",
    applicantMobileNoValidation: "मोबाइल नंबर आवश्यक आहे !!!",
    applicantAadharNoValidation: "अर्जदार आधार क्रमांक आवश्यक आहे !!!",
    applicantAadharNoValidationMinLength: "आधार क्रमांक 12 क्रमांकाचा असावा",
    applicantAadharNoValidationLength: "आधार क्रमांक 12 पेक्षा जास्त नसावा",

    aadharNoValidation: "आधार क्रमांक आवश्यक आहे !!!",

    ownerTitleValidation: " शीर्षक आवश्यक आहे !!!",
    ownerFirstNameValidation: "वर्तमान मालकाचे नाव आवश्यक आहे !!!",
    ownerFirstNameValidationLength:
      "वर्तमान मालकाचे नाव ५० वर्णांपेक्षा जास्त नसावे !!!",
    ownerMiddleNameValidation: "वर्तमान मालकाच्या वडिलांचे नाव आवश्यक आहे !!!",
    ownerMiddleNameValidationLength:
      "वर्तमान मालकाच्या वडिलांचे नाव ५० वर्णांपेक्षा जास्त नसावे ",
    ownerLastNameValidation: "वर्तमान मालकाचे आडनाव आवश्यक आहे !!!",
    ownerLastNameValidationLength:
      "वर्तमान मालकाचे आडनाव ५० वर्णांपेक्षा जास्त नसावे",
    ownerMobileNoValidation: "वर्तमान मालकाचा मोबाईल क्र आवश्यक आहे !!!",
    ownerAadharNoValidation: "वर्तमान मालक आधार क्र आवश्यक आहे !!!",
    approvalSection: "मंजूरी विभाग",
    revertedSection: "पूर्ववत विभाग",

    clearkRemarks: "लिपिक टिप्पणी",
    headClerkApprovalRemark: "मुख्य लिपिक टिप्पणी",
    officeSuperintendantApprovalRemark: "कार्यालयीन अधीक्षक टिप्पणी",
    administrativeOfficerApprovalRemark: "प्रशासकीय अधिकारी टिप्पणी",
    assistantCommissionerApprovalRemark: "सहाय्यक आयुक्त टिप्पणी",
    finalApprovedRemark: "अंतिम टिप्पणी",

    feesApplicableValidation: "शुल्क लागू आवश्यक आहे !!!",
    newHutNoValidation: "झोपडी क्र आवश्यक आहे !!!",
    saleValueValidation: "विक्री मूल्य आवश्यक आहे !!!",
    marketValueValidation: "बाजार भाव आवश्यक आहे !!!",
    transferRemarksValidation: "हस्तांतरित टिप्पण्या आवश्यक आहे !!!",
    proposedOwnerTitleValidation: "शीर्षक आवश्यक आहे !!!",
    proposedOwnerFirstNameValidation: "पहिले नाव आवश्यक आहे !!!",
    proposedOwnerFirstNameValidationLength:
      "पहिले नाव ५० वर्णांपेक्षा जास्त नसावे",
    proposedOwnerFirstNameMrValidation: "पहिले नाव आवश्यक आहे !!!",
    proposedOwnerFirstNameMrValidationLength:
      "पहिले नाव (मराठी) नाव 100 वर्णांपेक्षा जास्त नसावे",
    proposedOwnerMiddleNameValidation: "वडीलांचे नावं आवश्यक आहे !!!",
    proposedOwnerMiddleNameValidationLength:
      "वडीलांचे नावं ५० वर्णांपेक्षा जास्त नसावे",
    proposedOwnerMiddleNameMrValidation: "वडीलांचे नावं आवश्यक आहे !!!",
    proposedOwnerMiddleNameMrValidationLength:
      "वडीलांचे नावं (मराठी) नाव 100 वर्णांपेक्षा जास्त नसावे",
    proposedOwnerLastNameValidation: "आडनाव आवश्यक आहे !!!",
    proposedOwnerLastNameValidationLength: "आडनाव ५० वर्णांपेक्षा जास्त नसावे",
    proposedOwnerLastNameMrValidation: "आडनाव आवश्यक आहे !!!",
    proposedOwnerLastNameMrValidationLength:
      "आडनाव (मराठी) नाव 100 वर्णांपेक्षा जास्त नसावे",
    proposedOwnerMobileNoValidation: "मोबाईल क्र  आवश्यक आहे !!!",
    proposedOwnerAadharNoValidation: "आधार क्र आवश्यक आहे !!!",
    proposedOwnerAadharNoValidationMinLength:
      "आधार क्रमांक 12 क्रमांकाचा असावा",
    proposedOwnerAadharNoValidationLength: "आधार क्रमांक 12 पेक्षा जास्त नसावा",
    transferDateValidation: "हस्तांतरित तारीख आवश्यक आहे !!!",
    transferTypeKeyValidation: "हस्तांतरण प्रकार आवश्यक आहे !!!",
    subTransferTypeKeyValidation: "उपहस्तांतरण प्रकार आवश्यक आहे !!!",

    mobileNoValidation: "मोबाईल क्र  आवश्यक आहे !!!",

    spouseOccupationValidation: "व्यवसाय आवश्यक आहे !!!",
    spouseRelationKeyValidation: "नाते आवश्यक आहे !!!",
    emailIdValidation: "इ-मेल आवश्यक आहे !!!",
    emailIdValidtionLength: "ईमेल आयडी 80 वर्णांपेक्षा जास्त नसावा",
    spouseAgeValidation: "वय आवश्यक आहे !!!",
    spouseAgePtvValidation: "वय ही सकारात्मक संख्या असणे आवश्यक आहे !!!",
    spouseAgeIntValidation: "वय पूर्णांक असणे आवश्यक आहे !!!",
    spouseAgeValidationLength:
      "वय १८ वर्षे किंवा त्यापेक्षा जास्त असणे आवश्यक आहे",

    visitTimeValidation: "भेट देण्याची वेळ आवश्यक आहे !!!",
    lattitudeValidation: "अक्षांश आवश्यक आहे !!!",
    longitudeValidation: "रेखांश आवश्यक आहे !!!",
    geocodeValidation: "भौगोलिक कोड आवश्यक आहे !!!",
    scheduleDateTimeValidation: "तारीख-वेळ शेड्यूल आवश्यक आहे !!!",
    downloadNoc: "एनओसी डाउनलोड करा",
    approvalSection: "मंजूरी विभाग",
    clearkRemarks: "लिपिक टिप्पणी",
    headClerkApprovalRemark: "मुख्य लिपिक टिप्पणी",
    officeSuperintendantApprovalRemark: "कार्यालयीन अधीक्षक टिप्पणी",
    administrativeOfficerApprovalRemark: "प्रशासकीय अधिकारी टिप्पणी",
    assistantCommissionerApprovalRemark: "सहाय्यक आयुक्त टिप्पणी",
    finalApprovedRemark: "अंतिम टिप्पणी",
    iagreeForOnlinePay: "मी ऑनलाइन पेमेंटसाठी सहमत आहे",
    acknowledgementNo: "पोच पावती क्रमांक",

    yourPaymentDoneSuccess: " तुमचे पेमेंट यशस्वी झाले!!!",
    paymentFailed: "पेमेंट अयशस्वी !!!",
    orderId: "ऑर्डर आयडी ",
    amountInWord: "शब्दात रक्कम",
    trackingId: "ट्रॅकिंग आयडी",
    bankRefNo: "बँक संदर्भ क्र",
    billingName: "बिलिंग नाव",
    billingAdd: "बिलाचा पत्ता",
    billingCity: "बिलिंग शहर",
    billingZip: "बिलिंग पिन कोड ",
    billingCountry: "बिलिंग देश",
    billingEmail: "बिलिंग ईमेल",
    mobileNo: "मोबाईल क्र",
    transactionDate: "व्यवहाराची तारीख",
    billingState: "बिलिंग राज्य",
    goToList: "सूचीवर जा",
    narration: "विवरण",
    pcmc: "पिंपरी चिंचवड महानगरपालिका",
    fiscalYear: "सन",
    date: "तारीख",
    relatedTo: "विभागाकडून",
    cfcRefNo: "सीएफसी संदर्भ क्रं",
    cfcCounterNo: "सीएफसी काउंटर क्रं",
    receivedFrom: "कोणाकडून",
    rti: "झोपडपट्टी बिलिंग प्रणाली",
    narration: "विवरण",
    applicationServiceReceipt: "अर्ज सेवा शुल्क पावती",
    officeCopy: "कार्यालयाची प्रत",
    customerCopy: "ग्राहकाची प्रत",
    rupees: "रुपये",
    chequeNo: "धनादेश क्रं.",
    chequeDate: "धनादेश क्रं",
    bankName: "बँकेचे नाव",
    referenceNo: "संदर्भ क्रं.",
    details: "तपशील",
    payableAmount: "देय रक्कम",
    receivedAmount: "स्वीकारलेली रक्कम",
    rebateAmount: "सूट/सवलत रक्कम",
    advanceAmount: "आगाऊ रक्कम",
    actualPayableAmount: "एकूण देय रक्कम",
    receiverSignature: "स्वीकारनाऱ्याची स्वाक्षरी",
    printBy: "छापनार्याचे नाव",
    printDateAndTime: "छापतांना तारीख आणि वेळ",
    loiGenerate: "हेतू पत्र उत्पन्न करा",
    serviceCharges: "सेवा शुल्क",

    hutTransferServiceReceipt: "झोपडी हस्तांतरण सेवा शुल्क पावती",
    nocServiceReceipt: "Noc सेवा शुल्क पावती",
    photoPassServiceReceipt: "फोटोपास सेवा शुल्क पावती",
    aadharErrorMsg: "आधार नं आधीच अस्तित्वात आहे !!!",
    OtherPopulation: "इतर लोकसंख्या",

    gisId: "जीआयएस आयडी",
    gisIdReq: "जीआयएस आयडी आवश्यक आहे",
    cluster: "समुह",
    clusterName: "समुहचे नाव",
    clusterNameMr: "समुहचे नाव (मराठी)",
    noDocUpload: "कोणतेही दस्तऐवज अपलोड केलेले नाहीत",
    nameOfScheme: "योजनेचे नाव",
    location: "स्थान",
    flatNo: "फ्लॅट क्र",
    viewDoc: "पहा",
    eligible: "पात्र",
    noteligible: "पात्र नाही",
    makeLoiPayment: "LOI पेमेंट करा",
    serviceAcceptance: "सेवा स्वीकृती पत्र",
    remarkReq: "टिप्पणी आवश्यक आहे",
    fileUpload: "फाइल अपलोड",
    iAgree: "मी सहमत आहे",
  },
};
