export default {
  en: {
    type: 'commonLabels',
    module: 'Sports Portal',
    // dashboard: 'PCMC Dashboard
    dashboard: 'Pimpri-Chinchwad Municipal Corporation Dashboard',
    master: 'Masters',
    transaction: 'Transactions',
    report: 'Reports',
    masterPath: 'Sports Portal / Master',
    transactionPath: 'Sports Portal / Transaction ',
    reportPath: 'Sports Portal / Reports ',
    type: 'master',
    // master: "Masters",
    masterPath: 'Sports Portal/ Master',
    master: 'Masters',
    //breadcrum

    facilityNamePath: 'Sports Portal/ Master/ Facility Name Master',
    venuePath: 'Sports Portal/ Master / Venue Master',
    bookingTimePath: 'Sports Portal/ Master / Booking Time Master',
    facilityTypePath: 'Sports Portal/ Master / Facility Type Master',

    //label title
    facilityNameMaster: 'Facility Sub-Type Master',
    venueMaster: 'Facility Venue Master',
    slotMaster: 'Slot Master',
    bookingTimeMaster: 'Booking Time Slot Master',
    maintenanceAnnouncement: 'Maintenance Announcement',
    facilityTypeMaster: 'Facility Type Master',

    //Facility Name Master
    facilityNameId: 'Facility Name ID',
    facilityTypeId: 'Facility Type ID',
    zone: 'Zone',
    ward: 'Ward',
    venueId: 'Venue ID',
    department: 'Department',
    subDepartment: 'Sub Department',
    member: 'Member',
    facilityType: 'Facility Type',
    typee: 'Type',
    dailyDate: 'Date (Daily Slot)',
    Sections: 'Sections',
    facilityTypeEnglish: 'Facility Type(English)',
    verify: 'Verify',
    selectSlots: 'Select Slots',
    send: 'Send',
    medicalValidityPeriod: 'Medical Certificate Date',
    medicalCertificateNo: 'Medical Certificate No.',
    noOfSections: 'No. Of Sections',
    unit: 'Unit',
    unitEn: 'Unit (English)',
    unitMr: 'Unit (Marathi)',
    typeOfSport: 'Type Of Sport',
    facilityTypeMr: 'Facility Type (Marathi)',
    schoolCollegeAddress: 'School / College Address',
    facilityName: 'Facility Sub-Type Name (English)',
    gisCode: 'GIS Code',
    contactPersonNameMr: 'Contact Person Name (Marathi)',
    sizeOfVenue: 'Size Of Venue',
    remark: 'Remark',
    addressMr: 'Address(Marathi)',
    venueAddressMr: 'Venue Address (in Marathi)',
    venueAddressEn: 'Venue Address (in English)',
    venueVillageEn: 'Venue Village (in English)',
    venueVillageMr: 'Venue Village (in Marathi)',
    contactPersonMobileNo: 'Contact Person Mobile No.',
    contactPersonName: 'Contact Person Name (in English)',
    contactPerson: 'Contact Person Name',
    remarkMr: 'Remark (Marathi)',
    venue: 'Facility Venue',
    date: 'Date',
    name: 'Name',
    fname: 'First Name',
    mname: 'Middle Name',
    lname: 'Last Name',
    fromBookingTime: 'From Booking Time',
    toBookingTime: 'To Booking Time',
    capacity: 'Capacity',

    //other labels

    //Remarks
    venueDetails: 'Venue Details',
    facilityDetails: 'Facility Details',
    applicantTypeMaster: 'Applicant Type Master',
    equipmentMaster: 'Equipment Master',
    unitMaster: 'unit Master',
    durationTypeMaster: 'Duration Type Master',
    chargeTypeMaster: 'Charge Type Master',
    bookingTimeMaster: 'Booking Time Master',
    venueMaster: 'Venue Master',
    rateChargeMaster: 'Rate Charge Master',
    facilityTypeMaster: 'Facility Type Master',
    facilityNameMaster: 'Facility Sub-Type Master',
    facilityNameAndFacilityTypeAndDurationTypeMappingMaster:
      'Facility Name, Facility Type, Duration Type Mapping Master',
    //buttons
    add: 'Add',
    save: 'Save',
    update: 'Update',
    clear: 'Clear',
    exit: 'Exit',
    viewForm: 'View Form',
    viewDocument: 'View Document',
    download: 'Download',
    basicApplicationDetails: 'Basic Application Details',
    applicationHistory: 'Application History',
    time: 'Time',
    sentByUser: 'Sent By User',

    back: 'Back',
    saveAndNext: 'Save & Next',
    finish: 'Finish',

    type: 'transaction',

    transaction: 'Transaction',

    transactionPath: 'Sports Portal / Transactions ',

    //titles
    sportBooking: 'Sport Booking',
    check: 'Check Availability Status ',
    swimmingPool: 'Swimming Pool',

    //breadcrum

    //titles
    bookingDetails: 'Booking Details',
    personalGroupDetails: 'Personal Group Details',
    documentUploadDaily: 'Document Upload ',
    personalDetails: 'Personal Details',
    venueDetails: 'Venue Details',
    sectionDetails: 'Section Details',
    venueInformation: 'Venue Information',
    aadharAuthenticationDetails: 'Aadhar Authentication Details',
    eCSDetails: 'ECS Details',
    paymentDetails: 'Payment Details',
    documentsUpload: 'Upload Documents',

    //other labels
    documentUpload: 'Document Upload',
    bookingDetails: 'Booking Details',
    eCSDetails: 'ECS Details',
    aadharAuthentication: 'Aadhar Authentication',

    fromDate: 'Date(From)',
    maintainanceDate: 'Maintainance Date',
    maintainanceRemark: 'Maintainance Remark',
    facilityAvl: 'Facility Availability',
    formDateTime: 'Form Date Time',
    toDateTime: 'To Date Time',
    toDate: 'Date(To)',
    selectSlot: 'Select Slot',
    availableSlot: 'Available Slot',
    selectMultipleSlots: 'Select Multiple Slots',
    selectSlotsForSendMail: 'Select Slots',
    selectSlotA: 'Available Slot',
    ward: 'Ward',
    subDepartment: 'Sub Department',
    bookingRegistrationId: 'Booking Registration Id',
    applicationDate: 'Application Date',
    applicationTime: 'Application Time',
    bookingType: 'Booking Type',
    durationType: 'Duration Type',
    applicantType: 'Applicant Type',
    noDataAdded: 'No data added',
    equipmentNameEn: 'Equipment Name (English)',
    equipmentNameMr: 'Equipment Name (Marathi)',
    duration: 'Duration',
    noSlotAdded: 'NO SLOT ADDED',
    slotDuration: 'Slot Duration',
    chargeType: 'Charge Type',
    applicantTypeEn: 'Applicant Type (in English)',
    applicantTypeMr: 'Applicant Type (in Marathi)',
    durationTypeEn: 'Duration Type(English)',
    durationTypeMr: 'Duration Type (Marathi)',
    chargeTypeEn: 'Charge Type(English)',
    chargeTypeMr: 'Charge Type (Marathi)',
    zone: 'Zone',
    addMember: 'Add Member',
    delete: 'Delete',
    sportsBookingGroupDetailsDao: 'Group Details',
    addSection: 'Add Section',
    addSlot: 'Add Slot',
    department: 'Department',
    facilityType: 'Facility Type',
    typeOfSports: 'Type Of Sports',
    workAddress: 'Work Address',
    nameOfRecommendingPerson: 'Name of Recommending Person',

    facilityName: 'Facility Sub-Type ',
    facilityNameEn: 'Facility Sub-Type(English)',
    units: 'Units (English)',
    // unitMr: "Units (Marathi)",
    facilityNameMr: 'Facility Sub-Type Name (Marathi)',

    venue: 'Venue',
    venueEN: 'Venue Name (English)',
    venueMr: 'Venue Name (Marathi)',
    sections: 'Available Number of Sections',
    totalGroupMember: 'Total Group Member',
    additionalGroupMember: 'Additional Group Member',
    groupDetails: 'Group Details',
    groupName: 'Group Name',
    title: 'Title',
    firstName: 'First Name',
    middleName: 'Middle Name',
    lastName: 'Last Name',
    gender: 'Gender',
    name: 'Name',
    dateOfBirth: 'Date Of Birth',
    age: 'Age',
    mobileNo: 'Mobile No',
    aadharNo: 'Aadhar No',
    applicantaadharNo: 'Applicant Aadhar Number',
    emailAddress: 'Email Address',
    currentAddress: 'Current Address (English)',
    currentAddressMr: 'Current Address (Marathi)',
    permanentAddress: 'Permanent Address (English) ',
    permanentAddressMarathi: 'Permanent Address(Marathi)',
    cityName: 'City Name',
    cityNameEn: 'City Name (English)',
    cityNameMr: 'City Name (Marathi)',
    // state: "State",
    // state: "राज्य (इंग्लिश ) ",
    state: 'State (English) ',
    stateMr: 'State (Marathi) ',

    // statemr: "राज्य (मराठी)  ",
    Maharashtra: 'Maharashtra',
    pinCode: 'Pin Code',
    bankName: 'Bank Name',
    branchName: 'Branch Name',
    bankAccountHolderName: 'Bank Account Holder Name',
    bankAccountNo: 'Bank Account No',
    confirmBankAccountNo: 'Confirm Bank Account No',
    matchAccNo: 'Account number and confirmation must match',
    ifscCode: 'IFSC Code',
    mandatory: 'Mandatory',

    bankAddress: 'Bank Address',
    aadharCard: 'Aadhar Card',
    companyCard: 'Company Card',
    photo: 'Photo',
    panCard: 'Pan Card',
    medicalCertificate: 'Medical Certificate',
    aadharCertificate: 'Aadhar Card',
    photoCertificate: 'Photo',
    otherDocumentPhoto: 'Other Document Photo',
    checkBox: 'Permanent Address as the Correspondence Address',
    purposeOfBooking: 'Purpose Of Booking',
    bookingPersonDetails: 'Booking Person Details',
    slots: 'Slots',
    availableSlots: 'Available Slots',
    timePeriod: 'Time Period',
    sendOtp: 'SEND OTP',
    attachFile: 'Attach File',
    viewImage: 'VIEW IMAGE',
    srNo: 'Sr. No',
    actions: 'Actions',
    enterRemarkForApplicationEn: 'Enter Remark for Application',
    enterRemarkForApplicationMr: 'Enter Remark for Application (Marathi)',
    depositeCondition:
      'Note: Medical certificate should be authorized by MBBS,MD & MS only',

    fileSizeInstrction: 'file size should not be greater than 10 mb',

    approve: 'Approve',
    reject: 'Reject',
    revert: 'Revert',
    clerkVerification: 'CLERK VERIFICATION',
    sVerification: 'SUPERVISOR VERIFICARION',
    sOVerification: 'VERIFICATION SPORTS_OFFICER',
    aCVerification: 'VERIFICATION ADDITIONAL_COMMISHIONER',
    vCommiCVerification: 'VERIFICATION COMMISHIONER',
    sLetter: 'Sanction Letter ISSUANCE',
    slotDetails: 'Slot Detail',

    loiGeneration: 'LOI GENERATION',
    iCard: 'I-CARD',
    vSportsOfficer: 'VERIFICATION SPORTS_OFFICER',
    Lattitude: 'Lattitude',
    Longitute: 'Longitude',
    Addfile: 'Add File',
    //buttons
    add: 'Add',
    save: 'Save',
    update: 'Update',
    clear: 'Clear',
    exit: 'Exit',
    back: 'Back',
    saveAndNext: 'Save & Next',
    finish: 'Finish',

    type: 'report',

    reports: 'Reports',
    applicationNumber: 'Application Number',
    orderId: 'Order Id',
    applicationStatus: 'Application Status',

    reportsPath: 'Sports Portal / Reports ',

    //validation
    selectWard: 'Please select a ward',
    selectDate: 'Please select a date',
    selectTitle: 'Please select a title',

    enterFName: 'Please enter first name (English)',
    enterMName: 'Please enter middle name (English)',
    enterLName: 'Please enter last name (English)',

    enterFNameMr: 'Please enter first name (Marathi) ',
    enterMNameMr: 'Please enter middle name (Marathi)',
    enterLNameMr: 'Please enter last name (Marathi)',

    enterFlat: 'Please enter Flat/Building No (English) ',
    enterApartment: 'Please enter Apartment Name (English)',
    enterRoadName: 'Please enter Road Name (English)',
    enterLandmark: 'Please enter Landmark (English)',
    enterCity: 'Please enter a City Name / Village Name (English) ',
    // state: "Please enter State (English)",

    enterFlatMr: 'Please enter Flat/Building No (Marathi)',
    enterApartmentMr: 'Please enter Apartment Name (Marathi)',
    enterRoadNameMr: 'Please enter Road Name (Marathi)',
    enterLandmarkMr: 'Please enter Landmark (Marathi)',
    enterCityMr: 'Please enter a City Name / Village Name (Marathi)',
    // stateMr: "Please enter State (Marathi)",

    enterPinCode: 'Please enter a pincode ',
    enterPhoneNo: 'Please enter a phone no. ',
    enterMobileNo: 'Please enter a mobile no. ',
    enterEmailAddress: 'Please enter an e-mail. ',
    enteraadhaarNo: 'Please enter an aadhaar no. ',
    maxNumber: 'Adhar Number not valid on above 12 number',
    minNumber: 'Adhar Number must be at least 12 number',
    maxPin: 'Pincode Number not valid on above 6 number',
    minPin: 'Pincode Number must be at least 6 number',
    cancel: 'Cancel',
    bankNoMsg: 'Bank account number must be exactly 15 digits',
    conformMsg: 'Account number and confirmation must match',
    enterpanNo: 'Please enter an pan no. ',
    enterRemarks: 'Please enter a remark. ',
    enterAge: 'Please enter a Age. ',
    selectGender: 'Please select a Gender ',
    selectReligionby: 'Please select a Religion by Birth',
    selectAdoptionby: 'Please select a Religion by Adoption',
    selectStatusAt: 'Please select a Status at time of marriage',

    //mr
    selectZone: 'Please select a zone',
    VtimePeriod: 'Please select Time Period',
    selectWard: 'Please select a ward',
    selectZone: 'Please select a Zone',
    selectTitle: 'Please select a Title',
    placeMarriage: 'Please enter Place of Marriage (in English)',
    placeMarriageMr: 'Please enter Place of Marriage (in Marathi)',
    birthProf: 'Please select a Date of Birth Proof',
    ResideProof: 'Please select a Residence Proof',
    IdentyProof: 'Please select a ID Proof',
    witnessAddressC: 'Please enter an Address ',
    witnessRelation: 'Please enter an Relation. ',

    EnterDocName: 'Please enter an Document Name ',

    noOfCopies: 'No of Copies',
    charges: 'Total Charges',
    chargeName: 'Charge Name',
    amount: 'Amount',
    totalInWords: 'Total Charges in Words',
    totalCharges: 'Total Charges',
    applicantDetails: 'Applicant Details',
    chargesDetails: 'Charges Details',
    paymentMode: 'Payment Mode',
    paymentDetails: 'Payment Details',
    paymentType: 'Payment Type',
    receiptDate: 'Receipt Date',
    receiptNumber: 'Receipt Number',
    receiptAmount: 'Receipt Amount',
    ddNo: 'Demand Draft Number',
    ddDate: 'Demand Draft Date',
    bankName: 'Bank Name',
    branchName: 'Branch Name',
    bankAccountNo: 'Bank Account No',
    confirmAccountMsg: 'Please confirm your account number',

    //Modification in Marriage Certificate

    onlyMIMC: 'Modification of Marriage Certificate',
    oldLabel: 'Old Information',
    newLabel: 'New Information',
    gDoc: 'Groom Documents',
    bDoc: 'Bride Documents',
    OwnerDetails: ' Owner Details :',
    Owneraddress: ' Owner Address :',
    document: 'Document Tab :',
    boardheadphoto: 'Board Head Person Photo',
    boardorgphotocpy: 'Board / Organization PhotoCopy',
    panCard: 'Pan Card',
    adharcard: 'Aadhaar card',
    rationcard: 'Ration card',
    electrbill: 'Electric Bill',
    OtherDocument: 'Other Document',
    UploadFile: ' Upload File',
    remarkModel: 'Enter Remark on application',
    APPROVE: 'APPROVE',

    REASSIGN: 'Revert Back',
    onlyeng: 'Must be only characters',
    onlymarathi: 'Must be only  marathi',

    Vzone: 'Select Zone',
    VchargeType: ' Please Enter Charge Type (English)',
    VchargeTypeMr: 'Please Enter Charge Type (Marathi)',
    Vcapacity: 'Enter Capacity',
    Vward: 'Select Ward',
    VtypeOfSports: 'Select Type of Sports',
    Vvenue: 'Select Venue',
    Vdate: 'Please Select Date ',
    VtotalGroupMember: 'Enter Group Member',
    VSelectSlot: 'Please Select Slot ',
    VbookingType: 'Select Booking Type',
    VapplicantType: 'Select Applicant Type (English)',
    VType: 'Please Select Type',
    Vunit: 'Select Unit (English)',
    VunitMr: 'Select Unit (Marathi)',
    VapplicantMrType: 'Select Applicant Type (Marathi)',
    VdurationType: 'Select Duration Type',
    VfacilityType: 'Select Facility Type',
    VgisCode: 'Please Enter GIS Code',
    facilityTypeMrMsg: 'Select Facility Type (Marathi)',
    VfacilityName: 'Select Facility Sub-Type Name',
    VfacilityNameMr: 'Select Facility Sub-Type Name (Marathi)',
    Vvenue: 'Select Venue Name',
    VfromDate: 'Select From Date',
    VtoDate: 'Select To Date',
    VmaintainanceDate: 'Select To Maintainance Date',
    Vremark: 'Enter Remark (English)',
    VpurposeOfBooking: 'Select Purpose Of Booking',
    Vcaddres: 'Please enter an current address',
    Vpaddres: 'Please enter an Permanent Address',
    VfromBookingTime: 'Select From Booking Time',
    VselectSlots: 'Please Select Slot',
    VwAddress: 'Please Enter Work Address',

    VtoBookingTime: 'Select To Booking Time',
    VaadharCard: 'Please Upload Aadhar Card',
    VaadharNo: 'Please Enter Aadhar Number',
    VpanCard: 'Please Upload Pan Card',
    Vphoto: 'Please Upload passport Size Photo',
    Vmedical: 'Please Upload Medical Certificate',
    VbankName: 'Select Bank Name',
    VbranchName: 'Please enter an Branch Name',
    VbankAccountHolderName: 'Please enter an Bank Account Holder Name',
    VbankAccountNo: 'Please enter an Bank Account No',
    VifscCode: 'Please enter an IFSC Code',
    VbankAddress: 'Please enter an Bank Address',
    generateLoi: 'Generate LOI',
    pay: 'Pay',
    receiptModeDetails: 'Receipt Mode Details',
    masters: 'Masters',
    transactions: 'Transactions',
    reports: 'Reports',
    receipt: 'Receipts',
    usertask: 'User task',
    serviceName: 'Service Name ',
    masters: 'Masters',
    masterPath: 'FIRE BRIGADE SYSTEM / masters',
    demo: '',
    //mr
    MrMasters: 'Marriage Registration / Masters',
    marriageRegistrationMaritalStatus:
      'Marriage Registration / Masters / Marital Status',

    pay: 'PAY',
    marriageRegistrationrelation: 'Marriage Registration / Masters / relation',
    receiptModeDetails: 'Receipt Mode Details',
    maritialSatus: 'Marital Status',
    relation: 'Relation',

    AptBook: 'Appointment Slot Booking',
    serviceChargeTypeName: 'Service Charge Type Name',

    // field label
    srNo: 'Sr. No',
    actions: 'Actions',
    statusDetails: 'Status Details',

    //buttons
    add: 'Add',
    save: 'Save',
    update: 'Update',
    clear: 'Clear',
    exit: 'exit',

    ward: 'Ward',
    zone: 'Zone',
    latitude: 'Latitude',
    Longitude: 'Longitude',

    documentUpload: 'Documents Upload',
    applicationCreated: 'Application Submitted Successfully',
    addFile: 'Choose File',
    fileName: 'File Name',
    mandatoryOrOptional: 'Mandatory/Optional',
    mandatory: 'Mandatory',
    optional: 'Optional',
    upload: 'Upload',
    next: 'Next',
    preview: 'Preview',
    verify: 'Verify',
    reject: 'Reject',
    noFileFound: 'No file found',
    verified: 'Verified',

    attachFile: 'Attach File',
    srNo: 'Sr. No',
    actions: 'Actions',

    //breadcrum
    landReservationPath: 'Town Planning / Master / Land Reservation ',

    attachFile: 'Attach File',
    srNo: 'Sr. No',
    actions: 'Actions',

    //buttons
    add: 'Add',
    save: 'Save',
    update: 'Update',
    clear: 'Clear',
    exit: 'Exit',
    back: 'Back',
    saveAndNext: 'Save & Next',
    finish: 'Finish',

    //marathi details
    gFNameMr: '',
    gMNameMr: '',
    gLNameMr: '',
    ApplicatCheck1: 'If the Applicant is Groom',
    ApplicatCheck2: 'If the Applicant is Bride',
    OwnerChkeck: 'If the Applicant is Owner',
    transactions: 'Transactions',
    transactionPath: 'Legal Case / Transaction ',

    //mr
    Tnc: 'accept term & Condition',
    // instrustion
    onlyMHR:
      ' Marriages are registered in Maharashtra and either the bride or the groom must be a resident of Pimpri Chinchwad Municipal Corporation limits.',
    docNote:
      'Id proof, Residential proof, Age proof should be different, (Previous Status Proof contain value if Status at the time of marriage is Widow/Widower or Divorce) If Aadhaar card proof is added and citizen A registered agreement is required if living on rent.',
    //table
    newMRtable: 'NEW MARRIAGE REGISTRATION ',
    boardtitle: '  Marriage Board Registration ',
    zone: 'Zone',
    ward: 'Ward',
    Addrees: 'Applicant Address :',
    CrrtAdree: 'Current Address :',
    parmtAdree: 'Permanent Address :',
    personalDetails: 'Personal Information',
    Adress: 'Address  :',
    BriNBM: '  (  Name before marriage)',
    AppliToGroom: 'If the Applicant is Groom ',
    AppliToBride: 'If the Applicant is Bride',
    marrigeDetails: '  Marriage Details :',
    marrigeDate: 'Marriage Date',
    //aprove
    GPhoto: 'Groom Photo  ',
    Bphoto: 'Bride Photo  ',
    witnessphto1: 'Witness 1 Photo  ',
    witnessphto2: 'Witness 2 Photo  ',
    witnessphto3: 'Witness 3 Photo  ',
    Gthumb: 'Groom Thumb  ',
    Bthumb: 'Bride Thumb  ',
    witnessthumb1: 'Witness 1 Thumb  ',
    witnessthumb2: 'Witness 2 Thumb  ',
    witnessthumb3: 'Witness 3 Thumb  ',

    //title
    ApplicatDetails: 'APPLICANT DETAILS',
    ApplicatName: 'Applicant Name',
    groomDetail: 'GROOM DETAILS',
    groomParaentDetail: 'Groom Parents Details ',
    brideDetails: 'BRIDE DETAILS',
    brideParaentDetail: 'Bride Parents Details',
    priestDetails: 'PRIEST DETAILS',
    witness: 'Witness',
    witnessAdd: 'Witness',
    witnessDetails: 'WITNESS DETAILS',
    documentsUpload: 'Upload Documents',
    boardDetail: 'Board Details :',
    otherDetail: 'OTHER DETAILS',
    titleInmarathi: 'Title (Marathi)',
    titleInenglish: 'Title (In english)',

    // viceversa
    titleV: 'शीर्षक',
    firstNameV: 'प्रथम नावं  ',
    middleNameV: 'मधले नावं  ',
    lastNameV: 'आडनाव  ',

    //Groom
    // title: 'Title  ',
    // firstName: 'First Name  ',
    // middleName: 'Middle Name  ',
    // lastName: 'Last Name  ',
    title: 'Title ',
    title1: 'Title ',
    firstName: 'First Name (English) ',
    middleName: 'Middle Name (English) ',
    lastName: 'Last Name (English) ',
    firstNamee: 'First Name',
    middleNamee: 'Middle Name',
    lastNamee: 'Last Name',
    titlemr: 'शीर्षक ',
    firstNamemr: 'First Name (Marathi) ',
    middleNamemr: 'Middle Name (Marathi) ',
    lastNamemr: 'Last Name (Marathi) ',

    BirthDate: 'Birth Date   ',
    Gender: 'Gender',
    AadharNo: 'Aadhar No',
    Age: 'Age (at the time of marriage)',
    mobileNo: 'Mobile / Phone Number',
    phoneNo: 'Phone Number',
    email: 'Email',

    flatBuildingNo: 'Flat/Building No (English)  ',
    buildingName: 'Apartment Name (English) ',
    roadName: 'Road Name (English) ',
    Landmark: 'Landmark (English) ',
    villageName: 'Village Name (English) ',
    cityName: 'City Name / Village Name (English) ',

    flatBuildingNomr: 'Flat/Building No (Marathi) ',
    buildingNamemr: 'Apartment Name (Marathi) ',
    roadNamemr: 'Road Name (Marathi) ',
    Landmarkmr: 'Landmark (Marathi) ',
    villageNamemr: 'Village Name (Marathi) ',
    cityNamemr: 'City Name / Village Name (Marathi) ',

    // State: "State (English) ",
    // statemr: "State (Marathi) ",
    pincode: 'Pin Code',
    Religion1: 'Religion by Birth',
    Religion2: ' Religion by Adoption',
    StatusOfMarrige: ' Status at time of marriage',
    AgeDocument: 'Birth Proof Document',
    IdDocument: 'Id Document',
    residentialDocument: 'Residential Document',
    StatusOfDocument: 'Status Of Document',

    // //groomFather
    // firstNameF: 'Father First Name  ',
    // middleNameF: 'Father Middle Name  ',
    // lastNameF: 'Father Last Name  ',
    // AgeF: 'Father Age',
    // mobileNoF: 'Father Mobile Number',
    // AadharNoF: 'Father Aadhar No',

    // //groomMother
    // firstNameM: 'Mother First Name  ',
    // middleNameM: 'Mother Middle Name  ',
    // lastNameM: 'Mother Last Name  ',
    // AgeM: 'Mother Age',
    // mobileNoM: 'Mother Mobile Number',
    // AadharNoM: 'MotheM Aadhar No',

    //prist
    placeofMarriage: 'Place of Marriage (in English)',
    placeofMarriage1: 'Place of Marriage (in Marathi)',

    //witness
    address: 'Address',
    wRelation: 'Witness Relation',
    wDocument: 'Witness Document',

    //Document

    DBProof: 'Date of Birth Proof',
    ResProof: 'Residence Proof',
    IdProof: 'ID Proof',

    ResProofW1: 'Residence Proof of first witness',
    ResProofW2: 'Residence Proof of second witness',
    ResProofW3: 'Residence Proof of third witness',

    marrigeRelatedDoc: 'Marriage Related Document',

    invetaionCard: 'Marriage Invitation card / affidavit ',
    marrigePhotoC: 'Marriage Photograph (Couple) ',
    marDrf: 'Draft an application on the 100 Rs Stamp paper',

    DivorcePaper: 'Valid Divorce Paper (if applicable)',
    DeathC: 'Death Certificate (if applicable)',
    certiByReligiousPlc:
      ' Certificate issued by religious place i.e Temple, Mosque etc',
    docFormat:
      ' (Only jpg.jpeg.png.bmp.pdf files are allowed to upload. Photo Size max 100 kb)',
    enterDoc: 'Document Name',
    TandC: '',
    //board
    applicantName: 'Applicant Name ',
    boardNameT: 'Marriage Board Name',
    boardName: 'Marriage Board Name (English)  ',
    boardNamemr: 'Marriage Board Name (Marathi)  ',
    remark: 'Remark ',
    documentList: ' Documents List',
    ValidtyofMBR: '  Validity Of MBR',
    documentsUploadF: 'Upload Documents',

    //button
    back: 'Back',
    next: 'Next',
    add: 'Add',
    save: 'Save',
    update: 'Update',
    clear: 'Clear',
    exit: 'exit',
    submit: 'Submit',
    apply: 'Apply',
    addFile: 'Upload File',

    //table filed
    srNo: 'Sr. No',
    ApplicantName: 'Applicant Name',
    hName: 'Groom Name',
    wName: 'Bride Name',
    actions: 'Actions',

    //brudcrum
    newMarriageRegistration:
      'Marriage Registration / New Marriage Registration',
    BoardMarriageRegistration: 'Marriage Registration / New Board Registration',

    //ReIssuance of Marriage Certificate

    onlyRIMC: 'Re-Issuance of Marriage Certificate',
    mRegNo: 'Marriage Reg No',
    marriageDate: 'Marriage Date',
    marriageYear: 'Marriage Year',
    brideName: 'Bride Name',
    groomName: 'Groom Name',
    regDate: 'Registration Date',

    //Renewal of Marriage Board Registration
    onlyRMBR: 'Renewal of Marriage Board Registration',
    mbrName: 'Marriage Board Name',
    mbrDate: 'Marriage Board Reg Date',
    mbrYear: 'Marriage Board Reg Year',
    search: 'Search',

    //Application Details

    onlyApplDetail: 'Application Details',
    applFName: 'Applicant First Name',
    applMName: 'Applicant Middle Name',
    applLName: 'Applicant Last Name',
    groomFName: 'Groom First Name',
    groomMName: 'Groom Middle Name',
    groomLName: 'Groom Last Name',
    brideFName: 'Bride First Name',
    brideMName: 'Bride Middle Name',
    brideLName: 'Bride Last Name',
    mDate: 'Marriage Date',

    //ReIssuance of marriage Certificate
    newRMItable: 'ReIssuance of Marriage Certificate',
    applFullName: 'Applicant Full Name',
    applicationNo: 'Application No',
    generateLoi: 'Generate LOI',

    //Modification in Marriage Board Registration

    onlyMMBR: 'Modification in Marriage Board Registration',
    applicationDate: 'Application Date',
    registerationDate: 'Registeration Date',
    registerationNo: 'Marriage Board Reg Number',
    orgName: 'Organisation Name',

    //Payment Collection
    bankName: 'Bank Name',
    branchName: 'Branch Name',
    ifsc: 'IFSC Code',
    accountNumber: 'Account Number ',
    pay: 'Pay',
    exit: 'Exit',

    //validation
    selectWard: 'Please select a ward',
    selectDate: 'Please select a date',
    selectTitle: 'Please select a title',

    enterFName: 'Please enter first name (English)',
    enterMName: 'Please enter middle name (English)',
    enterLName: 'Please enter last name (English)',

    enterFNameMr: 'Please enter first name (Marathi) ',
    enterMNameMr: 'Please enter middle name (Marathi)',
    enterLNameMr: 'Please enter last name (Marathi)',

    enterFlat: 'Please enter Flat/Building No (English) ',
    enterApartment: 'Please enter Apartment Name (English)',
    enterRoadName: 'Please enter Road Name (English)',
    enterLandmark: 'Please enter Landmark (English)',
    enterCity: 'Please enter a City Name / Village Name (English) ',
    // state: "Please enter State (English)",

    enterFlatMr: 'Please enter Flat/Building No (Marathi)',
    enterApartmentMr: 'Please enter Apartment Name (Marathi)',
    enterRoadNameMr: 'Please enter Road Name (Marathi)',
    enterLandmarkMr: 'Please enter Landmark (Marathi)',
    enterCityMr: 'Please enter a City Name / Village Name (Marathi)',
    // stateMr: "Please enter State (Marathi)",

    enterPinCode: 'Please enter a pincode ',
    enterPhoneNo: 'Please enter a phone no. ',
    enterMobileNo: 'Please enter a mobile no. ',
    enterEmailAddress: 'Please enter an e-mail. ',
    enteraadhaarNo: 'Please enter an aadhaar no. ',
    enterpanNo: 'Please enter an pan no. ',
    enterRemarks: 'Please enter a remark. ',
    enterAge: 'Please enter a Age. ',
    selectGender: 'Please select a Gender ',
    selectReligionby: 'Please select a Religion by Birth',
    selectAdoptionby: 'Please select a Religion by Adoption',
    selectStatusAt: 'Please select a Status at time of marriage',

    //mr
    selectZone: 'Please select a zone',
    selectWard: 'Please select a ward',
    selectZone: 'Please select a Zone',
    selectTitle: 'Please select a Title',
    placeMarriage: 'Please enter Place of Marriage (in English)',
    placeMarriageMr: 'Please enter Place of Marriage (in Marathi)',

    birthProf: 'Please select a Date of Birth Proof',
    ResideProof: 'Please select a Residence Proof',
    IdentyProof: 'Please select a ID Proof',

    witnessAddressC: 'Please enter an Address ',
    witnessRelation: 'Please enter an Relation. ',

    EnterDocName: 'Please enter an Document Name ',

    noOfCopies: 'No of Copies',
    charges: 'Total Charges',
    chargeName: 'Charge Name',
    amount: 'Amount',
    totalInWords: 'Total Charges in Words',
    totalCharges: 'Total Charges',
    applicantDetails: 'Applicant Details',
    chargesDetails: 'Charges Details',
    paymentMode: 'Payment Mode',
    paymentType: 'Payment Type',
    receiptDate: 'Receipt Date',
    receiptNumber: 'Receipt Number',
    receiptAmount: 'Receipt Amount',
    ddNo: 'Demand Draft Number',
    ddDate: 'Demand Draft Date',
    bankName: 'Bank Name',
    branchName: 'Branch Name',
    bankAccountNo: 'Bank Account No',

    //Modification in Marriage Certificate

    onlyMIMC: 'Modification of Marriage Certificate',
    oldLabel: 'Old Information',
    newLabel: 'New Information',
    gDoc: 'Groom Documents',
    bDoc: 'Bride Documents',
    OwnerDetails: ' Owner Details :',
    Owneraddress: ' Owner Address :',
    document: 'Document Tab :',
    boardheadphoto: 'Board Head Person Photo',
    boardorgphotocpy: 'Board / Organization PhotoCopy',
    panCard: 'Pan Card',
    adharcard: 'Aadhaar card',
    rationcard: 'Ration card',
    electrbill: 'Electric Bill',
    OtherDocument: 'Other Document',
    UploadFile: ' Upload File',
    remarkModel: 'Enter Remark on application',
    APPROVE: 'APPROVE',

    REASSIGN: 'Revert Back',
    onlyeng: 'Must be only characters',
    onlymarathi: 'Must be only  marathi',

    //validation file upload
    birthProfV: 'Please Upload a Date of Birth Proof',
    ResideProofV: 'Please Upload a Residence Proof',
    IdentyProofV: 'Please Upload a ID Proof',

    invetaionCardV: 'Please Upload a Marriage Invitation card / affidavit ',
    marrigePhotoCV: 'Please Upload a Marriage Photograph (Couple) ',
    marDrfV: 'Please Upload a Draft an application on the 100 Rs Stamp paper',
    boardheadphotoV: 'Please Upload a Board Head Person Photo',
    boardorgphotocpyV: 'Please Upload a Board / Organization PhotoCopy',
    panCardV: 'Please Upload a Pan Card',
    adharcardV: 'Please Upload a Aadhaar card',
    masters: 'Masters',
    transactions: 'Transactions',
    reports: 'Reports',
    receipt: 'Receipts',
    usertask: 'User task',
    serviceName: 'Service Name ',
    masters: 'Masters',
    masterPath: 'FIRE BRIGADE SYSTEM / masters',
    demo: '',
    //mr
    MrMasters: 'Marriage Registration / Masters',
    marriageRegistrationMaritalStatus:
      'Marriage Registration / Masters / Marital Status',

    pay: 'PAY',
    marriageRegistrationrelation: 'Marriage Registration / Masters / relation',
    receiptModeDetails: 'Receipt Mode Details',
    maritialSatus: 'Marital Status',
    relation: 'Relation',

    AptBook: 'Appointment Slot Booking',
    serviceChargeTypeName: 'Service Charge Type Name',

    // field label
    srNo: 'Sr. No',
    actions: 'Actions',
    statusDetails: 'Status Details',

    //buttons
    add: 'Add',
    save: 'Save',
    update: 'Update',
    clear: 'Clear',
    exit: 'exit',

    ward: 'Ward',
    zone: 'Zone',
    latitude: 'Latitude',
    Longitude: 'Longitude',

    documentUpload: 'Documents Upload',
    applicationCreated: 'Application Submitted Successfully',
    addFile: 'Choose File',
    fileName: 'File Name',
    mandatoryOrOptional: 'Mandatory/Optional',
    mandatory: 'Mandatory',
    optional: 'Optional',
    upload: 'Upload',
    next: 'Next',
    preview: 'Preview',
    verify: 'Verify',
    reject: 'Reject',
    noFileFound: 'No file found',
    verified: 'Verified',

    attachFile: 'Attach File',
    srNo: 'Sr. No',
    actions: 'Actions',

    //breadcrum
    landReservationPath: 'Town Planning / Master / Land Reservation ',

    attachFile: 'Attach File',
    srNo: 'Sr. No',
    actions: 'Actions',

    //buttons
    add: 'Add',
    save: 'Save',
    update: 'Update',
    clear: 'Clear',
    exit: 'Exit',
    back: 'Back',
    saveAndNext: 'Save & Next',
    finish: 'Finish',

    //marathi details
    gFNameMr: '',
    gMNameMr: '',
    gLNameMr: '',
    ApplicatCheck1: 'If the Applicant is Groom',
    ApplicatCheck2: 'If the Applicant is Bride',
    OwnerChkeck: 'If the Applicant is Owner',
    transactions: 'Transactions',
    transactionPath: 'Legal Case / Transaction ',

    //mr
    Tnc: 'accept term & Condition',
    // instrustion
    onlyMHR:
      ' Marriages are registered in Maharashtra and either the bride or the groom must be a resident of Pimpri Chinchwad Municipal Corporation limits.',
    docNote:
      'Id proof, Residential proof, Age proof should be different, (Previous Status Proof contain value if Status at the time of marriage is Widow/Widower or Divorce) If Aadhaar card proof is added and citizen A registered agreement is required if living on rent.',
    //table
    newMRtable: 'NEW MARRIAGE REGISTRATION ',
    boardtitle: '  Marriage Board Registration ',
    zone: 'Zone',
    ward: 'Ward',
    Addrees: 'Applicant Address :',
    CrrtAdree: 'Current Address :',
    parmtAdree: 'Permanent Address :',
    personalDetails: 'Personal Information ',
    Adress: 'Address  :',
    BriNBM: '  (  Name before marriage)',
    AppliToGroom: 'If the Applicant is Groom ',
    AppliToBride: 'If the Applicant is Bride',
    marrigeDetails: '  Marriage Details :',
    marrigeDate: 'Marriage Date',
    //aprove
    GPhoto: 'Groom Photo  ',
    Bphoto: 'Bride Photo  ',
    witnessphto1: 'Witness 1 Photo  ',
    witnessphto2: 'Witness 2 Photo  ',
    witnessphto3: 'Witness 3 Photo  ',
    Gthumb: 'Groom Thumb  ',
    Bthumb: 'Bride Thumb  ',
    witnessthumb1: 'Witness 1 Thumb  ',
    witnessthumb2: 'Witness 2 Thumb  ',
    witnessthumb3: 'Witness 3 Thumb  ',

    //title
    ApplicatDetails: 'APPLICANT DETAILS',
    ApplicatName: 'Applicant Name',
    groomDetail: 'GROOM DETAILS',
    groomParaentDetail: 'Groom Parents Details ',
    brideDetails: 'BRIDE DETAILS',
    brideParaentDetail: 'Bride Parents Details',
    priestDetails: 'PRIEST DETAILS',
    witness: 'Witness',
    witnessAdd: 'Witness',
    witnessDetails: 'WITNESS DETAILS',
    documentsUpload: 'Upload Documents',
    boardDetail: 'Board Details :',
    otherDetail: 'OTHER DETAILS',
    titleInmarathi: 'Title (Marathi)',
    titleInenglish: 'Title (In english)',

    // viceversa
    titleV: 'शीर्षक',
    firstNameV: 'प्रथम नावं  ',
    middleNameV: 'मधले नावं  ',
    lastNameV: 'आडनाव  ',

    //Groom
    // title: 'Title  ',
    // firstName: 'First Name  ',
    // middleName: 'Middle Name  ',
    // lastName: 'Last Name  ',
    title: 'Title ',
    title1: 'Title ',
    firstName: 'First Name (English) ',
    middleName: 'Middle Name (English) ',
    lastName: 'Last Name (English) ',
    titlemr: 'शीर्षक ',
    firstNamemr: 'First Name (Marathi) ',
    middleNamemr: 'Middle Name (Marathi) ',
    lastNamemr: 'Last Name (Marathi) ',

    BirthDate: 'Birth Date   ',
    Gender: 'Gender',
    AadharNo: 'Aadhar No',
    Age: 'Age (at the time of marriage)',
    mobileNo: 'Mobile / Phone Number',
    phoneNo: 'Phone Number',
    email: 'Email',

    flatBuildingNo: 'Flat/Building No (English)  ',
    buildingName: 'Apartment Name (English) ',
    roadName: 'Road Name (English) ',
    Landmark: 'Landmark (English) ',
    villageName: 'Village Name (English) ',
    cityName: 'City Name / Village Name (English) ',

    flatBuildingNomr: 'Flat/Building No (Marathi) ',
    buildingNamemr: 'Apartment Name (Marathi) ',
    roadNamemr: 'Road Name (Marathi) ',
    Landmarkmr: 'Landmark (Marathi) ',
    villageNamemr: 'Village Name (Marathi) ',
    cityNamemr: 'City Name / Village Name (Marathi) ',

    // State: "State (English) ",
    // statemr: "State (Marathi) ",
    pincode: 'Pin Code',
    Religion1: 'Religion by Birth',
    Religion2: ' Religion by Adoption',
    StatusOfMarrige: ' Status at time of marriage',
    AgeDocument: 'Birth Proof Document',
    IdDocument: 'Id Document',
    residentialDocument: 'Residential Document',
    StatusOfDocument: 'Status Of Document',

    // //groomFather
    // firstNameF: 'Father First Name  ',
    // middleNameF: 'Father Middle Name  ',
    // lastNameF: 'Father Last Name  ',
    // AgeF: 'Father Age',
    // mobileNoF: 'Father Mobile Number',
    // AadharNoF: 'Father Aadhar No',

    // //groomMother
    // firstNameM: 'Mother First Name  ',
    // middleNameM: 'Mother Middle Name  ',
    // lastNameM: 'Mother Last Name  ',
    // AgeM: 'Mother Age',
    // mobileNoM: 'Mother Mobile Number',
    // AadharNoM: 'MotheM Aadhar No',

    //prist
    placeofMarriage: 'Place of Marriage (in English)',
    placeofMarriage1: 'Place of Marriage (in Marathi)',

    //witness
    address: 'Address',
    wRelation: 'Witness Relation',
    wDocument: 'Witness Document',

    //Document

    DBProof: 'Date of Birth Proof',
    ResProof: 'Residence Proof',
    IdProof: 'ID Proof',

    ResProofW1: 'Residence Proof of first witness',
    ResProofW2: 'Residence Proof of second witness',
    ResProofW3: 'Residence Proof of third witness',

    marrigeRelatedDoc: 'Marriage Related Document',

    invetaionCard: 'Marriage Invitation card / affidavit ',
    marrigePhotoC: 'Marriage Photograph (Couple) ',
    marDrf: 'Draft an application on the 100 Rs Stamp paper',

    DivorcePaper: 'Valid Divorce Paper (if applicable)',
    DeathC: 'Death Certificate (if applicable)',
    certiByReligiousPlc:
      ' Certificate issued by religious place i.e Temple, Mosque etc',
    docFormat:
      ' (Only jpg.jpeg.png.bmp.pdf files are allowed to upload. Photo Size max 100 kb)',
    enterDoc: 'Document Name',
    TandC: '',
    //board
    applicantName: 'Applicant Name ',
    boardNameT: 'Marriage Board Name',
    boardName: 'Marriage Board Name (English)  ',
    boardNamemr: 'Marriage Board Name (Marathi)  ',
    // remark: "Remarks",
    documentList: ' Documents List',
    ValidtyofMBR: '  Validity Of MBR',
    documentsUploadF: 'Upload Documents',

    //button
    back: 'Back',
    next: 'Next',
    add: 'Add',
    save: 'Save',
    update: 'Update',
    clear: 'Clear',
    exit: 'exit',
    submit: 'Submit',
    apply: 'Apply',
    addFile: 'Upload File',

    //table filed
    srNo: 'Sr. No',
    ApplicantName: 'Applicant Name',
    hName: 'Groom Name',
    wName: 'Bride Name',
    actions: 'Actions',

    //brudcrum
    newMarriageRegistration:
      'Marriage Registration / New Marriage Registration',
    BoardMarriageRegistration: 'Marriage Registration / New Board Registration',

    //ReIssuance of Marriage Certificate

    onlyRIMC: 'Re-Issuance of Marriage Certificate',
    mRegNo: 'Marriage Reg No',
    marriageDate: 'Marriage Date',
    marriageYear: 'Marriage Year',
    brideName: 'Bride Name',
    groomName: 'Groom Name',
    regDate: 'Registration Date',

    //Renewal of Marriage Board Registration
    onlyRMBR: 'Renewal of Marriage Board Registration',
    mbrName: 'Marriage Board Name',
    mbrDate: 'Marriage Board Reg Date',
    mbrYear: 'Marriage Board Reg Year',
    search: 'Search',

    //Application Details

    onlyApplDetail: 'Application Details',
    applFName: 'Applicant First Name',
    applMName: 'Applicant Middle Name',
    applLName: 'Applicant Last Name',
    groomFName: 'Groom First Name',
    groomMName: 'Groom Middle Name',
    groomLName: 'Groom Last Name',
    brideFName: 'Bride First Name',
    brideMName: 'Bride Middle Name',
    brideLName: 'Bride Last Name',
    mDate: 'Marriage Date',

    //ReIssuance of marriage Certificate
    newRMItable: 'ReIssuance of Marriage Certificate',
    applFullName: 'Applicant Full Name',
    applicationNo: 'Application No',
    generateLoi: 'Generate LOI',

    //Modification in Marriage Board Registration

    onlyMMBR: 'Modification in Marriage Board Registration',
    applicationDate: 'Application Date',
    registerationDate: 'Registeration Date',
    registerationNo: 'Marriage Board Reg Number',
    orgName: 'Organisation Name',

    //Payment Collection
    bankName: 'Bank Name',
    branchName: 'Branch Name',
    ifsc: 'IFSC Code',
    accountNumber: 'Account Number ',
    pay: 'Pay',
    exit: 'Exit',

    //validation
    selectWard: 'Please select a ward',
    selectDate: 'Please select a date',
    selectTitle: 'Please select a title',

    enterFName: 'Please enter first name (English)',
    enterMName: 'Please enter middle name (English)',
    enterLName: 'Please enter last name (English)',

    enterFNameMr: 'Please enter first name (Marathi) ',
    enterMNameMr: 'Please enter middle name (Marathi)',
    enterLNameMr: 'Please enter last name (Marathi)',

    enterFlat: 'Please enter Flat/Building No (English) ',
    enterApartment: 'Please enter Apartment Name (English)',
    enterRoadName: 'Please enter Road Name (English)',
    enterLandmark: 'Please enter Landmark (English)',
    enterCity: 'Please enter a City Name / Village Name (English) ',
    // state: "Please enter State (English)",

    enterFlatMr: 'Please enter Flat/Building No (Marathi)',
    enterApartmentMr: 'Please enter Apartment Name (Marathi)',
    enterRoadNameMr: 'Please enter Road Name (Marathi)',
    enterLandmarkMr: 'Please enter Landmark (Marathi)',
    enterCityMr: 'Please enter a City Name / Village Name (Marathi)',
    // stateMr: "Please enter State (Marathi)",

    enterPinCode: 'Please enter a pincode ',
    enterPhoneNo: 'Please enter a phone no. ',
    enterMobileNo: 'Please enter a mobile no. ',
    enterEmailAddress: 'Please enter an e-mail. ',
    enteraadhaarNo: 'Please enter an aadhaar no. ',
    enterpanNo: 'Please enter an pan no. ',
    enterRemarks: 'Please enter a remark. ',
    enterAge: 'Please enter a Age. ',
    selectGender: 'Please select a Gender ',
    selectReligionby: 'Please select a Religion by Birth',
    selectAdoptionby: 'Please select a Religion by Adoption',
    selectStatusAt: 'Please select a Status at time of marriage',

    //mr
    selectZone: 'Please select a zone',
    selectWard: 'Please select a ward',
    selectZone: 'Please select a Zone',
    selectTitle: 'Please select a Title',
    placeMarriage: 'Please enter Place of Marriage (in English)',
    placeMarriageMr: 'Please enter Place of Marriage (in Marathi)',

    birthProf: 'Please select a Date of Birth Proof',
    ResideProof: 'Please select a Residence Proof',
    IdentyProof: 'Please select a ID Proof',

    witnessAddressC: 'Please enter an Address ',
    witnessRelation: 'Please enter an Relation. ',

    EnterDocName: 'Please enter an Document Name ',

    noOfCopies: 'No of Copies',
    charges: 'Total Charges',
    chargeName: 'Charge Name',
    amount: 'Amount',
    totalInWords: 'Total Charges in Words',
    totalCharges: 'Total Charges',
    applicantDetails: 'Applicant Details',
    chargesDetails: 'Charges Details',
    paymentMode: 'Payment Mode',
    paymentType: 'Payment Type',
    receiptDate: 'Receipt Date',
    receiptNumber: 'Receipt Number',
    receiptAmount: 'Receipt Amount',
    ddNo: 'Demand Draft Number',
    ddDate: 'Demand Draft Date',
    bankName: 'Bank Name',
    branchName: 'Branch Name',
    bankAccountNo: 'Bank Account No',

    //Modification in Marriage Certificate

    onlyMIMC: 'Modification of Marriage Certificate',
    oldLabel: 'Old Information',
    newLabel: 'New Information',
    gDoc: 'Groom Documents',
    bDoc: 'Bride Documents',
    OwnerDetails: ' Owner Details :',
    Owneraddress: ' Owner Address :',
    document: 'Document Tab :',
    boardheadphoto: 'Board Head Person Photo',
    boardorgphotocpy: 'Board / Organization PhotoCopy',
    panCard: 'Pan Card',
    adharcard: 'Aadhaar card',
    rationcard: 'Ration card',
    electrbill: 'Electric Bill',
    OtherDocument: 'Other Document',
    UploadFile: ' Upload File',
    remarkModel: 'Enter Remark on application',
    APPROVE: 'APPROVE',

    REASSIGN: 'Revert Back',
    onlyeng: 'Must be only characters',
    onlymarathi: 'Must be only  marathi',

    //validation file upload
    birthProfV: 'Please Upload a Date of Birth Proof',
    ResideProofV: 'Please Upload a Residence Proof',
    IdentyProofV: 'Please Upload a ID Proof',

    invetaionCardV: 'Please Upload a Marriage Invitation card / affidavit ',
    marrigePhotoCV: 'Please Upload a Marriage Photograph (Couple) ',
    marDrfV: 'Please Upload a Draft an application on the 100 Rs Stamp paper',
    boardheadphotoV: 'Please Upload a Board Head Person Photo',
    boardorgphotocpyV: 'Please Upload a Board / Organization PhotoCopy',
    panCardV: 'Please Upload a Pan Card',
    adharcardV: 'Please Upload a Aadhaar card',
    yourPaymentDoneSuccess: ' Your payment done successful!!!',
    paymentFailed: 'Payment failed!!!',
    orderId: 'Order Id ',
    trackingId: 'Tracking Id',
    bankRefNo: 'Bank Reference No',
    billingName: 'Billing Name',
    billingAdd: 'Billing Address',
    billingCity: 'Billing City',
    billingZip: 'Billing Zipcode ',
    billingCountry: 'Billing Country',
    billingEmail: 'Billing Email',
    mobileNo: 'Mobile No',
    billingState: 'Billing State',
    transactionDate: 'Transaction Date',
    goToList: 'Go To List',
    totalAmount: 'Total Amount',
    loiNo: 'LOI No',
    print: 'Print',
    selfDeclaration: 'Self Declaration',
    action: 'Action',
    enterRemarkForApplication: 'Enter Remark',
    cancellSlot: 'Cancell Slots',

    documentName: 'Document Name',
    documentDetails: 'Document Details',
    depositRefundProcess: 'Deposit Refund Process',
    bookingDate: 'Booking Date',
    applicationDetails: 'Application Details',
    billDetails: 'Bill Details',
    notesheetOrReferenceNo: 'Notesheet/Reference No.',
    billDate: 'Bill Date',
    approverName: 'Approver Name',
    approvalDate: 'Approval Date',
    authority: 'Authority',

    noApplicationsFound: 'No Applications Found',
    viewApplication: 'View Application',
    searchByApplicationNumber: 'Search by Application Number',
    showFirst: 'Show first',
    equipmentsDetails: 'Equipments Details',
    equipmentName: 'Equipment Name',
    rate: 'Rate',
    quantity: 'Quantity',
    calculatedCharge: 'Calculated Charge',
    total: 'Total',
    otherEn: 'Other (in English)',
    otherMr: 'Other (in Marathi)',
    charge: 'Charge',
    otherCharges: 'Other Charges',
    adjustedDeposit: 'Adjusted Deposit',
    equipmentCharges: 'Equipment Charges',
    refundableAmount: 'Refundable Amount',

    //reports
    departmentServiceWiseReport: 'Department Service Wise Report',
    facilityVenueWiseRegister: 'Facility Venue Wise Register Report',
    customSelection: 'Custom Selection',
    facilityWiseRegister: 'Facility Wise Register Report',
    bookingCancellationReport: 'Booking Cancellation Report',
    zoneWiseFacilityRefundRegister: 'Zone Wise Facility Refund Register Report',
    zoneWiseGroundRegistrationDemandCollection:
      'Zone wise Ground Registration Demand Collection Report',
    zoneWiseSportFacilityAndVenueWiseDemandCollection:
      'Zone wise Sport Facility and Venue wise Demand Collection Report',
  },
  mr: {
    selfDeclaration: 'स्व-घोषणा फॉर्म',
    yourPaymentDoneSuccess: ' तुमचे पेमेंट यशस्वी झाले!!!',
    paymentFailed: 'पेमेंट अयशस्वी !!!',
    orderId: 'ऑर्डर आयडी ',

    trackingId: 'ट्रॅकिंग आयडी',
    bankRefNo: 'बँक संदर्भ क्र',
    billingName: 'बिलिंग नाव',
    billingAdd: 'बिलाचा पत्ता',
    billingCity: 'बिलिंग शहर',
    billingZip: 'बिलिंग पिन कोड ',
    billingCountry: 'बिलिंग देश',
    billingEmail: 'बिलिंग ईमेल',
    mobileNo: 'मोबाईल क्र',
    transactionDate: 'व्यवहाराची तारीख',
    billingState: 'बिलिंग राज्य',
    goToList: 'सूचीवर जा',
    loiNo: 'हेतू पत्र क्र',
    print: 'छापणे',
    totalAmount: 'एकूण रक्कम',
    paymentDetails: 'Payment Details',
    receiptModeDetails: 'पैसे भरावयाची पद्धत',
    type: 'commonLabels',
    pay: 'पैसे भरा',
    module: 'क्रीडा विभाग',
    // dashboard: 'डॅशबोर्ड',
    dashboard: 'पिंपरी-चिंचवड महानगरपालिका डॅशबोर्ड',
    master: 'मास्टर्स',
    transaction: 'व्यवहार',
    report: 'अहवाल',
    masterPath: 'क्रीडा विभाग/ मास्टर्स ',
    transactionPath: 'कायदेशीर प्रकरण/ व्यवहार ',
    reportPath: 'कायदेशीर प्रकरण/ अहवाल ',

    type: 'master',

    master: 'मास्टर्स',
    // transaction: "व्यवहार",
    report: 'अहवाल',
    masterPath: 'क्रीडा विभाग/ मास्टर ',
    // transactionPath: "क्रीडा विभाग/ व्यवहार ",

    //breadcrum
    viewImage: 'प्रतिमा पहा',
    facilityNamePath: 'क्रीडा विभाग/ मास्टर्स / सुविधा उप-प्रकार मास्टर',
    venuePath: 'क्रीडा विभाग/ मास्टर्स / ठिकाण मास्टर ',
    bookingTimePath: 'क्रीडा विभाग/ मास्टर्स / बुकिंग वेळ मास्टर्स',
    facilityTypePath: 'क्रीडा विभाग/ मास्टर्स / सुविधा प्रकार मास्टर',

    //titles
    facilityNameMaster: 'सुविधा उप-प्रकार मास्टर',
    facilityTypeMaster: 'सुविधा प्रकार मास्टर',
    venueMaster: 'सुविधा ठिकाण मास्टर',
    slotMaster: 'स्लॉट मास्टर',
    bookingTimeMaster: 'बुकिंग वेळ स्लॉट मास्टर',

    //labels
    facilityNameId: 'सुविधा उपप्रकार आयडी',
    facilityTypeId: 'सुविधा प्रकार आयडी',
    venueId: 'ठिकाण आयडी',
    addMember: 'सदस्य जोडा',
    delete: 'काढा',
    sportsBookingGroupDetailsDao: 'गट तपशील',

    addSection: 'विभाग जोडा',
    addSlot: 'स्लॉट जोडा',
    // delete: "सदस्य जोडा",
    zone: 'झोन',
    ward: 'प्रभाग',
    subDepartment: 'उप विभाग',
    department: 'विभाग',
    member: 'सदस्य',
    typeOfSport: 'खेळाचा प्रकार',
    facilityType: 'सुविधा प्रकार',
    typee: 'प्रकार',
    dailyDate: 'तारीख (दैनिक स्लॉट)',
    Sections: 'विभाग',
    facilityTypeEnglish: 'सुविधा प्रकार(इंग्लिश)',
    verify: 'सत्यापित करा',
    selectSlots: 'स्लॉट निवडा',
    send: 'पाठवा',
    medicalValidityPeriod: 'वैद्यकीय प्रमाणपत्राची तारीख',
    medicalCertificateNo: 'वैद्यकीय प्रमाणपत्र क्र.',
    noOfSections: 'विभागांची संख्या',
    unit: 'युनिट',
    unitEn: 'युनिट (इंग्लिश)',
    unitMr: 'युनिट (मराठी)',
    facilityTypeMr: 'सुविधा प्रकार (मराठी)',
    schoolCollegeAddress: 'शाळा/कॉलेजचा पत्ता',
    workAddress: 'कामाचा पत्ता',
    nameOfRecommendingPerson: 'शिफारस करणाऱ्या व्यक्तीचे नाव',
    facilityName: 'सुविधा उपप्रकार नाव',
    facilityNameEn: 'सुविधा उपप्रकार नाव(इंग्लिश)',
    facilityNameMr: 'सुविधा उपप्रकार नाव (मराठी)',
    units: 'युनिट्स (मराठी)',
    // unitMr: "युनिट्स (मराठी)",
    gisCode: 'GIS कोड',
    remark: 'शेरा',
    remarkMr: 'शेरा  (मराठी)',
    addressMr: 'पत्ता (मराठी)',
    venueAddressMr: ' ठिकाण पत्ता (मराठीमध्ये)',
    venueAddressEn: ' ठिकाण पत्ता (इंग्रजीमध्ये)',
    venueVillageEn: 'ठिकाण गाव (इंग्रजीमध्ये)',
    venueVillageMr: 'ठिकाण गाव (मराठीमध्ये)',
    contactPersonMobileNo: 'संपर्क व्यक्तीचा मोबाईल नं. ',
    contactPersonName: 'संपर्क व्यक्तीचे नाव (इंग्लिश)',
    contactPersonNameMr: 'संपर्क व्यक्तीचे नाव (मराठी)',
    contactPerson: 'संपर्क व्यक्तीचे नाव',
    sizeOfVenue: 'ठिकाणाचे क्षेत्रफळ',
    venue: 'सुविधा ठिकाण',
    venueMr: 'सुविधा ठिकाण (मराठी)',
    venueEN: 'सुविधा ठिकाण (इंग्लिश)',
    sections: 'विभागांची उपलब्ध संख्या',
    date: 'तारीख',
    fromBookingTime: '(पासून) बुकिंगची वेळ',
    toBookingTime: '(ते) बुकिंगची वेळ',
    capacity: 'क्षमता',
    Lattitude: 'अक्षांश',
    Longitute: 'रेखांश',
    cityOrVillage: 'शहर / गाव',
    pincode: 'पिनकोड',
    area: 'क्षेत्राचे नाव',
    name: 'नाव',
    mobile: 'मोबाईल नं.',
    phone: 'दूरध्वनी नं.',
    email: 'इलेक्ट्रॉनिक संदेश',
    aadharNo: 'आधार नं.',
    applicantaadharNo: 'अर्जदाराचा आधार क्रमांक',
    panNo: 'पॅन नं.',
    advocateCreation: 'वकिल यशस्वीपणे तयार केला',
    advocateDetails: 'वकील तपशील',
    bankDetails: 'बँक तपशील',
    documentUpload: 'दस्तऐवज अपलोड',
    title: 'शीर्षक ',
    fname: 'पहिले नाव ',
    mname: 'मधले  नाव ',
    lname: 'शेवटचे नाव ',
    advocateCategory: 'वकील श्रेणी *',
    nameOfBarCouncil: 'वकिलांचे मंडळचे प्रमाणपत्र परिषदचे नाव *',
    remarks: 'टिप्पणी *',
    bankName: 'बँकेचे नाव *',
    branchName: 'शाखेचे नाव *',
    accountNo: 'खाता क्रमांक *',
    bankIFSC: 'बँक IFSC कोड *',
    bankMICR: 'बँक MICR कोड *',

    VbankName: 'बँकेचे नाव निवडा',
    Vvenue: 'ठिकाणाचे नाव निवडा',
    Vdate: 'कृपया तारीख निवडा',
    VpanCard: 'कृपया पॅन कार्ड अपलोड करा',
    Vphoto: 'कृपया छायाचित्र अपलोड करा',
    Vmedical: 'कृपया वैद्यकीय प्रमाणपत्र अपलोड करा',
    VtotalGroupMember: 'गट सदस्य प्रविष्ट करा',
    VSelectSlot: 'कृपया स्लॉट निवडा',
    Vzone: 'झोन निवडा',
    VchargeType: 'कृपया शुल्क प्रकार प्रविष्ट करा (इंग्लिश)',
    VchargeTypeMr: 'कृपया शुल्क प्रकार प्रविष्ट करा (मराठी)',
    Vcapacity: 'क्षमता प्रविष्ट करा',
    Vward: 'प्रभाग निवडा',
    VtypeOfSports: ' खेळचे प्रकार निवडा',
    VbranchName: 'शाखेचे नाव भरा',
    VbankAccountHolderName: 'बँक खातेधारकाचे नाव भरा',
    VbankAccountNo: 'खाता क्रमांक भरा',
    VifscCode: 'बँक IFSC कोड भरा',
    VbankAddress: 'बँकेचा पत्ता भरा',
    Vvenue: 'सुविधा ठिकाण निवडा',
    VbookingType: 'बुकिंग प्रकार निवडा',
    application: 'अर्ज:',
    aadharCard: 'आधार कार्ड:',
    companyCard: 'कंपनी कार्ड',
    photo: 'पासपोर्टच्या आकाराचा फोटो',
    medicalCertificate: 'वैद्यकीय प्रमाणपत्र',
    aadharCertificate: 'आधार कार्ड',
    photoCertificate: 'छायाचित्र',
    panCard: 'पॅन कार्ड:',
    barCouncilCertificate: 'वकिलांचे मंडळचे प्रमाणपत्र',
    bankPassbook: 'बँक पासबुक',
    subType: 'उप-प्रकार',
    slots: 'स्लॉट',
    availableSlots: 'उपलब्ध स्लॉट',
    timePeriod: 'कालावधी',
    attachFile: 'फाईल जोडा',
    srNo: 'अनुक्रमांक',
    actions: 'क्रिया ',
    clerkVerification: 'लिपिक पडताळणी',
    approve: 'मंजूर',
    reject: 'अर्ज नाकारणे',
    revert: 'पूर्वस्थितीवर येणे',
    enterRemarkForApplication: 'अर्जासाठी टिप्पणी प्रविष्ट करा',
    enterRemarkForApplicationEn: 'अर्जासाठी टिप्पणी प्रविष्ट करा',
    enterRemarkForApplicationMr: 'अर्जासाठी टिप्पणी प्रविष्ट करा (मराठी)',
    depositeCondition:
      'नोंद: वैद्यकीय प्रमाणपत्र केवळ MBBS, MD & MS द्वारे अधिकृत असावे',
    fileSizeInstrction: 'फाइल आकार १० mb पेक्षा जास्त नसावा',
    sVerification: 'पर्यवेक्षक पडताळणी',
    sOVerification: 'पडताळणी क्रीडा अधिकारी',
    aCVerification: 'पडताळणी अतिरिक्त आयुक्त',
    vCommiCVerification: 'पडताळणी कमिशनर',
    sLetter: 'मंजूरी पत्र जारी',
    slotDetails: 'स्लॉट तपशील',

    iCard: 'आय-कार्ड',
    vSportsOfficer: 'पडताळणी क्रीडा अधिकारी',
    loiGeneration: 'LOI तयार करा',

    sendOtp: 'ओटीपी पाठवा',
    Addfile: 'फाइल जोडा',
    //Remarks
    selectDate: 'कृपया तारीख निवडा',
    selectTitle: 'कृपया शीर्षक निवडा',
    enterFName: 'कृपया पहिले नाव भरा ',
    enterMName: 'कृपया मधले  नाव भरा ',
    enterLName: 'कृपया शेवटचे नाव भरा ',
    selectAdvocateCategory: 'कृपया वकील श्रेणी निवडा',
    enterCouncilName: 'कृपया वकिलांचे मंडळचे प्रमाणपत्र परिषदचे नाव भरा',
    enterArea: 'कृपया क्षेत्राचे नाव भरा ',
    enterRoadName: 'कृपया रस्त्याचे नाव भरा ',
    enterLandmark: 'कृपया  महत्त्वाची खूण भरा',
    enterCity: 'कृपया  शहराचे / गावाचे नाव भरा ',
    enterPinCode: 'कृपया पिनकोड भरा',
    enterPhoneNo: 'कृपया दूरध्वनी नं. भरा',
    enterMobileNo: 'कृपया मोबाईल नं. भरा',
    enterEmailAddress: 'कृपया इलेक्ट्रॉनिक संदेश भरा',
    enteraadhaarNo: 'कृपया आधार नं. भरा',
    maxNumber: 'आधार क्रमांक १२ वरील क्रमांकावर वैध नाही',
    minNumber: 'आधार क्रमांक हा किमान १२ क्रमांकाचा असणे आवश्यक आहे',
    maxPin: '6 वरील क्रमांकावर पिनकोड क्रमांक वैध नाही',
    minPin: 'पिनकोड क्रमांक किमान 6 क्रमांकाचा असावा',
    cancel: 'रद्द करा',
    bankNoMsg: 'बँक खाते क्रमांक 15 अंकी असणे आवश्यक आहे',
    conformMsg: 'खाते क्रमांक आणि पुष्टीकरण जुळले पाहिजे',
    enterpanNo: 'कृपया पॅन नं. भरा',
    // enterRemarks: 'कृपया टिप्पणी. भरा',
    enterRemarks: 'कृपया टिप्पणी. द्या',

    //buttons
    add: 'जोडा',
    save: 'जतन करा',
    update: 'अद्यायावत करा',
    clear: 'रिक्त',
    exit: 'बाहेर पडा',

    back: 'मागे',
    saveAndNext: 'जतन करा आणि पुढे',
    finish: 'समाप्त',

    type: 'transaction',

    transaction: 'व्यवहार',
    transactionPath: 'कायदेशीर प्रकरण/ व्यवहार ',

    //breadcrum

    //titles
    sportBooking: 'क्रीडा बुकिंग',
    check: 'उपलब्धता स्थिती तपासा',
    swimmingPool: 'जलतरण तलाव',

    //titles
    bookingDetails: 'नोंदणी तपशील',
    personalGroupDetails: 'वैयक्तिक गट तपशील',
    documentUploadDaily: 'दस्तऐवज अपलोड',
    personalDetails: 'वैयक्तिक माहिती',
    aadharAuthentication: 'आधार प्रमाणीकरण',
    paymentDetails: 'देयक तपशील',
    aadharAuthenticationDetails: 'आधार प्रमाणीकरण तपशील',
    eCSDetails: 'ECS तपशील',
    documentsUpload: 'दस्तऐवज अपलोड करा',

    //other labels
    facilityAvl: 'सुविधा उपलब्धता',
    fromDate: 'तारीख (पासून)',
    maintainanceDate: 'देखरेखीची तारीख',
    maintainanceRemark: 'देखभाल टिप्पणी',
    toDate: 'तारीख (ते)',
    selectSlot: 'स्लॉट निवडा',
    availableSlot: 'उपलब्ध स्लॉट',
    selectMultipleSlots: 'एकाधिक स्लॉट निवडा',
    selectSlotsForSendMail: ' स्लॉट निवडा',
    selectSlotA: 'उपलब्ध स्लॉट',
    formDateTime: '(पासून) तारीख आणि वेळ',
    toDateTime: '(ते) तारीख आणि वेळ',
    bookingRegistrationId: 'बुकिंग नोंदणी आयडी',
    documentUpload: 'दस्तऐवज अपलोड',
    applicationDate: 'अर्जाची तारीख',
    applicationTime: 'अर्ज वेळ',

    bookingType: 'बुकिंग प्रकार',
    durationType: 'कालावधीचा प्रकार',
    applicantType: 'अर्जदाराचा प्रकार',
    noDataAdded: 'कोणताही डेटा जोडला नाही',
    equipmentNameEn: 'उपकरणाचे नाव (इंग्रजी)',
    equipmentNameMr: 'उपकरणाचे नाव (मराठी)',
    duration: 'कालावधी',
    noSlotAdded: 'कोणताही स्लॉट जोडला नाही',
    slotDuration: 'स्लॉट कालावधी',
    chargeType: 'शुल्क प्रकार ',
    applicantTypeEn: 'अर्जदाराचा प्रकार (इंग्रजीमध्ये)',
    applicantTypeMr: 'अर्जदाराचा प्रकार (मराठीमध्ये)',
    durationTypeMr: 'कालावधीचा प्रकार (मराठी)',
    durationTypeEn: 'कालावधीचा प्रकार (इंग्लिश)',
    chargeTypeMr: 'शुल्क प्रकार (मराठी)',
    chargeTypeEn: 'शुल्क प्रकार (इंग्लिश)',
    zone: 'झोन',
    ward: 'प्रभाग',
    subDepartment: 'उप विभाग',
    department: 'विभाग ',
    member: 'सदस्य',
    facilityType: 'सुविधा प्रकार',
    facilityName: 'सुविधेचे उपप्रकार',
    venue: 'सुविधा ठिकाण',
    typeOfSports: 'क्रीडा प्रकार',
    totalGroupMember: 'एकूण गट सदस्य',
    additionalGroupMember: 'अतिरिक्त गट सदस्य',
    groupName: 'गटाचे नाव',
    groupDetails: 'गट तपशील',
    title: 'शीर्षक',
    firstName: 'पहिले नाव',
    middleName: 'मधले नाव',
    lastName: 'आडनाव',
    gender: 'लिंग',
    dateOfBirth: 'जन्मतारीख',
    age: 'वय',
    mobileNo: 'मोबाईल क्र',
    aadharNo: 'आधार क्र',
    emailAddress: 'ईमेल आयडी',
    currentAddress: 'सध्याचा पत्ता (इंग्लिश)',
    currentAddressMr: 'सध्याचा पत्ता (मराठी)',
    permanentAddress: 'कायमचा पत्ता',
    permanentAddressMarathi: 'कायमचा पत्ता (मराठी)',
    cityName: 'शहराचे नाव',

    cityNameEn: 'शहराचे नाव (इंग्लिश)',
    cityNameMr: 'शहराचे नाव (मराठी)',
    state: 'राज्य',
    Maharashtra: 'महाराष्ट्र',
    pinCode: 'पिन कोड',
    bankName: 'बँकेचे नाव',
    branchName: 'शाखेचे नाव',
    bankAccountHolderName: 'बँक खातेधारकाचे नाव',
    bankAccountNo: 'बँक खाते क्र',
    matchAccNo: 'खाते क्रमांक आणि पुष्टीकरण जुळले पाहिजे',
    confirmAccountMsg: 'कृपया तुमच्या खाते क्रमांकाची पुष्टी करा',
    confirmBankAccountNo: 'बँक खाते क्रमांकाची पुष्टी करा',
    ifscCode: 'IFSC कोड',
    mandatory: 'अनिवार्य',
    bankAddress: 'बँकेचा पत्ता',
    aadharCard: 'आधार कार्ड',
    panCard: 'पॅन कार्ड',
    otherDocumentPhoto: 'इतर दस्तऐवज फोटो',
    checkBox: 'सध्याचा रहिवाशी पत्ता कायमचा पत्ता',
    purposeOfBooking: 'बुकिंगचा उद्देश',
    bookingPersonDetails: 'बुकिंग व्यक्ती तपशील',

    //buttons
    add: 'जोडा',
    save: 'जतन करा',
    update: 'अद्यायावत करा',
    clear: 'रिक्त',
    exit: 'बाहेर पडा',
    back: 'मागे',
    saveAndNext: 'जतन करा आणि पुढे',
    finish: 'समाप्त',

    onlyeng: 'फक्त इंग्लिश ',
    onlymarathi: 'फक्त मराठी',
    APPROVE: 'मंजूर करा',

    REASSIGN: 'पुन्हा नियुक्त करा',
    remarkModel: 'अर्जावर टिप्पणी प्रविष्ट करा',

    oldLabel: 'पूर्वीची माहिती',
    newLabel: 'नवीन माहिती',
    onlyMIMC: 'विवाह प्रमाणपत्रात बदल',
    // State: "स्टेट (इंग्लिश ) ",
    // statemr: "स्टेट (मराठी) ",
    UploadFile: 'फाइल अपलोड करा',
    electrbill: 'वीज बिल',
    OtherDocument: 'इतर दस्तऐवज',
    rationcard: 'रेशान कार्ड',
    adharcard: 'आधार कार्ड',
    panCard: 'पॅन कार्ड',
    boardorgphotocpy: 'संस्था किंवा मंडळची दस्तऐवज',
    boardheadphoto: 'मंडळाच्या प्रमुख व्यक्तीच छायाचित्र',
    document: 'दस्तऐवज',
    Owneraddress: ' मंडळच्या प्रमुख व्यक्तीचा पत्ता  :',
    OwnerDetails: 'मंडळच्या प्रमुख व्यक्तीची माहिती',
    titleInmarathi: 'शीर्षक मराठी',
    titleInenglish: 'शीर्षक इंग्लिश ',
    OwnerChkeck: 'जर अर्जादारच विवाह मंडळाचा प्रमुख असेल',
    apply: 'जतन करा',
    ifsc: 'आय एफ एस सी कोड',
    accountNumber: 'खाते क्रमांक',
    bankName: 'बँकेचे नाव',
    branchName: 'शाखेचे नाव',
    bankAccountNo: 'बँक खाते क्रमांक',
    ddDate: 'डिमांड ड्राफ्ट तारीख',
    ddNo: 'डिमांड ड्राफ्ट क्रमांक',
    receiptAmount: 'पावती रक्कम',
    receiptNumber: 'पावती क्रमांक',
    receiptDate: 'पावती तारीख',
    paymentMode: 'Payment Mode',
    paymentType: 'Payment Type',
    receiptModeDetails: 'Receipt Mode Details',
    chargesDetails: 'शुल्क तपशील',
    applicantDetails: 'अर्जदाराची माहिती',
    generateLoi: 'स्विकृती पत्र तयार करा',
    totalCharges: 'एकुण रक्कम',
    totalInWords: 'एकुण अक्षरी रक्कम ',
    amount: 'रक्कम',
    EnterDocName: 'कृपया दस्तऐवजाच नाव भरा ',
    witnessAddressC: 'कृपया पत्ता भरा  ',
    witnessRelation: 'कृपया साक्षीदारशी नाते भरा  ',

    birthProf: 'कृपया जन्म तारीख पुरावा निवडा ',
    ResideProof: 'कृपया रहिवासाचा पुरावा निवडा ',
    IdentyProof: 'कृपया ओळखपत्र पुरावा निवडा ',
    // //Remarks
    selectReligionby: 'कृपया जन्माने धर्म निवडा ',
    selectAdoptionby: 'कृपया दत्तक घेऊन धर्म निवडा ',
    selectStatusAt: 'कृपया लग्नाच्या वेळची स्थिती निवडा ',

    enterAge: 'कृपया वय भरा ',
    selectGender: 'कृपया लिंग निवडा ',
    selectZone: 'कृपया झोन निवडा',
    selectWard: 'कृपया वार्ड निवडा',
    selectDate: 'कृपया तारीख निवडा',
    selectTitle: 'कृपया शीर्षक निवडा',
    enterFName: 'कृपया पहिले नाव भरा (इंग्लिश )',
    enterMName: 'कृपया मधले  नाव भरा (इंग्लिश )',
    enterLName: 'कृपया शेवटचे नाव भरा (इंग्लिश )',

    enterFNameMr: 'कृपया पहिले नाव भरा (मराठी) ',
    enterMNameMr: 'कृपया मधले  नाव भरा (मराठी)',
    enterLNameMr: 'कृपया शेवटचे नाव भरा (मराठी)',

    enterFlat: 'कृपया  फ्लॅट नंबर नाव भरा  (इंग्लिश ) ',
    enterApartment: 'कृपया  अपार्टमेंट  नाव भरा  (इंग्लिश )',
    enterRoadName: 'कृपया रस्त्याचे नाव भरा (इंग्लिश )',
    enterLandmark: 'कृपया  महत्त्वाची खूण भरा (इंग्लिश )',
    enterCity: 'कृपया  शहराचे / गावाचे नाव भरा (इंग्लिश )',
    // state: "कृपया  राज्य नाव भरा (इंग्लिश )",

    enterFlatMr: 'कृपया  फ्लॅट नंबर नाव भरा  (मराठी)',
    enterApartmentMr: 'कृपया  अपार्टमेंट  नाव भरा(मराठी)',
    enterRoadNameMr: 'कृपया रस्त्याचे नाव भरा  (मराठी)',
    enterLandmarkMr: 'कृपया  महत्त्वाची खूण भरा  (मराठी)',
    enterCityMr: 'कृपया  शहराचे / गावाचे नाव भरा (मराठी)',
    // stateMr: "कृपया  राज्य नाव भरा  (मराठी)",

    enterArea: 'कृपया क्षेत्राचे नाव भरा ',
    enterRoadName: 'कृपया रस्त्याचे नाव भरा ',
    enterLandmark: 'कृपया  महत्त्वाची खूण भरा',
    enterCity: 'कृपया  शहराचे / गावाचे नाव भरा ',

    enterPinCode: 'कृपया पिनकोड भरा',
    enterPhoneNo: 'कृपया दूरध्वनी नं. भरा',
    enterMobileNo: 'कृपया मोबाईल नं. भरा',
    enterEmailAddress: 'कृपया इलेक्ट्रॉनिक संदेश भरा',
    enteraadhaarNo: 'कृपया आधार नं. भरा',
    enterpanNo: 'कृपया पॅन नं. भरा',
    enterRemarks: 'कृपया टिप्पणी. द्या',
    //mr
    selectWard: 'कृपया प्रभाग निवडा ',
    applicationNumber: 'अर्ज क्रमांक',
    orderId: 'ऑर्डर आयडी',
    applicationStatus: 'अर्जाची स्थिती',
    selectZone: 'कृपया झोन निवडा ',
    selectTitle: 'कृपया शीर्षक निवडा ',
    placeMarriage: 'कृपया  विवाहाचा ठिकाण भरा (इंग्लिश )',
    placeMarriageMr: 'कृपया  विवाहाचा ठिकाण भरा  (मराठी)',
    VfacilityType: 'कृपया सुविधाचा प्रकार निवडा',
    VgisCode: 'कृपया GIS कोड प्रविष्ट करा',
    facilityTypeMrMsg: 'कृपया सुविधाचा प्रकार निवडा(मराठी)',

    VdurationType: 'कृपया कालावधीचा प्रकार निवडा (इंग्लिश)',
    VdurationTypeMr: 'कृपया कालावधीचा प्रकार निवडा (मराठी)',
    VapplicantType: 'अर्जदाराचा प्रकार निवडा (इंग्लिश)',
    VType: 'कृपया प्रकार निवडा',
    VapplicantMrType: 'अर्जदाराचा प्रकार निवडा (मराठी)',
    Vunit: 'युनिट निवडा (इंग्लिश)',
    VunitMr: 'युनिट निवडा (मराठी)',
    VfromDate: ' कृपया तारीख निवडा',
    VtoDate: ' कृपया तारीख निवडा',
    VmaintainanceDate: 'देखभाल करण्याची तारीख निवडा',
    Vremark: 'टिप्पणी (इंग्लिश)',
    VremarkMr: 'टिप्पणी (मराठी)',
    VfacilityName: 'सुविधेचे उपप्रकार निवडा',
    VfacilityNameMr: 'सुविधेचे उपप्रकार निवडा (मराठी)',
    VpurposeOfBooking: 'बुकिंगचा उद्देश निवडा',
    Vcaddres: 'कृपया  सध्याचा पत्ता भरा   ',
    Vpaddres: 'कृपया कायमचा पत्ता प्रविष्ट करा',
    VfromBookingTime: 'कृपया वेळ निवडा ',
    VselectSlots: 'कृपया स्लॉट निवडा ',
    VtoBookingTime: 'कृपया वेळ निवडा ',
    VaadharCard: 'कृपया आधार कार्ड निवडा ',
    VaadharNo: 'कृपया आधार क्रमांक टाका',
    adharcardV: 'कृपया आधार कार्ड अपलोड करा',
    panCardV: 'कृपया पॅन कार्ड अपलोड करा',
    boardorgphotocpyV: 'कृपया संस्था किंवा मंडळची दस्तऐवज अपलोड करा',
    boardheadphotoV: 'कृपया मंडळाच्या प्रमुख व्यक्तीच छायाचित्र अपलोड करा',
    //validation file upload
    birthProfV: 'कृपया जन्म तारीख पुरावा अपलोड करा ',
    ResideProofV: 'कृपया रहिवासाचा पुरावा अपलोड करा ',
    IdentyProofV: 'कृपया ओळखपत्र पुरावा अपलोड करा ',

    invetaionCardV: 'कृपया विवाह निमंत्रण पत्रिका / प्रतिज्ञापत्र अपलोड करा',
    marrigePhotoCV: 'कृपया विवाह छायाचित्र (जोडीचे) अपलोड करा',
    marDrfV:
      'कृपया १०० रुपयांच्या स्टॅम्प पेपरवर असलेला अर्जाचा मसुदा अपलोड करा',

    registerationNo: 'मंडळाचा नोंदणी क्रमांक',
    onlyeng: 'फक्त इंग्लिश ',
    onlymarathi: 'फक्त मराठी',
    APPROVE: 'मंजूर करा',

    REASSIGN: 'पुन्हा नियुक्त करा',
    remarkModel: 'अर्जावर टिप्पणी प्रविष्ट करा',

    oldLabel: 'पूर्वीची माहिती',
    newLabel: 'नवीन माहिती',
    onlyMIMC: 'विवाह प्रमाणपत्रात बदल',
    // State: "स्टेट (इंग्लिश ) ",
    UploadFile: 'फाइल अपलोड करा',
    electrbill: 'वीज बिल',
    OtherDocument: 'इतर दस्तऐवज',
    rationcard: 'रेशान कार्ड',
    adharcard: 'आधार कार्ड',
    panCard: 'पॅन कार्ड',
    boardorgphotocpy: 'संस्था किंवा मंडळची दस्तऐवज',
    boardheadphoto: 'मंडळाच्या प्रमुख व्यक्तीच छायाचित्र',
    document: 'दस्तऐवज',
    Owneraddress: ' मंडळच्या प्रमुख व्यक्तीचा पत्ता  :',
    OwnerDetails: 'मंडळच्या प्रमुख व्यक्तीची माहिती',
    titleInmarathi: 'शीर्षक (मराठी)',
    titleInenglish: 'शीर्षक (इंग्लिश )',
    OwnerChkeck: 'जर अर्जादारच विवाह मंडळाचा प्रमुख असेल',
    apply: 'जतन करा',
    ifsc: 'आय एफ एस सी कोड',
    accountNumber: 'खाते क्रमांक',
    bankName: 'बँकेचे नाव',
    branchName: 'शाखेचे नाव',
    bankAccountNo: 'बँक खाते क्रमांक',
    ddDate: 'डिमांड ड्राफ्ट तारीख',
    ddNo: 'डिमांड ड्राफ्ट क्रमांक',
    receiptAmount: 'पावती रक्कम',
    receiptNumber: 'पावती क्रमांक',
    receiptDate: 'पावती तारीख',
    paymentMode: 'Payment Mode',
    paymentType: 'Payment Type',
    receiptModeDetails: 'Receipt Mode Details',
    chargesDetails: 'शुल्क तपशील',
    applicantDetails: 'अर्जदाराची माहिती',
    generateLoi: 'स्विकृती पत्र तयार करा',
    totalCharges: 'एकुण रक्कम',
    totalInWords: 'एकुण अक्षरी रक्कम ',
    amount: 'रक्कम',
    EnterDocName: 'कृपया दस्तऐवजाच नाव भरा ',
    witnessAddressC: 'कृपया पत्ता भरा  ',
    witnessRelation: 'कृपया साक्षीदारशी नाते भरा  ',

    birthProf: 'कृपया जन्म तारीख पुरावा निवडा ',
    ResideProof: 'कृपया रहिवासाचा पुरावा निवडा ',
    IdentyProof: 'कृपया ओळखपत्र पुरावा निवडा ',
    // //Remarks
    selectReligionby: 'कृपया जन्माने धर्म निवडा ',
    selectAdoptionby: 'कृपया दत्तक घेऊन धर्म निवडा ',
    selectStatusAt: 'कृपया लग्नाच्या वेळची स्थिती निवडा ',

    enterAge: 'कृपया वय भरा ',
    selectGender: 'कृपया लिंग निवडा ',
    selectZone: 'कृपया झोन निवडा',
    selectWard: 'कृपया वार्ड निवडा',
    selectDate: 'कृपया तारीख निवडा',
    selectTitle: 'कृपया शीर्षक निवडा',
    enterFName: 'कृपया पहिले नाव भरा (इंग्लिश )',
    enterMName: 'कृपया मधले  नाव भरा (इंग्लिश )',
    enterLName: 'कृपया शेवटचे नाव भरा (इंग्लिश )',

    enterFNameMr: 'कृपया पहिले नाव भरा (मराठी) ',
    enterMNameMr: 'कृपया मधले  नाव भरा (मराठी)',
    enterLNameMr: 'कृपया शेवटचे नाव भरा (मराठी)',

    enterFlat: 'कृपया  फ्लॅट नंबर नाव भरा  (इंग्लिश ) ',
    enterApartment: 'कृपया  अपार्टमेंट  नाव भरा  (इंग्लिश )',
    enterRoadName: 'कृपया रस्त्याचे नाव भरा (इंग्लिश )',
    enterLandmark: 'कृपया  महत्त्वाची खूण भरा (इंग्लिश )',
    enterCity: 'कृपया  शहराचे / गावाचे नाव भरा (इंग्लिश )',
    // state: "कृपया  राज्य नाव भरा (इंग्लिश )",

    enterFlatMr: 'कृपया  फ्लॅट नंबर नाव भरा  (मराठी)',
    enterApartmentMr: 'कृपया  अपार्टमेंट  नाव भरा(मराठी)',
    enterRoadNameMr: 'कृपया रस्त्याचे नाव भरा  (मराठी)',
    enterLandmarkMr: 'कृपया  महत्त्वाची खूण भरा  (मराठी)',
    enterCityMr: 'कृपया  शहराचे / गावाचे नाव भरा (मराठी)',
    // stateMr: "कृपया  राज्य नाव भरा  (मराठी)",

    enterArea: 'कृपया क्षेत्राचे नाव भरा ',
    enterRoadName: 'कृपया रस्त्याचे नाव भरा ',
    enterLandmark: 'कृपया  महत्त्वाची खूण भरा',
    enterCity: 'कृपया  शहराचे / गावाचे नाव भरा ',

    enterPinCode: 'कृपया पिनकोड भरा',
    enterPhoneNo: 'कृपया दूरध्वनी नं. भरा',
    enterMobileNo: 'कृपया मोबाईल नं. भरा',
    enterEmailAddress: 'कृपया इलेक्ट्रॉनिक संदेश भरा',
    enteraadhaarNo: 'कृपया आधार नं. भरा',
    enterpanNo: 'कृपया पॅन नं. भरा',
    enterRemarks: 'कृपया टिप्पणी. द्या',
    //mr
    selectWard: 'कृपया प्रभाग निवडा ',
    selectZone: 'कृपया झोन निवडा ',
    selectTitle: 'कृपया शीर्षक निवडा ',
    placeMarriage: 'कृपया  विवाहाचा ठिकाण भरा (इंग्लिश )',
    placeMarriageMr: 'कृपया  विवाहाचा ठिकाण भरा  (मराठी)',

    pay: 'पैसे भरा',
    titlemr: 'शीर्षक ',
    title1: 'Title ',
    newMRtable: 'नवीन विवाह नोंदणी',
    module: 'विवाह नोंदणी',
    // dashboard: 'डॅशबोर्ड',
    dashboard: 'पिंपरी-चिंचवड महानगरपालिका डॅशबोर्ड',
    masters: 'मास्टर्स',
    transactions: 'ट्रैन्ज़ैक्शन',
    reports: 'अहवाल',
    receipt: 'पावती',
    usertask: 'User task',
    serviceChargeTypeName: 'सेवा शुल्काचा प्रकार',

    chargeName: 'शुल्काचा प्रकार',
    masters: 'मास्टर्स',
    masterPath: 'तक्रार निरीक्षण / मास्टर्स',

    transaction: 'व्यवहार',
    report: 'अहवाल',
    masterPath: 'अग्निशमन यंत्रणा / मास्टर ',
    transactionPath: 'कायदेशीर प्रकरण/ व्यवहार ',
    reportPath: 'कायदेशीर प्रकरण/ अहवाल ',

    //mr
    MrMasters: 'विवाह नोंदणी/ मास्टर ',
    marriageRegistrationMaritalStatus: 'विवाह नोंदणी/ मास्टर / वैवाहिक स्थिती',

    marriageRegistrationrelation: 'विवाह नोंदणी/ मास्टर / नाते',

    AptBook: 'अपॉइंटमेंट स्लॉट बुकिंग',

    documentUpload: 'दस्तऐवज अपलोड',
    addFile: 'फाइल जोडा',
    fileName: 'फाईलचे नाव',
    mandatoryOrOptional: 'अनिवार्य/पर्यायी',
    mandatory: 'अनिवार्य',
    optional: 'पर्यायी',
    verify: 'सत्यापित',
    reject: 'नाकारा',
    noFileFound: 'कोणतीही फाइल आढळली नाही',
    verified: 'तपासून झाले',

    upload: 'अपलोड करा',
    next: 'पुढे',
    preview: 'पूर्वावलोकन',

    attachFile: 'फाईल जोडा',
    srNo: 'अनु क्र',
    actions: 'क्रिया ',
    serviceName: 'सेवेचे नाव ',
    //titles

    calendarScheduling: ' दिनदर्शिका शेड्युलिंग',
    maritialSatus: 'वैवाहिक स्थिती',
    relation: 'नाते',
    //field label
    srNo: 'अनु क्रमांक',
    actions: 'क्रिया ',
    statusDetails: 'स्थिती तपशील',

    //buttons
    venueDetails: 'ठिकाण तपशील',
    facilityDetails: 'सुविधा तपशील',
    applicantTypeMaster: 'अर्जदार प्रकार मास्टर',
    equipmentMaster: 'उपकरणे मास्टर',
    unitMaster: 'युनिट मास्टर',
    durationTypeMaster: 'कालावधी प्रकार मास्टर',
    chargeTypeMaster: 'शुल्क प्रकार',
    bookingTimeMaster: 'बुकिंग टाइम मास्टर',
    maintenanceAnnouncement: 'देखभाल घोषणा',
    venueMaster: 'ठिकाण मास्टर',
    rateChargeMaster: 'दर शुल्क मास्टर',
    facilityTypeMaster: 'सुविधा प्रकार मास्टर',
    facilityNameMaster: 'सुविधा उप-प्रकार मास्टर',
    facilityNameAndFacilityTypeAndDurationTypeMappingMaster:
      'सुविधेचे नाव, सुविधेचा प्रकार, कालावधी प्रकार मॅपिंग मास्टर',

    add: 'जोडा',
    save: 'जतन करा',
    update: 'अद्यायावत करा',
    clear: 'रिक्त',
    exit: 'बाहेर पडा',
    basicApplicationDetails: 'मूलभूत अर्ज तपशील',
    applicationHistory: 'अर्ज इतिहास',
    time: 'वेळ',
    sentByUser: 'मंजूरी देणारे नाव',
    viewForm: 'फॉर्म पहा',
    viewDocument: 'कागदपत्र पहा',
    download: 'डाउनलोड करा',

    ward: 'प्रभाग',
    zone: 'झोन',
    latitude: 'अक्षांश',
    Longitude: 'रेखांश',

    ward: 'प्रभाग',
    zone: 'झोन',
    latitude: 'अक्षांश',
    Longitude: 'रेखांश',

    ApplicatCheck1: 'जर अर्जदार वर असेल तर',
    ApplicatCheck2: 'जर अर्जदार वधु असेल तर',

    transactions: ' ट्रैन्ज़ैक्शन',
    transactionPath: 'कायदेशीर प्रकरण/  ट्रैन्ज़ैक्शन ',

    //mr
    // instrustion
    onlyMHR:
      'महाराष्ट्रातील विवाहाचे रजिस्ट्रेशन केले जाते आणि वधू किंवा वर यापैकी एक जण पिंपरी चिंचवड महानगर पालिकेच्या हद्दी मधील रहिवासी असावा.',
    docNote:
      'आयडी पुरावा, रहिवासी पुरावा, वयाचा पुरावा वेगळा असावा, (लग्नाच्या वेळी स्थिती असल्यास मागील स्टेटस प्रूफमध्ये मूल्य असते विधवा/विधुर किंवा घटस्फोटीत आहे) आधारकार्ड पुरावा जोडल्यास व नागरिक भाड्याने राहत असलेस नोंदणीकृत करारनामा आवश्यक आहे.',

    //aprove
    GPhoto: 'वरचा फोटो  ',
    Bphoto: 'वधुचा फोटो  ',
    witnessphto1: 'साक्षीदारचा १ फोटो  ',
    witnessphto2: 'साक्षीदारचा २ फोटो  ',
    witnessphto3: 'साक्षीदारचा ३ फोटो  ',
    Gthumb: 'वरचा अंगठाचा ठसा  ',
    Bthumb: 'वधुचा अंगठाचा ठसा  ',
    witnessthumb1: 'साक्षीदारचा १ अंगठाचा ठसा  ',
    witnessthumb2: 'साक्षीदारचा २ अंगठाचा ठसा  ',
    witnessthumb3: 'साक्षीदारचा ३ अंगठाचा ठसा  ',

    //table
    Tnc: 'नियम व अटी',
    newMRtable: 'नवीन विवाह नोंदणी',
    boardtitle: 'विवाह मंडळाची माहिती',
    zone: 'झोन',
    ward: 'वार्ड',
    Addrees: 'अर्जदाराचा रहिवासाचा पत्ता :',

    CrrtAdree: 'सध्याचा रहिवासाचा पत्ता :',
    parmtAdree: 'कायमचा रहिवासाचा पत्ता :',
    personalDetails: 'वैयक्तिक माहिती',
    venueDetails: 'ठिकाण तपशील',
    sectionDetails: 'विभाग तपशील',
    venueInformation: 'ठिकाण माहिती',
    Adress: 'पत्ता :',
    BriNBM: '  (  लग्नाआधीचे नाव)',
    AppliToGroom: '',
    AppliToBride: '',
    marrigeDetails: 'विवाहाची माहिती :',
    marrigeDate: 'विवाहाची दिनांक',

    //title
    ApplicatDetails: 'अर्जदाराची माहिती',
    ApplicatName: 'अर्जदाराच नाव',
    groomDetail: 'वराची माहिती',
    groomParaentDetail: 'वराच्या पालकांची माहिती',
    brideDetails: 'वधुची माहिती',
    brideParaentDetail: 'वधुच्या पालकांची माहिती',
    priestDetails: 'पुजारी माहिती',
    witness: 'साक्षीदार',
    witnessDetails: 'साक्षीदार माहिती',
    documentsUpload: 'दस्तऐवज अपलोड',
    boardDetail: 'विवाह मंडळाची माहिती :',
    otherDetail: 'इतर तपशील',

    // viceversa
    titleV: 'Title  ',
    firstNameV: 'First Name  ',
    middleNameV: 'Middle Name  ',
    lastNameV: 'Last Name  ',

    //groom
    title: 'शीर्षक',
    firstName: 'प्रथम नाव (इंग्लिश ) ',
    middleName: 'मधले नाव (इंग्लिश ) ',
    lastName: 'आडनाव (इंग्लिश ) ',
    firstNamee: 'प्रथम नाव',
    middleNamee: 'मधले नाव',
    lastNamee: 'आडनाव',
    firstNamemr: 'प्रथम नाव (मराठी) ',
    middleNamemr: 'मधले नाव (मराठी) ',
    lastNamemr: 'आडनाव (मराठी) ',
    BirthDate: 'जन्म दिनांक  ',
    Gender: 'लिंग',
    AadharNo: 'आधार नंबर',
    Age: 'वय (लग्नाच्या वेळीचे वय)',
    mobileNo: 'दूरध्वनी क्रमांक',
    phoneNo: 'फोन नंबर',
    email: 'ई-मेल',

    flatBuildingNo: 'फ्लॅट नंबर (इंग्लिश ) ',
    buildingName: 'अपार्टमेंट नाव (इंग्लिश ) ',
    roadName: 'गल्लीचे नाव (इंग्लिश ) ',
    Landmark: 'जमीन चिन्ह (इंग्लिश ) ',
    villageName: 'Village Name (English) ',
    cityName: 'शहराचे नाव (इंग्लिश ) ',

    flatBuildingNomr: 'फ्लॅट नंबर (मराठी) ',
    buildingNamemr: 'अपार्टमेंट नाव (मराठी) ',
    roadNamemr: 'गल्लीचे नाव (मराठी) ',
    Landmarkmr: 'जमीन चिन्ह (मराठी) ',
    villageNamemr: 'Village Name (Marathi) ',
    cityNamemr: 'शहराचे नाव (मराठी) ',

    // flatBuildingNo: 'फ्लॅट नंबर',
    // buildingName: 'अपार्टमेंट नाव',
    // roadName: 'गल्लीचे नाव',
    // Landmark: 'जमीन चिन्ह',
    // villageName: 'गावाचे नाव ',
    // cityName: 'शहराचे नाव',
    // state: "राज्य (इंग्लिश ) ",
    statemr: 'राज्य (मराठी)  ',
    stateMr: 'राज्य (मराठी)  ',

    pincode: 'पिन कोड',
    Religion1: 'जन्माने धर्म',
    Religion2: 'दत्तक घेऊन धर्म',
    StatusOfMarrige: 'लग्नाच्या वेळची स्थिती',
    AgeDocument: 'वयाचे कागदपत्र',
    IdDocument: 'ओळख कागदपत्र ',
    residentialDocument: 'रहिवाशी कागदपत्र',
    StatusOfDocument: 'कागदपत्र स्थिती ',

    //groomFather
    firstNameF: 'वडिलांचं प्रथम नाव  ',
    middleNameF: 'वडिलांचं मधले नाव  ',
    lastNameF: 'वडिलांचं आडनाव  ',
    AgeF: 'वडिलांच वय',
    mobileNoF: 'वडिलांचं दूरध्वनी क्रमांक',
    AadharNoF: 'वडिलांचं आधार नंबर',

    //groomMother
    firstNameM: 'आईचे प्रथम नाव  ',
    middleNameM: 'आईचे मधले नाव  ',
    lastNameM: 'आईचे आडनाव  ',
    AgeM: 'आईचे वय',
    mobileNoM: 'आईचे दूरध्वनी क्रमांक',
    AadharNoM: 'आईचे आधार नंबर',

    //prist
    placeofMarriage: 'लग्नाचे ठिकाण (इंग्लिश )',
    placeofMarriage1: 'लग्नाचे ठिकाण (मराठी) ',

    //witness
    address: 'पत्ता',
    wRelation: 'साक्षीदारशी नाते',
    wDocument: 'साक्षीदाराचे कागदपत्र',
    witnessAdd: 'साक्षीदार जोडा',

    //Document

    DBProof: 'जन्म तारीख पुरावा',
    ResProof: 'रहिवासाचा पुरावा',
    IdProof: 'ओळखपत्र पुरावा',
    ResProofW1: 'प्रथम साक्षीदार रहिवासाचा पुरावा',
    ResProofW2: 'द्वितीय साक्षीदार रहिवासाचा पुरावा',
    ResProofW3: 'तृतिय साक्षीदार रहिवासाचा पुरावा',
    marrigeRelatedDoc: 'विवाह संबंधित दस्तऐवज',

    invetaionCard: 'विवाह निमंत्रण पत्रिका / प्रतिज्ञापत्र ',
    marrigePhotoC: 'विवाह छायाचित्र (जोडीचे) ',
    marDrf: '१०० रुपयांच्या स्टॅम्प पेपरवर अर्जाचा मसुदा तयार करा',

    DivorcePaper: 'वैध घटस्फोट कागद (लागू असल्यास)',
    DeathC: 'मृत्यू प्रमाणपत्र (लागू असल्यास)',
    certiByReligiousPlc:
      ' मंदिर, मशीद इ. धार्मिक स्थळाद्वारे जारी केलेले प्रमाणपत्र',
    docFormat:
      ' (फक्त jpg.jpeg.png.bmp.pdf फाइल अपलोड करण्याची परवानगी आहे. फोटो आकार कमाल 100 kb)',
    enterDoc: 'दस्तऐवजाच नाव ',

    //board
    applicantName: 'अर्जदाराचे नाव ',
    boardNameT: 'विवाह मंडळचे नाव',
    boardName: 'विवाह मंडळचे नाव (इंग्लिश ) ',
    boardNamemr: 'विवाह मंडळचे नाव (मराठी) ',

    remark: 'शेरा',
    documentList: 'दस्तऐवज यादी',
    ValidtyofMBR: 'विवाह मंडळाची अंतिम वैधता',
    documentsUploadF: 'दस्तऐवज अपलोड',
    TandC: '',
    //button
    back: 'मागे',
    next: 'पुढे',
    add: 'जोडा',
    save: 'जतन करा',
    update: 'अद्यायावत करा',
    clear: 'रिक्त',
    exit: 'बाहेर पडा',
    submit: 'प्रस्तुत करणे',
    addFile: 'फाइल जोडा',

    //table filed
    srNo: 'अनुक्रमांक',
    actions: 'क्रिया ',
    hName: 'वरचे नाव',
    wName: 'वधूचे नाव',
    ApplicantName: 'अर्जदाराचे नाव',

    //brudcrum
    newMarriageRegistration: 'विवाह नोंदणी / नवीन विवाह नोंदणी ',
    BoardMarriageRegistration: 'विवाह मंडळ नोंदणी / नवीन विवाह मंडळ नोंदणी ',

    //module: 'शहर नियोजन',
    dashboard: 'पिंपरी-चिंचवड महानगरपालिका डॅशबोर्ड',
    // master: 'मास्टर्स',
    // transactions: 'व्यवहार',
    // report: 'अहवाल',
    // masterPath: 'शहर नियोजन/ मास्टर ',
    // transactionPath: 'शहर नियोजन/ व्यवहार ',
    // reportPath: 'शहर नियोजन/ अहवाल ',

    // //breadcrum
    // landReservationPath: 'शहर नियोजन/ मास्टर / जमीन आरक्षण',
    // tdrZoneGatAndVillageMappingPath:
    //   'शहर नियोजन/ मास्टर / टीडीआर प्रभाग-गट आणि गाव मॅपिंग',
    // villageWiseLandReservationEntryPath:
    //   'शहर नियोजन/ मास्टर / गावनिहाय जमीन आरक्षण नोंद',
    // villageMappingWithDesignationPath:
    //   'शहर नियोजन/ मास्टर / पदनामासह गाव मॅपिंग',

    // //titles
    // landReservation: 'जमीन आरक्षण',
    // tdrZoneGatAndVillageMapping: 'टीडीआर प्रभाग-गट आणि गाव मॅपिंग',
    // villageWiseLandReservationEntry: 'गावनिहाय जमीन आरक्षण नोंद',
    // villageMappingWithDesignation: 'पदनामासह गाव मॅपिंग',

    // //other labels
    // landReservationID: 'जमीन आरक्षण क्र',
    // reservationName: 'आरक्षणाचे नाव',
    // reservationNameEng: 'आरक्षणाचे नाव इंग्रजीत',
    // reservationNameMr: 'आरक्षणाचे नाव मराठीत',
    // surveyNumber: 'सर्वेक्षण क्र',
    // landReservationLegend: 'जमीन आरक्षण आख्यायिका',
    // reservationAreaInHector: 'हेक्टर मध्ये आरक्षण क्षेत्र',
    // landInPossession: 'ताब्यात जमीन',
    // remark: 'टिप्पणी',
    // villageName: 'गावाचे नाव',
    // gatName: 'गटाचे नाव',
    // zoneName: 'झोनचे नाव',
    // landReservationName: 'जमीन आरक्षण नाव',
    // citySurveyNo: 'शहर सर्वेक्षण क्र',
    // reservationNo: 'आरक्षण क्र',
    // landNotInPossessionInHector: 'ताब्यात नसलेली जमीन (हेक्टरमध्ये)',
    // landInPossessionInHector: 'ताब्यात जमीन (हेक्टरमध्ये)',
    // ddtp: 'डी.डी.टी.पी',
    // deAndTp: 'उपअभियंता /नगर नियोजक',
    // atpAndJe: 'सहाय्यक नगर नियोजक /कनिष्ठ अभियंता',

    // attachFile: 'फाईल जोडा',
    // srNo: 'अनु क्र',
    // actions: 'क्रिया ',

    // //buttons
    // add: 'जोडा',
    // save: 'जतन करा',
    // update: 'अद्यायावत करा',
    // clear: 'रिक्त',
    // exit: 'बाहेर पडा',
    // back: 'मागे',
    // saveAndNext: 'जतन करा आणि पुढे',
    // finish: 'समाप्त',

    //ReIssuance of Marriage Certificate

    onlyRIMC: 'विवाह प्रमाणपत्र पुन्हा जारी करणे',
    mRegNo: 'विवाह रजि क्र',
    marriageDate: 'लग्नाची तारीख',
    marriageYear: 'लग्नाचे वर्ष',
    brideName: 'वधूचे नाव',
    groomName: 'वराचे नाव',
    regDate: 'नोंदणी दिनांक',

    //Renewal of Marriage Board Registration
    onlyRMBR: 'विवाह मंडळ नोंदणीचे नूतनीकरण',
    mbrName: 'विवाह मंडळ नोंदणी नाव',
    mbrDate: 'विवाह मंडळ नोंदणी तारीख',
    mbrYear: 'विवाह मंडळ नोंदणी वर्ष',
    search: 'शोधा',

    //Application Details

    onlyApplDetail: 'अर्ज तपशील',
    applFName: 'अर्जदाराचे पहिले नाव',
    applMName: 'अर्जदाराचे मधले नाव',
    applLName: 'अर्जदार आडनाव',
    groomFName: 'वराचे पहिले नाव',
    groomMName: 'वराचे मधले नाव',
    groomLName: 'वराचे आडनाव',
    brideFName: 'वधूचे पहिले नाव',
    brideMName: 'वधू मधले नाव',
    brideLName: 'वधू आडनाव',
    mDate: 'लग्नाची तारीख',

    //ReIssuance of marriage Certificate
    newRMItable: 'विवाह प्रमाणपत्र पुन्हा जारी करणे',
    applFullName: 'अर्जदाराचे पूर्ण नाव',
    applicationNo: 'अर्ज क्र',
    applicationDate: 'अर्ज तारीख',
    action: 'क्रिया',
    enterRemarkForApplication: 'Enter Remark',
    cancellSlot: 'स्लॉट रद्द करा',

    documentName: 'दस्तऐवजाचे नाव',
    documentDetails: 'दस्तऐवज तपशील',
    depositRefundProcess: 'अनामत रक्कम परतावा',
    bookingDate: 'बुकिंग तारीख',
    applicationDetails: 'अर्ज तपशील',
    billDetails: 'बिल तपशील',
    notesheetOrReferenceNo: 'नोटशीट/संदर्भ क्र.',
    billDate: 'बिलाची तारीख',
    approverName: 'अनुमोदकाचे नाव',
    approvalDate: 'मंजुरीची तारीख',
    authority: 'प्राधिकरण',
    noApplicationsFound: 'कोणतेही अर्ज आढळले नाहीत',
    viewApplication: 'अर्ज पहा',
    searchByApplicationNumber: 'अर्ज क्रमांकाद्वारे शोधा',
    showFirst: 'पहिले',
    equipmentsDetails: 'उपकरणांचे तपशील',
    equipmentName: 'उपकरणाचे नाव',
    rate: 'दर',
    quantity: 'प्रमाण',
    calculatedCharge: 'गणना केलेले शुल्क',
    total: 'एकूण',
    otherEn: 'इतर (इंग्रजीमध्ये)',
    otherMr: 'इतर (मराठीत)',
    charge: 'चार्ज',
    otherCharges: 'इतर शुल्क',
    adjustedDeposit: 'समायोजित ठेव',
    equipmentCharges: 'उपकरणे शुल्क',
    refundableAmount: 'परत करण्यायोग्य रक्कम',

    //reports
    departmentServiceWiseReport: 'विभाग सेवानिहाय अहवाल',
    facilityVenueWiseRegister: 'सुविधेचे ठिकाण प्रमाणे नोंदणी अहवाल',
    customSelection: 'सानुकूल निवड',
    facilityWiseRegister: 'सुविधानिहाय नोंदणी अहवाल',
    bookingCancellationReport: 'बुकिंग रद्द करण्याचा अहवाल',
    zoneWiseFacilityRefundRegister: 'झोननिहाय सुविधा परतावा नोंदवही अहवाल',
    zoneWiseGroundRegistrationDemandCollection:
      'झोननिहाय ग्राउंड नोंदणी मागणी संकलन अहवाल',
    zoneWiseSportFacilityAndVenueWiseDemandCollection:
      'झोननिहाय क्रीडा सुविधा आणि स्थळनिहाय मागणी संकलन अहवाल',
  },
}
