export default {
  en: {
    type: "commonLabels",

    module: "SkySign Management System",
    // dashboard: 'PCMC Dashboard',
    dashboard: "Pimpri-Chinchwad Municipal Corporation Dashboard",
    master: "Masters",
    transactions: "Transactions",
    report: "Reports",
    masterPath: "SkySign / Master ",
    transactionPath: "SkySign / Transaction ",
    reportPath: "SkySign / Report ",
    type: "master",
    master: "Masters",
    masterPath: "SkySign/ Master",
    applicantName: "Applicant Name",

    //breadcrum
    courtPath: "SkySign / Master /Court",
    advocatePath: "SkySign / Master /Advocate",
    serviceHierachyPath: "SkySign / Master / Service Hierachy",
    caseTypePath: "SkySign/ Master / Case Type",
    caseSubTypePath: "SkySign / Master / Case Sub Type",
    caseStagesPath: "SkySign/ Master / Case Stages",
    employeeAndUserCreationPath:
      "SkySign / Master / Employee and User Creation",
    counterSchedulingPath: "SkySign / Master / Counter Scheduling",
    smsEmailWhatsAppTemplatesPath:
      "SkySign / Master / SMS / Email/WhatsApp Templates",
    userAuthenticationAndRoleRightsPath:
      "SkySign / Master / User Authentication and Role-Rights",
    changeResetForgetPasswordPath:
      "SkySign / Master / Change or Reset or ForgetPassword",
    calendarSchedulingPath: "SkySign / Master / Calendar Scheduling",

    //label title
    court: "Court",
    advocate: "Advocate",
    serviceHierachy: "Service Hierarchy",
    caseType: "Case Type",
    caseSubType: "Case Sub-Type",
    caseStages: "Case-Stage",
    employeeAndUserCreation: "Employee and User Creation",
    counterScheduling: " Counter Scheduling",
    smsEmailWhatsAppTemplates: " SMS / E-mail / Whatsapp Template",
    userAuthenticationAndRoleRights: " User Authentication and Role Rights",
    changeResetForgetPassword: "Change / Reset / Forget Password",
    calendarScheduling: " Calender Scheduling",

    //other labels

    courtName: "Court Name",

    address: "Address",

    landmark: "Landmark",
    cityOrVillage: "City / Village",
    pincode: "Pincode *",
    area: "Area",
    areaEn: "Area (In English)",
    areaMr: "Area (In Marathi)",

    name: "Name",

    phone: "Phone No.",
    email: "E-mail",

    advocateCreation: "Advocate Created Successfully",
    advocateDetails: "Advocate Details",
    bankDetails: "Bank Details",
    documentUpload: "Documents Upload",

    advocateCategory: "Advocate Category ",
    nameOfBarCouncil: "Name Of Bar Council *",
    remarks: "Remarks",
    bankName: "Bank Name *",
    branchName: "Branch Name *",
    accountNo: "Account No. *",
    bankIFSC: "Bank IFSC code *",
    bankMICR: "Bank MICR code *",
    application: "Application:",
    panCard: "Pan Card:",
    barCouncilCertificate: "Bar Council Certificate:",
    bankPassbook: "Bank Passbook:",
    subType: "Sub-Type",

    //Remarks
    selectDate: "Please select a date",
    selectTitle: "Please select a title",
    enterFName: "Please enter first name ",
    enterMName: "Please enter middle name ",
    enterLName: "Please enter last name ",
    selectAdvocateCategory: "Please select a category",
    enterCouncilName: "Please enter council name",
    enterArea: "Please enter area ",
    enterRoadName: "Please enter road name ",
    enterLandmark: "Please enter a landmark ",
    enterCity: "Please enter a city ",
    enterPinCode: "Please enter a pincode ",
    enterPhoneNo: "Please enter a phone no. ",
    enterMobileNo: "Please enter a mobile no. ",
    enterEmailAddress: "Please enter an e-mail. ",
    enteraadhaarNo: "Please enter an aadhaar no. ",
    enterpanNo: "Please enter an pan no. ",
    enterRemarks: "Please enter a remark. ",

    attachFile: "Attach File",
    srNo: "Sr. No",
    actions: "Actions",
    entersNumbers: "Please Enters Numbers Only",

    //buttons
    add: "Add",
    save: "Save",
    update: "Update",
    clear: "Clear",
    exit: "Exit",
    back: "Back",
    saveAndNext: "Save & Next",
    finish: "Finish",

    type: "transactions",

    transactions: "Transactions",
    transactionPath: "SkySign / Transaction",

    //breadcrum
    industryLicensePath:
      "SkySign / Transactions / Issuance of Industry License",

    //title
    industryLicense: "Issuance of Industry License",
    businessLicense: "Issuance of Business License",
    skySignLicense: "Issuance of SkySign License",
    storeLicense: "Issuance of Store License",
    caseEntry: "Case Entry",
    siteVisit: "Site Visit",
    reIssuanceOfIndustry: "ReIssuance of Industry License",
    reBusinessLicense: "ReIssuance of Business License",
    reskySignLicense: "ReIssuance of SkySign License",
    restoreLicense: "ReIssuance of Store License",

    //other labels
    or: "Or",
    serviceNames: "Service Name",
    applicationNumber: "Application Number",
    applicationDate: "Application Date",
    applicantType: "Applicant Type",
    applicationStatus: "Application Status",
    manager: "Manager",
    title: "Title (In English)",
    fname: "First Name (In English)",
    mname: "Middle Name (In English)",
    lname: "Last Name (In English)",
    titleMr: "Title (In Marathi)",
    fnameMr: "First Name (In Marathi)",
    mnameMr: "Middle Name (In Marathi)",
    lnameMr: "Last Name (In Marathi)",
    gender: "Gender",
    dateOfBirth: "Birth date ",
    age: "Age",
    mobile: "Mobile No.",
    email: "E-mail",
    panNo: "Pan No.",
    aadharNo: "Aadhaar No.",
    tax: "Tax",
    skysigndetails: "Sky Sign Details",
    advertisementtype: "Advertisement Type",
    mediaSubType: "Media Sub Type",
    mediaType: "Media Type",
    skysignInfo: "Skysign Info",
    skysignDemension: "SkySign Dimension",
    length: "Lenght(sq ft)",
    breadth: "Breadth(sq ft)",
    serviceChargeTypeName: "ServiceCharge",
    terraceCheckBox: "Height of Skysign From Level Terrace",
    heightOfSkysign: "Height of Skysign",
    heightFromGround: "Height of Skysign From Ground",
    heightFromTerrace: "Height from Terrace",
    DistanceFromPoachMarg: "Distance of SkySign From Poach Marg",
    heightOfSkysigncenterlineRoad: "Distance of SkySign From Road CenterLine",
    heightOfSkysignRoadLevel: "Height of SkySign From Road Level",
    consentofpropertyholder: "Consent of Property Holder?",
    openland: "Is the Skysign Location in Open Land",
    humanhabitat: "Is the Skysign Loaction in Human Habitat",
    dateofplacement: "Date of Placement",
    durationofvalidity: "Duration of Skysign Validity",
    additionalinfo: "Additional Info",
    fromdate: "From Date",
    todate: "To Date",
    isilluminated: "Is Illuminated?",
    quantity: "Quantity",
    baselicensefees: "Base License Fees",
    zonepremium: "Zone Premium",
    roadpremium: "Road Premium",
    centraldividerpremium: "Central Divider Premium",
    totallicfees: "Total License Fees",
    illuminationpremium: "Illumination Premium",
    groundrent: "Ground Rent",
    groundrentannum: "Ground Rent Per Annum",
    totalannualdemand: "Total Annual Demand",
    administrativeAndSupervisionFees: "Administrative And Supervision Fees(5%)",
    gst: "G.S.T in case of Municipal Property(18%)",
    industryaddress: "Industrial Address",
    businessaddress: "Business Address",
    storeAddress: "Store Address",
    isavailable: "Is Available",
    crPropertyTaxNumber: "Property Tax No",
    proprtyAmount: "Property Amount",
    waterAmount: "Water Amount",
    crWaterConsumerNo: "Water Consumer No",
    crCitySurveyNumber: "City Survey No/Block No/Sector No/Survey No",
    crCitySurveyNumber1: "Select Below Type",
    crAreaName: "Area Name",
    crLandmarkName: "Landmark Name*",
    crVillageName: "Village Name *",
    crPincode: "Pin code",
    crLattitude: "Lattitude",
    crCityName: "City Name *",
    crState: "State",
    nameOfOrganization: "Organization Name",
    nameOfBusiness: "Business Name",
    nameOfIndustry: "Industry Name",
    nameOfStore: "Store Name",
    propertyStatus: "Property Status",
    ownership: "Ownership",
    totalAreaFt: "Total Area (Sq.ft.)",
    totalAreaM: "Total Area (Sq.M.)",
    zone: "Zone *",
    noOfEmployees: "no of employees",
    zonename: "Zone Name ",
    areaname: "Area Name ",
    licenseType: "License Type",
    businessType: "Business Type",
    storeType: "Store Type",
    businessSubType: "Business SubType",
    unitType: "Unit Type",
    constructionType: "Construction Type",
    constructionAreaM: "Construction Area (Sq.M.)",
    constructionAreaFt: "Construction Area (Sq.ft.)",
    roadName: "Road Name *",
    villageName: "Village Name",
    machineCount: "Flour mill machine count",
    businessLocationTotalCountOfMachineries:
      "Total number of machines in the industry",
    officeStaff: "Office Staff",
    permanentEmployees: "Permanent Employees",
    temporaryEmployees: "Temporary Employees",
    contractualEmployees: "Contractual Employees",
    totalEmployees: "Total Employees",
    workingHours: "Daily Working Hours(In Hrs)",
    fireEquirepment: "Is there firefighting equipment available?",
    firstAidKit: " Are there first-aid kits available? * ",
    toilets: "Are any toilet facilities available? *",
    ObjectionCertificate:
      "Have you got a No Objection Certificate from your neighbors? *",
    nuisanceOfResidents:
      "Is the business likely to be a nuisance to the surrounding residents? *",
    disposalSystemOfWaste:
      "Is there a system for disposing of waste generated?*",
    storageofrawmaterial:
      "Is there a separate storage arrangement for raw materials or finished products? *",
    bussdate:
      "If the company is still in operation, then the date of commencement of Industry?",
    separatebusiness: "Do other items have a separate business license?",
    tanNo: "Tan No.",
    gstNo: "GST No.",
    registrationNo: "Registration No",
    manager: "Manager",
    director: "Director",
    owner: "Owner",
    applicantInformation: "Applicant Information",
    crLongitud: "Longitude",
    issuanceofLicense: "Basic Application Info",
    applicantDetails: "Applicant Details",
    aadharAuthentication: "Aadhaar Authentication",
    hoardingDetails: "Hoarding Details",
    skySignBusinessDetails: "SkySign Bussiness Details",
    skySignRate: "SkySign Rate",
    addressOfLicense: "Address of Applicant",
    industryInfo: "Industry Infomation",
    businessInfo: "Business Information",
    storeInfo: "Store Info",
    employeeDetaills: "Employee Details",
    partenershipDetail: "Partnership Detail",
    chargeName: "Charge Name",
    documentUpload: "Documents Upload",
    oTPVERIFICATION: "OTP VERIFICATION",
    currentAddress: "Current Address",
    postalAddress: "Permanent / Postal Address",
    permanentCorrespondence: "Permanent Address as the Correspondence Address",
    organizationInformation: "Organization Information",
    storeInformation: "Store Information",
    industryDate:
      "If the company is still in operation, then the date of commencement of Industry?",
    storeDate:
      "If the store is still in operation, then the date of commencement of Store?",
    temporarylicDate:
      "Date of issuance of temporary license subject to conditions in Notarized Guarantee ",
    thankYou: "Thank You",
    applicantIsFirm: "In case of applicant is firm/organization",
    Parteners: "Partner",
    yes: "Yes",
    no: "No",
    registrarionCertificate:
      "Shop Act License/SSI Registrarion Certificate/Factory Act*",
    buildingCommencementCertificate:
      "Building Commencement Certificate/ Property Tax Extract/ Building Completion Certifcate *",
    rawsiteviewermap: "Raw site viewer map",
    slumNOC:
      " In case of Flour Mill location is in Slum - NOC from Slum development Department/SRA Department",
    foodLicense:
      "In case of Flour Mill license - Food License required from Medical Officer",
    agreementLetter:
      "In case of tenant/partner - Consent letter/ Agreement Letter/ Leave and License Letter required from Property Holder",
    occupancyCertificate: "Occupancy Certificate",
    environmentalNoc:
      "Stone Crusher machine and Brick kiln or similar license, No Objection Certificate required from Environmental Departemnt of PCMC",
    plotNo: "Plot No.",
    citysurveyno: "City survey no",
    blockno: "Block no",
    sectorno: "Sector no",
    surveyno: "Survey no",
    selfownership: "self ownership",
    ConsentofPropertyholder: "Consent of Property holder",
    skysignlocationOpenland: "Is the skysign location is in  Open land?",
    skysignlocationhumanhabitat:
      "Is the skysign location is in  human habitat? ",
    dateofplacement: "Date of placement",
    durationofValidity: "Duration of Validity",
    additionalInfo: "Additional Info",
    industryType: "Industry Type",
    enterotp: "Enter Otp",
    pay: "Pay",
    viewBill: "View Bill",
    serviceCharge: "Service Charges",
    durationOfLicenseValidity: " Duration of License Validity",
    licenseValidity: "License Validity",
    chargesDetails: "Charges Details",
    financialYear: "Financial Year",
    calendarYear: "Calendar Year",
    dateOfIssuance: "date of Issuance",
    rate: "Rate",
    amount: "Amount",
    total: "Total",
    totalInWords: "Total in Words",
    generateLoi: "Generate LOI",
    previewLoi: "Preview LOI",
    verifyLoi: "Verify LOI",
    loiPrinting: "LOI Printing",
    loiCollection: "LOI Collection",
    paymentMode: "Payment Mode",
    paymentType: "Payment Type",
    receiptModeDetails: "Receipt  Details",
    receiptNumber: "Receipt No",
    receiptDate: "Receipt Date",
    receiptAmount: "Reciept Amount",
    type: "commonLabels",
    search: "Search",
    loiNO: "LOI NO.",
    loiDetails: "LOI Details",
    and: "And",
    loiDate: "LOI Date",
    applicationNo: "Application No.",
    dateOfIssuance: "Date of Issuance",
    calendarYear: "Calendar Year",
    financialYear: "Financial Year",
    bankAccountNo: "Bank Account no",
    ddNo: "DD No",
    ddDate: "DD Date",
    siteVisitAppointmentSchedule: "Site Visit Appointment Schedule",
    addSlotsOfSiteVisit: "Add Slots Of Site Visits",
    addMore: "Add More",
    delete: "Delete",
    bookNow: "Book Now",
    submit: "Submit",

    //buttons
    sendOTP: "Send OTP",

    add: "Add",
    save: "Save",
    update: "Update",
    clear: "Clear",
    exit: "Exit",
    back: "Back",
    saveAndNext: "Save & Next",
    finish: "Finish",
    partener: "Add Partner",
    APPROVE: "APPROVE",
    REASSIGN: "Revert",
    reject: "Reject",
    backToHome: "Back To home ",
    print: "Print",
    //Remark

    attachFile: "Attach File",
    type: "report",
    slab: "Slab",
    flourMill: "Flour Mill",
    flat: "Flat",
    quantity: "Quantity",
    businessValue: "Business Type Value",
    storeValue: "Store Type Value",
    applicantPartner: "Is Applicant a partner?",
    removePartner: "Remove Partner",
    applicantAddress: "Applicant Address",
    addPartnerCheckBoxTitle: "Is Applicant not a Sole Partner in the Business?",
    sentTime: "Sent Time",
    remark: "Remark",
    sentbyuser: "Sent By User",
    sentDate: "Sent Date",
    applicationHis: "Application History",
    photo1TextField: "Enter Information Of the 1st Photo",
    photo2TextField: "Enter Information Of the 2nd Photo",
    photo3TextField: "Enter Information Of the 3rd Photo",
    photo4TextField: "Enter Information Of the 4th Photo",
    photo5TextField: "Enter Information Of the 5th Photo",

    subZoneAreaMaster: "Sub-Zone Area Master",

    subZoneArea: "Sub-Zone Area",

    subZoneName: "Sub-Zone Name",
    subZoneNameEn: "Sub-Zone (In English)",
    subZoneNameMr: "Sub-Zone (In Marathi)",

    subZoneMaster: "Sub Zone Master",

    zoneMaster: "Zone-Master",

    zoneNameEn: "Zone Name(In English)",
    zoneNameMr: "Zone Name(In Marathi)",
    zoneUserMappingMaster: "Zone-User Mapping Master",
    user: "User",
    skysignInformation: "Skysign Information",
    agencyInformation: "Agency Information",
    nameOfAgency: "Name Of Agency",
    // subZoneName:"Sub Zone Name",
    areaName: "Area",
    status: "Status",
    agencyAddress: "Agency Address",
    skySignDetails: "SkySign Details",
    mediaType: "Media Type",
    mediaSubType: "Media Sub Type",
    formOfAdvertisement: "Form Of Advertisement",
    natureOfAdvertisement: "Nature Of Advertisement Applied",
    isDisplayOfFreeBaner: "Are you Applying for display of free Banner?",
    purpose: "Purpose",
    periodFrom: "Period From",
    periodTo: "Period To",
    noOfLocation: "No Of Location",
    categoryOfCivicMessage: "Category Of Civic Message",
    messageOfFreeBanner: "Message on Free banner",
    isTrustRegistrationAttached:
      "Whether Photocopy of Trust Registeration attached?",
    dimensions: "Dimensions",
    totalArea: "Total Area",
    height: "Height",
    width: "Width",
    length: "Length",
    siteLocationDetails: "Site Location Details",
    siteLocation: "Site Location",
    nameOfTheRoadDrawingVisibility: "Name Of The Road Drawing Visibility",
    widthOfRoad: "Width Of Road",
    noOfHoardingLocatedWithin25mtr: "No Of Hoarding Located Within 25 Meter",
    noOfTrees: "No Of Trees within 25 meters on either side",
    isTreesRequired: "Whether Trees are Required to cut?",
    landlordDetails: "Landlord Details",
    nameOfLandlord: "Name Of Landlord",
    isNocOfLandlordSubmitted: "Is NOC Of Landlord Submitted?",
    whetherDocumentsAreSubmitted:
      "Whether the documents submitted as per rule 17(b)",

    yourPaymentDoneSuccess: " Your payment done successful!!!",
    paymentFailed: "Payment failed!!!",
    orderId: "Order Id ",
    trackingId: "Tracking Id",
    bankRefNo: "Bank Reference No",
    billingName: "Billing Name",
    billingAdd: "Billing Address",
    billingCity: "Billing City",
    billingZip: "Billing Zipcode ",
    billingCountry: "Billing Country",
    billingEmail: "Billing Email",
    mobileNo: "Mobile No",
    billingState: "Billing State",
    transactionDate: "Transaction Date",
    goToList: "Go To List",
    totalAmount: "Total Amount",
    loiNo: "LOI No",

    fromTime: "From Time",
    toTime: "To Time",
    numberOfSlots: "No.of SLots",

    backToHomeBtn: "Back To Home",
  },
  mr: {
    type: "commonLabels",

    module: "परवाना व्यवस्थापन प्रणाली",
    // dashboard: 'डॅशबोर्ड',
    dashboard: "पिंपरी-चिंचवड महानगरपालिका डॅशबोर्ड",
    master: "मास्टर्स",
    transactions: "व्यवहार",
    report: "अहवाल",
    masterPath: "परवाना/ मास्टर ",
    transactionPath: "परवाना/ व्यवहार ",
    reportPath: "परवाना/ अहवाल ",
    type: "master",
    applicantName: "अर्जदाराचे नाव",

    master: "मास्टर्स",
    transaction: "व्यवहार",
    report: "अहवाल",
    masterPath: "परवाना/ मास्टर ",
    transactionPath: "परवाना/ व्यवहार ",
    reportPath: "परवाना/ अहवाल ",

    //breadcrum
    courtPath: "परवाना/ मास्टर /न्यायालय",
    advocatePath: "परवाना/ मास्टर /वकील",
    serviceHierachyPath: "परवाना/ मास्टर / सेवा पदानुक्रम",
    caseTypePath: "परवाना/ मास्टर / प्रकरणाचा प्रकार",
    caseSubTypePath: "परवाना/ मास्टर / प्रकरणाचा उप-प्रकार",
    caseStagesPath: "परवाना/ मास्टर / प्रकरण-टप्पे",
    employeeAndUserCreationPath:
      "परवाना/ मास्टर / कर्मचारी आणि वापरकर्ता निर्मिती",
    counterSchedulingPath: "परवाना/ मास्टर / काउंटर शेड्युलिंग",
    smsEmailWhatsAppTemplatesPath:
      "परवाना/ मास्टर / संदेश सेवा / इलेक्ट्रॉनिक संदेश/ व्हॉट्सॲप साचा",
    userAuthenticationAndRoleRightsPath:
      "परवाना/ मास्टर / वापरकर्ता प्रमाणीकरण आणि भूमिका-अधिकार",
    changeResetForgetPasswordPath:
      "परवाना/ मास्टर / बदल किंवा पुनर्प्रस्थापित किंवा पासवर्ड विसरलात",
    calendarSchedulingPath: "परवाना/ मास्टर / दिनदर्शिका शेड्युलिंग",

    //titles

    advocate: "वकील",
    serviceHierachy: "सेवा पदानुक्रम",
    caseType: "प्रकरणाचा प्रकार",
    caseSubType: "प्रकरणाचा उप-प्रकार",
    caseStages: "प्रकरण-टप्पे",
    employeeAndUserCreation: "कर्मचारी आणि वापरकर्ता निर्मिती",
    counterScheduling: " काउंटर शेड्युलिंग",
    smsEmailWhatsAppTemplates:
      " संदेश सेवा / इलेक्ट्रॉनिक संदेश/ व्हॉट्सॲप साचा",
    userAuthenticationAndRoleRights: " वापरकर्ता प्रमाणीकरण आणि भूमिका-अधिकार",
    changeResetForgetPassword:
      "बदल किंवा पुनर्प्रस्थापित किंवा पासवर्ड विसरलात",
    calendarScheduling: " दिनदर्शिका शेड्युलिंग",

    //other labels

    courtName: "न्यायालयाचे नाव",
    address: "पत्ता",
    roadName: "रस्त्याचे नाव",
    landmark: "महत्त्वाची खूण",
    cityOrVillage: "शहर / गाव",
    pincode: "पिनकोड",
    area: "क्षेत्राचे नाव",
    areaEn: "क्षेत्राचे नाव (इंग्रजी मध्ये)",
    areaMr: "क्षेत्राचे नाव (मराठी मध्ये)",

    name: "नाव",

    phone: "दूरध्वनी नं.",
    email: "इलेक्ट्रॉनिक संदेश",

    advocateCreation: "वकिल यशस्वीपणे तयार केला",
    advocateDetails: "वकील तपशील",
    bankDetails: "बँक तपशील",
    documentUpload: "दस्तऐवज अपलोड",
    advocateCategory: "वकील श्रेणी",
    nameOfBarCouncil: "वकिलांचे मंडळचे प्रमाणपत्र परिषदचे नाव *",
    remarks: "टिप्पणी *",
    bankName: "बँकेचे नाव *",
    branchName: "शाखेचे नाव *",
    accountNo: "खाता क्रमांक *",
    bankIFSC: "बँक IFSC कोड *",
    bankMICR: "बँक MICR कोड *",
    application: "अर्ज:",

    panCard: "पॅन कार्ड:",
    barCouncilCertificate: "वकिलांचे मंडळचे प्रमाणपत्र:",
    bankPassbook: "बँक पासबुक:",
    subType: "उप-प्रकार",

    attachFile: "फाईल जोडा",
    srNo: "अनुक्रमांक",
    actions: "क्रिया ",
    entersNumbers: "कृपया फक्त क्रमांक प्रविष्ट करा",

    //Remarks
    selectDate: "कृपया तारीख निवडा",
    selectTitle: "कृपया शीर्षक निवडा",
    enterFName: "कृपया पहिले नाव भरा ",
    enterMName: "कृपया मधले  नाव भरा ",
    enterLName: "कृपया शेवटचे नाव भरा ",
    selectAdvocateCategory: "कृपया वकील श्रेणी निवडा",
    enterCouncilName: "कृपया वकिलांचे मंडळचे प्रमाणपत्र परिषदचे नाव भरा",
    enterArea: "कृपया क्षेत्राचे नाव भरा ",
    enterRoadName: "कृपया रस्त्याचे नाव भरा ",
    enterLandmark: "कृपया  महत्त्वाची खूण भरा",
    enterCity: "कृपया  शहराचे / गावाचे नाव भरा ",
    enterPinCode: "कृपया पिनकोड भरा",
    enterPhoneNo: "कृपया दूरध्वनी नं. भरा",
    enterMobileNo: "कृपया मोबाईल नं. भरा",
    enterEmailAddress: "कृपया इलेक्ट्रॉनिक संदेश भरा",
    enteraadhaarNo: "कृपया आधार नं. भरा",
    enterpanNo: "कृपया पॅन नं. भरा",
    // enterRemarks: 'कृपया टिप्पणी. भरा',
    enterRemarks: "कृपया टिप्पणी. द्या",

    //buttons
    add: "जोडा",
    save: "जतन करा",
    update: "अद्यायावत करा",
    clear: "रिक्त",
    exit: "बाहेर पडा",
    back: "मागे",
    saveAndNext: "जतन करा आणि पुढे",
    finish: "समाप्त",
    APPROVE: "मंजूर करा",

    REASSIGN: "पुन्हा नियुक्त करा",
    reject: "नाकारा",
    type: "transactions",
    backToHome: "मागे जा ",
    print: "प्रिंट",
    transactions: "व्यवहार",
    transactionPath: "परवाना/ व्यवहार ",

    //breadcrum

    industryLicensePath: "परवाना / व्यवहार /उद्योगधंदा परवाना जारी करणे",
    caseEntryPath: "परवाना / व्यवहार /प्रकरणाची नोंदणी",

    //titles
    industryLicense: "नवीन उद्योगधंदा परवाना जारी करणे",
    businessLicense: "व्यवसाय परवान्याचा विमा",
    skySignLicense: "जाहिरात परवाना जारी करणे",
    storeLicense: "स्टोअर परवाना जारी करणे",
    caseEntry: "प्रकरणाची नोंदणी",
    siteVisit: "Site Visit",
    reIssuanceOfIndustry: "ReIssuance of Industry License",
    reBusinessLicense: "ReIssuance of Business License",
    reskySignLicense: "ReIssuance of SkySign License",
    restoreLicense: "ReIssuance of Store License",
    siteVisitAppointmentSchedule: "साइट भेट भेटीचे वेळापत्रक",
    addSlotsOfSiteVisit: "साइट भेटींचे स्लॉट जोडा",
    addMore: "आणखी जोडा",
    delete: "हटवा",
    bookNow: " बुक करा",
    submit: "प्रस्तुत करणे",

    //other labels
    or: "Or",
    serviceNames: "सेवा",
    applicationNumber: "अर्ज क्रमांक",
    applicationDate: "अर्जाची तारीख",
    applicantType: "अर्जदाराचा प्रकार",
    applicationStatus: "अर्जाची स्थिती",
    manager: "व्यवस्थापक",
    title: "शीर्षक (इंग्रजीमध्ये)",
    fname: "पहिले नाव (इंग्रजीमध्ये)",
    mname: "मधले नाव (इंग्रजीमध्ये)",
    lname: "आडनाव (इंग्रजीमध्ये)",
    titleMr: "शीर्षक (मराठीत)",
    fnameMr: "पहिले नाव (मराठीत)",
    mnameMr: "मधले नाव (मराठीत)",
    lnameMr: "आडनाव (मराठीत)",
    gender: "लिंग",
    dateOfBirth: "जन्मदिनांक",
    age: "वय",
    mobile: "मोबाईल नं.",
    email: "इ-मेल आयडी",
    panNo: "पॅन नं.",
    aadharNo: "आधार नं.",
    tax: "कर",
    skysigndetails: "जाहिरात परवाना माहिती",
    advertisementtype: "जाहिरातीचे प्रकार ",
    mediaSubType: "माध्यम उपप्रकार",
    mediaType: "माध्यम प्रकार",
    skysignInfo: "जाहिरात माहिती",
    skysignDemension: "जाहिरातीचे परिमाण",
    length: "लांबी(चौ .मी)",
    breadth: "रुंदी(चौ .मी)",
    heightOfSkysign: "जमिनीपासून आकाशचिन्हाची उंची ",
    terraceCheckBox: "गच्चीच्या पातळीपासून फलकांची उंची (फूट) ",
    serviceChargeTypeName: "Service charge Name",
    heightFromGround: "फलकांची जमिनीपासून तळभागापर्यंत उंची ",
    heightFromTerrace: "गच्चीच्या पातळीपासून फलकांची उंची (फूट )",
    DistanceFromPoachMarg: "फलकाचे पोहोच मार्गाचे विराम रेषेपासून अंतर ",
    heightOfSkysigncenterlineRoad:
      "फलकांची  रस्त्यांच्या रास्तरेषा रुंदीपासून अंतर (फूट)",
    heightOfSkysignRoadLevel:
      "फलकांची रस्त्याच्या पातळीपासूनची वरील उंची (फूट) ",
    consentofpropertyholder:
      "आकाशचिन्ह लावण्यास जागेच्या मालकीची संमती आहे काय ?",
    openland: "आकाशचिन्ह लावण्याचे ठिकाण खुल्या जागेत आहे काय ?",
    humanhabitat: "आकाशचिन्ह लावण्याचे ठिकाण मनुष्य वस्तीत आहे काय?",
    dateofplacement: "आकाशचिन्ह  कोणत्या तारखेपासून लावण्याचे आहे?",
    durationofvalidity: "आकाशचिन्ह किती मुदतीपर्यंत लावावयाची आहे ?",
    additionalinfo: "इतर माहिती ",
    fromdate: "या तारखेपासून ",
    todate: "या तारखेपर्यंत ",
    isilluminated: "प्रकाशित आहे ",
    quantity: "एकूण संख्या",
    baselicensefees: "बेस परवाना शुल्क ",
    zonepremium: "झोन प्रीमियम ",
    roadpremium: "रस्ते  प्रीमियम ",
    illuminationpremium: "प्रकाश प्रीमियम",
    centraldividerpremium: "केंद्रीय विभक्त प्रीमियम",
    totallicfees: "एकूण परवाना शुल्क ",
    groundrent: "ग्राउंड भाडे",
    groundrentannum: "ग्राउंड भाडे प्रति वर्ष ",
    totalannualdemand: "एकूण वार्षिक मागणी ",
    administrativeAndSupervisionFees: "प्रशासकीय आणि पर्यवेक्षण फीस(५%)",
    gst: "जी. एस. टी महानगरपालिकेच्या मिळकतीबाबतीत (१८%)",
    industryaddress: "औद्योगिक पत्ता",
    businessaddress: "व्यवसायाचा पत्ता",
    storeAddress: "स्टोअर पत्ता",
    isavailable: "उपलब्ध आहेत",
    crPropertyTaxNumber: "मालमत्ता कर क्र.",
    proprtyAmount: "रक्कम",
    waterAmount: "रक्कम",
    crWaterConsumerNo: "पाणी ग्राहक क्र.",
    crCitySurveyNumber: "सिटी सर्व्हे नंबर/ब्लॉक नंबर/सेक्टर नंबर/सर्व्हे क्र",
    crCitySurveyNumber1: "खालील प्रकार निवडा",
    crAreaName: "क्षेत्राचे नाव",
    crLandmarkName: "महत्त्वाची खूण",
    crVillageName: "गावाचे नाव",
    crPincode: "पिन कोड",
    crLattitude: "अक्षांश",
    crCityName: "शहराचे नाव",
    crState: "राज्य",
    nameOfOrganization: "संस्थेचे नाव",
    nameOfBusiness: "व्यवसायाचे नाव",
    nameOfIndustry: "उद्योगाचे नाव",
    nameOfStore: "स्टोअरचे नाव",
    propertyStatus: "मालमत्तेची स्थिती",
    ownership: "मालकीचा प्रकार",
    totalAreaFt: "एकूण क्षेत्रफळ (चौ. फूट)",
    totalAreaM: "एकूण क्षेत्रफळ (चौ.मी)",
    zone: "झोन",
    zonename: "झोन चे नाव",
    areaname: "क्षेत्राचे नाव",
    licenseType: "परवाना प्रकार",
    businessType: "व्यवसाय प्रकार",
    storeType: "स्टोअर प्रकार",
    businessSubType: "व्यवसाय उपप्रकार",
    unitType: "युनिट प्रकार",
    constructionType: "बांधकाम प्रकार",
    constructionAreaM: "बांधकाम क्षेत्र (चौ.मी)",
    constructionAreaFt: "बांधकाम क्षेत्र (चौ. फूट)",
    roadName: "रस्त्याचे नाव",
    villageName: "गावाचे नाव",
    machineCount: "पीठ गिरणी एकुण मशिनरी संख्या",
    businessLocationTotalCountOfMachineries:
      "व्यवसायाचे जागेवरील एकुण मशिनरी संख्या",
    officeStaff: "कार्यालयीन कर्मचारी",
    permanentEmployees: "कायम कामगार",
    temporaryEmployees: "तात्पुरते कामगार",
    contractualEmployees: "कंत्राटी कर्मचारी",
    totalEmployees: "एकूण कर्मचारी",
    workingHours: "कामाचे तास",
    fireEquirepment: "अग्निशमन साधने उपलब्ध आहेत का ?",
    firstAidKit: "प्रथमोपचार किट उपलब्ध आहेत का ?",
    toilets: "शौचालयाची सुविधा उपलब्ध आहे का?*",
    ObjectionCertificate:
      "तुम्हाला तुमच्या शेजाऱ्यांकडून ना हरकत प्रमाणपत्र मिळाले आहे का ?",
    nuisanceOfResidents:
      "व्यवसायामुळे आसपासच्या रहिवाशांना त्रास होण्याची शक्यता आहे का ?",
    disposalSystemOfWaste:
      "निर्माण होणाऱ्या कचऱ्याची विल्हेवाट लावण्याची व्यवस्था आहे का ?",
    storageofrawmaterial:
      "कच्चा माल किंवा तयार उत्पादनांसाठी वेगळी साठवण व्यवस्था आहे का ?",
    bussdate: "उद्योगधंदा चालु असलेस चालु केल्याची तारीख",
    separatebusiness: "इतर वस्तूंना स्वतंत्र व्यवसाय परवाना आहे का ?",
    tanNo: "टॅन क्र.",
    gstNo: "जीएसटी क्र.",
    registrationNo: "नाॊंदणी क्रमांक",
    manager: "व्यवस्थापक",
    director: "संचालक",
    owner: "मालक",
    applicantInformation: "अर्जदाराची माहिती",
    crLongitud: "रेखांश",
    issuanceofLicense: "मूलभूत अनुप्रयोग माहिती",
    applicantDetails: "अर्जदाराचे तपशील",
    aadharAuthentication: "आधार प्रमाणीकरण",
    hoardingDetails: "होर्डिंग तपशील",
    skySignBusinessDetails: "जाहिरात परवाना तपशील ",
    skySignRate: "जाहिरात कर",
    addressOfLicense: "पत्ता",
    industryInfo: "उद्योग माहिती",
    businessInfo: "व्यवसाय माहिती",
    storeInfo: "स्टोअर माहिती",
    employeeDetaills: "कर्मचारी तपशील ",
    partenershipDetail: "भागीदारी तपशील",
    chargeName: "Charge Name",
    documentUpload: "दस्तऐवज अपलोड",
    oTPVERIFICATION: "OTP पडताळणी",
    currentAddress: "सध्याचा पत्ता",
    postalAddress: "कायमस्वरूपी/ टपालाचा  पत्ता",
    permanentCorrespondence: "पत्रव्यवहाराचा पत्ता म्हणून कायमचा पत्ता",
    organizationInformation: "संस्थेची माहिती ",
    storeInformation: "स्टोअर माहिती",
    industryDate: "जर कंपनी अजूनही चालू असेल, तर उद्योग सुरू होण्याची तारीख?",
    storeDate: "जर स्टोअर अजूनही चालू असेल, तर स्टोअर सुरू होण्याची तारीख?",
    temporarylicDate:
      "तात्पुरता परवाना जारी करण्याची तारीख नोटरीकृत हमीमधील अटींच्या अधीन आहे",
    thankYou: "धन्यवाद",
    applicantIsFirm: "अर्जदाराच्या बाबतीत फर्म/संस्था आहे",
    Parteners: "भागीदारी",
    yes: "होय",
    no: "नाही",
    registrarionCertificate:
      "दुकान कायदा परवाना/एसएसआय नोंदणी प्रमाणपत्र/फॅक्टरी कायदा",
    buildingCommencementCertificate:
      "इमारत प्रारंभ प्रमाणपत्र / मालमत्ता कर उतारा / इमारत पूर्णत्व प्रमाणपत्र *",
    rawsiteviewermap: "कच्चा स्थळ दर्शक नकाशा",
    slumNOC:
      "पीठ गिरणीचे स्थान झोपडपट्टीत असल्यास - झोपडपट्टी विकास विभाग/एसआरए विभागाकडून एनओसी",
    foodLicense:
      "पीठ गिरणी परवान्याच्या बाबतीत - वैद्यकीय अधिकाऱ्याकडून अन्न परवाना",
    agreementLetter:
      "भाडेकरू/भागीदाराच्या बाबतीत - मालमत्ताधारकाकडून संमतीपत्र/करारपत्र/रजा आणि परवाना पत्र आवश्यक",
    occupancyCertificate: "भोगवटा प्रमाणपत्र",
    environmentalNoc:
      "स्टोन क्रशर मशीन आणि वीटभट्टी किंवा तत्सम परवाना, PCMC च्या पर्यावरण विभागाकडून ना हरकत प्रमाणपत्र आवश्यक",
    plotNo: "प्लॉट क्र.",
    citysurveyno: "सिटी सर्वे क्र.",
    blockno: "ब्लॉक क्र.",
    sectorno: "सेक्टर क्र.",
    surveyno: "सर्वे क्र.",
    selfownership: "स्वत:ची मालकी",
    ConsentofPropertyholder: "मालमत्ताधारकाची संमती",
    skysignlocationOpenland: "आकाशचिन्हाचे स्थान खुल्या जमिनीत आहे का?",
    skysignlocationhumanhabitat: "आकाशचिन्हाचे स्थान मानवी वस्तीत आहे का?",
    dateofplacement: "प्लेसमेंटची तारीख",
    durationofValidity: "वैधतेचा कालावधी",
    additionalInfo: "अतिरिक्त माहिती",
    industryType: "उद्योगधंदा प्रकार",
    enterotp: "Otp प्रविष्ट करा",
    pay: "बिल भरा",
    viewBill: "बिल पहा",
    durationOfLicenseValidity: " Duration of License Validity",
    licenseValidity: "License Validity",
    chargesDetails: "Charges Details",
    financialYear: "Financial Year",
    calendarYear: "Calendar Year",
    dateOfIssuance: "Date of Issuance ",
    serviceCharge: "Service Charges",
    rate: "Rate",
    amount: "Amount",
    total: "Total",
    totalInWords: "Total in Words",
    generateLoi: "Generate LOI",
    previewLoi: "Preview LOI",
    verifyLoi: "Verify LOI",
    loiPrinting: "LOI Printing",
    loiCollection: "LOI Collection",
    paymentMode: "Payment Mode",
    paymentType: "Payment Type",
    receiptModeDetails: "Receipt  Details",
    receiptNumber: "Receipt No",
    receiptDate: "Receipt Date",
    receiptAmount: "Reciept Amount",
    type: "commonLabels",
    search: "Search",
    loiNO: "LOI NO.",
    loiDetails: "LOI Details",
    and: "And",
    loiDate: "LOI Date",
    applicationNo: "अर्ज क्र.",
    dateOfIssuance: "Date of Issuance",
    calendarYear: "Calendar Year",
    financialYear: "Financial Year",
    bankAccountNo: "Bank Account no",
    ddNo: "DD no",
    dDDate: "DD Date",

    //buttons
    sendOTP: "OTP पाठवा",

    add: "जोडा",
    save: "जतन करा",
    update: "अद्यायावत करा",
    clear: "रिक्त",
    exit: "बाहेर पडा",
    back: "मागे",
    saveAndNext: "जतन करा आणि पुढे",
    finish: "समाप्त",
    partener: "भागीदार जोडा",

    // Remark
    attachFile: "फाईल जोडा",

    type: "report",

    slab: "स्लॅब",
    flourMill: "पिठाची चक्की",
    flat: "फ्लॅट",
    quantity: "प्रमाण",
    businessValue: "व्यवसाय प्रकार मूल्य",
    storeValue: "स्टोअर प्रकार मूल्य",
    applicantPartner: "अर्जदार भागीदार आहे का?",
    removePartner: "भागीदार काढा",
    applicantAddress: "अर्जदाराचा पत्ता",
    addPartnerCheckBoxTitle: "अर्जदार हा व्यवसायातील एकमेव भागीदार नाही का?",
    sentTime: "पाठवण्याची वेळ",
    remark: "टिप्पणी",
    sentbyuser: "वापरकर्त्याने पाठवले",
    sentDate: "पाठवण्याची तारीख",
    applicationHis: "अर्ज इतिहास",
    photo1TextField: "पहिल्या फोटोची माहिती एंटर करा",
    photo2TextField: "दुसऱ्या फोटोची माहिती एंटर करा",
    photo3TextField: "तिसऱ्या फोटोची माहिती एंटर करा",
    photo4TextField: "चौथ्या फोटोची माहिती एंटर करा",
    photo5TextField: "पाचव्या फोटोची माहिती एंटर करा",

    subZoneAreaMaster: "उप-क्षेत्र क्षेत्र मास्टर",
    subZoneArea: "उप-झोन क्षेत्र",

    subZoneName: "उप-क्षेत्राचे नाव",
    subZoneMaster: "सब-झोन मास्टर",

    subZoneNameEn: "उप-क्षेत्र (इंग्रजी मध्ये)",

    subZoneNameMr: "उप-क्षेत्र (मराठी मध्ये)",

    zoneMaster: "झोन मास्टर",

    zoneNameEn: "झोनचे नाव(इंग्रजी मध्ये)",
    zoneNameMr: "झोनचे नाव(मराठी मध्ये)",

    zoneUserMappingMaster: "झोन-वापरकर्ता मॅपिंग मास्टर",
    user: "वापरकर्ता",
    skysignInformation: "आकाशचिन्ह माहिती",

    //pg labels
    yourPaymentDoneSuccess: " तुमचे पेमेंट यशस्वी झाले!!!",
    paymentFailed: "पेमेंट अयशस्वी !!!",
    orderId: "ऑर्डर आयडी ",

    trackingId: "ट्रॅकिंग आयडी",
    bankRefNo: "बँक संदर्भ क्र",
    billingName: "बिलिंग नाव",
    billingAdd: "बिलाचा पत्ता",
    billingCity: "बिलिंग शहर",
    billingZip: "बिलिंग पिन कोड ",
    billingCountry: "बिलिंग देश",
    billingEmail: "बिलिंग ईमेल",
    mobileNo: "मोबाईल क्र",
    transactionDate: "व्यवहाराची तारीख",
    billingState: "बिलिंग राज्य",
    goToList: "सूचीवर जा",
    loiNo: "हेतू पत्र क्र",
    totalAmount: "एकूण रक्कम",

    fromTime: "वेळेपासून",
    toTime: "वेळेपर्यंत",
    numberOfSlots: "स्लॉटची संख्या",

    backToHomeBtn: "परत",
  },
};
