export default {
  en: {
    zoneCertificateDetails: "Zone Certificate Details",
    setBackCertificateDetails: "Set Back Certificate Details",
    module: "Town Planning",
    dashboard: "Pimpri-Chinchwad Municipal Corporation Dashboard",
    master: "Masters",
    transactions: "Transactions",
    report: "Reports",
    masterPath: "Town Planning / Master ",
    transactionPath: "Town Planning / Transaction ",
    reportPath: "Town Planning / Report ",
    partPlanDetails: "Part Plan Details",
    partPlan: "Part Plan",
    viewLocationOnMap: "View Location On Map",
    //breadcrum
    landReservationPath: "Town Planning / Master / Land Reservation ",
    ZoneGatAndVillageMappingPath:
      "Town Planning / Master / Zone Gat and Village Mapping",
    villageWiseLandReservationEntryPath:
      "Town Planning / Master / Village Wise Land Reservation Entry",
    villageMappingWithDesignationPath:
      "Town Planning / Master / Village Mapping With Designation",
    partMapPath: "Town Planning / Transaction / Part Map",
    zoneCertificatePath: "Town Planning / Transaction / Zone Certificate",
    developementPlanOpinionPath:
      "Town Planning / Transaction / Development Plan Opinion",

    //label title
    landReservation: "Land Reservation",
    ZoneGatAndVillageMapping: "Zone Gat and Village Mapping",
    villageWiseLandReservationEntry: "Village Wise Land Reservation Entry",
    villageMappingWithDesignation: "Village Mapping With Designation",
    partMap: "Part Map",
    zoneCertificate: "Zone Certificate",
    developementPlanOpinion: "Development Plan Opinion",
    setBackCertificate: "Set Back Certificate",
    attachmentSchema: "Attachments",
    //other labels
    landReservationID: "Land Reservation ID",
    reservationName: "Reservation Name",
    reservationNameEn: "Reservation Name in English",
    reservationNameMr: "Reservation Name in Marathi",
    surveyNumber: "Survey No.",
    landReservationLegend: "Land Reservation Legend",
    reservationAreaInHector: "Road Area (In Hector)",
    reservationAreaInsqmtr: "Reservation Area (Sq.mtr)",
    landInPossession: "Land in Possession",
    remark: "Remark",
    villageName: "Village Name",
    gatName: "Gat Name",
    zoneName: "Zone Name",
    landReservationNameEn: "Land Reservation Name in English",
    landReservationNameMr: "Land Reservation Name in Marathi",
    citySurveyNo: "City Survey No.",
    reservationNo: "Land Reservation No.",
    landNotInPossessionInHector: "Land Not In Possession (in Hector)",
    landInPossessionInHector: "Land in Possession (in Hector)",
    ddtp: "DDTP ",
    deAndTp: "Dy Engineer /Town Planner",
    atpAndJe: "Asst. Town Planner /Junior Engineer",
    applicationDate: "Application Date",
    applicationNo: "Application No.",
    applicantName: "Applicant Name",
    fullName: "Full Name",
    pincode: "Pincode",
    status: "Status",
    serviceName: "Service Name",
    title: "Title",
    firstNameEn: "First Name (in English)",
    middleNameEn: "Middle Name (in English)",
    surnameEn: "Last Name (in English)",
    firstNameMr: "First Name (in Marathi)",
    middleNameMr: "Middle Name (in Marathi)",
    surnameMr: "Last Name (in Marathi)",
    gender: "Gender",
    mobile: "Mobile",
    panNo: "PAN No.",
    email: "Email",
    aadharNo: "Aadhaar No.",
    serviceCompletionDate: "Service Completion Date",
    isCurrentUser: "Same as logged in user",
    personalDetails: "Personal Details",
    areaDetails: "Area Details",
    area: "Sq. / Mtr",
    documentUpload: "Documents Upload",
    applicationCreated: "Application Submitted Successfully",
    addFile: "Choose File",
    fileName: "File Name",
    mandatoryOrOptional: "Mandatory/Optional",
    mandatory: "Mandatory",
    optional: "Optional",
    upload: "Upload",
    next: "Next",
    preview: "Preview",
    verify: "Verify",
    reject: "Reject",
    noFileFound: "No file found",
    verified: "Verified",
    surveyNo: "Gat No / Survey No.",
    gisLocation: "GIS ID",
    flatNo: "Flat/Building No.",
    buildingName: "Building Name",
    roadName: "Road Name",
    landmark: "Landmark",
    ctsNo: "CTS No.",
    plotNo: "Plot No.",
    documentVerification: "Document Verification",
    legend: "Legend",
    landReservationNo: "Land Reservation No.",
    electoralWard: "Ward",
    landUnderPossession: "Land Under Possession",
    landNotUnderPossession: "Land Not Under Possession",
    appropriateAuthority: "Appropriate Authority",
    authorityNameEn: "Authority Name in English",
    authorityNameMr: "Authority Name in Marathi",
    partmapDetails: "Part Map Details ",
    attachFile: "Attach File",
    srNo: "Sr. No",
    actions: "Actions",

    //Remarks
    selectDate: "Please select a date",
    selectTitle: "Please select a title",
    enterFName: "Please enter first name ",
    enterMName: "Please enter middle name ",
    enterLName: "Please enter last name ",
    selectAdvocateCategory: "Please select a category",
    enterCouncilName: "Please enter council name",
    enterArea: "Please enter area ",
    enterRoadName: "Please enter road name ",
    enterLandmark: "Please enter a landmark ",
    enterCity: "Please enter a city ",
    enterPinCode: "Please enter a pincode ",
    enterPhoneNo: "Please enter a phone no. ",
    enterMobileNo: "Please enter a mobile no. ",
    enterEmailAddress: "Please enter an e-mail. ",
    enteraadhaarNo: "Please enter an aadhaar no. ",
    enterpanNo: "Please enter an pan no. ",
    enterRemarks: "Please enter a remark. ",
    address: "Address",

    //buttons
    add: "Add",
    save: "Save",
    update: "Update",
    clear: "Clear",
    exit: "Exit",
    print: "Print",
    back: "Back",
    saveAndNext: "Save & Next",
    finish: "Finish",

    addDocuments: "Add Documents",
    fileUpload: "File Upload",
    cancel: "Cancel",
    ApplicantName: "Applicant Name",
    statusDetails: "Status Details",
    titlemr: "शीर्षक ",
    ApplicatName: "Applicant Name",
    possessionType: "Possession Type",
    possessionTypeEn: "Possession Type in English",
    possessionTypeMr: "Possession Type in Marathi",

    RoadType: "Road Type",
    RoadTypeEn: "Road Size in English",
    RoadTypeMr: "Road Size in Marathi",

    RoadconstructionType: "Road Construction Type",
    RoadconstructionTypeEn: "Road Construction Type in English",
    RoadconstructionTypeMr: "Road Construction Type in Marathi",

    //Reservation Type
    ReservationType: "Reservation Type",
    ReservationTypeEn: "Reservation Type in English",
    ReservationTypeMr: "Reservation Type in Marathi",

    //reservation details
    possessionDate: "Possession Date",
    ownerName: "Owner Name",
    documentNo: "Document Number / Order Number",
    documentName: "Document Name",

    // road details
    roadLength: "Road Length",
    roadWidth: "Road Width",
    roadNumber: "Road Number",

    sentbyuser: "Sent By User",
    date: "Date",
    time: "Time",
    applicationHis: "Application History",

    remarkModel: "Enter Remark on application",
    APPROVE: "APPROVE",

    REASSIGN: "Revert Back",
    onlyeng: "Must be only characters",
    onlymarathi: "Must be only  marathi",

    //site visit
    siteVisitAppointmentSchedule: "Site Visit Appointment Schedule",
    addSlotsOfSiteVisit: "Add Slots Of Site Visits",
    addMore: "Add More",
    delete: "Delete",
    bookNow: "Book Now",
    siteVisitSchedule: "Site Visit Schedule",
    fromDateValidation: "from date selection is required !!!",
    fromDateValidation: "to date selection is required !!!",
    siteVisit: "Site Visit",
    siteVisitPhoto: "Photos of a Site Visit",
    siteVisitPhoto1: "Site Visit Photo 1",
    siteVisitPhoto2: "Site Visit Photo 2",
    siteVisitPhoto3: "Site Visit Photo 3",
    siteVisitPhoto4: "Site Visit Photo 4",
    siteVisitPhoto5: "Site Visit Photo 5",
    submit: "Submit",
    siteVisitPhotoUpload: "Upload Photos of a Site Visit",
    townplanQuestion: "Town Planning Question",
    roadWithBusinessLocation: "Road Width at Business Location? (in feet)",
    businessHawkinglocation:
      "who is operating the business at the hawking location ?",
    applicantItsSelf: "Applicant its self",
    withHelpofFamilyMembers: "with help of family members",
    byKeepingservant: "by keeping servant",
    inspectionSellingGoods:
      "Did the inspection discover that the applicant is selling goods at the specified location?",
    yes: "Yes",
    no: "No",
    businessTrafficCongestion:
      "Does the business currently cause traffic congestion ?",
    //quastion master
    questionEn: "Question (In English)",
    questionMr: "Question (In Marathi)",
    applicationName: "Application Name",
    questionType: "Question Type",
    questionMaster: "Question Master",
    answerType: "Answer Type",
    checkListType: "Checklist Type",
    answer: "Answer",

    //site visit
    LandDetails: "Land Details",
    BRTCorridore: "BRT Corridore",
    MetroCorridore: "Metro Corridor",
    FloodLine: "Flood Line",
    RedZone: "Red Zone/Buffer Zone",
    ReservationDetail: "Reservation Details",
    PlannedRoad: "Planned Road",
    SpecialZone: "Special Zone",
    AreaZone: "Area Zone",

    applicantDetails: "Applicant Details",
    noOfCopies: "No of Copies",
    charges: "Total Charges",
    chargeName: "Charge Name",
    amount: "Amount",
    totalInWords: "Total Charges in Words",
    totalCharges: "Total Charges",
    applicantDetails: "Applicant Details",
    chargesDetails: "Charges Details",
    paymentMode: "Payment Mode",
    paymentType: "Payment Type",
    receiptDate: "Receipt Date",
    receiptNumber: "Receipt Number",
    receiptAmount: "Receipt Amount",
    ddNo: "Demand Draft Number",
    ddDate: "Demand Draft Date",
    bankName: "Bank Name",
    branchName: "Branch Name",
    bankAccountNo: "Bank Account No",

    cheuqeNo: "Cheuqe Number",
    cheuqeDate: "Cheuqe Date",
    generateLoi: "Generate LOI",
    pay: "PAY",
    //gat Master
    gatMaster: "Gat Master",
    gat: "Gat",
    gatNo: "Gat No.",
    gatNameMr: "Gat Name (In Marathi)",

    applicationDetails: "Application Details",
    applicationName: "Application Name",
    serviceId: "Service Name",
    siteVistType: "Site Visit Type",
    visitDate: "Visit Date",
    siteVisitDetails: "Site Visit Details",
    applicantName: "Applicant Name",
    applicationStatus: "Application Status",
    //TDR / FSI Details
    details: "Details",
    checkList: "CheckList",
    applicationForm: "Application Form",
    selectDRCType: "Select DRC Type",
    selectULB: "Select ULB",
    administrationWard: "Administration Ward",
    reservationType: "Reservation Type",
    reservationName: "Reservation Name",
    reservationNo: "Reservation No",
    applicantAddressMr: "Applicant Address(In marathi)",
    applicantAddress: "Applicant Address(In English)",
    appliName: "Applicant Name(In English)",
    appliNameMr: "Applicant Name(In marathi)",
    drcTypeMr: "DRC Type (in Marathi)",
    drcTypeEn: "DRC Type (in English)",
    //schedule
    fromTime: "From time",
    toTime: "To Time",

    titleInmarathi: "Title (In Marathi)",
    titleInenglish: "Title (In english)",

    DRCNo: "DRC Number",
    nameOfDrcHolder: "Name Of DRC Holder",
    areaInSquareMeter: "Area In Square Meter",
    possessionCertificateNo: "Possession Certificate Number",
    orderNoOfAddCollector: "Order No.Of Additional Collector",
    orderNoOfGovt: "Order No.Of Government",
    zone: "Zone",
    proposalName: "Proposal Name",
    drcCertificate: "DRC Certificate Upload",
    roadSize: "Road Size",
    folioNo: "Folio Number",
    drcDate: "DRC Date",
    fsiCreditArea: "FSI Credit Area",
    subQuestions: "Sub Questions Section",

    // *******************************Validation***************************
    titleRemark: "Please Select Title",
    firstNameVal: "Please Enter First Name(In English)",
    firstNameValMr: "Please Enter First Name(In Marathi)",
    middleNameVal: "Please Enter Middle Name(In English)",
    middleNameValMr: "Please Enter Middle Name(In Marathi)",
    lastNameVal: "Please Enter Last Name(In English)",
    lastNameValMr: "Please Enter Last Name(In Marathi)",
    genderVal: "Please Select Gender",
    addressVal: "Please Enter Address",
    mobileVal: "Please Enter Mobile Number",
    emailVal: "Please Enter Email Address",
    villegeVal: "Please Enter Villege",
    serveyNoVal: "Please Enter Survey Number",
    cityServeyNoVal: "Please Enter City Survey Number",
    panNoVal: "Please Enter PAN Number",
    flatNoVal: "Please Enter Flat/Building Number",
    buildingNameVal: "Please Enter Building Name",
    areaVal: "Please Enter Area(sq./mr)",
    zoneVal: "Please Selct Zone Name",

    authorityNameVE: "Please enter name in english.",
    authorityNameVM: "Please enter name in marathi.",
    gisidV: "Please Enter a GIS ID.",
    legendV: "Please Enter a Legend.",
    villageNameV: "Please select a Village name.",
    ddtpV: "Please select a DDTP name.",
    deAndTpV: "Please select DE or TP name.",
    atpAndJeV: "Please select a ATP or JE name.",
    gatV: "Please select a Gat Name",
    zoneV: "Please select a Zone name.",
    landReservationLegendV: "Please select a Land Reservation Legend",
    landReservationNameEnV: "Please enter Land Reservation Name in english",
    landReservationNameMrV: "Please enter Land Reservation Name in marathi",
    landReservationNumberV: "Please enter Land Reservation Number",
    surveyNoV: "Please enter Survey No",
    citySurveyNoV: "Please Enter City Survey No",
    department: "Department",
    designation: "Designation",
    capture: "Capture",
    oR: "OR",
  },

  mr: {
    oR: "किंवा",
    capture: "कॅप्चर करा",
    designation: "पदनाम",
    department: "विभाग",
    landReservationLegendV: "कृपया एक जमीन आरक्षण आख्यायिका निवडा",
    landReservationNameEnV: "कृपया जमिनीचे आरक्षण नाव इंग्रजीत प्रविष्ट करा",
    landReservationNameMrV: "कृपया जमिनीचे आरक्षण नाव मराठीत प्रविष्ट करा",
    landReservationNumberV: "कृपया जमीन आरक्षण क्रमांक प्रविष्ट करा",
    surveyNoV: "कृपया सर्वेक्षण क्रमांक प्रविष्ट करा",
    citySurveyNoV: "कृपया सिटी सर्व्हे क्रमांक प्रविष्ट करा",
    gatV: "कृपया गट नाव निवडा",
    zoneV: "कृपया झोनचे नाव निवडा.",
    ddtpV: "कृपया डी.डी.टी.पी चे नाव निवडा.",
    deAndTpV: "कृपया उपअभियंता /नगर नियोजक चे नाव निवडा.",
    atpAndJeV: "कृपया सहाय्यक नगर नियोजक /कनिष्ठ अभियंता चे नाव निवडा.",
    villageNameV: "कृपया गावाचे नाव निवडा.",
    legendV: "कृपया एक आख्यायिका प्रविष्ट करा.",
    gisidV: "कृपया GIS ID प्रविष्ट करा.",
    authorityNameVE: "कृपया इंग्रजीमध्ये नाव प्रविष्ट करा.",
    authorityNameVM: "कृपया मराठीमध्ये नाव प्रविष्ट करा.",

    zoneCertificateDetails: "झोन प्रमाणपत्र तपशील",
    setBackCertificateDetails: "सामासिक अंतर तपासणी तपशील",
    partPlanDetails: "भाग योजना तपशील",
    partPlan: "भाग योजना",
    viewLocationOnMap: "नकाशावर स्थान पहा",
    titleInmarathi: "शीर्षक (मराठी मध्ये)",
    titleInenglish: "शीर्षक (इंग्लिश मध्ये)",
    fromTime: "काळापासून",
    toTime: " वेळेला",
    drcTypeMr: "DRC प्रकार (मराठी मध्ये)",
    drcTypeEn: "DRC प्रकार (इंग्रजी मध्ये)",
    applicationStatus: "अर्जाची स्थिती",
    applicantName: "अर्जदाराचे नाव",
    applicationName: "अर्जाचे नाव",
    serviceId: "सेवेचे नाव",
    siteVistType: "साइट भेट प्रकार",
    visitDate: "भेट तारीख",
    siteVisitDetails: "साइट भेट तपशील",
    applicationDetails: "अर्जाचा तपशील",
    //gat Master
    gatMaster: "गट मास्टर",
    gat: "गट",
    gatNo: "गट क्र.",
    gatNameMr: "गट नाव (मराठीत)",
    area: "क्षेत्रफळ चौ. / मीटर",
    pay: "पैसे भरा",
    generateLoi: "स्विकृती पत्र तयार करा",
    attachmentSchema: "संलग्नक",
    ifsc: "आय एफ एस सी कोड",
    accountNumber: "खाते क्रमांक",
    bankName: "बँकेचे नाव",
    branchName: "शाखेचे नाव",
    bankAccountNo: "बँक खाते क्रमांक",
    ddDate: "डिमांड ड्राफ्ट तारीख",
    ddNo: "डिमांड ड्राफ्ट क्रमांक",

    cheuqeDate: "चेक तारीख",
    cheuqeNo: "चेक क्रमांक",

    receiptAmount: "पावती रक्कम",
    receiptNumber: "पावती क्रमांक",
    receiptDate: "पावती तारीख",
    paymentMode: "पेमेंट मोड",
    paymentType: "पैसे भरण्याची पध्दत",
    receiptModeDetails: "Receipt Mode Details",
    chargesDetails: "शुल्क तपशील",
    applicantDetails: "अर्जदाराची माहिती",
    generateLoi: "स्विकृती पत्र तयार करा",
    totalCharges: "एकुण रक्कम",
    totalInWords: "एकुण अक्षरी रक्कम ",
    amount: "रक्कम",
    applicantDetails: "अर्जदाराची माहिती",

    SpecialZone: "विशेष झोन",
    AreaZone: "क्षेत्र झोन",
    PlannedRoad: "नियोजित रस्ते",
    ReservationDetail: "आरक्षण प्रयोजन",
    RedZone: "रेडझोन / बफर झोन",
    FloodLine: "पुर रेषा",
    MetroCorridore: "मेट्रो कॉरिडोर",
    BRTCorridore: "बी आर टी कॉरिडोर ",
    LandDetails: "जमिनीचा तपशील",

    businessTrafficCongestion:
      "व्यवसायामुळे सद्द्यस्थितीत रहदारीस अडथळा होतो का?",
    yes: "होय",
    no: "नाही",
    inspectionSellingGoods:
      "अर्जदार नमूद केलेल्या जागेवर व्यवसाय करीत असल्याचे तपासणीत आढळले?",
    applicantItsSelf: "अर्जदार स्वतः",
    applicantName: "अर्जदाराचे नाव",
    withHelpofFamilyMembers: "कुटुंबातील सदस्यांच्या मदतीने",
    streetVendorPhoto: "फोटो",
    byKeepingservant: "नोकर ठेवून",
    businessHawkinglocation: "व्यवसाय कार्य",
    roadWithBusinessLocation: "व्यवसाय ठिकाणची रस्ता रुंदी(फूट)",
    townplanQuestion: "नगर रचना प्रश्न",
    siteVisitPhotoUpload: "साइट भेटीचे फोटो अपलोड करा",
    submit: "प्रस्तुत करणे",
    siteVisitPhoto1: "साइट भेट फोटो 1",
    siteVisitPhoto2: "साइट भेट फोटो 2",
    siteVisitPhoto3: "साइट भेट फोटो 3",
    siteVisitPhoto4: "साइट भेट फोटो 4",
    siteVisitPhoto5: "साइट भेट फोटो 5",
    siteVisitPhoto: "साइट भेटीचे फोटो",

    siteVisit: "स्थळ भेट",
    addMore: "आणखी जोडा",
    delete: "हटवा",
    bookNow: "Book Now",
    fromDateValidation: "तारीख पासून निवड आवश्यक आहे",
    toDateValidation: "आजपर्यंतची निवड आवश्यक आहे",
    addSlotsOfSiteVisit: "साइट भेटींचे स्लॉट जोडा",
    siteVisitAppointmentSchedule: "साइट भेट भेटीचे वेळापत्रक",

    registerationNo: "मंडळाचा नोंदणी क्रमांक",
    onlyeng: "फक्त इंग्लिश मध्ये",
    onlymarathi: "फक्त मराठी मध्ये",
    APPROVE: "मंजूर करा",

    REASSIGN: "पुन्हा नियुक्त करा",
    remarkModel: "अर्जावर टिप्पणी प्रविष्ट करा",

    oldLabel: "पूर्वीची माहिती",
    applicationHis: "अर्जाचा इतिहास",
    date: "दिनांक",
    time: "वेळ",
    sentbyuser: "वापरकर्त्याने पाठवले",
    // road details
    roadLength: "रस्त्याची लांबी ",
    roadWidth: "रस्त्याची रुंदी",
    roadNumber: "रस्ता क्रमांक",

    documentNo: "दस्तऐवज क्रमांक / ऑर्डर क्रमांक",
    documentName: "दस्तऐवज नाव",
    ownerName: "मालकाचे नाव",
    possessionDate: "ताब्याचा दिनांक",
    //Reservation Type
    ReservationType: "आरक्षण प्रकार",
    ReservationTypeEn: "आरक्षण प्रकार इंग्रजीमध्ये",
    ReservationTypeMr: "आरक्षण प्रकार मराठीमध्ये",

    RoadconstructionType: "रस्त्याचा बांधकामाचा प्रकार",
    RoadconstructionTypeEn: "रस्त्याचा बांधकामाचा प्रकार इंग्रजीमध्ये",
    RoadconstructionTypeMr: "रस्त्याचा बांधकामाचा प्रकार मराठीमध्ये",

    RoadType: "रस्त्याचा प्रकार",
    RoadTypeEn: "रस्त्याचा आकार इंग्रजीमध्ये",
    RoadTypeMr: "रस्त्याचा आकार मराठीमध्ये",

    possessionType: "ताब्याचा प्रकार",
    possessionTypeEn: "ताब्याचा प्रकार इंग्रजीमध्ये ",
    possessionTypeMr: "ताब्याचा प्रकार मराठीमध्ये ",
    address: "पत्ता ",
    ApplicatName: "अर्जदाराच नाव",
    titlemr: "शीर्षक ",
    statusDetails: "स्थिती तपशील",
    ApplicantName: "अर्जादारच नाव",
    partmapDetails: "भाग नकाशा तपशील",
    cancel: "रद्द करा",
    fileUpload: "अपलोड दस्तऐवज",
    addDocuments: "दस्तऐवज जोडा",
    module: "शहर नियोजन",
    dashboard: "पिंपरी-चिंचवड महानगरपालिका डॅशबोर्ड",
    master: "मास्टर्स",
    transactions: "व्यवहार",
    report: "अहवाल",
    masterPath: "शहर नियोजन/ मास्टर ",
    transactionPath: "शहर नियोजन/ व्यवहार ",
    reportPath: "शहर नियोजन/ अहवाल ",

    //breadcrum
    landReservationPath: "शहर नियोजन/ मास्टर / जमीन आरक्षण",
    ZoneGatAndVillageMappingPath:
      "शहर नियोजन/ मास्टर / प्रभाग-गट आणि गाव मॅपिंग",
    villageWiseLandReservationEntryPath:
      "शहर नियोजन/ मास्टर / गावनिहाय जमीन आरक्षण नोंद",
    villageMappingWithDesignationPath:
      "शहर नियोजन/ मास्टर / पदनामासह गाव मॅपिंग",
    partMapPath: "शहर नियोजन / व्यवहार / भाग नकाशा",
    zoneCertificatePath: "शहर नियोजन / व्यवहार / झोन प्रमाणपत्र",
    developementPlanOpinionPath: "शहर नियोजन / व्यवहार / विकास योजना मत",

    //titles
    landReservation: "जमीन आरक्षण",
    ZoneGatAndVillageMapping: "प्रभाग-गट आणि गाव मॅपिंग",
    villageWiseLandReservationEntry: "गावनिहाय जमीन आरक्षण नोंद",
    villageMappingWithDesignation: "पदनामासह गाव मॅपिंग",
    partMap: "भाग नकाशा",
    zoneCertificate: "झोन प्रमाणपत्र",
    developementPlanOpinion: "विकास योजना मत",
    setBackCertificate: "सामासिक अंतर दाखला",

    //other labels
    landReservationID: "जमीन आरक्षण क्र",
    reservationName: "आरक्षणाचे नाव",
    reservationNameEn: "आरक्षणाचे नाव इंग्रजीत",
    reservationNameMr: "आरक्षणाचे नाव मराठीत",
    surveyNumber: "सर्वेक्षण क्र",
    landReservationLegend: "जमीन आरक्षण आख्यायिका",
    reservationAreaInsqmtr: "चौरस मीटर  मध्ये आरक्षण क्षेत्र",

    reservationAreaInHector: "हेक्टर मध्ये रस्त्याचे क्षेत्र",
    landInPossession: "ताब्यात जमीन",
    remark: "टिप्पणी",
    villageName: "गावाचे नाव",
    gatName: "गटाचे नाव",
    zoneName: "झोनचे नाव",
    landReservationNameEn: "जमीन आरक्षणचे नाव इंग्रजी मध्ये",
    landReservationNameMr: "जमीन आरक्षणचे नाव मराठी मध्ये",
    citySurveyNo: "शहर सर्वेक्षण क्र",
    reservationNo: "आरक्षण क्र",
    landNotInPossessionInHector: "ताब्यात नसलेली जमीन (हेक्टरमध्ये)",
    landInPossessionInHector: "ताब्यात जमीन (हेक्टरमध्ये)",
    ddtp: "डी.डी.टी.पी",
    deAndTp: "उपअभियंता /नगर नियोजक",
    atpAndJe: "सहाय्यक नगर नियोजक /कनिष्ठ अभियंता",
    applicationDate: "अजाणची तारीख",
    applicationNo: "अर्ज क्रमांक",
    fullName: "पूर्ण नाव",
    Zone: "झोन",
    pincode: "पिन कोड",
    status: "स्थिती",
    serviceName: "सेवेचे नाव",
    title: "शीर्षक",
    firstNameEn: "अर्जदाराचे पहिले नाव (इंग्रजी मध्ये)",
    middleNameEn: "अर्जदाराचे मधले नाव (इंग्रजी मध्ये)",
    surnameEn: "अर्जदाराचे शेवटचे नाव (इंग्रजी मध्ये)",
    firstNameMr: "अर्जदाराचे पहिले नाव (मराठी मध्ये)",
    middleNameMr: "अर्जदाराचे मधले नाव (मराठी मध्ये)",
    surnameMr: "अर्जदाराचे शेवटचे नाव (मराठी मध्ये)",
    gender: "लिंग",
    mobile: "मोबाईल",
    panNo: "पॅन नं",
    email: "ईमेल पत्ता",
    aadharNo: "आधार क्र.",
    serviceCompletionDate: "सेवा पूर्ण होण्याची तारीख",
    isCurrentUser: "लॉग इन केलेल्या वापरकर्त्याप्रमाणेच",
    personalDetails: "वैयक्तिक माहिती",
    areaDetails: "क्षेत्र तपशील",
    documentUpload: "दस्तऐवज अपलोड",
    addFile: "फाइल जोडा",
    fileName: "फाईलचे नाव",
    mandatoryOrOptional: "अनिवार्य/पर्यायी",
    mandatory: "अनिवार्य",
    optional: "पर्यायी",
    verify: "सत्यापित",
    reject: "नाकारा",
    noFileFound: "कोणतीही फाइल आढळली नाही",
    verified: "तपासून झाले",
    surveyNo: "गटाचे नाव / सर्वेक्षण क्र",
    gisLocation: "GIS क्रमांक",
    flatNo: "फ्लॅट/इमारत क्र",
    buildingName: "इमारतीचे नाव",
    roadName: "रस्त्याचे नाव",
    landmark: "महत्त्वाची खूण",
    ctsNo: "सीटीएस क्र.",
    plotNo: "भूखंड क्र.",
    documentVerification: "दस्तऐवज सत्यापन",
    legend: "आख्यायिका",
    electoralWard: "प्रभाग",
    landUnderPossession: "ताब्यात असलेली जमीन",
    landNotUnderPossession: "ताब्यात नसलेली जमीन",
    appropriateAuthority: "समुचित प्राधिकरण",
    landReservationNo: "जमिनीचे आरक्षण क्र",
    authorityNameEn: "समुचित प्राधिकरणाचे इंग्रजीमध्ये नाव",
    authorityNameMr: "समुचित प्राधिकरणाचे मराठीमध्ये नाव",

    upload: "अपलोड करा",
    next: "पुढे",
    preview: "पूर्वावलोकन",

    attachFile: "फाईल जोडा",
    srNo: "अनु क्र",
    actions: "क्रिया ",

    //Remarks
    selectDate: "कृपया तारीख निवडा",
    selectTitle: "कृपया शीर्षक निवडा",
    enterFName: "कृपया पहिले नाव भरा ",
    enterMName: "कृपया मधले  नाव भरा ",
    enterLName: "कृपया शेवटचे नाव भरा ",
    enterCouncilName: "कृपया वकिलांचे मंडळचे प्रमाणपत्र परिषदचे नाव भरा",
    enterArea: "कृपया क्षेत्राचे नाव भरा ",
    enterRoadName: "कृपया रस्त्याचे नाव भरा ",
    enterLandmark: "कृपया  महत्त्वाची खूण भरा",
    enterCity: "कृपया  शहराचे / गावाचे नाव भरा ",
    enterPinCode: "कृपया पिनकोड भरा",
    enterPhoneNo: "कृपया दूरध्वनी नं. भरा",
    enterMobileNo: "कृपया मोबाईल नं. भरा",
    enterEmailAddress: "कृपया इलेक्ट्रॉनिक संदेश भरा",
    enteraadhaarNo: "कृपया आधार नं. भरा",
    enterpanNo: "कृपया पॅन नं. भरा",
    // enterRemarks: 'कृपया टिप्पणी. भरा',
    enterRemarks: "कृपया टिप्पणी. द्या",
    //quastion master
    questionEn: "प्रश्न (इंग्रजी मध्ये)",
    questionMr: "प्रश्न (मराठी मध्ये)",
    applicationName: "अर्जाचे नाव",
    questionType: "प्रश्न प्रकार",
    questionMaster: "प्रश्न मास्टर",
    answerType: "उत्तर प्रकार",
    checkListType: "चेकलिस्ट प्रकार",
    answer: "उत्तर",
    // question:"प्रश्न",
    //buttons
    add: "जोडा",
    save: "जतन करा",
    update: "अद्यायावत करा",
    clear: "रिक्त",
    exit: "बाहेर पडा",
    print: "छापणे",
    back: "मागे",
    saveAndNext: "जतन करा आणि पुढे",
    finish: "समाप्त",
    //TDR / FSI Details
    details: "तपशील",
    checkList: "चेकलिस्ट",
    applicationForm: "अर्ज",
    selectDRCType: "DRC प्रकार निवडा",
    selectULB: "ULB निवडा",
    administrationWard: "प्रशासन प्रभाग",
    reservationType: "आरक्षणाचा प्रकार",
    reservationName: "आरक्षणाचे नाव",
    reservationN: "आरक्षण क्रमांक",
    applicantAddressMr: "अर्जदाराचा पत्ता(मराठी मध्ये)",
    applicantAddress: "अर्जदाराचा पत्ता(इंग्रजी मध्ये)",
    appliName: "अर्जदाराचे नाव(इंग्रजी मध्ये)",
    appliNameMr: "अर्जदाराचे नाव(मराठी मध्ये)",

    // TDR/FSI >> UTILIZATIONS
    DRCNo: "DRC क्रमांक",
    nameOfDrcHolder: "DRC धारकाचे नाव",
    areaInSquareMeter: "चौरस मीटर मध्ये क्षेत्र",
    possessionCertificateNo: "ताबा प्रमाणपत्र क्रमांक",
    orderNoOfAddCollector: "अतिरिक्त जिल्हाधिकाऱ्यांचा आदेश क्र",
    orderNoOfGovt: "शासनाचा आदेश क्रमांक",
    zone: "झोन",
    proposalName: "प्रस्तावाचे नाव",
    drcCertificate: "DRC प्रमाणपत्र अपलोड",
    roadSize: "रस्त्याचा आकार",
    folioNo: "फोलिओ क्रमांक",
    drcDate: "DRC तारीख",
    fsiCreditArea: "FSI क्रेडिट एरिया",

    subQuestions: "उपप्रश्न विभाग",
    // *******************************Validation***************************
    titleRemark: "कृपया शीर्षक निवडा",
    firstNameVal: "कृपया प्रथम नाव प्रविष्ट करा (इंग्रजीमध्ये)",
    firstNameValMr: "कृपया प्रथम नाव प्रविष्ट करा (मराठीत)",
    middleNameVal: "कृपया मधले नाव प्रविष्ट करा (इंग्रजीमध्ये)",
    middleNameValMr: "कृपया मधले नाव प्रविष्ट करा (मराठीत)",
    lastNameVal: "कृपया आडनाव प्रविष्ट करा (इंग्रजीमध्ये)",
    lastNameValMr: "कृपया आडनाव प्रविष्ट करा (मराठीत)",
    genderVal: "कृपया लिंग निवडा",
    addressVal: "कृपया पत्ता प्रविष्ट करा",
    mobileVal: "कृपया मोबाईल नंबर टाका",
    emailVal: "कृपया ईमेल प्रविष्ट करा",
    villegeVal: "कृपया गावात प्रवेश करा",
    serveyNoVal: "कृपया सर्वेक्षण क्रमांक प्रविष्ट करा",
    cityServeyNoVal: "कृपया सिटी सर्व्हे नंबर टाका",
    panNoVal: "कृपया पॅन क्रमांक प्रविष्ट करा",
    flatNoVal: "कृपया फ्लॅट/बिल्डिंग नंबर टाका",
    buildingNameVal: "कृपया इमारतीचे नाव प्रविष्ट करा",
    areaVal: "कृपया क्षेत्रफळ (sq./mr) प्रविष्ट करा",
    zoneVal: "कृपया झोनचे नाव निवडा",
  },
};
