export default {
  en: {
    petLicense: "Pet License",
    petAnimal: "Pet Animal",
    area: "Area",
    zone: "Zone",
    ward: "Ward",
    flatOrHouseNo: "Flat/House No.",
    buildingName: "Building Name",
    detailAddress: "Detail Address",
    ownerName: "Owner Name",

    fNameEn: "First Name (In English)",
    mNameEn: "Middle Name (In English)",
    lNameEn: "Last Name (In English)",
    fNameMr: "First Name (In Marathi)",
    mNameMr: "Middle Name (In Marathi)",
    lNameMr: "Last Name (In Marathi)",

    mobileNo: "Mobile no.",
    emailId: "E-mail ID",
    petName: "Pet Name",
    petBirthdate: "Pet Birthdate",
    animalBreed: "Animal Breed",
    animalColor: "Animal Color",
    animalAge: "Animal Age (in YY:MM)",
    animalWeight: "Animal Weight (in kg)",
    animalGender: "Animal Gender",
    antiRabiesVaccinationStatus: "Anti-Rabies Vaccination Status",
    vaccinationDate: "Vaccination Date",
    veterinaryDoctorsName: `Veterinary Doctor's Name`,
    documents: "Documents",
    vaccinationPDF: "Vaccination PDF",
    animalPhoto: "Animal Photo",
    remark: "Remark",
    status: "Status",
    petAnimalEn: "Pet Animal name (In English)",
    petAnimalMr: "Pet Animal name (In Marathi)",
    petBreed: "Pet Breed",
    breedNameEn: "Breed name (In English)",
    breedNameMr: "Breed name (In Marathi)",
    ownerPhotoID: "Owner ID Proof",
    makePayment: "Make Payment",
    generateLicense: "Generate License",
    viewLicense: "View License",
    licenseFor: "License For",
    pcmc: "Pimpri-Chinchwad Municipal Corporation",
    fiscalYear: "F.Y.",
    officeCopy: "OFFICE COPY",
    customerCopy: "CUSTOMER COPY",
    receiptNo: "Receipt No.",
    date: "Date",
    relatedTo: "Related To",
    cfcRefNo: "CFC Ref. No",
    cfcCounterNo: "CFC Counter No.",
    receivedFrom: "Received From",
    serviceName: "Service Name",
    narration: "Narration",
    address: "Address",
    paymentMode: "Payment Mode",
    rupees: "Rupees",
    chequeNo: "Cheque No.",
    chequeDate: "Cheque Date",
    bankName: "Bank Name",
    referenceNo: "Reference No.",
    applicationDate: "Application Date",
    details: "Details",
    payableAmount: "Payable Amount",
    receivedAmount: "Received Amount",
    rebateAmount: "Rebate/Concession Amount",
    advanceAmount: "Advance Amount",
    actualPayableAmount: "Actual Payable Amount",
    totalAmount: "Total Amount",
    amountInWords: "Amount in Words",
    receiverSignature: `Receiver's Signature`,
    tip: "Tip",
    printBy: "Printed By",
    printDateAndTime: "Print Date and Time",
    casePaperNo: "Case Paper No.",
    licenseNo: "License No.",
    ownerAddress: "Owner Address",
    symptoms: "History and Symptoms",
    aknowledgementSlipNo: "Acknowledgement Slip No. (numeric)",
    diagnosisDetail: "Tentative Diagnosis Details",
    medicineDetails: "Medicine Details",
    treatment: "Treatment",
    paymentGateway: "Payment Gateway",
    payment: "Payment",
    payerName: "Payer Name",
    payerAddress: "Payer Address",
    receiptDate: "Receipt Date",
    transactionDate: "Transaction Date",
    treatmentCategory: "Treatment Category",
    casePaperDate: "Case Paper Date",
    accountGlCode: "GL Account Code",
    opd: "Veterinary Dispensary",
    lattitude: "Lattitude",
    longitude: "Longitude",
    city: "City",
    state: "State",
    pincode: "Pincode",
    amount: "Amount (in Rs)",
    paymentType: "Payment Type",
    cfcCode: "CFC Code",
    ddNo: "Demand Draft's No.",
    ddDate: "Demand Draft's Date",
    branchName: "Branch Name",
    ifscCode: "IFSC Code",
    accountNo: "Account No.",
    caseEntry: "Case Entry",
    oldLicense: "Old License",
    fromDate: "From Date",
    toDate: "To Date",
    officeType: "Office Type",
    opdPrefix: `Veterinary Dispensary's Prefix`,
    opdNo: `Veterinary Dispensary's No`,
    opdName: `Veterinary Dispensary's Name`,
    opdOpeningTime: `Veterinary Dispensary's Opening Time`,
    opdClosingTime: `Veterinary Dispensary's Closing Time`,
    opdWorkingDays: `Veterinary Dispensary's Working Days`,
    labFacility: "Lab Facility",
    xRayFacility: "X-Ray Facility",
    opdAddress: `Veterinary Dispensary's Address`,
    flatOrBuildingNo: "Flat/Building No.",
    roadName: "Road Name",
    landmark: "Landmark",
    ipdPrefix: "IPD Shelter Prefix",
    ipdNo: "IPD Shelter No",
    ipdName: "IPD Shelter Name",
    ipdOpeningTime: "IPD Shelter Opening Time",
    ipdClosingTime: "IPD Shelter Closing Time",
    ipdWorkingDays: "IPD Shelter Working Days",
    ipdAddress: "IPD Shelter Address",
    defineIpd: "IPD Shelter",
    defineOpd: "Veterinary Dispensary",
    totalApplications: "Total Applications",
    paidApplications: "Paid Applications",
    unpaidApplications: "Unpaid Applications",
    approved: "Approved",
    reassigned: "Reassigned",
    pending: "Pending",
    underTreatment: "Under Treatment",
    dead: "Dead",
    released: "Released",
    fileName: "File Name",
    mandatoryOrOptional: "Mandatory or Optional",
    upload: "Upload",
    mandatory: "Mandatory",
    optional: "Optional",
    uploadWarning:
      "Please upload file (PDF/JPG/JPEG/PNG) with size less than 10MB !",
    medicine: "Medicine",
    medicineOrInjection: "Medicine/Injection",
    days: "Days",
    dosage: "Dosage",
    addMedicine: "Add Medicine",
    prescription: "Prescription",
    casePaperReceipt: "Case Paper Receipt",
    smallPetIncinerator: "Small Pet Incinerator",
    applicationNo: "Application No.",

    search: "Search",
    preview: "Preview",
    addFile: "Add File",
    srNo: "Sr. No",
    actions: "Actions",
    approve: "Approve",
    reassign: "Reassign",
    agreeAndNext: "Agree & Next",

    yearMaster: "Year Master",
    year: "Year",
    yearEn: "Year (In English)",
    yearMr: "Year (In Marathi)",
    yearPrefix: "Year Prefix",

    summaryCollection: "Summary Collection",
    licenseType: "License Type",
    vms: "Veterinary Management System",
    summaryCollectionReport: "Summary Collection Report",
    animalType: "Animal Type",
    newLicense: "New License",
    renewedLicense: "Renewed Pet License",
    count: "Count",
    feeCollected: "Fee Collected",
    totalFeeCollected: "Total Fee Collected",
    detailCollection: "Detail Collection",
    detailCollectionReport: "Detail Collection Report",
    grandTotal: "Grand Total",
    monthlyReport: "Monthly Report",
    yearlyReport: "Yearly Report",
    month: "Month",

    animalPhotoOne: "Animal Photo 1",
    animalPhotoTwo: "Animal Photo 2",
    animalPhotoThree: "Animal Photo 3",
    reasonForPickUp: "Reason For Picking Up",
    teamName: "Team Name",
    volunteerName: "Volunteer Name",
    teamOrVolunteer: "Team / Volunteer",
    dateOfDeath: "Date of Death",
    deathCertificate: "Death Certificate",
    dateOfRelease: "Date of Release",
    healthCertificate: "Health Certificate",
    kennelNo: "Kennel No.",
    specialInvestingationDescription: "Special Investigation Description",
    specialInvestingationDocument: "Special Investigation Document",
    noSpecialInvestigationDocumentAttached:
      "No Special Investigation Document Attached",
    complainerName: `Complainer's Name`,
    complainerAddress: `Complainer's Address`,
    complainerMobileNo: `Complainer's Mobile`,
    opdTitle: "Treating sick and injured animal through Veterinary Dispensary",
    twentyRs: "₹ 20.00",
    twentyRsWords: "Twenty Rupees only",
    casePaperFee: "Case Paper Fee",
    new: "New",
    existing: "Existing",
    petRegistrationStatus: "Pet Registration Status",
    paymentTable: "Payment Table",
    specialDoc: "Special Document",
    caseDetails: "Case Details",
    caseHistory: "Case History",
    noCaseHistory: "No case history found",

    dateWiseIssuedLicenseExpiry: "Date Wise Issued License Expiry Report",
    dateWiseRenewedLicenseExpiry: "Date Wise Renewed License Expiry Report",
    petLicenseReport: "Pet License Report",
    renewedPetLicenseReport: "Renewed Pet License Report",
    ipdOrOpdReport: `IPD Shelter or Veterinary Dispensary Report`,
    departmentType: "Department Type",

    //Class Master
    class: `Animal Classification`,
    classNameEn: `Animal Classification (In English)`,
    classNameMr: `Animal Classification (In Marathi)`,
    classMaster: `Animal Classification Master`,

    // Type of Vaccine Master
    typeOfVaccine: `Type of Vaccination`,
    typeOfVaccineEn: `Type of Vaccination (In English)`,
    typeOfVaccineMr: `Type of Vaccination (In Marathi)`,
    typeOfVaccineMaster: `Type of Vaccination Master`,

    // Vaccine Used Master
    vaccineUsed: `Vaccine Name`,
    vaccineUsedEn: `Vaccine Name (In English)`,
    vaccineUsedMr: `Vaccine Name (In Marathi)`,
    vaccineUsedMaster: `Vaccine Name Master`,

    // Route of Injection Master
    routeInjection: `Route of Administration`,
    routeInjectionEn: `Route of Administration (In English)`,
    routeInjectionMr: `Route of Administration (In Marathi)`,
    routeInjectionMaster: `Route of Administration Master`,

    // Vaccination Report (Transaction)
    vaccinationReport: `Vaccination Report`,
    vaccinationReportOpdKey: `Veterinary Dispensary's Key`,
    vaccinationReportDate: `Date`,
    vaccinationReportType: `Type of Vaccination`,
    vaccinationReportVaccine: `Vaccine Name`,
    vaccinationReportDose: `Dose`,
    vaccinationReportRoute: `Route of Injection`,
    vaccinationReportInjectionExpiry: `Injection Expiry Date`,
    vaccinationReportVaccinationDueDate: `Vaccination Due Date`,
    noVaccinationHistoryFound: "No Vaccination History Found",

    //Schedule Masterv

    schedule: `Schedule Category`,
    scheduleEn: `Schedule Category (In English)`,
    scheduleMr: `Schedule Category (In Marathi)`,
    scheduleMaster: `Schedule Category Master`,

    //Zoo Animal Master
    zooAnimalMaster: `Zoo Animal Master`,
    animalName: `Animal Name`,
    animalNameEn: `Animal Name (In English)`,
    animalNameMr: `Animal Name (In Marathi)`,

    //Animal Inventory
    male: "Male",
    female: "Female",
    unsexed: "Unsex",
    total: "Total",
    animalInventory: "Animal Inventory",
    zooAnimal: "Zoo Animal",
    dateOfEntry: "Date of Entry",
    openingBalance: "Opening Balance",
    births: "Births",
    acquisitions: "Acquisitions",
    disposals: "Disposals",
    deaths: "Deaths",
    closingBalance: "Closing Balances",
    openingBalanceMale: "Opening Balance(M)",
    openingBalanceFemale: "Opening Balance(F)",
    openingBalanceUnsexed: "Opening Balance(U)",
    birthMale: "Birth(M)",
    birthFemale: "Birth(F)",
    birthUnsexed: "Birth(U)",
    acquisitionMale: "Acquisition(M)",
    acquisitionFemale: "Acquisition(F)",
    acquisitionUnsexed: "Acquisition(U)",
    disposalsMale: "Disposals(M)",
    disposalsFemale: "Disposals(F)",
    disposalsUnsexed: "Disposals(U)",
    deathsMale: "Deaths(M)",
    deathsFemale: "Deaths(F)",
    deathsUnsexed: "Deaths(U)",
    closingBalanceMale: "Closing Balance(M)",
    closingBalanceFemale: "Closing Balance(F)",
    closingBalanceUnsexed: "Closing Balance(U)",

    pickupDate: "Pickup Date",
    zooInventory: "Zoo Inventory",
    m: "M",
    f: "F",
    u: "U",
    smallPetIncineratorReport: "Small Pet Incinerator Report",
    observation: "Observation",
    dailyReport: "Daily Report of Animals",
    scrutinyRemark: "Scrutiny Remark",
    zooKeeperName: `Zoo Keeper's Name`,
    genericReport: "Generic Report",
    licenseStartDate: "License Start Date",
    licenseEndDate: "License End Date",
    animalDetails: "Animal Details",
    vaccinationDetails: "Vaccination Details",
    injectionExpiryDate: "Injection Expiry Date",
    vaccinationDose: "Vaccination Dose",
    vaccinationHistoryDetails: "Vaccination History Details",
    vaccinationDueDate: "Due Date of Vaccination",
    dailyReportOfZooKeeper: "Daily Report Of Animals",

    opdRegistrations: "Veterinary Dispensary Registrations",
    ipdRegistrations: "IPD Shelter Registrations",
    entry: "Entry",
    supervisor: "Supervisor",
    ipdHeading: "TREATING SICK AND INJURED ANIMAL THROUGH IPD SHELTER",
    opdHeading:
      "TREATING SICK AND INJURED ANIMAL THROUGH VETERINARY DISPENSARY",

    //Payment Gateway Labels
    yourPaymentDoneSuccess: " Your payment is successful!!!",
    paymentFailed: "Payment failed!!!",
    orderId: "Order Id ",
    trackingId: "Tracking Id",
    bankRefNo: "Bank Reference No",
    billingName: "Billing Name",
    billingAdd: "Billing Address",
    billingCity: "Billing City",
    billingZip: "Billing Zipcode ",
    billingCountry: "Billing Country",
    billingEmail: "Billing E-mail",
    billingState: "Billing State",
    goToList: "Go To List",
    loiNo: "LOI No",

    renewalPetLicense: "Renewal of Pet License",
    veterinaryOfficer: "Veterinary Officer",

    viewLess: "View Less",
    viewMore: "View More",

    vetDoc: "Veterinary Doctor",
    curator: "Curator",
    curatorRemark: `Curator's Comment`,
    animalRescue: "Animal Rescue",
    nameOfInformer: "Name of Informer",
    rescueDateAndTime: "Date and Time of Rescue",
    addressOrLocationOfRescue: "Address or Location of Rescue",
    commonName: "Common Name",
    scientificName: "Scientific Name",
    age: "Age",
    time: "Time",
    rescuerInformation: "Rescuer Information",
    contactNo: "Contact No.",
    rescuerName: "Rescuer Name",
    dateOfRescue: "Date of Rescue",
    timeOfRescue: "Time of Rescue",
    informationOfRescuedAnimal:
      "Information of Rescued Bird/Animal/Reptile/Other",
    sex: "Sex",
    weight: "Weight",
    conditionOnArrival: "Condition on arrival",
    prognosis: "Prognosis",
    postMortemReport: "Post-Mortem Report",
    personalName: "Personal Name",
    dateOfBirth: "Date of Birth",
    timeOfBirth: "Time of Birth",
    placeOfBirth: "Place of Birth",
    animalDescription: "General description of animal",
    historyOfIllness: "History of illness",
    shortHistoryOfIllness: "Short history of illness",
    yes: "Yes",
    no: "No",
    yesThen: "If yes, then",
    organWiseDescription: "Organ Wise Description",
    headAndNeck: "Head and Neck",
    thoraxAndThoracicCavity: "Thorax and Thoracic Cavity",
    abdomenAndAbdominalCavity: "Abdomen and Abdominal Cavity",
    pelvicGirdle: "Pelvic Girdle",
    limbs: "Limbs",
    otherExaminationOrObservation: "Any Other Examination/Observation",
    biologicalTests: `Biological Tests done (if any)`,
    biologicalTestsDone: `Biological Tests done`,
    blood: "Blood",
    urine: "Urine",
    discharge: "Discharge",
    biopsy: "Biopsy",
    opinionIfAny: "Opinion (if any)",
    disposalInstruction: "Instructions for Disposal",
    doctorComment: `Doctor's Comment`,
    speciesName: "Species Name",
    addressProof: "Address Proof",
    timeOfDeath: "Time of Death",
    placeOfDeath: "Place of Death",

    dateOfPostMortem: "Date of Post-Mortem",
    timeOfPostMortem: "Time of Post-Mortem",
    fileType: "Type of File",
    beforeAfter: "Before / After",
    file: "File",
    fileUpload: "File Upload",
    postMortemImage: "Post-Mortem Image",
    animalHistoryCard: "Animal History Card",
    order: "Order",
    family: "Family",
    houseName: "House Name",
    identificationMark: "Identification Mark",
    dateAcquiredOrReceived: " Date of Acquired/Received",
    animalStockOrRegisterNo: "Animal stock or register no.",
    pageNo: "Page no.",
    studbookNo: "Studbook no.",
    whereKept: "Where kept",
    acquisitionDetails: "Acquisition Details",
    dateOfAcquisition: "Date of Acquisition",
    acquirerName: `Acquirer's Name`,
    acquirerAddress: `Acquirer's Address`,
    acquisitionMode: "Acquisition Mode",
    animalGeneralCondition: "Animal's general condition",
    quarantineData: `Quarantine's Data`,
    arrivalDate: "Arrival Date",
    testsConducted: "Tests Conducted",
    temperature: "Temperature",
    fecal: "Fecal",
    pathological: "Pathological",
    testResult: "Test Result",
    recordDetails:
      "Record of observations regarding behaviour, reproduction, health, treatment, etc",
    disposal: "Disposal",
    exchanged: "Exchanged",
    sold: "Sold",
    donated: "Donated",
    breedingLoan: "Breeding Loan",
    death: "Death",
    disposalDate: "Disposal Date",
    disposerName: `Disposer's Name`,
    disposerAddress: `Disposer's Address`,
    causeOfDeath: "Cause of Death",
    postmortemFindings: "Post Mortem Findings",
    postMortemReportNo: "Post Mortem Report No.",
    carcassDisposal: "Disposal of Carcass",
    burial: "Burial",
    cremation: "Cremation",
    organRemoved: "Organ Removed",
    organDonationDetails:
      "Whether any organ or parts given to museum, education institution, if so, name and address of person/agency/institution and mode of transaction (donation or sold)",
    familyNameEn: "Animal Family Name (in English)",
    familyNameMr: "Animal Family Name (in Marathi)",
    familyMaster: "Animal Family Master",

    microchipNo: "Microchip No.",
    size: "Size",
    dateTimeAndPlaceOfDeath: "Date, Time and Place of Death",
    dataNotFound: "Data not Found",
    place: "Place",

    //buttons
    add: "Add",
    save: "Save",
    update: "Update",
    clear: "Clear",
    cancel: "Cancel",
    exit: "Exit",
    back: "Back",
    saveAndNext: "Save & Next",
    finish: "Finish",
    print: "Print",

    pdfOnly: "(Upload PDF only)",
    imageOnly: "(Upload image only)",
    fileSizeImageOnly: "(Upload image only. Size less than 10 MB)",
    imageAndPDF: "(Upload image or PDF only)",

    //acknowledgement
    acknowledgment: "Acknowledgement",
    applicationDetails: "Application Details",
    dear: "Dear",
    thanksForUsingPCMCservice: `Thanks for using Pimpri-Chinchwad Municipal Corporation's citizen service`,
    applicationSubmittedline1: `Your application for`,
    applicationSubmittedline2: `has been successfully submitted under Pimpri-Chinchwad Municipal Corporation citizen service`,
    applicantName: "Applicant Name",
    applicantAddress: "Applicant Address",
    contactForQueries:
      "If any queries, please contact the respective department",
  },
  mr: {
    petLicense: "पाळीव प्राणी परवाना",
    petAnimal: "पाळीव प्राणी",
    area: "क्षेत्र",
    zone: "झोन",
    ward: "प्रभाग",
    flatOrHouseNo: "फ्लॅट/घर क्र.",
    buildingName: "इमारतीचे नाव",
    detailAddress: "पूर्ण पत्ता",
    ownerName: "मालकाचे नाव",

    fNameEn: "प्रथम नाव (इंग्रजीत)",
    mNameEn: "मधलं नाव (इंग्रजीत)",
    lNameEn: "आडनाव (इंग्रजीत)",
    fNameMr: "प्रथम नाव (मराठीत)",
    mNameMr: "मधलं नाव (मराठीत)",
    lNameMr: "आडनाव (मराठीत)",

    mobileNo: "मोबाईल नं",
    emailId: "ईमेल आयडी",
    petName: "पाळीव प्राण्याचे नाव",
    petBirthdate: "पाळीव प्राण्याची जन्मतारीख",
    animalBreed: "प्राण्याची जाती",
    animalColor: "प्राण्याचा रंग",
    animalAge: "प्राण्याचं वय (YY:MM मध्ये)",
    animalWeight: "प्राण्याचं वजन (किलोग्राम मध्ये)",
    animalGender: "प्राण्याचं लिंग",
    antiRabiesVaccinationStatus: "रेबीज प्रतिबंधक लसीकरण स्थिती",
    vaccinationDate: "लसीकरणची तारीख",
    veterinaryDoctorsName: "पशुवैद्यकीय डॉक्टरांचे नाव",
    documents: "कागदपत्रे",
    vaccinationPDF: "लसीकरणाची PDF",
    animalPhoto: "प्राण्याचा फोटो",
    remark: "शेरा",
    status: "अर्ज स्थिती",
    petAnimalEn: "पाळीव प्राण्याचे (इंग्रजीत नाव)",
    petAnimalMr: "पाळीव प्राण्याचे (मराठीत नाव)",
    petBreed: "पाळीव प्राण्याची जाती",
    breedNameEn: "जातीचं नाव (इंग्रजीत)",
    breedNameMr: "जातीचं नाव (मराठीत)",
    ownerPhotoID: "मालकाचा ओळख पुरावा",
    makePayment: "पैसे भरा",
    generateLicense: "परवाना निर्मिती",
    viewLicense: "परवाना पहा",
    licenseFor: "कुठल्या पाळीव प्राण्यासाठी",
    pcmc: "पिंपरी चिंचवड महानगरपालिका",
    fiscalYear: "सन",
    officeCopy: "कार्यालयाची प्रत",
    customerCopy: "ग्राहकाची प्रत",
    receiptNo: "पावती क्र.",
    date: "तारीख",
    relatedTo: "विभागाकडून",
    cfcRefNo: "सीएफसी संदर्भ क्रं",
    cfcCounterNo: "सीएफसी काउंटर क्रं",
    receivedFrom: "कडून प्राप्त झाले",
    serviceName: "सेवेचे नाव",
    narration: "विवरण",
    address: "पत्ता",
    paymentMode: "देय प्रकार",
    rupees: "रुपये",
    chequeNo: "धनादेश क्रं.",
    chequeDate: "धनादेश क्रं",
    bankName: "बँकेचे नाव",
    referenceNo: "संदर्भ क्रं.",
    applicationDate: "अर्जाची तारीख",
    details: "तपशील",
    payableAmount: "देय रक्कम",
    receivedAmount: "स्वीकारलेली रक्कम",
    rebateAmount: "सूट/सवलत रक्कम",
    advanceAmount: "आगाऊ रक्कम",
    actualPayableAmount: "एकूण देय रक्कम",
    totalAmount: "एकूण रक्कम",
    amountInWords: "एकूण रक्कम शब्दांमध्ये",
    receiverSignature: "स्वीकारनाऱ्याची स्वाक्षरी",
    tip: "टीप",
    printBy: "छापनार्याचे नाव",
    printDateAndTime: "छापतांना तारीख आणि वेळ",
    casePaperNo: "केसपेपर क्र.",
    licenseNo: "परवाना क्र.",
    ownerAddress: "मालकाचा पत्ता",
    symptoms: "इतिहास आणि लक्षणे",
    aknowledgementSlipNo: "पोच पावती क्र. (क्रमांक)",
    diagnosisDetail: "तात्पुरते निदान तपशील",
    medicineDetails: "औषध तपशील",
    treatment: "उपचार",
    paymentGateway: "पेमेंट गेटवे",
    payment: "पैसे भरणे",
    payerName: "देयकाचे नाव",
    payerAddress: "देयकाचा पत्ता",
    receiptDate: "पावतीची तारीख",
    transactionDate: "ट्रांसकशनची तारीख",
    treatmentCategory: "उपचार श्रेणी",
    casePaperDate: "केस पेपरची तारीख",
    accountGlCode: "जीएल खात्याचा कोड",
    opd: "पशुवैद्यकीय दवाखाना",
    lattitude: "अक्षांश",
    longitude: "रेखांश",
    city: "शहर",
    state: "राज्य",
    pincode: "पिनकोड",
    amount: "रक्कम (रुपये मध्ये)",
    paymentType: "पैसे भरण्याची पध्दत",
    cfcCode: "सीएफसी कोड",
    ddNo: "डिमांड ड्राफ्ट क्र",
    ddDate: "डिमांड ड्राफ्टची तारीख",
    branchName: "शाखेचे नाव",
    ifscCode: "आयएफएससी कोड",
    accountNo: "खाते क्रमांक",
    caseEntry: "केस एंट्री",
    oldLicense: "जुनं परवाना",
    fromDate: "या तारखेपासून",
    toDate: "या तारखेपर्यंत",
    officeType: "कार्यालयाचा प्रकार",
    opdPrefix: "पशुवैद्यकीय दवाखानाचा उपसर्ग",
    opdNo: "पशुवैद्यकीय दवाखानाचा क्रमांक",
    opdName: "पशुवैद्यकीय दवाखानाचे नाव",
    opdOpeningTime: "पशुवैद्यकीय दवाखाना उघडण्याची वेळ",
    opdClosingTime: "पशुवैद्यकीय दवाखाना बंद होण्याची वेळ",
    opdWorkingDays: "पशुवैद्यकीय दवाखानाचे कामाचे दिवस",
    labFacility: "प्रयोगशाळा सुविधा",
    xRayFacility: "क्ष-किरण सुविधा",
    opdAddress: "पशुवैद्यकीय दवाखानाचा पत्ता",
    flatOrBuildingNo: "फ्लॅट/इमारत क्र.",
    roadName: "रस्त्याचं नाव",
    landmark: "महत्त्वाची खूण",
    ipdPrefix: "आंतररुग्ण विभाग निवाराचा उपसर्ग",
    ipdNo: "आंतररुग्ण विभाग निवाराचा क्रमांक",
    ipdName: "आंतररुग्ण विभाग निवाराचे नाव",
    ipdOpeningTime: "आंतररुग्ण विभाग निवाराची उघडण्याची वेळ",
    ipdClosingTime: "आंतररुग्ण विभाग निवाराची बंद होण्याची वेळ",
    ipdWorkingDays: "आंतररुग्ण विभाग निवाराचे कामाचे दिवस",
    ipdAddress: "आंतररुग्ण विभाग निवाराचा पत्ता",
    defineIpd: "आंतररुग्ण विभाग निवारा",
    defineOpd: "पशुवैद्यकीय दवाखाना",
    totalApplications: "एकूण अर्जदार",
    paidApplications: "पैसे भरलेले अर्जदार",
    unpaidApplications: "पैसे न भरलेले अर्ज",
    approved: "एकूण मंजूर परवाना",
    reassigned: "एकूण रद्द परवाना",
    pending: "प्रलंबित अर्ज",
    underTreatment: "उपचाराधीन",
    dead: "मृत",
    released: "सोडले",
    fileName: "फाईलचे नाव",
    mandatoryOrOptional: "अनिवार्य/पर्यायी",
    mandatory: "अनिवार्य",
    optional: "पर्यायी",
    uploadWarning:
      "कृपया १०MB पेक्षा कमी आकाराची फाइल (PDF/JPG/JPEG/PNG) अपलोड करा !",
    medicine: "औषध",
    medicineOrInjection: "औषध/इंजेक्शन",
    days: "दिवस",
    dosage: "डोस",
    addMedicine: "औषध जोडा",
    prescription: "पावती",
    casePaperReceipt: "केस पेपर पावती",
    smallPetIncinerator: "लहान पाळीव प्राण्याचा अंतिम संस्कार",
    applicationNo: "अर्ज क्रमांक",

    search: "शोधा",
    preview: "पूर्वावलोकन",
    addFile: "फाइल जोडा",
    srNo: "अनु क्र",
    actions: "क्रिया ",
    approve: "मंजूर",
    reassign: "पुन्हा नियुक्त करा",
    agreeAndNext: "सहमत आणि पुढे",

    yearMaster: "वर्ष मास्टर",
    year: "वर्ष",
    yearEn: "वर्ष (इंग्रजी मध्ये)",
    yearMr: "वर्ष (मराठी मध्ये)",
    yearPrefix: "वर्ष उपसर्ग",

    licenseType: "परवाना प्रकार",
    vms: "पशुवैद्यकीय व्यवस्थापन प्रणाली",
    summaryCollectionReport: "सारांश संग्रह अहवाल",
    animalType: "प्राण्याचा प्रकार",
    newLicense: "नवीन परवाना",
    renewedLicense: "नूतनीकरण केलेले परवाना",
    count: "संख्या",
    feeCollected: "शुल्क गोळा केले",
    totalFeeCollected: "एकूण शुल्क गोळा केले",
    detailCollection: "तपशील संकलन",
    detailCollectionReport: "तपशील संकलन अहवाल",
    grandTotal: "गोळाबेरीज",
    monthlyReport: "मासिक अहवाल",
    yearlyReport: "वार्षिक अहवाल",
    month: "महिना",

    animalPhotoOne: "प्राण्याचा फोटो १",
    animalPhotoTwo: "प्राण्याचा फोटो २",
    animalPhotoThree: "प्राण्याचा फोटो ३",
    reasonForPickUp: "आणण्याचे कारण",
    teamName: "संघाचे नाव",
    volunteerName: "स्वयंसेवक नाव",
    teamOrVolunteer: "संघ / वयंसेवक",
    dateOfDeath: "मृत्यूची तारीख",
    deathCertificate: "मृत्यु प्रमाणपत्र",
    dateOfRelease: "सोडण्याची तारीख",
    healthCertificate: "आरोग्य प्रमाणपत्र",
    kennelNo: "कुत्र्याचे घर क्रं",
    specialInvestingationDescription: "विशेष तपास वर्णन",
    specialInvestingationDocument: "विशेष तपास दस्तऐवज",
    noSpecialInvestigationDocumentAttached:
      "कोणतेही विशेष तपास दस्तऐवज संलग्न केलेले नाही",
    complainerName: `तक्रारकर्त्याचे नाव`,
    complainerAddress: `तक्रारदाराचा पत्ता`,
    complainerMobileNo: `तक्रारदाराचा मोबाईल क्र.`,
    opdTitle: "आजारी व जखमी जनावरांवर पशुवैद्यकीय दवाखान्यातून उपचार करणे",
    twentyRs: "₹ २०.००",
    twentyRsWords: "वीस रुपये फक्त",
    casePaperFee: "केसपेपर शुल्क",
    new: "नवीन",
    existing: "विद्यमान",
    petRegistrationStatus: "पाळीव प्राणी नोंदणी स्थिती",
    paymentTable: "पेमेंट टेबल",
    specialDoc: "विशेष दस्तऐवज",
    caseDetails: "केस तपशील",
    caseHistory: "केस इतिहास",
    noCaseHistory: "केस इतिहास आढळला नाही",

    dateWiseIssuedLicenseExpiry:
      "दिनांकानुसार जारी केलेल्या परवानाचा कालबाह्य अहवाल",
    dateWiseRenewedLicenseExpiry:
      "दिनांकानुसार नूतनीकरण केलेल्या परवानाचा कालबाह्य अहवाल",
    petLicenseReport: "पाळीव प्राणी परवाना अहवाल",
    renewedPetLicenseReport: "नूतनीकरण केले पाळीव प्राणी परवाना अहवाल",
    ipdOrOpdReport: "आंतररुग्ण विभाग निवाराचा किंवा ओपीडी अहवाल",
    departmentType: "विभागाचा प्रकार",

    //Class Master
    class: `प्राणी वर्गीकरण`,
    classNameEn: `प्राणी वर्गीकरण (इंग्रजीत)`,
    classNameMr: `प्राणी वर्गीकरण (मराठीत)`,
    classMaster: `प्राणी वर्गीकरणाच मास्टर`,

    // Type of Vaccine Master
    typeOfVaccine: `लसीकरणाचा प्रकार`,
    typeOfVaccineEn: `लसीकरणाचा प्रकार (इंग्रजीत)`,
    typeOfVaccineMr: `लसीकरणाचा प्रकार (मराठीत)`,
    typeOfVaccineMaster: `लसीकरणाचा प्रकाराचा मास्टर`,

    // Vaccine Used Master
    vaccineUsed: `लसचे नाव`,
    vaccineUsedEn: `लसचे नाव (इंग्रजीत)`,
    vaccineUsedMr: `लसचे नाव (मराठीत)`,
    vaccineUsedMaster: `लसचे नाव मास्टर`,

    // Route of Injection Master
    routeInjection: `प्रशासनाचा मार्ग`,
    routeInjectionEn: `प्रशासनाचा मार्ग (इंग्रजीत)`,
    routeInjectionMr: `प्रशासनाचा मार्ग (मराठीत)`,
    routeInjectionMaster: `प्रशासनाच्या मार्गाचा मास्टर`,

    // Vaccination Report (Transaction)
    vaccinationReport: `टीका अहवाल`,
    vaccinationReportOpdKey: `पशुवैद्यकीय दवाखान्याचा नंबर`,
    vaccinationReportDate: `टीका दिनांक`,
    vaccinationReportType: `टीका प्रकार`,
    vaccinationReportVaccine: `वापरलेला टीका`,
    vaccinationReportDose: `डोस`,
    vaccinationReportRoute: `इंजेक्शनचा मार्ग`,
    vaccinationReportInjectionExpiry: `इंजेक्शनचा कालबाह्य अहवाल`,
    vaccinationReportVaccinationDueDate: `टीका देण्याची तारीख`,

    //schedule Master
    schedule: "अनुसूची श्रेणी",
    scheduleEn: `अनुसूची श्रेणी (इंग्रजीत) `,
    scheduleMr: `अनुसूची श्रेणी (मराठीत)`,
    scheduleMaster: `अनुसूची श्रेणी मास्टर`,

    //Zoo Animal Master
    zooAnimalMaster: "प्राणीसंग्रहालयातील प्राणीचा मास्टर",
    animalName: `प्राण्याचे नाव`,
    animalNameEn: `प्राण्याचे नाव (इंग्रजी मध्ये)`,
    animalNameMr: `प्राण्याचे नाव (मराठी मध्ये)`,

    //Animal Inventory
    male: "पुरुष",
    female: "स्त्री",
    unsexed: "अलिंग",
    total: "एकूण",
    animalInventory: "प्राणी यादी",
    zooAnimal: "प्राणीसंग्रहालयातील प्राणी",
    dateOfEntry: "प्रवेशाची तारीख",
    openingBalance: "ओपनिंग बॅलन्स",
    births: "जन्म",
    acquisitions: "संपादन",
    disposals: "विल्हेवाट: ",
    deaths: "मृत्यू",
    closingBalance: "अंतिम शिल्लक",
    openingBalanceMale: "ओपनिंग बॅलन्स(M)",
    openingBalanceFemale: "ओपनिंग बॅलन्स(F)",
    openingBalanceUnsexed: "ओपनिंग बॅलन्स(U)",
    birthMale: "जन्म(M)",
    birthFemale: "जन्म(F)",
    birthUnsexed: "जन्म(U)",
    acquisitionMale: "संपादन(M)",
    acquisitionFemale: "संपादन(F)",
    acquisitionUnsexed: "संपादन(U)",
    disposalsMale: "विल्हेवाट(M)",
    disposalsFemale: "विल्हेवाट(F)",
    disposalsUnsexed: "विल्हेवाट(U)",
    deathsMale: "मृत्यू(M)",
    deathsFemale: "मृत्यू(F)",
    deathsUnsexed: "मृत्यू(U)",
    closingBalanceMale: "अंतिम शिल्लक(M)",
    closingBalanceFemale: "अंतिम शिल्लक(F)",
    closingBalanceUnsexed: "अंतिम शिल्लक(U)",

    pickupDate: "आणले तेव्हाची तारीख",
    zooInventory: "प्राणीसंग्रहालय यादी",
    m: "पु",
    f: "स्त्री",
    u: "इ",
    smallPetIncineratorReport: "लहान पाळीव प्राण्याचा अंतिम संस्कारचा अहवाल",
    observation: "निरीक्षण",
    dailyReport: "प्राण्यांचा दैनिक अहवाल",
    scrutinyRemark: "छाननीचा शेरा",
    zooKeeperName: "प्राणीसंग्रहालयाच्या रक्षकाचे नाव",
    genericReport: "सामान्य अहवाल",
    licenseStartDate: "परवाना सुरू तारीख",
    licenseEndDate: "परवाना समाप्त तारीख",
    animalDetails: "प्राण्यांचे तपशील",
    vaccinationDetails: "लसीकरण तपशील",
    injectionExpiryDate: "इंजेक्शन कालबाह्यता तारीख",
    vaccinationDose: "लसीकरण डोस",
    vaccinationHistoryDetails: "लसीकरण इतिहास तपशील",
    vaccinationDueDate: "लसीकरणाची अंतिम तारीख",
    noVaccinationHistoryFound: "कोणताही लसीकरण इतिहास आढळला नाही",
    dailyReportOfZooKeeper: "प्राण्यांचा दैनिक अहवाल",

    opdRegistrations: "पशुवैद्यकीय दवाखानाचे नोंदणी",
    ipdRegistrations: "आंतररुग्ण विभाग निवाराचे नोंदणी",
    entry: "प्रवेश",
    supervisor: "पर्यवेक्षक",
    ipdHeading:
      "आजारी आणि जखमी प्राण्यांवर आंतररुग्ण विभाग निवारा द्वारे उपचार करणे",
    opdHeading: "आजारी व जखमी जनावरांवर पशुवैद्यकीय दवाखान्यातून उपचार करणे",

    //Payment Gateway Labels
    yourPaymentDoneSuccess: " तुमचे पेमेंट यशस्वी झाले!!!",
    paymentFailed: "पेमेंट अयशस्वी !!!",
    orderId: "ऑर्डर आयडी ",
    trackingId: "ट्रॅकिंग आयडी",
    bankRefNo: "बँक संदर्भ क्र",
    billingName: "बिलिंग नाव",
    billingAdd: "बिलाचा पत्ता",
    billingCity: "बिलिंग शहर",
    billingZip: "बिलिंग पिन कोड ",
    billingCountry: "बिलिंग देश",
    billingEmail: "बिलिंग ईमेल",
    billingState: "बिलिंग राज्य",
    goToList: "सूचीवर जा",
    loiNo: "हेतू पत्र क्र",

    renewalPetLicense: "पाळीव प्राणी परवान्याचे नूतनीकरण",
    veterinaryOfficer: "पशुवैद्यकीय अधिकारी",

    // mobileNo: 'मोबाईल क्र',
    // transactionDate: 'व्यवहाराची तारीख',
    // totalAmount: 'एकूण रक्कम',

    viewLess: "कमी पहा",
    viewMore: "अधिक पहा",

    vetDoc: "पशुवैद्यकीय डॉक्टर",
    curator: "अभिरक्षक",
    curatorRemark: "अभिरक्षकचा शेरा",
    animalRescue: "प्राणी बचाव",
    nameOfInformer: "माहिती देणाऱ्याचे नाव",
    rescueDateAndTime: "बचावाची तारीख आणि वेळ",
    addressOrLocationOfRescue: "बचावाचा पत्ता किंवा स्थान",
    commonName: "सामान्य नाव",
    scientificName: "शास्त्रीय नाव",
    age: "वय",
    time: "वेळ",
    rescuerInformation: "बचावकर्त्याची माहिती",
    contactNo: "संपर्क क्र.",
    rescuerName: "बचावकर्त्याचे नाव",
    dateOfRescue: "बचावाची तारीख",
    timeOfRescue: "बचावाची वेळ",
    informationOfRescuedAnimal:
      "बचावलेले पक्षी/प्राणी/सरपटणारे प्राणी/इतर माहिती",
    sex: "लिंग",
    weight: "वजन",
    conditionOnArrival: "आगमनाची स्थिती",
    prognosis: "रोगनिदान",
    postMortemReport: "मरणोत्तर देह तपासणीचा अहवाल",
    personalName: "वैयक्तिक नाव",
    dateOfBirth: "जन्मतारीख",
    timeOfBirth: "जन्म वेळ",
    placeOfBirth: "जन्मस्थान",
    animalDescription: "प्राण्याचे सामान्य वर्णन",
    historyOfIllness: "आधी कोणताही आजार",
    shortHistoryOfIllness: "आजारपणाचा थोडक्यात इतिहास",
    yes: "Ha",
    no: "Nahi",
    yesThen: "जर होय, तर",
    organWiseDescription: "अवयवानुसार वर्णन",
    headAndNeck: "डोके आणि मान",
    thoraxAndThoracicCavity: "थोरॅक्स आणि थोरॅसिक पोकळी",
    abdomenAndAbdominalCavity: "उदर आणि उदर पोकळी",
    pelvicGirdle: "ओटीपोटाचा कमरपट्टा",
    limbs: "हातपाय",
    otherExaminationOrObservation: "इतर कोणतीही परीक्षा/निरीक्षण",
    biologicalTests: `जैविक चाचण्या केल्या (असल्यास)`,
    biologicalTestsDone: `जैविक चाचण्या केल्यास`,
    blood: "रक्त",
    urine: "मूत्र",
    discharge: "डिस्चार्ज",
    biopsy: "बायोप्सी",
    opinionIfAny: "मत (असल्यास)",
    disposalInstruction: "विल्हेवाट लावण्यासाठी सूचना",
    doctorComment: `डॉक्टरांचा शेरा`,
    speciesName: "प्रजातीचे नाव",
    addressProof: "पत्ता पुरावा",
    timeOfDeath: "मृत्यूची वेळ",
    placeOfDeath: "मृत्यूचे ठिकाण",

    dateOfPostMortem: "मरणोत्तर देह तपासणीची तारीख",
    timeOfPostMortem: "मरणोत्तर देह तपासणीची वेळ",
    fileType: "फाईलचा प्रकार",
    beforeAfter: "आधी/नंतर",

    file: "फाईल",
    fileUpload: "फाइल अपलोड",
    postMortemImage: "मरणोत्तर देह तपासणीचे चित्र",
    animalHistoryCard: "प्राणी इतिहास कार्ड",
    order: "अनुक्रम",
    family: "कुटुंब",
    houseName: "घराचे नाव",
    identificationMark: "ओळख चिन्ह",
    dateAcquiredOrReceived: "अधिग्रहित/प्राप्त झाल्याची तारीख",
    animalStockOrRegisterNo: "जनावरांचा साठा किंवा रजिस्टर क्र.",
    pageNo: "पान क्र.",
    studbookNo: "स्टडबुक क्र.",
    whereKept: "कुठे ठेवले",
    acquisitionDetails: "संपादन तपशील",
    dateOfAcquisition: "संपादनाची तारीख",
    acquirerName: "प्राप्तकर्त्याचे नाव",
    acquirerAddress: `प्राप्तकर्त्याचा पत्ता`,
    acquisitionMode: "संपादन मोड",
    animalGeneralCondition: "प्राण्याची सामान्य स्थिती",
    quarantineData: "अलग ठेवण्याचा डेटा",
    arrivalDate: "पोहोचण्याची तारीख",
    testsConducted: "चाचण्या घेतल्या",
    temperature: "तापमान",
    fecal: "मल",
    pathological: "पॅथॉलॉजिकल",
    testResult: "चाचणी निकाल",
    recordDetails:
      "वर्तन, पुनरुत्पादन, आरोग्य, उपचार इत्यादींसंबंधी निरीक्षणांची नोंद",
    disposal: "विल्हेवाट",
    exchanged: "देवाणघेवाण केली",
    sold: "विकले",
    donated: "दान केले",
    breedingLoan: "प्रजनन कर्ज",
    death: "मृत्यू",
    disposalDate: "विल्हेवाटीची तारीख",
    disposerName: `विल्हेवाट लावनाऱ्याचे नाव`,
    disposerAddress: `विल्हेवाट लावनाऱ्याचा पत्ता`,
    causeOfDeath: "मृत्यूचे कारण",
    postmortemFindings: "शव परिक्षणचे निष्कर्ष",
    postMortemReportNo: "शव परिक्षणचा अहवाल क्र.",
    carcassDisposal: "मृतदेहाची विल्हेवाट लावण्याची पद्धत",
    burial: "पुरणे",
    cremation: "अंत्यसंस्कार",
    organRemoved: "अवयव काढले",
    organDonationDetails:
      "संग्रहालय, शिक्षण संस्था यांना दिलेले कोणतेही अवयव किंवा भाग, तसे असल्यास, व्यक्ती/संस्था/संस्थेचे नाव आणि पत्ता आणि व्यवहाराची पद्धत (देणगी किंवा विक्री)",
    familyNameEn: "प्राणीच्या कुटुंबाचे नाव (इंग्रजीमध्ये)",
    familyNameMr: "प्राणीच्या कुटुंबाचे नाव (मराठीत)",
    familyMaster: "प्राण्यांच्या कुटुंबाचा मास्टर",

    microchipNo: "मायक्रोचिप क्र.",
    size: "आकार",
    dateTimeAndPlaceOfDeath: "तारीख, वेळ आणि मृत्यूची जागा",
    dataNotFound: "माहिती सापडला नाही",
    place: "जागा",

    //buttons
    add: "जोडा",
    save: "जतन करा",
    update: "अद्यायावत करा",
    clear: "रिक्त",
    cancel: "रद्द करा",
    exit: "बाहेर पडा",
    back: "मागे",
    saveAndNext: "जतन करा आणि पुढे",
    finish: "समाप्त",
    print: "छापणे",
    pdfOnly: "(फक्त PDF अपलोड करा)",
    imageOnly: "(फक्त चित्र अपलोड करा)",
    fileSizeImageOnly: "(१० MB मध्ये मावणारे चित्र अपलोड करा)",
    imageAndPDF: "(फक्त चित्र किंवा PDF अपलोड करा)",

    //acknowledgement
    acknowledgment: "पोच पावती",
    applicationDetails: "अर्जाचा तपशील",
    dear: "प्रिय",
    thanksForUsingPCMCservice: `पिंपरी-चिंचवड महापालिकेची नागरिक सेवा वापरल्याबद्दल धन्यवाद`,
    applicationSubmittedline1: `पिंपरी-चिंचवड महानगरपालिका नागरिक सेवेअंतर्गत तुमचा`,
    applicationSubmittedline2: `अर्ज यशस्वीरित्या सादर झाला आहे.`,
    applicantName: "अर्जदाराचे नाव",
    applicantAddress: "अर्जदाराचे पत्ता",
    contactForQueries: "काही शंका असल्यास, कृपया संबंधित विभागाशी संपर्क साधा",
  },
};
