export default [
  {
    lang: "en",

    module: "Legal Case Management System",
    formType: "masters",
    master: "Masters",
    transaction: "Transactions",
    report: "Reports",

    masterPath: "Legal Case / Master ",
    transactionPath: "Legal Case / Transaction ",

    courtPath: "Legal Case / Master /Court",
    advocatePath: "Legal Case / Master /Advocate",
    serviceHierachyPath: "Legal Case / Master / Service Hierachy",
    caseTypePath: "Legal Case/ Master / Case Type",
    caseSubTypePath: "Legal Case / Master / Case Sub Type",
    caseStagesPath: "Legal Case/ Master / Case Type",
    employeeAndUserCreationPath:
      "Legal Case / Master / Employee and User Creation",
    counterSchedulingPath: "Legal Case / Master / Counter Scheduling",
    smsEmailWhatsAppTemplatesPath:
      "Legal Case / Master / SMS / Email/WhatsApp Templates",
    userAuthenticationAndRoleRightsPath:
      "Legal Case / Master / User Authentication and Role-Rights",
    changeResetForgetPasswordPath:
      "Legal Case / Master / Change or Reset or ForgetPassword",
    calendarSchedulingPath: "Legal Case / Master / Calendar Scheduling",

    //label title
    court: "Court",
    advocate: "Advocate",
    serviceHierachy: "Service Hierarchy",
    caseType: "Case type",
    caseSubType: "Case Sub-Type",
    caseStages: "Case-Stage",
    employeeAndUserCreation: "Employee and User Creation",
    counterScheduling: " Counter Scheduling",
    smsEmailWhatsAppTemplates: " SMS / E-mail / Whatsapp Template",
    userAuthenticationAndRoleRights: " User Authentication and Role Rights",
    changeResetForgetPassword: "Change / Reset / Forget Password",
    calendarScheduling: " Calender Scheduling",

    //other labels
    complaintType: "Subject/Complaint Type *",
    complaintSubType: "Complaint Sub Type *",
    status: "Status *",
    mediaName: "Media Name *",
    mediaPrefix: "Prefix *",
    remark: "Remark",
    eventType: "Event Type",
    eventDate: "Event Date *",
    alertDateTime: "Alert Date & Time *",
    description:'Description',
    courtName: "Court Name *",
    address: "Address *",
    roadName: "Road Name *",
    landmark: "Landmark *",
    cityOrVillage: "City / Village *",
    pincode: "Pincode *",
    area: "Area *",
    name: "Name *",
    mobile: "Mobile No. *",
    phone: "Phone No. *",
    email: "E-mail *",
    aadharNo: "Aadhar No. *",
    panNo: "Pan No. *",
    advocateCreation: "Advocate Created Successfully",
    advocateDetails: "Advocate Details",
    bankDetails: "Bank Details",
    documentUpload: "Document Upload",
    title: "Title *",
    fname: "First Name *",
    mname: "Middle Name *",
    lname: "Last Name *",
    advocateCategory: "Advocate Category *",
    nameOfBarCouncil: "Name Of Bar Council *",
    remarks: "Remarks *",
    bankName: "Bank Name *",
    branchName: "Branch Name *",
    accountNo: "Account No. *",
    bankIFSC: "Bank IFSC code *",
    bankMICR: "Bank MICR code *",
    application: "Application:",
    aadharCard: "Aadhar Card:",
    panCard: "Pan Card:",
    barCouncilCertificate: "Bar Council Certificate:",
    bankPassbook: "Bank Passbook:",

    //Remarks
    selectDate: "Please select a date",
    selectTitle: "Please select a title",
    enterFName: "Please enter first name ",
    enterMName: "Please enter middle name ",
    enterLName: "Please enter last name ",
    selectAdvocateCategory: "Please select a category",
    enterCouncilName: "Please enter council name",
    enterArea: "Please enter area ",
    enterRoadName: "Please enter road name ",
    enterLandmark: "Please enter a landmark ",
    enterCity: "Please enter a city ",
    enterPinCode: "Please enter a pincode ",
    enterPhoneNo: "Please enter a phone no. ",
    enterMobileNo: "Please enter a mobile no. ",
    enterEmailAddress: "Please enter an e-mail. ",
    enteraadhaarNo: "Please enter an aadhaar no. ",
    enterpanNo: "Please enter an pan no. ",
    enterRemarks: "Please enter a remark. ",

    attachFile: "Attach File",
    srNo: "Sr. No",
    actions: "Actions",

    //buttons
    add: "Add",
    save: "Save",
    update: "Update",
    clear: "Clear",
    exit: "Exit",
    back: "Back",
    saveAndNext: "Save & Next",
    finish: "Finish",
  },
  {
    lang: "mr",

    module: "कायदेशीर प्रकरण व्यवस्थापन प्रणाली",
    formType: "masters",
    master: "मास्टर्स",
    transaction: "व्यवहार",
    report: "अहवाल",

    masterPath: "कायदेशीर प्रकरण/ मास्टर ",
    transactionPath: "कायदेशीर प्रकरण/ व्यवहार ",

    courtPath: "कायदेशीर प्रकरण/ मास्टर /न्यायालय",
    advocatePath: "कायदेशीर प्रकरण/ मास्टर /वकील",
    serviceHierachyPath: "कायदेशीर प्रकरण/ मास्टर / सेवा पदानुक्रम",
    caseTypePath: "कायदेशीर प्रकरण/ मास्टर / प्रकरणाचा प्रकार",
    caseSubTypePath: "कायदेशीर प्रकरण/ मास्टर / प्रकरणाचा उप-प्रकार",
    caseStagesPath: "कायदेशीर प्रकरण/ मास्टर / प्रकरण-टप्पे",
    employeeAndUserCreationPath:
      "कायदेशीर प्रकरण/ मास्टर / कर्मचारी आणि वापरकर्ता निर्मिती",
    counterSchedulingPath: "कायदेशीर प्रकरण/ मास्टर / काउंटर शेड्युलिंग",
    smsEmailWhatsAppTemplatesPath:
      "कायदेशीर प्रकरण/ मास्टर / संदेश सेवा / इलेक्ट्रॉनिक संदेश/ व्हॉट्सॲप साचा",
    userAuthenticationAndRoleRightsPath:
      "कायदेशीर प्रकरण/ मास्टर / वापरकर्ता प्रमाणीकरण आणि भूमिका-अधिकार",
    changeResetForgetPasswordPath:
      "कायदेशीर प्रकरण/ मास्टर / बदल किंवा पुनर्प्रस्थापित किंवा पासवर्ड विसरलात",
    calendarSchedulingPath: "कायदेशीर प्रकरण/ मास्टर / दिनदर्शिका शेड्युलिंग",

    //titles
    court: "न्यायालय",
    advocate: "वकील",
    serviceHierachy: "सेवा पदानुक्रम",
    caseType: "प्रकरणाचा प्रकार",
    caseSubType: "प्रकरणाचा उप-प्रकार",
    caseStages: "प्रकरण-टप्पे",
    employeeAndUserCreation: "कर्मचारी आणि वापरकर्ता निर्मिती",
    counterScheduling: " काउंटर शेड्युलिंग",
    smsEmailWhatsAppTemplates:
      " संदेश सेवा / इलेक्ट्रॉनिक संदेश/ व्हॉट्सॲप साचा",
    userAuthenticationAndRoleRights: " वापरकर्ता प्रमाणीकरण आणि भूमिका-अधिकार",
    changeResetForgetPassword:
      "बदल किंवा पुनर्प्रस्थापित किंवा पासवर्ड विसरलात",
    calendarScheduling: " दिनदर्शिका शेड्युलिंग",

    //other labels
    complaintType: "विषय/तक्रारीचा प्रकार *",
    complaintSubType: "तक्रारीचा उप प्रकार *",
    status: "स्थिती *",
    mediaName: "मीडियाचे नाव *",
    mediaPrefix: "मीडिया उपसर्ग *",
    remark: "टिप्पणी",
    eventType: "कार्यक्रमाचा प्रकार *",
    eventDate: "कार्यक्रमाची तारीख *",
    alertDateTime: "सूचना तारीख आणि वेळ *",
    description:'वर्णन',
    courtName: "न्यायालयाचे नाव",
    address: "पत्ता",
    roadName: "रस्त्याचे नाव",
    landmark: "महत्त्वाची खूण",
    cityOrVillage: "शहर / गाव",
    pincode: "पिनकोड",
    area: "क्षेत्राचे नाव",
    name: "नाव",
    mobile: "मोबाईल नं.",
    phone: "दूरध्वनी नं.",
    email: "इलेक्ट्रॉनिक संदेश",
    aadharNo: "आधार नं.",
    panNo: "पॅन नं.",
    advocateCreation: "वकिल यशस्वीपणे तयार केला",
    advocateDetails: "वकील तपशील",
    bankDetails: "बँक तपशील",
    documentUpload: "दस्तऐवज अपलोड",
    title: "शीर्षक *",
    fname: "पहिले नाव *",
    mname: "मधले  नाव *",
    lname: "शेवटचे नाव *",
    advocateCategory: "वकील श्रेणी *",
    nameOfBarCouncil: "वकिलांचे मंडळचे प्रमाणपत्र परिषदचे नाव *",
    remarks: "टिप्पणी *",
    bankName: "बँकेचे नाव *",
    branchName: "शाखेचे नाव *",
    accountNo: "खाता क्रमांक *",
    bankIFSC: "बँक IFSC कोड *",
    bankMICR: "बँक MICR कोड *",
    application: "अर्ज:",
    aadharCard: "आधार कार्ड:",
    panCard: "पॅन कार्ड:",
    barCouncilCertificate: "वकिलांचे मंडळचे प्रमाणपत्र:",
    bankPassbook: "बँक पासबुक:",

    attachFile: "फाईल जोडा",
    srNo: "अनुक्रमांक",
    actions: "क्रिया ",

    //Remarks
    selectDate: "कृपया तारीख निवडा",
    selectTitle: "कृपया शीर्षक निवडा",
    enterFName: "कृपया पहिले नाव भरा ",
    enterMName: "कृपया मधले  नाव भरा ",
    enterLName: "कृपया शेवटचे नाव भरा ",
    selectAdvocateCategory: "कृपया वकील श्रेणी निवडा",
    enterCouncilName: "कृपया वकिलांचे मंडळचे प्रमाणपत्र परिषदचे नाव भरा",
    enterArea: "कृपया क्षेत्राचे नाव भरा ",
    enterRoadName: "कृपया रस्त्याचे नाव भरा ",
    enterLandmark: "कृपया  महत्त्वाची खूण भरा",
    enterCity: "कृपया  शहराचे / गावाचे नाव भरा ",
    enterPinCode: "कृपया पिनकोड भरा",
    enterPhoneNo: "कृपया दूरध्वनी नं. भरा",
    enterMobileNo: "कृपया मोबाईल नं. भरा",
    enterEmailAddress: "कृपया इलेक्ट्रॉनिक संदेश भरा",
    enteraadhaarNo: "कृपया आधार नं. भरा",
    enterpanNo: "कृपया पॅन नं. भरा",
    // enterRemarks: 'कृपया टिप्पणी. भरा',
    enterRemarks: "कृपया टिप्पणी. द्या",

    //buttons
    add: "जोडा",
    save: "जतन करा",
    update: "अद्यायावत करा",
    clear: "रिक्त",
    exit: "बाहेर पडा",
    back: "मागे",
    saveAndNext: "जतन करा आणि पुढे",
    finish: "समाप्त",
  },

  // {
  //   lang: 'en',
  //   formType: 'transaction',
  //   transaction: 'Transactions',
  //   transactionPath: 'Legal Case/ Transaction ',
  // },
  // {
  //   lang: 'mr',
  //   formType: 'transaction',
  //   transaction: 'व्यवहार',
  //   transactionPath: 'कायदेशीर प्रकरण/ व्यवहार ',
  // },
];
