export default {
  en: {
    pcmcName: "Pimpri Chinchwad Municipal Corporation",
    pcmcNameNew: "Pimpri Chinchwad Citizen Service Portal",
    welcomeTo: "WELCOME TO",
    citizen: "CITIZEN",
    department: "DEPARTMENT",
    cfcUser: "CFC USER",
    citizenCred: "Citizen Email Id / Phone Number / Username",
    departmentCred: "User Email Id / Phone Number / Username",
    cfcCred: "CFC User Email Id / Phone Number / Username",
    password: "Password",
    verifyMe: "Verify Me",
    forgotPassword: "Forgot Password?",
    or: "Or",
    dontHaveAnAccount: "Don't have an account?",
    signUpHere: "Sign Up Here",
    login: "Login",
    footer: "© 2024, Developed Under GIS Enabled ERP Project",
    googleMarthiTrans: "Download Google Marathi Translator",
    enterYourRegisteredEmail_PhoneNumber: "Enter your registered Email ID",
    email_phoneNumber: "Email",
    next: "Next",
    enterTheOtpReceivedOnYourEmail_ID:
      "Enter the OTP received on your Email ID",
    verification: "Verification",
    otp: "OTP",
    verify: "Verify",
    resend: "Resend",
    resending: "Resending...",
  },
  mr: {
    pcmcName: "पिंपरी-चिंचवड महानगरपालिका",
    pcmcNameNew: "पिंपरी चिंचवड सिटीझन सर्व्हिस पोर्टल",
    welcomeTo: "आपले स्वागत आहे",
    citizen: "नागरिक",
    department: "विभाग",
    cfcUser: "सीएफसी वापरकर्ता",
    citizenCred: "नागरिक ईमेल / फोन नंबर / वापरकर्तानाव",
    departmentCred: "वापरकर्ता ईमेल / फोन नंबर / वापरकर्तानाव",
    cfcCred: "सीएफसी वापरकर्ता ईमेल / फोन नंबर / वापरकर्तानाव",
    password: "पासवर्ड",
    verifyMe: "माझी पडताळणी करा",
    forgotPassword: "पासवर्ड विसरलात?",
    or: "किंवा",
    dontHaveAnAccount: "खाते नाही?",
    signUpHere: "येथे साइन अप करा",
    login: "लॉगिन करा",
    footer: "© २०२४, जी.आय.एस. सक्षम ई.आर.पी प्रकल्पाअंतर्गत विकसित",
    googleMarthiTrans: "गुगल मराठी अनुवादक डाउनलोड करा",
    enterYourRegisteredEmail_PhoneNumber: "तुमचा नोंदणीकृत ईमेल आयडी",
    email_phoneNumber: "ईमेल",
    next: "पुढे",
    enterTheOtpReceivedOnYourEmail_ID:
      "तुमच्या ईमेल आयडीवर मिळालेला ओटीपी प्रविष्ट करा",
    verification: "पडताळणी",
    otp: "ओटीपी",
    verify: "पडताळणी करा",
    resend: "पुन्हा पाठवा",
    resending: "पुन्हा पाठवत आहे...",
  },
};
