export default {
  BackendMenu: ["DB", "HMS", "LO", "HM"],
  BackendInnerCards: [
    "HMSZ",
    "HMSM",
    "HMS",
    "C-HMSM01",
    "C-HMSM02",
    "C-HMSM03",
    "C-HMSM04",
    "C-HMSM05",
    "C-HMSM06",
    "C-HMSM07",
    "C-HMSM08",
    "C-HMSM09",
    "C-HMSM10",
    "C-HMSM11",
    "C-HMSM12",
    "C-HMSM13",
    "C-HMSM14",
    "C-HMSM14",
    "C-HMSM14",
    "C-HMSM14",
    "HMST",
    "C-HMST01",
    "C-HMST02",
    "C-HMST03",
    "HMSR",
    "C-HMSR1",
  ],
};
